### ISSUE TITLE
How to access local files in workspace from Bazel test

### ISSUE THREAD

**Issue by dxj910804** [bazelbuild/bazel#8321]
### Description of the problem / feature request:

Not able to read a file in local workspace while running Bazel test causing test case failure. 

### Feature requests: what underlying problem are you trying to solve with this feature?

I saw in the bazel directories mainly we have **../bazel/.../execroot/ <a copy of my workspace>**
and **../bazel/.../sandbox/<test files>**. I kind of need to access files in my workspace while running the test cases. A walk around would be get the $TEST_SRCDIR which is a deep path under **../bazel/.../sandbox/<test files>** and then keep tracking back to the copy of my workspace, but it seems to me too "complicated". Is there a better way to this ? 

I have read this page **https://docs.bazel.build/versions/master/build-ref.html#data** and tried to use "data" attribute, I'm still not finding the set of files in sandbox path.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

create a workspace with two bazel layers, in the child layer try to run a test case and in the test case try to access a file within the child directory.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.25.1

###  Have you found anything relevant by searching the web?

https://docs.bazel.build/versions/master/build-ref.html#data

**Comment by Globegitter** [comment]
Data is the attribute one should use for that. Maybe you are not looking at the right location for the file. Bazel will execute at the root of the workspace in the sandbox and if data is a source file e.g. located at `path/to/file` you will also find it in the sandbox at `path/to/file`, i.e. bazel perverse directory structure and in the sandbox. I believe with `--sandbox-debug` you can inspect the sandbox afterwards.

**Comment by dxj910804** [comment]
Yes, I did debug with this flag "--sandbox-debug" on, that's how I conclude in the description " I saw in the bazel directories mainly we have **../bazel/.../execroot/** 
and **../bazel/.../sandbox/**. " and I only find my set of files in execroot not in sandbox. Wondering if there's a way to put it in sandbox ?

**Comment by Globegitter** [comment]
They will end up in the sandbox also. Can you put a minimal example up on github? Otherwise it's impossible to help further at this point.

**Comment by dxj910804** [comment]
Yes you are right, it is in sandbox, I made a mistake. Closing this issue.
