### ISSUE TITLE
Strategies for working around `select` conflicts

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#8323]
In [envoy](https://github.com/envoyproxy/envoy) there are [some features](https://github.com/envoyproxy/envoy/blob/4b0b6540a1c34423813c6a81967cd6656c7b8f05/bazel/BUILD#L88-L111) that can be disabled by consumers using `--defines`. One of these is also disabled based on your platform. This leads us to having [this select](https://github.com/envoyproxy/envoy/blob/4b0b6540a1c34423813c6a81967cd6656c7b8f05/bazel/envoy_build_system.bzl#L655-L661):

```py
def envoy_select_hot_restart(xs, repository = ""):
    return select({
        repository + "//bazel:disable_hot_restart": [],
        repository + "//bazel:apple": [],
        "//conditions:default": xs,
    })
```

The problem is that if you're building on macOS, and also pass `--define=hot_restart=disabled`, you end up with this error:

```
envoy/source/extensions/filters/http/ip_tagging/BUILD:29:1: Illegal ambiguous match on configurable attribute "copts" in //source/extensions/filters/http/ip_tagging:config:
//bazel:disable_hot_restart
//bazel:darwin
Multiple matches are not allowed unless one is unambiguously more specialized.
```

In this case, since we return `[]` either way, we don't really care which one of these conditions matches, just that one does at all.

I've tried a few things:

- Using skylib's [`with_or`](https://github.com/bazelbuild/bazel-skylib/blob/c5852220719bc29fdb256612adc4adde26b30b6c/docs/selects_doc.md#selectswith_or), which produces the same error
- Creating a separate `alias` that contains both of these, hoping it would be resolved differently
- Using `constraint_values` on the `disable_hot_restart` `config_setting` in order to scope a new `config_setting` that could be used instead

I _think_ I could somehow create many `config_setting`s that were constrained to different platforms that were never macOS, but that wouldn't scale well.

Is there a way to work around this?

// @htuch

**Comment by clintharrison** [comment]
I replied on Slack, but I suspect others will find the workaround useful (with all credit to @gregestren of course!):

The alias-chaining approach outlined in https://github.com/bazelbuild/proposals/blob/master/designs/2018-11-09-config-setting-chaining.md should accomplish this instead of `with_or`. This does require creating a new `alias` to these chained `config_setting`s, which doesn't fit super neatly into your model of returning a `select()` like that.

It also appears that https://github.com/bazelbuild/bazel-skylib/pull/89 has not yet been merged, possibly blocked on being able to adequately test it 🙁
An alternative is to "unroll" that implementation:

```
config_setting(
    name = "disable_hot_restart_define",
    values = {"define": "hot_restart=disabled"},
)

alias(
    name = "disable_hot_restart_or_apple",
    values = select({
        ":apple": ":apple",
        "//conditions:default": ":disable_hot_restart_define",
    })
)
```

```
def envoy_select_hot_restart(xs, repository = ""):
    return select({
        repository + "//bazel:disable_hot_restart_or_apple": [],
        "//conditions:default": xs,
    })
```

and I believe this accomplishes what you want 🙂

**Comment by keith** [comment]
Thanks for the help @clintharrison! https://github.com/envoyproxy/envoy/pull/6945

**Comment by gregestren** [comment]
FYI I recently got the go-ahead to integrate the testing for https://github.com/bazelbuild/bazel-skylib/pull/89. So I'm planning to give that another round and try to test & merge over the next few weeks.
