### ISSUE TITLE
CoverageOutputGenerator fails with docker execution

### ISSUE THREAD

**Issue by adamporich** [bazelbuild/bazel#8326]
### Description of the problem:

`bazel coverage //...` fails when running with `spawn_strategy=docker`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have a reproduction repository available at https://github.com/adamporich/bazel_coverage

I did some digging and found that within the execroot the CoverageOutputGenerator seems to be missing it's runfiles. 

i.e. /execroot/__main__/bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator/Main.runfiles seems to be missing

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.25.2

**Comment by benjaminp** [comment]
Probably a duplicate of #4033.

**Comment by hlopko** [comment]
CC @iirina

**Comment by iirina** [comment]
Closing as duplicate of #4033.
