### ISSUE TITLE
repository cache races

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#8327]
The repository cache does not do its file manipulations in atomic fashion, so its readers and writers are potentially vulnerable to races. I don't think this can cause problems within a single Bazel server because the repository cache is protected with `synchronized`. However, races can certainly appear with multiple Bazel servers sharing the same repository cache.

Here's a synthetic example with Bazel 0.25.0:
```
$ truncate --size=1G /tmp/big
$ cat > WORKSPACE
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
http_file(
  name = "big",
  urls = ["file:///tmp/big"],
  sha256 = "a993f8c574e0fea8c1cdcbcd9408d9e2e107ee6e4d120edcfa11decd53fa0cae",
)
$ for i in $(seq 15); do bazel --output_base "/tmp/bazel--$i" build; done
$ for i in $(seq 15); do bazel --output_base "/tmp/bazel--$i" build @big//file & done
```
Generally, at least one of the last Bazel invocations fails with an error like:
```
ERROR: no such package '@big//file': java.io.FileNotFoundException: ~/.cache/bazel/_bazel_benjamin/cache/repos/v1/content_addressable/sha256/a993f8c574e0fea8c1cdcbcd9408d9e2e107ee6e4d120edcfa11decd53fa0cae/file (No such file or directory)
```

**Comment by aehlig** [comment]
Proposed fix (currently under review): https://bazel-review.googlesource.com/c/bazel/+/99890

**Comment by benjaminp** [comment]
Thanks. While I'm on the topic, it would also be nice to remove the TOCTOU races from `RepositoryCache.get()` so that an external process could prune the repository cache. (I can file another issue about this if that's helpful.)
