### ISSUE TITLE
Windows: statically link msvcrt into Bazel

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8328]
### Description of the problem / feature request:

Link msvcrt statically into Bazel.

### Feature requests: what underlying problem are you trying to solve with this feature?

To not require the user installing the VC redistributable DLLs before running Bazel (e.g. msvcrt140.dll).

These DLLs are likely installed for most users because virtually every MSVC-built binary requires them (except the statically linked ones). However these DLLs are not part of the default Windows installation, so both Desktop and Server versions lack them.

It would improve first-time Bazel usage if the user didn't have to install these DLLs before running Bazel.

Prerequisites:

- `@bazel_tools//tools/cpp/runfiles` should have this feature enabled
- sign-off from @meisterT that the size increase (see below) is acceptable

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

0.26.0 rc8

### Any other information, logs, or outputs that you want to share?

As an experimented, I took a033de42e0003542311254bc5266316546cb836e and updated all packages with cc_library and cc_binary deps of Bazel with:

```
package(features = ["static_link_msvcrt"])
```

to link msvcrt statically.

The good news is, it's possible and Bazel works on a clean Windows Server image without the DLLs.

The even better news is, it only adds about 1.5MB to the Bazel binary (46,105,380 bytes vs. 47,611,573 bytes).

**Comment by laszlocsomor** [comment]
FYI @meteorcloudy @hlopko

**Comment by meteorcloudy** [comment]
Sounds like a good deal to me ;)

**Comment by meisterT** [comment]
1.5MB is big, almost ~3.5% of the binary. We were removing many smaller things to reach this size.

Do you have a clue how many users install bazel via chocolatey? Is that the majority? Is it possible to specify a dependency on the DLLs there?

**Comment by laszlocsomor** [comment]
Thanks for the perspective.

https://chocolatey.org/packages/bazel/0.25.1 says Bazel was installed a total of 62k times, but that's all-time download and may or may not include ephemeral installations (e.g. CI systems).
Secondly, with https://github.com/bazelbuild/bazel/pull/7437 we will have a dependency on the msvcrt DLLs. Therefore Chocolatey installs are no concern.

This feature would help those who just download a naked Bazel binary from github or releases.bazel.build. But I have no data on those download numbers.

I agree it's a low-priority feature request, hence P4.
