### ISSUE TITLE
Bazel aborts fetching external repo

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#834]
I did a bazel clean --expunge recently to test that a fresh build worked for another developer, and ran into a weird issue.

This triggered a SHA256 miss-match when downloading.  I debugged that to the file being truncated when it was downloaded.  I deleted the file to trigger a re-download, and it successfully downloaded the full file.

**Comment by bsilver8192** [comment]
With the same misbehaving server as @AustinSchuh and a Bazel from recent master, the file no longer needs to be deleted manually. Doing another `bazel build` attempts to refetch it again. Also, the new error message actually mentions that it's a SHA256 mismatch, which is good.

However, wget detects that the download is truncated without having to rely on a checksum, which Bazel should too. I think Bazel is ignoring getting less bytes from the connection than the Content-Length header sent by the server indicates.

**Comment by damienmg** [comment]
@kchodorow, can you have a look?

**Comment by kchodorow** [comment]
Sure, I'll add a content length check.  I'm downgrading to p2 since we do catch/correct this error now, just not as well as we'd like to.
