### ISSUE TITLE
Ctrl-C doesn't interrupt fetching remote repositories

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#8346]
Reproduction:

```
bazel query -k 'deps(@bazel_tools//...)'
# This starts downloading a lot of things
<Press Ctrl-C>
```

Then observe that the downloads are not stopped. It appears that #1226 regressed?

**Comment by aehlig** [comment]
The reproduction case should be `bazel query -k 'deps(@bazel_tools//...)'`. The fact that `@bazel_tools` is not self-contained is a separate issue.

**Comment by lberki** [comment]
My bad. Let me update the repro instructions.

**Comment by lberki** [comment]
(And yes, that is an issue too, but I figured filing one issue was enough for the day :) )

**Comment by aehlig** [comment]
This is happening in the repository cache; disabling it (by setting `--repository_cache=`, i.e., by setting `repository_cache` to the empty string) will get downloads that get interrupted immediately.
