### ISSUE TITLE
Single threaded C++ link

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#835]
It looks like Bazel is only issuing a single link step on my local machine at a time.  The machine is fast enough that multiple links should be issued at once.  (I've set --local_resources 50000,16,1000)

**Comment by ulfjack** [comment]
Just to clarify - you're saying that this is happening even if you set
local_resources?

Here's the relevant snippet from CppLinkAction:
  // Linking uses a lot of memory; estimate 1 MB per input file, min 1.5
Gib.
  // It is vital to not underestimate too much here,
  // because running too many concurrent links can
  // thrash the machine to the point where it stops
  // responding to keystrokes or mouse clicks.
  // CPU and IO do not scale similarly and still use the static minimum
estimate.
  public static final ResourceSet LINK_RESOURCES_PER_INPUT =
      ResourceSet.createWithRamCpuIo(1, 0, 0);

  // This defines the minimum of each resource that will be reserved.
  public static final ResourceSet MIN_STATIC_LINK_RESOURCES =
      ResourceSet.createWithRamCpuIo(1536, 1, 0.3);

  // Dynamic linking should be cheaper than static linking.
  public static final ResourceSet MIN_DYNAMIC_LINK_RESOURCES =
      ResourceSet.createWithRamCpuIo(1024, 0.3, 0.2);

**Comment by AustinSchuh** [comment]
Correct, this happens if I have set local_resources.  I haven't actually tried it without local_resources set.

I have a bunch of targets which all depend on a library.  When I change the library, it should trigger 20+ links, most of them in parallel.  When I watch what is happening with top, I only see one instance of the linker running at a time.

**Comment by ulfjack** [comment]
Maybe @philwo can take a look, since he is about to make a few changes in this area.

**Comment by AustinSchuh** [comment]
Thanks!  One of my suspicions is that the md5sum calculation done after building an artifact is single-threaded in bazel, and this is causing slowdowns for rules quickly generating large outputs.  If there is some sort of trace that would help you, please let me know.

**Comment by bsilver8192** [comment]
The md5sum calculation is indeed single-threaded. [DigestUtils does it intentionally](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/actions/cache/DigestUtils.java#L117). I can see how that improves performance for HDDs, but it seems like there should be a way to disable or tune it for machines without seek latency.

**Comment by bsilver8192** [comment]
This also makes SkyframeActionExecutor.checkActionCache with a big output file much slower than necessary on my machine (2 hyperthreaded cores and an SSD) because bazel spends a long time pegging a single core calculating the MD5 of the single large file.

**Comment by ulfjack** [comment]
Philipp has been looking at making DigestUtils not single-threaded, but it's tricky as long as we need to support hard drives with spinning platters. :-(

**Comment by AustinSchuh** [comment]
Couldn't you replace the mutex with a semaphore which is initialized to the number of IO units?

**Comment by ulfjack** [comment]
What are IO units?

The problem is that if you have a spinning platter, single-threading gives you the best performance in some scenarios.

**Comment by philwo** [comment]
While I personally would like to just get rid of HDD-specific optimizations and I/O accounting, the less extreme proposal would probably be to somehow detect whether the output_base is on an SSD and tune the available I/O units in the Bazel resource management system accordingly (i.e. set to 1 when running on an HDD, set to infinite when running on an SSD).

Then replace the mutex with a semaphore initialized to the number of available I/O, as @AustinSchuh proposed.

**Comment by ulfjack** [comment]
I think we should add a short-term workaround, e.g., read an environment variable BAZEL_MULTITHREADED_DIGEST, and use that to either disable the lock or turn it into a semaphore. This isn't a good long-term fix, but at least it would reduce the pain a bit.

**Comment by philwo** [comment]
I'll send a CL tomorrow that implements a workaround for this.

**Comment by bsilver8192** [comment]
@AustinSchuh was talking about the IO setting of --local_resources. Seems like using that instead of an environment variable might be a bit nicer to use.

**Comment by ulfjack** [comment]
Yes, a flag would be nicer, but unfortunately the lock is very deep in the
bowels of Bazel in a way that makes it hard to pass a flag there. Otherwise
we could try to auto-detect whether it's an ssd or not.

**Comment by philwo** [comment]
I found a way to do this relatively cleanly via a flag and will send my change for code-review to Ulf.

**Comment by philwo** [comment]
Could you please check if this flag helps and report back? :)

**Comment by AustinSchuh** [comment]
Ok, I finally found some time to test...

bazel build --stamp=no //...
-> 21:58.19

bazel build --stamp=no --experimental_multi_threaded_digest //...
-> 21:37.60

So, improvement!  I was watching top most of the time, and it looks like the sandboxes are holding things back now.  (I would see around 2-4 jobs actually doing work, and 10+ sandboxes starting up)
