### ISSUE TITLE
Tests on Windows without JDK fail when one have /include, /bin or /lib directories [XXX crosses boundary of subpackage '@local_jdk//include']

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#8351]
Bazel fails analysis if you have `/lib`, `/bin` or `/include` folders in your workspace and trying to use tests and JDK is missing and your OS is Windows.

Please kindly look at the example here: https://github.com/excitoon/bazel-issues/tree/master/tests-on-windows-without-jdk

Tested on 0.23.2 and 0.25.2.

**Comment by excitoon** [comment]
@meteorcloudy Could you please take a look at this?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by excitoon** [comment]
Did you reproduce it?
