### ISSUE TITLE
Windows: Improve flexibility of VC++ build tool configuration

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#8353]
- Currently, users can use BAZEL_VC to tell Bazel where to find the VC build tools. But in VS 2017, we can have multiple version of VC build tools installed at the same time, Bazel doesn't provide a way to select the specific version.

- Besides, there are multiple toolchains for different execution and target platforms combinations. For example
```
amd64
amd64_arm
amd64_x86
x86_amd64
x86_arm
```
Currently, Bazel only support building for `amd64`, we should also support others.

**Comment by meteorcloudy** [comment]
Related PR: https://github.com/bazelbuild/bazel/pull/7686

**Comment by laszlocsomor** [comment]
Can we close this?

**Comment by meteorcloudy** [comment]
Not yet, we still don't support compiling for `arm` and `x86` platform.

**Comment by laszlocsomor** [comment]
Thanks. Do you know if anyone is working on it, or planning to?

**Comment by meteorcloudy** [comment]
Yes, I'm planning to do this ;)

**Comment by meteorcloudy** [comment]
Closing due to https://github.com/bazelbuild/bazel/pull/11973
