### ISSUE TITLE
shardcount should be dynamically tunable for RBE builds

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#8354]
We want to build gerrit on GCE/RBE. 

Our major bottleneck is the tests, so for the remote build we would want to shard some tests with (say) shardcount=10. However, for local builds on developer laptops, this will only slow things down. This means that the setting must be controlled from the command line.

Suggestion:
a minimal solution could be 

  --test_shardcount=10

to shard everything 10-way. This is crude, though, because some tests don't benefit from sharding at all, but we could make do by putting --test_shardcount=1 in the checked-in .bazelrc and specifying shardcount=10 in the BUILD.

Another option:

BUILD:
```
  # Determine shardcount based on --test_shardcount and the following setting.
  # if no --test_shardcount=1
  java_test(name = "..",
     maxshards = 10)
```

**Comment by ulfjack** [comment]
How do you know that it will slow down local builds?

Note that some test runners treat no tests in a shard as a failure, but disabling sharding from the command-line might be an option.

**Comment by hanwen** [comment]
it will certainly not speed up our tests, because they're all multithreaded, and we have a shared test server per test class (more shards = more test server setup/teardown.)

**Comment by ulfjack** [comment]
Did you try it? :-p

**Comment by hanwen** [comment]
with RBE , 4 shards

//javatests/com/google/gerrit/acceptance/git:git                         PASSED in 623.6s
  Stats over 4 runs: max = 623.6s, min = 95.2s, avg = 311.0s, dev = 225.5s

without sharding on RBE

//javatests/com/google/gerrit/acceptance/git:git                         PASSED in 850.4s

311 * 4  > 850

and that doesn't even take into account further slowdown due to CPU cache contention.

**Comment by buchgr** [comment]
As mentioned in my e-mail one approach would be to use workers with more cores instead. That would probably be more expensive though.

As for sharding I wonder if we should make it so that Bazel can auto generate a profile (i.e. starlark file) with shard counts for test targets based on a sample run. This profile file could then be used in subsequent runs to automatically set a shard count?

**Comment by hanwen** [comment]
yes, I made 4 CPU workers now, and things are fast enough for RBE to be a interesting option.

I think this is specific to java tests. IIRC, JIT'ing takes up 1-2 extra CPUs even for single-threaded tests.

**Comment by hanwen** [comment]
I guess Java compile similarly should use 4-CPU workers too.

**Comment by buchgr** [comment]
> yes, I made 4 CPU workers now, and things are fast enough for RBE to be a interesting option.

Great! You can also add constraints to particularly compute heavy tests and run those on even beefier workers i.e. bazel runs its determinism test on a 32 core machine.

> I guess Java compile similarly should use 4-CPU workers too.

I think an attractive option would be to build a native image for JavaBuilder/javac and avoid the jitting all together. I believe some folks did this for the scala compiler and that gave them similar performance to local workers.

**Comment by hanwen** [comment]
are native binaries already available in bazel? Where can I learn more about this? I think it might be useful for the test binaries. 

Shouldnt native javac be the default if you use RBE ?

**Comment by buchgr** [comment]
> are native binaries already available in bazel? Where can I learn more about this? I think it might be useful for the test binaries.

No they are not. Afaik folks have been building native binaries using https://www.graalvm.org/.

> Shouldnt native javac be the default if you use RBE ?

Absolutely. We haven't invested time into this yet as it's not the highest priority thing right now.

**Comment by ulfjack** [comment]
*From: *Jakob Buchgraber <notifications@github.com>
*Date: *Thu, May 16, 2019 at 9:14 PM
*To: *bazelbuild/bazel
*Cc: *Ulf Adams, Comment

are native binaries already available in bazel? Where can I learn more
> about this? I think it might be useful for the test binaries.
>
> No they are not. Afaik folks have been building native binaries using
> https://www.graalvm.org/.
>
> Shouldnt native javac be the default if you use RBE ?
>
> Absolutely. We haven't invested time into this yet as it's not the highest
> priority thing right now.
>
Precompiling Java code with GraalVM into a fully native executable
generally results in lower peak performance, so it may be a net loss in
end-to-end build time. It also doesn't support dynamic code loading, which
would prevent you from using annotation processors (they're loaded into the
Javac JVM), so this not likely going to be the default any time soon.
However, there are more options here, and we're only just starting to
explore the space.

**Comment by hanwen** [comment]
That sounds like a no-go. We use AutoValue.

**Comment by buchgr** [comment]
> Precompiling Java code with GraalVM into a fully native executable
generally results in lower peak performance, so it may be a net loss in
end-to-end build time. 

In remote execution you'll never hit peak performance for java compilation.
I don't see how this statement is applicable here.

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem.
