### ISSUE TITLE
Unnecessary dependencies from coverage collection

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#8355]
This is split out from https://github.com/bazelbuild/bazel/issues/6656#issuecomment-492863029

Every `sh_test` depends on the Java and C++ toolchains because of coverage.
Example:
```
sh_test(
    name = "foo",
    srcs = ["foo.sh"],
)
```

While fixing https://github.com/bazelbuild/bazel/issues/5331 the lcov merger was added to every sh_test in https://github.com/bazelbuild/bazel/commit/8fcc07aebb677566de6c53b5ab57f124a840cf60

This pulls in a lot of unnecessary deps, see
```
bazel query  --implicit_deps  'deps(@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main,1)'

@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main
@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:all_lcov_merger_lib
@bazel_tools//tools/launcher:launcher
@bazel_tools//tools/jdk:current_java_toolchain
@bazel_tools//tools/jdk:current_java_runtime
@bazel_tools//tools/jdk:current_host_java_runtime
@bazel_tools//tools/jdk:JacocoCoverageRunner
@bazel_tools//tools/cpp:toolchain
@bazel_tools//tools/cpp:grep-includes
```

That also means you have to install or download the JDK via the external repository to run any sh_test. We should make this conditional.

I have no clue why this depends on the `cpp:toolchain`, cc @hlopko.

**Comment by iirina** [comment]
We can add the `CoverageOutputGenerator` dependency only in coverage mode.

> That also means you have to install or download the JDK via the external repository to run any sh_test. We should make this conditional.

I'm not sure it means that. Bazel will try and download the host JDK because of the Java dependency, but the `sh_test` doesn't require an installed JDK  if it's not executing any java target.
