### ISSUE TITLE
http://bazel.io/docs/skylark/lib/native.html docs should auto-expand native rules

### ISSUE THREAD

**Issue by shaoster** [bazelbuild/bazel#836]
Currently, the presence of native rules like java_binary is inferred only from this sentence:
"A built-in module to support native rules and other package helper functions."
Which makes it very hard to discover from keyword search.

Recommend docgen expanding all native rules so keyword search hits.

**Comment by davidzchen** [comment]
Good idea. I'll take a look at this.

**Comment by helenalt** [comment]
Labeling for Skylark team to review

**Comment by laurentlb** [comment]
I think the documentation is now clearer.
https://docs.bazel.build/versions/3.1.0/skylark/lib/native.html

Please open a new bug if you still have concerns.
