### ISSUE TITLE
//src/test/java/com/google/devtools/build/lib/blackbox/tests/workspace:WorkspaceBlackBoxTest very flaky on CI

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#8365]
I was not able to repro the flakiness locally or with RBE so far, even with 100 runs_per_test.

Next steps:
- disable test
- try to repro in a docker container

**Comment by philwo** [comment]
@meisterT Can you disable the test? I'm trying to repro on a CI VM with Docker.

**Comment by philwo** [comment]
Marking as P0 because all pre- and postsubmits are failing currently.

**Comment by meisterT** [comment]
We fixed the immediate breakage and after syncing, CI should turn green again.

**Comment by meisterT** [comment]
This seems fixed.
