### ISSUE TITLE
Flipping of --incompatible_disallow_load_labels_to_cross_package_boundaries bit broke plugin build in Gerrit Code Review

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#8367]
After Bazel upgrade from 0.24.0 to 0.25.1, that flipped cross package boundaries bit in #6408, load statement doesn't work anymore:

```
$ cat plugins/external_plugin_deps.bzl 
load(":events-log/external_plugin_deps.bzl", events_log = "external_plugin_deps")

def external_plugin_deps():
    events_log()
```
and is failing with:

```
ERROR: Failed to load Starlark extension '//plugins:events-log/external_plugin_deps.bzl'.
It usually happens when the repository is not defined prior to being used.
This could either mean you have to add the '' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or the repository '' was defined too late in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.087s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

All is fine, when `--incompatible_disallow_load_labels_to_cross_package_boundaries=false`  option is passed.

Bundling custom plugins feature in release.war is documented here: https://gerrit-review.googlesource.com/Documentation/dev-build-plugins.html#_bundle_custom_plugin_in_release_war.

To reproduce, clone [gerrit code review](https://gerrit-review.googlesource.com/gerrit), and clone [events-log plugin](https://gerrit-review.googlesource.com/plugins/events-log) into plugins directory in gerrit tree.

Then replace plugins/external_plugin_deps.bzl with the file shown above and run:

```
  $ bazel build :release
```

**Comment by davido** [comment]
@laurentlb @hanwen Could you please have a look?

**Comment by hanwen** [comment]
the load statement

  load(":events-log/external_plugin_deps.bzl", events_log = "external_plugin_deps")

is incorrect "events-log" holds a BUILD file, so this should be something like 

    load("//plugins/events-log:external_plugin_deps.bzl" , ... )

however, the WORKSPACE under the plugin triggers a recursive workspace. 

aehlig suggests to mount the subdir as a `local_repository`. This causes the sub-WORKSPACE to be ignored.

**Comment by davido** [comment]
Thanks.
