### ISSUE TITLE
FR: add sourcepath support to native Java rules

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#8369]
### Description of the problem / feature request:

NB: I'm not familiar with plans, if any, to move Bazel's Java rules to Starlark. Depending on timeline, that might make this request moot.

`java_library` should take a `sourcepath` attribute which translates to `javac`'s `-sourcepath` option. This should be recorded in `JavaInfo.sourcepath` and, for example, passed along to `turbine` when generating header jars.

I cannot just pass `-sourcepath` via `javacopts`, because even though Bazel correctly compiles my library, the sourcepath inputs aren't provided to the action which generates its implicit header jar, and so that action fails.

### Feature requests: what underlying problem are you trying to solve with this feature?

For legacy reasons, I have two codependent jars. B depends on A, but A needs type information which is ultimately compiled into B. The Ant system I'm replacing compiles A using `-sourcepath Bsrcs`.

I imagine this may also apply to the use case described in #2606.

### What operating system are you running Bazel on?

CentOS 6.6

### What's the output of `bazel info release`?

`0.24.1+vmware`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

- https://github.com/bazelbuild/bazel/issues/2606
- https://docs.bazel.build/versions/master/skylark/lib/java_common.html#compile - `java_common.compile` has a `sourcepath` attr. I'm toying with this as a stopgap.

**Comment by iirina** [comment]
There are plans to migrate the Java rules to Starlark, but it will be a long journey across several quarters. Depending what you need, you can try to write a small Starlark rule that uses `java_common.compile` and use it only for the codependent jars.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
