### ISSUE TITLE
worker_verbose flag has no effect

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#837]
According to [the documentation](https://github.com/bazelbuild/bazel/blob/791265874faf26f63093dbcd4476fda9f10e1f32/src/main/java/com/google/devtools/build/lib/worker/WorkerOptions.java), passing this flag should cause messages to be printed when workers are started or shut down. But the flag doesn't seem to have any visible effect for me, even when running with `--experimental_persistent_javac`.

[Glancing at the code](https://github.com/bazelbuild/bazel/search?utf8=%E2%9C%93&q=workerVerbose&type=Code), it looks like this flag is only checked to print some failure reasons. Not sure whether it's supposed to be doing more or if the help text is in error.

**Comment by martine** [comment]
This is making it hard for me to diagnose worker problems.  Any news?

**Comment by philwo** [comment]
I'm on this right now and hope to have a fix in by tomorrow.

**Comment by philwo** [comment]
The fix is in code review now.
