### ISSUE TITLE
GCC and linker errors/warnings hard to read - no colors

### ISSUE THREAD

**Issue by leocnsh** [bazelbuild/bazel#8371]
### Description of the problem / feature request:

When building our project with bazel, it's extremely hard to identify why a build fails due to the nature of the output of bazel. The GCC compiler prints a lot of output onto the console, including errors, warnings and notes.

While the bazel output (ig INFO, FAILED, ...) is colorful, the GCC output is not. We'd appreciate if there were some colors in the output so that it's easier to identify the actual error among the landslide of text output. When using other build systems, the output is colorful, just since switching to bazel we face this issue.

### Feature requests: what underlying problem are you trying to solve with this feature?

Slow debugging due to difficulties identifying what's wrong.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 0.25.0

###  Have you found anything relevant by searching the web?

There are multiple proposals to improve the error message output from 2016. Since it's 2019 now, it's hard to believe that these haven't been realized yet:
https://ci-staging.bazel.build/designs/2016/05/23/beautiful-error-messages.html
https://ci-staging.bazel.build/designs/2016/05/26/implementing-beautiful-error-messages.html

**Comment by benjaminp** [comment]
Pass `-fdiagnostics-color=always` to GCC?

**Comment by leocnsh** [comment]
That works. I added these lines to my .bazelrc to make it default for each build/run:
`build --copt=-fdiagnostics-color=always
run --copt=-fdiagnostics-color=always`

**Comment by leocnsh** [comment]
@benjaminp thank you so much for your tip. By using the ```--copt``` flag to pass ```-fdiagnostics-color=always``` to GCC, I do get colored output, but unfortunately I also prevent bazel remote cache from working correctly: Since other developers might not be using the same copts,  the cache is always cold (from my system's view).

Do you have any ideas how to prevent this? Effectively, the ```-fdiagnostics``` flag just changes the printed output, not the compilation result, and thus I should be able to use the remote cache.

**Comment by hlopko** [comment]
Well, you can convince your peers and your CI to also use colors :) Or setup one CI pipeline that will populate caches for you. 

In general you cannot tell bazel that this option is safe. It's also not so given that adding color is safe, what if my rule saved the compiler output in a file and used the file later in the build for smth?

I'll close this issue now since there's no action item at this point. Feel free to continue the discussion. Thank you!

**Comment by blackliner** [comment]
@benjaminp and @hlopko i just got curios, because whenever i do a 'bazel test ...' after a 'bazel build ...', the cache is not used. I removed '--copt=-fdiagnostics-color=always' from my .bazelrc, and now the cache is properly reused. Is this behavior wanted?

**Comment by benjaminp** [comment]
It's certainly intended that compiler options are part of the cache key.

**Comment by blackliner** [comment]
Both commands had the exact same compiler options.

**Comment by benjaminp** [comment]
`--copt` modifies the compiler options, so that seems unlikely.

**Comment by blackliner** [comment]
In the .bazelrc, there was:
build -c opt --copt=-fdiagnostics-color=always
test -c opt --copt=-fdiagnostics-color=always
Wit the added `--copt=-fdiagnostics-color=always` the build artifacts are not reused, with this .bazelrc they are:
build -c opt
test -c opt
