### ISSUE TITLE
Bazel CI: Buildfarm is failing on mac with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#8374]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/977#264751ae-9b35-4172-b70b-ed39e9567647
```
ERROR: /private/var/tmp/_bazel_buildkite/0457393985f9e9b929c0fb76ddf39add/external/remote_apis/BUILD.bazel:23:1: no such package '@remote_apis//build/bazel/semver': BUILD file not found in directory 'build/bazel/semver' of external repository @remote_apis and referenced by '@remote_apis//:build_bazel_semver_java_proto'
```

Culprit: c6207b4751d5b190813cddb1f918a9adcd0022ae
https://buildkite.com/bazel/culprit-finder/builds/152#36870f4a-3561-478c-9345-aa0ee0509eb4

**Comment by meteorcloudy** [comment]
E... The reason is https://github.com/bazelbuild/remote-apis has a directory named `build` under the root directory. On Windows and macos, where file path is case-insensitive, `repository_ctx.delete("BUILD")` will accidentally delete this directory.

**Comment by aehlig** [comment]
> /cc @aehlig Do you know anything that could help us distinguish the file `BUILD` and the directory `build/`?

You could test if `BUILD` is a file or a directory, and not remove it if it is a directory (as the old `rm -f BUILD` did).

Note that it is in general problematic to run projects written for case-sensitive file systems on file insensitive file systems. Not removing `BUILD` because `BUILD.bazel` takes priority only works by luck, as so far no one has a directory `build.bazel`.

**Comment by meteorcloudy** [comment]
There is no way to test a path is a file or directory in `repository_ctx` API. 
I don't think it works just by luck, `BUILD.bazel` is supposed to take priority than `BUILD`
https://github.com/bazelbuild/bazel/blob/69095be0988711b42dad047892cd20581e9e9e10/src/main/java/com/google/devtools/build/lib/skyframe/BazelSkyframeExecutorConstants.java#L48-L49

**Comment by aehlig** [comment]
> I don't think it works just by luck, `BUILD.bazel` is supposed to take priority than `BUILD`

The place were you're lucky is that so far only directories called `build` are used, not ones called `build.bazel`.

**Comment by meteorcloudy** [comment]
I see. But I don't think any Bazel users will have a such directory. If they do have such a directory, the project won't work on Windows and Mac anyway. And we should warn users not to do this.
