### ISSUE TITLE
Document configuration transitions

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8377]
Documentation of the `cfg` argument in `rule` is unclear (https://docs.bazel.build/versions/0.25.0/skylark/lib/globals.html#rule):

> If set, points to the configuration transition the rule will apply to its own configuration before analysis.

I don't think a user will be able to understand and use that.

Rules documentation doesn't mention it either (https://docs.bazel.build/versions/master/skylark/rules.html). The Example repository (https://github.com/bazelbuild/examples/tree/master/rules) also doesn't help.

**Comment by juliexxia** [comment]
(Context: I'm moving on from Bazel on friday and spending some time triaging all bugs assigned to me before unassigning myself)

This is still a confusing thing. `cfg` should be documented for both the `rule()` function ([which can only be a starlark transition](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java;l=405;drc=9804ba5b88e241ac94e25aac6288b307789f0db5;bpv=1;bpt=1)) and the `attr.*()` functions ([which can be an unfortunately wide variety of things](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkAttrModule.java;l=218-263;drc=9804ba5b88e241ac94e25aac6288b307789f0db5;bpv=1;bpt=1)).
