### ISSUE TITLE
How to uninstall Bazel

### ISSUE THREAD

**Issue by Jacobh2** [bazelbuild/bazel#838]
Hi!

I installed Bazel using the steps here http://bazel.io/docs/install.html.

But now I want to uninstall it. How do I go about doing that?

**Comment by damienmg** [comment]
rm -fr ~/.bazel ~/.bazelrc

**Comment by damienmg** [comment]
Be careful not to mixed up with that command. But it basically recursively remove ~/.bazel and ~/.bazelrc

**Comment by ahumesky** [comment]
Bazel also creates a directory at ~/.cache/bazel which you might want to remove.

**Comment by Jacobh2** [comment]
Found it at ~/.cache/bazel! Thanks!

**Comment by robosina** [comment]
Also I found an executable of bazel in this path `/usr/local/bin/bazel`

**Comment by mbelalsh** [comment]
This command worked for me: `sudo apt-get --purge remove bazel`

**Comment by crazyjat** [comment]
How do on windows?

**Comment by ShahriarAlom** [comment]
`sudo rm -fr ~/.bazel ~/.bazelrc ~/usr/local/lib/bazel ~/.cache/bazel`
delete all above files and folders,
then look into the usr/bin for bazel file, you will find bazel file with version if you have installed using `sudo`, then uninstall `them by sudo apt-get --purge remove bazel-<version>` (one by one if installed multiple version)
after that install bazel proper way and promise never to install bazel without knowing the proper way!

you can install it using sudo and you just need to keep only one bazel verion that matches your need!

**Comment by NikolayJuly** [comment]
There might some trace of bazel in your ~/.lldbinit* files.
