### ISSUE TITLE
incompatible_restrict_string_escapes: Restrict string escapes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8380]
When the flag `incompatible_restrict_escape_sequences` is set, Bazel will reject any string with an unknown escape sequence.

For example, the sequence `\w` doesn't exist. The old behavior was to interpret `"\w"` as if it was `\\w` (in other words, the string will contain a backslash and a w). This behavior is problematic because adding any new escape sequence to the language becomes a breaking change. It may also confuse readers of the code: some backslashes need to be escaped, some don't.

The fix is simple. If you need a literal backslash, escape it:

```diff
- x = "\w"
+ x = "\\w"
```

Buildifier will be updated to automatically fix this.

We intend to flip this flag with Bazel 1.0.

Implement: https://github.com/bazelbuild/starlark/issues/38

**Comment by meteorcloudy** [comment]
Is buildifier updated for this incompatible change?

**Comment by vladmos** [comment]
Buildifier support is on the way: https://github.com/bazelbuild/buildtools/pull/694

**Comment by vladmos** [comment]
Buildifier supports the transformation: `buildifier --lint=fix --warnings=string-escape path/to/BUILD`

**Comment by laurentlb** [comment]
When is it going to be enabled by default?

**Comment by philwo** [comment]
Closing, because this flag has been flipped in https://github.com/bazelbuild/bazel/commit/73402fa4aa5b9de46c9a4042b75e6fb332ad4a7f.
