### ISSUE TITLE
Download performace regression between Bazel 0.24.0 and Bazel 0.25.2 

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#8383]
### Description of the problem:

I've noticed a performance regression on cached builds (combined remote and disk cache) between Bazel 0.24.0 and Bazel 0.25.2.

A build of a fairly large target after `clean --expunge` on a fully populated remote cache and empty disk-cache takes 8m5.825s on 0.24.0 and 9m34.820s on Bazel 0.25.2. Note, that our version of 0.24.0 includes the [combined disk cache patch](https://github.com/digital-asset/daml/blob/b5dec5aa3b7016e29bf3321689b417536676fcf6/nix/overrides/bazel/combined_cache.patch), which is also part of 0.25.2 (https://github.com/bazelbuild/bazel/pull/7512).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

To reproduce the Bazel 0.25.2 numbers, check out https://github.com/digital-asset/daml/pull/442/commits/306b2e3b305726ef0ecaae9981c0f579b78dcfa5 and run
```
source .envrc
bazel build damlc
bazel clean --expunge # (or just bazel clean)
rm -rf .bazel-cache
time bazel build damlc
```

To reproduce the Bazel 0.24.0 numbers, check out https://github.com/digital-asset/daml/pull/442/commits/b5dec5aa3b7016e29bf3321689b417536676fcf6 and run
```
source .envrc
bazel build damlc
bazel clean --expunge # (or just bazel clean)
rm -rf .bazel-cache
time bazel build damlc
```

Porting the repository to Bazel 0.25.2 required a few changes to Bazel code, see https://github.com/digital-asset/daml/pull/442/commits. None of these seem relevant to the download performance, but I can't say for sure.

### What operating system are you running Bazel on?

OpenSUSE Tumbleweed 20190510

### What's the output of `bazel info release`?

release 0.25.2- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

[Using Nix](https://github.com/digital-asset/daml/blob/78505ebbab06c0ebe62924a4c32da905ad7ba40f/nix/overrides/bazel/default.nix)

### Any other information, logs, or outputs that you want to share?

Below I'm listing all observed numbers on clean build of `bazel build damlc` for populated remote cache and empty or populated disk cache. Note, none of these are using the new minimal downloads feature (`--experimental_remote_download_outputs=minimal`).

- bazel 0.25.2:
  - bazel clean --expunge:
    - empty disk cache:
        ```
        INFO: Elapsed time: 574.442s, Critical Path: 128.47s
        INFO: 2903 processes: 2903 remote cache hit.
        INFO: Build completed successfully, 5015 total actions
        
        real    9m34.820s
        user    0m0.360s
        sys     0m0.260s
        ```
    - disk cache:
        ```
        INFO: Elapsed time: 105.435s, Critical Path: 28.88s
        INFO: 2903 processes: 2903 remote cache hit.
        INFO: Build completed successfully, 5015 total actions
        
        real    1m45.594s
        user    0m0.176s
        sys     0m0.128s
        ```
  - bazel clean:
    - empty disk cache:
        ```
        INFO: Elapsed time: 398.458s, Critical Path: 151.57s
        INFO: 2903 processes: 2902 remote cache hit, 1 linux-sandbox.
        INFO: Build completed successfully, 5015 total actions
        
        real    6m38.570s
        user    0m0.251s
        sys     0m0.198s
        ```
    - disk cache:
        ```
        INFO: Elapsed time: 45.495s, Critical Path: 14.29s
        INFO: 2903 processes: 2903 remote cache hit.
        INFO: Build completed successfully, 5015 total actions
        
        real    0m45.598s
        user    0m0.160s
        sys     0m0.167s
        ```
- bazel 0.24.0:
  - bazel clean --expunge:
    - empty disk cache:
        ```
        INFO: Elapsed time: 485.540s, Critical Path: 198.11s
        INFO: 2903 processes: 2903 remote cache hit.
        INFO: Build completed successfully, 5015 total actions
        
        real    8m5.825s
        user    0m0.309s
        sys     0m0.205s
        ```
    - disk cache:
        ```
        INFO: Elapsed time: 91.986s, Critical Path: 25.91s
        INFO: 2903 processes: 2903 remote cache hit.
        INFO: Build completed successfully, 5015 total actions
        
        real    1m32.176s
        user    0m0.200s
        sys     0m0.176s
        ```
  - bazel clean:
    - empty disk cache:
        ```
        INFO: Elapsed time: 357.468s, Critical Path: 157.44s
        INFO: 2903 processes: 2903 remote cache hit.
        INFO: Build completed successfully, 5015 total actions
        
        real    5m57.573s
        user    0m0.281s
        sys     0m0.121s
        ```
    - disk cache:
        ```
        INFO: Elapsed time: 46.354s, Critical Path: 21.23s
        INFO: 2903 processes: 2903 remote cache hit.
        INFO: Build completed successfully, 5015 total actions
        
        real    0m46.527s
        user    0m0.154s
        sys     0m0.209s
        ```

**Comment by jin** [comment]
cc @meisterT @buchgr

**Comment by buchgr** [comment]
@aherrmann thanks for the report! Are you only seeing this with the combined disk and remote cache?

**Comment by meisterT** [comment]
Closing for lack of response.
