### ISSUE TITLE
git_repository inserts invalid empty parameter when called with commit parameter

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#8384]
@aehlig: Bug introduced by https://source.bazel.build/bazel/+/d79786d45be22b27f9dce9a03a5b0cb97daed414

When git_repository is called with a commit parameter and no shallow_since, the "shallow" variable ends up being empty string, which inserts an empty parameter onto the git command line. That fails.

**Comment by aehlig** [comment]
Pending: https://bazel-review.googlesource.com/c/bazel/+/101350
