### ISSUE TITLE
confusing cc_library warning about linkstatic and the absence of object files

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#8388]
If I write a `cc_library` containing only object files, Bazel emits a warning implying there are no object files:
```
$ bazel version
Build label: 0.25.2
$ cat > BUILD
cc_library(
    name = "lib",
    srcs = ["thing.o"],
)
$ bazel build --nobuild  //:lib
WARNING: BUILD:1:1: in linkstatic attribute of cc_library rule //:lib: setting 'linkstatic=1' is recommended if there are no object files
$
```

**Comment by oquenchil** [comment]
We want to eventually deprecate allowing object files in cc_library. Does cc_import work for you in this case?

**Comment by benjaminp** [comment]
`cc_import` isn't a direct replacement because it only takes libraries not object files. This bug report is reduced from some [Tensorflow code](https://github.com/tensorflow/tensorflow/blob/e1c98eeb8ff8a25d2ecdcf1961974d6c9c1e3df4/tensorflow/compiler/aot/tfcompile.bzl#L268-L299).

This warning predates `cc_import`, but I don't understand what its intent is.

**Comment by oquenchil** [comment]
Fix is on the way. This was a bug in cc_library, for the warning we didn't look at precompiled files. Thank you Benjamin.
