### ISSUE TITLE
--execution_log_binary_file negation

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#8393]
Using bazel 0.26.0rc10 and `--execution_log_binary_file`, you cannot negate the argument with `--execution_log_binary_file=` as you could with `experimental_execution_log_file`. I'm not sure if it was intentional behavior before but previously passing:

```
bazel build //... --experimental_execution_log_file=foo.log --experimental_execution_log_file=
```

Would not write an execution log file. This is useful for when you have a configuration that implies `experimental_execution_log_file`, but for some reason you don't want to write it just for this build.

**Comment by buchgr** [comment]
That's not an intended change (@agoulti). I think it should be possible to negate all our flags. WDYT @ishikhman?

**Comment by ishikhman** [comment]
I agree, we should keep the possibility to negate/disable all flags. It feels to me like a bug in a recent change that introduced a new set of flags.

**Comment by keith** [comment]
Note that I just discovered that this is broken with `--experimental_execution_log_file` as well, which causes issues for us even without changing to the new flag.

**Comment by keith** [comment]
I've submitted a fix for this https://github.com/bazelbuild/bazel/pull/8428
