### ISSUE TITLE
Bazel HEAD fails to build Bazel when using RBE

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#8395]
Spotted in our downstream pipeline: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/981#09ddae55-7302-4acc-90c9-444b67ef0743

ERROR: /workdir/bazel-downstream-projects/bazel/tools/osx/BUILD:17:1: Couldn't build file tools/osx/xcode-locator: Executing genrule //tools/osx:xcode-locator-genrule failed: No usable spawn strategy found for spawn with mnemonic Genrule. Are your --spawn_strategy or --strategy flags too strict?

This is caused by the auto-strategy flag rollout, but I'm not sure what exactly happens there.

**Comment by ishikhman** [comment]
Should be fixed by https://github.com/bazelbuild/continuous-integration/pull/663, let's see.

**Comment by ishikhman** [comment]
fixed by bazelbuild/continuous-integration#663
