### ISSUE TITLE
document that nested workspaces are supported

### ISSUE THREAD

**Issue by crorvick** [bazelbuild/bazel#8398]
### Description of the problem / feature request:

The documentation for `local_repository()` does not clearly state that nested workspaces are supported.

### Feature requests: what underlying problem are you trying to solve with this feature?

Document that nested workspaces are supported.

**Comment by laurentlb** [comment]
Some more context: https://groups.google.com/forum/#!msg/bazel-discuss/DXBjq-49pOs/hT2feMrhAwAJ

**Comment by aehlig** [comment]
7bdfb57ccb33bc23814f509ba6aaf188597cb731 actually fixed this issue.
