### ISSUE TITLE
Add --test_support flag to include a file in all test runs

### ISSUE THREAD

**Issue by adzenith** [bazelbuild/bazel#8399]
### Description of the problem / feature request:

It would be useful to have a `--test_support` flag analogous to the `--coverage_support` flag. If this flag existed, I would use it to add sanitizer suppression files (such as [for thread sanitizer](https://github.com/google/sanitizers/wiki/ThreadSanitizerSuppressions)) to my test runs.

### Feature requests: what underlying problem are you trying to solve with this feature?

Clang's sanitizers sometimes have false positives, such as when running thread sanitizer against TBB or address sanitizer with boost::python. The way to suppress these false positives is to set an environment variable with the path to a text file containing suppressions. In Bazel, there are currently a couple of ways to do this:

- Use an absolute path to the file so that it works from the sandbox (but doesn't work with e.g. Remote Build Execution)
- Make a new cc_test macro that adds a runtime dependency on the file (ideally only when running sanitizers), and convert all of your cc_tests into this new macro.

Neither of these is ideal. In searching for other ways to fix this problem, I came across this flag:
> [`--coverage_support=<a build target label>`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--coverage_support) default: `"@bazel_tools//tools/test:coverage_support"`
> Location of support files that are required on the inputs of every test action that collects code coverage. Defaults to '//tools/test: coverage_support'. 

which looks perfect, except that it's only for coverage runs. Getting an equivalent flag for tests would be amazing.

### What operating system are you running Bazel on?

Ubuntu 16.04.

### What's the output of `bazel info release`?

`release 0.23.2`

###  Have you found anything relevant by searching the web?

No, I've searched and not found anything other than `--coverage_support`.

### Any other information, logs, or outputs that you want to share?

That's it!

**Comment by hlopko** [comment]
CC @iirina, since you're working on coverage, you might know how hard would it be to implement this option for tests. What do you recommend? Is it doable for an external contributor? ;)

**Comment by hlopko** [comment]
Thinking about it, could you put the suppression file as a `data` dependency of the test? That way you can get the file into your test action, and you can do it on a per-test basis. With `--test_support` you'd potentially add the file also into unrelated tests.

**Comment by adzenith** [comment]
I actually want this file included in all tests, because I'm building the whole workspace with the sanitizer.

I mentioned "add[ing] a runtime dependency on the file" in the original description as something I can do right now but I'd rather not do, because I either have to update `data` for every test in the workspace, or make a new macro that wraps `cc_test`, which then involves adding a `load` in every BUILD file that has a test. This flag would mean I can just use cc_test normally and I don't have to make any other changes.

**Comment by adzenith** [comment]
I've figured out a workaround using `prelude_bazel`, which I read about [here](https://groups.google.com/forum/#!msg/bazel-discuss/igMsIXf0kUQ/EVRhdRXlCQAJ). This in turn led me eventually to [here](https://github.com/bazelbuild/BUILD_file_generator/blob/master/tools/build_rules/prelude_bazel), where there's a working implementation that I was able to copy.

In the end, `prelude_bazel` lets me override the default `cc_test` implementation, which then allows me to add a simple `select` to the `data` attribute for all `cc_test`s to include suppression files.

My only fear with this approach is that `prelude_bazel` is completely undocumented (which is why I didn't know about it before) and that it is maybe unmaintained or could disappear.

**Comment by hlopko** [comment]
Yeah using `prelude_bazel` is frowned upon :) But we're going to migrate the world to force using `load` statements with C++ rules for Bazel 1.0, so you can just go ahead and fetch https://github.com/bazelbuild/rules_cc repo and use it in your workspace. And since you're loading `cc_test` anyway, you can load your macro instead, and it won't look surprising.

**Comment by hlopko** [comment]
I actually like the macro solution more than the `--test_support` hook. I'll leave to @iirina to decide whether to add it or to recommend to use macros.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
