### ISSUE TITLE
Analysis of target '//tensorflow/contrib/tensor_forest:model_ops_test' failed; build aborted: for tensorflow/contrib/tensor_forest/libutils.so

### ISSUE THREAD

**Issue by luorixiangyang** [bazelbuild/bazel#8400]
env:
OS: windows 10
bazel version: 0.24.1
tensorflow version:r1.14
python:3.6.4
CUDA:9.0
cuDNN: 7.1
--------------------------------
send under command in gitBash could complete successfully
bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
---------------------------------------------
but send bazel test command encounter error, details as following.:
command(in gitBash):
bazel test tensorflow/contrib/tensor_forest:model_ops_test

Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
Loading:
Loading: 0 packages loaded
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (1 packages loaded, 0 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (33 packages loaded, 352 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (58 packages loaded, 2552 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (82 packages loaded, 4125 targets configured)
Analyzing: target //tensorflow/contrib/tensor_forest:model_ops_test (83 packages loaded, 4154 targets configured)
ERROR: file 'tensorflow/contrib/tensor_forest/libutils.so' is generated by these conflicting actions:
Label: //tensorflow/contrib/tensor_forest:model_ops_test
RuleClass: cc_test rule
Configuration: c9dc3b2a2ac77c2e5a3c9175e9c4aa9e
Mnemonic: Symlink
Action key: 0ac20b0e60679a64dc9111fddc500670
Progress message: Copying Execution Dynamic Library
PrimaryInput: File:[[<execution_root>]bazel-out/x64_windows-opt/bin]tensorflow/core/grappler/clusters/libutils.so, File:[[<execution_root>]bazel-out/x64_windows-opt/bin]tensorflow/core/grappler/costs/libutils.so
PrimaryOutput: File:[[<execution_root>]bazel-out/x64_windows-opt/bin]tensorflow/contrib/tensor_forest/libutils.so
**ERROR: Analysis of target '//tensorflow/contrib/tensor_forest:model_ops_test' failed; build aborted: for tensorflow/contrib/tensor_forest/libutils.so, previous action: action 'Copying Execution Dynamic Library', attempted action: action 'Copying Execution Dynamic Library'
INFO: Elapsed time: 10.421s**
INFO: 0 processes.
FAILED: Build did NOT complete successfully (84 packages loaded, 4219 targets configured)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (84 packages loaded, 4219 targets configured)
----------------------------------------
how to fix?

**Comment by dslomov** [comment]
Please file this in TensorFlow bug tracker.

**Comment by luorixiangyang** [comment]
> Please file this in TensorFlow bug tracker.

Hi dslomov，
I am not very clearify why this is not bazel issue. I found the corresponding code of Bazel source will occur the error,  could y help me to check why cause the error. I test py_test and cc_test all ok. only test for tf_cc_test will cause the error. I update CUDA to 10.0 and cudnn to 7.5 , tensorflow to 2.0 still have this error when run  tf_cc_test by bazel test. I also build a issue at tensorflow [project[#28898]:](https://github.com/tensorflow/tensorflow/issues/28898)

/**
   * Create the actions to symlink/copy execution dynamic libraries to binary directory so that they
   * are available at runtime.
   *
   * @param dynamicLibrariesForRuntime The libraries to be copied.
   * @return The result artifacts of the copies.
   */
  private static ImmutableList<Artifact> createDynamicLibrariesCopyActions(
      RuleContext ruleContext, NestedSet<Artifact> dynamicLibrariesForRuntime) {
    ImmutableList.Builder<Artifact> result = ImmutableList.builder();
    for (Artifact target : dynamicLibrariesForRuntime) {
      if (!ruleContext.getLabel().getPackageName().equals(target.getOwner().getPackageName())) {
        // SymlinkAction on file is actually copy on Windows.
        Artifact copy = ruleContext.getBinArtifact(target.getFilename());
        ruleContext.registerAction(SymlinkAction.toArtifact(
            ruleContext.getActionOwner(), target, copy, "Copying Execution Dynamic Library"));
        result.add(copy);
      }
    }
    return result.build();
  }
