### ISSUE TITLE
Windows: Bazel@HEAD no longer shows error message from C++ compiler

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#8402]
Culprit: 33f7b7755db0ed5cad1b686b7616183927c72ab1
You can reproduce by building a C++ file that has some syntax error.

**Comment by meteorcloudy** [comment]
@ulfjack Please tell me if it's a easy fix, otherwise we should rollback first.

**Comment by ulfjack** [comment]
I have a fix. I'm not sure if I have a regression test.

**Comment by ulfjack** [comment]
As far as I can tell, the breakage did not make it into 0.26 (May release), and the fix should be picked up  by 0.27.

**Comment by meteorcloudy** [comment]
Yes, I can also confirm that. Thanks for the fix and test!
