### ISSUE TITLE
Creating runfiles tree failed without error message

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#8413]
### Description of the problem:

Just seen this multiple times in CI:

```
(15:24:07) INFO: Invocation ID: b229b03f-d4d7-4b93-9fa6-b11307b73912
(15:24:07) INFO: Current date is 2019-05-20
...
15:27:09) Analyzing: target //:lint-ci (106 packages loaded, 7328 targets configured)
(15:27:20) INFO: Analyzed target //:lint-ci (253 packages loaded, 17461 targets configured).
(15:27:20) INFO: Found 1 target...
(15:27:21) [0 / 2] [-----] Writing script lint-ci.bash ... (2 actions, 0 running)
(15:27:21) [0 / 2] [-----] Writing script lint-ci.bash ... (2 actions, 0 running)
(15:27:35) ERROR: /home/circleci/project/BUILD.bazel:65:1: Creating runfiles tree bazel-out/k8-fastbuild/bin/lint-ci.bash.runfiles failed: build-runfiles failed: error executing command 
  (cd /home/circleci/.cache/bazel/_bazel_circleci/f16e36219ef33c22efc2ad20f3e3775c/execroot/__main__ && \
  exec env - \
    CI=true \
    PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /home/circleci/.cache/bazel/_bazel_circleci/install/d3bd40b000554ec2dfd10da1797a94e5/_embedded_binaries/build-runfiles bazel-out/k8-fastbuild/bin/lint-ci.bash.runfiles_manifest bazel-out/k8-fastbuild/bin/lint-ci.bash.runfiles): Process terminated by signal 9: Process terminated by signal 9
/bin/bash: line 1:    72 Killed                  bazel --batch run --config=ci --verbose_failures lint-ci
```

And not getting any reasons as to why this failed apart from the fact that it terminated with signal 9. Running the same command locally works fine and I can not reproduce.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Not sure how it is possible to reproduce this.

### What operating system are you running Bazel on?

This is in CircleCI (with only 4GB of RAM) inside a Debian Stretch container

### What's the output of `bazel info release`?

release 0.25.2 but also saw it with 0.24.1

The only similar issue that I found was https://github.com/bazelbuild/bazel/issues/6176

Edit: Interesting, I have just seen another failure and there I saw the following error:
```
(20:58:12) WARNING: Writing to Remote Cache:
Cannot allocate memory
```

I activated the `--disk_cache` very recently in ci so maybe that is related somehow

**Comment by Globegitter** [comment]
It was most likely a memory issue, as adding `--jobs=2` resolved the issue. So possibly can be closed.

**Comment by ishikhman** [comment]
Closing for now, please feel free to re-open it in case you face this issue again! :)
