### ISSUE TITLE
Out of memory errors reference 'Blaze'

### ISSUE THREAD

**Issue by xiongchiamiov** [bazelbuild/bazel#842]
There are [a](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/BugReport.java#L112) [couple](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/BugReport.java#L144-L145) places in `BugReport.java` where Blaze is referenced in output to the user; these should probably be "Bazel" instead.

**Comment by tfarina** [comment]
@dslomov would you be fine if we submit a patch to replace these "Blaze" references by
Constants.PRODUCT_NAME? Or will that cause too much disturbance/noise at this point?

**Comment by damienmg** [comment]
@tfarina I think that's fine to do it. Unless @lfpino has objections (he's working on removing all usages of the Constants class and might have some guidance to do it to reduce his work load). We might have still instance of it in the client launcher.

**Comment by lfpino** [comment]
Go ahead, those references to Constants.PRODUCT_NAME should be easy to remove later on.

**Comment by tfarina** [comment]
I have made https://bazel-review.googlesource.com/#/c/3103/ for this.

I was not able to set @lfpino as a reviewer, it does not autocomplete there.

Please, feel free to review when you can.

Thanks,
