### ISSUE TITLE
Shouldn't pull archives when there is more than one defined with the same name

### ISSUE THREAD

**Issue by tsvisabo** [bazelbuild/bazel#8433]
### Description of the problem / feature request:
Multiple `http_archives` with the same _name_ attribute shouldn't be allowed on the same WORKSPACE, i assume it applies also to `new_http_archives` and `git_repository` too

### Feature requests: what underlying problem are you trying to solve with this feature?

Having unique archive names in the same WORKSPACE and avoid pulling remote archives only to fail finding out there's an ambiguity 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create 2 `http_archive` targets in the same WORKSPACE with the same name,  the pulling is probably sequential, and the conflicts aren't being detected beforehand

### What operating system are you running Bazel on?

linux64

### What's the output of `bazel info release`?

I didn't wait for the pull to complete, so i am not sure how it fails exactly, all i know is, the archives with the conflicting names are being pull when they shouldn't

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

apt-get

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
