### ISSUE TITLE
Unprecise error message when toolchain info features configuration is wrong

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#8435]
### Description of the problem / feature request:

When trying to convert my codebase from `CROSSTOOL` to the skylark toolchain definition, I used a string in the `features` field of `cc_common.create_cc_toolchain_config_info`, such as:

```
cc_common.create_cc_toolchain_config_info(
  ...
  features = [
      "supports_pic",
  ],
```

This leads to the following error message:

```
[Bazel traceback]
class java.lang.String cannot be cast to class com.google.devtools.build.lib.packages.SkylarkInfo (java.lang.String is in module java.base of loader 'bootstrap'; com.google.devtools.build.lib.packages.SkylarkInfo is in unnamed module of loader 'app')
```

This can be improved, mostly because `SkylarkInfo` is too vague to help understand by what the string should be replaced.

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

```release 0.25.2- (@non-git)```

**Comment by katre** [comment]
This is not a configurability issue, it is part of cc toolchain definition.
