### ISSUE TITLE
Python: py_binary output zip may be non-deterministic

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8436]
### Description of the problem / feature request:

Repro: https://github.com/laszlocsomor/projects/tree/master/bazel/python_zip_nondeterministic

When building a py_binary with `--build_python_zip`, the zip file's contents are not sorted, so it might be non-deterministic.

### What operating system are you running Bazel on?

Windows 10 , Linux

### What's the output of `bazel info release`?

release 0.25.1

**Comment by laszlocsomor** [comment]
This is not just on Windows, I see it on Linux with `--build_python_zip`:

```
  $ unzip -l bazel-bin/app/app.zip
Archive:  bazel-bin/app/app.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     7757  2010-01-01 00:00   __main__.py
        0  2010-01-01 00:00   __init__.py
        0  2010-01-01 00:00   runfiles/__main__/__init__.py
        0  2010-01-01 00:00   runfiles/bar/lib/__init__.py
        0  2010-01-01 00:00   runfiles/bar/__init__.py
        0  2010-01-01 00:00   runfiles/__init__.py
        0  2010-01-01 00:00   runfiles/__main__/app/__init__.py
       48  2010-01-01 00:00   runfiles/__main__/app/main.py
       33  2010-01-01 00:00   runfiles/bar/lib/lib_foo.py
---------                     -------
     7838                     9 files
```

**Comment by laszlocsomor** [comment]
Repro (added to original message): https://github.com/laszlocsomor/projects/tree/master/bazel/python_zip_nondeterministic

**Comment by brandjon** [comment]
I'll look at fixing this for 0.27.

**Comment by brandjon** [comment]
I'm not sure that this is an issue -- have you observed any actual non-determinism?

This zip action is created [here](https://github.com/bazelbuild/bazel/blob/b2fac7457a673a13427861aabb323a32b74e07ce/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java#L309). Notice that the zip arguments are added in the order of the top-level `__init__.py` first, then all other `__init__.py` files, then all runfiles artifacts minus the executable, in the order returned by `runfilesSupport.getRunfilesArtifacts()`. That returns a depset, and we should expect depset values to be deterministic but not necessarily sorted.

I believe the zipper tool preserves order of its arguments.

I can add a sort call to that function, but I think it'd be superfluous.

**Comment by brandjon** [comment]
(Downgrading pending a response but note that Laszlo's OOO until next week.)

**Comment by laszlocsomor** [comment]
I didn't observe non-determinism.
I still prefer sorting even if superfluous. Costs little, makes "unzip -l" output easier to read, and avoids relying on lucky circumstance.

**Comment by brandjon** [comment]
Easy enough to do but I'm putting out fires related to toolchains atm. I figure the sorting should also include the `__init__.py` and `__main__.py` files if we're doing it for readability's sake.

**Comment by brandjon** [comment]
I might be being pedantic, but I'll add that I don't think the fact that nested set order is deterministic is "lucky". :) We rely on an assumption of determinism-by-default all over bazel. If for whatever reason a non-determinism is present in the underlying nested set, it could be that sorting these files masks the problem.

**Comment by minor-fixes** [comment]
Does "non-determinism" in this context mean that if `deps` are reordered, the `NestedSet` (and thus the file order, etc.) are unchanging?

In Bazel 5.1.1, we're seeing changing the order of entries in `deps` change the order of file entries in the zip (which probably doesn't matter) and the order of the `PYTHONPATH` in [this substitution](https://sourcegraph.com/github.com/bazelbuild/bazel/-/blob/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt?L444:21), which appears to matter (certain entries appearing before other entries causes `ModuleNotFound` errors) though it's not clear if the blame lies with NestedSet/determinism, any wrappers we have around `py_binary` that cause this somehow, or the Python dependencies themselves.
