### ISSUE TITLE
Toolchain tutorial need more examples

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#8437]
### Description of the problem / feature request:

When reading the documentation for toolchain: https://docs.bazel.build/versions/0.25.0/cc-toolchain-config-reference.html I had issues finding the information I wanted.

The documentation can benefit to have more examples. Actually, I had to grep / read through the bazel source code, mostly reading file `tools/cpp/cc_toolchain_config.bzl` to find my answers.

An short list of what (I thought) was difficult to understand only using the tutorial:

- The `features` section. I had no idea what I was supposed to put in the `features` argument. Especially to enable features which already exists such as `supports_pic`.
- The documentation details the usage of the `enabled` argument for `feature`, but does not show it in the examples, it is difficult to understand when this argument is used.

**Comment by katre** [comment]
This is not a configurability issue, it is part of cc toolchain definition.

**Comment by oquenchil** [comment]
I'm adding a link in the tutorial to https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html which has more information about features, including `supports_pic`.

The tutorial is kept as simple as possible, the reader can explore more on their own.
