### ISSUE TITLE
`test_tag_filter` should imply `build_tag_filter` in `bazel test` command

### ISSUE THREAD

**Issue by ghost** [bazelbuild/bazel#8439]
### Description of the problem / feature request:

Right now, the somewhat innocent looking command
```
$ bazel test //... --test_tag_filters=my-specific-tag
```
builds far more than it needs to to run the specified test.

As far as I can tell, this is because bazel is interpreting the `test` command as
```
$ bazel build [label] [options]
$ bazel test [label] [options]
```
and since the first part of that ignores `--test_tag_filters`, the above innocent-looking command expands to
```
$ bazel build //...
$ bazel test //... --test_tag_filters=my-specific-tag
```

This is _very_ counter-intuitive.

I suggest that the `build` part of a `bazel test` command use the same analysis as the `test` part of that command, so only the required test targets (and their dependencies) are built.

### Feature requests: what underlying problem are you trying to solve with this feature?

Fixing counter-intuitive command-line behaviour, reducing accidentally very long builds.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.23.2
```

**Comment by janakdr** [comment]
Does the flag `--build_tests_only` work to make Bazel behave as you expect in this case?

**Comment by aiuto** [comment]
Perhaps --test_tag_filters should imply use of build_tests_only.
OR.... perhaps bazel test should imply build_tests_only, so that if you actually want to build everything, you' would have to add --nobuild_tests_only.  That seems like reasonable behavior, but I'm sure that would upset someones process.

**Comment by dmivankov** [comment]
Another interesting related note is how `//...` doesn't include `manual` targets but `$(bazel query //...)` does and `--test_tag_filters=-manual` isn't enough to prevent building `manual` targets.
