### ISSUE TITLE
Support tooling like Retrolambda for Android binaries

### ISSUE THREAD

**Issue by perezd** [bazelbuild/bazel#844]
discussion here: https://groups.google.com/forum/#!msg/bazel-discuss/Or50uVScwkI/VxvEwBc5HAAJ
project details: https://github.com/orfjackal/retrolambda

Ina nutshell, this is a javac plugin that rewrites JDK 8 bytecode into acceptable bytecode for other JDK versions. This enables Android developers to utilize lambda syntax shorthand, and other JDK8 features.

**Comment by dslomov** [comment]
Assigning to Damien for triage

**Comment by damienmg** [comment]
We don't have the bandwidth to do that right now but we definitely would like to support retrolambda. Contribution welcomed :)

**Comment by ulfjack** [comment]
I just stumbled across this in my own Android app. If you use java_library
rules, you manually need to set them all to Java 6, or the Android tools
will barf with an incomprehensible error message. :-( Unfortunately, it
requires significant changes to the Java rules to support this; changes
which we ought to make anyway, but currently don't have the capacity to do.
:-((

**Comment by perezd** [comment]
I am just annoyed enough about this that I might be willing to take this on. Can someone outline the work that needs to be done? I'm not really sure where to start with this.

**Comment by perezd** [comment]
So after some discussion, one simple thing we could do is make it possible to override the java_toolchain source/target values that are currently hardcoded in BazelAndroidSemantics.java.

WDYT?

**Comment by ulfjack** [comment]
How does that help?

I'd prefer to first clean up our Java rule infrastructure (JavaCommons,
JavaCompileActionBuilder, JavaCompileAction), before we start adding more
features to it. Just yesterday I found out that android_binary still
doesn't support runtime_deps, making it unnecessarily diverge from
java_binary (and less amenable to automatic deps management). I'm thinking
that something similar to CcLibraryHelper might be a good idea, and
consistently using that from all java_* and android_* rules.

**Comment by perezd** [comment]
Sorry, I realize that may have been unclear.

Retrolambda rewrites bytecode compiled from JDK8 into compatible alternative bytecode for lower version of the JDK like 5, 6, or 7. It does this by replacing things like lambdas with anonymous classes automatically, etc.

So, given that require, step 1 in supporting Retrolambda is configuring bazel to support customizing `javacopts` for `android_library` so that source 8 and target 8 are respected. I realize that if we do this change, we'd end up bytecode that the `dx` command would start immediately chocking on. My current plan is to write a wrapper script for `dx` and see if I can intercept the `_deploy.jar`, rewrite using Retrolambda, and then hand the rewritten jar over to the original `dx` command.

This solution feels hacky and gross, but it also feels like the least obtrusive suggestion. If the dx wrapper thing works, potentially we could add cleaner support for it by adding a `dx_wrapper_shell` argument to the `android_sdk` build rules...but not sure I really advocating for that.

Does that help clear things up?

**Comment by ulfjack** [comment]
That gives me an idea - you could write a java_toolchain rule that first
invokes the Java compiler and then immediately runs Retrolambda after that.
Except maybe you need the original Jar files for the downstream Javac
invocations?

**Comment by perezd** [comment]
That could work too, maybe we could create an android_toolchain that is more specific to the build steps of Android/Dex? Its worth noting however that jack/jill won't work with Retrolambda, so doing something very official seems like maybe a bad idea. WDYT?

**Comment by ulfjack** [comment]
Unless there's a specific reason why java_toolchain doesn't work, I
wouldn't add an android_toolchain for this purpose.

In the future, any Bazel user will be able to write their own
java_toolchain drop-in replacement in Skylark.

**Comment by perezd** [comment]
That an interesting proposal, but I think it'd put a lot more distance between us and a workable Retrolambda solution in bazel if we were to prioritize that. Maybe I'm wrong, not sure I understand the implications of it.

I think a good first step is to allow android_* rules to respect java_toolchain settings. WDYT?

**Comment by ulfjack** [comment]
On Wed, Feb 10, 2016 at 5:46 PM, Derek Perez <notifications@github.com>
wrote:

> That an interesting proposal, but I think it'd put a lot more distance
> between us and a workable Retrolambda solution in bazel if we were to
> prioritize that. Maybe I'm wrong, not sure I understand the implications of
> it.
>
> I think a good first step is to allow android_* rules to respect
> java_toolchain settings. WDYT?
>

If you're proposing to remove the code from AndroidJavaSemantics, that
would unfortunately break all of Google's internal users. I have a proposal
for better handling of target platforms that would fix this, but that's a
larger change.

**Comment by perezd** [comment]
While that does sound bad, I was told that any change in the Bazel* files would explicitly not impact Google's internal users. This change I'm advocating for is found here:
https://github.com/bazelbuild/bazel/blob/5cf42ff6898ff2a459956405f57f0338f9a2a01b/src/main/java/com/google/devtools/build/lib/bazel/rules/android/BazelAndroidSemantics.java#L71

Would that still break Google?

**Comment by perezd** [comment]
To be clear, I'm assuming if we were able to optionally pass RuleContext into getJavacArguments, we could check for the toolchain and respond properly. This would be a backwards compatible change I believe.

**Comment by ahumesky** [comment]
Ulf, it's not clear to me how java_toolchain would indicate the wrapper to use for javac:
https://github.com/bazelbuild/bazel/blob/14aaeb90d14fdd61f109f34d13710815253eaa93/src/main/java/com/google/devtools/build/lib/rules/java/JavaToolchainRule.java

Do you mean --javabase / --host_javabase?

**Comment by ulfjack** [comment]
Sorry, Derek, you're right. It's not immediately obvious that it would
break Google. My bad. But I'm still not sure how you'd make Android builds
work again with that code removed. If you change the default java_toolchain
to set -target 7 -source 7, then you can't build Java 8 code anymore, and
if you don't, you can't build Android code without setting additional flags.

Alex, err, yeah, I mean whatever place is defining what binary to run for
the Java compiler. If that isn't java_toolchain right now, then whatever
other place does. It's weird that the compiler and the flags are declared
in different places; apparently I didn't pay enough attention when
reviewing the Java changes. :-/ It's actually the --javabuilder_top flag.

**Comment by ahumesky** [comment]
Oh, yeah that's true, you might actually have to write a wrapper around javabuilder, not javac, since javabuilder and javac are tied together so much.

**Comment by perezd** [comment]
Hi Ulf,

So, the plan would not to be to change the default toolchain to java 7/7, but to define a custom toolchain for use with android that is set to 8/8, and compile android jars with JDK8. Currently the way BazelAndroidSemantics is configured, it always returns java 7/7 copts regardless of what you set, no way to override, that is what we'd need to change. Does that help? Its actually a pretty small change that would go a long way.

**Comment by perezd** [comment]
Hi everyone,

not to beat a dead horse, but here is my Android experience in Bazel right now, as I try to use RxJava:
https://gist.github.com/perezd/eaaac8b6fe7bfbf2266c

In Gradle/Maven it would not be this ugly.
All we have to do is make it possible for me to compile android code into JDK8, I can then wrap the dex call in retrolambda support outside of bazel.

**Comment by ulfjack** [comment]
I agree that it's not good, but I don't think it's a small change right now, unfortunately. The obvious change of removing the few lines in BazelAndroidSemantics.java has problems as well, right?

There's a related problem, which I've been discussing with +ahumesky. It's not currently easy to annotate Java rules such that they can be easily used from Android. If you depend on a java_library from an android_binary (even indirectly), you get an opaque error message.

We could change JavaCommon to put the hard-coded options before the javacopts expansion, which would at least allow you to override -source and -target on a per-android_library basis.

**Comment by perezd** [comment]
My current workaround (appears to be working) is the following:
- convert all my android_library instances to java_libraries (compiles
using JDK8 here) with a neverlinked android SDK as a dep.
- create retrolambda genrule that takes a java_binary->java_import target's
jar file, unjars it, runs retrolambda (converts to JDK7), and rejars it.
- provide a new java_import (of the new rejared classes) that can be used
as a dep for an android_binary.

Believe it or not, all that mess works, and can be reasonably clean given a
macro. I'll post more details here when I'm done so people who are
searching for this support can at least have a potential workaround.

**Comment by ahumesky** [comment]
That all works to get the java code compiled with jdk8. Does it work with android resources? Can the java_library depend on an android_library to get the R classes?

As Ulf said, we can switch around these arguments:
https://github.com/bazelbuild/bazel/blob/7ba49f371e9e495385c9294ab87b1940cb05357d/src/main/java/com/google/devtools/build/lib/rules/java/JavaCommon.java#L409-L411

**Comment by perezd** [comment]
that simple change would be a huge help, when could we do this?

re: depending on android, no it can't but in my case I can make everything
an android_library, and as for R class pretty sure I can get that to work
with some more elbow grease. basically gradle just generates a class and
compiles things against it but doesn't link. I can delegate actual resource
generation to the android_binary target.

I'd rather avoid all of this :) an even simpler macro is possible if I can
set javac source/target opts to 8, then simply run retrolambda against each
output jar in parallel, rather than a single push to the final sum just
before becoming an android binary.

**Comment by ahumesky** [comment]
The change itself is trivial, but verifying that it doesn't break anything could take a couple days, but I'm not sure I'll have time this week to put that together.

**Comment by ahumesky** [comment]
After some more discussion, it seems that this should be a safe change to make.

**Comment by ulfjack** [comment]
This should make it easier at least to work around temporarily. I'm afraid I won't be able to do a lot more work here. @perezd, have you tried this?

**Comment by perezd** [comment]
It did work! Thank you for this help!! I started a new thread to mobilize
the last remaining bit of help needed to make this work better:
https://groups.google.com/forum/#!topic/bazel-discuss/xp6eqktCTrg

**Comment by ahumesky** [comment]
See https://github.com/bazelbuild/bazel/issues/2222 for more updates on java 8 for android in bazel.
