### ISSUE TITLE
dyld: lazy symbol binding failed on Darwin for cc_test target

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/bazel#8445]
### Description of the problem / feature request:

Running gunit unit test using `blaze test` on Darwin results in dyld lazy symbol finding error:

```
$ bazel test //foo:foo_test --test_output=errors
INFO: Analyzed target //foo:foo_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
FAIL: //foo:foo_test (see /private/var/tmp/_bazel_dzc/df81d8fb4cd81e4ef0a6151c52c3a958/execroot/com_google_bazel_507/bazel-out/darwin-fastbuild/testlogs/foo/foo_test/test.log)
INFO: From Testing //foo:foo_test:
==================== Test output for //foo:foo_test:
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from FooTest
[ RUN      ] FooTest.BaseCase
dyld: lazy symbol binding failed: Symbol not found: __ZN3foo3FooD1Ev
  Referenced from: /private/var/tmp/_bazel_dzc/df81d8fb4cd81e4ef0a6151c52c3a958/sandbox/darwin-sandbox/19/execroot/com_google_bazel_507/bazel-out/darwin-fastbuild/bin/foo/foo_test.runfiles/com_google_bazel_507/foo/foo_test
  Expected in: flat namespace

dyld: Symbol not found: __ZN3foo3FooD1Ev
  Referenced from: /private/var/tmp/_bazel_dzc/df81d8fb4cd81e4ef0a6151c52c3a958/sandbox/darwin-sandbox/19/execroot/com_google_bazel_507/bazel-out/darwin-fastbuild/bin/foo/foo_test.runfiles/com_google_bazel_507/foo/foo_test
  Expected in: flat namespace

external/bazel_tools/tools/test/test-setup.sh: line 310: 94915 Abort trap: 6           "${TEST_PATH}" "$@" 2>&1
================================================================================
Target //foo:foo_test up-to-date:
  bazel-bin/foo/foo_test
INFO: Elapsed time: 0.283s, Critical Path: 0.13s
INFO: 2 processes: 2 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//foo:foo_test                                                           FAILED in 0.1s
  /private/var/tmp/_bazel_dzc/df81d8fb4cd81e4ef0a6151c52c3a958/execroot/com_google_bazel_507/bazel-out/darwin-fastbuild/testlogs/foo/foo_test/test.log

INFO: Build completed, 1 test FAILED, 2 total actions
```

Setting `linkstatic = 1` on the `cc_test` target results in the following linker error:

```
$ bazel test //foo:foo_test --test_output=errors
INFO: Analyzed target //foo:foo_test (1 packages loaded, 8 targets configured).
INFO: Found 1 test target...
ERROR: /Volumes/oasis/Projects/experimental/bazel-8445/foo/BUILD:23:1: Linking of rule '//foo:foo_test' failed (Exit 1) cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -lc++ -fobjc-link-runtime -Wl,-S -o bazel-out/darwin-fastbuild/bin/foo/foo_test bazel-out/darwin-fastbuild/bin/foo/_objs/foo_test/foo_test.o ... (remaining 23 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Undefined symbols for architecture x86_64:
  "foo::Foo::~Foo()", referenced from:
      foo::(anonymous namespace)::FooTest_BaseCase_Test::TestBody() in foo_test.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //foo:foo_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.806s, Critical Path: 0.63s
INFO: 14 processes: 14 darwin-sandbox.
FAILED: Build did NOT complete successfully

FAILED: Build did NOT complete successfully
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Reproduction case available here: https://github.com/davidzchen/bazel-8445

To repro (on macOS):

```
$ git clone https://github.com/davidzchen/bazel-8445
$ cd bazel-8445
$ bazel test //foo:foo_test --test_output=errors
```

### What operating system are you running Bazel on?

macOS 10.14.5

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`bazel build //src:bazel` from source checkout

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD 
git@github.com:davidzchen/bazel
cc7a6e0b2ffed7b6cb3d299e4c37859ad167e06e
cc7a6e0b2ffed7b6cb3d299e4c37859ad167e06e
```

###  Have you found anything relevant by searching the web?

#507 and #2944 appear related

### Any other information, logs, or outputs that you want to share?

GitHub repo with reproduction case: https://github.com/davidzchen/bazel-8445

To reproduce:

```
$ git clone https://github.com/davidzchen/bazel-8445
$ cd bazel-8445
$ bazel test //foo:foo_test --test_output=errors
```

**Comment by davidzchen** [comment]
Actually, I thought I had isolated a base repro case for this, but it turns out not. I'll close it for now and reopen once I have that set up.

**Comment by davidzchen** [comment]
I have created a reproduction case for this and have updated the issue description with the GitHub repo. It seems that it occurs when a `cc_proto_library` is linked since this `dyld` error does not occur at commit d87b66bfc9afe5879140a9b30e75be4f1de747ac.

Is this a known issue?

+cc hlopko

**Comment by davidzchen** [comment]
+cc @andromedaf

**Comment by davidzchen** [comment]
@oquenchil Is there a way to work around this issue in the meantime?

**Comment by oquenchil** [comment]
Thanks for the detailed repro instructions, without them it would have taken much longer to debug what's going on.

There is no Bazel bug in this case.

You could use the following steps to find out what happened:
With `c++filt __ZN3foo3FooD1Ev` you will see that the missing symbol is the destructor. It's weird that every other symbol is found meaning that Bazel has the dynamic library, but just that one symbol is missing.

That is part of your custom class Foo. Not the auto-generated protobuf class. If you check the header you will see that you have ~Foo(); but you never define the destructor anywhere. You are overriding the default one without giving an implementation, so the symbol is not anyway and you get a runtime error. If you remove that line or implement an actual body for the destructor it should work.

**Comment by xindubawukong** [comment]
Thanks @oquenchil

**Comment by abhinavsingh** [comment]
@oquenchil jFYI, I ran into similar problem with an abstract class.

Per recommendation, I should define a virtual destructor, but upon doing do I run into `dyld: lazy symbol binding failed: Symbol not found: __ZN12DllInterfaceD2Ev`.  If I complete the destructor implementation in virtual class or simply remove the destructor, it works, but then I have memory leaks, as derived class destructor is not being called.

I am still digging further to confirm if this is really related to `bazel`, but frankly I am confused right now by this error.

**Comment by abhinavsingh** [comment]
> @oquenchil jFYI, I ran into similar problem with an abstract class.
> 
> Per recommendation, I should define a virtual destructor, but upon doing do I run into `dyld: lazy symbol binding failed: Symbol not found: __ZN12DllInterfaceD2Ev`. If I complete the destructor implementation in virtual class or simply remove the destructor, it works, but then I have memory leaks, as derived class destructor is not being called.
> 
> I am still digging further to confirm if this is really related to `bazel`, but frankly I am confused right now by this error.

For anyone running into this, see https://stackoverflow.com/a/24317259/414221
