### ISSUE TITLE
Don't require a system-installed Python interpreter for bootstrapping

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8446]
Forked from discussion in #7947. On windows, we can have the native launcher take on the [responsibilities](https://github.com/bazelbuild/bazel/issues/7947#issuecomment-494981489) of the stub script, in particular extracting the runfiles. This means it can use any Python runtime to launch the user code, including a runtime in runfiles.

We should also consider creating a native launcher for non-Windows platforms to do the same, so we don't need the `#!/usr/bin/env python` shebang.

Finally, we can consider merging the zip file into the launch to create a self-extracting native executable.

**Comment by abergmeier** [comment]
> We should also consider creating a native launcher for non-Windows platforms to do the same, so we don't need the #!/usr/bin/env python shebang.

Can you write up a proposal for goals and rough ideas?
