### ISSUE TITLE
$-escape does not remove escape in ctx.expand_location

### ISSUE THREAD

**Issue by ehthayer** [bazelbuild/bazel#8447]
### Description of the problem / feature request:

$-escape is not removed from the output of ctx.expand_location()

### Feature requests: what underlying problem are you trying to solve with this feature?

bazel_build/rules_docker uses ctx.expand_location() to process jvm_flags and args.  We'd like to include environment variable references in our java containers that are substituted by a utility function.  Although we could change the syntax of the utility function to accept $$ instead of $, the ctx.expand_location() functionality is inconsistent with the deprecated ctx.expand_make_variables() and with how the `cmd` argument is processed in `genrule`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The following rule when applied prints "$$FOO" rather than "$FOO"

```
def _impl(ctx):
    print("ctx.expand_location() = " + ctx.expand_location("$$FOO"))

expand_location = rule(implementation = _impl)
```
### What operating system are you running Bazel on?

mac os

### What's the output of `bazel info release`?

release 0.25.2

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

an internal github enterprise serivce.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
