### ISSUE TITLE
pkg_tar does not rebuild when filegroup references directory

### ISSUE THREAD

**Issue by rgatti** [bazelbuild/bazel#8450]
### Description of the problem / feature request:

When `filegroup` references a directory instead of explicit files `pkg_tar` does not see changes.

```
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

filegroup(
    name = "does_not_work_src",
    srcs = ["src"],
)

pkg_tar(
    name = "does_not_work",
    srcs = [":does_not_work_src"],
    mode = "0644",
    package_dir = "/",
    strip_prefix = ".",
)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I would expect successive builds to update files inside the tarball when source files change.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone https://github.com/rgatti/bazel_filegroup_pkg_tar and run `./test.sh`.

The output shows first a working example when `filegroup` uses `glob`. Then, a non-working example when `filegroup` points directly to a directory.

### What operating system are you running Bazel on?

```
rgatti@thinkpad bazel-tar-test$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic
rgatti@thinkpad bazel-tar-test$ uname -a
Linux thinkpad 4.18.0-20-generic #21-Ubuntu SMP Mon May 6 18:45:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### What's the output of `bazel info release`?

I've tested this on the latest release 0.25.2 and on the latest master branch.

```
rgatti@thinkpad bazel-tar-test$ bazel info release 
release 0.25.2
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

I built the master branch using release 0.25.2 with `bazel build //src:bazel`.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
rgatti@thinkpad bazel$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://github.com/bazelbuild/bazel.git
39f31abb7c923bc9b7e24a19edf69427cbe7e8b5
39f31abb7c923bc9b7e24a19edf69427cbe7e8b5
```

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Here's the output of running `./test.sh` in my example project (https://github.com/rgatti/bazel_filegroup_pkg_tar).

```
rgatti@thinkpad bazel-tar-test$ ./test.sh

>> WORKING EXAMPLE
>> ----------------------------------------
>> Cleaning workspace
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
>> Run #1, writing 'run 1' to src/data
INFO: Analyzed target //:works (18 packages loaded, 139 targets configured).
INFO: Found 1 target...
Target //:works up-to-date:
  bazel-bin/works.tar
INFO: Elapsed time: 1.928s, Critical Path: 0.20s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 6 total actions
>> Run #2, writing 'run 2' to src/data
INFO: Analyzed target //:works (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:works up-to-date:
  bazel-bin/works.tar
INFO: Elapsed time: 0.258s, Critical Path: 0.13s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
>> Result: DIFFERENT
>> #1: 'run 1'
>> #2: 'run 2'

>> NON WORKING EXAMPLE
>> ----------------------------------------
>> Cleaning workspace
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
>> Run #1, writing 'run 1' to src/data
INFO: Analyzed target //:does_not_work (18 packages loaded, 139 targets configured).
INFO: Found 1 target...
Target //:does_not_work up-to-date:
  bazel-bin/does_not_work.tar
INFO: Elapsed time: 0.679s, Critical Path: 0.17s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 6 total actions
>> Run #2, writing 'run 2' to src/data
INFO: Analyzed target //:does_not_work (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:does_not_work up-to-date:
  bazel-bin/does_not_work.tar
INFO: Elapsed time: 0.155s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
>> Result: SAME
>> #1: 'run 1'
>> #2: 'run 1'
```

**Comment by benjaminp** [comment]
Bazel infamously does not correctly invalidate source directories. c64421bc35214f0414e4f4226cc953e8c55fa0d2 fixed this but behind a flag.

**Comment by rgatti** [comment]
Thank you for the commit reference. Seems like the documentation should be updated if the best practice is to always reference source files directly and the only workaround is a `host_jvm_args`.

**Comment by hlopko** [comment]
@ulfjack is there any progress planned on `-DBAZEL_TRACK_SOURCE_DIRECTORIES` rollout? Thanks!

**Comment by bradleyjames** [comment]
> Seems like the documentation should be updated if the best practice is to always reference source files directly

If I'm understanding this issue correctly the Concepts and Terminology article contains this documentation.  From https://docs.bazel.build/versions/master/build-ref.html#label_directory:

> In order to ensure correct incremental rebuilds (and re-execution of tests) after a change, the build system must be aware of the complete set of files that are inputs to the build (or test). When you specify a directory, the build system will perform a rebuild only when the directory itself changes (due to addition or deletion of files), but won't be able to detect edits to individual files as those changes do not affect the enclosing directory. Rather than specifying directories as inputs to the build system, you should enumerate the set of files contained within them, either explicitly or using the glob() function. (Use ** to force the glob() to be recursive.)

**Comment by ulfjack** [comment]
There isn't a good way to roll out -DBAZEL_TRACK_SOURCE_DIRECTORIES=1, except to enable it and see what breaks. Unfortunately, we can't easily make it a command option. I haven't had time to work on a rollout.

**Comment by janakdr** [comment]
I think this is working as documented. The rollout of tracking source directories is a separate issue.
