### ISSUE TITLE
exec_compatible_with not working with 0.26.0 (rc15)

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#8451]
### Description of the problem / feature request:

`exec_compatible_with` is in [bazel common definition](https://docs.bazel.build/versions/0.24.0/be/common-definitions.html#common-attributes),
working great with rules_scala's [`scala_junit_test`](https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L682)

It helps us define different execution env constraints.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
For some reason with bazel0.26.0 (rc15) it fails the build:
```
ERROR: /Users/ors/workspace/rules_scala/test/BUILD:346:1: //test:JunitTestWithDeps: no such attribute 'exec_compatible_with' in 'scala_junit_test' rule 
```

Please kindly check out my repro on [Wix's rules_scala fork](https://github.com/bazelbuild/rules_scala/compare/master...wix:bazel26?expand=1#diff-c40927b6657800717d4b0b498e1bad55R354) - try to build `//test/...`
(in `bazel 0.25.2` it still worked)

### What operating system are you running Bazel on?

Tested on both macos and linux

### What's the output of `bazel info release`?

```
release 0.26.0rc15
```
linked to #7499

**Comment by or-shachar** [comment]
@laurentlb @aehlig

**Comment by laurentlb** [comment]
Did it work with Bazel 0.25?

**Comment by or-shachar** [comment]
yes it did

**Comment by laurentlb** [comment]
Possibly related to https://github.com/bazelbuild/bazel/issues/8134 and https://github.com/bazelbuild/bazel/issues/8026

In particular, https://github.com/bazelbuild/bazel/commit/a0f88c076349f84cfc3aeae01bf4043affe9775d is touching the base rule classes.

**Comment by katre** [comment]
Yes, I clearly missed something in that commit. Investigating now.

**Comment by katre** [comment]
This is a regression, caused by a0f88c0. I have a workaround, and will send an actual fix shortly.

The workaround: add the flag `--incompatible_disallow_rule_execution_platform_constraints_allowed` to your build. I am in the process of making every target allow the `exec_compatible_with` attribute, and this flag will opt you into that behavior.

The fix will be to just change the default assumption in the `rule()` function.

**Comment by katre** [comment]
This is a release blocker for #7499.

**Comment by or-shachar** [comment]
Thanks!
