### ISSUE TITLE
The source jar does not contains resources files

### ISSUE THREAD

**Issue by natros** [bazelbuild/bazel#8457]
### Description of the problem / feature request:

I have this layout and I want to generate a jar with the sources:

```
.
├── BUILD.bazel
├── WORKSPACE
└── src
    └── main
        ├── java
        │   └── com
        │       └── github
        │           └── natros
        │               └── Foo.java
        └── resources
            └── com
                └── github
                    └── natros
                        └── conf.xml
```

The BUILD.bazel is a simple:

```python
java_library(
    name = "res",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
)
```

Generates the jar
```
$ bazel build //:res
INFO: Analyzed target //:res (14 packages loaded, 524 targets configured).
INFO: Found 1 target...
Target //:res up-to-date:
  bazel-bin/libres.jar
INFO: Elapsed time: 6.181s, Critical Path: 4.33s
INFO: 4 processes: 3 darwin-sandbox, 1 worker.
INFO: Build completed successfully, 5 total actions
```

and the jar with the sources
```
bazel build //:libres-src.jar
INFO: Analyzed target //:libres-src.jar (0 packages loaded, 1 target configured).
INFO: Found 1 target...
Target //:libres-src.jar up-to-date:
  bazel-bin/libres-src.jar
INFO: Elapsed time: 0.141s, Critical Path: 0.04s
INFO: 1 process: 1 darwin-sandbox.
INFO: Build completed successfully, 2 total actions
```

The generated jar contains all files:

```
$ unzip -l bazel-bin/libres.jar
Archive:  bazel-bin/libres.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-01-2010 00:00   META-INF/
       48  01-01-2010 00:00   META-INF/MANIFEST.MF
        0  01-01-2010 00:00   com/
        0  01-01-2010 00:00   com/github/
        0  01-01-2010 00:00   com/github/natros/
       39  01-01-2010 00:00   com/github/natros/conf.xml
      270  01-01-2010 00:00   com/github/natros/Foo.class
---------                     -------
      357                     7 files
```

but the `libres-src.jar` is missing the resources:

```
 unzip -l bazel-bin/libres-src.jar
Archive:  bazel-bin/libres-src.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-01-2010 00:00   META-INF/
       48  01-01-2010 00:00   META-INF/MANIFEST.MF
        0  01-01-2010 00:00   com/
        0  01-01-2010 00:00   com/github/
        0  01-01-2010 00:00   com/github/natros/
       48  01-01-2010 00:00   com/github/natros/Foo.java
---------                     -------
       96                     6 files
```

### What operating system are you running Bazel on?

> macOS 10.14.15
> java version "1.8.0_212"
> Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
> Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)

### What's the output of `bazel info release`?

> release 0.25.3

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> git@github.com:natros/bazel-jar-resources.git
> 74514e1f1f9cd857e3410821f39da0718a91d3d9
> 74514e1f1f9cd857e3410821f39da0718a91d3d9

**Comment by iirina** [comment]
According to the [documentation](https://docs.bazel.build/versions/master/be/java.html) this is working as intended. Can you describe your use case and why it requires the resources in the source jar?

**Comment by natros** [comment]
I'm used to maven and when maven packs the sources includes all files in src/main/{java,resources}.

My use case is to deploy/share the sources to be included in another project that uses GWT and needs .java, .ui.xml and .gwt.xml files. The other project does not use bazel.

**Comment by iirina** [comment]
Thanks for the explanations @natros!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
