### ISSUE TITLE
implement circuit breaking for remote caching

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8460]
After a series of failures to fetch a remote result the remote cache should stop trying for a while and then try to recover after some time. This is useful for people working under bad / unreliable network conditions or even without a network.

**Comment by werkt** [comment]
I can resurrect this, perhaps with more specific requirements if it satisfies this

https://github.com/werkt/bazel/tree/remote-cooldown

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
