### ISSUE TITLE
pkg_tar does not support tags

### ISSUE THREAD

**Issue by eytankidron** [bazelbuild/bazel#8462]
When running a build remotely, setting tags=["local"] in a pkg_tar rule appears to have no effect, causing the pkg_tar to still run remotely.

I suspect this is a more general problem of the pkg_tar rule (or rather the [pkg_tar macro](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/pkg/pkg.bzl#L265)) not passing the tags property downstream.

**Comment by hlopko** [comment]
Yes there is a more general problem, and @ishikhman is working on fixing it.

@ishikhman is there a tracking issue so I can close this one as duplicate? Thank you!

**Comment by ishikhman** [comment]
@hlopko here it is: https://github.com/bazelbuild/bazel/issues/7766

**Comment by hlopko** [comment]
Thank you! Therefore closing in favor of #7766.
