### ISSUE TITLE
Compiling a cc_library with multiple toolchains

### ISSUE THREAD

**Issue by Monnoroch** [bazelbuild/bazel#8463]
### Description of the problem / feature request:

Can I compile the same `cc_library` with multiple toolchains in the same `bazel test //...` run?

Here is a hypothetical example of my BUILD file:

```
# A library with some C code.
cc_library(
  name = "my_lib",
  ...
)

# A unit test for `my_lib`. It's a normal unit test that needs to be compiled for the host platform and executed when running `bazel test //...`.
cc_test(
  name = "my_test",
  deps = [":my_lib"],
)

# This is a binary of a firmware image compiled for an ARM device with a RTOS and a bootloader built in. I want this to be compiled when I run `bazel test //...`.
cc_binary_from_my_toolchain(
  name = "my_binary",
  deps = [":my_library"],
)
```

Using my current knowledge of Bazel I need to create two separate, but almost identical `cc_library` targets with different toolchains, but this becomes a nightmare when I have libraries depending on libraries depending on libraries (I have about a hundred of C packages). Is it possible to not do that? If not, can it be done with a custom `cc_library` rule? If still not, is something like this planned?

###  Have you found anything relevant by searching the web?

Just some issues in this repo:

https://github.com/bazelbuild/bazel/issues/7868 (similar question for Java)
https://github.com/bazelbuild/bazel/issues/7020

**Comment by oquenchil** [comment]
You would have to call `bazel test` with different configuration flags, see https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html.

You wouldn't need to replicate the targets but you would have to call `bazel test` twice.

**Comment by Monnoroch** [comment]
@oquenchil that is not possible, unfortunately. I have protocol buffers that need to be compiled with protoc (that I need to compile for Linux/Clang) into C sources that I need to then compile for ARM/RTOS with a different toolchain. So there's a build dependency graph that requires me building with two toolchains in the same `bazel` call. A global C++ toolchain flag will obviously not work for me.

**Comment by oquenchil** [comment]
I'm not sure your initial BUILD file example illustrates that. From that example it looks like you have a cc_test and a cc_binary, they don't depend on each other, so they could be built with different configurations. Could you write the exact BUILD file that you are trying to build and doesn't work?

Regarding your last message about protoc, protoc is not part of the C++ toolchain. It doesn't need the toolchain to convert protobuf to C++ files. If you are building protoc yourself, then it should be built with the host configuration anyway, so it should work.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
