### ISSUE TITLE
Compiling a cc_binary with multiple defined values

### ISSUE THREAD

**Issue by Monnoroch** [bazelbuild/bazel#8464]
### Description of the problem / feature request:

I have a `cc_library` with a compile-time variable. Many other libraries depend on it recursively. I also have a `cc_binary` that indirectly uses this library. I want to compile two (or more) versions of this binary with a different value for this variable. Hypothetical example:

`my_lib.h`:
```
#define MY_VALUE
```

`my_lib.cc`:
```
int global_variable = MY_VALUE;
```

`BUILD.bazel`:
```
cc_library(
  name = "my_library",
  hdrs = ["my_lib.h"],
  srcs= ["my_lib.cc"],
  ...
)

cc_binary(
  name = "my_binary_1",
  deps = [":my_library"],
  defines = {"MY_VALUE": "1"},
)

cc_binary(
  name = "my_binary_10",
  deps = [":my_library"],
  defines = {"MY_VALUE": "10"},
)
```

With my current knowledge of Bazel I have to copy-paste each library for each value to do this. Instead I would only like to copy-paste the final artifact target. In my example I expect `bazel build //...` to build both binaries. Is this possible? If not, is it planned to support something like this?

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/7939, but I think it's something else.

**Comment by kkiningh** [comment]
Not exactly what you're asking for, but this how I would do this.

```python
[cc_library(
   name = "my_library_" + str(i),
   hdrs = ["my_lib.h"],
   srcs= ["my_lib.cc"],
   copts = ["-DMY_VALUE=" + str(i)],
) for i in range(0, 10)]

[cc_binary(
   name = "my_binary_" + str(i),
   deps = [":my_library_" + str(i)],
 ) for i in range(0, 10)]
```

Depending on your use case, a macro might make more sense.

**Comment by Monnoroch** [comment]
@kkiningh, yes this is what I meant. However I don't have one library, I have a large tree of about a hundred libraries depending on each other. And every one of them would have to have two versions for just one variable. And each of them would have to use dependencies with a correct suffux. Now what happens if I were to have ten variables? Then each library would have to have a thousand versions! This is completely unmaintainable and it makes me think that Bazel could help with that.

**Comment by oquenchil** [comment]
Is this for different configurations? If it is then https://stackoverflow.com/questions/39278204/bazel-platform-specific-c-defines might be useful.

If not, then you can just have your build graph with one version of each target and build with different define values for the defines by passing the flag -copts=-DMY_VALUE

**Comment by Monnoroch** [comment]
@oquenchil can you please give me example to be 100% sure I understand your idea? And yes, this is for different configurations, but it has nothing to do with platforms. We just build a binary with three different subsets of features enabled.

**Comment by oquenchil** [comment]
You would have to pass the configuration option to bazel like `bazel build -copts=-DMY_VALUE=1`. So if you have 100 different defines you would have to call bazel 100 times. But you don't have to repeat the targets.

**Comment by Monnoroch** [comment]
@oquenchil I see. Unfortunately, this pretty much guarantees long term CI issues when someone forgot to add another call when a new feature is introduced. But thanks!

Can this become a feature request for supporting build-time flags though? They are already kind of supported since you can set them in `defines`, but not really because this recursive scenario is impossible to implement nicely: either write macros to generate multiple targets for you `cc_librar`ies or call build/test many times to test all of them.

**Comment by oquenchil** [comment]
I think what you are requesting is something similar to this:
https://github.com/bazelbuild/bazel/issues/5076

What you are proposing with setting the defines in cc_binary does not work with the Bazel model. Dependencies are built and they don't know anything about dependents downstream. So propagating a value like this is not possible.

Since you mentioned that this is related to configurations, check if any of the other solutions proposed in #5076 work for you.

**Comment by Monnoroch** [comment]
Indeed, that case is pretty much exactly like my setup.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
