### ISSUE TITLE
pkg_deb breaks (again) under python3

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/bazel#8465]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

`pkg_deb` uses `make_deb.py`, which breaks under python3

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```
# tools/python/BUILD
py_runtime(
    name = 'py-3',
    visibility = [
        '//visibility:public',
    ],
    interpreter_path = '/usr/bin/python3',
    files = [],
)
```

```
# bazel.rc
build --python_top=tools/python:py-3
```

Then, `bazel build` *any* `pkg_deb` targets would yield something similar to the following:

```text
  (cd /home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-sandbox/1469/execroot/logi && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb '--output=bazel-out/k8-fastbuild/bin/pkg/git/tools/logi-git-tools_0.0.1_amd64.deb' '--changes=bazel-out/k8-fastbuild/bin/pkg/git/tools/logi-git-tools_0.0.1_amd64.changes' '--data=bazel-out/k8-fastbuild/bin/pkg/git/tools/data.tar' '--package=logi-git-tools' '--architecture=amd64' '--maintainer=LogiOcean Developers' '--version=0.0.1' '--description=The git tools every develoepr misses' '--distribution=unstable' '--urgency=medium')
Execution platform: @bazel_tools//platforms:host_platform

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-sandbox/1469/execroot/logi/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/bazel_tools/tools/build_defs/pkg/make_deb.py", line 355, in <module>
    main(FLAGS(sys.argv))
  File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-sandbox/1469/execroot/logi/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/bazel_tools/tools/build_defs/pkg/make_deb.py", line 327, in main
    version=GetFlagValue(FLAGS.version),
  File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/sandbox/linux-sandbox/1469/execroot/logi/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/make_deb.runfiles/bazel_tools/tools/build_defs/pkg/make_deb.py", line 301, in GetFlagValue
    flagvalue = flagvalue.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```
### What operating system are you running Bazel on?

Ubuntu 18.04.2

### What's the output of `bazel info release`?

0.25.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```text
ssh://git@git.corp.logiocean.com/LogiOcean/LogiOcean.git
e470971a1818ac19d370afc6651942fb21808451
6759bae30b35cbdb66b046a841c729db7d59c890
```

###  Have you found anything relevant by searching the web?

Not relevant

**Comment by qzmfranklin** [comment]
@brandjon 

This issue is of the exact same nature with https://github.com/bazelbuild/bazel/issues/6818:
> Python3 is not tested for rules such as `pkg_deb`.

This might have sounded similar, but I am a little surprised that no tests under python3 existed for so long for `pkg_deb`. Would like to see it change.

**Comment by qzmfranklin** [comment]
The offending line was committed by [this commit](https://github.com/bazelbuild/bazel/commit/70e3c339bea02f6e9273b13de11d078ca6c2752f#diff-687105bbda36ddcad584169fe214e7e1).

**Comment by qzmfranklin** [comment]
Looked around a bit, a bit surprised to find that there is no tests for `make_deb.py`.

Adding tests for it should help prevent such regressions in future releases.

**Comment by aiuto** [comment]
We are going to address pkg rules when we get them out of bazel core
https://docs.google.com/document/d/1GAbAiW0nVbxGlwsdXhFIcn3owlZJkMJiXBt-ttA9z_k/edit#heading=h.5mcn15i0e1ch

**Comment by qzmfranklin** [comment]
@aiuto

Thanks for the info!

I am unblocked by making a copy of the `pkg_deb` rule from Bazel core.

Agree that the pkg rules should be separated from bazel core.

Happy for now.

**Comment by aiuto** [comment]
Fixed in rules_pkg. https://github.com/bazelbuild/rules_pkg/issues/35
