### ISSUE TITLE
Lazy loading of external repositories in BUILD files

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#8466]
### Description of the  feature request:
Given the following BUILD file at the root of my WORKSPACE:

```
load("@bazel_gazelle//:def.bzl", "gazelle")
load("@com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier")
load("@build_bazel_rules_nodejs//:defs.bzl", "nodejs_binary")

nodejs_binary(
  name = "some-binary",
  data = ["some-data.js"],
  entry_point = "__main__/some-data.js",
)

gazelle(
    name = "gazelle",
    prefix = "github.com/a/b",
)

buildifier(
    name = "buildifier",
)
```

When I run `bazel run //:gazelle` and I do not have the `com_github_bazelbuild_buildtools`, or the `build_bazel_rules_nodejs` or any other repository I load on my disk yet (which is defined e.g. as an `http_archive` in the `WORKSPACE` file) then it will download that repository even though I do not need it for running this command, just because it is being loaded in the same build file. It would be great if it would not have to download any external repositories that are not needed for the current build.

### Feature requests: what underlying problem are you trying to solve with this feature?

Save the download of a potentially expensive, unnecessary external repository, that might ever just be used by a subset of the team. 

The two main use cases for us, we define a lot of different "global" binaries in the top level `BUILD` file, such as linters for specific langauges, tools related to package management, or specific deploys. And usually developers are just ever going to run a subset of these things on their machine, so imo they should not need to have to download and store this on their disk if not necessary.

The other case I have noticed, is some rules provide a function to load external dependencies in, such as rules_python: https://github.com/bazelbuild/rules_python#consuming-pip-dependencies - if now the requirements file got updated and I build something that does not have any external dependencies in the same package I still have to wait for the pip packages to have to be reinstalled. It would be nice if it does not have to be.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use the given `BUILD` file above with all these repositories defined in the `WORKSPACE` as a `http_archive` or a `git_repository` with a version you do not have cached locally, then `bazel run` any of the binaries and see that on first execution the dependencies of all binaries are being downloaded.

### What operating system are you running Bazel on?

Elementary OS 5 (Ubuntu 18.04)

### What's the output of `bazel info release`?

release 0.26.0rc16

###  Have you found anything relevant by searching the web?

The topic has been first discussed here around the topic of recursive workspaces here https://groups.google.com/forum/#!topic/bazel-dev/YGV4_pMIMmA but I realised this actually could be useful to anyone.

**Comment by davido** [comment]
Gerrit Code Review project has exactly the same issue with go-lang dependency. It was added only to run Polymer UI for frontend developers. When a backend developer just building Java artifacts, then 100+ MB big go-lang image is downloaded, even though it's not needed to build plain Java. To reproduce run `bazel build :headless` in Gerrit [repository](https://gerrit.googlesource.com/gerrit).

**Comment by laurentlb** [comment]
The workaround is to split the BUILD file. For example, create a gazelle directory and do `bazel run //gazelle`.

Given the current evaluation model, it can be difficult to implement lazy loading.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
