### ISSUE TITLE
Compilation of Bazel source using Bazel Head on RBE fails due to spawn strategy rejecting genrule

### ISSUE THREAD

**Issue by smukherj1** [bazelbuild/bazel#8469]
### Description of the problem / feature request:
Related to #7480. We have tests that run builds using RBE to build Bazel source using Bazel head. These tests started failing since May 16 with the following error:
```
ERROR: /remote_build_test_container/project_src/tools/osx/BUILD:17:1: Executing genrule //tools/osx:xcode-locator-genrule failed: No usable spawn strategy found for spawn with mnemonic Genrule.  Your --spawn_strategyor --strategy flags are probably too strict. Visit https://github.com/bazelbuild/bazel/issues/7480 for migration advises
```

Our tests  run `bazel test` using `--spawn_strategy=remote` on the following targets
```
//src/test/java/...
-//src/test/java/com/google/devtools/build/android/...
-//src/test/java/com/google/devtools/build/lib:sandbox-tests
-//src/test/java/com/google/devtools/build/lib/shell:CommandUsingLinuxSandboxTest
-//src/test/java/com/google/devtools/build/lib:vfs_inmemoryfs_test
-//src/test/java/com/google/devtools/build/lib/blackbox/tests:PythonBlackBoxTest
-//src/test/java/com/google/devtools/build/lib/rules/objc:ObjcRulesTests",
-//src/test/java/com/google/devtools/build/lib:worker-tests
-//src/test/java/com/google/devtools/build/lib/buildeventstream/transports:BuildEventTransportTest-//src/test/java/com/google/devtools/build/lib/blackbox/tests/workspace:BazelEmbeddedSkylarkBlackBoxTest
```

### Feature requests: what underlying problem are you trying to solve with this feature?
Any idea how to fix the error? Is there a test that depends on `//tools/osx:xcode-locator-genrule` which we can disable?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Build Bazel source using Bazel head on RBE

### What operating system are you running Bazel on?
Kokoro GCP Ubuntu VM

### What's the output of `bazel info release`?
Don't have this info. It's Bazel built from Bazel source HEAD, so not an official release or RC.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.
Ran the following on the Kokoro Ubuntu VM using Bazel 0.25.0
```
+git clone https://github.com/bazelbuild/bazel.git
Cloning into 'bazel'...
+ cd bazel
+ bazel build //src:bazel --spawn_strategy=standalone
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
Don't have this info available but this test has been failing consistently since May 16, 2019.

###  Have you found anything relevant by searching the web?
#7480 is directly related. However, we would like guidance on whether we should be excluding certain test targets when we use Bazel built from HEAD to build Bazel source at HEAD.

### Any other information, logs, or outputs that you want to share?
N/A

**Comment by smukherj1** [comment]
FYI @nlopezgi

**Comment by buchgr** [comment]
@smukherj1 in Bazel HEAD and starting with Bazel 0.27 you'll no longer need to set any `--spawn_strategy=` flags. Remove the flag and it should work again.

**Comment by nlopezgi** [comment]
Hi @buchgr,
thanks for the clarifications.
https://github.com/bazelbuild/bazel-toolchains/pull/549 adds a test to validate this works as intended with 0.27.0rc1 (spoiler, it is).
also fyi @agoulti 
Thanks!
