### ISSUE TITLE
Specify BUILD file for external archives

### ISSUE THREAD

**Issue by Qix-** [bazelbuild/bazel#847]
This is potentially a feature request.

Right now my biggest hangup with Bazel is the fact no library I use uses Bazel. Therefore, they don't have `BUILD` files.

I don't mind writing them for all of these repositories, but I want to keep some sort of modularity within my project and not have to include each project inline.

Is there a way to specify a `BUILD` file for repositories or archives [obtained externally](http://bazel.io/docs/be/workspace.html#git_repository)?

I see you can do this [with the `new_` family of functions](http://bazel.io/docs/external.html) but not with anything used externally.

**Comment by damienmg** [comment]
You mean like a [new_git_repository](http://bazel.io/docs/be/workspace.html#new_git_repository)?

**Comment by Qix-** [comment]
_(sigh)_ It's late, don't judge me. Sorry for the wasted time.

Thanks!

**Comment by damienmg** [comment]
No worry, I like when we are so fast abswering feature request that we think of it before users ask for it :D

**Comment by Qix-** [comment]
Hahaha :+1: That's the way to run a project.
