### ISSUE TITLE
Document/link bazel upgrade process

### ISSUE THREAD

**Issue by EricBurnett** [bazelbuild/bazel#8470]
### Description of the problem / feature request:

The upgrade process for switching bazel versions should be well documented and easy to find.

### Feature requests: what underlying problem are you trying to solve with this feature?

Bazel users don't appear to know about (or at least, follow) bazel's best practices around version upgrades, and when I search for information as if I was in their shoes, it's very hard to find and not user-centric. [backwards-compatibility](https://docs.bazel.build/versions/master/backward-compatibility.html) is the best existing doc, but is centered on the compatibility process itself rather than the user-centric "how do I upgrade?".

I recommend:

 - Write a user-centric doc for best practices doing upgrades.
 - Include link to [bazelisk](https://github.com/bazelbuild/bazelisk).
 - Include script for users doing a bump from one version to the next - e.g. step-by-step guide of finding incompatible changes that will break in the next version.
 - Include script for users skipping versions. How can they best figure out the necessary changes - Validate against each intermediate version along the way, or something easier?
 - Link to this doc from each entry in [bazel releases](https://github.com/bazelbuild/bazel/releases), for easy discoverability.
 - Make sure it's searchable under obvious keywords - "bazel upgrade", "update bazel version", etc.

### What's the output of `bazel info release`?

Bazel 0.25 is the latest, as of when I'm filing this bug.

**Comment by EricBurnett** [comment]
@dslomov

**Comment by laurentlb** [comment]
Thanks!
Note that release notes include a section about upgrading, but we could do better (or be more consistent), e.g. https://blog.bazel.build/2019/03/26/bazel-0.24.html

Bazelisk was just moved to bazelbuild organization. We can now advertise it more widely.

**Comment by EricBurnett** [comment]
Huh, interesting - I didn't realize bazel releases ended up on the blog too, nor that it has different content than the releases page. (E.g. https://blog.bazel.build/2019/05/28/bazel-0.26.0.html vs https://github.com/bazelbuild/bazel/releases/tag/0.26.0).

I checked, and if I search _"bazel versions"_ or _"bazel releases"_ I only find the releases page; if I search for a release by name (_"bazel 0.25"_), however, I can find the blog post for it. Should these be cross-linked, and/or contain the same content? Because I definitely think the blog post is an improvement on the raw release notes, but had no idea it existed and didn't find it while researching this bug.

**Comment by laurentlb** [comment]
I did it for Bazel 0.23: https://github.com/bazelbuild/bazel/releases/tag/0.23.0
I'll advise other release managers to do the same (generated release notes are quite bad and are often misleading).

**Comment by dslomov** [comment]
I do not think we should _prescribe_ a specific upgrade process. Organizations differ in how their codebases are structured and in their workflows, and the hope is that organizations will design the processes that work for them based on a _policy_ that Bazel project has for rolling out incompatible changes. That said, it is useful to document `bazelisk --migrate` better and provide an _example_ upgrade process. 

Note that this whole space will change very soon as we increase the stability windows and switch to real semantic versioning.

**Comment by laurentlb** [comment]
Shall we move all the upgrade notes from the release announcement to a dedicated page?

The release announcement includes a link to that page and can focus on the more interesting changes. The upgrade page can then have more details. It gives the general recommendations. For each release, there's a section with the flags that flipped. Users would need to upgrade multiple versions will have everything they need in one page.

**Comment by EricBurnett** [comment]
I think we can mostly call this done? I see https://docs.bazel.build/versions/master/updating-bazel.html exists now and pretty much covers this bug, is linked to off the blog post for releases, and is findable under 'updating bazel'. 

Thanks Dmitry!

I do observe that searching 'bazel releases' still leads to https://github.com/bazelbuild/bazel/releases, and that links from there to the blog posts are hit-or-miss (e.g. 0.28.0 does, but 0.29.1, 0.29.0, and 0.28.1 do not). I'd be nice to link to the most relevant blog post from _all_ releases, including point releases, but that's a lot less pressing now that there's a general doc that can be found.

**Comment by laurentlb** [comment]
Documentation is here: https://docs.bazel.build/versions/master/updating-bazel.html

I think this can be closed?
