### ISSUE TITLE
"WORKSPACE file can not be a symlink" exception thrown: backward-incompatible bug

### ISSUE THREAD

**Issue by irengrig** [bazelbuild/bazel#8475]
Bazel 0.26,
if the WORKSPACE file is a symlink, an exception is thrown.
This is not intended change, it should be thrown only if managed directories are used in the project.

**Comment by hlopko** [comment]
Thanks for working on the fix! :)

**Comment by hlopko** [comment]
FYI, this issue also breaks tulsi (https://buildkite.com/bazel/tulsi-bazel-darwin/builds/161). CC @DavidGoldman. Patch release with the fix is being prepared.
