### ISSUE TITLE
bazel build run sub package binary and generate a new sub package 

### ISSUE THREAD

**Issue by dxj910804** [bazelbuild/bazel#8486]
### Description of the problem / feature request:

Writing here to check if below feature is already supported by bazel or is there any plan to support. 

Here's the layout:
//parent ==> import //parent/generated
//parent/gen 
//parent/generated

the expected sequence is:
1  build //parent/gen module 
2 run //parent/gen module to generate //parent/generated module. //parent module depends on files in //parent/generated module.
3 build and test //parent

I was adding genrule named as "gen_model" to generate //parent/generated but not able to reach //parnet/gen by all means using srcs, data or deps (last two are not allowed).

In parent BUILD.bazel
```
genrule(
    name = "gen_model",
    srcs = ["//parent/gen:gen"],
    outs = ["generated_model.go"],
    cmd = "./gen",
)

```
```
go_library(
    name = "go_default_library",
    srcs = [
        "generated_model.go",
        "main.go",
    ],
    visibility = ["//visibility:private"],
    deps = [
        "//parent/generated:go_default_library",
        ":gen_model",
    ],
)
```

In gen BUILD.bazel
```
go_binary(
    name = "gen",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
```

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

release 0.25.2

### Any other information, logs, or outputs that you want to share?

in deps attribute of go_library rule //parent:go_default_library: '//parent:gen_model' does not have mandatory providers: 'GoLibrary'. Since this rule was created by the macro 'go_library_macro', the error might have been caused by the macro implementation in /home/go/src/golang/parent/BUILD.bazel:10:1

**Comment by aiuto** [comment]
//parent/gen:gen is a *tool* used by your genrule. I think you want

genrule(
    name = "gen_model",
    tools= ["//parent/gen:gen"],
    outs = ["generated_model.go"],
    cmd = "$(location //parent/gen:gen)"
)

**Comment by jin** [comment]
@dxj910804 please try out the solution provided by @aiuto, and feel free to reopen this issue if you're still running into problems.
