### ISSUE TITLE
Only stamp on optimized/release builds

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel#849]
I'd like to set our repo up so by default, -c dbg or -c fastbuild run without stamping, but -c opt runs with stamping enabled.

bazel.rc:
build --stamp=yes

will do it for everything.  Is there a way to only enable stamping for -c opt by default?

**Comment by ulfjack** [comment]
There's no way to do that right now, but I think it's a very valuable
feature request. We might want that internally as well.

**Comment by dslomov** [comment]
Assigning to Damien for further triage.

**Comment by damienmg** [comment]
Ok that's a valuable FR but we haven't the bandwidth to work on it right now.

As a workaround you can put that in your bazelrc:

```
build:opt --stamp
build:opt -c opt

build:dbg --nostamp
build:dbg -c dbg

build:fastbuild --nostamp
build:fastbuild -c fastbuild
```

And then call bazel with `--config dbg` instead of `-c dbg`

**Comment by helenalt** [comment]
@ulfjack given the workaround provided by damenmg above, is this still a feature worth considering or do we close this issue?

**Comment by ulfjack** [comment]
I think that's good enough.
