### ISSUE TITLE
<name>_deploy.jar differs on Windows and Unix because of build-data.properties

### ISSUE THREAD

**Issue by Xjs** [bazelbuild/bazel#8497]
### Description of the problem / feature request:

`build-data.properties` contains different strings on Windows and Unix, and partially mixed up line endings on Windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have created and documented a test case on https://github.com/Xjs/bazel-java-test/blob/master/case1.md .

### What operating system are you running Bazel on?

These test cases were produced on Windows 10 (Insider Preview) and Ubuntu 18.04.

### What's the output of `bazel info release`?

Tested with `release 0.25.2`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:Xjs/bazel-java-test.git
70202cc99f788de3fd89c48be169bb09946a86e8
70202cc99f788de3fd89c48be169bb09946a86e8
```

###  Have you found anything relevant by searching the web?

Issue https://github.com/bazelbuild/bazel/issues/6575 may be related.

**Comment by iirina** [comment]
cc: @laszlocsomor

**Comment by laszlocsomor** [comment]
Stellar bug report with the test cases and their descriptions -- thank you!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by fmeum** [comment]
One part of this should be fixed by https://github.com/bazelbuild/bazel/pull/18073.
