### ISSUE TITLE
Improve error message for incompatible_string_join_requires_strings

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8507]
When the flag `--incompatible_string_join_requires_strings` is enabled, Baze checks that each element is a string (see https://github.com/bazelbuild/bazel/issues/7802).

However, the error message is just a type error. This can be confusing for users who are upgrading Bazel. The error message should at least include the name of the flag.

Since we're flipping the flag in Bazel 0.27, it would be great to improve the error message before that. @jin, @c-parsons, do you have time to do it this week? (tomorrow is public holiday in Germany)

Thanks!

**Comment by jin** [comment]
I can take a stab at this.
