### ISSUE TITLE
Latest green Bazel breaks rules_swift with access to File.owner field

### ISSUE THREAD

**Issue by allevato** [bazelbuild/bazel#8509]
rules_swift's Buildkite pipeline is showing the repository broken on both Mac and Linux with the latest green Bazel.

Build results: https://buildkite.com/bazel/rules-swift-swift/builds/521#27d3f19d-06f8-4e28-b24a-6220378fd452

The error is produced by an access to `File.owner`, but the error message is just a string representation of the `File` object without any other information:

```
ERROR: /Users/buildkite/builds/bk-imacpro-8/bazel/rules-swift-swift/examples/xplatform/proto/BUILD:9:1: in @build_bazel_rules_swift//swift/internal:swift_protoc_gen_aspect.bzl%swift_protoc_gen_aspect aspect on proto_library rule //examples/xplatform/proto:example_proto:
--
  | Traceback (most recent call last):
  | File "/Users/buildkite/builds/bk-imacpro-8/bazel/rules-swift-swift/examples/xplatform/proto/BUILD", line 9
  | @build_bazel_rules_swift//swift/internal:swift_protoc_gen_aspect.bzl%swift_protoc_gen_aspect(...)
  | File "/private/var/tmp/_bazel_buildkite/046792c74cd8960abeff40131c81a07e/external/build_bazel_rules_swift/swift/internal/swift_protoc_gen_aspect.bzl", line 302, in _swift_protoc_gen_aspect_impl
  | swift_common.compile(actions = aspect_ctx.actions, bin_..., <8 more arguments>)
  | File "/private/var/tmp/_bazel_buildkite/046792c74cd8960abeff40131c81a07e/external/build_bazel_rules_swift/swift/internal/api.bzl", line 489, in swift_common.compile
  | declare_compile_outputs(actions = actions, copts = (copts ...), <3 more arguments>)
  | File "/private/var/tmp/_bazel_buildkite/046792c74cd8960abeff40131c81a07e/external/build_bazel_rules_swift/swift/internal/compiling.bzl", line 183, in declare_compile_outputs
  | derived_files.intermediate_object_file(actions, target_name = target_name, ...)
  | File "/private/var/tmp/_bazel_buildkite/046792c74cd8960abeff40131c81a07e/external/build_bazel_rules_swift/swift/internal/derived_files.bzl", line 93, in derived_files.intermediate_object_file
  | _intermediate_frontend_file_path(target_name, src)
  | File "/private/var/tmp/_bazel_buildkite/046792c74cd8960abeff40131c81a07e/external/build_bazel_rules_swift/swift/internal/derived_files.bzl", line 71, in _intermediate_frontend_file_path
  | owner_relative_path(src)
  | File "/private/var/tmp/_bazel_buildkite/046792c74cd8960abeff40131c81a07e/external/build_bazel_rules_swift/swift/internal/utils.bzl", line 162, in owner_relative_path
  | file.owner
  | File:[[<execution_root>]bazel-out/darwin-fastbuild/bin]examples/xplatform/proto/example_proto.protoc_gen_pb_swift/examples/xplatform/proto/example.pb.swift
```

Digging through recent commits, this one looks relevant: https://github.com/bazelbuild/bazel/commit/9dd7e8ed7931274b0c5b791e1c076140dcf7b74f

Specifically, the part that says "This means that it is no longer safe to call #getArtifactOwner, #getOwnerLabel, etc. on an artifact if it was created by the configured target that is currently being analyzed."

That's exactly what this code is doing—an aspect declares a file, then calls a function that ends up accessing its `owner` property.

If `owner` is no longer acceptable to call on files generated by the current target, what should i replace that logic with?

cc @janakdr

**Comment by allevato** [comment]
For additional context, this is why that logic exists: https://github.com/bazelbuild/rules_swift/blob/master/swift/internal/utils.bzl#L150-L196

This is called when we declare `.o` files for each `.swift` file in a compile. We use the owner-relative path to the source file as the trailing part of a path relative to an `_objs` directory. In other words, the file `//foo/bar:baz/quux.swift` will produce the `.o` file `bazel-bin/foo/bar/_objs/baz/quux.swift.o`.

In this particular case, the `.swift` file is also generated, specifically by the same aspect analysis that goes on to compile it, which I believe is why this error is now appearing.

**Comment by janakdr** [comment]
Currently rolling back the change, sorry for the trouble.

**Comment by allevato** [comment]
Thank you! 🙂
