### ISSUE TITLE
`./compile.sh` without Android is broken

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#851]
c74d3e4d9f2340c4a53f818f052df72a824660c0 broke running `./compile.sh test` in a fresh repository.

```
ERROR: no such target '//external:android_ndk_for_testing': target 'android_ndk_for_testing' not declared in package 'external' defined by /home/brian/bazel/WORKSPACE.
```

I think @mrdomino is the author of the commit. Any ideas on how to make it still work without running a script before doing `./compile.sh`? Maybe uncomment the lines in WORKSPACE and have compile.sh run `scripts/workspace_user.sh` automatically if `WORKSPACE.user` doesn't exist?

**Comment by mrdomino** [comment]
Oof. Obvious oversight on my part. We probably ought to keep the binds to
//:dummy for those targets with instructions to remove them. (It'd be great
to not require manual editing to enable android targets but nothing springs
to mind.)

**Comment by damienmg** [comment]
I already sent out a code review for that. do not worry :)

**Comment by mrdomino** [comment]
Great, thank you.
