### ISSUE TITLE
Allow Args values as an argument to Args.add_*

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#8515]
### Description of the feature request:

The `Args` type has a family of `add_*` methods. It should be legal to pass not just files, depsets and lists but also other Args to these methods.

Example:

```python
args1 = ctx.actions.args()
args1.add_all(["--foo", "--bar"])

args2 = ctx.actions.args()
args2 = ctx.actions.add_all(args1, format_each="--opt=%s")
```

### Feature requests: what underlying problem are you trying to solve with this feature?

It is sometimes necessary to build an argument list in one place, feed it to one command, then post-process it in another place before feeding it to another command. For example, you might have a compiler and a static analysis tool that calls the compiler (and therefore needs to forward the original compiler flags). Currently, the only way to support this use case is to keep arguments as a `List` for as long as possible (which induces more work during the analysis phase), because `Args` cannot be composed using arbitrary transformations like `map_each` or `format_each`. In fact `Args` cannot even be composed by concatenation (see #6230).

This feature would resolve #6230 as a side-effect as well. `args2.add_all(args1)` would have the effect of merging two argument lists.

### What's the output of `bazel info release`?

v0.24

###  Have you found anything relevant by searching the web?

#6230 makes a related feature request.

**Comment by brandjon** [comment]
Let's dedup this into #6230 as a proposed syntax.
