### ISSUE TITLE
Is there any way to keep the assert working when build -c dbg?

### ISSUE THREAD

**Issue by mirsking** [bazelbuild/bazel#8516]
### Description of the problem / feature request:

> Is there any way to keep the assert working when build -c dbg? 
Or any option to remove -DNDEBUG flag in the dbg build type? 

### What operating system are you running Bazel on?

> Ubuntu 16.04

### What's the output of `bazel info release`?

> release 0.17.1

###  Have you found anything relevant by searching the web?

> No

**Comment by aiuto** [comment]
There is not enough here to even answer. This does not sound like a Bazel question. It seems to be more suited to a general C++ list or answer board. Can you provide a code sample and what you mean by "keep the assert working"?

**Comment by mirsking** [comment]
Sorry, but I have found a work around. I'll just close this. Thank you anyway.
