### ISSUE TITLE
Prevent "Deleting stale sandbox base" from showing up when not necessary

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#8525]
What's the reason for [printing](https://github.com/bazelbuild/bazel/blob/536a166270590a8dbc701718550383f3a07cc763/src/main/java/com/google/devtools/build/lib/sandbox/SandboxModule.java#L220) the `INFO: Deleting stale sandbox base /some/long/uuidy/path` message? I find it non-actionable and noisy.

**Comment by benjaminp** [comment]
Presumably you are experiencing https://github.com/bazelbuild/bazel/issues/7095, which is unrelated to the sandbox base.

**Comment by thundergolfer** [comment]
Thanks! Yeah this looks like a more promising lead. 

I'm trying to find more info what causes 'stale' sandboxes. I don't remember seeing this log before but maybe it's new in the version of Bazel we've upgraded to.

**Comment by kylecordes** [comment]
If the answer is as simple as "restarting Bazel server causes it", and such restarts happen regularly by default (i.e. a short idle shutdown), indeed it would be great to get rid of this noisy message.

**Comment by jin** [comment]
This hasn't been a useful message to me, ever, IMO. 

cc @jmmv what do you think about not showing this by default?

**Comment by jmmv** [comment]
@meisterT Why did you close this? I think the warning message is still annoying and we should do something about it. See my latest reply.

**Comment by meisterT** [comment]
Sorry, I understood that you already only show the message when necessary and consider it useful.
