### ISSUE TITLE
Get output files from failed tests

### ISSUE THREAD

**Issue by AdamDorwart** [bazelbuild/bazel#8527]
### Description of the problem / feature request:

Currently it seems difficult to collect output files from failed tests. In general just figuring out which tests failed without parsing stdout of the Bazel client seems difficult.

### Feature requests: what underlying problem are you trying to solve with this feature?

Maybe `aquery` is the right way to do this? Something like
```
bazel aquery tests(//:all) intersect attr("status", "FAILED", //:all)
```
to get all the failed tests and then use the machine readable output of that to collect output files.

Another option might be a command line option to produce a summarized test result xml

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

0.21.0

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/1779

**Comment by keith** [comment]
I hit this recently too, bazel CI is doing this with this logic https://github.com/bazelbuild/continuous-integration/blob/af35abfab14b30fd1e256a56a1c2794dccadbd08/buildkite/bazelci.py#L1434-L1455

We are now doing the same

cc @philwo

**Comment by buchgr** [comment]
@AdamDorwart this can be done with the BEP. See https://docs.bazel.build/versions/master/build-event-protocol.html and https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto

**Comment by buchgr** [comment]
Please re-open if this doesn't answer your question.
