### ISSUE TITLE
Bazel's integration tests are influenced by $HOME/.bazelrc

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#8542]
A couple of tests fail when a $HOME/.bazelrc file is present and should be fixed to not be influenced by this file:

**Fails when any $HOME/.bazelrc exists (even as an empty file):**

//src/test/cpp:rc_file_test:
- fails due to asserting the number of loaded rc files being a fixed number.

**Fails when $HOME/.bazelrc contains `build --nocache_test_results`:**

//src/test/shell/bazel:bazel_coverage_cc_test_gcc:
- test_cc_test_coverage_gcov FAILED: Expected regexp //:t.*cached not found .

//src/test/shell/integration:build_event_stream_test: 
- test_cached_test_results FAILED: Expected regexp cached_locally not found .
- test_test_start_times FAILED: Expected regexp cached_locally.*true not found .

**Fails when $HOME/.bazelrc contains `build -c dbg --javacopt="-g" --copt="-g" --strip="never"`:**

Note: This is [recommended in our documentation](https://www.bazel.build/contributing.html#debugging-bazel) for contributors in order to build Bazel with debugging symbols.

//src/test/shell/bazel:external_correctness_test
- test_genrule_d_correctness FAILED: Expected regexp bazel-out/.*-fastbuild/.*/external/a/b/c not found in bazel-genfiles/external/a/b/c/d .

//src/test/shell/integration:aquery_test
- test_aquery_text FAILED: Expected regexp Configuration: .*-fastbuild not found in output .

**Fails when $HOME/.bazelrc contains `build --copt=-w --host_copt=-w`:**

//src/test/shell/integration:output_filter_test:
- test_output_filter_cc FAILED: Expected regexp triggers_a_warning not found .

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
