### ISSUE TITLE
removing --override_repository does not correctly switch back to original repository

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#8543]
### Description of the problem / feature request:

This is a *reproducibility* issue with bazel 0.26.

I'm using a repository fetched using `http_archive`, from `load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")`. Sometimes I'm overwriting it using `--override_repository=...` on the command line and it works perfectly. However, when I'm removing the flag, bazel does not come back to my original setting, leading to unpredictable results.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm using a simple repository that you can clone here: https://github.com/guibou/bazel_override_repo_repro

It contains a WORKSPACE file with an `http_archive`, `@foo` which is supposed to fetch a remote repository containing a rule which display `I'm from gist` during analysis phase. The gist is here: https://gist.github.com/guibou/8e2946aab523125c634ee124f716753b

The repository also contains a directory `foo_alt` containing a similarly structured repository which, when used, will display `Hello` during the analysis phase.

I'm now switching from the "remote" (default) and the "local" repository using `--override_repository`.

Build using the default (i.e. the `http_archive`) correctly displays `'Im in a gist`:
```
[guillaume@paddle:~/bazel_non_repro_override_repo]$ bazel build //...
Starting local Bazel server and connecting to it...
DEBUG: /home/guillaume/.cache/bazel/_bazel_guillaume/5b3d64037925a138f9475c1e032758a5/external/foo/bar.bzl:2:5: I'm in a gist
INFO: Analyzed 0 targets (1 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 4.483s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

`--override_repository` works as expected and displays `hello`. (Note that I'm using an absolute path on my computer, please adapt for your tests).

```
[guillaume@paddle:~/bazel_non_repro_override_repo]$ bazel build @foo//... --override_repository=foo=/home/guillaume/bazel_non_repro_override_repo/foo_alt
DEBUG: /home/guillaume/.cache/bazel/_bazel_guillaume/5b3d64037925a138f9475c1e032758a5/external/foo/bar.bzl:2:5: hello
INFO: Analyzed 0 targets (1 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.347s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

However, switching back to the default setting (i.e. no `--override_repository`) does not restore the previous setting. See the `hello` instead of `I'm from gist`:

```
[guillaume@paddle:~/bazel_non_repro_override_repo]$ bazel build //...
DEBUG: /home/guillaume/.cache/bazel/_bazel_guillaume/5b3d64037925a138f9475c1e032758a5/external/foo/bar.bzl:2:5: hello
INFO: Analyzed 0 targets (1 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.138s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

A `clean --expunge` solves the problem:

```
[guillaume@paddle:~/bazel_non_repro_override_repo]$ bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

[guillaume@paddle:~/bazel_non_repro_override_repo]$ bazel build //...
Starting local Bazel server and connecting to it...
DEBUG: /home/guillaume/.cache/bazel/_bazel_guillaume/5b3d64037925a138f9475c1e032758a5/external/foo/bar.bzl:2:5: I'm in a gist
INFO: Analyzed 0 targets (1 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 2.052s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
release 0.26.0- (@non-git)
or
release 0.26.0
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Using `nixpkgs`. Please note that by build  is not officially in nixpkgs yet, but except from that regression, it can correctly build an important codebase. I've also tried with similar result in a docker container, installing ubuntu and using the official procedure.

**Comment by kastiglione** [comment]
I've hit this problem too, thanks for reporting @guibou.

**Comment by HackAttack** [comment]
I have what feels like the same issue, but with `repo_env` on 0.27.0

```python
# WORKSPACE
load(":test.bzl", "test")

test(name = "test")
```
```python
# test.bzl
def _test_impl(repo_ctx):
    print("RULE INVOKED")
    repo_ctx.file("BUILD", "", executable = False)

test = repository_rule(
    implementation = _test_impl,
    environ = ["VAR"],
    local = False,
)
```
```python
# BUILD
genrule(
    name = "name",
    cmd = "echo hello, world > $@",
    outs = ["out"],
)
```
Once the `repo_env` is added, the repository rule stops executing, and removing it doesn’t make it start executing until a `clean --expunge`.
```
$ bazel build @test//...
DEBUG: /tmp/test/test.bzl:2:5: RULE INVOKED
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.053s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
$ bazel build @test//... --repo_env=VAR=var
INFO: Build option --repo_env has changed, discarding analysis cache.
INFO: Analyzed 0 targets (1 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.074s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
$ bazel build @test//...
INFO: Build option --repo_env has changed, discarding analysis cache.
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.071s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

**Comment by aehlig** [comment]
Pending review: https://bazel-review.googlesource.com/c/bazel/+/109533
