### ISSUE TITLE
Bazel keeps using wrong GCC

### ISSUE THREAD

**Issue by LukeIreland1** [bazelbuild/bazel#8548]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I'm building Tensorflow 1.13.1 with Bazel 0.19.2, using armclang. Bazel needs GCC for some things anyway, but I can't make it use Arm GCC, it instead uses the default RHEL GCC.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to build Tensorflow using Arm Clang and Arm GCC, on RHEL 7. I've succeeded with the below instructions on Ubuntu 16.04. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

export CC=armclang;
export CXX=armclang++;
export FC=armflang;
export F77=armflang;
export CXXFLAGS="-stdlib=libc++ -L$ARM_HPC_COMPILER_DIR/lib";
export LDFLAGS="-L$ARM_HPC_COMPILER_DIR/lib -lm -lrt";
module load Generic-AArch64/<OS>/<version>/arm-hpc-compiler-19.2/armpl/19.2.0
grep -rl march . | xargs sed -i 's/march/mcpu/g'
bazel build --copt="-armpl" --config=opt --config=noaws //tensorflow/tools/pip_package:build_pip_package --verbose_failures

### What operating system are you running Bazel on?

RHEL 7

### What's the output of `bazel info release`?

release 0.19.2- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Dist zip bootstrap

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/tensorflow/tensorflow.git
39a279ef76b7b49b6ff164dcf5e22aee5de6e5a1
93dd14dce2e8751bcaab0a0eb363d55eb0cc5813
###  Have you found anything relevant by searching the web?

No, seems pretty unique.

>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> If the files are large, upload as attachment or provide link.

**Comment by LukeIreland1** [comment]
[error.txt](https://github.com/bazelbuild/bazel/files/3249075/error.txt)

**Comment by hlopko** [comment]
Not so related, but out of all variables you pass only `CC=armclang` is consumed by Bazel.

In the error log you sent it seems the right clang is used I see:

```
C++ compilation of rule '//tensorflow/core/grappler/graph_analyzer:graph_analyzer_lib' failed (Exit 1): armclang failed: error executing command 
  (cd /home/lukire01/.cache/bazel/_bazel_lukire01/56020ca81e5c7ac52bae20835db53b5a/execroot/org_tensorflow && \
  exec env - \
    <not important> \
  /opt/arm/arm-hpc-compiler-19.2_Generic-AArch64_RHEL-7_aarch64-linux/bin/armclang ...
```

What did you expect to happen and what happened instead?

**Comment by LukeIreland1** [comment]
It's used in parts, but not all over. I need Bazel to use custom GCC provided instead, which it does mostly.
`which gcc` confirms that the version of gcc to be used has been changed to the custom GCC, but somehow Bazel uses the system GCC.

The error message may not be as a direct result of the system GCC being used, but I can't isolate it while it uses the system GCC.

I expect it to pass and build successfully, as I am following these steps identical to the ones I took to build successfully on Ubuntu.

**Comment by hlopko** [comment]
I'm sorry, you'll have to isolate the problem more on your end. It's not even clear this is a Bazel problem or Host system configuration that's incompatible. Check for different versions of tools, libstdc++, other libraries, PATH, include directories...

**Comment by LukeIreland1** [comment]
Yes, in order to isolate the problem, I need to be able to get Bazel to use my GCC. It's not, so I can't. The fact that it's not, is a problem on it's own, and the only reason, after much investigation, I've found that stops the build from completing.

**Comment by LukeIreland1** [comment]
It's likely related to [this issue](https://github.com/bazelbuild/bazel/issues/4510). It is failing when it tries to use the headers in  `/usr/include/c++/4.8.5`, instead of those at `/opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/include/c++/8.2.0/`.

These headers, and things like glibc and libstdc++ are needed by the Arm compiler too, so the problem is how to convince Bazel to use the non-system Arm C / C++ libs/headers

**Comment by hlopko** [comment]
Oh one critical question I should've asked right at the beginning. Are you cross compiling? Bazel's C++ autoconfigured toolchain only works for host compilations. If you need to cross-compile, you need to write your own toolchain. See https://docs.bazel.build/versions/0.26.0/tutorial/cc-toolchain-config.html and https://docs.bazel.build/versions/0.26.0/cc-toolchain-config-reference.html.

**Comment by LukeIreland1** [comment]
If I'm literally just wanting the change the path of the gcc, is it not possible to just edit the existing toolchain, and any occurrences of gcc there? If not, I assume I'll have to add the path in here: "toolchain/cc_toolchain_config.bzl", as given in the example.

**Comment by hlopko** [comment]
You did change the path of the gcc. You see it in your log: `/opt/arm/arm-hpc-compiler-19.2_Generic-AArch64_RHEL-7_aarch64-linux/bin/armclang`. Is that not the right armclang? Bazel will use this binary for anything it needs to do with C++ compiler.

It is the expected builtin include directory for your armclang: `/usr/lib/gcc/aarch64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/`? In your log we see:

> In file included from tensorflow/core/grappler/graph_analyzer/sig_node.cc:16:
> In file included from ./tensorflow/core/grappler/graph_analyzer/sig_node.h:23:
> In file included from bazel-out/host/genfiles/tensorflow/core/framework/graph.pb.h:25:
> In file included from external/protobuf_archive/src/google/protobuf/generated_message_table_driven.h:34:
> In file included from external/protobuf_archive/src/google/protobuf/map.h:50:
> In file included from external/protobuf_archive/src/google/protobuf/stubs/hash.h:146:
> /usr/lib/gcc/aarch64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/unordered_map:47:
> /usr/lib/gcc/aarch64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/hashtable.h:268:7: error: static_assert failed due to requirement '__if_hash_not_cached<is_default_constructible<__detail::_Hashtable_ebo_helper<0, __hash_code_base> > >::value' "Cache the hash
>  code or make functors involved in hash code and bucket index computation default constructible"
>       static_assert(__if_hash_not_cached<

Is it possible that protobuf doesn't compile in your configuration because of incompatible headers?

**Comment by LukeIreland1** [comment]
/usr/lib/gcc/aarch64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ is the system GCC, and I want it to use gcc at /opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/. I've tried changing all the files I could find with this GCC path, but somehow Bazel is still using the system GCC path for GCC. I'll make my own toolchain if it's going to be easier than just replacing paths, but I was wondering if you knew a quick fix.

`def _impl(ctx):
    tool_paths = [
        tool_path(
            name = "gcc",
            path = "/opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/",
        ),`

If this is all I need to do, then it's not too much hassle. It accepts Armclang fine, but uses system GCC in parts, and Arm GCC in parts, and the issue is, it should be fully Arm GCC as the system GCC is effectively outdated/incompatible. It works on Ubuntu as the system GCC is updated/compatible.

It just seems that no matter what I do, it somehow finds a way to the system GCC path, so if I just need to use my own toolchain to fix this, I'll give that a go, just I imagine it will take much longer as I'll then have to reconfigure the things that aren't causing a problem, despite only needing to change one variable/path

**Comment by hlopko** [comment]
Did you try passing `--sysroot=/opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/`? Or passing `-isystem=/...`? You can use Bazel's --copt option.

Bazel doesn't not tell the C++ compiler where to look for system headers. armclang is using its defaults. You can see what defaults are by running `armclang -E -xc++ - -v`.

**Comment by LukeIreland1** [comment]
`[lukire01@vcn-man-apps ~]$ armclang -E -xc++ - -v
Arm C/C++/Fortran Compiler version 19.2 (build number 155) (based on LLVM 7.1.0)
Target: aarch64--linux-gnu
Thread model: posix
InstalledDir: /opt/arm/arm-hpc-compiler-19.2_Generic-AArch64_RHEL-7_aarch64-linux/bin
Found candidate GCC installation: /opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/lib/gcc/aarch64-linux-gnu/8.2.0
Found candidate GCC installation: /usr/lib/gcc/aarch64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/aarch64-redhat-linux/4.8.5
Selected GCC installation: /opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/lib/gcc/aarch64-linux-gnu/8.2.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/opt_arm/arm-hpc-compiler-19.2_Generic-AArch64_RHEL-7_aarch64-linux/llvm-bin/clang-7" -cc1 -triple aarch64--linux-gnu -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu generic -target-feature +neon -target-abi aapcs -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /home/opt_arm/arm-hpc-compiler-19.2_Generic-AArch64_RHEL-7_aarch64-linux/lib/clang/7.1.0 -I/opt/arm/armpl-19.2.0_Generic-AArch64_RHEL-7_arm-hpc-compiler_19.2_aarch64-linux/include -I/opt/arm/arm-hpc-compiler-19.2_Generic-AArch64_RHEL-7_aarch64-linux/include -I/opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/include -internal-isystem /opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/lib/gcc/aarch64-linux-gnu/8.2.0/../../../../include/c++/8.2.0 -internal-isystem /opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/lib/gcc/aarch64-linux-gnu/8.2.0/../../../../include/c++/8.2.0/aarch64-linux-gnu -internal-isystem /opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/lib/gcc/aarch64-linux-gnu/8.2.0/../../../../include/c++/8.2.0/backward -internal-isystem /usr/local/include -internal-isystem /home/opt_arm/arm-hpc-compiler-19.2_Generic-AArch64_RHEL-7_aarch64-linux/lib/clang/7.1.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/lukire01 -ferror-limit 19 -fmessage-length 168 -fno-signed-char -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ - -faddrsig
clang -cc1 version 7.1.0 based upon LLVM 7.1.0
Arm C/C++/Fortran Compiler version 19.2 default target aarch64-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/arm/armpl-19.2.0_Generic-AArch64_RHEL-7_arm-hpc-compiler_19.2_aarch64-linux/include
 /opt/arm/arm-hpc-compiler-19.2_Generic-AArch64_RHEL-7_aarch64-linux/include
 /opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/include
 /opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/lib/gcc/aarch64-linux-gnu/8.2.0/../../../../include/c++/8.2.0
 /opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/lib/gcc/aarch64-linux-gnu/8.2.0/../../../../include/c++/8.2.0/aarch64-linux-gnu
 /opt/arm/gcc-8.2.0_Generic-AArch64_RHEL-7_aarch64-linux/lib/gcc/aarch64-linux-gnu/8.2.0/../../../../include/c++/8.2.0/backward
 /usr/local/include
 /home/opt_arm/arm-hpc-compiler-19.2_Generic-AArch64_RHEL-7_aarch64-linux/lib/clang/7.1.0/include
 /usr/include
End of search list.`

**Comment by LukeIreland1** [comment]
It correctly selects the right GCC version. I'll try those two flags you gave me.

**Comment by LukeIreland1** [comment]
`gcc: error: unrecognized command line option '-armpl'` It's now compiling with gcc instead of armclang, which isn't what I wanted. It should only use gcc when necessary. Same as if you're cross compiling for clang.

**Comment by LukeIreland1** [comment]
So I take it my only option is building a new toolchain.

**Comment by LukeIreland1** [comment]
I noticed those guides you linked are for 0.26.2 and I'm on 0.19.2. Will they work fine?

**Comment by hlopko** [comment]
Nope, a lot has changed since 0.19. You can use the select on the top left side to see docs for 0.19, but I'd suggest migrating to the latest bazel version.

**Comment by LukeIreland1** [comment]
Okay, I'm only using 0.19 because I have to build Bazel and TensorFlow myself, and the latest TensorFlow tested build config used Bazel 0.19.2, but it's just been updated to 0.24.1, so I'll give that a try.

Also worth mentioning, I tried "hacking" (I can't think of a better word) the existing toolchain (to ensure this would be the solution by replacing all instances of system GCC paths to Arm GCC paths, and then it complained about NumPy using system GCC libs. In which case, it sounds like the problem is more that I need to build all the dependencies myself for AArch64 with armclang (or at least Arm GCC), rather than the issue being I need to make a toolchain to tell the entire system where to look for GCC.

I'm confident that the issue is this, because all the dependencies are installed before Bazel even comes into play, so I'll rebuild any moaning packages and let you know if that fixes it. Have you come across someone in a similar situation to mine before?

**Comment by LukeIreland1** [comment]
Hi, sorry for the lack of updates - I've been on holiday for a while. There are no mentions of `/usr/lib/gcc` anywhere in my edited workspace (custom Bazel, custom pip packages), yet in the error messages for building TensorFlow, it constantly mentions files in /usr/lib/gcc/

The good thing is, the link is always the same

```
In file included from external/protobuf_archive/src/google/protobuf/stubs/hash.h:39:
In file included from /usr/lib/gcc/aarch64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/unordered_map:48:
```

In hash.h, the file that is somehow using system GCC (when it shouldn't), the only actual mention of `unordered_map` is the following

```
#if defined(GOOGLE_PROTOBUF_HAS_CXX11_HASH)
# define GOOGLE_PROTOBUF_HASH_NAMESPACE std
# include <unordered_map>
# define GOOGLE_PROTOBUF_HASH_MAP_CLASS unordered_map
# include <unordered_set>
# define GOOGLE_PROTOBUF_HASH_SET_CLASS unordered_set
#elif defined(GOOGLE_PROTOBUF_HAS_TR1)
# define GOOGLE_PROTOBUF_HASH_NAMESPACE std::tr1
# include <tr1/unordered_map>
# define GOOGLE_PROTOBUF_HASH_MAP_CLASS unordered_map
# include <tr1/unordered_set>
# define GOOGLE_PROTOBUF_HASH_SET_CLASS unordered_set
# endif
```

Honestly, I don't know which out of CXX11_HASH and TR1, the system GCC or Arm GCC has, but regardless, I'm very confused how after this point, it's still looking at system GCC.

The file included from the `hash.h` file is `google/protobuf/stubs/common.h`, which doesn't mention unordered_map anywhere, but includes `map`, and this `map` may be the system GCC `map`. I simply need it to look at my GCC, but it should be since I built Bazel successfully with Arm GCC.

If Bazel isn't the issue here, and it's when Bazel uses Java/Python which were built with system GCC, then I can attempt to switch those, but I'd like to start off by saying, does that sound like a reasonable assumption that those two are the only things that could be causing this issue?

**Comment by LukeIreland1** [comment]
Bazel seems to be linked to system GCC regardless of how it's built.

When using Bazel built with my custom GCC, and trying to install TensorFlow with custom Clang, I get:
```
/home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper: /lib64
/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca
54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper)
/home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper: /lib64
/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca
54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper)
/home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper: /lib64
/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54
062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper)
```
from running:
```
bazel build --linkopt=-L${GCC_DIR}/lib64 --copt="-mtune=native" --copt="-march=armv8-a" --copt="-mcpu=native" --copt="-armpl" --copt="-O3" --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --config=noaws --define tensorflow_mkldnn_contraction_kernel=0 //tensorflow/tools/pip_package:build_pip_package --verbose_failures
```

This error message originates from ```/home/lukire01/builds/tf-armclang/tensorflow/tensorflow/lite/toco/python/BUILD:44:1: SWIGing tensorflow/lite/toco/python
/toco.i failed (Exit 1): swig failed: error executing command ```

I'm unsure a custom toolchain actually fixes the problem. All I need is for Bazel/TensorFlow to use Arm GCC/Clang, and Arm libraries. The paths are already setup, just Bazel doesn't seem interested in using them.

**Comment by LukeIreland1** [comment]
```ERROR: /home/lukire01/builds/tf-armclang/tensorflow/tensorflow/lite/toco/python/BUILD:44:1: SWIGing tensorflow/lite/toco/python
/toco.i failed (Exit 1): swig failed: error executing command 
  (cd /home/lukire01/.cache/bazel/_bazel_lukire01/d929f9864bbaa20629bc3975f3aa4efe/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/swig/swig -c++ -python -module tensorflow_wrap_toco -o bazel-out/aarch64-opt/bin/tensorflow/lite/
toco/python/tensorflow_wrap_toco.cc -outdir bazel-out/aarch64-opt/bin/tensorflow/lite/toco/python -Iexternal/eigen_archive -Iba
zel-out/aarch64-opt/genfiles -Iexternal/protobuf_archive -Iexternal/swig -Iexternal/com_google_absl -Ibazel-out/aarch64-opt/gen
files/external/local_config_python -Iexternal/nsync -Iexternal/jpeg -Iexternal/com_googlesource_code_re2 -Iexternal/flatbuffers
 -Iexternal/zlib_archive -Iexternal/gemmlowp -Iexternal/highwayhash -Iexternal/gif_archive -Ibazel-out/aarch64-opt/genfiles/ext
ernal/jpeg -Iexternal/arm_neon_2_x86_sse -Iexternal/farmhash_archive -Iexternal/swig/Lib -Iexternal/swig/Lib/cffi -Iexternal/swig/Lib/python -Iexternal/swig/Lib/std -Iexternal/swig/Lib/typemaps tensorflow/lite/toco/python/toco.i)
Execution platform: @bazel_tools//platforms:host_platform
/home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper: /lib64
/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca
54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper)
/home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper: /lib64
/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca
54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper)
/home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper: /lib64
/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54
062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper)
Target //tensorflow/tools/pip_package:build_pip_package failed to build```

**Comment by LukeIreland1** [comment]
```
ERROR: /home/lukire01/builds/tf-armclang/tensorflow/tensorflow/lite/toco/python/BUILD:44:1: SWIGing tensorflow/lite/toco/python
/toco.i failed (Exit 1): swig failed: error executing command 
  (cd /home/lukire01/.cache/bazel/_bazel_lukire01/d929f9864bbaa20629bc3975f3aa4efe/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/swig/swig -c++ -python -module tensorflow_wrap_toco -o bazel-out/aarch64-opt/bin/tensorflow/lite/
toco/python/tensorflow_wrap_toco.cc -outdir bazel-out/aarch64-opt/bin/tensorflow/lite/toco/python -Iexternal/eigen_archive -Iba
zel-out/aarch64-opt/genfiles -Iexternal/protobuf_archive -Iexternal/swig -Iexternal/com_google_absl -Ibazel-out/aarch64-opt/gen
files/external/local_config_python -Iexternal/nsync -Iexternal/jpeg -Iexternal/com_googlesource_code_re2 -Iexternal/flatbuffers
 -Iexternal/zlib_archive -Iexternal/gemmlowp -Iexternal/highwayhash -Iexternal/gif_archive -Ibazel-out/aarch64-opt/genfiles/ext
ernal/jpeg -Iexternal/arm_neon_2_x86_sse -Iexternal/farmhash_archive -Iexternal/swig/Lib -Iexternal/swig/Lib/cffi -Iexternal/swig/Lib/python -Iexternal/swig/Lib/std -Iexternal/swig/Lib/typemaps tensorflow/lite/toco/python/toco.i)
Execution platform: @bazel_tools//platforms:host_platform
/home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper: /lib64
/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca
54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper)
/home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper: /lib64
/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca
54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper)
/home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper: /lib64
/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/lukire01/.cache/bazel/_bazel_lukire01/install/de1dd57dca54
062b3b0b4ca705cb2e46/_embedded_binaries/process-wrapper)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by krafczyk** [comment]
@LukeIreland1  I've also mentioned in #4510, This is a problem for me too. I need to use a non-system GCC to build tensorflow, but process-wrapper is built with a dependency on libstdc++ and libgcc for the non-system GCC. When trying to run the process-wrapper, it doesn't properly set the LD_LIBRARY_PATH and so the call predictably fails.

**Comment by krafczyk** [comment]
@LukeIreland1 In case this is helpful to you,

I wound up backporting the commit here: https://github.com/bazelbuild/bazel/commit/ab9c1f5f98a993b4da532224a9fed1b1b9a90148

To the version of bazel I was trying to use (0.26.1 in my case). Then I set BAZEL_LINKOPTS to "-static-libstdc++ -static-libgcc" and BAZEL_LINKLIBS to "-l%:libstdc++.a". This worked to ensure the c++ runtime wasn't shared linked and so it didn't matter what compiler I used to build bazel. It might be possible to put "-l%:libstdc++.a" in BAZEL_LINKOPTS without the patch but I didn't try it.

**Comment by sudhakarsq** [comment]
@krafczyk I'm facing this issue when I try to use bazel 0.26.1. 

Did you patch the commit from #https://github.com/bazelbuild/bazel/commit/ab9c1f5f98a993b4da532224a9fed1b1b9a90148 directly to your 0.26.1 bazel version or did you upgrade your bazel to 0.27 first and then patched the commit? 

The changes in the mentioned commit don't map directly to the files present in bazel 0.26.1.

**Comment by krafczyk** [comment]
I back ported into 0.26.1. I'll try and find the patch(s) I wound up with.

**Comment by krafczyk** [comment]
There are 3 patches. first allows you to set the output directory in the bootstrap script
```
diff --git scripts/bootstrap/buildenv.sh scripts/bootstrap/buildenv.sh
index f5ee696..808e911 100755
--- scripts/bootstrap/buildenv.sh
+++ scripts/bootstrap/buildenv.sh
@@ -175,8 +175,10 @@ function tempdir() {
   atexit cleanup_tempdir_${DIRBASE}
   NEW_TMPDIR="${DIR}"
 }
+if [ -z ${OUTPUT_DIR} ]; then
 tempdir
 OUTPUT_DIR=${NEW_TMPDIR}
+fi;
 phasefile=${OUTPUT_DIR}/phase
 function cleanup_phasefile() {
   if [ -f "${phasefile}" ]; then
```
This patch allows you to pass command line arguments through the boostrap script.

```
diff --git compile.sh compile.sh
index a53dc83..0a05020 100755
--- compile.sh
+++ compile.sh
@@ -67,6 +67,7 @@ bazel_build "src:bazel_nojdk${EXE_EXT}" \
   --action_env=PATH \
   --host_platform=@bazel_tools//platforms:host_platform \
   --platforms=@bazel_tools//platforms:target_platform \
+  $@ \
   || fail "Could not build Bazel"
 bazel_bin_path="$(get_bazel_bin_path)/src/bazel_nojdk${EXE_EXT}"
 [ -e "$bazel_bin_path" ] \
```

Finally, this is the important patch. This patch allows you to set special link lines through BAZEL_LINKLIBS.

```
diff --git tools/cpp/cc_configure.bzl tools/cpp/cc_configure.bzl
index b4ffa0f..895f3d4 100755
--- tools/cpp/cc_configure.bzl
+++ tools/cpp/cc_configure.bzl
@@ -58,6 +58,7 @@ cc_autoconf = repository_rule(
         "BAZEL_HOST_SYSTEM",
         "BAZEL_CXXOPTS",
         "BAZEL_LINKOPTS",
+        "BAZEL_LINKLIBS",
         "BAZEL_PYTHON",
         "BAZEL_SH",
         "BAZEL_TARGET_CPU",
diff --git tools/cpp/unix_cc_configure.bzl tools/cpp/unix_cc_configure.bzl
index 50f2595..2b8c3fa 100755
--- tools/cpp/unix_cc_configure.bzl
+++ tools/cpp/unix_cc_configure.bzl
@@ -379,6 +379,7 @@ def configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools):
 
     cxx_opts = split_escaped(get_env_var(repository_ctx, "BAZEL_CXXOPTS", "-std=c++0x", False), ":")
     link_opts = split_escaped(get_env_var(repository_ctx, "BAZEL_LINKOPTS", "-lstdc++:-lm", False), ":")
+    link_libs = split_escaped(get_env_var(repository_ctx, "BAZEL_LINKLIBS", "", False), ":")
     supports_gold_linker = _is_gold_supported(repository_ctx, cc)
     cc_path = repository_ctx.path(cc)
     if not str(cc_path).startswith(str(repository_ctx.path(".")) + "/"):
@@ -473,7 +474,7 @@ def configure_unix_toolchain(repository_ctx, cpu_value, overriden_tools):
                     cc,
                     "-pass-exit-codes",
                 )
-            ) + link_opts),
+            ) + link_opts + link_libs),
             "%{opt_compile_content}": get_starlark_list(
                 [
                     # No debug symbols.
```

Then I build bazel using the ./compile.sh script and setting the environment variables `BAZEL_LINKOPTS="-static-libstdc++:-static-libgcc"` and `BAZEL_LINKLIBS="-l%:libstdc++.a"`

This will build bazel without linking dynamically against libstdc++ and libgcc. This solves the process-wraper issue.

**Comment by mrodozov** [comment]
For us that doesn't have the possibility to use static libstdc++ will that work (nearly the same) but with dynamic library ?

**Comment by aiuto** [comment]
Closing because this is for an obsolete Bazel and has gone stale.
