### ISSUE TITLE
Add integration tests for java annotation plugins.

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#8556]
Currently we don't test the `plugins` attribute on the java rules. Testing this feature would have caught https://github.com/bazelbuild/intellij/issues/845 at presubmit time and would have avoided a bazel patch release.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
