### ISSUE TITLE
Document the fact that aspects can use toolchains

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#8558]
### Description of the problem / feature request:

I spent a lot of time to get toolchains to work with aspects since I didn't know/understand they work like rules with toolchains.
I read https://docs.bazel.build/versions/master/skylark/aspects.html and https://github.com/pcj/bazel_aspects and https://www.kchodorow.com/blog/2017/01/10/aspects-the-fan-fic-of-build-rules/ but none talk about toolchains.

This might seem basic but I did a lot of experiments until I stumbled onto a code snippet (in my own repo :) of rules_scala) that shows this.
cc @katre

**Comment by laurentlb** [comment]
(this topic is between Configurability and Starlark, but there's a lot of documentation work to do on the Starlark side, I hope Configurability team can take it)

**Comment by gregestren** [comment]
@ittaiz can you link the code snippet here? 

Are you asking for detailed documentation or just a mention that aspects can also use the interface and a link to https://docs.bazel.build/versions/master/toolchains.html?
