### ISSUE TITLE
Move toolchain autodetection to @rbe_autoconfig

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8560]
@buchgr informs me that it's possible to auto-detect runtimes on the remote platform at workspace evaluation time, by having a repo rule launch a docker container to replicate the remote environment. Assuming that this works for the target platform too and not just the execution platform, we could use this to replace the execution-time checking that we currently do in the autodetecting toolchain. This would avoid some `PATH` env var issues and be more robust.

The model I was previously using was that platform vendors would define a Python toolchain for their platform, but apparently @rbe_autoconfig is considered the best practice now since it's easier to maintain.

**Comment by nlopezgi** [comment]
Hi @brandjon ,
While `rbe_autoconfig` is the recommended way to auto-detect runtimes for _existing_ complex configure like repo rules (e.g., `local_cc_configure`) my advice for cases in which rules like this do not yet exist, is to enable vendors to define the toolchains themselves by hand if this is not an overly complex task (which is not the case for a C toolchain currently). 
The main reason for this, is that generating configs on demand via `rbe_autoconfig` requires a container be pulled in the host (which incurs a performance penalty, cannot be done remotely or be cached properly, and requires the user properly setup their host to run docker containers). Some day, in the distant future, when users can reasonably write a C toolchain, and configure like repo rules work natively with remote execution, we expect `rbe_autoconfig` to not be needed at all.
Please let me know if you have questions.

**Comment by brandjon** [comment]
I see. Thanks for the context Nicolas. In that case I'll defer this until there's a demonstrated need for it, or it's obsolete once we have remotely executed repo rules.

**Comment by meisterT** [comment]
Putting it in the ice box until there's actual need.
