### ISSUE TITLE
Shared libraries hits filesystem limits on Linux

### ISSUE THREAD

**Issue by ozio85** [bazelbuild/bazel#8567]
### Description of the problem / feature request:
When creating shared object on linux, an internal shared library is created under:
Workspace_root/_solib_k8

When using cc_import, and the import is itself importing another .so, the path is appended to the first path with a "_Uimport___U" and just continues, creating a very long path. Even not using a cc_import it is possible to hit the maximum filename length (255). 

Example of command:
bazel/install/[hash]/_embedded_binaries/build-runfiles (args bazel-out/k8-fastbuild/bin/[PathToApplication].runfiles_manifest bazel-out/k8-fastbuild/bin/[PathToApplication].runfiles): mkdir 'Workspace_root/_solib_k8/**[Path_STo_SShared_SObject]_Uimport___U[Path_STo_S_Another_SShared_SObject]**: File name too long [36]

Linux has a maximum filename length of 255 characters for most filesystems (including EXT4), and a maximum path of 4096 characters. 

### Feature requests: what underlying problem are you trying to solve with this feature?

I suggest to create a hash instead of this insanely long path.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Follow my example above.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

0.25.2

###  Have you found anything relevant by searching the web?

Havn't found any.

**Comment by lingithub1** [comment]
I'm encountering the same problem for Bazel 4.2.1 on RHEL 7.4.
