### ISSUE TITLE
Incremental builds on MacOS appear to pause before returning

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#857]
With the new Java workers enabled, I often get sub-second incremental builds, which is nice. Unfortunately, bazel often appears to pause before returning control to the terminal.

```
$ time bazel build --workspace_status_command=/usr/bin/true --nostamp java/info/adams/commons
INFO: Found 1 target...
Target //java/info/adams/commons:commons up-to-date:
  bazel-bin/java/info/adams/commons/libcommons.jar
INFO: Elapsed time: 0,158s, Critical Path: 0,01s

real    0m0.738s
user    0m0.013s
sys 0m0.030s
```

Ctrl-\ shows that it's waiting in TimestampGranularityMonitor.

On a null build, the only files it's waiting for are stable-status.txt and volatile-status.txt (which are unconditionally re-created on every build), which makes this issue very visible on null builds.

Unfortunately, OSX only has second mtime accuracy, which at first glance seems to require that we use the TSGM. We could special-case the status files, but that wouldn't help for incremental builds. Maybe we could special-case all output files? Or maybe there's a better way to detect file changes than watching mtime?

No good ideas here.

**Comment by ulfjack** [comment]
Philipp suggested that we should just always md5 all the files, but I think that would be prohibitively expensive. Even at 1 GB/s, all of bazel's source files would take ~0.5s.

**Comment by dmaclach** [comment]
Ulf,

Could you add a marker or some sort in the extended attributes of the file?

Cheers,
Dave

**Comment by dmaclach** [comment]
To be more clear on this, could you use setxaddr to timestamp the files to
a higher resolution than what the filesystem gives you?

**Comment by ulfjack** [comment]
That might be ok for output files. The concern is that someone or something modifies a file and the timestamp stays the same - since other tools (or the os) don't know about the extended attribute, they probably won't update / delete the attribute when / if they modify a file in place.

I spend some (little) time googling for this problem and the best suggestion I found was to use a sort of fingerprint, consisting of the mtime and a few other fields (size, inode), and re-md5 the file if any of the fingerprint data changes. I know some linux tools that do this, and it seems to work well, but I don't know how well it works on Mac or Windows.

**Comment by philwo** [comment]
@ulfjack Anything left to do here? I remember you fixed some issues related to the timestamp granularity in the last months.

**Comment by ulfjack** [comment]
Here's a possible plan, but it's a bit elaborate. The main problem we're worried about is that you have a script that runs bazel, then modifies a file, then runs bazel again. If the bazel runs are very fast, then using mtime to detect changes is unreliable if the file system only stores timestamps that are accurate to 1 second.

1. whenever bazel writes a file, we take the mtime & md5 afterwards and add the file to a list
2. at the end of a build, we look at the current system time, and remove all files whose mtime is less than the system time
3. on a subsequent build, we md5 all the files on the list to detect if they've been changed, and use mtime only for files not on the list

I.e., we consider all files as potentially modified if their mtime is not significantly smaller than the end time of the previous build. There should only be very few such files, so the overhead should be small. In addition, a sequence of null builds will eventually stop md5ing files if enough time has passed for the mtime to be reliable.

On linux, we have ms accuracy, so we probably don't need to do anything special, although it might be nice to have a more generalized file metadata concept.

**Comment by meisterT** [comment]
I don't think this is a issue any more for the status action. I did 100 runs on a Mac and never found this to be the case.

**Comment by philwo** [comment]
Indeed, this was fixed on macOS via their new filesystem: "APFS supports 1 nanosecond timestamp granularity, which improves on HFS Plus's 1-second time stamp granularity."
