### ISSUE TITLE
[BES/BEP] : BES doesn't report intermediate targets built as a part of building primary target

### ISSUE THREAD

**Issue by rahul-nitkkr** [bazelbuild/bazel#8570]
### Description of the problem / feature request:

> While experimenting with BES , builds invoked with //... report all targets available in the WORKSPACE correctly, but when invoked with a specific target as bazel build //foo:bar, which has dependencies on other targets in the workspace , the intermediate targets are not reported with TargetConfigured/Completed events

### Feature requests: what underlying problem are you trying to solve with this feature?

> A way to get the intermediate targets and their corresponding completion events from BES

an example would be :
let's say the build has 3 targets 
 
```
java_library(
    name = "foo",
    deps = ["some_dep"]
)

java_library(
    name = "bar",
    deps = ["some_other_dep", 
                 ":foo"]
)

java_library(
    name = "baz",
    deps = [":bar"]
)
```

when run with bazel build //...  BES reports 3 targets configured 
while running with bazel build //:baz, only 1 target is reported as configured/completed.

is there a way to get the underlying(intermediate) 2 target's completion statuses as well ? I'd rather **not** rely on log parsing from the Progress event

**Comment by buchgr** [comment]
I believe `--build_event_publish_all_actions` will solve your problem. Please re-open if it doesn't.
