### ISSUE TITLE
Release 0.28 - July 2019 (stable)

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#8571]
Target RC date - July 1st, 2019
This release will have no [breaking changes](https://docs.bazel.build/versions/master/backward-compatibility.html).

See the  [blog post](https://blog.bazel.build/2019/06/06/Bazel-Semantic-Versioning.html)  for some details

**Comment by hlopko** [comment]
Who's the release manager for July?

**Comment by dslomov** [comment]
> Who's the release manager for July?

Let me assign someone

**Comment by dslomov** [comment]
Sorry I screwed up a bit and created duplicated issues for 0.28 and 0.29 releases; all fixed now, the people assigned.

**Comment by hlopko** [comment]
Ah great! Thanks for the quick reply.

**Comment by laurentlb** [comment]
# Status of Bazel 0.28

I plan to keep this message up to date during the release process and provide the important information.

- Target baseline: July 1st
- Expected release date: July 10-16
- [List of release blockers](https://github.com/bazelbuild/bazel/labels/Release%20blocker)

To report a release-blocking bug: file a bug, use the `Release blocker` label, and cc @laurentlb. Release blockers are regressions in Bazel relative to Bazel 0.26 or Bazel 0.27.

Task list:

- [x] Update GitHub issues for incompatible changes
- [x] Pick release baseline: 2e374a9c6e3d4ed71f0145de287c4b2fe43c76d6
- [ ] Create release candidate
- [ ] Check downstream projects
- [ ] [Create draft release announcement](https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit#heading=h.ibnqhsyprlp8)
- [ ] Send for review the release announcement PR
- [ ] Push the release, notify package maintainers
- [ ] Update the documentation
- [ ] Publish the announcement (blog & mailing-list)

**Comment by laszlocsomor** [comment]
Please cherry-pick https://github.com/bazelbuild/bazel/commit/6d0b14b95a71175362030b4811ca74512b00a890 to fix 0.26 -> 0.27 regression https://github.com/bazelbuild/bazel/issues/8723. See also https://github.com/bazelbuild/bazel/issues/7816#issuecomment-508392622

**Comment by laurentlb** [comment]
0.28.0rc2 was created using:
`scripts/release/release.sh create` --force_rc=2 0.28.0 2e374a9c6e3d4ed71f0145de287c4b2fe43c76d6 6d0b14b95a71175362030b4811ca74512b00a890 

The binaries are available here: https://releases.bazel.build/0.28.0/rc2/index.html

**Comment by laurentlb** [comment]
Released: https://github.com/bazelbuild/bazel/releases/tag/0.28.0

**Comment by jin** [comment]
0.28.0 introduced a build regression with the behavior of `--experimental_google_legacy_api`. 

To reproduce, clone https://github.com/bazelbuild/intellij and run `bazel build //aswb:aswb_bazel_zip --define=ij_product=android-studio-beta`.

0.28.0:

```
jingwen@jingwen-sea:~/code/intellij$ USE_BAZEL_VERSION=0.28.0 bazel build //aswb:aswb_bazel_zip --define=ij_product=android-studio-beta --nobuild
ERROR: /usr/local/google/home/jingwen/code/intellij/aspect/intellij_info_impl.bzl:105:25: android_common is experimental and thus unavailable with the current flags. It may be enabled by setting --experimental_google_legacy_api
ERROR: /usr/local/google/home/jingwen/code/intellij/aswb/BUILD:212:1: error loading package 'aspect': Extension 'aspect/intellij_info_impl.bzl' has errors and referenced by '//aswb:aspect_directory'
ERROR: Analysis of target '//aswb:aswb_bazel_zip' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.200s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: java ... (3 packages)
```

0.27.2:

```
jingwen@jingwen-sea:~/code/intellij$ USE_BAZEL_VERSION=0.27.2 bazel build //aswb:aswb_bazel_zip --define=ij_product=android-studio-beta --nobuild
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Analyzed target //aswb:aswb_bazel_zip (59 packages loaded, 2137 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/566de91536493bd30d1fb02c05327dbd/sandbox
INFO: Elapsed time: 10.472s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

**Comment by meteorcloudy** [comment]
@laurentlb  7d2bc7e caused a bug which was caught internally, 2260b970cb2a10c21a2fde116aa82c79be52991f is the fix, but it's not in 0.28.0. Please cheery-pick 2260b970cb2a10c21a2fde116aa82c79be52991f if you're releasing 0.28.1.

Related https://github.com/bazelbuild/bazel/issues/8707

**Comment by meteorcloudy** [comment]
@laurentlb Please cherry-pick c6ca6c2ccd9e11a87f837341ae05d2ba037975b1 to fix regression reported at https://github.com/bazelbuild/bazel/issues/3857#issuecomment-510538152

**Comment by laurentlb** [comment]
Created 0.28.1 with:
`scripts/release/release.sh create 0.28.1` 18cd9048526f067a4950c6ddbf4b1b3604760af0 2260b970cb2a10c21a2fde116aa82c79be52991f a0af170f87c8230fcd8860599b983df097b646bd c6ca6c2ccd9e11a87f837341ae05d2ba037975b1

You can download it from: https://releases.bazel.build/0.28.1/rc1/index.html

**Comment by jin** [comment]
Users are starting to report issues with the IntelliJ plugin: https://github.com/bazelbuild/intellij/issues/976#issuecomment-512913723

Could we expedite promoting 0.28.1rc1 to a release?

**Comment by laurentlb** [comment]
Released: https://github.com/bazelbuild/bazel/releases/tag/0.28.1

**Comment by ulfjack** [comment]
The release notes are messed up:
```
This release contains contributions from many people at Google, as well as .
```

The sentence is incomplete. Did something go wrong with the release script?

**Comment by ulfjack** [comment]
The release notes link for 0.28.0 contains a link to the pull request for the release notes, rather than a link to the blog post.

**Comment by laurentlb** [comment]
Thanks, release descriptions on GitHub have been fixed.

**Comment by dstiers-1109** [comment]
Thank you
