### ISSUE TITLE
Remote execution pipeline fails

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8574]
### Description of the problem / feature request:

Remote execution pipeline fails:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1021#0e97657f-36db-482a-a385-eb492d1e2153

Example test log:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //src/test/cpp:bazel_startup_options_test
-----------------------------------------------------------------------------
/b/f/w/bazel-out/k8-fastbuild/bin/src/test/cpp/bazel_startup_options_test.runfiles/io_bazel/src/test/cpp/bazel_startup_options_test: symbol lookup error: /b/f/w/bazel-out/k8-fastbuild/bin/src/test/cpp/bazel_startup_options_test.runfiles/io_bazel/src/test/cpp/../../../_solib_k8/libsrc_Smain_Scpp_Slibblaze_Uutil.so: undefined symbol: _ZN10blaze_util8internal10LogMessageC1ENS_8LogLevelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEii
```

### What operating system are you running Bazel on?

Linux / JDK 11

### What's the output of `bazel info release`?

bazel @ efb3f1595ee897484c477168b8da42b67602e10e

**Comment by laurentlb** [comment]
cc @buchgr, @ishikhman

**Comment by laurentlb** [comment]
This is blocking the release of Bazel. Can you take a look?

**Comment by buchgr** [comment]
Please ignore the error. I believe the pipeline should be removed from downstream.

**Comment by laurentlb** [comment]
Thanks!

(cc @philwo)

**Comment by ishikhman** [comment]
> Please ignore the error. I believe the pipeline should be removed from downstream.

why do you think so?

**Comment by buchgr** [comment]
> I'm curious, why do you think so? It was green at the end of may..

That was more by accident than by design :). We are using pre-generated toolchains for remote execution. So in downstream testing, Bazel built from HEAD will use the toolchains of the released version of Bazel.

**Comment by ishikhman** [comment]
> > I'm curious, why do you think so? It was green at the end of may..
> 
> That was more by accident than by design :). We are using pre-generated toolchains for remote execution. So in downstream testing, Bazel built from HEAD will use the toolchains of the released version of Bazel.

ah, I see, thanks!

**Comment by buchgr** [comment]
I have removed the pipeline from downstream.
