### ISSUE TITLE
py_test/sh_test pulls in unnecessary java repositories at runtime (0.26)

### ISSUE THREAD

**Issue by Profpatsch** [bazelbuild/bazel#8575]
### Description of the problem / feature request:

Bazel 0.26 tries to download `remote_java_tools_linux` for a trivial `BUILD` file using the `py_binary` rule.

I’d expect bazel to support its builtin rules without depending on external repositories.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please see the minimal repro here: https://github.com/Profpatsch/repros/tree/master/bazel-python_binary-downloads-repostitories

Go offline and run the command in the repro.

### What operating system are you running Bazel on?

```
$ uname -a
Linux shiki 4.19.34 #1-NixOS SMP Fri Apr 5 20:33:17 UTC 2019 x86_64 GNU/Linux
```

### What's the output of `bazel info release`?

$ bazel info release
release 0.26.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

```
$ git clone https://github.com/NixOS/nixpkgs
$ git fetch git@github.com:groodt/nixpkgs bazel-0.26.0
$ git checkout FETCH_HEAD
$ nix-build -A bazel
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

non-applicable

###  Have you found anything relevant by searching the web?

nothing here in the issue tracker

**Comment by brandjon** [comment]
This is not specific to Python. I'm able to reproduce it for `sh_test`. Note that this happens when you build a `py_test` but not when it's just a `py_binary` target.

**Comment by comius** [comment]
The problem is that all Test rules depend on `@bazel_tools//tools/test:coverage_report_generator`, whether coverage is enabled or not.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by fmeum** [comment]
I believe this was fixed by https://github.com/bazelbuild/bazel/pull/16995.

@sgowroji Could you close as completed?
