### ISSUE TITLE
Permit turning off android resource merging

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#8577]
### Description of the problem / feature request:

Now that name-spaced resources are supported, teams that exclusively use this feature have no need for the expensive resource merging work. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Reduce unnecessary work during an android build.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Write any trivial app which consumes .aars, and depend on a namespaced resource directly (rather than in the local R.class). Then build. All the resources are merged into the current library, even though the current library doesn't require local references to these. 

### What operating system are you running Bazel on?

Mac OS X 10.14.5

### What's the output of `bazel info release`?

release 0.25.2

###  Have you found anything relevant by searching the web?

Discussion with @jin has confirmed that the resource merging is (presently) mandatory.

**Comment by cgruber** [comment]
I want to put some weight on this one - based on our profiles, we're doing immense amounts of resource merging, and we've turned it off in Gradle, which is making clean builds of gradle 1/4 or less of the time of a bazel clean build. While that's not the normal case we imagine (low incrementality) it occurs in a variety of situations, and it's probably a quality-of-life blocker to our bazel adoption.

**Comment by jin** [comment]
@cgruber are your comparisons with remote caching enabled?

**Comment by cgruber** [comment]
Yeah. That helps a lot, but we have lots of scenarios where there's invalidation of a good chunk of the graph, and in those cases, it really hurts.

**Comment by jin** [comment]
Unassigning myself as I don't have the bandwidth to work on this, and I'm refocusing on other areas in Bazel.

**Comment by cgruber** [comment]
Ok, that's a problem as this is, hands down, a migration blocker for us. We have enough work that invalidates enough of the graph, that we simply cannot take the hit vs. gradle that this extra work imposes on us.  It's pure-waste, from our perspective, given that we use name-spaced resources now.

**Comment by jin** [comment]
It's unlikely that we'll add this functionality to the native Android rules. We'll need to discuss this with the owners of the Starlark rules_android to see how we can move this forward.

**Comment by cgruber** [comment]
Should I move this issue (well, replicate it) over as a feature request on rules_android?

**Comment by cgruber** [comment]
I am totally ok with this happening within the starlark rules, as long as it happens.

**Comment by cgruber** [comment]
Meant to close this, as it migrated to bazelbuild/rules_android#10
