### ISSUE TITLE
Query with rbuildfiles frequently throws IllegalStateException

### ISSUE THREAD

**Issue by rohansingh** [bazelbuild/bazel#8582]
### Description of the problem / feature request:

In our CI system, we run the following query to determine if any modified files are dependencies of any BUILD files:

```
 bazel query \
   --keep_going \
   --order_output=no \
   --universe_scope='//...' \
   "rbuildfiles($comma_sep_modified_files)"
```

Frequently, this results in an exception that looks like this:

```
java.lang.IllegalStateException: File:[/buildkite/builds/hello-world[source]]frontend/web/src/js/app/middleware/initialization.js=InMemoryNodeEntry{identity=728588638, value=null, lastChangedVersion=IntVersion: 388, lastEvaluatedVersion=IntVersion: 388, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=[], singleReverseDep=false, dataToConsolidate=null}, dirtyBuildingState=FullDirtyBuildingState{dirtyState=CHECK_DEPENDENCIES, signaledDeps=-1, externalDeps=0, dirtyDirectDepIndex=0, lastBuildDirectDeps=GroupedList{elements=[FILE:[/buildkite/builds/hello-world]/[frontend/web/src/js/app/middleware/initialization.js]], size=1}, lastBuildValue=RegularFileArtifactValue{digest=00190f7f9e1cb320fe146036e972844242a6aa8353a2b9aff2740a536146f894, size=1459, proxy=ctime of 1559922057219 and nodeId of 1317526}}}
--
  | at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
  | at com.google.devtools.build.skyframe.DelegatingWalkableGraph.getReverseDeps(DelegatingWalkableGraph.java:132)
  | at com.google.devtools.build.lib.query2.RBuildFilesVisitor.getVisitResult(RBuildFilesVisitor.java:80)
  | at com.google.devtools.build.lib.query2.ParallelVisitor$VisitTask.process(ParallelVisitor.java:217)
  | at com.google.devtools.build.lib.query2.ParallelVisitor$Task.run(ParallelVisitor.java:197)
  | at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
```

The affected filename differs on each build, but the stack trace is always the same, with the exception coming from `RBuildFilesVisitor`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Determining which targets may have been affected by a pull request.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unfortunately this is in a mid-sized, private monorepo which I can't provide here. Running the `bazel query` provided above results in this exception around 10-20% of the time on our CI servers.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
# bazel info release
INFO: Invocation ID: 2537f98b-c39a-4e98-a4fd-90ff745c9416
release 0.26.1
```

Note however that I also saw this issue with Bazel 0.25.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
1577a2caadd770afa708cf6e0eeea08cda579c34
bdfc59dde9a6eee44df21b66ba67ce027bd18e59
```

###  Have you found anything relevant by searching the web?

It is possible that #7294 is related but I'm not sure.

**Comment by rohansingh** [comment]
Note that simply retrying the query almost always succeeds.

**Comment by haxorz** [comment]
> [@rohansingh]  In our CI system, we run the following query

can you briefly summarize *how* your CI uses bazel? based on the nature of this crash, i'm guessing the workflow is:

- CI learns about new commit
- CI updates its local filesystem with the new commit
- CI invokes `blaze query` ***on an already running bazel server***

> [@rohansingh] ... The affected filename differs on each build...

is the filename always that of a file you modified inter-bazel-command?

e.g.

`$ bazel query rest-of-args`
`$ echo "some modification" >> some-file.js`
`$ bazel query query rest-of-args`

i reckon the bazel INFO log would be informative but i understand you probably don't want to upload that (has directory names, file names, env variables, etc). you could still look at it to help establish the sequence of operations that tickles the crash. in particular, the log line from SequencedSkyframeExecutor#logDiffInfo would be useful.

**Comment by rohansingh** [comment]
@haxorz You're exactly right about the CI workflow. The CI uses long-running Buildkite agents. Except in the case of an agent crash or restart, the Bazel server will already be running.

Some random agent gets assigned to build a commit, and it updates its local filesystem with the new commit. This is done by using `git` in a build directory, and then using `rsync` to copy any changed files to the Bazel workspace directory. The `bazel query` is invoked from the workspace directory.

Based on my notes, it does also seem that you're correct that the filename is one that has been modified between Bazel commands, generally in the new commit that is being tested.

Unfortunately I've since left the company where this was an issue, so I'm no longer in a position to share any of the relevant logs. /cc @loganmhb

**Comment by haxorz** [comment]
> Based on my notes, it does also seem that you're correct that the filename is one that has been modified between Bazel commands, generally in the new commit that is being tested.

^^ that's enough of a lead for us to debug. so, an INFO log is probably not needed.

thanks for the bug report!

**Comment by mtl-wgtwo** [comment]
Hi, FWIW, I am seeing an identical issue.  I can reproduce this on my local machine with one specific file, but only if I am running this command via a CI script I am working on.   If I do a `bazel clean --expunge`, I can get an "interesting" error message:

```
Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: REPOSITORY_DIRECTORY:@local_config_sh=InMemoryNodeEntry{identity=1476772426, value=null, lastChangedVersion=IntVersion: 18, lastEvaluatedVersion=IntVersion: 18, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=[REPOSITORY:@local_config_sh, FILE_STATE:[/private/var/tmp/_bazel_mtl/e29eb7b0b1e778349fd921c835da28f5/external/local_config_sh]/[WORKSPACE], FILE_STATE:[/private/var/tmp/_bazel_mtl/e29eb7b0b1e778349fd921c835da28f5/external/local_config_sh]/[BUILD.bazel], FILE_STATE:[/private/var/tmp/_bazel_mtl/e29eb7b0b1e778349fd921c835da28f5/external/local_config_sh]/[BUILD], FILE_STATE:[/private/var/tmp/_bazel_mtl/e29eb7b0b1e778349fd921c835da28f5/external/local_config_sh]/[tools]], singleReverseDep=false, dataToConsolidate=null}, dirtyBuildingState=FullDirtyBuildingState{dirtyState=CHECK_DEPENDENCIES, signaledDeps=-1, externalDeps=0, dirtyDirectDepIndex=0, lastBuildDirectDeps=GroupedList{elements=[PRECOMPUTED:repository_overrides, PRECOMPUTED:dependency_for_unconditional_repository_fetching, PACKAGE_LOOKUP:external, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 0, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 1, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 2, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 3, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 4, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 5, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 6, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 7, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 8, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 9, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 10, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 11, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 12, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 13, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 14, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 15, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 16, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 17, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 18, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 19, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 20, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 21, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 22, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 23, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 24, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 25, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 26, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 27, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 28, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 29, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 30, [/Users/mtl/Development/gocode/src/github.com/omnicate/loltel]/[WORKSPACE], 31, [ACTION_ENVIRONMENT_VARIABLE:WINDIR, ACTION_ENVIRONMENT_VARIABLE:PATH], PRECOMPUTED:repo_env, PRECOMPUTED:skylark_semantics, PRECOMPUTED:output_verification_repository_rules, com.google.devtools.build.lib.rules.repository.ResolvedHashesValue$$Lambda$350/0x00000008003fe440@3535a48f, PRECOMPUTED:path_package_locator, com.google.devtools.build.lib.skyframe.BlacklistedPackagePrefixesValue$$Lambda$351/0x00000008003fd840@3a1f1888], size=43}, lastBuildValue=/private/var/tmp/_bazel_mtl/e29eb7b0b1e778349fd921c835da28f5/external/local_config_sh}}
```
if the bazel server is running, then I get this:

```
java.lang.IllegalStateException: [] DETERMINE_TESTS EXPAND_TEST_SUITES com.google.devtools.build.lib.pkgcache.TestFilter@e17a1=InMemoryNodeEntry{identity=875333263, value=null, lastChangedVersion=IntVersion: 371, lastEvaluatedVersion=IntVersion: 371, directDeps=null, reverseDeps=ReverseDeps{reverseDeps=[], singleReverseDep=false, dataToConsolidate=null}, dirtyBuildingState=FullDirtyBuildingState{dirtyState=CHECK_DEPENDENCIES, signaledDeps=-1, externalDeps=0, dirtyDirectDepIndex=0, lastBuildDirectDeps=GroupedList{elements=[PACKAGE:external], size=1}, lastBuildValue=ValueWithEvents{value=com.google.devtools.build.lib.skyframe.TargetPatternPhaseValue@addfb438, transitiveEvents size=0, transitivePostables size=2}}}
```

The command that does this is similar to the OP's: 

```
bazel query 'rbuildfiles(3rd/golang/golang.bzl)' --universe_scope=//... --order_output=no --incompatible_disable_deprecated_attr_params=false --keep_going --output package
```

In my case, if I take the failing command and run it outside of the script it works, but invoked in the script the command fails.   The file in question contains a function that is invoked from the WORKSPACE and loads our golang dependencies.

**Comment by rohansingh** [comment]
I'm working on a new project with a modern version of Bazel and am able to reproduce this issue again. Happy to provide anything that would help get it resolved.

**Comment by haxorz** [comment]
Sorry for the complete lack of work here. I've personally been too busy to work on this. We'll try to get it prioritized internally.

> Happy to provide anything that would help get it resolved.

If you can come up with a toy repro using only simple filesystem operations and `bazel query` invocations (i.e. no fancy `git` stuff), that'd be lovely. Otherwise we'll just resort to staring at the Bazel source code until we find the bug.

**Comment by rohansingh** [comment]
> If you can come up with a toy repro using only simple filesystem operations and bazel query invocations (i.e. no fancy git stuff), that'd be lovely.

It might take a while but now that I have an environment that can intermittently repro, I should be able to come up with something. After all, the way we are using the CI environment where this happens, it is basically some combination of filesystem operations and `bazel query` invocations that triggers it.

**Comment by haxorz** [comment]
A toy repro would be ideal, but even more info about the nature of the filesystem modifications would be nice. This way we can brainstorm possible bugs.

For example, if the only filesystem modification is an _edit_ of a `.js` file, I'm not seeing how this crash bug could reasonably happen. I'm guessing something like the following is happening:
- Your `foo/BUILD` file already had `glob(["bar.js"])`
- The filesystem modification in question is the deletion of the file `foo/bar.js`.
- Bazel reacts to this by re-evaluating your `BUILD` file also removing the `FILE(foo/bar.js)` node from its internal graph.
- ???
- Something went wrong and Bazel didn't actually remove one of the reverse dep edges!
- Your `rbuildfiles` query evaluation follows this bogus edge, and then Bazel blows up.

**Comment by rohansingh** [comment]
Got it. This new project is using the same semantics as I had previously— when building a new commit, `rsync` updates the Bazel workspace directory. That directory's previous state would be from whatever commit the CI agent processed previously, which could really be anything.

But I should trivially be able to get `rsync` to summarize what actions it took. That might provide some insight the next time there's a failure.

**Comment by janakdr** [comment]
@haxorz how is rbuildfiles getting its hands on an Artifact node? That's what `File:[/buildkite/builds/hello-world[source]]frontend/web/src/js/app/middleware/initialization.js` looks like. I wouldn't think query would touch that part of the graph at all.

**Comment by haxorz** [comment]
@janakdr Oh, wow, that's a great point. I glossed over the brackets in the string payload. Yeah, this does look like it's coming from Artifact#toString.

> I wouldn't think query would touch that part of the graph at all.

The SkyQuery codebase is written with just `bazel query` in mind. So, there is RBuildFilesVisitor#NODES_TO_PRUNE_TRAVERSAL, but that's not trying to prune traversals of other edges that Bazel's Skyframe graph might have.

So this is definitely a big lead! To understand the crash, we'd still need an explanation along the lines of my previous comment though, right? .... Except now it's pretty straight-forward, I think:

*  `bazel build //foo` <-- Get an `Artifact(doesntmatter)` -> `FileStateValue(blah)` transitive dep path
*  `echo xxx > blah` <-- Cause Bazel to want to do eager invalidation of UTC of `FileStateValue(blah)`
*  `bazel query --universe_scope=//something/that/contains/blah/in/skyframe/land "rbuildfiles(blah)"

**Comment by rohansingh** [comment]
So, still waiting to have more meaningful info to report, but I already see that `rsync --verbose` is reporting the following:

```
$ rsync --verbose --archive --delete "$git_checkout_dir" $bazel_workspace_dir"
...
deleting bazel-workspace
deleting bazel-testlogs
deleting bazel-out
 deleting bazel-bin
...
```

Those Bazel symlinks are recreated by the next Bazel invocation, so I don't think that should be an issue, right? Just figured I'd flag it in case it's relevant.

**Comment by janakdr** [comment]
Sorry for not communicating clearly, @rohansingh . We have a complete explanation of the bug: it's that we are including non-query-related edges in DelegatingWalkableGraph#getReverseDeps, and we are also not removing non-query-related nodes when we prime the query graph. I think that @haxorz will have a fix at some point.

**Comment by rohansingh** [comment]
@janakdr Ah, got it. I kind of glazed over the details there because I'm not very familiar with Bazel internals. Thanks!

@haxorz If you have a potential patch that you'd like me to test at some point, let me know. I'm seeing this happen multiple times a day now so it should be pretty easy for me to verify whether a fix works.

**Comment by rohansingh** [comment]
@haxorz Thanks so much for the fix!
