### ISSUE TITLE
Reduce OOM risks with --persistent_android_resource_processor by limiting the number of default workers

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#8586]
On a 12-thread machine, building https://github.com/google/google-authenticator-android with `--persistent_android_resource_processor` and aapt2 spawns `23` JVM workers:

```
$ ps -ef | grep java.*ResourceProcessorBusyBox.*persistent_worker | wc -l
23
```

We should cap the number of workers for the resource processor to reduce OOM risks, especially for large builds.

**Comment by jin** [comment]
Here's a benchmark of `shutdown && clean && build //java/com/google/android/apps/authenticator` of various default values for `--worker_max_instances` for the mnemonics covered by `--persistent_android_resource_processor` on a 12-thread linux machine. 

| worker_max_instances | wall time | number of workers | total heap size of all workers | average heap size of a worker | max heap of a worker | 
|----------------------|-----------|-------------------|------------|--------------|----------| 
| 1                    | 32.435    | 7                 | 1273856    | 181979       | 606208   | 
| 2                    | 31.25     | 12                | 2007801    | 167317       | 593920   | 
| 4                    | 32.422    | 22                | 5122431.8  | 233024       | 643072   | 
| auto                 | 32.194    | 22                | 4994452.5  | 227393       | 585728   | 
| 6                    | 34.618    | 32                | 4518322.3  | 141710       | 581632   | 


All heap sizes are in kilobytes.

Number of workers: `jps | grep ResourceProcessorBusyBox | wc -l`
Total heap size: `jps | grep ResourceProcessorBusyBox | cut -d' ' -f1 | xargs -n 1 jstat -gc | sed -n '1~2!p' | awk '{split($0,a," "); sum=a[3]+a[4]+a[6]+a[8]; print sum}' | jq -s 'add'`
Average heap size: `jps | grep ResourceProcessorBusyBox | cut -d' ' -f1 | xargs -n 1 jstat -gc | sed -n '1~2!p' | awk '{split($0,a," "); sum=a[3]+a[4]+a[6]+a[8]; print sum}' | awk '{ total += $1; count++ } END { print total/count }'`
Max heap size: `jps | grep ResourceProcessorBusyBox | cut -d' ' -f1 | xargs -n 1 jstat -gc | sed -n '1~2!p' | awk '{split($0,a," "); sum=a[3]+a[4]+a[6]+a[8]; print sum}' | sort -n | tail -n 1`

\*: [used heap size per worker](https://stackoverflow.com/questions/14464770/how-to-check-heap-usage-of-a-running-jvm-from-the-command-line) is the sum of:

```
S0U: Survivor space 0 utilization (kB).
S1U: Survivor space 1 utilization (kB).
EU: Eden space utilization (kB).
OU: Old space utilization (kB).
```

This is computed using 

```
$ jps | grep ResourceProcessorBusyBox | cut -d' ' -f1 | xargs -n 1 jstat -gc | sed -n '1~2!p' | awk '{split($0,a," "); sum=a[3]+a[4]+a[6]+a[8]; print sum}' | jq -s 'add' 
```

Using this data, it looks like the optimal number of workers is 2. I'll follow up with some tests on macOS.

**Comment by jin** [comment]
cc @meisterT

**Comment by meisterT** [comment]
cc @jmmv 
see also https://github.com/bazelbuild/bazel/pull/6857

**Comment by jin** [comment]
Here are some more stats on a 2018 2-core i7 Macbook Pro, using this benchmark project: https://github.com/jin/simple_tree

![graph](https://user-images.githubusercontent.com/347918/59960608-8ba07780-9498-11e9-89dd-35ad03975307.png)

I extended `--persistent_android_resource_processor` to also include Javac, Desugar and DexBuilder actions, and renamed it to `--android_persistent_workers`. In the stats below, total heap sizes refer to the sum of all heaps across Javac, Desugar, DexBuilder and ResourceProcessorBusyBox actions.

| worker_max_instances | total heap sizes | wall time of execution phase (s) | critical path wall time of execution phase (s) |
| --- | --- | --- | --- |
| 1 | 811MiB | 67.508 | 33.09 | 
| 2 | 1.07GiB | 70.076 | 37.98 | 
| 4 | 2.25GiB | 75.949 | 45.70 |

This is pretty definitive that the default value of 4 workers is far too heavy for MacBook Pros, and turns out that having just 1 worker per action mnemonic can speed things up fairly significantly due to the reduced load.
