### ISSUE TITLE
bazel fails to fetch ssh repos 0.1.5rc1

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#859]
I get this:

```
st-oscar1:bazel-scala-example oscar$ bazel build example-scalding
ERROR: no such package '@bazel//tools/build_defs/scala': Error cloning repository: git@github.com:bazelbuild/bazel.git: reject HostKey: github.com.
INFO: Elapsed time: 0.072s
```
trying this branch: https://github.com/avibryant/bazel-scala-example/tree/oscar/scalding-example

possibly related: https://github.com/int128/gradle-ssh-plugin/issues/69

This is better than the stack trace I get with 0.1.4 like #802 , but the work around is the same: and I still can't work with ssh git repos.

:/

**Comment by kchodorow** [comment]
Is this a regression, or has it always not worked?  (If it's not a regression, we have #810 for adding ssh auth support.)

**Comment by johnynek** [comment]
@kchodorow thanks for the pointer. I don't know. I had assumed ssh would work since the prior failure hit a java ssh class not found issue, but maybe that was a partially implemented bit of code.

**Comment by dslomov** [comment]
Duplicate #810
