### ISSUE TITLE
Building in environments with restricted network access

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#8592]
This is an overview bug for a broad problem space: we want to have a sensible development experience in an environment where direct access to the internet is not available.

For context, I'll start by describing our particular scenario and what we've done about it, but I expect that we're not the only people who have this problem.

We cannot make direct connections to the internet, inbound or outbound. We also cannot, in general, download binaries from the internet and just use them. We can use binaries from the internet if they have been downloaded by a black-box appliance (which does have internet access) and declared to be permitted. The functioning of this black-box is opaque; we treat it as an oracle function which says "yes" or "no" to any given string of bytes. but it gives consistent answers, so results can be cached.

(Practical implementation of the black-box is believed to approximate grep -q "GNU General Public License", but we can't introspect its implementation here; nothing we do will remove the requirement to use this particular black box)

What we have been doing so far to make bazel work is wrapping the black-box appliance in 
repository rules, which automate the process of pushing downloads through it and then deliver the result. This is a huge improvement over anything else we could have done, but is still quite expensive: we have to effectively rewrite/override the workspace of any repository that we use. It's a long way from how smoothly bazel works outside this environment.

Past discussions around this topic have suggested creating an http proxy which runs files through the black-box on demand. This seemed like a promising idea at first, but is complicated by almost all the URLs being https. We would either need an ssl-intercepting http proxy (which can be done, but nothing quite like this exists in the open-source space), or some other approach to the problem.

A notable extra dimension of complexity is that many of the downloads should be run by external tools like git. Ideally these would also work.

Some things which might work:
* generalising the idea of an ssl-intercepting proxy for use in this sort of role
* inventing a variation on http_proxy which delegates ssl to the proxy, and teaching the world of open-source tools to use it
* any better ideas?

**Comment by buchgr** [comment]
Hi Andrew,

I believe this proposal from @jmillikin would solve your problems https://docs.google.com/document/d/1aagKnM8kRmMvLqSXasShsI-NYOBZYtgNrbYWLPwBoBg/edit#.
E-Mail discussion thread here: https://groups.google.com/forum/#!topic/bazel-discuss/V0YFIrZAK7Q/discussion

Best,
Jakob

**Comment by asuffield** [comment]
Yes, that sounds like a viable approach. We'd need to see enough of the rule definition to intercept things like git_repository, which is a little bit deeper than the current design, but only a little bit.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
