### ISSUE TITLE
using remote git_repository seems broken in 0.1.5

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#860]
This branch:

https://github.com/avibryant/bazel-scala-example

builds with bazel 0.1.4. It points to the bazel repo to get the scala support from there:

https://github.com/avibryant/bazel-scala-example/blob/master/WORKSPACE#L1

It works great.

In 0.1.5rc1 I get:
```
st-oscar1:bazel-scala-example oscar$ bazel build example-lib
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package 'external': Every .bzl file must have a corresponding package, but 'tools/build_defs/d' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
INFO: Elapsed time: 0.058s
```
It seems to be complaining about a missing build_rule for D, but I am not using that. It is like the namespacing is broken and it is looking in the current project, not the `git_repository` for that file.

**Comment by damienmg** [comment]
1. The correct way to refer to the scala support should be '@bazel_tools//tools/build_defs/scala:scala.bzl' now.

2. I think the error message is really cryptic, @kchodorow do you know which build file fails to parse?

**Comment by johnynek** [comment]
to loop back around there were a few issues:

1. a .gitconfig that rewrote https to ssh auth
2. ssh is not supported see #810 

this is a public repo so a work around without changing the .gitconfig is to use:
```
git_repository(
  name = "io_bazel_rules_scala",
  remote = "git://github.com/bazelbuild/rules_scala",
  commit = "e077a21eb9a281f904847d79f6367cec00a2adc3"
)
```
works around the rewrite issue.

**Comment by davidzchen** [comment]
This is a pretty old bug. These issues that @johnynek mentioned should be mitigated by #1408.
