### ISSUE TITLE
Add an autodetecting host toolchain

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8603]
Add a repo rule to autodetecting the Python toolchain on the host machine.

For cases where the target platform is the host machine, this avoids issues with relying on `PATH` at execution time to find the right system Python interpreter, e.g. #8536. It does not completely eliminate runtime dependence on `PATH` though, due to the stub script shebang; see also #6817 and #8446.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
