### ISSUE TITLE
Add a test to ensure Bazel can build offline

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8604]
This has been discussed a few times in the past. Bazel shouldn't depend on Internet implicitly.

Recent user report: https://github.com/bazelbuild/bazel/issues/8575

We could have an integration test that we run without Internet access.

**Comment by jin** [comment]
What's the build target? Bazel itself is already tested to build offline using the distfile integration test with `no-network`.

**Comment by meisterT** [comment]
Closing in favor of #8592
