### ISSUE TITLE
remote: retry Execute() with status OK but empty ExecuteResponse

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8605]
If a server closes an Execute()/WaitExecute() call with status OK and an ExecuteResponse.done=false then Bazel should retry the call. This was discovered / requested by @werkt.

**Comment by m3rcuriel** [comment]
Bumping this -- it's blocking our migration to 0.28.0 with buildfarm.

**Comment by m3rcuriel** [comment]
CC @ola-rozenfeld @lberki bumping this again -- can't migrate to 0.28 without this fix.
