### ISSUE TITLE
Inconsistent order for choosing execution platform and toolchains

### ISSUE THREAD

**Issue by eytankidron** [bazelbuild/bazel#8608]
When bazel (0.26.1) chooses what remote execution platform to use (and as a consequence what toolchains to use) for a particular target, it seems to follow the following order of precedence:
* --extra_execution_platforms (in the order specified in .bazelrc)
* --extra_execution_platforms (in the order specified in the bazel command line flag)
* register_execution_platforms (in the order specified in WORKSPACE)
* --host_platform

However, if said target does not define a toolchain type (I saw this for genrule), then the platform specified in --host_platform is used first, and the order of precedence is:
* --host_platform
* --extra_execution_platforms (in the order specified in .bazelrc)
* --extra_execution_platforms (in the order specified in the bazel command line flag)
* register_execution_platforms (in the order specified in WORKSPACE)

This behaviour is inconsistent. The first ordering seems to be the one we want.

**Comment by buchgr** [comment]
Wouldn't one want to always want for the command line flag to override everything else, including .bazelrc?

**Comment by katre** [comment]
@buchgr: Yes, that would be best, but there's not a good way to do that with Bazel's current handling of allowMultiple options.

The actual issue here is the legacy support to prefer the host platform when there are no toolchains required. This should be easy enough to remove.

**Comment by buchgr** [comment]
Agreed. In addition to that it will allows us to specify one fewer flag when configuring Bazel for remote execution (--host_platform=@rbe_default//config:platform) which is great!
