### ISSUE TITLE
Incremental correctness issue with starlark build settings

### ISSUE THREAD

**Issue by juliexxia** [bazelbuild/bazel#8610]
Repro:

# bzl
my_flag = rule(implementation = _imp, build_setting = config.string(flag = True))

# BUILD
load(...)
my_flag(name = 'my_flag')
java_library(name = 'unrelated_target')

$ bazel build //stuff/unrelated_target --//stuff/my_flag=foo
... (works fine)

*delete //stuff/my_flag target *

$ bazel build //stuff/unrelated_target --//stuff/my_flag=foo
... (works fine)

$ bazel build //stuff/unrelated_target --//stuff/my_flag=foo
Error loading option //stuff/my_flag: no such target '//stuff/my_flag'

There are some package cache issues with starlark options parsing. --experimental_build_setting_api will be flipped for .27 but should be flipped back to keep this feature experimental while the fix for this issue is making it into the bazel release.

**Comment by laurentlb** [comment]
Rollback CL is https://github.com/bazelbuild/bazel/commit/536a166270590a8dbc701718550383f3a07cc763

I can cherry-pick it for 0.27
