### ISSUE TITLE
Make workspace_status_command output available for custom rules

### ISSUE THREAD

**Issue by ah-edg** [bazelbuild/bazel#8618]
### Description of the problem / feature request:

The output of workspace_status_command is a file, available in custom rules under `ctx.info_file` (`STABLE_`...) and `ctx.version_file` (others).
It is not possible to retrieve the contents as parsed variables that are universally useable (e.g. in a dict).

Reading the file from custom rules seems to be unsupported in Starlark, probably to guarantee termination.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to use the repository git commit revision and additional stable data in custom rules, e.g. to generate a source file containing the version so the binary I build can report it.

Ideally this could be done by supporting something like `ctx.filename.vars` to retrieve a dict of keys and values - maybe even only for those two files.

###  Have you found anything relevant by searching the web?

I looked and also asked on Stackoverflow myself:
* https://stackoverflow.com/questions/50648052/how-can-i-build-custom-rules-using-the-output-of-workspace-status-command/50702690
* https://stackoverflow.com/questions/56466067/how-can-i-access-ctx-info-file-variables-in-ctx-actions-expand-template

I currently use a workaround reading the vars with bash into environment variables and using bash for templating (see second SO link above). I want to avoid doing so and I want to avoid yet another language in the mix. This should be possible in Starlark only IMO.

PS: Bazel is amazing and this is a very detailed level for nits. Though this would help me a lot and probably unify code for multiple rules in your own org, it is not a blocker. We've been Bazel users for well over a year and are very, very happy. Thank you for your work and please keep it up!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
