### ISSUE TITLE
Envoy fails on Bazel CI with Bazel@HEAD

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8626]
Hey @brandjon,

we are seeing a Python error with Bazel@HEAD that we are not seeing with Bazel 0.26.1
```
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f60e' in position 190: ordinal not in range(128)
```

I believe you updated the Python rules to pick python3 instead of python2 by default in master?

```
Executing tests from //test/extensions/filters/network/thrift_proxy:integration_test
-----------------------------------------------------------------------------
WARNING: Perftools heap leak checker is active -- Performance may suffer
[==========] Running 98 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 96 tests from TransportAndProtocol/ThriftConnManagerIntegrationTest
[ RUN      ] TransportAndProtocol/ThriftConnManagerIntegrationTest.Success/FramedBinary
ERROR:root:Unexpected exception in handler
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/bk-docker-spqt/bazel-downstream-projects/envoy/test/extensions/filters/network/thrift_proxy/driver/generated/example/Example.py", line 239, in process_execute
    result.success = self._handler.execute(args.input)
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d1c957111778f6d978cec2005bbaba74/sandbox/linux-sandbox/4808/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/thrift_proxy/integration_test.runfiles/envoy/test/extensions/filters/network/thrift_proxy/driver/server.py", line 33, in execute
    print("server: execute({0})".format(param))
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f60e' in position 190: ordinal not in range(128)
client exception: 6: Internal error
test/extensions/filters/network/thrift_proxy/integration_test.cc:197: Failure
Expected equality of these values:
  1U
    Which is: 1
  counter->value()
    Which is: 0
[  FAILED  ] TransportAndProtocol/ThriftConnManagerIntegrationTest.Success/FramedBinary, where GetParam() = (4-byte object <00-00 00-00>, 4-byte object <00-00 00-00>, false) (742 ms)
```

**Comment by keith** [comment]
I should be able to fix this on the envoy side when I'm back in the office next week

**Comment by buchgr** [comment]
thanks @keith!

**Comment by lizan** [comment]
@buchgr this is fixed in https://github.com/envoyproxy/envoy/pull/7305

**Comment by keith** [comment]
I've submitted a PR to re-enable it on CI here https://github.com/bazelbuild/continuous-integration/pull/729

**Comment by c-parsons** [comment]
Since this test was re-enabled, it hasn't had a green run with Bazel@HEAD

The errors continue to look like python issues.

```
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/06fadb9199abde754fea02f0bf6240b7/sandbox/linux-sandbox/4812/execroot/envoy/bazel-out/k8-fastbuild/bin/test/extensions/filters/network/thrift_proxy/integration_test.runfiles/com_github_twitter_common_rpc/twitter/common/rpc/finagle/trace.py", line 36, in from_value
    elif isinstance(value, (int, long)):
NameError: name 'long' is not defined
```

and

```
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/06fadb9199abde754fea02f0bf6240b7/sandbox/linux-sandbox/4403/execroot/envoy/bazel-out/k8-fastbuild/bin/test/integration/hotrestart_test.runfiles/envoy/tools/socket_passing.py", line 13, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'
```

**Comment by brandjon** [comment]
That "client" target you updated with `python_version = "PY2"` appears to still be using Python 3. That probably means it's being used in the host config and you need to add `--host_force_python=PY2` to the top-level bazelrc (for the "build" command).

**Comment by keith** [comment]
I'm trying to use that flag, but based on @lizan's PR that only set a few of our py_binary targets to PY2, so I'm not sure it will work still. https://github.com/envoyproxy/envoy/pull/7337

Is there any way we can trigger that bazel job against this PR if it does end up being green on normal envoy CI?

**Comment by c-parsons** [comment]
I'm not sure (hoping @buchgr or @meteorcloudy can chime in), but you could manually build a bazel@HEAD and try to replicate the build locally? That would at least give us a good guess on whether things are fixed

**Comment by keith** [comment]
Well my PR was merged upstream so we can wait for the next run and see if that fixed this case.

**Comment by meteorcloudy** [comment]
We have no way to trigger a CI build with Bazel@HEAD for a PR from envoy. But it's easy to get a Bazel binary built from HEAD.
```
wget https://storage.googleapis.com/bazel-builds/artifacts/ubuntu1404/<bazel commit>/bazel
```

**Comment by brandjon** [comment]
@keith, looks like the [httplib failure](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/df6b6191-1a51-47bb-b763-bc0d8dc68a31/test/integration/hotrestart_test/attempt_1.log) is [still there at head](https://buildkite.com/bazel/envoy/builds/817#df6b6191-1a51-47bb-b763-bc0d8dc68a31), which is why the downstream pipeline [hasn't picked up your other change](https://github.com/envoyproxy/envoy/issues/7379#issuecomment-505345602).

>   File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/4706/execroot/envoy/bazel-out/k8-fastbuild/bin/test/integration/hotrestart_test.runfiles/envoy/tools/socket_passing.py", line 13, in <module>
>    import httplib
> ModuleNotFoundError: No module named 'httplib'

It sounds like [`socket_passing`](https://github.com/envoyproxy/envoy/blob/5ee70cb19ca3bb6d817bae497b63c2a250d2d16b/tools/BUILD#L21) needs to be declared `python_version = "PY2"`.

**Comment by brandjon** [comment]
See also [this comment](https://github.com/envoyproxy/envoy/issues/7379#issuecomment-505357431) about how to ensure `httplib` is available in the Python environment. But it sounds like you already have httplib available for PY2 and just need to make this target PY2.

**Comment by keith** [comment]
This should be fixed by https://github.com/envoyproxy/envoy/pull/7391

**Comment by keith** [comment]
Envoy CI is now on 0.27.0, so I'm hoping we're good on the next bazel CI run now

**Comment by meteorcloudy** [comment]
Envoy is green on Bazel CI! Thanks for the fix!
