### ISSUE TITLE
Unable to build tensorflow from source with bazel for C++

### ISSUE THREAD

**Issue by jonywalker1998** [bazelbuild/bazel#8627]
I tried to build tensorflow r1.13 GPU with bazel on windows, and followed the instruction
https://www.tensorflow.org/install/source_windows extractly, but without success.
I am new using bazel, normally I use cmake build, but the cmake build is no more supported. I used bazel 0.21 since the 0.23 not accepted. Following are the build output:
>D:\DATA\workspace\backup\tensorflow-1.13>python ./configure.py
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
nul
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Invocation ID: 48dfb31a-b74b-4104-842d-e65640c8d7a5
You have bazel 0.21.0 installed.
Please specify the location of python. [Default is C:\Python35\python.exe]:

>Found possible Python library paths:
  C:\Python35\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Python35\lib\site-packages]

>Do you wish to build TensorFlow with XLA JIT support? [y/N]: y
XLA JIT support will be enabled for TensorFlow.

>Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

>Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

>Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10.0]: 9.0

>Please specify the location where CUDA 9.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0]:

>Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:

>Please specify the location where cuDNN 7 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0]:

>Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 3.5,7.0]: 6.1

>Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: /arch:AVX2

>Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: Y
Eigen strong inline overridden.

>Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
        --config=gdr            # Build with GDR support.
        --config=verbs          # Build with libverbs support.
        --config=ngraph         # Build with Intel nGraph support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=noaws          # Disable AWS S3 filesystem support.
        --config=nogcp          # Disable GCP support.
        --config=nohdfs         # Disable HDFS support.
        --config=noignite       # Disable Apacha Ignite support.
        --config=nokafka        # Disable Apache Kafka support.
        --config=nonccl         # Disable NVIDIA NCCL support.

>D:\DATA\workspace\backup\tensorflow-1.13>bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
d:\data\workspace\backup\tensorflow-1.13/.bazelrc
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Invocation ID: 1eca8146-2b0a-4ba3-9e96-ea47fd2407ce
INFO: Analysed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 5.232s, Critical Path: 0.04s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

But nothing was built!

**Comment by rongjiecomputer** [comment]
This is because you did not specify the build target (`//tensorflow/tools/pip_package:build_pip_package`) you want to build, so Bazel exits without doing anything.

Run `bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package` instead (copied from the doc you posted).

**Comment by jin** [comment]
@jonywalker1998 please try out the solution by @rongjiecomputer, and reopen this issue if it doesn't work for you. Thanks.
