### ISSUE TITLE
bazel 0.1.5rc1 does not set up bazel_tools repo

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#863]
After installing with --user, I have:

```
st-oscar1:Downloads oscar$ cd ~/.bazel
st-oscar1:.bazel oscar$ find ./
./
.//bin
.//bin/bazel
.//bin/bazel-complete.bash
.//bin/bazel-real
.//etc
.//etc/bazel.bazelrc
```
which I guess is related to build failures later.

**Comment by johnynek** [comment]
actually this seems unrelated to my problem. The issue seemed to be if I copy rules into my `tools/build_def` directory, it produces really confusing error messages.

**Comment by kchodorow** [comment]
Bazel should no longer require the base_workspace.  It is no longer created by the installer and can be removed from the package path.
