### ISSUE TITLE
ctx.split_attr broken nondeterministically with Starlark transitions

### ISSUE THREAD

**Issue by juliexxia** [bazelbuild/bazel#8633]
ctx.split_attr builds itself for every starlark rule, encompassing every attribute with a split transition. In doing so it actually applies transition but doesn't do any of the set up or tear down work necessary for starlark transitions to properly be applied.

**Comment by juliexxia** [comment]
ctx.split_attr also automatically keys on cpu which means it doesn't return the right mapping for transitions keyed on anything else and can throw IllegalStateExceptions. 

Unfortauntely I'm just now finding this issue though it seems to have been broken forever. 49862c5fa66f65deb513ee938d3d052b9e4cfbbe puts a bandaid on the issue by just disallowing ctx.split_attr to include starlark transitioned attrs while we work on fixing this.

**Comment by laurentlb** [comment]
I don't think we should delay (again) the release for this, unless it worked with Bazel 0.26.

**Comment by juliexxia** [comment]
I get that. The only reason I ask is because it can lead to hard bazel crashes which I thought upped the priority level of bugs. But I leave the decision up to you as release manager!

**Comment by katre** [comment]
@juliexxia, please update or close this issue.

**Comment by juliexxia** [comment]
This issue seems like it watch band-aid-ed when it first came up (which has definitely been released in Bazel by now) and it's full functionality with a fix will be released soon!
