### ISSUE TITLE
Homebrew install is missing tools in base_workspace

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#864]
I'm not sure if this is the right place to file this. (Do I need to file it against the Homebrew repo?)

Actual:
```
$ ls -l /usr/local/Cellar/bazel/0.1.4/base_workspace/tools
total 8
-rw-r--r--  1 dfabulich  admin  97 Jan 15 04:55 BUILD
-rw-r--r--  1 dfabulich  admin   0 Jan 15 04:55 DONT_FOLLOW_SYMLINKS_WHEN_TRAVERSING_THIS_DIRECTORY_VIA_A_RECURSIVE_TARGET_PATTERN
```

Expected: For comparison, when I run the OS X bazel installer from https://github.com/bazelbuild/bazel/releases the base_workspace/tools folder is full of stuff.

```
$ ls -l /usr/local/lib/bazel/base_workspace/tools
total 24
-rw-r--r--@  1 dfabulich  wheel  1926 Dec 31  1979 BUILD
-rw-r--r--@  1 dfabulich  wheel    97 Dec 31  1979 bazel.rc
drwxr-xr-x@  8 dfabulich  wheel   272 Dec 31  1979 build_defs
drwxr-xr-x@ 10 dfabulich  wheel   340 Dec 31  1979 build_rules
drwxr-xr-x@  4 dfabulich  wheel   136 Dec 31  1979 buildstamp
drwxr-xr-x@  5 dfabulich  wheel   170 Dec 31  1979 cpp
drwxr-xr-x@  3 dfabulich  wheel   102 Dec 31  1979 defaults
drwxr-xr-x@  4 dfabulich  wheel   136 Dec 31  1979 genrule
drwxr-xr-x@  4 dfabulich  wheel   136 Dec 31  1979 j2objc
drwxr-xr-x@  6 dfabulich  wheel   204 Dec 31  1979 jdk
drwxr-xr-x@ 11 dfabulich  wheel   374 Dec 31  1979 objc
drwxr-xr-x@  4 dfabulich  wheel   136 Dec 31  1979 python
drwxr-xr-x@  4 dfabulich  wheel   136 Dec 31  1979 test
-rw-r--r--@  1 dfabulich  wheel   149 Dec 31  1979 test_sharding_compliant
```

**Comment by kchodorow** [comment]
Bazel should no longer need the base_workspace, so we removed it from the installer.  Are you seeing errors?

**Comment by dfabulich** [comment]
Yes. Without the base_workspace, none of the tools can be imported.

To repro:
https://github.com/dfabulich/wtf_pkg_tar

It's a simple BUILD file https://github.com/dfabulich/wtf_pkg_tar/blob/master/BUILD
```
load("/tools/build_defs/pkg/pkg", "pkg_tar", "pkg_deb")

pkg_tar(
	name = "aoeu"
)
```

When I run the Homebrew installation:

```
$ bazel build //:aoeu
ERROR: error loading package '': Extension file not found. Unable to load file '//tools:build_defs/pkg/pkg.bzl': file doesn't exist or isn't a file.
```

When I run the OS X installer, the build succeeds.

**Comment by kchodorow** [comment]
You should be able to `load('@bazel_tools//tools/build_defs/pkg/pkg.bzl', 'pkg_tar', 'pkg_deb')`.

**Comment by dfabulich** [comment]
```
$ bazel build //:aoeu
ERROR: error loading package '': Extension file not found. Unable to load package for '@bazel_tools//tools/build_defs/pkg:pkg.bzl': BUILD file not found on package path.
```

**Comment by dfabulich** [comment]
FWIW, http://bazel.io/docs/be/pkg.html says: `load("/tools/build_defs/pkg/pkg", "pkg_tar", "pkg_deb")` and that's the only version I've seen to work.

**Comment by damienmg** [comment]
`bazel version`?

**Comment by damienmg** [comment]
Sorry I just saw it's 0.1.4. It has a bug that did not included pkg extension.

I will try with 0.1.5rc1 and release it today if it works. We should also update the README files.

**Comment by damienmg** [comment]
Tested with 0.1.5rc1, I'll send the documentation updates and push 0.1.5

**Comment by dfabulich** [comment]
It works now with `load('@bazel_tools//tools/build_defs/pkg:pkg.bzl', 'pkg_tar', 'pkg_deb')` in v0.1.5, but the documentation in master still says to use `/tools`.

**Comment by damienmg** [comment]
I updated the documentation internally and it should be updated tomorrow.
