### ISSUE TITLE
Allow exported name override for rules

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#8640]
When a rule is defined, the first name of that rule gets special treatment as the forever-name of the rule (for example, under `bazel query`)

For example:

```python
_fake_rule_name = rule(...)

foo_library = _fake_rule_name
```

When querying `foo_library` targets using `bazel query`, the targets will show up as type `_fake_rule_name` because that was their first name.

This is counter-intuitive, and it often becomes problematic in cases when users would like to override this behavior.
One concrete example where an override makes sense: https://github.com/bazelbuild/bazel/issues/7977#issuecomment-488118667

One should be allowed to specify the canonical rule name of a rule definition, overriding the behavior that this must be the first exported name.

**Proposal:**
Add a string parameter to the `rule()` function, `exported_name`. When specified, the rule will have this canonical name. When unspecified, the rule will take on the name of the first exported name (previous behavior). This change will not require an incompatible change flag.

**Comment by katre** [comment]
This does not appear to be a P1. Downgrading and marking as untriaged so Starlark team can decide about whether this is needed.

**Comment by brandjon** [comment]
Dedupping against #5078.
