### ISSUE TITLE
dynamic spawn strategy does not take download time into account

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8647]
The dynamic spawn strategy does not take downloading of output files into account when being used with remote execution but will only take cache hit/miss + execution time into account.

We'll need to change the SpawnRunner interface to differentiate between generation of action outputs (execution + download) and moving the outputs into the correct place.

Related https://github.com/bazelbuild/bazel/issues/8646

**Comment by jmmv** [comment]
@buchgr, I think this was already done?

**Comment by buchgr** [comment]
yep
