### ISSUE TITLE
Get rid of bundled stuff

### ISSUE THREAD

**Issue by KOLANICH** [bazelbuild/bazel#8650]
### Description of the problem / feature request:
Bundling dependencies is an extremily bad practice. Instead packages installed into OS should be used.

### Feature requests: what underlying problem are you trying to solve with this feature?

1. The size of Bazel distributions proposed to be downloaded is too large.
2. I don't want to use the bundled java.
3. I don't like binaries unpacking stuff somewhere so I have to use strace to get known what is unpacked and where
4. even a `deb` package you distribute is just the same piece of ... bazel, just wrapped in a deb package.

So

1. self-unpacking archives should be replaced with just archives
2. instead of bundling java and/or libs there should be 2 archives: one for dependencies (without java), one for bazel.  Archive with dependencies is downloaded and unpacked by a user manually if he feels he needs it.  And a user should be instructed what packages to install instead of unpacking dependencies. Java should not be added and should always be installed by a user.
3. proper packages should be created automating instalation of the stuff. No sfx installers or code fetching the data from inet in them!

### What operating system are you running Bazel on?
* Ubuntu 19.04 disco
* Debian stretch

**Comment by dslomov** [comment]
I do not appreciate the tone and the attitude of this feature request. Please express your requests in more respectful manner in the future.
