### ISSUE TITLE
incompatible_skip_genfiles_symlink: Remove bazel-genfiles symlink

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8651]
Since Bazel 0.25 (and https://github.com/bazelbuild/bazel/issues/6761), both `bazel-genfiles` and `bazel-bin` point to the same location.

When the flag `incompatible_skip_genfiles_symlink` is set, the `bazel-genfiles` symlink is not created. This flag will be introduced in Bazel 0.29 and enabled by default in Bazel 1.0.

This may break external scripts that refer to the `bazel-genfiles` symlink. The fix is to replace `bazel-genfiles` with `bazel-bin`.

**Comment by laurentlb** [comment]
@lberki, do you know how to do it? I'm not familiar with this code.

**Comment by lberki** [comment]
It's in `OutputDirectoryLinksUtils`:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildtool/OutputDirectoryLinksUtils.java#L142

So it shouldn't be very hard, but I'm unable to sign up anyone on my team to following through with the incompatible flag process.

Why is this a P1?

**Comment by laurentlb** [comment]
My hope is that the change in Bazel is easy to do (we can reevaluate if it's not).

Symlinks in the user directory are highly visible (anyone running Bazel will notice it). I'd rather remove it than have to document it. It's an incompatible change that will affect many people (https://github.com/search?q=bazel-genfiles&type=Code), so I'd rather do it earlier than later.

**Comment by dslomov** [comment]
This P1 bazel-1.0 issue is unassigned. Please assign cc @laurentlb

**Comment by drigz** [comment]
@laurentlb Should the docs be updated for this? https://docs.bazel.build/versions/master/output_directories.html#documentation-of-the-current-bazel-output-directory-layout
