### ISSUE TITLE
TypeScript Incremental Compilation

### ISSUE THREAD

**Issue by pspeter3** [bazelbuild/bazel#8653]
### Description of the problem / feature request:

[TypeScript](https://www.typescriptlang.org/) supports incremental compilation as of [v3.4](https://devblogs.microsoft.com/typescript/announcing-typescript-3-4/). In order to cache this information, it creates a `.tsbuildinfo` for each compilation with a well known path. With Starlark, it does not seem possible to provide this output file as an input to future compilations.

### Feature requests: what underlying problem are you trying to solve with this feature?

Allow certain outputs to be used during sandboxing for future builds but not included in the input set. Ideally, the compiler should be able to access the `.tsbuildinfo` but does not need it for compilation.

**Comment by alexeagle** [comment]
Bazel pretty much has this built-in, long before TypeScript added the feature. What are you hoping would behave differently?
That said we think there might be a chance to simplify as an internal refactoring.

**Comment by pspeter3** [comment]
Can you explain how? I know that I can shard compilation and make it incremental by splitting packages. However, at the size of our build graph, using TypeScript's type check cache would be leveraged. The compiler can use the `.tsbuildinfo` files to skip type checking files it has already checked. I view this as similar to the bazel Scala rules which use a worker process to cache information.

**Comment by irengrig** [comment]
Thank you for the issue.

> In order to cache this information, it creates a .tsbuildinfo for each compilation with a well known path. 
As far as I know, accessing any file by a path is already possible with current implementation of sandboxing. I.e. the tools like typescript compiler can already use those local files provided they access it with absolute paths on your local system.

Also, as Alex replied, Bazel in general already have incremental builds feature, it will only rebuild the targets with the changed inputs. For that, the build targets should already describe their inputs, i.e. it is as grained as you create it.
I haven't looked deeply into Typescript's incremental compilation, does it add incrementality on more fine-grained basis?

(Also, if you wanted the same behavior with remote execution, you need to specify all inputs explicitly to be uploaded to the remote host, but then you probably wanted to keep also the updated cache.
But first I would like to know if there is a performance gain in using typescript's incremental mode with Bazel.)

**Comment by pspeter3** [comment]
I believe that there would be a performance gain for Bazel.

Currently we use Bazel to produce `*.d.ts` and `*.js` files from `*.ts` files. We only use the `*.d.ts` files from input packages and get caching from Bazel if the `*.d.ts` files do not change. I think this is what you are referring to as incremental compilation? _(I want to make sure I am using the correct terms)_

TypeScript's `--incremental` flag does a few things. One aspect is to add Bazel style incremental caching when used with TypeScript projects. In this case, it would be redundant of Bazel though likely not harmful. Another aspect is to prevent type checking on packages it has already checked before. This is useful when have many packages as inputs to a package but only one dependency changed. It only needs to recompute the type information for that dependency which speeds up compilation. That's my understanding from the research @mmorearty has been doing.

I can understand why this feature may not fit well with the Bazel ecosystem (especially with Remote Workers) but figured I would file an issue and learn more.

**Comment by pauldraper** [comment]
> With Starlark, it does not seem possible to provide this output file as an input to future compilations.

Basically correct. For a long discussion on stateful compilers, see https://groups.google.com/forum/#!msg/bazel-discuss/3iUy5jxS3S0/9HtzLEVIEQAJ

There are two exceptions:

1. Dependency pruning. Native rules have long had this, and it was recently added to Starlark as [`unused_inputs_list`](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run). This allows actions to declare certain inputs as unused. Bazel ignores any changes in those files, a used files is changed.

2. Workers. Workers save state, at the expense of looser correct guarantees. For example, I believe rules_typescript caches ASTs between runs. It could save .tsbuildinfo.

**Comment by pspeter3** [comment]
Yeah, my thought was that we could build this as a worker. Are workers allowed to read/write files that get shared by remote caching? It would be nice to share the .tsbuildinfo across multiple machines.

**Comment by jmmv** [comment]
Workers are local processes so they can only read whatever is on the local machine. If you can make the remote action generate outputs with the data you need, then those outputs will be downloaded by Bazel. If those outputs are inputs to the following actions (which run in workers), then the workers could use those details too.

It's unclear to me what feature request is being made here for Bazel. So far, the contents of this bug seem to be more of a discussion than a specific request, and that belongs better in the bazel-discuss mailing list. Please continue there and once you have a specific feature request for Bazel, reopen this one. (Or if you have such a request already, please clarify and reopen as well.) Thanks!

**Comment by pauldraper** [comment]
@jmmv, the original feature request was for actions to be able to reuse previous state.

I.e. another instance of https://groups.google.com/forum/#!msg/bazel-discuss/3iUy5jxS3S0/9HtzLEVIEQAJ

That said, I believe the existing answer of "use a worker for that" is a satisfactory answer.
