### ISSUE TITLE
Linking Issues with GCC in Bazel 0.27

### ISSUE THREAD

**Issue by henryqinshield** [bazelbuild/bazel#8656]
### Description of the problem / feature request:

We have just upgraded to bazel 0.27. When we go to build, we are seeing a problem with build outputs in that they are not linking properly. We are using GCC to compile and link. We are also using our own custom crosstool as seen in the attached file. 

When we set --incompatible_do_not_split_linking_cmdline=false, everything seems to link and run properly.

### What operating system are you running Bazel on?

Ubuntu 16.04

###  Have you found anything relevant by searching the web?

When I looked at https://github.com/bazelbuild/bazel/issues/7687 it seems to suggest that this only affects CROSSTOOLS with a param file. We don't use a param file but are still seeing these issues...

[crosstool_config.bzl.txt](https://github.com/bazelbuild/bazel/files/3298762/crosstool_config.bzl.txt)

**Comment by scentini** [comment]
cc/ @oquenchil

**Comment by hlopko** [comment]
You can run your build with `--subcommands` to see full gcc invocations and you can diff the command line before and after the `--incompatible_do_not_split_linking_cmdline` flip. That will help you isolate the problem. Maybe a simple reordering of features in your `crosstool_config.bzl` will be enough afterwards.
