### ISSUE TITLE
Use rules_jvm_external to manage Bazel's third_party Java dependencies

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#8658]
Once https://github.com/bazelbuild/rules_jvm_external/pull/169 is merged, rules_jvm_external will be able to resolve Maven dependencies transitively using `maven_install.json`, a pinned list of transitive artifacts. This file is generated with an initial call to Coursier via rules_jvm_external. Subsequent calls will use `http_file` with sha256 checksums to verify integrity and take advantage of Bazel's repository cache.

Benefit 1: **No need to vendor jars in third_party**. Instead, one can just update the `maven_install` declaration in the WORKSPACE file with new artifacts / versions, and check in the updated `maven_install.json` file. Contributions touching `third_party` no longer need to be split up into two changes (third_party and non-third_party).

Benefit 2: **No need for Bazel maintainers to manually wire up transitive dependencies in third_party.** `rules_jvm_external` will resolve and fetch artifacts from Maven into `$output_base/external/@maven` with a fully wired up BUILD file. The missing piece is a post-build step to vendor that directory back into Bazel's source tree.

Benefit 3: **Maintaining capability for fully offline builds**, since artifact downloads will be managed by Bazel and can be integrated with the distdir in a straightforward manner.

**Comment by buchgr** [comment]
AFAIK we'll still need to vendor them for two reasons:
1. there is a security requirement that every dependency added needs to be code reviewed by a  Bazel contributor
2. we need to be able to bootstrap without internet

However, I believe what rules_jvm_external should be able to do is generate the vendor directory automatically based on a maven_install.json?

**Comment by buchgr** [comment]
@ulfjack will know all the details. it's been proposed in the past ...

**Comment by jin** [comment]
> However, I believe what rules_jvm_external should be able to do is generate the vendor directory automatically based on a maven_install.json?

Correct. The files would be generated into `$output_base/external`, but we can copy it back into the source tree.

> there is a security requirement that every dependency needs to be code reviewed and LGTMed by a Bazel contributor

Is the SHA256 checksum of a dependency a sufficient proxy for the dependency itself?

> we need to be able to bootstrap without internet

This will be possible using the distdir_tar, like how we currently manage remote_java_tools and remote_android_tools.

**Comment by buchgr** [comment]
> Is the SHA256 checksum of a dependency a sufficient representation for the dependency itself?

The last few times we talked about this it was not ...

**Comment by jin** [comment]
> The last few times we talked about this it was not ...

Fair enough. I have a PR that allows rules_jvm_external to write directly into a source tree and use the new `workspace.managed_directories`: https://github.com/bazelbuild/rules_jvm_external/pull/168

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by jin** [comment]
I think @meteorcloudy has fixed this?

**Comment by meteorcloudy** [comment]
Yes, working on https://github.com/bazelbuild/bazel/pull/17221 to migrate the rest of Bazel's jar dependencies to rules_jvm_external.
