### ISSUE TITLE
Exception when trying to depend on target with transitive dependency of JAR resource

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#8659]
### Description of the problem / feature request:

When trying to depend on a repo that declares a `java_binary` which depends on something [in different external repo] via `resources`, `bazel` throws

```
Caused by: java.lang.IllegalArgumentException: Path 'external/remote_java_tools_darwin/java_tools/src/tools/singlejar/singlejar_local' is not under 'external/b', cannot relativize
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm reusing custom `singlejar` implementation in multiple repos. My custom implementation happens to depend on original `singlejar` binary (`@bazel_tools//tools/jdk:singlejar`) via `resources` attribute.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Two workspaces:

```
13:26:32 vmax@ghost tmp master ? tree
.
├── a
│   ├── BUILD
│   ├── WORKSPACE
│   └── test.sh
└── b
    ├── BUILD
    ├── Main.java
    ├── WORKSPACE
```

Workspace `@a`:

`BUILD`:

```
sh_test(
    name = "test",
    srcs = ["test.sh"],
    data = ["@b//:main"]
)
```

`WORKSPACE`:

```
local_repository(
    name = "b",
    path = "<…>/tmp/b"
)
```

`test.sh`: empty, has `+x` flag

Workspace `@b`:

`BUILD`:

```
java_binary(
    name = "main",
    srcs = ["Main.java"],
    resources = [
        "@bazel_tools//tools/jdk:singlejar"
    ],
    main_class = "com.example.Main",
    visibility = ["//visibility:public"]
)
```

`Main.java`:

```
package com.example;

public class Main {
    public static void main(String[] args) {}
}
```

`WORKSPACE`: empty

### What operating system are you running Bazel on?

`macOS Mojave 10.14.5`

### What's the output of `bazel info release`?

`release 0.27.0`
Note: `0.26.1` is *not* affected.

### Any other information, logs, or outputs that you want to share?

- Building `//:main_deploy.jar` from `@b` *is* supported regardless of version
- Building `@b//:main_deploy.jar` from `@a` *does* work on `0.26.1`
- Building `@b//:main_deploy.jar` (or any other target from `@a` that depends on anything from `@b`) from `@a` *does not* work on `0.27.0` — see
[build.log](https://github.com/bazelbuild/bazel/files/3301096/build.log)

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
