### ISSUE TITLE
OS X installer --bazelrc option doesn't work

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#867]
To repro:
```
./bazel-0.1.4-installer-darwin-x86_64.sh --bazelrc=/tmp/bazelrc
```
Now, edit /tmp/bazelrc and put a junk parameter in there.

```
build --foo=bar --package_path %workspace%:/usr/local/lib/bazel/base_workspace
fetch --package_path %workspace%:/usr/local/lib/bazel/base_workspace
query --package_path %workspace%:/usr/local/lib/bazel/base_workspace
```

Expected: `Unrecognized option: --foo=bar` That's what happens if you put a junk parameter in `/etc/bazel.bazelrc`.

Actual: The parameter is ignored. 

If you look at `template_bin.sh`, you can see that the installer itself _writes_ to the custom bazelrc location, but the `bazel` executable is hard-coded to use `/etc/bazel.bazelrc`; at no point is the `bazel` executable modified or updated to use a custom location.

**Comment by damienmg** [comment]
That's working as intended. This special set-up is for people that add a `startup --bazelrc /tmp/bazelrc` to the workspace bazelrc.
