### ISSUE TITLE
aar_import does not offer a srcjar option

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#8671]
### Description of the problem / feature request:

aar_import doesn't provide a facility to link a source-jar, which limits IDEs abilities to materialize the sources of imported .aar libraries. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Improved IDE integration.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to do a `aar_import` and there is no API to do this. 

### What operating system are you running Bazel on?

Mac OS X

### What's the output of `bazel info release`?

0.26.1

###  Have you found anything relevant by searching the web?

Looked around issues and fora, chatting about it on slack, but nothing seems to have been conclusively decided.

### Any other information, logs, or outputs that you want to share?

Investigating AarImport.java, it seems that it creates a JavaCommon which could include source artifacts, but does not, explicitly passing in an empty immutable list.  This seems entirely feasible, but the API isn't exposed and the bits aren't hooked up.

**Comment by ahumesky** [comment]
Yeah, this is something we'll want to add, but we'll have to find time for it

**Comment by cgruber** [comment]
Amazing.  Thank you!
