### ISSUE TITLE
RE combined with BES is slow with large output artifacts

### ISSUE THREAD

**Issue by cphang99** [bazelbuild/bazel#8673]
### Description of the problem / feature request:

When BES is used in conjunction with remote-execution, output artifacts tagged `no-remote` and `no-cache` are uploaded to the CAS. When these outputs are large in size, this can result in significant performance penalties.

More concretely, we have seen significant performance penalities when BES is used in conjunction with RE, but *not* when each was used in isolation.

It would be beneficial to introduce a bazel command line flag which would disable BES artifact upload for output artifacts corresponding to targets that are marked `no-remote` and `no-cache`. The paths for output files corresponding to these targets should be local (or none at all) and not bytestream:/// pathnames.

### What operating system are you running Bazel on?

macOS 10.14.x

### What's the output of `bazel info release`?

release 0.25.3

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/8249 refers to how file URIs are automatically translated to bytestream:/// paths in remote execution/remote cache contexts

**Comment by buchgr** [comment]
Interesting. Are you suggesting that we should not reference these files at all then in the BEP?

**Comment by ishikhman** [comment]
Hm, can it be because those tags are not properly propagated? 
What rules were you using for those tagged targets?

**Comment by cphang99** [comment]
> Interesting. Are you suggesting that we should not reference these files at all then in the BEP?

I think so. We should not reference them with bytesream paths if that results them being uploaded to the CAS.

**Comment by cphang99** [comment]
> Hm, can it be because those tags are not properly propagated?
> What rules were you using for those tagged targets?

We’re using a custom rule, but we can verify that the `no-remote` and `no-cache` tags are being correctly propagated.

For a particular target that produces 2GB artefacts, with `no-remote` and `no-cache` tags set, a bazel build of that target is 10x slower, but *only* when BES + remote execution is enabled. Interestingly, this is not shown in the elapsed time, but only on using a `time` command.
```
INFO: Elapsed time: 4.706s, Critical Path: 0.63s
INFO: 0 processes.

real    0m40.333s
user    0m0.040s
sys     0m0.028s
```

**Comment by cphang99** [comment]
One suggestion:

We have observed that enabling `—experimental_remote_download_outputs` i.e. builds without the bytes makes the issue go away in 0.25.3. We have tracked this down to here 

https://github.com/bazelbuild/bazel/blob/0.25.3/src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java#L250-L267.

We understand that from bazel 0.28, BES will be supported with builds without the bytes (https://github.com/bazelbuild/bazel/pull/8669) but we were wondering whether an additional flag (that would be independent of `--experimental_remote_download_outputs`) that would optionally disable artifact uploads from BES would be useful as well

**Comment by arlyon** [comment]
Update, seems that this is a symptom of issue #7630 which is being looked into
