### ISSUE TITLE
Compiling from source fails because of assumptions about JAVA_VERSION

### ISSUE THREAD

**Issue by annaken** [bazelbuild/bazel#8675]
### Description of the problem:

I'm building bazel 0.25.2 for Docker image openjdk:8-slim from source, but the compile stage fails like

    env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
    ...
    Building Bazel from scratchscripts/bootstrap/compile.sh: line 79: 
        [: 8u212-b04: integer expression expected
    ERROR: JDK version (1.8) is lower than 8u212-b04, please set $JAVA_HOME.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm following the instructions at following instructions at https://docs.bazel.build/versions/master/install-compile-source.html

### What operating system are you running Bazel on?

Docker image openjdk:8-slim ie Debian Stretch

### Cause

I'm pretty sure the issue is that in the source code, https://github.com/bazelbuild/bazel/blob/master/scripts/bootstrap/buildenv.sh#L80
JAVA_VERSION is set to whatever it is already set to in the OS. 
However in this openjdk-slim image, JAVA_VERSION is not set to a numeric value, ie

    echo $JAVA_VERSION
    8u212-b04

In the error message, "integer expression expected" is helpful but "please set $JAVA_HOME" is misleading.

### Workaround

If I do `export JAVA_VERSION=''` before I compile then the build succeeds because now the buildenv script sets JAVA_VERSION to 1.8.

**Comment by katre** [comment]
Closed for lack of activity. Please ping the reviewers to reopen if this is still a problem in a recent version of Bazel.
