### ISSUE TITLE
Tensorflow with CUDA build failure in Docker

### ISSUE THREAD

**Issue by AlexJoz** [bazelbuild/bazel#868]
Hello) Trying to make dockerfile from ubuntu 14: tensorflow on python3 with cuda and ec2 support ..
In dockerfile have smth like this:
```
RUN  TF_UNOFFICIAL_SETTING=1 \
     TF_CUDA_COMPUTE_CAPABILITIES=3.0 \
     PYTHON_BIN_PATH=/usr/bin/python3 ./configure && \
   bazel build \
     --config=cuda \
     --verbose_failures \
     --spawn_strategy=standalone \
     --local_resources 4096,1.0,1.0 \
     tensorflow/tools/pip_package:build_pip_package && \

    bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip && \

    echo $(date) : "=== Building wheel" && \

    python3 setup.py bdist_wheel --python-tag py34 >/dev/null && \

    pip3 install --upgrade /tmp/pip/tensorflow-0.6.0-py34-none-any.whl
```

Without --localresources had "Killed" error like [here](http://stackoverflow.com/questions/34699069/building-tensorflow-from-source-on-ubuntu-14-04-lts-gcc-internal-compiler-erro)
--spawn_strategy from [here](https://github.com/bazelbuild/bazel/issues/698)

Now have such error, and have no idea what to do next =(

`____[577 / 1,175] Compiling tensorflow/python/pywrap_tensorflow.cc
____[580 / 1,175] Compiling tensorflow/core/util/work_sharder.cc [for host]
____[585 / 1,175] Compiling tensorflow/core/lib/hash/crc32c.cc [for host]
____[587 / 1,175] Compiling tensorflow/core/lib/histogram/histogram.cc [for host
]
ERROR: /tensorflow/tensorflow/stream_executor/BUILD:5:1: undeclared inclusion(s)
 in rule '//tensorflow/stream_executor:stream_executor':
this rule is missing dependency declarations for the following files included by
 'tensorflow/stream_executor/cuda/cuda_rng.cc':
  '/tensorflow/tensorflow/stream_executor/cuda/cuda_rng.h'
  '/tensorflow/tensorflow/stream_executor/cuda/cuda_activation.h'
  '/tensorflow/tensorflow/stream_executor/cuda/multi_op_activation.h'
  '/tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.h'
  '/tensorflow/tensorflow/stream_executor/cuda/cuda_kernel.h'
  '/tensorflow/tensorflow/stream_executor/cuda/cuda_driver.h'
  '/tensorflow/tensorflow/stream_executor/cuda/cuda_helpers.h'
  '/tensorflow/tensorflow/stream_executor/cuda/cuda_platform_id.h'
  '/tensorflow/tensorflow/stream_executor/cuda/cuda_stream.h'.

____Building complete.
Target //tensorflow/tools/pip_package:build_pip_package failed to build

____Elapsed time: 998.708s, Critical Path: 715.53s`

**Comment by damienmg** [comment]
Which version of TensorFlow are you using?

**Comment by damienmg** [comment]
(also which version of bazel?)

**Comment by AlexJoz** [comment]
BAZEL_VERSION 0.1.4
TensorFlow 0.6.0

**Comment by damienmg** [comment]
I think this is a TensorFlow issue not a Bazel one. It seems like the configuration does not have configured cuda correctly. Can you try to file an issue against tensorflow?

**Comment by AlexJoz** [comment]
Hm) ok i'll try! thnx)

**Comment by philwo** [comment]
Closing this, as I saw you opened an issue with Tensorflow :) Please feel free to reopen if it turns out to be a Bazel bug.
