### ISSUE TITLE
Expand Build Encyclopedia on docs.bazel.build to a Global Build Encyclopedia encompassing all open sourced Starlark rules

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#8681]
https://docs.bazel.build/versions/0.27.0/be/overview.html currenty lists native rules, embedded Starlark rules, and a list of popular rulesets.

I believe it'll be a lot more useful to see a global list of rules (not just links to rulesets) across the open source ecosystem in a "Global" BUILD encyclopedia. 

Some high level work include:

* Aggregrating / indexing a list of rulesets (e.g. from https://github.com/jin/awesome-bazel)
* Applying a static analyzer like Skydoc or a tool from https://github.com/bazelbuild/buildtools to parse rule names 
* Generating a structured, organized output of these rule names with links to their ruleset repositories
* Integration with the bazel.build website pipeline.

**Comment by jin** [comment]
Labeling this under Starlark instead of Product, since this is something that the Bazel Frontend team can own.

**Comment by jin** [comment]
cc @laurentlb

**Comment by laurentlb** [comment]
This is just about listing the rule names (not the full documentation)? What's the benefit?

I'd expect you either need the list of rule sets (to know if there are rules for a specific language), or the full documentation (to use it).

**Comment by jin** [comment]
> This is just about listing the rule names (not the full documentation)? What's the benefit?

Yes, just like the native rules. It's useful (especially for new Bazel users, or to a casual passerby) to see the entire ecosystem of rules at a glance, aggregated in a single location. In a way, it's about surfacing the encyclopedia with rules in the ecosystem in an automated fashion. 

e.g. Adding rules for Scala, Rust, Swift and JavaScript make it look like this:

<img width="707" alt="Screen Shot 2019-06-19 at 8 45 22 PM" src="https://user-images.githubusercontent.com/347918/59810479-64e51400-92d3-11e9-971f-52c144098969.png">

> I'd expect you either need the list of rule sets (to know if there are rules for a specific language), or the full documentation (to use it).

Yeah. This is more for discovery and aggregation.

**Comment by aiuto** [comment]
This is a product issue. I will certainly be doing a single doc set for bazel plus rules in the federation. We can expand that to other rules too, once the basics are in place

**Comment by laurentlb** [comment]
Why did you close the issue?

**Comment by jin** [comment]
This is still nice to have, because the the BE is a key landing page to many users internally and externally.  It'll be great to teach the Build Encyclopedia about Starlark rules and Stardoc.

**Comment by jin** [comment]
cc @floriographygoth

**Comment by aiuto** [comment]
I have no idea why I closed this, since I agree with the idea. I probably fumble-fingered.

**Comment by jin** [comment]
Aspect (the company) built this: https://docs.aspect.build 

@alexeagle
