### ISSUE TITLE
Error during the bazel build

### ISSUE THREAD

**Issue by annakhaimovich-babylon** [bazelbuild/bazel#8682]
Hi, I tried with bazel version 0.27.0 and 0.26.1
This is an error which I have. 
ERROR: /private/var/tmp/_bazel_anna/4a5a8dc24223cbce1398873ead9ee5e3/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:115:1: load() statements must be called before any other statement. First non-load() statement appears at /private/var/tmp/_bazel_anna/4a5a8dc24223cbce1398873ead9ee5e3/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:26:1. Use --incompatible_bzl_disallow_load_after_statement=false to temporarily disable this check.

ERROR: error loading package '': in /private/var/tmp/_bazel_anna/4a5a8dc24223cbce1398873ead9ee5e3/external/org_tensorflow/tensorflow/workspace.bzl: Extension 'third_party/gpus/cuda_configure.bzl' has errors

ERROR: error loading package '': in /private/var/tmp/_bazel_anna/4a5a8dc24223cbce1398873ead9ee5e3/external/org_tensorflow/tensorflow/workspace.bzl: Extension 'third_party/gpus/cuda_configure.bzl' has errors

**Comment by jin** [comment]
Have you tried passing the flag `--incompatible_bzl_disallow_load_after_statement=false`? 

Please open issues about TF builds on the [Tensorflow repository](https://github.com/tensorflow/tensorflow/issues). Thanks!
