### ISSUE TITLE
Updating a 0.23.0 compatible cc_toolchain_config.bzl for 0.27.0 (or supporting custom tool for link actions out-of-the box)

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/bazel#8687]
### Description of the problem / feature request:

I have a C/C++ toolchain configuration that works with Bazel 0.23.0 - 0.26.0 but fails with 0.27.0. I'm trying to create an equivalent toolchain config for 0.27.0.

This is the working 0.23.0 config: 
https://github.com/bazelbuild/bazel-toolchains/tree/master/configs/experimental/ubuntu16_04_clang/1.2/bazel_0.23.0/ubsan

This is my (work in progress) version for 0.27.0:
https://github.com/bazelbuild/bazel-toolchains/pull/591

### Feature requests: what underlying problem are you trying to solve with this feature?

The simplest solution to my issue would be to add a feature to overload the tool used for link actions. Not sure if were ready in the c/c++ toolchain migration to discuss if such a feature would be possible. 

Barring that, I would like to be able to override only some specific actions (link actions in my case) in a cc_toolchain_config.bzl file. My current attempt in https://github.com/bazelbuild/bazel-toolchains/pull/591 is to add the new actions to the action_configs object
(https://github.com/bazelbuild/bazel-toolchains/pull/591/files#diff-c0cc56bae33cd7a567664e93094bc3f5R86)
However, this is failing with error:
`ERROR: .../bazel-toolchains/configs/experimental/ubuntu16_04_clang/1.2/bazel_0.27.0/ubsan/BUILD:49:1: in cc_toolchain_suite rule //configs/experimental/ubuntu16_04_clang/1.2/bazel_0.27.0/ubsan:toolchain: Invalid toolchain configuration: multiple action configs for action 'c++-link-dynamic-library `
Which seems to make sense as the action is probably defined by default. Is there a way that I can just override the link actions w/o having to write all other actions myself in my cc_toolchain_config.bzl?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Pull https://github.com/bazelbuild/bazel-toolchains/pull/591

Run `bazel build //configs/experimental/ubuntu16_04_clang/1.2/bazel_0.27.0/ubsan/...` to repro the error

Run `gcloud builds submit --config tests/rbe_external_project/abseil_ubsan.yaml` to verify use of toolchain config on an RBE build

### What operating system are you running Bazel on?

The failing builds are being executed in the bazel container from a GCB build. But the error can just be repro'd on any OS by just doing` bazel build` of the target indicated above.

### What's the output of `bazel info release`?

I'm using bazel 0.27.0 in the failing test

### Any other information, logs, or outputs that you want to share?

fyi @hlopko

**Comment by scentini** [comment]
The key difference between the two toolchain configs you provided is the existence of the `no_legacy_features` feature in the first one:

Unless `no_legacy_features` feature is specified, Bazel [adds/moves around some features](https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html#legacy-features-patching-logic). Part of this toolchain config manipulation is defining all the `action_configs` - if you don't provide the `no_legacy_features` feature, Bazel defines the `action_configs` for you, and doesn't allow overwriting them.

b984716 makes Bazel define only `action_configs` that are not defined by the toolchain config rule, thus allowing you to overwrite them.

**Comment by nlopezgi** [comment]
Great, thanks @scentini !
do you know which release will include
[b984716](https://github.com/bazelbuild/bazel/commit/b9847161fa972c3afa76f0dcf7d5d81f9e52ccc6)?
Thanks again!

**Comment by scentini** [comment]
Our RCs are cut at the beginning of each month, so 0.28 will contain it.
Thank you!
