### ISSUE TITLE
Cleanup legacy code paths for old PY2 default

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8688]
Since #6647 has been closed as of 0.25, we should remove the flags `--incompatible_py3_is_default` and `--incompatible_py2_outputs_are_suffixed`.

Blocked on #7903, and the fact that these flags are still in use internally to Google.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
