### ISSUE TITLE
copts containing quotes and remote execution

### ISSUE THREAD

**Issue by s-jeckel-mxn** [bazelbuild/bazel#8694]
### Description of the problem:

I have a cc_library containing quotes in its copts to define a string. When executed locally, the string is passed on correctly. When executed remotely, the quotes are removed and the build fails.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

main.cpp
```
void foo(const char* x) {}

int main()
{
    foo(MY_DEFINE);
    return 0;
}
```
```
cc_library(
    name = "main",
    srcs = ["main.cpp"],
    copts = ['-DMY_DEFINE=\\"Test\\"'],
)
```
Locally, MY_DEFINE is substituted with "Test".
Remotely, MY_DEFINE is substituted with Test.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.27.0

**Comment by meisterT** [comment]
Is this still an issue?
