### ISSUE TITLE
The actions run and run_shell should provide a way to capture standard output/error

### ISSUE THREAD

**Issue by bmuschko** [bazelbuild/bazel#8695]
### Description of the problem / feature request:

The actions run and run_shell should provide a way to capture standard output/error. Right now there's no way to further process the output.

### Feature requests: what underlying problem are you trying to solve with this feature?

Sometimes you want to do something with the output. For example a tool might indicate its version by running `<tool-name> version`. As a result you might want to capture the value and write it to a file as part of a rules definition.

### What operating system are you running Bazel on?

MacOSX 10.14.5

### What's the output of `bazel info release`?

release 0.27.0

###  Have you found anything relevant by searching the web?

I asked on Slack in a wider context: https://bazelbuild.slack.com/archives/CDCMRLS23/p1561132832006900

**Comment by irengrig** [comment]
Thank you for the feedback.
Redirection of the stdout/stderr will help with run_shell().
However, it is indeed a missing feature for run().

**Comment by laurentlb** [comment]
Duplicate with #5511
