### ISSUE TITLE
ctx.actions.run#tools param doesn't include all expected runfiles

### ISSUE THREAD

**Issue by wchargin** [bazelbuild/bazel#8697]
### Description of the problem / feature request:

A `ctx.actions.run` action with declared `tools` runs without some of
the dependencies of those tools. Declaring the dependencies explicitly
(as additional `tools`) changes the behavior of the build.

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone the [tensorflow/tensorboard] repository and check out commit
51fb0795. Apply the following patch (pipe it to `git apply`):

```diff
diff --git a/tensorboard/defs/web.bzl b/tensorboard/defs/web.bzl
index ced08234..2500fff9 100644
--- a/tensorboard/defs/web.bzl
+++ b/tensorboard/defs/web.bzl
@@ -170,18 +170,12 @@ def _tf_web_library(ctx):
         [ts_config, er_config],
         transitive=[
             ts_inputs,
-            # TODO(@wchargin): Because `_tsc` is passed as `tools`
-            # below, collecting its runfiles should in principle be
-            # unnecessary, but without this line the two deps of `_tsc`
-            # (`tsc.js` and `@org_nodejs//:bin/node`) are in fact not
-            # included, and so execrooter fails at runtime.
-            collect_runfiles([ctx.attr._tsc]),
             ts_typings,
             ts_typings_execroots,
         ],
     )
     ctx.actions.run(
-        tools=ctx.files._tsc,
+        tools=ctx.files._tsc + ctx.files._tsc_deps,
         inputs=ts_inputs,
         outputs=ts_outputs,
         executable=ctx.executable._execrooter,
@@ -407,6 +401,14 @@ tf_web_library = rule(
             allow_files=True,
             executable=True,
             cfg="host"),
+        "_tsc_deps": attr.label_list(
+            default=[
+                Label("@com_microsoft_typescript//:tsc.js"),
+                Label("@org_nodejs//:bin/node"),
+            ],
+            allow_files=True,
+            cfg="host",
+        ),
         "_default_typings": attr.label(
             default=Label("//tensorboard:tf_web_library_default_typings"),
             allow_files=True),
```

Then run `bazel build //tensorboard`, which works. But then delete the
two newly added `Label` lines from `web.bzl` (so that no additional deps
are being passed), and re-run `bazel build //tensorboard`, which fails
with

```
bazel-out/host/bin/external/com_microsoft_typescript/tsc: line 6: /HOMEDIR/.bazel-output-base/sandbox/linux-sandbox/774/execroot/org_tensorflow_tensorboard/external/org_nodejs/bin/node: No such file or directory
```

(a failure in our tool, yes, but because the required runfiles are not
being provided). Verify that the dependencies are actually declared:

```
$ bazel query '@com_microsoft_typescript//:tsc' --output=build
# /HOMEDIR/.bazel-output-base/external/com_microsoft_typescript/BUILD:17:1
sh_binary(
  name = "tsc",
  data = ["@com_microsoft_typescript//:tsc.js", "@org_nodejs//:org_nodejs"],
  srcs = ["@com_microsoft_typescript//:tsc.sh"],
)
$ bazel query 'somepath(@com_microsoft_typescript//:tsc, @org_nodejs//:bin/node)'
@com_microsoft_typescript//:tsc
@org_nodejs//:org_nodejs
@org_nodejs//:bin/node
```

### What operating system are you running Bazel on?

gLinux (like Debian)

### What's the output of `bazel info release`?

release 0.27.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
$ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
git@github.com:tensorflow/tensorboard.git
master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
51fb0795c88521d91a3c722412c0b91fdab2a66a
```

(I don’t use a `master` branch; I work mostly in detached HEAD states.)

### Have you found anything relevant by searching the web?

@c-parsons comments that more digging is required:
<https://github.com/tensorflow/tensorboard/pull/2368#discussion_r296406580>

### Any other information, logs, or outputs that you want to share?

No.

**Comment by irengrig** [comment]
@c-parsons do you mind assigning it to you?

**Comment by c-parsons** [comment]
Perfect. We've already had some discussion on the issue in https://github.com/tensorflow/tensorboard/pull/2368#discussion_r296321399

**Comment by c-parsons** [comment]
Rephrasing this bug (with repro case):
It seems that specifying a `files_to_run` object as the `tools` parameter to an action sometimes does not include all of the files one should expect.

See https://github.com/tensorflow/tensorboard/pull/2368#discussion_r296321399 for a repro.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
