### ISSUE TITLE
bazel0.26.0: genrule outputs files in both gendir and bindir irrespective of the value of output_to_bindir

### ISSUE THREAD

**Issue by abhishek-carbon3d** [bazelbuild/bazel#8698]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

genrule outputs files in both gendir and bindir irrespective of the value of output_to_bindir

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

genrule(
   name = "test",
   srcs = [
   ],
   output_to_bindir = False,
   outs = ["test.txt"],
   cmd = "echo hello > $@",
)

test.txt is in both bindir and gendir

### What operating system are you running Bazel on?

ubuntu18

### What's the output of `bazel info release`?

release 0.26.0

BTW it works as expected in release 0.22.0 so not sure when it was broken

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

No

**Comment by benjaminp** [comment]
#6761

**Comment by laurentlb** [comment]
This is working as intended: we're removing the distinction between `bazel-bin` and `bazel-genfiles`. Is it breaking your code in any way? Can you avoid using `output_to_bindir`?

We plan to remove the `genfiles` directory: https://github.com/bazelbuild/bazel/issues/8651

**Comment by abhishek-carbon3d** [comment]
It was breaking some home grown rules for nodejs/ts (hoping to switch over to the rapidly evolving official nodejs toolchain soon :).

We have fixed our rules, but I thought I would report this in case it was not intentional. Closing.
