### ISSUE TITLE
j2objc aspect labels aren't working with @bazel_tools prefix

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#870]

**Comment by damienmg** [comment]
We decided this might not get resolved as the corresponding code is getting deprecated. At least it is no longer a blocker for 0.2, we are good to go.

For the record, use the package_path and put the bazel repositories in it is the current workaround.

**Comment by kchodorow** [comment]
In particular, objc rules may require `//third_party/java/j2objc:proto_runtime` and `//third_party/java/j2objc:jre_emul_lib` to be on the package path (both are defined in [third_party/java/j2objc/BUILD](https://github.com/bazelbuild/bazel/blob/master/third_party/java/j2objc/BUILD)).

**Comment by c-parsons** [comment]
Kristina, is this still an issue? I know you've been doing some work on @bazel_tools... (and hey, you're the original reporter) :)
Feel free to reassign back to me if you need me to investigate

**Comment by kchodorow** [comment]
Looks to me like they are now referred to via external repository, so it should work?
