### ISSUE TITLE
Windows: bug with glob + exclude

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8705]
### Description of the problem / feature request:

`glob.exclude` is buggy on Windows when the glob matching pattern uses path casing (e.g. "foo") different from the exclusion pattern (e.g. "Foo").

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/laszlocsomor/projects/tree/7e9b9c565248d77c5baca9ed80a9cf3dc8bcf146/bazel/glob-exclude

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.26.1

**Comment by laszlocsomor** [comment]
Probably the same bug with a different effect: https://github.com/bazelbuild/bazel/issues/8759

**Comment by laszlocsomor** [comment]
@baskus: I'm having second thoughts -- maybe it's not a great idea to make glob() case-insensitive.
WDYT about requiring case-correctness on Windows (like on Linux) and ensuring "foo/**" won't match "Foo/Bar/baz.txt" to begin with? (which is the current case, and arguably a bug).

**Comment by laszlocsomor** [comment]
I was going about the culprit the wrong way.

It's not the problem that `glob()` is case-sensitive, the problem is that `glob(["foo/**"])` matches `Foo/` but yields "foo/". See https://github.com/bazelbuild/bazel/issues/8759#issuecomment-508509742

Fixing https://github.com/bazelbuild/bazel/issues/8759  would automatically fix this one too: both the include and exclude patterns would have to be case-correct.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
