### ISSUE TITLE
incompatible_disable_nocopts: Disallow 'nocopts' attribute from cc_* rules

### ISSUE THREAD

**Issue by scentini** [bazelbuild/bazel#8706]
**Flag:** `--incompatible_disable_nocopts`
**Available since:** 0.28
**Will be flipped:** 1.0

The `nocopts` attribute in cc_* rules is used to specify a pattern for filtering out flags from C++ compilation command line.
We are deprecating it because:

- it prevents migration of C++ rules to Starlark: we don’t have regex in Starlark currently
- we don’t need to do it - we can disable features to have the same effect

### Migration

**If you use the `nocopts` attributes to filter out a flag please comment on this issue, with the offending flag/pattern that you're filtering out.**

As we have no way of knowing which flags users filter out, we will rely on them reaching out to us  in case the flipping of the `--incompatible_disable_nocopts` flag breaks their project. We will keep on support for filtering out the flags through `--noincompatible_disable_nocopts` for 1-2 extra Bazel releases, until we are able to provide the support for disabling the reported flags through features.

If a user is filtering out a flag provided by bazel's own [C++ toolchain configuration](https://source.bazel.build/bazel/+/master:tools/cpp/cc_toolchain_config.bzl), we will wrap the flag into a feature, so the user can disable the feature instead of filter out the flag.
E.g a
```
cc_library(
    name = "lib",
    srcs = ["lib.cc", "lib.h"],
    nocopts = "flagA",
)
```
would be migrated to
```
cc_library(
    name = "lib",
    srcs = ["lib.cc", "lib.h"],
    features = ["-flag_a_feature"],
)
```
with `flag_a_feature` being defined in bazel's own [C++ toolchain configuration](https://source.bazel.build/bazel/+/master:tools/cpp/cc_toolchain_config.bzl).

**Comment by dslomov** [comment]
What is the flag flip risk in 1.0? 
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/195 shows that it "only" breaks TensorFlow

**Comment by AustinSchuh** [comment]
I grepped through our code base and we have 1 call site.  One library really doesn't work well when built with coverage support (which is enabled by the toolchain/crosstool).  We remove the ```--coverage``` flag with nocopts.

**Comment by scentini** [comment]
Thanks for reaching out!
Our C++ toolchain configuration rule provides the `--coverage` flag through a `coverage` feature.
Can you try replacing `nocopts = '--coverage'` with `features = ["-coverage"]` (note the _minus_ , denoting "_disable this feature_")?

**Comment by AustinSchuh** [comment]
That looks like it worked.  That's a much better solution than nocopts.  Thanks!

**Comment by scentini** [comment]
This flag was flipped in 8b840e1.

**Comment by cocasema** [comment]
There's one more use-case for nocopts - when we build third-party code and have to disable some warnings (-Wno-). If we have both .c and .cpp files in a single cc_library and need to turn off some c-only warnings (like -Wno-declaration-after-statement), we also have to add then to nocopts to make g++ happy.

**Comment by scentini** [comment]
Do you use your own toolchain configuration? If so, you'll need to create a feature that will pass the -Wno-declaration-after-statement to the command line, and use
`features = ["-declaration_after_statement"]` in the targets that you'd like to **not** apply the flag to.

**Comment by wanguanglu** [comment]
if I want to filter "-Werror" with nocopts="-Werror"
but features = ["-error"] seems not work.

**Comment by asraa** [comment]
Hi, I have a use-case for nocopts, and wanted to know what the appropriate migration is. I have a third-party library that I'm building through an `http_archive`, and wanted to build it without the preprocessor macro `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` defined, even when the CLI defines it. Some users pass in `--copt=-DFUZZING_BUILD_...` and a build configuraiton we define also uses this copt.

Originally I was going to use nocopts and patch the BUILD file for the dependency, but instead it seems I should be using a feature. Does this mean I need to create a feature for FUZZING_BUILD_MODE... and pass it in to every target *but* the RE2 library during a specific build config?

**Comment by mst9009** [comment]
If I want to filter out the “-g” option, how should I set the “features” attribute？Thanks！

**Comment by wrowe** [comment]
> If I want to filter out the “-g” option, how should I set the “features” attribute？Thanks！

@mst9009 sorry this is quite late, but adding copts "-g0" should accomplish what you were looking for?

**Comment by changlan** [comment]
Hi. How should I filter out the `-fstack-protector` flag with the “features” attribute? Tried `default_compile_flags` but it removed all compile flags.

**Comment by mason-bially** [comment]
This may be a whole separate issue, but one of the use cases for `nocopts` that I was using was removing `/I.` from some windows builds where it was being applied incorrectly (it's inclusion causes MSVC to behave differently than gcc/clang given the same file structure). So a feature flag setting of `-include_path_local` (minus to remove) would be nice (unless there is a syntax for removing a specific instance of the `include_paths` flag group? Currently my workaround is this: 

```
cc_library(
    ...
    features = select({
        "@bazel_tools//src/conditions:windows": ["-include_paths"],
        "//conditions:default": [],
    }),
    copts = select({
        "@bazel_tools//src/conditions:windows": ["/Imanual", "/Iinclude", "/Ilist"],
        "//conditions:default": [],
    }),
)
```

Which is brittle, ugly, and not great.

**Comment by wondfor** [comment]
maybe you should fix the [us](https://docs.bazel.build/versions/main/be/c-cpp.html#cc_binary.nocopts)

**Comment by JohnGHS** [comment]
I have to admit that I'm only starting with Bazel, so please take the following with a grain of salt.
I'm trying to integrate a non-gcc C++ compiler into Bazel, and it is complaining about a lot of gcc-specific options that are being injected into the build. I can easily believe that this is because I'm following a tutorial that assumes a gcc builder, hence a single `load()` could be adding unnecessary flags. However, the most egregious of these (as I see it) are:

- "Unknown option '-frandom-seed=...'"
- "Unknown option '-iquote' passed to linker"
- "Unrecognized option: -S"

I know what each of these options do with gcc (although I'm surprised to see '-iquote' passed to the linker), but want to turn them off.

**Comment by scentini** [comment]
cc @oquenchil

**Comment by dmadisetti** [comment]
3 years later and docs have no been updated. Also dead references in comments and code: https://github.com/bazelbuild/bazel/search?p=1&q=nocopts&type=code

Is the logic with `UNFILTERED_COMPILE_FLAGS_FEATURE_NAME` still relevant? https://github.com/bazelbuild/bazel/blob/a48e246e53c19cfa5d68c21ffefee0470acf7230/src/main/java/com/google/devtools/build/lib/rules/cpp/CompileCommandLine.java#L144

The provided toolchain link is also dead, has it been moved to https://cs.opensource.google/bazel/bazel/+/master:tools/cpp/cc_toolchain_config_lib.bzl ?

Which is then consumed by the various tool chain definitions? e.g. https://cs.opensource.google/bazel/bazel/+/master:tools/cpp/unix_cc_toolchain_config.bzl

I think these features need to be a bit better documented, are they consistent between toolchains? I think I found something for my usecase, but not with the granularity I would like (just looking to turn off `cxx_flags`).

**Comment by keith** [comment]
FWIW this attribute is still in the docs which might confuse some folks

**Comment by hvadehra** [comment]
cc @pzembrod
