### ISSUE TITLE
Coverage tests fail on CentOS 7

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#8708]
I have managed to get Bazel to build and pass its own test suite completely on CentOS 7, except for three coverage tests. From the logs, I don't know how to fix them or what's actually wrong - maybe it's just a missing dependency that I can install in the Docker container, but I don't know.

@iirina Could you have a look and let me know your thoughts?

//src/test/shell/bazel:bazel_cc_code_coverage_test: https://storage.googleapis.com/bazel-testing-buildkite-artifacts/a3844e46-4074-4a57-8728-7eef9418afb1/src/test/shell/bazel/bazel_cc_code_coverage_test/attempt_1.log

//src/test/shell/bazel:bazel_coverage_cc_test_gcc: https://storage.googleapis.com/bazel-testing-buildkite-artifacts/a3844e46-4074-4a57-8728-7eef9418afb1/src/test/shell/bazel/bazel_coverage_cc_test_gcc/attempt_1.log

//src/test/shell/bazel:bazel_coverage_sh_test: https://storage.googleapis.com/bazel-testing-buildkite-artifacts/a3844e46-4074-4a57-8728-7eef9418afb1/src/test/shell/bazel/bazel_coverage_sh_test/attempt_1.log

From this CI build: https://buildkite.com/bazel-testing/bazel-bazel/builds/394#a3844e46-4074-4a57-8728-7eef9418afb1

The Docker container is: gcr.io/bazel-public/centos7:java8.

**Comment by iirina** [comment]
Somewhere in the log very well hidden: ` gcov_location: unbound variable`, which makes me think that gcov is not installed.

**Comment by philwo** [comment]
Mhm... I installed the `lcov` package, which provides a `/usr/bin/gcov` file:

```
[root@9c94264446ac /]# gcov --version
gcov (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or 
FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by iirina** [comment]
Ok then, let me take another look.

**Comment by iirina** [comment]
I'm looking at [gcov documentation for Centos 7](https://www.unix.com/man-page/centos/1/gcov/) and the `-i` option (which bazel uses) is not present.

Let's test what gcov actually does on centos. Can you tell me what's the output of the following commands?

```
$ cat >tmp.c <<EOF
#include <stdio.h>
int main (void) {
  int i, total;
  total = 0;
  for (i = 0; i < 10; i++)
    total += i;
   if (total != 45)
     printf ("Failure\n");
  else
     printf ("Success\n");
  return 0;
}
EOF

$ gcc -fprofile-arcs -ftest-coverage tmp.c
$ ./a.out
$ gcov -i tmp.gcda
$ cat tmp.c.gcov
```

**Comment by philwo** [comment]
Sure, here's the output:

```
[root@3120ebdf085d ~]# cat >tmp.c <<EOF
> #include <stdio.h>
> int main (void) {
>   int i, total;
>   total = 0;
>   for (i = 0; i < 10; i++)
>     total += i;
>    if (total != 45)
>      printf ("Failure\n");
>   else
>      printf ("Success\n");
>   return 0;
> }
> EOF

[root@3120ebdf085d ~]# gcc -fprofile-arcs -ftest-coverage tmp.c

[root@3120ebdf085d ~]# ./a.out 
Success

[root@3120ebdf085d ~]# gcov -i tmp.gcda
gcov: invalid option -- 'i'
Usage: gcov [OPTION]... SOURCE|OBJ...

Print code coverage information.

  -h, --help                      Print this help, then exit
  -v, --version                   Print version number, then exit
  -a, --all-blocks                Show information for every basic block
  -b, --branch-probabilities      Include branch probabilities in output
  -c, --branch-counts             Given counts of branches taken
                                    rather than percentages
  -n, --no-output                 Do not create an output file
  -l, --long-file-names           Use long output file names for included
                                    source files
  -f, --function-summaries        Output summaries for each function
  -o, --object-directory DIR|FILE Search for object files in DIR or called FILE
  -s, --source-prefix DIR         Source prefix to elide
  -r, --relative-only             Only show data for relative sources
  -p, --preserve-paths            Preserve all pathname components
  -u, --unconditional-branches    Show unconditional branch counts too
  -d, --display-progress          Display progress information

For bug reporting instructions, please see:
<http://bugzilla.redhat.com/bugzilla>.

[root@3120ebdf085d ~]# cat tmp.c.gcov
cat: tmp.c.gcov: No such file or directory
```

**Comment by philwo** [comment]
Here's the list of files in the current directory after the commands above ran:

```
[root@3120ebdf085d ~]# ls -l
total 40
-rwxr-xr-x 1 root root 23768 Jun 25 07:59 a.out
-rw-r--r-- 1 root root   204 Jun 25 07:59 tmp.c
-rw-r--r-- 1 root root   220 Jun 25 07:59 tmp.gcda
-rw-r--r-- 1 root root   572 Jun 25 07:59 tmp.gcno
```

**Comment by philwo** [comment]
Here's the output of just running `gcov` without `-i`:

```
[root@3120ebdf085d ~]# gcov tmp.gcda 
File 'tmp.c'
Lines executed:87.50% of 8
Creating 'tmp.c.gcov'

[root@3120ebdf085d ~]# cat tmp.c.gcov 
        -:    0:Source:tmp.c
        -:    0:Graph:tmp.gcno
        -:    0:Data:tmp.gcda
        -:    0:Runs:1
        -:    0:Programs:1
        -:    1:#include <stdio.h>
        1:    2:int main (void) {
        -:    3:  int i, total;
        1:    4:  total = 0;
       11:    5:  for (i = 0; i < 10; i++)
       10:    6:    total += i;
        1:    7:   if (total != 45)
    #####:    8:     printf ("Failure\n");
        -:    9:  else
        1:   10:     printf ("Success\n");
        1:   11:  return 0;
        -:   12:}
```

**Comment by iirina** [comment]
Thanks @philwo! This concludes that Bazel C++ coverage doesn't work on CentOS 7, so I suggest disabling the 3 failing tests.

**Comment by iirina** [comment]
Some more explanations: the `-i` option outputs a format that bazel can understand, parse and convert to bazel's standard coverage output. The standard gcov format is not supported by bazel.

**Comment by philwo** [comment]
Oh, OK! Thanks for checking this out. Alright, I've disabled the three tests. :)

**Comment by guobiaoxiong** [comment]
what's the recommend gcov version？
