### ISSUE TITLE
Add a macro to define PY2-or-PY3 target

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8713]
Create a macro for defining a binary/test that uses either PY2 or PY3, whichever is available on the target platform.

Background: Currently, `py_binary` and `py_test` have a `python_version` attribute that is completely authoritative (asterisk: except when overridden by `--host_force_python`) for whether the target gets analyzed as `PY2` or `PY3`. This choice is then enforced by the Python toolchain, e.g. the default autodetecting toolchain.

This creates a problem when you want to define a target that has code compatible with both 2 and 3, and doesn't care which one it uses. You end up having to pick one or the other, and if the version you picked doesn't have a corresponding interpreter on the user's target machine, there's a build or runtime error. What we'd prefer is a way of saying "I don't care", so that either version will work so long as the target platform has at least one of Python 2 or 3.

This could be implemented by defining a macro that creates both a PY2 and PY3 target, and a wrapper target that dispatches to one or the other based on a `select()` that could read the target platform's constraints. We could add special values for the `py2_interpreter_path` / `py3_interpreter_path` constraint settings to indicate that no system Python interpreter of that version is available.

See possible use cases in https://github.com/bazelbuild/rules_apple/issues/456#issuecomment-497814961 and https://github.com/tensorflow/tensorflow/issues/29220#issuecomment-505376754.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
