### ISSUE TITLE
Windows: rename embedded JDK's java.exe

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8719]
Branched from https://github.com/bazelbuild/bazel/issues/5254#issuecomment-500103972.

Let's rename the embedded JDK's "java.exe" to something Bazel-specific, e.g. "bazel-server.exe".

Rationale:
- easier to find and terminate in Task Manager
- the embedded JDK should only be used for Bazel itself (https://github.com/bazelbuild/bazel/issues/5254#issuecomment-505008097)

Version: Bazel 0.27.0 on Windows 10

**Comment by laszlocsomor** [comment]
@meisterT : not sure if you're the right assignee, please reassign if adequate

**Comment by laszlocsomor** [comment]
Caveat: the bazel client must be aware that java.exe may be called bazel-server.exe, and it must handle both.

**Comment by meisterT** [comment]
Since that change is an incompatible change and cannot be guarded behind a flag, I'll have to wait for the next incompatible release before I can do the change.

**Comment by philwo** [comment]
@meisterT With that approach, people will not have a migration window over some releases where they can get used to the new binary name. I'm not sure if we can ever make this change.

**Comment by philwo** [comment]
Alternatively we could ship both a java.exe and a bazel-server.exe in the binary and then use an incompatible startup flag to decide which one to execute. OK, our binary size will be double for a while, but oh the sweet backwards compatibility, I'm sure everyone will love it. 😀

**Comment by meisterT** [comment]
Having that doubled doesn't sound too bad - since at least on Linux the java binary only has 10k.

**Comment by laszlocsomor** [comment]
Why would the binary size double? We'd only copy java.exe not the other JDK files.

**Comment by laszlocsomor** [comment]
Which part of this change is incompatible?

**Comment by philwo** [comment]
@laszlocsomor True, we can just duplicate the java.exe! For a moment I thought we’d have to include two entire JDKs. 😅

**Comment by laszlocsomor** [comment]
Actually, why copy and not just rename? Nothing but that particular Bazel version should use the embedded JDK. There's nothing to be backwards compatible with.

**Comment by philwo** [comment]
Rename wouldn’t work because multiple servers can run from the same install base with different values for that incompatible flag.

**Comment by laszlocsomor** [comment]
But all of those servers are the same Bazel version. So there's no need for an incompatible flag, no?

Which part of the change is incompatible?

**Comment by meisterT** [comment]
Laszlo: the name is exposed (otherwise we would not change it). Assume someone wrote a script that (outside of bazel) uses the process name, e.g. monitors the CPU usage over time.

**Comment by meisterT** [comment]
I am not actively working on this, but would review a PR.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
