### ISSUE TITLE
Windows, C++: support selecting the Windows SDK

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8721]
### Feature requests: what underlying problem are you trying to solve with this feature?

If multiple Windows SDK versions are installed, the user may want to select which one to use. Currently there's no way to do so.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.27.0

###  Have you found anything relevant by searching the web?

Related: https://github.com/bazelbuild/bazel/issues/8353

**Comment by laszlocsomor** [comment]
cc @meteorcloudy @hlopko

**Comment by hlopko** [comment]
I don't think I'll have the capacity to design/implement this, but I'll gladly review the proposal.

**Comment by meteorcloudy** [comment]
This won't be hard to implement it, I will do it!
