### ISSUE TITLE
starlark range inconsistencies with spec

### ISSUE THREAD

**Issue by Quarz0** [bazelbuild/bazel#8722]
- The Starlark [spec](https://github.com/bazelbuild/starlark/blob/master/spec.md#range) mentions that `Range values are not hashable.`. However, they could be added as keys to dictionaries, for example, ```x = {range(10): 1}``` is allowed.

- In the spec it is mentioned that `The x in y operator, where y is a range, reports whether x is equal to some member of the sequence y; the operation fails unless x is a number.`. However, the implementation allows for x to be of almost any type, for example:

```
True in range(20)              # False
"abc" in range(30)             # False
range(10) in range(10)         # False
dict() in range(10)            # False
```

**Comment by laurentlb** [comment]
@alandonovan
Why would range values not be hashable?
Why should `in` fail in this case? Returning False looks good to me.

**Comment by brandjon** [comment]
For the first issue, this appears to be fixed: range is not valid in a dictionary.

```
> print({range(10):1})
Error: unhashable type: 'range'
```

I filed bazelbuild/starlark#175 for the second issue.

As for whether range *should* be hashable, I don't feel strongly either way, but it seems like a strange operation to want to do. (A separate FR could be opened in the starlark repo if someone wants it.)
