### ISSUE TITLE
starlark partition/rpartition accept 0 parameters

### ISSUE THREAD

**Issue by Quarz0** [bazelbuild/bazel#8725]
The [spec](https://github.com/bazelbuild/starlark/blob/master/spec.md#stringpartition) does not mention that the parameter `x` or `sep` for partition is optional yet partition and rpartition are allowed to be called with 0 parameters with `sep` getting the default value `' '`.

**Comment by laurentlb** [comment]
In Python3, the argument is mandatory too.
Looks like a bug in our implementation.
