### ISSUE TITLE
starlark string.splitlines line terminators

### ISSUE THREAD

**Issue by Quarz0** [bazelbuild/bazel#8727]
The Starlark [spec](https://github.com/bazelbuild/starlark/blob/master/spec.md#stringsplitlines) says that the splitlines function `splitting S at line terminators (currently assumed to be a single newline, \n, regardless of platform).`
The current implementation assumes line terminators are `'\n'`, `'\r'` and `'\r\n'`.

For example `'\r\r'.splitlines()` should return `["\r\r"]` according to the spec, but the actual result is `["", ""]`.

**Comment by laurentlb** [comment]
cc @alandonovan

Python3 returns `["", ""]`. We may update the spec instead.

**Comment by laurentlb** [comment]
Please file an issue on https://github.com/bazelbuild/starlark
