### ISSUE TITLE
Coverage Header & INL Files

### ISSUE THREAD

**Issue by mvonarx** [bazelbuild/bazel#8731]
### Description of the problem / feature request:

For a C++ project including various layers of `*.hh` and `*.inl` files, running `bazel coverage ...` produces different results when compared with manually running the executable and assembling the generated `*.gcda` files with the `*.gcno` files from compile time stored in `bazel-bin`.

### Feature requests: what underlying problem are you trying to solve with this feature?

The coverage report differences cause missing executed linecounts in many `*.hh` and `*.inl` files.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a project with a few layers of abstraction through included `*.hh` and `*.inl` files, especially with some template definitions, and run coverage analysis.

### What operating system are you running Bazel on?

Ubuntu 16.04.1

### What's the output of `bazel info release`?

```
Starting local Bazel server and connecting to it...
(14:45:35) INFO: Invocation ID: 54397831-32ca-4221-aba2-392edad88abf
release 0.23.2
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Private repository.

###  Have you found anything relevant by searching the web?

Posted in `bazel-dev` group [here.](https://groups.google.com/forum/#!topic/bazel-dev/ooJL9wF6uY8)

**Comment by iirina** [comment]
@mvonarx thanks for filing the bug report! Can you provide more details on what is the difference in coverage reports?

Please also take a look at the [--instrumentation_filter](https://docs.bazel.build/versions/master/command-line-reference.html) flag. 

Also if you add 

```
--combined_report=lcov --coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main
``` 

to your command line you'll get a combined coverage report under 
`bazel-out/_coverage/_coverage_report.dat`.

**Comment by vectoralpha** [comment]
I created a fork off of the examples repository to illustrate this issue.

https://github.com/vectoralpha/examples/commit/9f8f4943df4f0024174a2c6fb7c64f3c56723122

**Comment by iirina** [comment]
Thanks for the repo @vectoralpha. I'll try to take a closer look into this issue soon.
