### ISSUE TITLE
Using bazel remote cache from GKE with workload identity is broken

### ISSUE THREAD

**Issue by dvulpe** [bazelbuild/bazel#8733]
Running bazel with remote cache configured on GKE using Workload Identity metadata server is broken. This is due to the validation and a bug in an upstream library  https://github.com/googleapis/google-auth-library-java/issues/282

The gke metadata server logs read:
```
surfaceable error handling request, surfacing as (code 403, message "Missing required header \"Metadata-Flavor\": \"Google\""), path="/" : surfaceable error (status 403, message "Missing required header \"Metadata-Flavor\": \"Google\""): dropping request because header "Metadata-Flavor" has bad value "", path="/"
```

which is due to a problem upstream: https://github.com/googleapis/google-auth-library-java/issues/282 which appears to be fixed in version v0.16.2.

Would it be possible to use the last released version of google-auth-library-java (v0.16.2), please?

### What operating system are you running Bazel on?

Linux/Mac
Bazel 0.27.0

**Comment by dvulpe** [comment]
I would have raised a PR to fix this but I noticed the actual binaries are in checked in 😬

**Comment by coeuvre** [comment]
Is this still an issue?

**Comment by dvulpe** [comment]
I haven’t used GKE in a while, but I will check this later today and come back with an answer.

**Comment by dvulpe** [comment]
Just checked against `gcr.io/cloud-marketplace-containers/google/bazel:3.5.0` and I was able to use the Cloud Storage remote cache from a pod running in GKE with workload identity enabled.

I've used the following command to test:
```
bazel test --remote_cache=https://storage.googleapis.com/BUCKET_NAME --google_default_credentials //...
```
Bazel wrote to the Cloud Storage bucket and a clean build has fetched from the remote cache.

Thanks for fixing this!

**Comment by coeuvre** [comment]
Thanks for verifying! Closing.
