### ISSUE TITLE
Expose CoverageOutputGenerator's label in a configuration

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#8736]
In the native rules we have the late-bound attribute `:lcov_merger` which looks at the build configuration to see if coverage is enabled and returns the label of `CoverageOutputGenerator` or null (see [BaseRuleClasses#115](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java;l=115?q=BaseRuleClasses&ss=bazel)).

We need the Starlark rules to be able to define `_lcov_merger` as a late bound attribute in the same way. For this to happen, the `CoverageOutputGenerator`s label has to be exposed on a class that extends BuildConfiguration.Fragment.

This is helpful for example for `rules_go` (see #8670), in order for `go_test` to be compatible with bazel's native test rules (e.g. `java_test`, `cc_test`).

**Comment by fmeum** [comment]
@c-mita I think that I generally know how to resolve this issue, but would need to know which `Fragment` I should add expose the label on. Could you provide guidance here as per https://github.com/bazelbuild/bazel/pull/13983#issuecomment-981646173 or point me to someone who could?
