### ISSUE TITLE
Unable to reference @bazel_tools//src/main/protobuf targets

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#8738]
### Description of the problem / feature request:

I am unable to use Bazel's protobuf targets and sources---specifically extra_action_base_java_proto---directly from `@bazel_tools//src/main/protobuf` because of an unsatisfied dependency on `@bazel_tools//tools/build_rules:genproto.bzl`.

As a workaround, in order to use extra actions, my project's WORKSPACE needs to refer to and clone Bazel's source via git_repository. Cloning the full repository is slow, and needing to rev the SHA1 each time we upgrade Bazel is a pain.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```console
$ cat BUILD
java_binary(
    name = "dummy",
    srcs = ["src/main/java/Dummy.java"],
    main_class = "Dummy",
    deps = [
        "@bazel_tools//src/main/protobuf:extra_actions_base_proto",
    ],
)
$ bazel build :dummy
...
ERROR: .../dummy/BUILD:1:1: error loading package '@bazel_tools//src/main/protobuf': Unable to load file '@bazel_tools//tools/build_rules:genproto.bzl': file doesn't exist and referenced by '//dummy:dummy'
ERROR: Analysis of target '//dummy:dummy' failed; build aborted: error loading package '@bazel_tools//src/main/protobuf': Unable to load file '@bazel_tools//tools/build_rules:genproto.bzl': file doesn't exist
```

### What operating system are you running Bazel on?

- Linux (CentOS 6.x, 7.x)
- macOS High Sierra and Mojave (10.13 and 10.14)

### What's the output of `bazel info release`?

release 0.26.0+vmware

###  Have you found anything relevant by searching the web?

- #1188

**Comment by iirina** [comment]
Bazel needs to embed a custom `@bazel_tools//src/main/protobuf/BUILD` file instead of the one it uses itself, to avoid loading unnecessary depenencies that don't exist under `@bazel_tools` (e.g. `//tools/build_rules:utilities.bzl`, `//tools/build_rules:genproto.bzl`).

**Comment by thekyz** [comment]
any eta on when this could be solved?

**Comment by beasleyr-vmw** [comment]
I'm going to take a crack at this this week.

Would appreciate some suggestions for and from potential reviewers to nail down a few details:
- Should the embedded tools export the .proto files under `@bazel_tools//src/main/protobuf` or `@bazel_tools//tools/protobuf`?
    - I'm leaning toward `//tools/protobuf`, because TTBOMK all public `@bazel_tools` packages are rooted under `//tools`. This would also support aggregating `.proto` files not originally found in `//src/main/protobuf`, like `src/main/java/com/google/devtools/build/lib/bazel/debug/workspace_log.proto` and `src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto`.
- Is it fair to go ahead and export _all_ .proto files found in `//src/main/protobuf`, or should the exported set be filtered/whitelisted? (I assume filtered based on https://github.com/bazelbuild/bazel/blob/d695d10c65564ace10cf30058cdff2222028cd5d/src/main/protobuf/BUILD#L100-L104.)
    - Should this package bother exporting `proto_library`, `java_proto_library`, etc. rules as well, or just the .proto files, to begin?

**Comment by bartle-stripe** [comment]
@beasleyr-vmw any progress on this?

**Comment by beasleyr-vmw** [comment]
@bartle-stripe Thanks for the reminder. I put out a patch as a PR that we've used since February. It might give you something to work with if you build Bazel from source.

**Comment by fweikert** [comment]
I'm closing this issue since 0.26.0 is beyond its supported lifecycle. Please use a more recent version of Bazel, which should not suffer from this problem.
