### ISSUE TITLE
Force loading the Java rules from the rules_java repo

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#8741]
This big breaking change will force users of the Java rules to use the Starlark rules from the [rules_java repository](https://github.com/bazelbuild/rules_java). The rules there are currently only wrappers around native rules, but they will soon be rewritten.

To save our users from this big migration after Bazel 1.0, we will implement an incompatible flag and provide migration instructions before 1.0, and we will flip this flag for 1.0.

**Comment by davido** [comment]
Not sure If I should report issues here or rather in #8741.

I'm trying to migrate Gerrit (stable-2.14 branch) to this change, using buildifier 0.28.0 with `--lint=fix` option: [1].

After performing the change in BUILD and in *.bzl files, build is failing on Bazel 0.28.1:

```
 bazel build gerrit-server:server
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 10de3546-ba55-4f89-8ce1-461c1caea26e
ERROR: Failed to load Starlark extension '@rules_java//java:defs.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @rules_java
This could either mean you have to add the '@rules_java' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
ERROR: cycles detected during target parsing
INFO: Elapsed time: 7.208s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

[1] https://gerrit-review.googlesource.com/c/gerrit/+/232534

**Comment by ittaiz** [comment]
I know there were some thoughts on offering automatic migrations for certain flags any chance this flag has this? Alternatively is there a buildozer magic to add a load whenever there’s a usage?
Cc @laurentlb since I think I heard this thought from you

**Comment by iirina** [comment]
You can use buildifier right now to add load statements

```
buildifier --lint=fix -warnings=native-java -r path/to/your/workspace/root/dir
```

or do you mean something that runs automatically when the flag is set?

**Comment by ittaiz** [comment]
Awesome! This is exactly what I meant 😁 thanks!
Any chance you know where I can find a list of the supported fixes?

**Comment by iirina** [comment]
Cool :smile:  There's [a list of all supported warnings](https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md).

**Comment by lberki** [comment]
Update: We decided not to require everyone to add a load() statement to every single BUILD file because it's too much churn. The current plan is to "pretend" that the eventual C++/Java rules written in Starlark are load()ed everywhere.

We might revisit this decision once they are reasonably stable and once we decide where exactly they need to be load()ed from, but now is not the time.
