### ISSUE TITLE
incompatible_load_java_rules_from_bzl: load the Java rules from @rules_java

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#8746]
Flag: --incompatible_load_java_rules_from_bzl
Available since: 0.28 
Will be flipped in: 1.0 
Tracking issue: #8741

java_library, java_binary, java_test,  java_import, java_lite_proto_library, java_proto_library, 
java_package_configuration, java_plugin, java_runtime, java_toolchain have to be loaded from @rules_java.

For example if you are using java_library, add the following load statement to your BUILD/bzl file.
load("@rules_java//java:defs.bzl", "java_library")

## Migration

Add `rules_java` repositories to your WORKSPACE file and load its dependecies:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_java",
    url = "https://github.com/bazelbuild/rules_java/releases/download/0.1.1/rules_java-0.1.1.tar.gz",
    sha256 = "220b87d8cfabd22d1c6d8e3cdb4249abd4c93dcc152e0667db061fb1b957ee68",
)
load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")
rules_java_dependencies()
rules_java_toolchains()
```

Fix all your BUILD files that use Java rules to include the load statement. Use buildifier to automatically update all your BUILD files:

```
buildifier --lint=fix -warnings=native-java -r path/to/your/workspace/root/dir
```

**Comment by iirina** [comment]
Currently the builds will fail with `--incompatible_load_java_rules_from_bzl` because the java_tools are released separately and do not use the macro definitions yet. This will be fixed by updating BUILD.java_tools and releasing new java_tools versions.

**Comment by iirina** [comment]
Repositories referenced by bazel that use the native java rules and have to be migrated & upgraded before migrating bazel itself:

- [ ] skydoc
- [ ] java_tools_langtools_javac{9, 10, 11, 12}
- [ ] bazel_j2objc
- [ ] desugar_jdk_libs
- [ ] bazel_toolchains
- [ ] bazel_rbe_toolchains

**Comment by Yannic** [comment]
@iirina Can we update the description to include the load statement so users will know to include them?

```python
load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")
rules_java_dependencies()
rules_java_toolchains()
```

**Comment by dslomov** [comment]
Will migration tooling be available to do the migration? (based on buildifier)

**Comment by iirina** [comment]
@dslomov Yes I updated the migration notes to include using buildifier.

**Comment by Jdban** [comment]
I pasted this into my `WORKSPACE` file
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_java",
    sha256 = "bc81f1ba47ef5cc68ad32225c3d0e70b8c6f6077663835438da8d5733f917598",
    strip_prefix = "rules_java-7cf3cefd652008d0a64a419c34c13bdca6c8f178",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip",
        "https://github.com/bazelbuild/rules_java/archive/7cf3cefd652008d0a64a419c34c13bdca6c8f178.zip",
    ],
)
load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")
rules_java_dependencies()
rules_java_toolchains()
```

I get this error: 
```
$ bazel test //... --incompatible_load_java_rules_from_bzl
ERROR: error loading package '': Unable to load file '@rules_java//java:repositories.bzl': file doesn't exist
```

This is on bazel `0.29.0`. I haven't modified my build files yet, but I did not expect to see `'@rules_java//java:repositories.bzl': file doesn't exist` as an error.
Did I miss something?
Is there documentation on `rules_java` at all? It is absent from the java rules documentation on docs.bazel.build: https://docs.bazel.build/versions/master/be/java.html

If this is flipping in 1.0, there should be more documentation.

**Comment by brandjon** [comment]
Is it possible you need to run `bazel sync`? I believe there's a built-in `@rules_java` for migration purposes, and if you add the workspace entry without syncing it might still be using the dummy built-in implementation. I just hit something like that.

But now that I've synced (and using the latest rules_java commit), I still get failures within `@bazel_tools`, under `@bazel_tools//tools/jdk:dummy_java_runtime`. Is this migration-ready?

**Comment by iirina** [comment]
@brandjon It is not migration ready

**Comment by brandjon** [comment]
In that case, should we remove the tags `migration-ready` and `migration-0.29`? I believe the latter controls whether this flag is tested by the bazelisk pipeline in buildkite.

**Comment by krlvi** [comment]
Using the 0.1.1 release https://github.com/bazelbuild/rules_java/releases worked successfully for our project

**Comment by iirina** [comment]
Thanks for reporting @krlvi! I updated the snippet in the initial comment to use the latest release.

**Comment by ejona86** [comment]
It appears jvm_import_external needs to be fixed. I recognize maven_install is the new hotness, but migrating to maven_install is non-trivial so takes time. It does look like it may be a bit awkward to figure out a fix for jvm_import_external.

**Comment by iirina** [comment]
@ejona86 can you provide more details about what needs to be fixed in `jvm_import_external`?

**Comment by davido** [comment]
I think @ejona86 is saying that both `jvm_import_external` and `java_import_external` are not compatible with: `--incompatible_load_java_rules_from_bzl` option and will generate say `java_import(...)` without loading `java_import` in BUILD file for external repository:

```
load("@rules_java//java:defs.bzl", "java_import")
```

Moreover, some bazel projects, most notably `rules_closure` even maintain their own fork of `java_import_external` definition. I filed this issue to track it: [1], and I tried to fixed it in the past, but my PR: [2] was not accepted, unfortubately.

* [1] https://github.com/bazelbuild/rules_closure/issues/434
* [2] https://github.com/bazelbuild/rules_closure/pull/239

**Comment by ejona86** [comment]
Yes, `jvm_import_external` generates BUILD files that use `java_import` without an import. And the rule name "java_import" is injected, so it is non-trivial to add the import.

**Comment by davido** [comment]
@iirina Should we file a new issue to adapt `{java|jvm}_import_external` implementation to be compatible with `--incompatible_load_java_rules_from_bzl` option?

**Comment by iirina** [comment]
Thanks all for chiming in. A new issue for `{java|jvm}_import_external` would be great, thanks!

**Comment by lberki** [comment]
We gave up on this :(

**Comment by MikhailTymchukFT** [comment]
@lberki Can you please elaborate?
And what about [tracking issue](https://github.com/bazelbuild/bazel/issues/8741)?

**Comment by lberki** [comment]
Erm, sorry for the curt answer. We decided not to require everyone to add a `load()` statement to every single BUILD file because it's too much churn. The current plan is to "pretend" that the eventual C++/Java rules written in Starlark are `load()`ed everywhere.

We might revisit this decision once they are reasonably stable and once we decide where exactly they need to be `load()`ed from, but now is not the time.
