### ISSUE TITLE
Error reporting of missing toolchain could be more helpful

### ISSUE THREAD

**Issue by aspiwack** [bazelbuild/bazel#8748]
### Description of the problem / feature request:

When Bazel can't find a toolchain for a given target, it will complain with

```
ERROR: While resolving toolchains for target //:example: no matching toolchains found for types <toolchain name>
```

Which is accurate, but not very informative.

It turns out that the way I triggered this was that I was using rules_haskell+rules_nixpkgs, but had forgotten to set `--host_platform=@io_tweag_rules_haskell//haskell/platforms:linux_x86_64_nixpkgs`.

It was very puzzling! I had registered my toolchain in the WORKSPACE file. What was going on? It took me and a colleague more time than I care to admit to figure out what was wrong.

My understanding of how Bazel handles toolchain, though, is that my toolchain was indeed registered, but it was uneselected by the platform predicates. So, instead of just the one line above, I'd like to see something like:

```
ERROR: While resolving toolchains for target //:example: no matching toolchains found for types <toolchain name>
There are unselected toolchains for that name
* <toolchain1>: predicates <list of conditions for toolchain1 to be selected>
* <…>: …
Did you set your platform flags incorrectly?
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

WORKSPACE

```python
workspace(name = "test")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive"
)

http_archive(
    name = "io_tweag_rules_haskell",
    strip_prefix = "rules_haskell-1f7a51b278f27b0cea8c9aef9b529e39ea735b75",
    urls = ["https://github.com/tweag/rules_haskell/archive/1f7a51b278f27b0cea8c9aef9b529e39ea735b75.tar.gz"],
    sha256 = "6d4c53b1ff515773adc4e49d07f799f4165a875f21622bf4d326b22542e6180c",
)

load(
    "@io_tweag_rules_haskell//haskell:repositories.bzl",
    "haskell_repositories"
)

haskell_repositories()

http_archive(
    name = "io_tweag_rules_nixpkgs",
    strip_prefix = "rules_nixpkgs-0.5.2",
    urls = ["https://github.com/tweag/rules_nixpkgs/archive/v0.5.2.tar.gz"],
    sha256 = "5a384daa57b49abf9f0b672852f1a66a3c52aecf9d4d2ac64f6de0fd307690c8",
)

load(
    "@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl",
    "nixpkgs_git_repository",
    "nixpkgs_package"
)

nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "c21f08bfedde0f7d00a5ebc85455fb28b9037932", # Any tag or commit hash
)

load(
    "@io_tweag_rules_haskell//haskell:nixpkgs.bzl",
    "haskell_register_ghc_nixpkgs",
)

load(
    "@io_tweag_rules_haskell//haskell:haskell.bzl",
    "haskell_register_ghc_bindists",
)

haskell_register_ghc_nixpkgs(
    attribute_path = "haskell.compiler.ghc864",
    repositories = {"nixpkgs": "@nixpkgs//:default.nix"},
    version = "8.6.4",
)
```

BUILD.bzl

```python
package(default_visibility = ["//visibility:public"])

load(
    "@io_tweag_rules_haskell//haskell:haskell.bzl",
    "haskell_toolchain_library",
    "haskell_library",
    "haskell_binary",
)

haskell_toolchain_library(name = "base")

haskell_binary(
    name = "example",
    srcs = [":Example.hs"],
    deps = [":base"],
)
```

Example.hs

```haskell
module Main where

import Prelude (putStrLn)

main = putStrLn "Hello from rules_haskell!"
```

Call
```
$ bazel run //:example
```

To obtain the error message

The following doesn't error (at least if you have the Nix package manager installed):

```
$ bazel run //:example --host_platform=@io_tweag_rules_haskell//haskell/platforms:linux_x86_64_nixpkgs
```

### What operating system are you running Bazel on?

Ubuntu 19.04

### What's the output of `bazel info release`?

```
release 0.27.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Built with Nixpkgs 19.09pre184217.74e217e6af5 .

**Comment by katre** [comment]
This is definitely an interesting approach and I see the utility. Not sure anyone will have the time to tackle this in the near future, unfortunately.
