### ISSUE TITLE
Files copied from successful foreign_cc CMake invocation handled as text not binary

### ISSUE THREAD

**Issue by wrowe** [bazelbuild/bazel#8749]
### Description of the problem / feature request:

Corruption of .lib and .pdb objects generated for the foreign_cc c-ares component is observed in the bazel build in the 0.24.0 bazel timeframe. The first delta between what CMake has compiled and archived for c-ares (cares.lib) and what bazel has copied to the bazel-out directory indicated by this linker error 

Execution platform: @bazel_tools//platforms:host_platform
bazel-out\x64_windows-dbg\genfiles\external\envoy\bazel\foreign_cc\ares\lib\cares.lib : fatal error LNK1127: library is corrupt
Target //source/exe:envoy-static failed to build

consists of two-byte sequence to single byte truncation, first occurring here;

Comparing files .\cares.lib and C:\WORKSPACE\ENVOY\BAZEL-OUT\X64_WINDOWS-DBG\GENFILES\EXTERNAL\ENVOY\BAZEL\FOREIGN_CC\ARES\LIB\CARES.LIB
00081313: 0D 0A
00081314: 0A 00
00081316: 00 0E
00081317: 0E 00
0008131A: 00 04
0008131B: 04 00

It appears bazel has treated this file as text input, truncating \r\n into \n, and I'd presume without digging more deeply that the second missing byte is a similar 0D 0A pair truncated to 0A.

The next step is to diagnose where bazel has opened the files to copy (.lib, .pdb etc) in Win32-pseudo-posix text mode, and ensure these archives are opened in binary mode instead.

The copy by CMake from lib/cares.lib where it was actually linked mirrors the copy CMakes creates for an installation tree in cares/lib/cares.lib, suggesting that the local 'cp' command is not at fault.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The bazel build schema is complex to provision on windows for envoyproxy project, myself an my colleagues are happy to walk anyone through the reproduction and test any proposed patches to bazel. 

### What operating system are you running Bazel on?

Windows OS.

### What's the output of `bazel info release`?

WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\workspace\envoy/tools/bazel.rc
Starting local Bazel server and connecting to it...
development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Bazel 0.24.0 with the long command line - pathname workaround patch was generated under stock/release bazel 0.24.0 with Visual Studio 2017 and JDK 8 u221.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

The forked branch, with minimal patches, can be found here;
https://github.com/greenhouse-org/bazel/tree/directory-hack-0.24.0

###  Have you found anything relevant by searching the web?

No hints found.

### Any other information, logs, or outputs that you want to share?

Provided above

**Comment by irengrig** [comment]
Closing this as the issue was resolved in rules_foreign_cc
