### ISSUE TITLE
Device  /dev/tty not found, once upgrade from 0.9.0 to 0.10.0+

### ISSUE THREAD

**Issue by systemlogic** [bazelbuild/bazel#8752]
### Description of the problem / feature request:

Device  /dev/tty not found, once upgrade from 0.9.0 to 0.10.0+

### Feature requests: what underlying problem are you trying to solve with this feature?

Restore functionality in 0.9.0 which was allowing multiple thread running in parallel and /dev/tty issue never comes.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Wrtie few shell targets  which uses makeself to create binary. One has to create multiple such targets and their test rules. Run the test on CI, Error will come. NOTE: IF test cases will run serially on local  issue won't be reported.

In our case we have written complete Python tooling where, we create virtual environment, install dependencies, add required python code, create zip file out of big mess. We can ship this file on any linux machine and binary can run without any python or external dependencies.

### What operating system are you running Bazel on?

ubuntu

### What's the output of `bazel info release`?

release 0.15.2

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

IBM private git repository

###  Have you found anything relevant by searching the web?

makeself.io
If device not found which also means it is being used.

### Any other information, logs, or outputs that you want to share?

For some of the test cases, we are noticing  `cannot create /dev/tty: No such device or address`
Any idea what we are doing wrong Or is there any setting we can do in jenkins?
```Loaded image: bazel/tools/python/tests:check_version_py3_artifact_image

./check_version_py3_runtime_wrapper.sh: 208: ./check_version_py3_runtime_wrapper.sh: cannot create /dev/tty: No such device or address

/root/deploy.sh: line 143:    21 Terminated              "${EXECUTABLE}" --quiet --target "${OUTPUT}" -- "${args[@]}"```

**Comment by ishikhman** [comment]
@systemlogic could please specify what exactly are you trying to update from version 0.9.0 to 0.10.0?

**Comment by systemlogic** [comment]
I only want to update bazel version to get new feature. 0.10.0 is first stepping stone where /dev/tty issue is coming until 0.15.2.

**Comment by dslomov** [comment]
Without more context, it is very hard to tell what happened here

**Comment by laszlocsomor** [comment]
Hey @systemlogic , sorry to hear about these issues.

Do I understand correctly that the problem is multiple tests running in parallel that all try to write to the console?

Could you maybe create a public github repo with fake BUILD rules that we could clone and repro the issue from?

Also, can you try using a more recent Bazel version? Bazel 0.15 is more than a year old, current release is 0.27.1 and we release every month. Unfortunately we cannot offer long-term support for old versions. (Our first longer-term support release will be 1.0, expected to land in September 2019.)

**Comment by systemlogic** [comment]
@laszlocsomor 
In order to fix the build issue coming after bazel upgrade, we have to run all script as sudo. This is a major change and our builds are prone now. 
For now we are good.
We tried to jump to latest version of bazel but we have to apply bazel fix in following order 
1). /dev/tty issue.
2).  Scala macwire
3).  array index out of bound
4). gazel bazel
and our PR become very heavy to accommodate such a large change.

Many Thanks.
