### ISSUE TITLE
cpufeatures doesn't work with recent Android NDK

### ISSUE THREAD

**Issue by pszturmaj** [bazelbuild/bazel#8753]
### Description of the problem / feature request:

When including `@androidndk//:cpufeatures` in cc_library's deps, I get following error:

```
fatal error: 'cpu-features.h' file not found
#  include <cpu-features.h>
           ^~~~~~~~~~~~~~~~
1 error generated.
```

Same library is successfully building with bare ndk-build (Android.mk references cpufeatures). Also the other cc_library rules that don't require cpufeatures are correctly building with NDK/bazel.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- Use Android NDK ver 20.0.5594570 (installed automatically from Android Studio SDK manager)
- add cpufeatures to deps:
```
cc_library(
	name = "dep_lib",
	srcs = [
		"source_referencing_cpufeatures_header.c",
	]
)
cc_library(
	name = "lib",
	deps = [
		"@androidndk//:cpufeatures",
		":dep_lib",
	]
)
```

WORKSPACE file:
```
android_sdk_repository(
	name = "androidsdk",
	path = "PATH_TO_ANDROID_SDK"
)

android_ndk_repository(
	name = "androidndk",
	path = "PATH_TO_ANDROID_SDK/ndk/20.0.5594570"
)
```
Build with:
```
bazel build //:lib --crosstool_top=@androidndk//:default_crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
```

### What operating system are you running Bazel on?

Windows 10 (1809)

### What's the output of `bazel info release`?

release 0.27.0

**Comment by ahumesky** [comment]
Hmm, so the cpufeatures target is just

    cc_library(
        name = 'cpufeatures',
        srcs = glob(['ndk/sources/android/cpufeatures/*.c']),
        hdrs = glob(['ndk/sources/android/cpufeatures/*.h']),
        linkopts = ['-ldl'],
    )

and looking at ndk-r20, those files still appear to be there:

    ~/android-ndk-r20$ ls sources/android/cpufeatures
    Android.mk  cpu-features.c  cpu-features.h  NOTICE

What's the output when you do
    bazel query @androidndk//:cpufeatures --output=build

**Comment by ahumesky** [comment]
The problem is that `cpu-features.h` has to be referenced like this:

    #include "ndk/sources/android/cpufeatures/cpu-features.h"

See the example here: https://docs.bazel.build/versions/master/be/android.html#android_ndk_repository_cpufeatures

(also note that in your repro example, `@androidndk//:cpufeatures` has to go in the `deps` of `dep_lib`, since that's the target whose sources are referencing cpu-features.h)
