### ISSUE TITLE
External package does not resolve dependencies

### ISSUE THREAD

**Issue by marcohu** [bazelbuild/bazel#8754]
Trying to use a target from an external package that has dependencies 
defined in the package workspace (via the `workspace_file` attribute) fails.

`bazel build //...` shows this error message:

```bash
ERROR: /home/user/.cache/bazel/_bazel_user/64492308e78c9898c41f12c18dd29b63/external/antlr3_runtimes/BUILD.bazel:43:1: no such package '@stringtemplate3//jar': The repository '@stringtemplate3' could not be resolved and referenced by '@antlr3_runtimes//:antlr3_tool'
ERROR: Analysis of target '//external_dependency/src/main/java/bazel:hello' failed; build aborted: no such package '@stringtemplate3//jar': The repository '@stringtemplate3' could not be resolved

```

You can find a repro at https://github.com/marcohu/bazel

The project layout looks like this:

```
├── antlr.BUILD
├── antlr.WORKSPACE
├── BUILD
├── external_dependency
│   └── src
│       └── main
│           └── java
│               └── bazel
│                   ├── BUILD
│                   └── Hello.java
├── LICENSE
└── WORKSPACE
```
The `WORKSPACE` definition looks like this:

```python
workspace(name="bazel")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "antlr3_runtimes",
    sha256 = "d4f7d3c38c5523f8009ff37528e5797c81adb454be6acc9af507cfcb41f2016f",
    strip_prefix = "antlr3-master",
    urls = ["https://github.com/ibre5041/antlr3/archive/master.tar.gz"],
    build_file = "@//:antlr.BUILD",
    workspace_file = "@//:antlr.WORKSPACE",
)
```
Interestingly the same error appears if I comment out the `workspace_file` attribute, so it seems there is something wrong with that. 

I'm using Bazel 0.27.0 on Debian Testing.

**Comment by ishikhman** [comment]
One thing I've noticed briefly looking: in given example you should be referring your repository as `@antlr3_runtimes//:%name_from_antlr.BUILD%`, while from the error message it seems that you were refering to it as `@stringtemplate3//jar`. Documented [here](https://docs.bazel.build/versions/master/repo/http.html)

If that does not help, please copy your question to our [Stakoverflow](https://stackoverflow.com/questions/tagged/bazel) on in [the mailing list](https://groups.google.com/forum/#!forum/bazel-discuss), that would make the issue more visible and we will be able to help you faster, thanks!
