### ISSUE TITLE
Contents of bazelrc shall not be passed through command line

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#8755]
We have about 15 kilobytes in `.bazelrc`. Bazel seems to copy contents of this file even if exact options are not used for that run, when it runs Java:
```
--default_override=1:build:XXXX=YYYY
```

@meteorcloudy On Windows there is a 32k limitation of command line. That breaks everything. Can we figure out a way how to not pass `.bazelrc` contents via command line (for example, parse it in Java code)?

This code is so old it even has no history in GitHub :( :
https://github.com/bazelbuild/bazel/blame/6f864c3a5d1aa03037cf9e8c6ab853f278d67d9a/src/main/cpp/option_processor.cc#L449

**Comment by laszlocsomor** [comment]
With which command line do you see this exactly. My repro attempts failed.

**Comment by excitoon** [comment]
https://github.com/excitoon/bazel-issues/tree/master/bazelrc-long-command-line

Looks like it is only reproduces with deprecated `--batch` startup option.

**Comment by laszlocsomor** [comment]
Thanks! Oh my, that's nasty.

Can you not use `--batch` and manually call `bazel shutdown` afterwards?

**Comment by laszlocsomor** [comment]
P3 because it's a deprecated feature and there's a workaround.

**Comment by excitoon** [comment]
Okay!

https://devopsreactions.tumblr.com/post/144645169838/looking-at-old-code

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by excitoon** [comment]
You can reproduce it with the example.
