### ISSUE TITLE
Windows: bug with glob + casing

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8759]
### Description of the problem / feature request:

`glob()` is case-sensitive on Windows if the glob is complex.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Get https://github.com/laszlocsomor/projects/tree/7e9b9c565248d77c5baca9ed80a9cf3dc8bcf146/bazel/glob-exclude
2. Edit the `BUILD` file's `glob` like so:
    ```diff
    --- a/bazel/glob-exclude/BUILD
    +++ b/bazel/glob-exclude/BUILD
    @@ -1,7 +1,7 @@
     genrule(
         name = "x",
         srcs = glob(
    -        ["foo/**"],  # mind this is lower-case
    +        ["f*o*o/**"],  # mind this is lower-case
             exclude = ["Foo/Bar/y.dat"],  # mind this is upper-case
         ),
         outs = ["x.txt"],
    ```
3. `bazel build :all`, and see `bazel-bin\x.txt` has no matches. If you change the `f` to `F` in the glob, the match is there.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.27.0

###  Have you found anything relevant by searching the web?

Likely same culprit as https://github.com/bazelbuild/bazel/issues/8705

**Comment by laszlocsomor** [comment]
I think this behavior is actually correct, and the opposite is wrong, i.e. when the glob is not "complex" it should still be case-sensitive.

Example: `glob(["foo/bar"])` matches `Foo/Bar` (and yields `foo/bar` which is the culprit of https://github.com/bazelbuild/bazel/issues/8705) but `glob(["fo*/Bar"]) doesn't, because Bazel does a `stat` for the first (which ignores casing) but does a `readdir` + regex match for the second.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
