### ISSUE TITLE
Add a project that uses tensorflow as an external repo to our CI

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#876]
We build tensorflow, but there are other issues that have popped up having it included as an external repo.

**Comment by dslomov** [comment]
@damienmg could you take a look and further triage?

**Comment by damienmg** [comment]
This will be done next week.

**Comment by damienmg** [comment]
This was done by adding TensorFlow serving

**Comment by iahmad-khan** [comment]
can someone please suggest how to add tensorflow as an external repo to an existing software repo

**Comment by kchodorow** [comment]
See https://github.com/tensorflow/serving/blob/master/WORKSPACE.
