### ISSUE TITLE
cc_proto_library should suppress warnings in message headers

### ISSUE THREAD

**Issue by ghorn** [bazelbuild/bazel#8761]
### Description of the problem / feature request:

When using `-Wuseless-cast -Werror`, you are unable to include the header generated by `cc_proto_library`. Every `string` field in my proto messages gets a setter like this:
```C++
inline void MyMessage::set_my_field(const char* value, size_t size) {
  
  my_field_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MyMessage.my_field)
}
```
When you #include this header you get errors like:
```
bazel-out/k8-fastbuild/bin/my_messages.pb.h: In member function 'void MyMessage::set_my_field(const char*, size_t)':
bazel-out/k8-fastbuild/bin/my_messages.pb.h:1234:56: error: useless cast to type 'const char*' [-Werror=useless-cast]
       ::std::string(reinterpret_cast<const char*>(value), size));
                                                        ^
```
Ideally this header would get treated as a system library in `cc_library` and included with `-isystem` to turn off warnings, but the `cc_library` option `includes` is not accessible (https://github.com/bazelbuild/bazel/issues/4446). I think `includes = ["."]` should be hardcoded in some form to guarantee that any warnings in the proto message header don't break your compilation.

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

release 0.27.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

nix

###  Have you found anything relevant by searching the web?
https://github.com/bazelbuild/bazel/issues/5466 (resolved by turning off errors for compilation, doesn't help including headers)
https://github.com/bazelbuild/bazel/issues/4446 (more general version of the problem with trickier solution)

**Comment by hlopko** [comment]
Well, that will only solve the problem when you change your codebase to import proto headers with "#include <>" right? For me the proper fix is to tell protoc that it generages code with warnings and it should be fixed there. There is a push for this already in https://github.com/protocolbuffers/protobuf/issues/4628.

**Comment by ghorn** [comment]
I agree that fixing the warning in protocol buffers should be done either way. And you would indeed have to `#include <...>` which may not be desirable for many people. But this will probably come up again in the future. For example the warning I showed above is a different warning than in #4628. I was proposing this to facilitate a workaround, but I get the disadvantages.

The alternative workaround seems to be making a patch to protocolbuffers to fix the warning and then overriding the version of protobufs you're using with bazel. This seems reasonable, but it is not straightforward to figure out how to do that for many users.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
