### ISSUE TITLE
Allow putting multiple constraint_values from a single constraint_setting into platform

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/bazel#8763]
Current toolchains/platforms have no way of expressing that a particular constraint setting is not important for a given platform.

This is useful for e.g. autoconfigured host platform where we want to say I take any C++ toolchain, it doesn't matter which compiler it has. Similar situation is for rules_go with cgo on linux, they don't need specific C++ compiler, any will do.

This changes how platform inheritance works. Currently child platform overrides constraints from the parent. After this change values will be additive. Care will have to be taken (and problem documented) on the user side to register toolchains that are meant to be selected by the child platform before toolchains that are selected by the parent platform.

**Comment by hlopko** [comment]
Related: https://github.com/bazelbuild/rules_go/issues/2089, https://github.com/bazelbuild/rules_cc/issues/24, https://github.com/bazelbuild/bazel/issues/8766.

**Comment by brandjon** [comment]
Also applies to Python (non-hermetic) toolchains, where the system has an interpreter at more than one path. (Not commenting on prioritization, just that it's a potential use case.)

**Comment by dslomov** [comment]
Is this still a blocker for 1.0?

**Comment by dslomov** [comment]
ping @katre

**Comment by katre** [comment]
I am not aware of any uses of this that are required for 1.0, since we de-prioritized enabling toolchain resolution for CC rules.

**Comment by katre** [comment]
Also, I don't know when anyone will have time to work on it.

**Comment by strican** [comment]
My understanding is that this is a requirement for `rules_go` and `rules_docker` to work together. See bazelbuild/rules_go#2089. This seems like an important scenario to me at least.

**Comment by dslomov** [comment]
> My understanding is that this is a requirement for `rules_go` and `rules_docker` to work together. See [bazelbuild/rules_go#2089](https://github.com/bazelbuild/rules_go/issues/2089). This seems like an important scenario to me at least.

@hlopko / @katre: thoughts? Are rules_go + rules_docker broken? Or it is it just for platform-based C++ rules?

**Comment by dslomov** [comment]
Keeping this blocking 1.0 until the comment is addressed.

**Comment by katre** [comment]
The fixes for https://github.com/bazelbuild/rules_go/issues/2089 require widespread work, not just this issue regarding multiple constraint values (See @hlopko's [comment](https://github.com/bazelbuild/rules_go/issues/2089#issuecomment-507583536) for details). The work to add [host platform generic autodetection](https://github.com/bazelbuild/bazel/issues/8766) hasn't even been fully specced out, much less designed, for example.

Given that only resolving this issue won't fix rules_go, and that there's no one available to fix this issue, much less the related issues @hlopko raised, I don't think getting this in for 1.0 is needed or even feasible.

**Comment by dslomov** [comment]
Thanks @katre!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
