### ISSUE TITLE
Skylark Overview page is confusing or inconsistent

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#8776]
https://docs.bazel.build/versions/master/skylark/lib/skylark-overview.html

Some issues:

1. "Global Modules" is populated with a number of items that are not quite module-like. For example, `CcProvider`, `CcToolchainInfo`, and `TemplateVariableInfo` are builtin providers, but exist under "Global modules"

2. Some types are listed here in not-so-meaningful ways. For example, LateBoundDefault, while it is technically a Starlark type (I believe you can get an object of its type and call `type()` on it to get "LateBoundDefault", but otherwise it has no meaning. Such cases should be in perhaps a "types" section of the documentation, and not in the global reference alongside calllable modules.

3. "Built-in Types and Modules" is unclear. Should we drop the "and Modules" ?

4. Should we separate language-specific build API types into different documentation sections? It would pollute the overview less, since only apple rules writers likely care about Apple-related providers.

5. We should consider overhauling module doc pages to make it very clear how one can access the module from a rule context (or, in some cases, globally). For example: https://docs.bazel.build/versions/0.27.0/skylark/lib/apple.html makes it seem like one can simply call `apple.bitcode_mode`, when it's truly `ctx.fragments.apple.bitcode_mode`.

**Comment by cvrebert** [comment]
Also, [`native`'s page](https://docs.bazel.build/versions/master/skylark/lib/native.html) says it's "A built-in module to support native rules", yet the index lists it under "Built-in Types" rather than "Global Modules" for some reason.

**Comment by c-parsons** [comment]
Thanks for the heads up.

We fixed a good deal of this with a514febe5f7318a3e761d7bbeddca2f8f3054010, but apparently native was left out.

**Comment by brandjon** [comment]
Not sure how many of Chris's issues from the first post remain, but we can still clean up the [One-Page Overview](https://bazel.build/rules/lib/starlark-overview#global-modules) (current link) some more. Off the top of my head:

* Create more documentation categories, maybe with a small amount of hierarchy, and display them in the overview and on the pages for the individual symbols. This would help avoid situations like the delightfully ambiguous [`DottedVersion`](https://bazel.build/rules/lib/DottedVersion).
* Separate all core Starlark symbols from Bazel-specific ones. Right now we only do this for data types, but we should do it for top-level functions too.
* Likewise, separate all language-specific builtins (things that could/should be Starlarkified) from generic symbols (`rule`/`provider`/etc.).
* Probably most important of all, separate symbols based on what context they're useful/available in -- bzlmod, WORKSPACE, BUILD, .bzl.
