### ISSUE TITLE
Enable overriding the tool used by link actions in cc_configure

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/bazel#8777]
### Description of the problem / feature request:

Enable overriding the tool used by link actions in cc_configure.

### Feature requests: what underlying problem are you trying to solve with this feature?

We want to support ubsan builds with Bazel / RBE without the need for a custom toolchain configuration. Currently, the only thing that our toolchain configuration defines is the tool used for link actions (e.g., https://github.com/bazelbuild/bazel-toolchains/blob/master/configs/experimental/ubuntu16_04_clang/1.2/bazel_0.23.0/ubsan/cc_toolchain_config.bzl#L116).
Every other sanitizer (asan, msan, tsan) currently works out of the box both with the Bazel container and with Bazel + RBE, except for ubsan. We spend too much effort currently to manually upgrade our ubsan custom toolchain with new Bazel versions.

We think it should be plausible to have `cc_configure` read a `BAZEL_LINKTOOL` env variable or something of the sort and produce the corresponding toolchain config that only has the relevant action configs overridden.

**Comment by keith** [comment]
Related https://github.com/bazelbuild/bazel/pull/7883

**Comment by hlopko** [comment]
Can you link issues/discussions about ubsan needed clang++? Sounds weird that it does..

**Comment by hlopko** [comment]
And to be sure, you don't care about specifying the linker (e.g. specifying FOO when passing `-fuse-ld=FOO` to CC), you only want to specify the tool that will be used in linking related action configs.

I think the former is requested more often..

**Comment by hlopko** [comment]
Alternative that comes to mind is to use clang++ for CC - setting clang++ to be the compiler driver for everything. Did you consider that? What were the problems?

**Comment by nlopezgi** [comment]
Hi Marcel, thanks for your response.
I have tried using clang++ for CC and that does not work for ubsan, it has to only be the tool used for link actions. I have an internal bug with the full discussion about this, will send it to you via email.

**Comment by hlopko** [comment]
Thanks Nick, give me a few days to see if we can get away with using `clang`, I hope it will be possible.

**Comment by nlopezgi** [comment]
sure thing! I would love to find a simpler way to get ubsan to work.

**Comment by hlopko** [comment]
Closing since it seems there are ways to make upsan work with current APIs.
