### ISSUE TITLE
namespace-sandbox bug in getopt usage

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#878]
```
  while (optind < argc && argv[optind][0] == '@') {
    const char *filename = argv[optind] + 1;
    const int old_optind = optind;
    optind = 1; <== this needs to be set to 1; note that ParseOptionsFile adds an empty zero-th argument
    optreset = 1; <== according to the manpage, this needs to be set before calling getopt on a second pass
    ParseOptionsFile(filename, opt);
    optind = old_optind + 1;
    optreset = 1; <== here also
  }

```

**Comment by ulfjack** [comment]
I tried to use part of this .c file on OSX where the getopt call fails immediately on params files.

**Comment by ulfjack** [comment]
Also, it's leaking memory. There's a malloc call for full_sandbox_path in SetupDirectories, but no corresponding free call.

**Comment by ulfjack** [comment]
And the use of dirname isn't safe on OSX. While linux makes modifications in-place - so we have to make a copy before calling dirname -, OSX returns a pointer to a statically allocated buffer - so we have to make a copy after calling dirname (otherwise the value will change underneath us the next time we call dirname; which is a problem for the recursive directory creation).

**Comment by philwo** [comment]
I think this is obsolete with the new sandbox being released now.
