### ISSUE TITLE
incompatible_enable_profile_by_default: Switch to the JSON profile and enable it by default

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#8783]
This flags enables the JSON profile by default for every bazel invocation. The JSON profile is written to the output base (exact path is written to stderr) and you can load it via chrome://tracing. See also https://docs.bazel.build/versions/master/skylark/performance.html#json-profile.

It also sets the recommended options:
- compression
- slim profile
- cpu profile
- profile started event

There is no code change necessary.

We did a lot of Google-internal experiments and think it doesn't affect end to end build performance.

We intend to flip this with the next incompatible release, probably 1.0 in September.

**Comment by dslomov** [comment]
What is the breaking change here?

**Comment by meisterT** [comment]
We create a file by default that was previously not created. I don't expect any breakage here, but wanted to play safe.

**Comment by dslomov** [comment]
This is closed, I assume.
