### ISSUE TITLE
Commit ea172999bd6f0b6f5b05613040f730a03ea40a1d broke pkgcache_test on ci.bazel.io

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#879]
Found by
`git bisect run bazel test //src/test/java/com/google/devtools/build/lib:pkgcache_test `

This has been failing since http://ci.bazel.io/job/Bazel/350/...

**Comment by damienmg** [comment]
It's still failing :(
http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/lastCompletedBuild/testReport/

**Comment by dslomov** [comment]
sorry, looking now

On Fri, Feb 12, 2016 at 10:43 AM, Damien Martin-Guillerez <
notifications@github.com> wrote:

> It's still failing :(
>
> http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/lastCompletedBuild/testReport/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bazelbuild/bazel/issues/879#issuecomment-183253824>.
>



-- 
Google Germany GmbH
*Dienerstr. 12, 80331 München., DE *

**Comment by dslomov** [comment]
https://github.com/bazelbuild/bazel/commit/ea172999bd6f0b6f5b05613040f730a03ea40a1d
is the curpit

On Fri, Feb 12, 2016 at 10:43 AM, Dmitry Lomov <dslomov@google.com> wrote:

> sorry, looking now
>
> On Fri, Feb 12, 2016 at 10:43 AM, Damien Martin-Guillerez <
> notifications@github.com> wrote:
>
>> It's still failing :(
>>
>> http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/lastCompletedBuild/testReport/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bazelbuild/bazel/issues/879#issuecomment-183253824>.
>>
>
>
>
> --
> Google Germany GmbH
> *Dienerstr. 12, 80331 München., DE *
>



-- 
Google Germany GmbH
*Dienerstr. 12, 80331 München., DE *

**Comment by dslomov** [comment]
(oh sorry nevermind)

On Fri, Feb 12, 2016 at 11:30 AM, Dmitry Lomov <dslomov@google.com> wrote:

>
> https://github.com/bazelbuild/bazel/commit/ea172999bd6f0b6f5b05613040f730a03ea40a1d
> is the curpit
>
> On Fri, Feb 12, 2016 at 10:43 AM, Dmitry Lomov <dslomov@google.com> wrote:
>
>> sorry, looking now
>>
>> On Fri, Feb 12, 2016 at 10:43 AM, Damien Martin-Guillerez <
>> notifications@github.com> wrote:
>>
>>> It's still failing :(
>>>
>>> http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/lastCompletedBuild/testReport/
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/bazelbuild/bazel/issues/879#issuecomment-183253824>.
>>>
>>
>>
>>
>> --
>> Google Germany GmbH
>> *Dienerstr. 12, 80331 München., DE *
>>
>
>
>
> --
> Google Germany GmbH
> *Dienerstr. 12, 80331 München., DE *
>



-- 
Google Germany GmbH
*Dienerstr. 12, 80331 München., DE *

**Comment by dslomov** [comment]
So yes still reproes even with that CL.

**Comment by damienmg** [comment]
I feel bad for that, I am the culprit.

So the original culprit broke that test and one of my change added another error, fixing it.
