### ISSUE TITLE
/lib64/libc.so.6: version "GLIBC_2.18" not found 

### ISSUE THREAD

**Issue by YuMan-Tam** [bazelbuild/bazel#8792]
I successfully compiled (bootstrap) Bazel 0.27 without error. However, I encounter the following error (see bottom) when I run ```./bazel build```. The issue seems to be that the embedded ```libunix.so``` reference ```/lib64/libc.so.6``` that's too old for my user installed ```libstdc++.so.6```. 

This may be related to issue #914. 

The problem may be solved (I believe) if there's a flag that I can pass during compilation such that  ```libunix.so``` will be created so ```/lib64/libc.so.6```  can be replaced by a newer user installed ```libc.so.6``` that would match the ```libstdc++.so.6```.

I wonder if there is such an option in the current release? Or if this is a bug? Or if there is other explanation and solution? I cannot seem to find any relevant documentation. I did add the ```EXTRA_BAZEL_ARGS``` flag as instructed on the official website when I bootstrap Bazel.

Upgrading RHEL is unfortunately not an option because I do not have root privilege. 

```Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Server crashed during startup. Now printing /sasdata/ra/user/$USER/.cache/bazel/_bazel_$USER/29acc57af8377a04a45afcce69fee630/server/jvm.out

JNI initialization failed: /sasdata/ra/user/$USER/.cache/bazel/_bazel_$USER/install/438d6e3ea83cf26e0889510a13e0b592/_embedded_binaries/libunix.so: /lib64/libc.so.6: version `GLIBC_2.18' not found  (required by /sasdata/ra/user/$USER/.local/brew/lib/libstdc++.so.6).  Possibly your installation has been corrupted. ```

**Comment by dslomov** [comment]
team-EngProd for installation/packahging

**Comment by meisterT** [comment]
Please reopen if this is still a problem at head.
