### ISSUE TITLE
BEP testActionOutput names should include the package path

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#8800]
## Description of the problem / feature request:

The build event logs created by `--build_event_json_file` don't include package paths in the `testActionOutput` entries, which makes it difficult to collect and visualize test outputs as part of a larger CI system (e.g. in a Jenkins cluster with JUnit plugins).

This seems to only be a problem with test outputs. Regular build outputs are named properly.

```
"testActionOutput": [
  {
    "name": "test.log",
    "uri": "file:///path-to-execroot/helloworld/bazel-out/darwin-dbg/testlogs/hello/world/hello_world_test/run_2_of_2/test.log"
  },
  {
    "name": "test.xml",
    "uri": "file:///path-to-execroot/helloworld/bazel-out/darwin-dbg/testlogs/hello/world/hello_world_test/run_2_of_2/test.xml"
  }
],
```

Ideally, those records would look something like this:
```
"testActionOutput": [
  {
    "name": "hello/world/hello_world_test/run_2_of_2/test.log",
    "uri": "file:///path-to-execroot/helloworld/bazel-out/darwin-dbg/testlogs/hello/world/hello_world_test/run_2_of_2/test.log"
  },
  {
    "name": "hello/world/hello_world_test/run_2_of_2/test.xml",
    "uri": "file:///path-to-execroot/helloworld/bazel-out/darwin-dbg/testlogs/hello/world/hello_world_test/run_2_of_2/test.xml"
  }
],
```

### What operating system are you running Bazel on?

macOS and Linux

### What's the output of `bazel info release`?

`release 0.26.1`

**Comment by buchgr** [comment]
@jmillikin-stripe You can transform the former path to the later path with information from the corresponding `TestResultId`.

@ulfjack @ericfelly do you recall a good reason why it's the way it is?

**Comment by ulfjack** [comment]
The name tag here is more of a 'type' of what these files represent. The event should contain the target name and the run information as machine-readable data?

**Comment by buchgr** [comment]
> The event should contain the target name and the run information as machine-readable data?

correct. this information is in `TestResultId`.

**Comment by jmillikin-stripe** [comment]
The `TestResultId` looks something like this:
```json
    "id": {
        "testResult": {
            "label": "//hello/world:hello_world_test",
            "run": 2,
            "shard": 1,
            "attempt": 2,
            "configuration": {
                "id": "1ad7da7783ba62fe677649fbe67d09e6"
            }
        }
    },
```
It might technically be possible to construct `hello/world/hello_world_test/run_2_of_2/test.log` from this data, but that would require hardcoding the exact format of Bazel's test logs.

**Comment by buchgr** [comment]
> but that would require hardcoding the exact format of Bazel's test logs.

I don't follow. The `TestResultId` is specified as a protobuf message and is public API. My understanding of your request is that you are trying to construct a unique name, in the context of one Bazel invocation, for test.log files. Is that not the case? Is it important for you that this name matches the actual on-disk path?

**Comment by jmillikin-stripe** [comment]
Actually, I'm not sure it's possible to construct the filename for a test given only the `TestResultId`. Consider the following:
```json

{
    "id": {
        "testResult": {
            "label": "//hello/world:hello_world_test",
            "run": 3,
            "shard": 1,
            "attempt": 1,
            "configuration": {
                "id": "9b35f2316e822619c8f2ca6e770ffff7"
            }
        }
    },
    "testResult": {
        "testActionOutput": [
            {
                "name": "test.log",
                "uri": "file:///path-to-execroot/helloworld/bazel-out/darwin-dbg/testlogs/hello/world/hello_world_test/run_3_of_4/test.log"
            },
            {
                "name": "test.xml",
                "uri": "file:///path-to-execroot/helloworld/bazel-out/darwin-dbg/testlogs/hello/world/hello_world_test/run_3_of_4/test.xml"
            }
        ],
        "testAttemptDurationMillis": "619",
        "status": "PASSED",
        "testAttemptStartMillisEpoch": "1564412642813",
        "executionInfo": {
            "strategy": "darwin-sandbox"
        }
    }
}
```

I want to render this log in some way that indicates it's test run 3 of 4, ideally matching the format that Bazel prints to the user's terminal when run.

**Comment by janakdr** [comment]
@michaeledgar

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
