### ISSUE TITLE
CcToolchainInfo.*_executable deprecated without alternative

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#8802]
### Description of the problem:

The documentation to [`CcToolchainInfo`](https://docs.bazel.build/versions/0.27.0/skylark/lib/CcToolchainInfo.html) (as of 0.27.0) lists various methods of the form `*_executable` as deprecated (emphasis mine):

> `nm_executable`
> ```
> string CcToolchainInfo.nm_executable()
> ```
> Path to GNU binutils 'nm' binary. **WARNING: This method is only added to allowincremental migration of existing users. Please do not use in new code. Will be removed soon as part of the new Starlark API to the C++ toolchain.**

However, the documentation gives no indication of any alternatives that should be used instead. The [design document "Skylark API to the C++ toolchain"](https://docs.google.com/document/d/1g91BWJITcYw_X-VxsDC0VgUn5E9g0kRBGoBSpoO41gA/edit#) refers users to [`get_tool_for_action`](https://docs.bazel.build/versions/0.27.0/skylark/lib/cc_common.html#get_tool_for_action) as an alternative. However, as far as I can tell, this is incomplete. E.g. I was not able to find an action that returns the equivalent of [`nm_executable`](https://docs.bazel.build/versions/0.27.0/skylark/lib/CcToolchainInfo.html#nm_executable).

### Bugs: what's the simplest, easiest way to reproduce this bug?

See documentation of [`CcToolchainInfo`](https://docs.bazel.build/versions/0.27.0/skylark/lib/CcToolchainInfo.html).

The following snippet lists the tools for all available actions.

```
load("@bazel_tools//tools/build_defs/cc:action_names.bzl", "ACTION_NAMES")

    for attr in dir(ACTION_NAMES):
        action_name = getattr(ACTION_NAMES, attr, None)
        if action_name == None:
            continue
        is_enabled = cc_common.action_is_enabled(
            feature_configuration = feature_configuration,
            action_name = action_name,
        )
        if not is_enabled:
            continue
        tool = cc_common.get_tool_for_action(
            feature_configuration = feature_configuration,
            action_name = action_name,
        )
        print(action_name, tool)
    fail("THE END")
```

On my setup it results in the following list (generated under rules_haskell Nix shell, formatted for readability):

```
assemble                             .../bin/gcc
c-compile                            .../bin/gcc
c++-compile                          .../bin/gcc
c++-header-parsing                   .../bin/gcc
c++-link-dynamic-library             .../bin/gcc
c++-link-executable                  .../bin/gcc
c++-link-nodeps-dynamic-library      .../bin/gcc
c++-link-static-library              .../bin/ar
c++-module-codegen                   .../bin/gcc
c++-module-compile                   .../bin/gcc
linkstamp-compile                    .../bin/gcc
lto-backend                          .../bin/gcc
lto-index-for-dynamic-library        .../bin/gcc
lto-index-for-executable             .../bin/gcc
lto-index-for-nodeps-dynamic-library .../bin/gcc
preprocess-assemble                  .../bin/gcc
strip                                .../bin/strip
```

OS: openSUSE Tumbleweed 20190529

### What's the output of `bazel info release`?

`release 0.27.0- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Nix shell of rules_haskell repository as of commit 3010bcd712ebd764f16df7cb7b23fd77b9333da7.

**Comment by ccontavalli-j** [comment]
BTW, stumbled on the same issue. I am creating a custom rule using the cc toolchain.

The rule needs to invoke the `ld` executable selected by the toolchain mechanics directly. ld_executable is deprecated, but could not find any ACTION_NAME that would provide the path of ld directly.

I also tried to achieve the same result by invoking `gcc` or `clang` with linking flags, but did not find a combination that achieved the result directly. So, sticking to ld_executable for now.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
