### ISSUE TITLE
cc_library 'defines' attribute ignored for windows

### ISSUE THREAD

**Issue by 4ZM** [bazelbuild/bazel#8804]
### Description of the problem / feature request:

There is a bug when adding a `defines` attribute to a `cc_library` or `cc_binary`. It does not add the define at compile time in some instances.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On windows, create an empty WORKSPACE file, a BUILD file with this content:

```
cc_library(
    name = 'foo',     
    srcs=['main.cpp'],
    defines=['SECRETSAUCE']
)
```
and a main.cpp file with this content: `int main() { return 0; }`

finally create a CROSSTOOL file.

Build like so: `bazel build :foo -s +crosstool params`

Output doesn't include `/DSECRETSAUCE`:

```
C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe /c main.cpp /Fobazel-out/x64_windows-fastbuild/bin/_objs/foo/main.o /nologo /I. /Ibazel-out/x64_windows-fastbuild/bin /showIncludes /MT /WX /EHsc /DNOMINMAX /D_ENABLE_ATOMIC_ALIGNMENT_FIX /Od
```

Running this without a CROSSTOOL file works as expected.

### What operating system are you running Bazel on?

Win10

### What's the output of `bazel info release`?

release 0.27.1

###  Have you found anything relevant by searching the web?

No

**Comment by scentini** [comment]
IIUC, the defines are not passed to the command line when you're using your own C++ toolchain.
Do you define the [preprocessor_defines](https://source.bazel.build/bazel/+/master:tools/cpp/windows_cc_toolchain_config.bzl;l=641) feature in your cc_toolchain_config rule?

**Comment by 4ZM** [comment]
I have this in the toolchain (I think it was generated automatically from the migration scripts going from old CROSSTOOL files):

```
preprocessor_defines_feature = feature(                                                                                                                                         
        name = "preprocessor_defines",                                                                                                                                              
        flag_sets = [                                                                                                                                                               
            flag_set(                                                                                                                                                               
                actions = [                                                                                                                                                         
                    ACTION_NAMES.preprocess_assemble,                                                                                                                               
                    ACTION_NAMES.c_compile,                                                                                                                                         
                    ACTION_NAMES.cpp_compile,                                                                                                                                       
                    ACTION_NAMES.cpp_header_parsing,                                                                                                                                
                    "c++-header-preprocessing",                                                                                                                                     
                    ACTION_NAMES.cpp_module_compile,                                                                                                                                
                ],                                                                                                                                                                  
                flag_groups = [                                                                                                                                                     
                    flag_group(                                                                                                                                                     
                        flags = ["/D%{preprocessor_defines}"],                                                                                                                      
                        iterate_over = "preprocessor_defines",                                                                                                                      
                    ),                                                                                                                                                              
                ],                                                                                                                                                                  
            ),                                                                                                                                                                      
        ],                                                                                                                                                                          
    )
```

I would still like to be able to add a define for a specific target in a BUILD file though

**Comment by 4ZM** [comment]
`preprocessor_defines_feature` is added to a `features` list and that is passed to:
```
 cc_common.create_cc_toolchain_config_info(                                                                                                                                  
            ctx = ctx,                                                                                                                                                              
            features = features,
            ...
```

**Comment by scentini** [comment]
Seems like you're missing
[`enabled = True,`](https://source.bazel.build/bazel/+/master:tools/cpp/windows_cc_toolchain_config.bzl;l=643)
in your definition.

The way this works is --> Bazel collects the `define` values from targets into a build variable called `preprocessor_defines`.

The following in the definition of the feature:
```
flag_group(                                                                                                                                                     
    flags = ["/D%{preprocessor_defines}"], 
    iterate_over = "preprocessor_defines",
),
``` 
means to iterate over the `preprocessor_defines` values and prepend a `/D` to each one.

If a feature is enabled, it means Bazel will add the flags it provides to the command line of each specified action.
A feature can be enabled by default (`enabled=True`),
can be specified from a target:
```
cc_library(
    ...
    features = ["feature_x"],
)
```
it can also be specified on the command line:
`bazel build //foo:bar --features=feature_x`

For this specific feature, it's logical to enable it by default.

**Comment by 4ZM** [comment]
This works! Thanks for the help.

We have a bunch of other features as well without `enabled = True`, but they seem to be enabled anyway... like this one. 
```
compiler_flags_feature = feature(
        name = "compiler_flags",
```
The `preprocessor_defines` was the only one I had to enable explicitly.

**Comment by scentini** [comment]
In that case the `compiler_flags` `feature` is implied by some other `feature`, or by an `action_config`. E.g Bazel's own Windows + msvc-cl C++ toolchain configuration has a [`cpp_compile_action`](https://source.bazel.build/bazel/+/master:tools/cpp/windows_cc_toolchain_config.bzl;l=198) which implies a list of `features`, among which the `compiler_flags` one.

Note also that, if you don't have a [`no_legacy_features`](https://source.bazel.build/bazel/+/master:tools/cpp/windows_cc_toolchain_config.bzl;l=750) `feature`, Bazel will automatically add the `action_configs` as well as some `features`, in case they're not defined. See the [`legacy features patching logic`](https://docs.bazel.build/versions/0.27.0/cc-toolchain-config-reference.html#legacy-features-patching-logic) on which `features` we add/shuffle (this will be deprecated at some point, see #8303).

[Here](https://docs.bazel.build/versions/0.27.0/cc-toolchain-config-reference.html#features) you can read more about the way `features` and `action_configs` interact with each other.

**Comment by wyhao31** [comment]
> IIUC, the defines are not passed to the command line when you're using your own C++ toolchain. Do you define the [preprocessor_defines](https://source.bazel.build/bazel/+/master:tools/cpp/windows_cc_toolchain_config.bzl;l=641) feature in your cc_toolchain_config rule?

Happened to run into this thread. Can I ask the reason why defines are not populated to command line when using customized C++ toolchain? Thanks!
