### ISSUE TITLE
Starlark repository rules: environment leaks in

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8806]
# Description of the problem / feature request:

Every envvar is visible to repository rules, not just those they declare in `repository_rule(..., environ)`. But the repo is only re-fetched if one of the declared envvars changes.

This leads to correctness bugs. Concrete example: https://github.com/bazelbuild/bazel/blob/7f395915ba03f85f92a759887d7bec74d1fc8973/tools/cpp/cc_configure.bzl#L122 does not declare depending on e.g. "VS160COMNTOOLS", but https://github.com/bazelbuild/bazel/blob/7f395915ba03f85f92a759887d7bec74d1fc8973/tools/cpp/windows_cc_configure.bzl#L143 can read that envvar. If the user updates this envvar, the repo rule is not re-fetched.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/laszlocsomor/projects/tree/daa9e479505d8ae04d32d2c91f7ffd5c198ff4db/bazel/repo_rule_envvars

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

release 0.27.1

**Comment by meteorcloudy** [comment]
Thanks for discovering this bug! Sending a fix now~

**Comment by laszlocsomor** [comment]
Thank you!

**Comment by laszlocsomor** [comment]
This is not Windows-specific.

**Comment by aehlig** [comment]
Note that the invalidation mechanism for external repositories is the [approved and implemented design by @damienmg](https://bazel.build/designs/2016/10/18/repository-invalidation.html) that people are relying upon. One might discuss to change it, but that would have to be a deliberate incompatible change, not a simple bug fix. Also note that correctness for repository rules cannot be enforced by `bazel`, but it has to rely on the rule author doing the right thing: repository rules execute arbitrary commands that can read arbitrary files without `bazel` knowing about them. On the other hand, often environment variables like `PATH` are inspected just to find a tool, the rule author knows it doesn't which specific version is found, so the rule does not want to be invalidated upon this.

**Comment by laszlocsomor** [comment]
@aehlig : Thanks, the design suggests the behavior is intended, and [`repository_rule.environ`'s doc](https://docs.bazel.build/versions/0.27.0/skylark/lib/globals.html#repository_rule) also says:

> Provides a list of environment variable that this repository rule depends on. If an environment variable in that list change, the repository will be refetched.

So yes, Bazel behaves as advertised.

I assert this behavior is surprising, and maybe ill-designed. That said you have every right to close this as WAI.

**Comment by aehlig** [comment]
> That said you have every right to close this as WAI.

Will do so. Feel free to file a feature request (or even a design document) to change the current semantics.
