### ISSUE TITLE
Java 7 build are failing since http://ci.bazel.io/job/Bazel/350/

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#881]
I suspect commit 51d444355be31dabb1cc45af2d1bdcc67b00abaa but I am currently running a git bisect so we will know.

/cc @dslomov

**Comment by damienmg** [comment]
Culprit is 6bdb82aeead0b3b101b0d05724d8c5493ce819f8 according to git bisect.

**Comment by damienmg** [comment]
Forget it after looking at the CL it makes no sense that this is the culprit

**Comment by damienmg** [comment]
Finally found the culprit change: 7896c3aaa911d429d4200951469132727b73b7e8

Script to run a git bisect (20h to run the bisect):

```
$ cat /tmp/script.sh 
#!/bin/bash

export JAVA_VERSION=1.7
exitCode=0
bash -c "source scripts/ci/build.sh; bazel_build" || exitCode=$?
git reset --hard
exit $exitCode
```

**Comment by damienmg** [comment]
Liam: TL;DR: since the turbine change, the JDK 7 build fails.

This build is basically: use an older JavaBuilder with bazel and avoid building JavaBuilder. Seems like the turbine compiler is compiled anyway.

A a side-note: is there incoming JavaBuilder change that will break the bazel <-> JavaBuilder interface (meaning that we won't be able to compile with older jdk)?

**Comment by cushon** [comment]
There shouldn't be any changes to the interface, header compilation is behind a flag and it won't affect existing configurations if disabled.

Your internal fix looks good, but you may want to extend it to not build anything under `buildjar/...` on jdk7.

How long are you planning to support 7?

**Comment by damienmg** [comment]
As long as possible. We are doing best effort here, don't worry.

**Comment by damienmg** [comment]
Not fixed :(

**Comment by cushon** [comment]
Sorry for the trouble. Would it make sense to exclude everything under `buildjar/...`? I don't think any of it works on jdk7.

**Comment by damienmg** [comment]
No problem, we might need to do it but it's a more than a line change so it
was less troubles to change the tag.
