### ISSUE TITLE
Read Bazel configs from environment variables

### ISSUE THREAD

**Issue by simon0191** [bazelbuild/bazel#8810]
# Read Bazel configs from environment variables

### Description of the problem / feature request:

There are different environments where Bazel is invoked in order to do builds, tests, etc, and depending on the environment we need to enable different configurations. For example, we want to enable remote cache in CI jobs, but disk cache in developers laptops which currently  can be accomplished using `--bazelrc` or `--config` flags.

The problem with these approaches is that in both cases we need to modify all the scripts that invoke Bazel to explicitly add those flags, and depending on the complexity of the task (i.e. a release CI job), the different Bazel invocations may be spread across multiple files in the repository.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to be able to provide Bazel options through environment variables so that in CI I can globally enable certain config that will be picked up by all the Bazel invocations in that environment.

Taking java and JAVA_OPTS as reference I propose enabling something similar like:

- BAZELOPTS="build --remote_cache=cache.com"
or
- BAZELRC="path/to/bazelrc/for/ci"

I also noticed that a BAZELRC is used in some scripts of the Bazel repository. So, Why not adding "native" support for it?

https://github.com/bazelbuild/bazel/blob/5e5ee0db8f1925bcf9ac39232faa0622966d7e2a/scripts/bootstrap/bootstrap.sh#L55

**Comment by Globegitter** [comment]
One approach that should fulfill your use-case areas is making use of `try-import` in the bazelrc. You can have one checked in bazelrc which has `try-import not-checked-in-bazelrc` and you should be good to go with different configs on different machines/setups.

**Comment by aiuto** [comment]
I'm not a fan of using environment variables to control behavior. It makes scripts magic, in that the text you read is not the entire picture of what is happening. You have to understand the entire context of how you got there.

If you have scripts that are dual use for developers and CI, you could do exactly what bootstrap.sh does

```
: ${BAZELRC:="$HOME/.bazelrc"}
 ${BAZEL} --bazelrc=${BAZELRC} ...
```
And have the CI set up its environment with 
`BAZELRC="path/to/bazelrc/for/ci"`

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
