### ISSUE TITLE
Protocol Buffer documentation missing

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#882]
I've just noticed that the page at http://bazel.io/docs/be/protocol-buffer.html (linked from the Docs sidebar) is empty. Seems to affect only this page, as all others have content.

**Comment by davidzchen** [comment]
The native Protocol Buffer rules are not available yet but some of the source files are in place. I will update the docgen to not produce a page if the documentation is empty. Once we open source the Protocol Buffer rules, the documentation will be added.
