### ISSUE TITLE
`cc_import` doesn't copy dlls

### ISSUE THREAD

**Issue by mason-bially** [bazelbuild/bazel#8820]
### Description of the problem / feature request:

`cc_import` doesn't appear to copy `.dll`s correctly in the provided configuration (on windows).

### Feature requests: what underlying problem are you trying to solve with this feature?

Use an externally built `.dll` file (though if someone has a BUILD file for skia that would work too)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use the attached repro and run:

```
> cd out
> bazel run example
...
error while loading shared libraries: skia.dll: cannot open shared object file: No such file or directory
>
```

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

> release 0.27.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

* [This is the pattern I am following](https://github.com/bazelbuild/bazel/issues/4560) and appears to be the only piece of information on `cc_import`

**Comment by mason-bially** [comment]
[repro.zip](https://github.com/bazelbuild/bazel/files/3369583/repro.zip)

**Comment by mason-bially** [comment]
[repro.zip](https://github.com/bazelbuild/bazel/files/3369586/repro.zip)

**Comment by mason-bially** [comment]
Notably the `linkstatic = 0` in the `example` binary doesn't actually do anything, it fails either way.

**Comment by scentini** [comment]
@meteorcloudy  can you help with this one?

**Comment by meteorcloudy** [comment]
@mason-bially Thanks for reporting this! This is a bug in Bazel, because Bazel only checked if the dll's package name is the same as the binary but forget to check if they come from the same repository. In this case, they are both under the root package and Bazel ignored the copy. I'll send a fix for this soon!

**Comment by mason-bially** [comment]
@meteorcloudy Thanks for fixing that! Are there any official resources for best practices involving dynamic libraries I could read (besides the link I gave)? While trying to debug this I was having trouble understanding the model Bazel was attempting to use.

**Comment by meteorcloudy** [comment]
We don't have a very good cross-platform solution yet. But we do have some examples to build DLL on Windows, see https://github.com/bazelbuild/bazel/blob/master/examples/windows/dll/BUILD

@oquenchil is working on a cross-platform solution for dynamic library.
