### ISSUE TITLE
Bazel sets execute permission on non-executable files

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/bazel#8824]
### Description of the problem

When using rules_apple, some outputs are incorrectly being set to have the execute permission set. In rules_apple, these files have their permissions explicitly set to standard values:

https://github.com/bazelbuild/rules_apple/blob/7f8a25a57ab9a4e406025eaa2c4394a20f793f47/tools/bundletool/bundletool_experimental.py#L204

However, after this, Bazel changes there permissions to `0555`/`r-xr-xr-x`. I believe this is happening here:

https://github.com/bazelbuild/bazel/blob/658d47f41ca6df7f6739f77b2f1bb615e61811c1/src/main/java/com/google/devtools/build/lib/skyframe/ActionMetadataHandler.java#L633-L660

It looks like maybe the whole tree artifact is being given these permissions.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build any sample rules_apple iOS app with `apple.experimental.tree_artifact_outputs` enabled. (using  `--define=apple.experimental.tree_artifact_outputs=1`). Virtually all files in the `.app` will have the execute bit set.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.27.0

**Comment by benjaminp** [comment]
Probably this, #2888, and #5588 should be merged into one issue to rule them all.

**Comment by jmmv** [comment]
Agreed. Closing in favor of #5588.
