### ISSUE TITLE
appengine_war() fails because it looks for appengine.BUILD in project's workspace

### ISSUE THREAD

**Issue by ahumesky** [bazelbuild/bazel#883]
this looks for the build file in the project's workspace:

```
def appengine_repositories():
  native.new_http_archive(
      name = "com_google_appengine_java",
      ......
      build_file = "tools/build_rules/appengine/appengine.BUILD",
  )
```

```ERROR: /path/to/workspace/package/BUILD:13:1: every rule of type appengine_war implicitly depends upon the target '@com_google_appengine_java//:api', but this target could not be found because of: no such package '@com_google_appengine_java//': In new_http_archive rule //external:com_google_appengine_java the 'build_file' attribute does not specify an existing file (/path/to/workspace/tools/build_rules/appengine/appengine.BUILD does not exist).```

One way to fix this is to use `build_file_content` instead of `build_file`.

**Comment by damienmg** [comment]
We have the issue in many skylark rules, we should indeed use the build_file_content or enable the use of labels for build_file. The later is a bit tricky but I believe we can do it without changing the way we split the WORKSPACE file because the only use case are skylark macros.
