### ISSUE TITLE
incompatible_allow_tags_propagation

### ISSUE THREAD

**Issue by ishikhman** [bazelbuild/bazel#8830]
Tags are not currently being propagated from a bazel's target to the actions' execution requirements. which would be very useful in order to be able to mar certain targets as 'no-remote' or 'no-cache'. At the moment, this is possible only on action/rule level or via adjustments to the rules. 
Detailed description of the issue is in #7766.
Design is described in the [proposal](https://docs.google.com/document/d/1X2GtuuNT6UqYYOK5lJWQEdPjAgsbdB3nFjjmjso-XHo/edit?ts=5ca70ed0#heading=h.5mcn15i0e1ch).

In order to make the transition smoother, a flag `--incompatible_allow_tags_propagation `  has been introduced. 

## What does it change?
* If the flag  `--incompatible_allow_tags_propagation ` set to `true`, bazel will take tags specified on target level, filter them based on **prefix** and propagate to the actions, that are created for the target.
**Propagated prefixes**: "block-", "requires-", "no-", "supports-", "disable-", "local", "cpu:"

* If set to `false` tags are not propagated.

## Migration notes
Check the tags with the prefixes: "block-", "requires-", "no-", "supports-", "disable-", "local", "cpu:". Most likely they were not propagated and with the flag `--incompatible_allow_tags_propagation` they will be, therefore the build behavior might change. 

## Plan 
**By Bazel 1.0:** Make functionality usable
- [x] Starlark rules are able to propagate tags under `--incompatible_allow_tags_propagation ` flag
- [x] Native rules (C++, for example) are able to propagate tags under `--incompatible_allow_tags_propagation ` flag

**After Bazel 1.0:**: Stabilize
- [ ] fix everything that is failing/unstable incrementally
- [ ] move 'tags propagation' from _experimental_ to _supported_ feature

**Comment by laurentlb** [comment]
What's the status of this flag?
If it's ready, add the label `migration-ready` (or `migration-0.x`) and `breaking-change-1.0`.

**Comment by dslomov** [comment]
What is the extent of the breakage? How hard it is to migrate? Do we have tooling available?

**Comment by ishikhman** [comment]
**Before the change**: tags were ignored for starlark rules
**After the change**: tags are propagated for starlark rules
Migration would be needed only for the cases where tags were specified for targets where they are not actually required.

What do you mean by 'tooling'?

**Comment by dslomov** [comment]
> What do you mean by 'tooling'?
> 

Migration tooling (of any kind) - but I do not think it is posisble :)
Breakage does seem non-existent

**Comment by werkt** [comment]
This flag appears to invalidate external repository fetches if only applied to the `build` command, and a `query` is run without it. Given `query`'s behavior, I'm not sure why it's even a valid flag there, but it definitely should not be invalidating things to omit it.

**Comment by keith** [comment]
Fix in this issue https://github.com/bazelbuild/bazel/issues/10961#issuecomment-598844709

**Comment by werkt** [comment]
Regardless of the fix (to move the flag into `common`), it seems invalid that this flag should be available for non-build at all, and since it reflects behavior changes only at execution time, it should not be affecting computation of external repository keying.

**Comment by laurentlb** [comment]
I agree the flag should affect only build, not query.
If someone sends a PR, they can cc me on it.

**Comment by coeuvre** [comment]
Lower the priority to P3 since we currently have no bandwidth.

**Comment by keith** [comment]
What still needs to be done to flip this one? I think it's a common surprise for folks when tags don't propagate as they expect. Based on the comment here https://github.com/bazelbuild/bazel/blob/53f189973e1372d53c7cc2a041a3e34adcff4fbe/src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java#L35-L38 it doesn't seem super clear how we would break apart the `build` vs `query` impact of this flag

**Comment by luxe** [comment]
Should `--experimental_allow_tags_propagation` propagate tag information to **Remote Exec**?  
I see the github issue is tagged  **team-Remote-Exec**, but its not clear if that is the intent of the flag.

From what I can see, the flag only propagates into `execution_requirements` (not the `exec_properties`).  

`exec_properties` are  what become [Platform Properties](https://github.com/bazelbuild/remote-apis/blob/636121a32fa7b9114311374e4786597d8e7a69f3/build/bazel/remote/execution/v2/remote_execution.proto#L649) in REAPI.   
When I dump the `Action` and `Command` proto on the **Remote Exec** side, I see no other data related to having used tag propagation.  

I wonder if [getPlatformProto](https://github.com/bazelbuild/bazel/blob/2edab739e1f61fe8813230b03396ca46f0790089/src/main/java/com/google/devtools/build/lib/analysis/platform/PlatformUtils.java#L65) should be extended to use the `execution_requirements`.  Otherwise, I'm not sure how this information would make it into a **Remote Exec** system.

**Comment by aiuto** [comment]
@katre @gregestren   FYI.

**Comment by katre** [comment]
The separation between exec properties and exec requirements has always been confusing to me. I recently made [a change to that all exec properties become exec requirements, but not vice versa](https://cs.opensource.google/bazel/bazel/+/e4c1c434d49062449c7a83dd753fe01923766b1d). Does it make sense to use exec requirements to populate PlatformProto?

**Comment by fmeum** [comment]
@coeuvre I would see a lot of value in flipping this. It may not even require much effort apart from moving it to the common flags. What do you think?

**Comment by coeuvre** [comment]
SGTM. I would love to see this is flipped.

**Comment by sgowroji** [comment]
All test cases are getting skipped and one fails ```//src/test/shell/bazel:srcs_test```  https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1621#018a159f-e7de-4b84-b1dc-00533b11d231/2174

**Comment by fmeum** [comment]
@meteorcloudy Should we close this issue since the flag has been flipped? Or do we leave it open until the flip has been released?
