### ISSUE TITLE
Bazel integration test not using Bazel HEAD

### ISSUE THREAD

**Issue by rongjiecomputer** [bazelbuild/bazel#8831]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When using older Bazel to run tests under `//src/test/shell/`, test does not use Bazel HEAD but instead uses the main Bazel that is building everything which is not intended.

I tried to repro this in BuildKite, but it seems to work as intended: https://github.com/bazelbuild/bazel/pull/8828 ([log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/1fc5e6b5-c034-47d6-9f8f-ea2fda56b114/src%5Ctest%5Cshell%5Cbazel%5Cbazel_rules_java_test%5Cattempt_1.log)).

Locally, I tried to print `PATH` env var before the test runs the first `bazel build ...`:

`C:/users/jie/github/bazel/src/test/shell/bin:/mingw64/bin:/usr/bin:/c/Users/jie/bin:/bin:.:/mingw64/bin:/usr/bin:/c/bin:/usr/bin:/usr/bin:/c/WINDOWS:/c/WINDOWS/System32:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Users/jie/Tools/bazel:/c/Python36:/c/Mingw64/contain:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Mingw64/bin:/cmd:/c/Users/jie/AppData/Local/Microsoft/WindowsApps`

Note: `/c/Users/jie/Tools/bazel` is where I stored the main Bazel. Bazel Github repo lives in `C:/users/jie/github/bazel`. `C:/users/jie/github/bazel/src/test/shell/bin` is first thing in `PATH`.

I opened my Git bash, manually set `PATH` to the string above and run `which bazel`. Git bash picks `/c/Users/jie/Tools/bazel/bazel`.

If I replaced `C:/users/jie/github/bazel/src/test/shell/bin` with `/c/users/jie/github/bazel/src/test/shell/bin` in PATH (Unix style), Git bash will pick `/c/users/jie/github/bazel/src/test/shell/bin/bazel` (the correct one).

/cc @laszlocsomor

**Comment by laszlocsomor** [comment]
team-Windows for now for triaging, since @rongjiecomputer saw it on Windows

**Comment by rongjiecomputer** [comment]
@laszlocsomor If you can point me to the line of code that prepends `C:/users/jie/github/bazel/src/test/shell/bin` to the `PATH`, I can debug more (feel like this might be specific to my setup). Not urgent.

**Comment by laszlocsomor** [comment]
@rongjiecomputer : https://source.bazel.build/search?q=file:src%2Ftest%2Fshell%20%5CbPATH%3D%20case:yes&ss=bazel

Looks like this line: https://source.bazel.build/bazel/+/master:src/test/shell/testenv.sh;l=78?q=file:src%2Ftest%2Fshell%20%5CbPATH%3D%20case:yes&ss=bazel
