### ISSUE TITLE
Finding a workaround for sandboxing babel

### ISSUE THREAD

**Issue by jacobvoytko** [bazelbuild/bazel#884]
I wrote a Skylark rule for running React.js conversions to feed into the Closure JS rules. It's written in the cheesiest way possible, but I'm the only user, so ¯\_(ツ)_/¯

At its core...
```
  ctx.action(
    inputs=[input],
    outputs=[output],
    command = "babel --no-babelrc --presets /usr/local/lib/node_modules/babel-preset-react %s -o %s" % (input.path, output.path),
    env = {"PATH": "/usr/local/bin:/usr/bin"})
```

It's worked on OSX for a while. Bazel errors when building Golang programs with --cpu=k8 on my Mac, so I load into a Linux VM and run this, and discover that /usr/local is not contained in the sandbox on Linux. [The Bazel sandboxing page](http://bazel.io/blog/2015/09/11/sandboxing.html) invites me to file a bug to resolve this, so here I am!

How do I get around this? Clearly I'm not going to get babel vendored, and I like having all of my builds inside of bazel.

Paths I see...

1. Binding /usr/local in source myself, and maintaining a branch (I'm comfortable modifying Bazel, and I'm going to do this in the short-term just to move forwards).
2. Figure out why linux builds fail for golang on OSX
3. Some clever way of treating babel like a remote executable package

For posterity, the Golang errors cross-building on OSX involve the Go compiler being unable to find the standard library. I'd be happy to file a second bug for this.
```
> bazel build app:go_default_library --cpu=k8
bitbucket.org/reviewninja/reviewninja/app/config.go:4: can't find import: "encoding/json"
```

**Comment by dslomov** [comment]
@philwo, could you take a quick look?

**Comment by philwo** [comment]
I think something like this should work:

Create a file BUILD.usrlocal in your workspace root:
```
filegroup(
    name = "everything",
    srcs = glob(['**']),
    visibility = ["//visibility:public"],
)
```

Create a rule in your WORKSPACE file:
```
new_local_repository(
    name = "usrlocal",
    path = "/usr/local",
    build_file = "BUILD.usrlocal",
)
```

Then add "@usrlocal//:everything" to the inputs of your Skylark action, maybe by making the "everything" filegroup an attribute "_usrlocal" and then adding that to the inputs. For an example, check the Java Skylark rules and search for "_jdk": https://github.com/bazelbuild/bazel/blob/master/tools/build_rules/java_rules_skylark.bzl

I would be interested to hear if that works. I will also prepare a change to make the directories included in the sandbox configurable. This would also solve your problem. :)

**Comment by jacobvoytko** [comment]
I tried this, and it looks like it almost worked! 

```
ERROR: /home/jake/.cache/bazel/_bazel_jake/da01c3df97cdda5beead68065bdca359/external/usrlocal/BUILD:1:1: @usrlocal//:everything: invalid label 'lib/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/library/modules/$.a-function.js' in element 582 of attribute 'srcs' in 'filegroup' rule: invalid target name 'lib/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/library/modules/$.a-function.js': target names may not contain '$'.
```

It looks like it's choking on unsupported characters in node_modules, so it seems I can't restrict it to the directories I want.
