### ISSUE TITLE
Allow WORKSPACE/BUILD to be outside of project

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#8854]
In the Angular ecosystem, we have a CLI tool that hides all the build system details. Today it uses Webpack but with the `@angular/bazel` npm package, we swap it out transparently with Bazel.

This means that users don't author WORKSPACE or BUILD files. The surrounding tooling generates these on the fly.

Today we simulate this by creating the files inside the project, running bazel, then immediately deleting them again. In watch mode, the ibazel process runs for as long as the user hasn't cancelled the `ng serve` command. This means that the WORKSPACE and BUILD files show up in their editor as they're working, even worse they appear as unadded to version control so they get highlighted.

What we really want is some way to run Bazel without having these files in the project directory at all.

/cc @vsavkin

**Comment by alexeagle** [comment]
Maybe https://docs.bazel.build/versions/master/user-manual.html#flag--package_path is related to the solution here.

We also need to have other behaviors like ignoring subdirectories which require files in the project (`.bazelignore`) so we should consider these to be part of the configuration we want to pass in some other way.

**Comment by alexeagle** [comment]
Trying `--package_path` - notes:

Ran 
```
npx @bazel/create repro_bazel_8854
mkdir /tmp/repro_bazel_8854
cd repro_bazel_8854
mv WORKSPACE BUILD.bazel /tmp/repro_bazel_8854
echo "build --package_path=/tmp/repro_bazel_8854" >> .bazelrc
```

I get 
`ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
`
Okay, let's do the bare minimum to satisfy that and move on:

```sh
echo "#Marker for Bazel that this is a Workspace root" > WORKSPACE
```

Try the build again:
```
ERROR: An error occurred during the fetch of repository 'npm':
   Not a regular file: /tmp/repro_bazel_8854/package.json
```
now we have a problem that the repository rule doesn't look in the original directory, it's looking in the `--package_path` for other files like `package.json`. This is a problem - on linux I can symlink some files into the package_path but on Windows we have only directory Junction right now.

Maybe every time Angular CLI runs Bazel it could copy the package.json and lock files, but I'm worried the repository rules can look for other things in the wrong package path.
It also means it defeated the whole point of the managed directories feature - Bazel installs the `node_modules` into the `/tmp` package_path location which means it has a separate copy from the users.

Okay, let's try symlinking those two files to move on
```
alexeagle@alexeagle-glaptop:/tmp/repro_bazel_8854$ ln -s ~/Projects/repro_bazel_8854/yarn.lock yarn.lock
$ ln -s ~/Projects/repro_bazel_8854/package.json package.json
```

Now I can do a basic build.

Let's try a subdirectory:

```
$ mkdir /tmp/repro_bazel_8854/pkg
$ cat > /tmp/repro_bazel_8854/pkg
# paste from https://raw.githubusercontent.com/bazelbuild/rules_nodejs/master/examples/app/styles/BUILD.bazel
$ mkdir pkg
$ cat > pkg/base.less
# paste from https://raw.githubusercontent.com/bazelbuild/rules_nodejs/master/examples/app/styles/base.less
$ cat > pkg/variables.less
# paste from https://raw.githubusercontent.com/bazelbuild/rules_nodejs/master/examples/app/styles/variables.less
```
it fails:
```
$ bazel build pkg:base
INFO: Build option --legacy_external_runfiles has changed, discarding analysis cache.
INFO: Analyzed target //pkg:base (80 packages loaded, 1680 targets configured).
INFO: Found 1 target...
ERROR: missing input file '//pkg:base.less'
ERROR: missing input file '//pkg:variables.less'
ERROR: /tmp/repro_bazel_8854/pkg/BUILD.bazel:3:1: //pkg:base: missing input file '//pkg:base.less'
ERROR: /tmp/repro_bazel_8854/pkg/BUILD.bazel:3:1: //pkg:base: missing input file '//pkg:variables.less'
```

This seems very broken.

**Comment by meteorcloudy** [comment]
I don't think `--package_path` works the way we wanted. If you tell Bazel to look for packages under a certain `package_path`, it will look for both BUILD files and all referenced files in the same directory. It's not possible to use BUILD files under directory B for building files under directory A. Even when they have the same path fragment (eg. `A/foo/bar` and `B/foo/bar`)

**Comment by meteorcloudy** [comment]
I think we'll have to implement new features to support WORKSPACE/BUILD files to be outside of the project.

**Comment by alexeagle** [comment]
Okay then, I've made this P1 to get attention - this is the #1 thing we need to roll out Bazel in the Angular CLI in Q1

**Comment by meteorcloudy** [comment]
I see, I'm doing some experimental to see how hard this is to implement in Bazel.

**Comment by alexeagle** [comment]
Update: we discussed it yesterday and can't think of a good reason why `.gitignore` the WORKSPACE/BUILD files isn't sufficient to patch up the user experience for now.

**Comment by meteorcloudy** [comment]
I'll close this issue now, instead we'll work on https://github.com/bazelbuild/bazel/issues/3885 to ease the trouble of having a WORKSPACE file in Angular CLI users' workspace.
