### ISSUE TITLE
java_test fails with "cannot determine test class"

### ISSUE THREAD

**Issue by carl-mastrangelo** [bazelbuild/bazel#8855]
Description of the problem / feature request:

`java_test` as shown in the [documentation](https://docs.bazel.build/versions/master/be/java.html#java_test) does not figure out which tests to run.    I have a compiling `java_library` that I can confirm does contain a test class:

```python
java_library(
    name = "tests",
    testonly = 1,
    srcs = glob(["src/test/java/io/perfmark/java6/*.java"]),
    deps = [
        ":mark-holder",
        "//impl:generator",
        "//impl:internal-accessor",
        "//impl:mark",
        "//impl:mark-holder",
        "//impl:marker",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "AllTests",
    size = "small",
    runtime_deps = [
        ":tests",
    ],
)
```

Trying to build `AllTests fails:

```
bazel build //java6:AllTests
ERROR: .../perfmark/java6/BUILD.bazel:50:1: in java_test rule //java6:AllTests: cannot determine test class
ERROR: Analysis of target '//java6:AllTests' failed; build aborted: Analysis of target '//java6:AllTests' failed; build aborted
INFO: Elapsed time: 0.110s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

This seems to go against the pattern the documentation shows.  I expected the bazel test runner (suite?) to automatically derive the test classes from the srcs of the library, or from the class files which are annotated `@RunWith`.

 

### What operating system are you running Bazel on?

64 bit Linux

### What's the output of `bazel info release`?

release 0.28.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
git@github.com:carl-mastrangelo/perfmark.git
7036da9ee440c21e1955c88e8a6f5101426f11ab
7036da9ee440c21e1955c88e8a6f5101426f11ab
```

**Comment by iirina** [comment]
You have to specify `test_class` field on `java_test`. From the documentation:
 
> If this argument is omitted, it will be inferred using the target's name and its source-root-relative path.

**Comment by carl-mastrangelo** [comment]
@iirina this is really unfortunate, as it behaves very differently than the internal one.  Won't this result in every bazel project having to re-implement their own test runner?

**Comment by gn-harness** [comment]
I am surprised this was never fixed!
