### ISSUE TITLE
Clean up `@bazel_tools`

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8859]
# Description of the problem / feature request:

This is an umbrella issue to track efforts to clean up `@bazel_tools`. We should remove unnecessary source code from this repo, and make it work for `bazel query @bazel_tools//...`.

## Details

This repo is built into Bazel. It's always available in every workspace. It's a place for commonly used tools like `tools/test/test-setup.sh`, which is the test wrapper used for every `bazel test` action.

But there is also source code in this repo, each file for their own reason. E.g. the runfiles libraries `@bazel_tools//tools/<lang>/runfiles` are included as source so they can be compiled into binaries.

Some source code's purpose in `@bazel_tools` is less obvious. Sometimes they cause problems, like https://github.com/bazelbuild/bazel/issues/8614 whose culprit is https://github.com/bazelbuild/bazel/pull/8742#issuecomment-506745688.

### What's the output of `bazel info release`?

`release 0.28.0`

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
