### ISSUE TITLE
Move dependency `//src/main/cpp/util:filesystem` out of runfiles_test in tools/cpp:

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#8862]
Move dependency `//src/main/cpp/util:filesystem` out of runfiles_test in tools/cpp:
https://github.com/bazelbuild/bazel/blob/8c524dc612fb93da02a23759d393bb55f199a0d7/tools/cpp/runfiles/BUILD#L66

**Comment by laszlocsomor** [comment]
Are there any issues you could reference that motivate this request?

**Comment by oquenchil** [comment]
https://github.com/bazelbuild/bazel/issues/8743
