### ISSUE TITLE
.../android/dexer:AllTests fails on Ubuntu 18.04 with Java11 on RBE

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8863]
On Ubuntu 18.04 with Java 11 I get the following error:
```
testBuildDexArchive(com.google.devtools.build.android.dexer.DexBuilderTest)
java.util.concurrent.ExecutionException: com.android.dx.cf.code.SimException: ERROR in com.google.devtools.build.android.dexer.DexBuilderTest.testBuildDexArchive:()V: invalid opcode ba - invokedynamic requires --min-sdk-version >= 26 (currently 13)
```

https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/ead1e3bd-6770-4661-a2f6-d67f8873d43e/src/test/java/com/google/devtools/build/android/dexer/AllTests/attempt_1.log

I assume it has something to do with Java 11. Any ideas? @jin @ahumesky

**Comment by ahumesky** [comment]
Is this with using java 11 for the host or target? I would think it's target

**Comment by buchgr** [comment]
host and target are identical set to Java 11. Should it work if I switched target to Java 8?

**Comment by ahumesky** [comment]
I see the problem. The test is testing that DexBuilder can dex a jar file, and the jar file that it's testing with is the jar of all the tests themselves. Dex can't handle java 8 feature like invokedynamic, and it seems something has introduced an invokedynamic instruction. There aren't any lambdas in the tests, so I'm not sure where it's coming from.

We can either desugar the input jars, which seems like overkill, or just get some jar that DexBuilder can dex and check it in.

**Comment by ahumesky** [comment]
Actually there's an easier solution, which is to just add `javacopts = ["-source 7 -target 7"]` to the test
