### ISSUE TITLE
Windows: check if cmd.exe AutoRun may cause any problems

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8865]
### Description of the problem / feature request:

`HKCU\Software\Microsoft\Command Processor\AutoRun` defines a command string that cmd.exe runs upon startup.

If Bazel or Starlark rules run `.bat` files or `cmd.exe` commands, those may be affected.

We should check for this error and fix in Bazel.

See https://github.com/tensorflow/tensorflow/issues/30416#issuecomment-510488870

Related: https://github.com/bazelbuild/bazel/issues/2190

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

bazel 0.28.0

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by peakschris** [comment]
We have just hit this, @sgowroji could we reopen this?

**Comment by sgowroji** [comment]
@peakschris  Can you please file a new issue attaching this as reference with complete details.
