### ISSUE TITLE
Move website, docs building and tutorials out of bazel repo.

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#8866]
We should get doc building out of bazelbuild/bazel and moved to bazelbuild/bazel-website. This will decouple non-generated doc changes from Bazel-CI.

it will allow doc changes to github first.
it will make it easier to iterate on docs by decoupling
it will reduce the size of the bazel distribution (both files and dependencies)
Context: #11459 It is taking a ridiculous amount of time to roll back a docs breakage because of full Bazel CI.

**Comment by aiuto** [comment]
Example: https://github.com/bazelbuild/bazel/pull/8853
There is no good reason why I should not be able to just merge that PR

**Comment by aehlig** [comment]
On the other hand, keeping code and documentation in the same
repository makes it easier to keep them in sync. You can see what
the code was, when a particular piece of documentation was added
or modified. Moreover, you can also ask the author of a change to
add the necessay changes to the documentation in the same change.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by aiuto** [comment]
w.r.t. to @aehlig\'s comment, we would still have the generated doc be done in the bazel repo. But do do most code reviews of that stuff we don't need the full web site, we just need a framework that gets the text in a nice placeholder. So, it's not much of a blocker.
