### ISSUE TITLE
Add a new java_common API for exporting transitive dependencies

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#8867]
The new API expresses the use case of packaging together dependencies (exports, deps, runtime_deps) and creating a provider that serve these as transitive dependencies. This use case cannot be achieved with the current java_common APIs.

One important example where this is needed is `scala_import` with no jars. See more details in https://github.com/bazelbuild/rules_scala/pull/781#issuecomment-510448363.

The same API will be needed when migrating `java_import` to Starlark to support the cases where no `jars` are specified (but `exports` is, for example).

**Comment by iirina** [comment]
@hlopko FYI

**Comment by ittaiz** [comment]
Is this still open?

**Comment by hlopko** [comment]
Yup, and I've been trying to find time to work on it for half a year apparently.

**Comment by iirina** [comment]
@ittaiz I'm trying to write a design doc for this API, can you give some more details for the use case of `scala_import` with no jars? I think we discussed this before but I don't remember very well. :)

**Comment by ittaiz** [comment]
Yeah, the use-case is for when you need to export a group of jars.
For example I want to create an indirect target that abstract other internal targets.

**Comment by iirina** [comment]
Thanks! Do you know of any use case where the API needs to group a source jar as well, among the exports, deps, runtime deps? I can't think of any right now, and IMO it doesn't make sense to have a source jar without any output jars.

**Comment by ittaiz** [comment]
I agree. I can’t think of any.
Do you have a need for it internally?

**Comment by iirina** [comment]
No, I was just making sure this is not an use case.

I put everything together [in this doc](https://docs.google.com/document/d/11bS3JhIKAtaccQVhZDL_Sm_jCFTv_GFdqx3Pn-VAEEA/edit#heading=h.5mcn15i0e1ch). Implementation follows soon.

**Comment by ittaiz** [comment]
LGTM, thanks!

**Comment by iirina** [comment]
@ittaiz I implemented this, but didn't submit it yet. I was thinking why one can't use `java_common.merge` in this case, to merge in all dependencies. I can't think of a good reason, maybe something skips my mind.

I tried to following case:

```
java_binary(
  name = 'HelloBinary',
  srcs = ['HelloBinary.java'],
  deps = [':export_deps'],
)

my_export_rule(
  name = 'export_deps',
  deps = [':hello_library_interm'],
)

java_library(
  name = 'hello_library_interm',
  srcs = ['HelloLibraryInterm.java'],
  exports = [':hello_library'],
)

java_library(
  name = 'hello_library',
  srcs = ['HelloLibrary.java'],
)
```

Where `HelloBinary` calls `HelloLibrary.funcHelloLibrary()`, using strict java deps, and the build was successful.

`my_export` uses `java_common.merge`:

```
def _impl(ctx):
  return [java_common.merge([dep[JavaInfo] for dep in ctx.attr.deps])]
```
