### ISSUE TITLE
androidndk doesn't register toolchains

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel#8871]
### Description of the problem / feature request:

`@androidndk` toolchains/compiler are not registered, and thus skipped from toolchain resolution.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone https://github.com/steeve/rules_go_bazel_toolchains and run following command
```
$ bazel build --config=android_arm64 //:main_cc
```

When removing the `--platforms` from the bazelrc (thus removing constraints), the build succeeds.

### What operating system are you running Bazel on?

macos

### What's the output of `bazel info release`?

`release 0.28.0`

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/rules_go/issues/2089#issuecomment-510668841

### Any other information, logs, or outputs that you want to share?

All is at https://github.com/bazelbuild/rules_go/issues/2089#issuecomment-510663447

**Comment by steeve** [comment]
I got it to work by adding the following in a custom build file:
```
toolchain(
    name = "android",
    exec_compatible_with = [
        "@bazel_tools//platforms:osx",
        "@bazel_tools//platforms:x86_64",
    ],
    target_compatible_with = [
        "@bazel_tools//platforms:android",
        "@bazel_tools//platforms:aarch64",
    ],
    toolchain = "@androidndk//:aarch64-linux-android-clang7.0.2-libcpp",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)
```

**Comment by ahumesky** [comment]
The work to migrate the Android NDK rule to toolchains / platforms is ongoing. It may not happen for the native version of `android_ndk_repository` but will happen for the Starlark version.

**Comment by steeve** [comment]
@ahumesky the problem though is that crosstool_top is ignored when platforms are used it seems (in this case the platform is constraining on `android` and `aarch64`).

**Comment by jin** [comment]
I took a stab at this: https://github.com/bazelbuild/bazel/pull/8918
