### ISSUE TITLE
Desugaring java8 APIs fails (on linux, but not MacOS) 

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#8872]
### Description of the problem / feature request: 

When building with `bazel-0.28.0-linux-x86_64` (also 0.27.1) and while using `--experimental_desugar_java8_libs`, the desugaring step for the jar from `com.android.support:collections:28.0.0` fails with the following:

```
[2019-07-11 21:59:29] ERROR: /data/app/kochiku-worker/.cache/bazel/_bazel_kochiku-worker/a138fc95459b1e4b372379097726419d/external/maven/com/android/support/BUILD.bazel:46:1: Desugaring external/com_android_support_collections/maven/com/android/support/collections/28.0.0/collections-28.0.0.jar for Android failed (Exit 1)
[2019-07-11 21:59:29] --desugar_supported_core_libs requires specifying renamed and/or emulated core librariesTarget //apps/my-app:my-app failed to build
```

This works perfectly fine using 0.28.0 (or 0.27.1) on my Mac OS desktop.  This only fails in our linux CI cluster (which version-pins bazel with the repository)  

> Note: This is a serious concern as `com.android.support:collections:28.0.0` is a standard upstream dependency of quite a few of the android support libraries, which means that that, plus AndroidX assume de-sugaring of APIs as a part of the build process. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unclear - it is consistently breaking with any usage of a jar/aar containing Java8 APIs which need desugaring. 

### What operating system are you running Bazel on?

Centos 7 x86_64

### What's the output of `bazel info release`?

0.28.0

###  Have you found anything relevant by searching the web?

I've found only the code where the error is thrown, but nothing about specific versions failing, or particular OSs. 

### Any other information, logs, or outputs that you want to share?

No, but I'll update the bug as I investigate further.

**Comment by cgruber** [comment]
Subsequent builds result in different .jar desugaring attempts being attempted first and reported, e.g.:

```
[2019-07-11 22:18:58] ERROR: /data/app/kochiku-worker/.cache/bazel/_bazel_kochiku-worker/a138fc95459b1e4b372379097726419d/external/maven/org/jetbrains/kotlinx/BUILD.bazel:22:1: Desugaring external/org_jetbrains_kotlinx_kotlinx_coroutines_core_common/maven/org/jetbrains/kotlinx/kotlinx-coroutines-core-common/1.1.1/kotlinx-coroutines-core-common-1.1.1.jar for Android failed (Exit 1)
[2019-07-11 22:18:59] --desugar_supported_core_libs requires specifying renamed and/or emulated core librariesTarget //apps/my-app:my-app failed to build
```

But I can't get any additional information, `--verbose_failures` doesn't show me any command-lines, or any other information than posted above. I know with 0.27.1 the error seems to be posted by the worker into stdout, breaking the worker protocol, so the error is a bit more verbose - but basically is just a stack trace containing the trace up to the validation step where that above-mentioned error is thrown.  This seems to mean that the list of APIs to rename or emulate is not being given in these builds, and the tool is failing, but that's not under my control as a user - I just put that experimental flag in and bazel takes care of the rest.

**Comment by cgruber** [comment]
Also note, this did not occur in `0.26.1`

**Comment by laurentlb** [comment]
@ahumesky
It looks like a regression, but only with an experimental flag. Alex, do you think this is release-critical?

**Comment by cgruber** [comment]
Well it's certainly a migration blocker for us - and for anyone using a modern version of a standard android support library, which requires it or breaks. And since our CI is on linux, we're basically blocked from upgrading bazel until this is fixed.  Please triage appropriately. :)

**Comment by cgruber** [comment]
Note - it also happens for from-source compilation, it just happens to hit earlier on maven-supplied jars.

**Comment by cgruber** [comment]
Put another way, the flag may be experimental, but Android support libraries ships using Java8 APIs and expects desugaring. That's more the issue. Not really bazel's fault, but it's a non-optional flag, despite being formally experimental.

(feels like a variant of Hyrum's Law is in play)

**Comment by ahumesky** [comment]
While we're looking into this, note that core library desugaring is a bazel-only feature right now, so nothing in the support libraries should depend on core library desugaring. They'll need "plain" desugaring though, which as far as I know should still be working.

**Comment by cgruber** [comment]
That sure confuses me then, because when I turn it off, com.android.support:collections:28.0.0 fails to be processed because of a java8 api. :/

**Comment by cgruber** [comment]
I'll need to re-examine that.  If core library is a bazel-only thing, then I'm not sure why I ever needed to turn it on, since we're a gradle shop for the moment (until this migration is done), yet I got these errors that were fixed by turning on core libraries desugaring.  Hmm.

**Comment by ahumesky** [comment]
What errors were you getting without `--experimental_desugar_java8_libs`?

**Comment by ahumesky** [comment]
This may have something to do with enabling persistent workers for the desugar action ([here](https://github.com/bazelbuild/bazel/pull/8343), @jin), because I don't get that error when I disable persistent workers with `--strategy=Desugar=sandboxed`

**Comment by ahumesky** [comment]
But something else seems to be broken, at least with my test setup, because it fails when trying to use a java 8 lib:

```
java/bazel/MainActivity.java:16: error: package java.time does not exist
import java.time.Clock;
                ^
java/bazel/MainActivity.java:28: error: cannot find symbol
    Log.i("Clock: " + Clock.class);
                      ^
  symbol:   class Clock
  location: class MainActivity
```

**Comment by cgruber** [comment]
Hmm. I'll try to figure out the error I got before. I'll also try it all out without the worker and report back. Working on something else ATM but I'll try to get feedback in today or tomorrow on this thread.

**Comment by cgruber** [comment]
I have been all around this issue, and I have too many simultaneous changes happening, because of minor incompatibilities between 0.26.1 and 0.28, and the various things I'm doing to bring everything in the ecosystem into synchronicity, and I am having some issues isolating the issue. When I try to run the whole project without desugaring libs, though, now,  using 0.28.0, I end up with an error accessing a static method on an interface (which I would think is a language feature, not a library). 

It definitely does work if I use "standalone" strategy for the desugaring thing, though, so I do suspect there's something about the persistent worker on linux.

Given that i can workaround with `--strategy` I'd say this isn't a blocker, though it would be good to figure that out.

**Comment by senpo** [comment]
For some reasons, this also happens to my setup: bazel-2.0.0 on mac. Adding "--strategy=Desugar=sandboxed" does help fix the compile error.

**Comment by Kernald** [comment]
This is still an issue in 3.7.1 (at least on Linux).
