### ISSUE TITLE
Bazel 0.28.0: find: ‘src/tools/xcode-common/java/com/google/devtools/build/xcode/common’: No such file or directory

### ISSUE THREAD

**Issue by jiapei100** [bazelbuild/bazel#8874]
Trying to build the **NEWEST** release.

```
🍃  Building Bazel from scratch..find: ‘src/tools/xcode-common/java/com/google/devtools/build/xcode/common’: No such file or directory
find: ‘src/tools/xcode-common/java/com/google/devtools/build/xcode/util’: No such file or directory
....
🍃  Building Bazel with Bazel.
.WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/tmp/bazel_KyUGgKsa/archive/libblaze.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
DEBUG: /tmp/bazel_KyUGgKsa/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/bazel_KyUGgKsa/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.
...
```

Failed to build with
```
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
---8<---8<--- End of exception details ---8<---8<---

---8<---8<--- Start of log ---8<---8<---
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 117440512 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/bazel_KyUGgKsa/out/execroot/io_bazel/hs_err_pid29067.log
 the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 117440512 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/bazel_KyUGgKsa/out/execroot/io_bazel/hs_err_pid29067.log
---8<---8<--- End of log ---8<---8<---
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 1587.237s, Critical Path: 195.45s
INFO: 1418 processes: 1344 local, 74 worker.
FAILED: Build did NOT complete successfully

ERROR: Could not build Bazel
```

**Comment by laurentlb** [comment]
Did this work with Bazel 0.27?

**Comment by clnperez** [comment]
i'm hitting this as well on both versions 0.28.1 and 0.27.2. i'm building on ppc64le

**Comment by clnperez** [comment]
it looks like xcode-common is gone as of https://github.com/bazelbuild/bazel/commit/32246b2b604f317ef84c70392e935f63f6979909 

so i modified: https://github.com/bazelbuild/bazel/blob/0.28.1/scripts/bootstrap/compile.sh#L47

 `DIRS=$(echo src/{java_tools/singlejar/java/com/google/devtools/build/zip,main/java} tools/java/runfiles third_party/java/dd_plist/java ${OUTPUT_DIR}/src)`

**Comment by mdasari823** [comment]
I am getting same error.

`🍃  Building Bazel from scratch..find: ‘src/tools/xcode-common/java/com/google/devtools/build/xcode/common’: No such file or directory
find: ‘src/tools/xcode-common/java/com/google/devtools/build/xcode/util’: No such file or directory
....
🍃  Building Bazel with Bazel.
.WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
DEBUG: /tmp/bazel_61welBUv/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/bazel_61welBUv/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.
ERROR: /tmp/bazel_61welBUv/out/external/bazel_tools/tools/jdk/BUILD:499:14: Configurable attribute "actual" doesn't match this configuration: Could not find a JDK for host execution environment, please explicitly provide one using `--host_javabase.`
INFO: Call stack for the definition of repository 'remote_java_tools_linux' which is a http_archive (rule definition at /tmp/bazel_61welBUv/out/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /DEFAULT.WORKSPACE.SUFFIX:229:1
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: 

/tmp/bazel_61welBUv/out/external/bazel_tools/tools/jdk/BUILD:499:14: Configurable attribute "actual" doesn't match this configuration: Could not find a JDK for host execution environment, please explicitly provide one using `--host_javabase.`
INFO: Elapsed time: 12.311s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (92 packages loaded, 1172 targets \
configured)

ERROR: Could not build Bazel`

**Comment by sergiocampama** [comment]
That's a different error: `Could not find a JDK for host execution environment, please explicitly provide one using --host_javabase`

The xcode path one is just a warning.

**Comment by mdasari823** [comment]
Aah, sorry. Thanks for pointing it out. It works well when I give the JDK execution environment explicitly using `env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh`
