### ISSUE TITLE
How to integrate existing Makefile-style repo into bazel-style repo?

### ISSUE THREAD

**Issue by Traeyee** [bazelbuild/bazel#8883]
Now my company is starting to use bazel to build c++ projects. At the beginning, we rewrite BUILD by hands to integrate some Makefile-style like thrift, rapidjson, etc. But gradually we integrate more and more thirdparty repo, so we try to find out a way to use the existing build tools. For example, is there a rule that can let me run cmd 'make' then it can generate some libraries, and other targets can depend on them?

**Comment by Globegitter** [comment]
Not sure if that helps but have you seen https://github.com/bazelbuild/rules_foreign_cc

**Comment by Traeyee** [comment]
> Not sure if that helps but have you seen https://github.com/bazelbuild/rules_foreign_cc

Oh, I love it, thx

**Comment by scentini** [comment]
Assuming https://github.com/bazelbuild/rules_foreign_cc was the answer you were looking for. Please reopen the issue if that's not the case.
