### ISSUE TITLE
Force loading the Protobuf rules from the rules_proto repo

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazel#8891]
This big breaking change will force users of the Protobuf rules to use the Starlark rules from the [@rules_proto](https://github.com/bazelbuild/rules_proto) repository. The rules there are currently only wrappers around native rules, but they will be rewritten in the future.

Design doc: https://docs.google.com/document/d/1Wai_okIK_NnhNJZai5nkTUvZVHdV5pp1YwNLFtWwpC4/edit?ts=5d2c8077

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
