### ISSUE TITLE
Modify scheduler to take action type into acount

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#8895]
So the problem I am trying to solve is that on the Mac we have certain types of compile actions (notable xcasset compiles) that can take a very long time and have a lot of inputs. They must be run before packaging of the application can occur. The only actions that depends on the asset compiles is the packaging.

So what I think I would like is for asset compiles to be run as early in the build process as possible to attempt to make sure that they don't end up being the long pole before packaging occurs. I have seen several full builds where the delta in build times from one build to the next has been directly impacted by where the asset compile has ended up in the build.

A more general solution to this problem would be to allow actions to specify an educated estimate at the "size" of the action, and have the scheduler push to have these actions executed earlier.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
