### ISSUE TITLE
Ban "--platforms" from config_setting 

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#8896]
### Description of the problem / feature request:

Spawned from this comment thread: https://docs.google.com/a/google.com/document/d/1UZaVcL08wePB41ATZHcxQV4Pu1YfA1RvvWm8FbZHuW8/edit?disco=AAAADQko1J8

We want to discourage `select()`ing on platforms, in preference for `constraint_setting`s. In other words, it's far preferable to have:

```
config_setting(
    ...,
    constraint_values = ["@platforms//os:linux"])
```

than separate `config_setting`s for every specific Linux-based platform definition.

### Feature requests: what underlying problem are you trying to solve with this feature?

Sane, maintainable, generic multi-platform support.

More rationale: https://github.com/hlopko/bazel_platforms_examples/blob/4019120264181e491bc148a5e874e1de55b01f58/examples/05_select_on_platform/README.md

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/8583 - would allow embedding this directly in `select` (no need for an intermediate `config_setting`)

**Comment by gregestren** [comment]
@katre , @hlopko , @aragos  for input. I'm happy to implement if it makes sense.

We could take this even farther and ban everything in [PlatformOptions](https://github.com/bazelbuild/bazel/blob/6a17989e0b53c722cce1c62fdc83bb2261b36188/src/main/java/com/google/devtools/build/lib/analysis/PlatformOptions.java).

This is also an opportunity to conservatively roll out platform support + best practices, then relax these restrictions only when/if we see clear need to.

**Comment by gregestren** [comment]
Also comment from @katre on the original thread:

> It would be nice to either forbid it, or at least show an error saying something like "This doesn't work like you think it does". Maybe a similar error for "--host_cpu" and other host flags would also be useful?

**Comment by katre** [comment]
I like the concept. Ideally it'd be more flexible than just a blacklist in config_setting: possibly a new setting/metadata on individual flags?

**Comment by c-parsons** [comment]
> I like the concept. Ideally it'd be more flexible than just a blacklist in config_setting: possibly a new setting/metadata on individual flags?

+1

I've also had this thought with respect to flags labeled "experimental".

**Comment by gregestren** [comment]
Looks like we already have

> I like the concept. Ideally it'd be more flexible than just a blacklist in config_setting: possibly a new setting/metadata on individual flags?

Looks like we already have precedent: https://github.com/bazelbuild/bazel/blob/4760cc3c0f7467cb199adad8599fa297ffc2c883/src/main/java/com/google/devtools/build/lib/analysis/config/FragmentOptions.java#L117-L136

**Comment by gregestren** [comment]
While there's a broader theme this highlights, this bug should remain focused specifically on `--platforms`, as that has its own, and wide-ranging, reasons for exclusion. And it's a smaller practical scope.

I'm going to close this since there's no urgency for this yet and I don't think that's happening soon. We can re-open when/if we sense this is truly something to worry about.
