### ISSUE TITLE
support run command for experimental_remote_download_outputs

### ISSUE THREAD

**Issue by phb** [bazelbuild/bazel#8899]
### Description of the problem / feature request:

experimental_remote_download_outputs does not properly download all runtime dependencies.

### Feature requests: what underlying problem are you trying to solve with this feature?
Attempting to use the new remote builds without the bytes (#6862)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
https://github.com/phb/bazel_minimal_missingrunfiles
and specifically see 
https://github.com/phb/bazel_minimal_missingrunfiles/blob/master/EXAMPLE_OUTPUT

### What operating system are you running Bazel on?

macosx.

### What's the output of `bazel info release`?

Tried various versions including latest HEAD as of today.

This was initially reported in #6862 and split into it's own ticket. CC @buchgr

**Comment by buchgr** [comment]
Thanks for filing the issue. I see what you mean now. You are indeed correct the run command is not supported (yet).

**Comment by phb** [comment]
Hi @buchgr,

I just wanted to give a quick ping on this issue. Can you think of any workaround? We have a deploy target that we generally run from our CI, but we are unable to run it without turning off minimal downloads and trigger a full rebuild.

**Comment by buchgr** [comment]
I wrote a patch that should make it work. Can you give it a try please: https://github.com/bazelbuild/bazel/pull/9298?
