### ISSUE TITLE
`bazel query --output=location` does not print source file paths

### ISSUE THREAD

**Issue by wchargin** [bazelbuild/bazel#8900]
### Description of the problem / feature request:

The [docs for `--output=location`][docs] say:

> For source files, the location of line 1 of the actual file is printed.

This is what I want, but it is not what happens: instead, what is
printed is the location of a reference to the source file from a BUILD
file. There appears to be no way to actually turn a label for a source
file into that source file’s path on disk.

[docs]: https://docs.bazel.build/versions/master/query.html#output-location

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ cd "$(mktemp -d)"
$ >WORKSPACE
$ >BUILD <<EOF cat
> py_binary(
>   name = "main",
>   srcs = ["main.py"],
> )
> EOF
$ >main.py
$ bazel query //:main.py --output=location 2>/dev/null
/tmp/tmp.97B2nY3jsI/BUILD:3:10: source file //:main.py
```

Not even `--output=proto` includes the promised information:

```
$ bazel query //:main.py --output=proto | strings
//:main.py
/tmp/tmp.97B2nY3jsI/BUILD:3:10*
```

### What operating system are you running Bazel on?

gLinux (like Debian)

### What's the output of `bazel info release`?

release 0.28.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Nope.

### Any other information, logs, or outputs that you want to share?

Nope.

**Comment by jin** [comment]
@janakdr could you please assign a priority level for triaged issues, please?

**Comment by zhengwei143** [comment]
This issue will be resolved with https://github.com/bazelbuild/bazel/issues/12322.

**Comment by zhengwei143** [comment]
We are re-thinking the changes that fixed this issue and are considering changing the documentation to match this behaviour instead. 

But first we would like to check whether this would be a big issue with you (that it will continue to print the location of the source file within the BUILD file instead)?

**Comment by wchargin** [comment]
It would certainly be inconvenient. This issue has 6 upvotes (not
including me), which puts it in the top 3.5% of open issues sorted by
vote count.

Finding the source file on disk is often useful, but I’ve never wanted
this to produce a location in a BUILD file (the bad behavior).
If I wanted that, I’d look at `same_pkg_direct_rdeps` or something.

**Comment by zhengwei143** [comment]
Thanks for the input, we have also decided internally to carry on with this change.
