### ISSUE TITLE
filegroups destroy providers

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#8904]
If you wrap a filegroup() rule around a target with a provider, the providers are lost. This is inconvenient, and does not appear to be strictly necessary.

Given something like this:

rule_with_provider(name = "foo", ...)
filegroup(name = "foos", srcs = [":foo"])
rule_consuming_provider(..., deps = [":foos"])

It would be convenient if this worked, and I can't see any apparent reason why this is impossible, it's just not how filegroups work today.

This scenario is obviously a little more interesting:

rule_with_provider(name = "foo1", ...)
rule_with_provider(name = "foo2", ...)
filegroup(name = "foos", srcs = [":foo1", ":foo2"])
rule_consuming_provider(..., deps = [":foos"])

However, there is a single obvious interpretation in the implementation of rule_consuming_provider, since ctx.attr.deps will expand to a list of files, each of which has its own provider field.

Can we make this work?

**Comment by iirina** [comment]
Can you give some details about specific use cases where this would be useful? What is the purpose of the intermediate filegroup? You can collect the providers using aspects propagated from the filegroups.

**Comment by asuffield** [comment]
The intermediate filegroup is there to give a single name (and typically, visibility) to the targets - this pattern typically occurs on interface boundaries, where many users want to depend on a thing, and the providers of the thing want to change the set of targets it includes.

I suppose aspects would work as a different approach - it's quite a bit more work to write, but should be functional.

**Comment by iirina** [comment]
Thanks for the explanatios @asuffield. Another way to go is to implement your own filegroup rule in Starlark and only propagate the providers of interest. This is a bit more work, but you can control what gets propagated. It wouldn't scale well for filegroup to identify and propagate all providers of dependencies.

**Comment by asuffield** [comment]
Yes, I'm currently using that as a workaround, but it's quite verbose. 

It's not clear to me why filegroup would hit a scaling problem here - it should scale linearly with its input, as each file produced by the filegroup would have the same set of providers as its source file. Is that not strictly equal in size?

**Comment by dslomov** [comment]
I do not think there is any good semantics we can assign to this. In your example,
```
rule_with_provider(name = "foo1", ...)
rule_with_provider(name = "foo2", ...)
filegroup(name = "foos", srcs = [":foo1", ":foo2"])
```
there can only be one provider of a given type returned by a `filegroup` rule and there is no generic way to merge multiple providers into one - basically there is just no good semantics for that.

**Comment by sfreilich** [comment]
I feel like this thread doesn't explain the problem with the original suggestion adequately because it's swallowing the assumption that `filegroup` is an alias for one or more targets. It's not. `filegroup` provides files, it's not suitable for use in `label_list` attributes that don't set `allow_files`.

"Implement your own filegroup" is sort of a solution for this, but generally language-specific rules should handle encapsulating and forwarding dependencies by themselves. That is, it's not for example:

```
py_library(
    name = "a",
    ...
)

py_library(
    name = "b",
    ...
)

filegroup_forwarding_pyinfo(
    name = "interface",
    srcs = [
        ":a",
        ":b",
    ],
    visibility = ["//visibility:public"],
)
```

It's just:

```
py_library(
    name = "interface",
    deps = [
        ":a",
        ":b",
    ],
    visibility = ["//visibility:public"],
)
```
