### ISSUE TITLE
Can't upgrade to 0.24.1

### ISSUE THREAD

**Issue by yunoJ** [bazelbuild/bazel#8906]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I can't upgrade to 0.24.1

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```sudo apt-get install --only-upgrade bazel```

### What operating system are you running Bazel on?

ubuntu 18.04

### What's the output of `bazel info release`?

release 0.18.1

###  Have you found anything relevant by searching the web?

https://docs.bazel.build/versions/master/install-ubuntu.html
https://github.com/bazelbuild/bazel/issues/5714

### Any other information, logs, or outputs that you want to share?

It seems that I have bazel 0.18.1 installed on my gpu but when I try to upgrade it, 
```Skipping bazel, it is not installed and only upgrades are requested.```
message pops up. 

Will appreciate any help, thanks.

**Comment by dslomov** [comment]
What are your repositories for `apt-get`? Be aware that Bazel is not in Debian nor in Ubuntu.

**Comment by yunoJ** [comment]
Looks like Bazel is not included in the repository as you mentioned. Should I do apt-add?

**Comment by philwo** [comment]
> It seems that I have bazel 0.18.1 installed on my gpu

What do you mean with "gpu"? Please provide more information about your system - what kind of machine is this, if it's a VM, then which image are you running and how come that there's software installed that you don't know about (like Bazel)?

Unless I'm missing something, the error message tells you that you didn't install Bazel 0.18.1 via apt-get, so you can't upgrade Bazel using apt-get. Maybe whoever prepared the machine you're working on simply downloaded a Bazel 0.18.1 binary and put it into `/usr/local/bin/bazel`. That's a totally valid way of installing Bazel.

If you want to check, this should tell you whether Bazel comes from apt-get: `apt list -a bazel`. If it doesn't show anything, then Bazel wasn't installed via apt-get on your system.

Also note that our apt-get repository doesn't currently provide older versions, so you wouldn't be able to install exactly Bazel 0.24.1 using apt-get anyway.

I would recommend to just download the Bazel version that you need from here: https://github.com/bazelbuild/bazel/releases/tag/0.24.1, put it somewhere (maybe on your PATH) and call it explicitly.

Optionally, you could remove the old Bazel binary installed on your system.

Hope this helps!

**Comment by yunoJ** [comment]
By gpu I'm using Quadro GV100. It's not a VM and I'm using tiny imagenet data. I'm sharing this machine with a friend and maybe he downloaded it way back. 
Well I checked ```apt list -a bazel``` and got 0.28.1. I then downloaded 0.24.1 from github and ```bazel info release`` now sasy 0.24.1. Thanks for the answer! I'm worried that might 0.28.1 and 0.24.1 might collide though.

**Comment by philwo** [comment]
Hi @yunoJ - I see :) No problem! Glad that you could figure it out.

You can download and use as many Bazel versions in parallel as you like - they all use their own separate installation directories and will not conflict with each other. Even if you use multiple versions of Bazel in the same workspace, it should be safe and Bazel will figure it out, but if you ever run into issues, a `bazel clean --expunge` should definitely fix it! :)

**Comment by yunoJ** [comment]
Oh okay! Will close the issue thanks to @philwo
