### ISSUE TITLE
Publish documentation for @bazel_tools//tools/build_defs/repo:jvm.bzl

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#8908]
Documenation for [`jvm_import_external` and friends](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/jvm.bzl) is not fully present, nor it is published.

`jvm_import_external` is a more direct replacement for `maven_jar`, so we should add that, and also recommend it in the [maven_jar docs](https://docs.bazel.build/versions/master/be/workspace.html#maven_jar)

**Comment by dslomov** [comment]
cc @laurentlb @jin @aehlig

**Comment by jin** [comment]
I'm working on a plan to unify `jvm_import_external` with `rules_jvm_external`, while turning down `maven_jar` and `maven_server`. Docs for `jvm_import_external` will fall out of that naturally, but we should be careful about the messaging for users to interoperate usage between `jvm_import_external` and `rules_jvm_external`.

**Comment by dslomov** [comment]
What is the planned state for 1.0?
https://github.com/bazelbuild/bazel/issues/6799 recommends `jvm_maven_import_external` as a replacement, so we should at least document it.
