### ISSUE TITLE
bazel can't rebuild tensorflow when I modify C++ header file(like *.h)

### ISSUE THREAD

**Issue by fengyuICT** [bazelbuild/bazel#8913]
bazel version: 0.16.1  and 0.21.0
If I Modify C++ header file that like op_kernel.h in tensorflow source code, and I use the same command to compile it. However, bazel can't recognize that I was changing some code in header file, and bazel output is just " Build completed successfully".

**Comment by fengyuICT** [comment]
Is anyone have some advice? the solution I used currently is delete all bazel-out files, and rebuild it from scratch, but it take lots of time(30min~).

**Comment by scentini** [comment]
Hi @fengyuICT, can you try a more recent Bazel version?
Can you also provide a minimal repro?

**Comment by fengyuICT** [comment]
yes, you can try the demo:
build tensorflow-r1.10 from scratch(git clone tensorflow, and build it according to the website), use cudnn(cuda-9.0/cudnn7) or mkl-dnn, bazel-0.21.0.
then try to modify the header file, such as tensorflow/stream_executor/dnn.h
class AlgorithmConfig {
    AlgorithmDesc algorithm() const { **std::cout << algorithm_ << std::endl;** return algorithm_; }
}
then rebuild tensorflow, you can see the bazel does not recognize the dnn.h is changed and bazel just print some sentence like that "Build completed successfully".

**Comment by oquenchil** [comment]
Please re-open if this is still a problem.
