### ISSUE TITLE
JavaInfo#runtime_output_jars not containing all the expected jars

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#8916]
### Description of the problem / feature request:
JavaInfo#runtime_output_jars not containing all the expected jars
See this [PR](https://github.com/bazelbuild/rules_scala/pull/785) for repro.
cc @iirina

**Comment by ittaiz** [comment]
@iirina any updates?

**Comment by iirina** [comment]
Not yet. I'm still trying to finish the .java -> JavaInfo migration. I'll post more updates.
