### ISSUE TITLE
Recursion check triggers for higher-order utility functions like partial.call

### ISSUE THREAD

**Issue by Bocete** [bazelbuild/bazel#8921]
### Description of the problem / feature request:

The ["Recursion was detected" exception](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/syntax/UserDefinedFunction.java#L63) is fired by a nested invocation of [`partial.call`](https://github.com/bazelbuild/bazel-skylib/blob/master/lib/partial.bzl#L22) even if there's no recursion between the two partially invoked functions. The recursion comes from `partial.call` calling itself.

I understand why this is happening right now. However, semantically, `partial.call` is no more than a function calling meta-method. If possible, it shouldn't be treated differently than routines that invoke functions in Bazel's own code.

One possible way to fix it would be to have `partial.call` contribute to loop detection by looking if its `partial` argument appeared in the stack trace, not if it was invoked again itself. I understand that this wouldn't be sound in case a different function object is generated for each iteration, so there could be better solutions out there. There's also the issue of special-casing what should be a vanilla library method.

### Feature requests: what underlying problem are you trying to solve with this feature?

Let one nest partial function calls while still avoiding loops. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
load(
    "@bazel_skylib//lib:partial.bzl",
    "partial",
)

def _a():
  # pass

a = partial.make(a)

def _b():
  partial.call(a)

b = partial.make(_b)

# Here's the problem
partial.call(b)
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

I'm using the latest Google distro of Bazel.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No specific mention of this issue, but I did track my error down to Bazel code linked in the issue.

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by brandjon** [comment]
This is probably the single most compelling case for allowing recursion in Starlark.

At the same time, the strongest argument against allowing recursion in Starlark is that, in Bazel, people could use it to implement hierarchical traversals over provider structures rather than returning flat providers of depsets.
