### ISSUE TITLE
Files in transitive_sources should implicitly be added to runfiles

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8927]
In the `py_library` rule, files that appear in `srcs` are added both to the target's `PyInfo.transitive_sources` field and to its runfiles. The latter is important so that the source file is available to the downstream `py_binary` at execution time, so it can be imported.

When you define a Starlark rule that acts like `py_library`, it is possible to add files to `transitive_sources` without adding them to runfiles (via `DefaultInfo`). `py_binary` does not add these to runfiles itself, so it ends up not being able to import them.

One possible resolution is to just add the transitive sources to runfiles at the `py_binary`. But it's still debatable whether they should've been added to runfiles back in the original library-like Starlark rule. If so, then adding them in the `py_binary` helps to mask a bug that becomes apparent only when another kind of rule besides `py_binary` depends on the library-like rule.

It's also conceivable that a rule besides `py_binary` could want to distinguish between sources and other kinds of runfiles. For instance, the rule could embed the source files (but not other runfiles) in some kind of archive. In that case, it's advantageous to not automatically add sources to runfiles.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
