### ISSUE TITLE
Cannot run bazel test subsequently: missing input file from bazel-out/scala.runfiles

### ISSUE THREAD

**Issue by jakepgoldman** [bazelbuild/bazel#8928]
### Description of the problem / feature request:

I am currently running bazel test (using scala_test) on a number of end to end test modules in my repo. In order for the tests to execute correctly, I am injecting most of the repo into the testing workspace (as a data dependency for scala_test) using a filegroup target. My scala_test target also uses the tags=["test_runner", "no-sandbox"]. 

Each time I execute the tests, they run smoothly and pass. However, if I run the bazel test command again, bazel always returns a missing input file error pertaining to some file that is part of scala.runfiles or bazel-out. These are the most common output messages that I am getting: 

missing input file '//:bazel-out/_tmp/action_outs/stderr-497'
missing input file '//:bazel-bin/.../src/test/scala/lsqa/scala.runfiles_manifest'
missing input file '//:bazel-out/darwin-fastbuild/bin/.../src/test/scala/lsqa/scala.runfiles/MANIFEST

I am able to fix the issue by running 'bazel clean --expunge' after each time I execute the tests, but doing this defeats the benefits of bazel.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Using a scala_test target with tags=["test_runner", "no-sandbox"], and necessary srcs, data, runtime_deps and deps. 

I am running the test using the command: bazel test target --test_output=streamed  --test_env TEST_WORKSPACE=blah/blah --test_env TZ=EDT  (*** I also include a few other --test_env variables for specific use cases within our E2E tests)

Unfortunately, I don't have a minimal example to share. 

### What operating system are you running Bazel on?

I work within a nix shell and have a Unix machine. 

### What's the output of `bazel info release`?

release 0.27.1

**Comment by iirina** [comment]
Looks more like an issue with https://github.com/bazelbuild/rules_scala to me. Can you open an issue with them? We can look more into it if the rules_scala owners don't think it's a problem with the rules.
