### ISSUE TITLE
feature request: A mode for --experimental_remote_download_outputs to download testlogs only

### ISSUE THREAD

**Issue by lizan** [bazelbuild/bazel#8934]
### Feature requests: what underlying problem are you trying to solve with this feature?

While setting up Bazel RBE with Envoy CI, we want the CI download less artifacts from RBE to save network bandwidth and disk, while we want to be able to inspect testlogs individually.

Currently the setup is --test_output=all and --experimental_remote_download_outputs=minimal so all test outputs are printed to console, the test log are already downloaded but not write to the disk, it would be nice bazel-testlogs is set up, and better with test.xml, so CI system can interpret them.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

`release 0.28.0`

**Comment by buchgr** [comment]
have you tried `--experimental_remote_download_outputs=toplevel`. I believe this does what you want :).  Please re-open this bug if it doesn't.

**Comment by lizan** [comment]
@buchgr No `toplevel` is not what I want. I don't want test binaries are downloaded because they are fat, in Envoy it is around 80GB and even larger for sanitizer builds. This caused the RBE CI slowdown. `minimal` doesn't produce anything while `toplevel` downloads too much.

Can you reopen the issue?

**Comment by buchgr** [comment]
@lizan 

`bazel test //:foo --experimental_remote_download_outputs=toplevel` will only download test.log and test.xml. It won't download any binaries. Have you tested it and are seeing something else?

**Comment by lizan** [comment]
@buchgr Yes I did. Bazel downloads the binaries and it bursted CI. I had to add https://github.com/envoyproxy/envoy/blob/50fb561c23078e01efd4dc3852812efbf5ca8936/.bazelrc#L107.

I just tried now again and it downloaded binary. The command I ran:
```
bazel test -c opt --config=remote-clang --config=remote-ci --remote_instance_name=<rbe-instance>  --experimental_remote_download_outputs=toplevel //test/common/common:base64_test
```
at the commit above.

**Comment by buchgr** [comment]
@lizan ahh I see what you mean. Thanks for the reproducer. Please note that with `minimal` it will download test.log and test.xml of failed tests. I suppose this is not enough?

**Comment by lizan** [comment]
Yeah I'd like to setup CI Test Summary like [this](https://dev.azure.com/cncf/envoy/_build/results?buildId=6209&view=ms.vss-test-web.build-test-results-tab) without download test binaries. So it will be nice to have all `test.log` and `test.xml` that ran remotely.

**Comment by buchgr** [comment]
I have sent out https://github.com/bazelbuild/bazel/pull/8947 to address this issue. Maybe you could try it out on envoy?

**Comment by buchgr** [comment]
I tested it with the command line you provided and things work fine!

**Comment by lizan** [comment]
Thanks @buchgr I was able to verify in Envoy.
