### ISSUE TITLE
incompatible_disable_partition_default_parameter

### ISSUE THREAD

**Issue by vladmos** [bazelbuild/bazel#8953]
The flag disables the default value `' '` for `sep` parameter of `String.partition` and `String.rpartition`.

When the flag is flipped, one needs to provide an explicit value for the parameter, e.g. `s.partition(" ")`.

Implemented with https://github.com/bazelbuild/bazel/pull/8894

Expected timeline:

released with Bazel 0.29 (August 3), off by default
enabled by default with Bazel 1.0 (September 2019)

**Comment by dslomov** [comment]
Do we have migration support in buildifier?

**Comment by laurentlb** [comment]
No breakage found, neither on Bazel downstream projects, nor in the entire Google codebase.

Tooling is not useful (especially as it would have false negatives, due to the lack of static typing).

**Comment by dslomov** [comment]
> No breakage found, neither on Bazel downstream projects, nor in the entire Google codebase.
> 
> Tooling is not useful (especially as it would have false negatives, due to the lack of static typing).

That sounds reasonable to me.
