### ISSUE TITLE
incompatible_assignment_identifiers_have_local_scope: Variable assignment inside function is not treated as local

### ISSUE THREAD

**Issue by Quarz0** [bazelbuild/bazel#8956]
### Description of the problem / feature request:

> Augmented assignment statements do not make the LHS identifier local, thus variables declared outside a function are allowed to be assigned inside a function without being treated as local.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```python
a_list = []
def f4():
    a_list += [1]
f4()
print(a_list) # [1]
```
Running the same code using the Go implementation or Python:
```python
a_list = []
def f4():
    a_list += [1]
f4() # local variable a_list referenced before assignment
```

Suggested fix: use `list.append` or `list.extend` instead of `+=`.

```python
a_list = []
def f4():
    a_list.append(1)
f4() # valid
```

### Any other information, logs, or outputs that you want to share?

> https://stackoverflow.com/questions/6797164/why-doesnt-pythons-plus-equals-operator-modify-variables-from-inner-functio/6797210#6797210

**Comment by dslomov** [comment]
Is this realistic to flip in 1.0? 
Do we have any migration tooling?

**Comment by laurentlb** [comment]
I expect the number of breakages to be very low. I've run it on some projects inside Google (27k packages loaded, 690k targets configured), I couldn't detect any breakage.

In case of breakage, the fix should be simple to do manually. I'll update the first message.

**Comment by laurentlb** [comment]
Apparently, there's no breakage in Baze downstream projects either: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/196
