### ISSUE TITLE
Bazel crashes on macos with "failed to delete output files before executing action"

### ISSUE THREAD

**Issue by johnedmonds** [bazelbuild/bazel#8963]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

On macos, Bazel crashes with the error "failed to delete output files before executing action." Underlying cause is an IOException because the filename is too long. This is fixed by https://github.com/bazelbuild/bazel/commit/77497817b011f298b7f3a1138b08ba6a962b24b8 (see the change in FunctionTransitionUtil.java) but not released.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add a transition to a rule. The bug triggers when the chain of dependencies with transitions becomes too long.

### What operating system are you running Bazel on?

Mac

### What's the output of `bazel info release`?

release 0.28.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by laurentlb** [comment]
@juliexxia @gregestren 
Is it a new bug in Bazel 0.28, or is it older?
Can you confirm this change should be cherry-picked and we need a patch release?

**Comment by jin** [comment]
I can confirm I ran into this bug into 0.28.1.

**Comment by gregestren** [comment]
This bug should have existed ever since transitions were available. https://github.com/bazelbuild/bazel/commit/77497817b011f298b7f3a1138b08ba6a962b24b8 is an upgrade over the original logic.

So this shouldn't be a regression and I'm not sure a patch release is necessary as it should have never been possible to rely on this working correctly in the first place.


@johnedmonds what kind of impact are you facing from this?

**Comment by johnedmonds** [comment]
@gregestren That all sounds correct. Impact is that we need to use a pre-release version of bazel to build https://github.com/bazelbuild/rules_rust/pull/240.

**Comment by laurentlb** [comment]
It doesn't seem to qualify for a patch release.
I suggest to continue using your own version of Bazel until the next release (0.29, in August).

**Comment by chenmy0917** [comment]
I also encountered this problem, can you help me, look forward your reply @laurentlb 

**OS**: Ubuntu 16.04

**Bazel Version**:
![image](https://user-images.githubusercontent.com/22138217/113702954-c37bbc00-970c-11eb-88c9-74eda50cec03.png)

**Error**:
![image](https://user-images.githubusercontent.com/22138217/113703033-e1e1b780-970c-11eb-8c17-c56a10fce046.png)

**Comment by gregestren** [comment]
Hey @chenmy0917 . While this is the same error (`File name too long`), I think the cause is coming from a different place (it's not related to `FunctionTransitionUtil`). I recommend starting a new, dedicated bug for your failure.

**Comment by chenmy0917** [comment]
> Hey @chenmy0917 . While this is the same error (`File name too long`), I think the cause is coming from a different place (it's not related to `FunctionTransitionUtil`). I recommend starting a new, dedicated bug for your failure.

okay, thanks for your suggestion
