### ISSUE TITLE
C++ compilation of rule '@com_google_protobuf_javalite//:protoc_lib' failed (Exit -1)

### ISSUE THREAD

**Issue by TemplateDestruction** [bazelbuild/bazel#8968]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

C++ compilation of rule '@com_google_protobuf_javalite//:protoc_lib' failed (Exit -1)  Note: Remote connection/protocol failed with: execution failed: cl.exe failed: error executing command 

I want to build project in android studio using Bazel and encounter with this error

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

To repoduce you should download mediapipe google repository https://github.com/google/mediapipe  and open project in Android studio through bazel. Then 
enter Target Expression: //mediapipe/examples/android/src/java/com/google/mediapipe/apps/facedetectioncpu
enter Bazel command: mobile-install
enter Bazel flags: -c opt --config=android_arm64 
select Run

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.27.2

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git remote get-url origin : https://github.com/google/mediapipe.git
git rev-parse master: dc40414468e1b622065c2fe094c7956a0256f53c
git rev-parse HEAD: dc40414468e1b622065c2fe094c7956a0256f53c

###  Have you found anything relevant by searching the web?

https://github.com/tensorflow/tensorflow/issues/17709

### Any other information, logs, or outputs that you want to share?

[logs.docx](https://github.com/bazelbuild/bazel/files/3423926/logs.docx)

**Comment by jin** [comment]
Could you please upload the full set of logs with `--verbose_failures` into the issue directly, instead of the docx file?

**Comment by jin** [comment]
This also looks odd:

```
Note: Remote connection/protocol failed with: execution failed: cl.exe failed: error executing command
```

It doesn't look like you're running with remote execution / caching. 

The [bazelrc](https://github.com/google/mediapipe/blob/master/.bazelrc) also doesn't suggest anything, although the `--jobs=128` is definitely too much for a local build. Could you please file this issue on the mediapipe repository and ask if they support building on Windows? If we can narrow down that this is an issue with Bazel and not the project, we can reopen this issue.

**Comment by TemplateDestruction** [comment]
Probably, you didn't understand me, From windows side I just use Android studio to set application to Android device



Logs:
ERROR: C:/users/breakout/_bazel_breakout/obcyfho6/external/bazel_tools/src/main/native/windows/BUILD:20:1: C++ compilation of rule '@bazel_tools//src/main/native/windows:lib-file' failed (Exit -1). Note: Remote connection/protocol failed with: execution failed: cl.exe failed: error executing command 
  cd C:/users/breakout/_bazel_breakout/obcyfho6/execroot/mediapipe
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include;E:\Windows Kits\10\include\10.0.17763.0\ucrt;E:\Windows Kits\10\include\10.0.17763.0\shared;E:\Windows Kits\10\include\10.0.17763.0\um;E:\Windows Kits\10\include\10.0.17763.0\winrt;E:\Windows Kits\10\include\10.0.17763.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;E:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;E:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;E:\Windows Kits\10\bin\10.0.17763.0\x64;E:\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\breakout\AppData\Local\Temp
    SET TMP=C:\Users\breakout\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/bazel_tools /Ibazel-out/host/bin/external/bazel_tools /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /Fobazel-out/host/bin/external/bazel_tools/src/main/native/windows/_objs/lib-file/file.obj /c external/bazel_tools/src/main/native/windows/file.cc
Execution platform: @bazel_tools//platforms:host_platform
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(184): CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECAT(...)): РќРµ СѓРґР°РµС‚СЃСЏ РЅР°Р№С‚Рё СѓРєР°Р·Р°РЅРЅС‹Р№ С„Р°Р№Р».

Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu:edgedetectiongpu failed to build
ERROR: E:/caramels/hackprojects/mediapipes/mediapipe/examples/android/src/java/com/google/mediapipe/apps/edgedetectiongpu/BUILD:68:1 C++ compilation of rule '@bazel_tools//src/main/native/windows:lib-file' failed (Exit -1). Note: Remote connection/protocol failed with: execution failed: cl.exe failed: error executing command 
  cd C:/users/breakout/_bazel_breakout/obcyfho6/execroot/mediapipe
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include;E:\Windows Kits\10\include\10.0.17763.0\ucrt;E:\Windows Kits\10\include\10.0.17763.0\shared;E:\Windows Kits\10\include\10.0.17763.0\um;E:\Windows Kits\10\include\10.0.17763.0\winrt;E:\Windows Kits\10\include\10.0.17763.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;E:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\\x64;E:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;E:\Windows Kits\10\bin\10.0.17763.0\x64;E:\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\breakout\AppData\Local\Temp
    SET TMP=C:\Users\breakout\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/bazel_tools /Ibazel-out/host/bin/external/bazel_tools /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /Fobazel-out/host/bin/external/bazel_tools/src/main/native/windows/_objs/lib-file/file.obj /c external/bazel_tools/src/main/native/windows/file.cc
Execution platform: @bazel_tools//platforms:host_platform
INFO: Elapsed time: 2.223s, Critical Path: 0.09s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by jin** [comment]
Thanks for providing the full logs!

**Comment by laszlocsomor** [comment]
This part looks strange:
```
Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECAT(...)): РќРµ СѓРґР°РµС‚СЃСЏ РЅР°Р№С‚Рё СѓРєР°Р·Р°РЅРЅС‹Р№ С„Р°Р№Р».
```

What language is your Windows set to?

Do you still see this issue?

@jin wrote:
> Could you please file this issue on the mediapipe repository and ask if they support building on Windows?

Did you contact mediapipe?

**Comment by Acimaz** [comment]
Did you manage to fix this @TemplateDestruction? I have a similar problem atm on macOS
