### ISSUE TITLE
Exclude exec_tools with query and --nohost_deps

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#8976]
### Description of the problem / feature request:

Currently if you have a target that depends on a `genrule` that has `tools` like, you can query for the `deps` of that target and it will not include the `tools`. If you move to the new `exec_tools` field on `genrule`, these are included in the query with `--nohost_deps`. Based on the name of the flag I think that makes sense, but I guess that means it would be nice to have a new flag like `--noexec_deps` or something that excluded these targets.

### Feature requests: what underlying problem are you trying to solve with this feature?

Currently we query for all the source files of the target we're building and its dependencies, we don't want to include sources that aren't part of the final produce for our IDE integration.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.28.0

**Comment by gregestren** [comment]
I think this should be a quick fix. And the request sounds reasonable.

**Comment by katre** [comment]
This is definitely reasonable. There is also an internal issue related to this (http://b/138274743) which @brandjon is looking into.
