### ISSUE TITLE
Installation guide should recommend using apt over installer script

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8985]
[This page](https://docs.bazel.build/versions/0.28.0/install-ubuntu.html) calls the binary installer (side point: isn't it a .sh installer?) the recommended way to install. I would think that using our custom APT repository is better, since it should be able to grab dependencies automatically and is easier to uninstall.

The word "recommended" appears only in the hyperlink, so maybe it's leftover from a previous version of this page.

**Comment by jeongukjae** [comment]
Hi, I think this issue is resolved in below commit.

* https://github.com/bazelbuild/bazel/commit/d3f8efca72a0e2013467c033df1bf58dd76e8a10#diff-a8adbbd2808b548a57eb6cbfc008bc2d61a2c7275dbbcd81db277067a773de80
* Current docs page: https://bazel.build/install/ubuntu

**Comment by sgowroji** [comment]
Thank you for sharing the commit [details](https://github.com/bazelbuild/bazel/issues/8985#issuecomment-1422838359). Closing this issue as it is fixed.
