### ISSUE TITLE
Make the timeout to start the Bazel server configurable

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#8988]
### Description of the problem / feature request:

When launched on a machine under heavy load, the Bazel client may fail to connect to the server after the hardcoded 120s timeout.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- Give your machine a **lot** of jobs to chew on.
- Launch Bazel.
- Observe the Bazel client terminate with a `FATAL: couldn't connect to server (<pid>) after 120 seconds` message.

### What operating system are you running Bazel on?

CentOS 7

### What's the output of `bazel info release`?

release 0.26.0+vmware

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

na

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

na

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/blob/0.28.1/src/main/cpp/blaze.cc#L729-L732

I'm aware of the `--batch` flag, but it's deprecated.

### Any other information, logs, or outputs that you want to share?

I'm sporadically observing this on VMs in a build farm with ~30 vCPUs which, for dumb reasons I can't get into, need to service multiple build jobs simultaneously. Applications aren't starved for memory---it's a function of the kernel's runqueue; Bazel is just occasionally drawing the short straw.

I would appreciate it if this timeout were made user configurable or user disable-able. We'll likely patch our distribution in the meantime and are open to submitting a pull request.

**Comment by jmmv** [comment]
Huh, so we do have a `--connect_timeout_secs` but it doesn't apply to this hardcoded value, which still exists.

I'm sure we'd take a PR on this if you have one already around.

**Comment by janakdr** [comment]
Can this be closed?

**Comment by beasleyr-vmw** [comment]
Yes, I believe so. Thanks!
