### ISSUE TITLE
failed to read cache environment

### ISSUE THREAD

**Issue by crazyStrongboy** [bazelbuild/bazel#8990]
### Description of the problem / feature request:

> When bazel read go.env，I can find the specified file in my system。But the log shows that the specified file cannot be found。I don't known why~

![image](https://user-images.githubusercontent.com/33116100/61923723-8baffd80-af97-11e9-96aa-aa1786973367.png)

but I can find go.env in my system。

![image](https://user-images.githubusercontent.com/33116100/61923867-0f69ea00-af98-11e9-97c7-49c0cece4585.png)

### What operating system are you running Bazel on?

> windows

### What's the output of `bazel info release`?

> release 0.28.1

**Comment by jin** [comment]
Please open an issue on the [Go rules](https://github.com/bazelbuild/rules_go) repository.
