### ISSUE TITLE
Labels with a name ending in `/BUILD` are not valid

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#8992]
`bazel query //:a/BUILD` yields: `target names may not contain ':'`

This is inconsistent with `//:a/B`, `//:a/build` and `//:a/BUILD/x`, all of which are apparently legal labels and yield `target 'a/BUILD/c' not declared in package ''`). 

it's also confusing because the target names does not contain any colons.

**Comment by haxorz** [comment]
The general behavior looks WAI to me, but I agree the error message is confusing and unhelpful.

Assigning to me to type up a long reply and also improve the error message.
