### ISSUE TITLE
Move Python rules documentation from Bazel site to rules_python

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#8996]
Blocked on bazelbuild/rules_python#202 and bazelbuild/rules_python#144, both of which will be fixed imminently. (But I don't think this will be prioritized anywhere near as soon as those.)

**Comment by abergmeier** [comment]
Can you elaborate, how this should happen? AFAIK rules_python does not have any documentation aside from markdown and even these are not even linked.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
