### ISSUE TITLE
Error messages from incompatible_use_platforms_repo_for_constraints are lost in future builds

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#8998]
# Description of the problem / feature request:

When building with  `--incompatible_use_platforms_repo_for_constraints`, the error messages I get are lost on subsequent runs. This means that it is hard to see what is actually broken.

Command: `bazel build //... --incompatible_use_platforms_repo_for_constraints`

Output after attempt 1
```

INFO: Writing tracer profile to '/private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/command.profile.gz'
Loading: 
Loading: 0 packages loaded
Analyzing: 19 targets (8 packages loaded, 0 targets configured)
ERROR: /private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/external/bazel_tools/platforms/BUILD:49:1: in alias rule @bazel_tools//platforms:osx: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/external/bazel_tools/platforms/BUILD:19:1: in alias rule @bazel_tools//platforms:x86_64: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/external/bazel_tools/platforms/BUILD:69:1: in alias rule @bazel_tools//platforms:linux: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: While resolving toolchains for target //examples:lib1: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:hello-world-server-bin: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:test-example: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //build_rules:racket-compiler: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples/foo-collection:foo: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:binary-base: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:hello-world-server: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:binary-example: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
WARNING: errors encountered while analyzing target '//examples:binary-base': it will not be built
WARNING: errors encountered while analyzing target '//examples:hello-world-server': it will not be built
WARNING: errors encountered while analyzing target '//examples:hello-world-server-bin': it will not be built
WARNING: errors encountered while analyzing target '//examples:test-example': it will not be built
WARNING: errors encountered while analyzing target '//build_rules:racket-compiler': it will not be built
WARNING: errors encountered while analyzing target '//examples/foo-collection:foo-collection': it will not be built
WARNING: errors encountered while analyzing target '//examples:binary-example': it will not be built
WARNING: errors encountered while analyzing target '//build_rules:bazel-tools': it will not be built
WARNING: errors encountered while analyzing target '//examples:lib1': it will not be built
WARNING: errors encountered while analyzing target '//examples/foo-collection:foo': it will not be built
INFO: Analysis succeeded for only 9 of 19 top-level targets
INFO: Analyzed 19 targets (24 packages loaded, 66 targets configured).
INFO: Found 9 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[1 / 5] Executing genrule //linux/v7.0:racket-src-linux; 1s darwin-sandbox ... (4 actions running)
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 2.905s, Critical Path: 2.48s
INFO: 4 processes: 4 darwin-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

```
Output after attempt 2
```
INFO: Writing tracer profile to '/private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/command.profile.gz'
Loading: 
Loading: 0 packages loaded
Analyzing: 19 targets (0 packages loaded, 0 targets configured)
ERROR: While resolving toolchains for target //build_rules:racket-compiler: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples/foo-collection:foo: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:binary-base: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:binary-example: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:hello-world-server: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:hello-world-server-bin: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:lib1: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
ERROR: While resolving toolchains for target //examples:test-example: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
WARNING: errors encountered while analyzing target '//examples:binary-base': it will not be built
WARNING: errors encountered while analyzing target '//examples:hello-world-server': it will not be built
WARNING: errors encountered while analyzing target '//examples:hello-world-server-bin': it will not be built
WARNING: errors encountered while analyzing target '//examples:test-example': it will not be built
WARNING: errors encountered while analyzing target '//build_rules:racket-compiler': it will not be built
WARNING: errors encountered while analyzing target '//examples/foo-collection:foo-collection': it will not be built
WARNING: errors encountered while analyzing target '//examples:binary-example': it will not be built
WARNING: errors encountered while analyzing target '//build_rules:bazel-tools': it will not be built
WARNING: errors encountered while analyzing target '//examples:lib1': it will not be built
WARNING: errors encountered while analyzing target '//examples/foo-collection:foo': it will not be built
INFO: Analysis succeeded for only 9 of 19 top-level targets
INFO: Analyzed 19 targets (0 packages loaded, 0 targets configured).
INFO: Found 9 targets...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 0.187s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

```

Using code from: https://github.com/endobson/minimal-racket/tree/a98ed78cbe60699ec954304e6346c3f4433ee330

### What operating system are you running Bazel on?

macOS 10.13.5

### What's the output of `bazel info release`?

release 0.28.1

**Comment by aiuto** [comment]
I don't think this is a compatibilty issue. I think it is basic behavior. The rule fails in pass one. Nothing has changed, we do not try it again, so there is no output.

**Comment by philwo** [comment]
I don't see how xProduct can help here - reassigning to the flag owner for triaging.

**Comment by hlopko** [comment]
Yeah this is a result of inner workings of Bazel. I agree this is very inconvenient, but I don't have a good solution to this. I'll close this issue now and if we see this causing problems to more users I'll reinvestigate.

**Comment by sallybelly** [comment]
> # Description of the problem / feature request:
> When building with `--incompatible_use_platforms_repo_for_constraints`, the error messages I get are lost on subsequent runs. This means that it is hard to see what is actually broken.
> 
> Command: `bazel build //... --incompatible_use_platforms_repo_for_constraints`
> 
> Output after attempt 1
> 
> ```
> 
> INFO: Writing tracer profile to '/private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/command.profile.gz'
> Loading: 
> Loading: 0 packages loaded
> Analyzing: 19 targets (8 packages loaded, 0 targets configured)
> ERROR: /private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/external/bazel_tools/platforms/BUILD:49:1: in alias rule @bazel_tools//platforms:osx: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
> ERROR: /private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/external/bazel_tools/platforms/BUILD:19:1: in alias rule @bazel_tools//platforms:x86_64: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
> ERROR: /private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/external/bazel_tools/platforms/BUILD:69:1: in alias rule @bazel_tools//platforms:linux: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
> ERROR: While resolving toolchains for target //examples:lib1: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:hello-world-server-bin: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:test-example: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //build_rules:racket-compiler: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples/foo-collection:foo: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:binary-base: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:hello-world-server: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:binary-example: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> WARNING: errors encountered while analyzing target '//examples:binary-base': it will not be built
> WARNING: errors encountered while analyzing target '//examples:hello-world-server': it will not be built
> WARNING: errors encountered while analyzing target '//examples:hello-world-server-bin': it will not be built
> WARNING: errors encountered while analyzing target '//examples:test-example': it will not be built
> WARNING: errors encountered while analyzing target '//build_rules:racket-compiler': it will not be built
> WARNING: errors encountered while analyzing target '//examples/foo-collection:foo-collection': it will not be built
> WARNING: errors encountered while analyzing target '//examples:binary-example': it will not be built
> WARNING: errors encountered while analyzing target '//build_rules:bazel-tools': it will not be built
> WARNING: errors encountered while analyzing target '//examples:lib1': it will not be built
> WARNING: errors encountered while analyzing target '//examples/foo-collection:foo': it will not be built
> INFO: Analysis succeeded for only 9 of 19 top-level targets
> INFO: Analyzed 19 targets (24 packages loaded, 66 targets configured).
> INFO: Found 9 targets...
> [0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
> [1 / 5] Executing genrule //linux/v7.0:racket-src-linux; 1s darwin-sandbox ... (4 actions running)
> ERROR: command succeeded, but not all targets were analyzed
> INFO: Elapsed time: 2.905s, Critical Path: 2.48s
> INFO: 4 processes: 4 darwin-sandbox.
> FAILED: Build did NOT complete successfully
> FAILED: Build did NOT complete successfully
> ```
> 
> Output after attempt 2
> 
> ```
> INFO: Writing tracer profile to '/private/var/tmp/_bazel_endobson/e36ff165f90c34e5ec103dfa2b4ef8e1/command.profile.gz'
> Loading: 
> Loading: 0 packages loaded
> Analyzing: 19 targets (0 packages loaded, 0 targets configured)
> ERROR: While resolving toolchains for target //build_rules:racket-compiler: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples/foo-collection:foo: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:binary-base: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:binary-example: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:hello-world-server: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:hello-world-server-bin: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:lib1: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> ERROR: While resolving toolchains for target //examples:test-example: invalid registered toolchain '@minimal_racket//:osx_osx_racket_toolchain': Analysis of target '@bazel_tools//platforms:x86_64' failed; build aborted
> WARNING: errors encountered while analyzing target '//examples:binary-base': it will not be built
> WARNING: errors encountered while analyzing target '//examples:hello-world-server': it will not be built
> WARNING: errors encountered while analyzing target '//examples:hello-world-server-bin': it will not be built
> WARNING: errors encountered while analyzing target '//examples:test-example': it will not be built
> WARNING: errors encountered while analyzing target '//build_rules:racket-compiler': it will not be built
> WARNING: errors encountered while analyzing target '//examples/foo-collection:foo-collection': it will not be built
> WARNING: errors encountered while analyzing target '//examples:binary-example': it will not be built
> WARNING: errors encountered while analyzing target '//build_rules:bazel-tools': it will not be built
> WARNING: errors encountered while analyzing target '//examples:lib1': it will not be built
> WARNING: errors encountered while analyzing target '//examples/foo-collection:foo': it will not be built
> INFO: Analysis succeeded for only 9 of 19 top-level targets
> INFO: Analyzed 19 targets (0 packages loaded, 0 targets configured).
> INFO: Found 9 targets...
> [0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
> ERROR: command succeeded, but not all targets were analyzed
> INFO: Elapsed time: 0.187s, Critical Path: 0.02s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully
> FAILED: Build did NOT complete successfully
> ```
> 
> Using code from: https://github.com/endobson/minimal-racket/tree/a98ed78cbe60699ec954304e6346c3f4433ee330
> 
> ### What operating system are you running Bazel on?
> macOS 10.13.5
> 
> ### What's the output of `bazel info release`?
> release 0.28.1
