### ISSUE TITLE
Bootstrapping 32 bit Bazel 0.8.0 on Ubuntu

### ISSUE THREAD

**Issue by roberric** [bazelbuild/bazel#8999]
I want to build Tensor flow 1.5.0 on a 32 bit, 8G ram Ubuntu 14.04 machine, hence I need to bootstrap a 32 bit 0.8.0 Bazel

I get this error "java.lang.OutOfMemoryError: Java heap space"

I run this command:
sudo env BAZEL_JAVAC_OPTS="-J-Xms384m -J-Xmx2g" EXTRA_BAZEL_ARGS="--verbose_failure --jobs=2 --ram_utilization_factor=10 --host_javabase=@local_jdk//:jdk" bash ./compile.sh

It seems that none of the memory settings in the command line are having any effect. Do they not work when bootstrapping?

**Comment by roberric** [comment]
I using this version of Java since the Bazel build has other issues with newer versions.

openjdk version "1.8.0_153"
OpenJDK Runtime Environment (Zulu 8.25.0.3-linux32) (build 1.8.0_153-b01)
OpenJDK Server VM (Zulu 8.25.0.3-linux32) (build 25.153-b01, mixed mode)

**Comment by roberric** [comment]
didn't mean to close this

**Comment by philwo** [comment]
@roberric Unfortunately, neither running Bazel on a 32-bit platform, nor the Bazel version itself, nor the EOL'd Ubuntu 14.04 version match anything that we use ourselves and try to support these days.

I would suggest to ask this question on our mailing list instead: https://groups.google.com/forum/#!forum/bazel-discuss - other Bazel users who might be trying to build on 32-bit platforms or that version of Bazel due to TensorFlow might be able to help out.

I'll keep this open for a day, just in case I do get an idea what might cause the problems.

Some questions:
Which program crashes with the OutOfMemory error? Is it Bazel itself, or Javac, or something else?

I would try to pass the `-s` flag to Bazel via `EXTRA_BAZEL_ARGS`, which should cause it to print the command-lines of all build steps. This should tell you whether the Xms / Xmx  etc. flags actually reach the JavaBuilder invocations.

**Comment by roberric** [comment]
I don't believe any of the Bazel options such as job=2, are being used in the bootstrapping. I switched my Java version to 162, but to no avail. I have an env variable set as:

_JAVA_OPTIONS=-Xms512m -Xmx2g -verbose_failures



Here is the terminal output.
sudo env  EXTRA_BAZEL_ARGS="--s --jobs=2 --ram_utilization_factor=10 --host_javabase=@local_jdk//:jdk" bash ./compile.sh
[sudo] password for r: 
🍃  Building Bazel from scratch../usr/lib/jvm/zulu8.27.0.7-jdk8.0.162-linux_i686/bin/javac -classpath third_party/apache_commons_compress/apache-commons-compress-1.9.jar:third_party/jsr330_inject/javax.inject.jar:third_party/jackson2/jackson-core-2.8.6.jar:third_party/java/jacoco/org.jacoco.core-0.7.5.201505241946-src.jar:third_party/java/jacoco/org.jacoco.agent-0.7.5.201505241946.jar:third_party/java/jacoco/org.jacoco.report-0.7.5.201505241946-src.jar:third_party/java/jacoco/org.jacoco.agent-0.7.5.201505241946-src.jar:third_party/java/jacoco/jacocoagent.jar:third_party/java/jacoco/org.jacoco.report-0.7.5.201505241946.jar:third_party/java/jacoco/org.jacoco.core-0.7.5.201505241946.jar:third_party/java/proguard/proguard5.3.3/lib/proguard.jar:third_party/java/proguard/proguard5.3.3/lib/proguardgui.jar:third_party/java/proguard/proguard5.3.3/lib/retrace.jar:third_party/java/proguard/proguard5.3.3/examples/annotations/lib/annotations.jar:third_party/java/javapoet/javapoet-1.8.0.jar:third_party/java/jdk/langtools/javac.jar:third_party/java/jdk/langtools/javac-9-dev-r4023-3.jar:third_party/java/jarjar/gradle/wrapper/gradle-wrapper.jar:third_party/java/jarjar/jarjar-core/src/test/resources/enumtest.jar:third_party/java/jarjar/jarjar-1.4.jar:third_party/java/android_databinding/v2_3_1/exec.jar:third_party/java/jcommander/jcommander-1.48.jar:third_party/api_client/google-http-client-1.22.0.jar:third_party/api_client/google-api-client-jackson2-1.22.0.jar:third_party/api_client/google-api-client-1.22.0.jar:third_party/api_client/google-http-client-jackson2-1.22.0.jar:third_party/auth/google-auth-library-credentials-0.6.0.jar:third_party/auth/google-auth-library-oauth2-http-0.6.0.jar:third_party/plexus_utils/plexus-utils-3.0.21.jar:third_party/pcollections/pcollections-2.1.2.jar:third_party/tomcat_annotations_api/tomcat-annotations-api-8.0.5.jar:third_party/mockito/mockito-all-1.10.19.jar:third_party/apache_commons_codec/commons-codec-1.9.jar:third_party/netty_tcnative/netty-tcnative-boringssl-static-2.0.5.Final.jar:third_party/jimfs/jimfs-1.1.jar:third_party/hungarian_algorithm/software-and-algorithms-1.0.jar:third_party/hungarian_algorithm/software-and-algorithms-1.0-src.jar:third_party/apache_velocity/velocity-1.7.jar:third_party/apache_httpclient/httpclient-4.5.3.jar:third_party/junit/junit-4.11.jar:third_party/ijar/test/libwrongcentraldir.jar:third_party/netty/netty-all-4.1.14.Final.jar:third_party/maven/maven-settings-3.3.3.jar:third_party/maven/maven-settings-builder-3.3.3.jar:third_party/maven/maven-builder-support-3.3.3.jar:third_party/maven_model/maven-repository-metadata-3.2.3.jar:third_party/maven_model/maven-model-3.2.3.jar:third_party/maven_model/maven-model-builder-3.2.3.jar:third_party/maven_model/maven-aether-provider-3.2.3.jar:third_party/apache_commons_pool2/commons-pool2-2.3.jar:third_party/allocation_instrumenter/java-allocation-instrumenter-3.0.1.jar:third_party/apache_commons_logging/commons-logging-1.1.1.jar:third_party/bytebuddy/byte-buddy-dep-0.7-rc6.jar:third_party/protobuf/3.4.0/libprotobuf_java_util.jar:third_party/protobuf/3.4.0/libprotobuf_java.jar:third_party/jgit/org.eclipse.jgit-4.0.1.201506240215-r.jar:third_party/slf4j/slf4j-jdk14-1.7.7.jar:third_party/slf4j/slf4j-api-1.7.7.jar:third_party/jsr305/jsr-305.jar:third_party/auto/auto-service-1.0-rc2.jar:third_party/auto/auto-value-1.4.jar:third_party/auto/auto-common-0.3.jar:third_party/gson/gson-2.2.4.jar:third_party/truth/truth-0.36.jar:third_party/opencensus/opencensus-api-0.5.1.jar:third_party/guava/guava-testlib-23.1-jre.jar:third_party/error_prone/error_prone_annotation-2.1.1.jar:third_party/error_prone/error_prone_annotations-2.1.1.jar:third_party/error_prone/error_prone_check_api-2.1.1.jar:third_party/android_common/com.android.tools_dvlib_25.0.0.jar:third_party/android_common/com.android.tools.external.lombok_lombok-ast_0.2.3.jar:third_party/android_common/com.android.tools.lint_lint-api_25.0.0.jar:third_party/android_common/com.android.tools.lint_lint-checks_25.0.0.jar:third_party/android_common/com.android.tools.build_manifest-merger_25.0.0.jar:third_party/android_common/com.android.tools.build_builder_2.0.0.jar:third_party/android_common/com.android_annotations_25.0.0.jar:third_party/android_common/com.android.tools_ddmlib_25.0.0.jar:third_party/android_common/com.android.tools.build_builder-model_2.0.0.jar:third_party/android_common/com.android.tools_common_25.0.0.jar:third_party/android_common/com.android.tools_sdk-common_25.0.0.jar:third_party/android_common/com.android.tools.build_builder-test-api_2.0.0.jar:third_party/android_common/com.android.tools_repository_25.0.0.jar:third_party/android_common/com.android.tools.layoutlib_layoutlib_25.0.0.jar:third_party/android_common/com.android.tools_sdklib_25.0.0.jar:third_party/hamcrest/hamcrest-core-1.3.jar:third_party/hazelcast/hazelcast-3.6.4.jar:third_party/hazelcast/hazelcast-client-3.6.4.jar:third_party/aether/aether-impl-1.0.0.v20140518.jar:third_party/aether/aether-transport-classpath-1.0.0.v20140518.jar:third_party/aether/aether-transport-wagon-1.0.0.v20140518.jar:third_party/aether/aether-spi-1.0.0.v20140518.jar:third_party/aether/aether-transport-file-1.0.0.v20140518.jar:third_party/aether/aether-transport-http-1.0.0.v20140518.jar:third_party/aether/aether-connector-basic-1.0.0.v20140518.jar:third_party/aether/aether-util-1.0.0.v20140518.jar:third_party/aether/aether-api-1.0.0.v20140518.jar:third_party/apache_httpcore/httpcore-4.4.6.jar:third_party/apache_commons_lang/commons-lang-2.6.jar:third_party/plexus_interpolation/plexus-interpolation-1.22.jar:third_party/turbine/turbine-0.1-20170828.jar:third_party/xz/xz-1.5.jar:third_party/joda_time/joda-time-2.3.jar:third_party/asm/asm-commons-5.1.jar:third_party/asm/asm-util-5.1.jar:third_party/asm/asm-analysis-5.1.jar:third_party/asm/asm-tree-5.1.jar:third_party/asm/asm-5.1.jar:third_party/instrumentation/instrumentation-api-0.4.3.jar:third_party/jsch/jsch-0.1.51.jar:third_party/plexus_component_annotations/plexus-component-annotations-1.6.jar:third_party/apache_commons_collections/commons-collections-3.2.2.jar:third_party/jcip_annotations/jcip-annotations-1.0-1.jar:third_party/grpc/grpc-protobuf-1.6.1.jar:third_party/grpc/grpc-netty-1.6.1.jar:third_party/grpc/grpc-auth-1.6.1.jar:third_party/grpc/grpc-stub-1.6.1.jar:third_party/grpc/grpc-core-1.6.1.jar:third_party/grpc/grpc-context-1.6.1.jar:third_party/grpc/grpc-protobuf-lite-1.6.1.jar:third_party/guava/guava-23.1-jre.jar:third_party/error_prone/error_prone_core-2.1.1.jar:/tmp/bazel_Qu9hfAJo -sourcepath src/java_tools/singlejar/java/com/google/devtools/build/zip:src/main/java:src/tools/xcode-common/java/com/google/devtools/build/xcode/common:src/tools/xcode-common/java/com/google/devtools/build/xcode/util:third_party/java/dd_plist/java:/tmp/bazel_Qu9hfAJo/src -d /tmp/bazel_Qu9hfAJo/classes -source 1.8 -target 1.8 -encoding UTF-8 @/tmp/bazel_BhnEgHZd/param
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:17: warning: Signal is internal proprietary API and may be removed in a future release
import sun.misc.Signal;
               ^
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:18: warning: SignalHandler is internal proprietary API and may be removed in a future release
import sun.misc.SignalHandler;
               ^
src/main/java/com/google/devtools/build/lib/skyframe/serialization/strings/FastStringCodec.java:27: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:17: warning: Signal is internal proprietary API and may be removed in a future release
import sun.misc.Signal;
               ^
src/main/java/com/google/devtools/build/lib/server/signal/InterruptSignalHandler.java:18: warning: SignalHandler is internal proprietary API and may be removed in a future release
import sun.misc.SignalHandler;
               ^
src/main/java/com/google/devtools/build/lib/skyframe/serialization/strings/FastStringCodec.java:27: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^


The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.io.UnixFileSystem.resolve(UnixFileSystem.java:108)
	at java.io.UnixFileSystem.resolve(UnixFileSystem.java:133)
	at java.io.File.getAbsolutePath(File.java:556)
	at java.io.File.getAbsoluteFile(File.java:572)
	at com.sun.tools.javac.file.RegularFileObject.getAbsoluteFile(RegularFileObject.java:246)
	at com.sun.tools.javac.file.RegularFileObject.hashCode(RegularFileObject.java:240)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.get(HashMap.java:557)
	at com.sun.tools.javac.util.AbstractLog.getSource(AbstractLog.java:64)
	at com.sun.tools.javac.util.AbstractLog.useSource(AbstractLog.java:57)
	at com.sun.tools.javac.comp.MemberEnter$5.run(MemberEnter.java:864)
	at com.sun.tools.javac.comp.Annotate.flush(Annotate.java:143)
	at com.sun.tools.javac.comp.Annotate.enterDone(Annotate.java:129)
	at com.sun.tools.javac.comp.Enter.complete(Enter.java:512)
	at com.sun.tools.javac.comp.Enter.main(Enter.java:471)
	at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:982)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.enterTrees(JavacProcessingEnvironment.java:1015)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.<init>(JavacProcessingEnvironment.java:902)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.next(JavacProcessingEnvironment.java:921)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1187)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	at com.sun.tools.javac.main.Main.compile(Main.java:381)
	at com.sun.tools.javac.main.Main.compile(Main.java:370)
	at com.sun.tools.javac.main.Main.compile(Main.java:361)
	at com.sun.tools.javac.Main.compile(Main.java:56)
	at com.sun.tools.javac.Main.main(Main.java:42)

**Comment by philwo** [comment]
@roberric `sudo` usually runs processes in a clean environment, so it wouldn't surprise me if that removes your _JAVA_OPTIONS environment variable.

Example:
```bash
philwo@philwo2:~$ _JAVA_OPTIONS=test env | grep _JAVA_OPTIONS
_JAVA_OPTIONS=test
philwo@philwo2:~$ _JAVA_OPTIONS=test sudo env | grep _JAVA_OPTIONS
```

However, Bazel also runs processes in a clean environment in order to improve hermeticity, so the variable might get lost then, even if it passes `sudo`.

AFAIK Bazel 0.8.0 doesn't yet support `--action_env`, so you can't use that to pass them through.

However, if the bootstrap crashes during the "Building Bazel from scratch" phase, I think it's not even yet using Bazel, so all these flags don't have an effect. It's just using plain Javac. I would advise to dig through the compile.sh scripts and try to hack it so that it passes the required flags to the Javac. Maybe it's this call here: https://github.com/bazelbuild/bazel/blob/0.8.0/scripts/bootstrap/compile.sh#L117 ?

Sorry, I don't think I can help you more with that. :(

**Comment by roberric** [comment]
I had the same thought about adding the Java parameters to the compile.sh. But I decided to give up and reimage my disk with a 64bit Ubuntu and just get the prebuilt Tensorflow 1.5.0. I've done that and can now get on with using Tensorflow instead of trying to build it.
