### ISSUE TITLE
cannot use $(location with //external targets

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/bazel#90]
BUILD:9:11: in cmd attribute of genrule rule //src/main/java:gxpgen: label '//external:gxp' in $(location) expression is not a declared prerequisite of this rule.

WORKSPACE
maven_jar(
    name = "gxp-repo",
    artifact_id = "google-gxp",
    group_id = "com.google.gxp",
    version = "0.2.4-beta",
)
bind(
    name = "gxp",
    actual = "@gxp-repo//jar",
)

BUILD file:
genrule(
    name = "gxpgen",
    outs = ["foo"],
    cmd = "java -cp $(location //external:gxp) com.google.gxp.compiler.cli.Gxpc" +
          " --output_language java --dir $(@D) --help",
    tools = ["//external:gxp"],
)

**Comment by kchodorow** [comment]
I'm working on a fix for this, I'll update this issue once it's in.

**Comment by kayasoze** [comment]
Unfortunately this issue still exists for genrules referenced from the tools attribute of a genrule.  Verified by patching location_test.sh.

**Comment by bsilver8192** [comment]
I think <https://bazel-review.googlesource.com/#/c/1750/> fixes this.

**Comment by kayasoze** [comment]
It appears fixed to me.
