### ISSUE TITLE
incompatible_load_python_rules_from_bzl: Python rules now need to be loaded from @rules_python

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#9006]
**Flag:** `--incompatible_load_python_rules_from_bzl`
**Available since:** 0.29
**Will be flipped in:** 2.0
**Feature tracking issue:** #8893

## Motivation

The "core" Python rule logic is currently bundled with Bazel as a combination of native symbols and symbols loaded from `@bazel_tools//tools/python`. Eventually the native rules will be ported to Starlark, and all symbols will live in [bazelbuild/rules_python](https://github.com/bazelbuild/rules_python). In the meantime, we're making it so the user loads these symbols from the rules_python repository, even though they're largely still implemented inside of Bazel itself. This will help make future migration of rule logic to rules_python less painful.

## Change

Enabling this flag causes the four native Python rules,

* `py_library`
* `py_binary`
* `py_test`
* `py_runtime`

to fail at analysis time when they are used directly instead of via rules_python.

## Migration

Any usage of the these rules as a built-in symbol should be replaced with a use of the macros defined in rules_python as follows. (All four macros are defined in `defs.bzl`.)

```python
# My BUILD file

py_binary(
    ...
)
```

should become

```python
# My BUILD file

load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    ...
)
```

In the case of macros in .bzl files,

```python
# My .bzl file

def my_macro(...):
    native.py_binary(
        ...
    )
```

should become

```python
# My .bzl file

load("@rules_python//python:defs.bzl", "py_binary")

def my_macro(...):
    py_binary(
        ...
    )
```

To access the `@rules_python` repo you'll need to make sure you have the following in your WORKSPACE file:

```python
# My WORKSPACE file

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "rules_python",
    remote = "https://github.com/bazelbuild/rules_python.git",
    commit = "4b84ad270387a7c439ebdccfd530e2339601ef27",  # (2019-08-02 or later)
)

load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()
```

If you're using rules_python for pip support (which is separate from the core Python rules), you'll also need to [call the `pip_repositories()` function](https://github.com/bazelbuild/rules_python#setup).

Note that until recently, `@rules_python` went by the workspace name `@io_bazel_rules_python`. If you have a definition for the old name in your WORKSPACE file then you'll need to rename it, and ensure your commit is updated to a recent version.

**Comment by brandjon** [comment]
The downstream incompatible change pipeline won't test this until 0.29 is released, but in the meantime I did a custom downstream run with the flag flip [here](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1121#0cc6461c-51dd-4cc2-abbc-1862ae4984e3). Looks like several dozen failures, maybe almost half of all configurations in the pipeline.

**Comment by dslomov** [comment]
Is there a tool to facilitate this migration? (it is a mechanic change, so buildifer should help)

**Comment by brandjon** [comment]
Not at the moment, I'd like to add one but not sure how long that'll take. The changes amount to 1) adding WORKSPACE boilerplate, 2) adding `load()` statements to BUILD files, 3) (rarer) adding `load()` statements to .bzl files and replacing `native.<py_rule>` with `<py_rule>`.

**Comment by brandjon** [comment]
Will be added by bazelbuild/buildtools#691. It doesn't currently do WORKSPACE files though -- looks like the java and cc bzl migrations don't do that either?

**Comment by brandjon** [comment]
Update: We will not be flipping this flag (or the analogous flags for java and cc) in Bazel 1.0. The main reasons are:

- The blast radius is high. Pretty much every BUILD file in every project needs to be updated. There is tooling to do this automatically in buildifier, however...

- The tooling does not yet automatically update WORKSPACE files. Users instead have to manually copy/paste the right incantation into their WORKSPACE from rules_python/java/cc's readme.md page. The Bazel federation is also not in a position to make this change easier yet.

- The benefit is not large enough to overcome these issues. Although it's a step toward migrating the rules out of Bazel, as long as the actual rule implementations still live in Bazel we still have to support them for the duration of the 1.x development cycle.

With this in mind we'll look at targeting Bazel 2.0 instead. In the meantime we can improve tooling and add new flags for more related deprecations/migrations.

**Comment by aaliddell** [comment]
What's the timescale on 2.0? It 'sounds' a long way off but that depends on the release cycle chosen for Bazel after 1.0.

Also, is the intention to replace the native implementations with the Starlark implementations (similar to @bazel_tools, but without the `load`) during the 1.0 lifetime, but not force the manual addition to workspace and load in BUILD until 2.0? That doesn't solve having to support both, but starts getting the Starlark implementations battle tested.

**Comment by brandjon** [comment]
At this point the only thing set in stone about 2.0 is that it'll be [at least 3 months](https://blog.bazel.build/2019/06/06/Bazel-Semantic-Versioning.html).

Note that there is no Starlark implementation of the native Python rules -- only redirects in rules_python that export the native implementations as if they were defined in Starlark. Migrating the implementation to Starlark is not necessarily blocked on getting people to load from rules_python first. Only deleting/modifying the native rules is blocked on that.

**Comment by Yannic** [comment]
What's the status of this flag? Is it going to be flipped eventually or has it been abandoned? If it's the former, can we add `migration-X` labels for 2.x and 3.x so it'll be detected by Bazelisk and tested on Buildkite?

**Comment by wchargin** [comment]
+1 to @Yannic’s question: this flag was supposed to be flipped in Bazel
2.0, but still isn’t flipped in Bazel 3.7, which released almost a year
later. Is it still realistically planned? This matters for downstream
`rules_*` maintainers; we need to know whether we have to go to the
trouble of pulling in a `rules_python` dependency for helper scripts.

**Comment by lberki** [comment]
Ow, this bug is still open? After careful consideration, we decided that this would be change that causes way too much breakage, so we decided to take another approach instead: we'll teach Bazel to be able to carry Starlark rules with itself just like it does ones implemented in Java now. We'll have to figure out how to decouple these rules from Bazel, of course, but that's a next step. (My crystal ball says that it will involve some magic connection between BUILD files and the WORKSPACE file, for example, by adding implicit `load()` statements to the beginning of every BUILD file, but that's just a guess)

**Comment by cpsauer** [comment]
If the plan is to reverse course, could it be a good idea to delete this flag?
(Genuinely not sure; just wanted to float.)

[Context: I, like others it seems, got here because someone using [a tool I'd build for bazel](https://github.com/hedronvision/bazel-compile-commands-extractor/) had it flipped, [breaking things](https://github.com/hedronvision/bazel-compile-commands-extractor/issues/19). Probably via `--all_incompatible_changes`, so [it's removal will certainly help when it ships](https://github.com/bazelbuild/bazel/issues/13892). Maybe there's a need for this to still be around; not sure.]
