### ISSUE TITLE
incompatible_disable_depset_items: disallow the "items" parameter on the depset constructor

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#9017]
**Flag: --incompatible_disable_depset_items**

Disables the `items` parameter of the `depset()` contructor.

### Motivation

The `items` parameter has been [documented as Deprecated](https://docs.bazel.build/versions/master/skylark/lib/globals.html#depset) for many months. Users are encouraged to use `direct` and `transitive` instead.

### Migration

Separate the items of a depset into the direct elements and the transitive depsets to union; use `direct` and `transitive` parameters. See [the documentation](https://docs.bazel.build/versions/master/skylark/lib/globals.html#depset).

**Comment by aehlig** [comment]
It seems that this flag isn't flipped yet. Extending the migration window.
