### ISSUE TITLE
Starlark: ctx.actions.run can't use source file as executable

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#9023]
### Description of the problem / feature request:

ctx.actions.run cannot use a source file as the executable. If you make a copy with a genrule, you can use it.

More info: https://github.com/laszlocsomor/projects/tree/019c456fa4da1a20b000381158c4b31f4700d17a/bazel/ctx_actions_run_with_file

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.28.1

**Comment by laurentlb** [comment]
The command is `foo.sh bazel-out/k8-fastbuild/bin/use-file.out`. I suspect the path is incorrect.

A cleaner workaround is to wrap the shell script with `sh_binary`, like in the example: https://github.com/bazelbuild/examples/blob/master/rules/actions_run/BUILD

**Comment by laszlocsomor** [comment]
> The command is `foo.sh bazel-out/k8-fastbuild/bin/use-file.out`. I suspect the path is incorrect.

What is the correct path?

> A cleaner workaround is to wrap the shell script with `sh_binary`, like in the example: https://github.com/bazelbuild/examples/blob/master/rules/actions_run/BUILD

Sure. But we support `genrule.tools=["my.sh"]` and `genrule.cmd="$(location my.sh) ..."`, why not this?

**Comment by brandjon** [comment]
This does sound inconsistent to me.

**Comment by pcjanzen** [comment]
I believe that If you move foo.sh into any subdirectory, it'll work; the problem is when the source file is at the root of the workspace directory, we don't execute `./foo.sh`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
