### ISSUE TITLE
glob results should not include files from symlinked bazel-* exec root directories

### ISSUE THREAD

**Issue by irengrig** [bazelbuild/bazel#9026]
Please find the example project attached.

rule.bzl:
`def _impl(ctx):
  text = ""
  for label_ in ctx.attr.files:
    for file_ in label_.files.to_list():
      text += "\n" + file_.basename
  out_file = ctx.actions.declare_file("out.txt")
  ctx.actions.write(out_file, text)
  return [DefaultInfo(files = depset(direct = [out_file]))]

simple_rule = rule(
  implementation = _impl,
  attrs = {
    "files": attr.label_list(allow_files = True),
  }
)`

BUILD file:
`load(":rule.bzl", "simple_rule")

filegroup(name = "all", srcs = glob(["**"], exclude = ["out/**"]), 
visibility = ["//visibility:public"])

simple_rule(
  name = "simple",
  files = [":all"],
)
`

The resulting out.txt of running "bazel build //:simple" **for the second time**:
`
.bazelignore
BUILD
WORKSPACE
out.txt
out.txt
out.txt
stable-status.txt
volatile-status.txt
rule.bzl`

- files from bazel-* directories, like volatile-status.txt, are included into glob.

However, Bazel is capable of detection that those directories are not sources and therefore should be always ignored.
Though it is not very likely to really see the pattern like glob("**") on the top level, in reality it could be something more specific but including bazel-* directories, like: glob("*gen").

[glob.tar.gz](https://github.com/bazelbuild/bazel/files/3452220/glob.tar.gz)

**Comment by benjaminp** [comment]
Isn't this the same as #6350?

**Comment by irengrig** [comment]
@benjaminp yep, seems so, thank you!

Duplicate of #6350
