### ISSUE TITLE
Support testing android application

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#903]
`android_test` and `android_robolectric_test`

**Comment by damienmg** [comment]
Splitting this one in two.
android_test will be there next quarter but android_robolectric_test should be there in O(weeks)

**Comment by steren** [comment]
Update: This is actively being worked on and should land by end of Q2.

**Comment by kamalmarhubi** [comment]
@steren does this mean both `android_test` and `android_robolectric_test`?

**Comment by damienmg** [comment]
Both are being worked on but Android robolectric test might arrive slower
(android_test is prioritized over the other)

**Comment by aj-michael** [comment]
An update:

Android emulator testing support is being actively worked on. The tools that Bazel uses for testing Android applications will not be bundled as part of Bazel, but instead will be accessible at https://github.com/google/android-testing-support-library.

The first step towards android testing support was checked in last night in 6dd0292fb522f68ea18371107d68934c3f7eee22. It is a new rule called android_device that works in conjunction with the android-testing-support-library to launch emulators.

Stay tuned for more :smile:

**Comment by aj-michael** [comment]
Update:

We have open sourced a variety of android_device rules in https://github.com/google/android-testing-support-library/tree/master/tools/android/emulated_devices. The android testing rules will allow you to specify a device to test against and this repro creates many android_device rules based on physical devices hardware specifications.

Although the testing rules are not out yet, you can launch emulators from this repository as follows:

```
$ cat WORKSPACE
android_sdk_repository(name = "androidsdk")
git_repository(
    name = "android_test_support",
    remote = "https://github.com/google/android-testing-support-library",
    commit = "5e8ea367d53d6951c9511afc37f1ce36fb4bcd79",
)
load("@android_test_support//tools/android/emulator:unified_launcher.bzl", "load_workspace")
load_workspace()

$ bazel run @android_test_support//tools/android/emulated_devices/pixel:android_25_x86 -- --noadd_insecure_cacert --enable_display

$ bazel run @android_test_support//tools/android/emulated_devices/generic_watch:wear_24_x86 -- --noadd_insecure_cacert --enable_display
```

Note that you will need a bazel binary built from HEAD (it must include 8d876cf3ac18a0563828f4d66a48b84c957c55fb).

**Comment by kamalmarhubi** [comment]
@aj-michael re the device rules (https://github.com/bazelbuild/bazel/issues/903#issuecomment-295392958), I tried the exact same thing with the `pixel:google_25_x86` device in a fresh `WORKSPACE` and get an error about a missing `snapshots.img`:

```
$ bazel run @android_test_support//tools/android/emulated_devices/pixel:google_25_x86 -- --noadd_insecure_cacert --enable_display
INFO: Analysed target @android_test_support//tools/android/emulated_devices/pixel:google_25_x86 (0 packages loaded).
INFO: Found 1 target...
Slow read: a 2147483648-byte read from /home/heap-kamal/.cache/bazel/_bazel_heap-kamal/d42b9c57d24cf5db3bd8d332dc35437f/external/androidsdk/system-images/android-25/google_apis/x86/system.img took 19048ms.
Slow read: a 576716800-byte read from /home/heap-kamal/.cache/bazel/_bazel_heap-kamal/d42b9c57d24cf5db3bd8d332dc35437f/external/androidsdk/system-images/android-25/google_apis/x86/userdata.img took 5032ms.
ERROR: missing input file '@androidsdk//:tools/lib/emulator/snapshots.img'
ERROR: /home/heap-kamal/.cache/bazel/_bazel_heap-kamal/d42b9c57d24cf5db3bd8d332dc35437f/external/android_test_support/tools/android/emulated_devices/pixel/BUILD:16:1: @android_test_support//tools/android/emulated_devices/pixel:google_25_x86: missing input file '@androidsdk//:tools/lib/emulator/snapshots.img'
Target @android_test_support//tools/android/emulated_devices/pixel:google_25_x86 failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/heap-kamal/.cache/bazel/_bazel_heap-kamal/d42b9c57d24cf5db3bd8d332dc35437f/external/android_test_support/tools/android/emulated_devices/pixel/BUILD:16:1 1 input file(s) do not exist
INFO: Elapsed time: 26.063s, Critical Path: 0.15s
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

(I can't seem to find the `system-images;android-25;default;x86` image in `sdkmanager` that would be needed to make your precise command work.)

**Comment by aj-michael** [comment]
@kamalmarhubi , unfortunately the Android SDK recently decided to shift around all of it's contents. This is tracked in https://github.com/bazelbuild/bazel/issues/3504, although I have not had time to fix it. In particular, they removed a file called `snapshots.img` that Bazel was relying on.

**Comment by kamalmarhubi** [comment]
@aj-michael thanks for the context!

**Comment by jin** [comment]
The rules have been open sourced as [`android_local_test`](https://docs.bazel.build/versions/master/be/android.html#android_local_test) and [`android_instrumentation_test`](https://docs.bazel.build/versions/master/be/android.html#android_instrumentation_test).

**Comment by aj-michael** [comment]
Woooooot! Congrats!

**Comment by jgavris** [comment]
@jin is it on the roadmap to support `bazel coverage` for `android_local_test`?

>android_local_test does not yet support coverage

**Comment by jin** [comment]
@jgavris sorry I missed this. The Android rules are undergoing a complete rewrite into Skylark, landing in https://github.com/bazelbuild/rules_android

Once the rules are in Skylark, we'll be able to iterate on them to add new features like coverage.
