### ISSUE TITLE
replace httpdownloader with remote/http package

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#9036]
The `HttpDownloader` used to fetch remote repositories should be replaced by the netty-based code in the remote/http package that is already used for remote caching.

**Comment by buchgr** [comment]
@artem-zinnatullin mentioned that he might be interested in working on this.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
