### ISSUE TITLE
no such package 'tools/arm_compiler': BUILD file not found on package path

### ISSUE THREAD

**Issue by ApacheWang** [bazelbuild/bazel#9041]
Hi, I find a bug about when I run bazel/src/test/shell/bazel/testdata/bazel_toolchain_test_data and try to build it, it return me an Error.
My order is 
 `bazel build -s --crosstool_top=//tools/arm_compiler:toolchain --cpu=armeabi-v7a hello`
My platform is Ubuntu 16.04, and bazel version is 0.28.1.
My Error is 
`ERROR: /opt/git/bazel/src/test/shell/bazel/testdata/bazel_toolchain_test_data/BUILD:7:1: every rule of type cc_binary implicitly depends upon the target '//tools/arm_compiler:toolchain', but this target could not be found because of: no such package 'tools/arm_compiler': BUILD file not found on package path
ERROR: Analysis of target '//:hello' failed; build aborted: no such package 'tools/arm_compiler': BUILD file not found on package path
`
I hope someone can help me, thank you.

**Comment by ApacheWang** [comment]
I followed the official tutorial, but it is really difficult to cross-compile with bazel. cmake may be a command, but bazel needs to write a lot of configuration files, can reduce the cross-compilation threshold, and I think cross-compilation It is a very big demand, and many people complain that hope can be improved, bazel can develop better.

**Comment by scentini** [comment]
Did you rename the WORKSPACE.linaro and BUILD.linaro files to WORKSPACE and BUILD?
This toolchain is only used for testing purposes, and we create a proper repository [inside the test itself](https://source.bazel.build/bazel/+/master:src/test/shell/bazel/bazel_toolchain_test.sh;l=44).
