### ISSUE TITLE
Windows, test: support running tests from long paths

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#9042]
### Description of the problem / feature request:

`bazel test //foo/bar/baz/.../qux:my_test` fails if the package path is long. (Lower limit depends on the output root path length, but it's definitely at most MAX_PATH.)

Reason is, Windows cannot create a process for a binary whose path is longer than MAX_PATH. Workaround is to create a junction pointing to the binary's parent directory, then CreateProcessW works.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

0.28.1

**Comment by laszlocsomor** [comment]
Unfortunately I couldn't repro this with cc_test: if my package path was too long then MSVC couldn't compile the file, and with a shorter package path I couldn't repro the bug.

**Comment by ozio85** [comment]
I have made repro. The key is to have a short name of the test file and a long label name, then the runfiles directory will be longer, but the object files remain the same length.
[repro.zip](https://github.com/bazelbuild/bazel/files/3463630/repro.zip)

Please note that also the long path problem with cl.exe (or mingw for that matter) is solvable by creating a wrapper script that detects long paths and moves input files to a temp directory, replaces long output files with a temp location and move them back after the compilation is performed.

If a params file is used (which solves problems when there command line length exceeds 32767 chars), also the params file has to be parsed and replaced.

**Comment by ozio85** [comment]
I have attached a wrapper script that works with mingw, which moves files to temp location before compliation. It should be easy to modify it to work with msvc aswell:

[fix_long_paths.zip](https://github.com/bazelbuild/bazel/files/3463650/fix_long_paths.zip)

**Comment by laszlocsomor** [comment]
Thank you, the repro works! I extracted it under `C:\src\gh9042\repro` and could `bazel build` but not `bazel test`, using bazel 0.28.1.

Moving files to shorter paths for cl.exe can fix compilation but breaks two things:
- `#include` directives
- source file paths in .pdb files

That's why we didn't fix it in Bazel :(

**Comment by ozio85** [comment]
Thats true when source files are moved, but they are not the main problem. (Windows Explorer cannot handle paths longer than MAX_PATH anyway.. files are displayed but you cannot spawn any commands or start any editors)

The problem is really the object files and definition files since they are placed in [out_folder]/_objs/[name_of_object_which_may_be_long][.d/.o]

The out location of .d and .o files could be handle with a junction from a shorter path. However, when the .o files are linked in a later step, the same problem occurs. I guess it can be solved with a junction as well, a bit more messy, but solvable.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
