### ISSUE TITLE
Docs for build_file / workspace_file are confusing or incorrect

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#9050]
The documentation for `build_file` and `workspace_file`, e.g. for [`new_local_repository`](https://docs.bazel.build/versions/master/be/workspace.html#new_local_repository_args), say that these attributes have type `String` and actually hold labels that are resolved relative to the main repo. Yet [this test](https://github.com/bazelbuild/bazel/blob/90a55a994b5f5ae5ad928052ed77351055c28945/src/test/shell/integration/modify_execution_info_test.sh#L159) appears to use paths, not labels, as the value of this attr. Which is it?

**Comment by aehlig** [comment]
> The documentation for `build_file` and `workspace_file`, e.g. for [`new_local_repository`](https://docs.bazel.build/versions/master/be/workspace.html#new_local_repository_args), say that these attributes have type `String` and actually hold labels that are resolved relative to the main repo.

Yes. This is a correct description of the semantics of those rules.

For backwards compatibility, these rules also support the old, deprecated, way ...
> Yet [this test](https://github.com/bazelbuild/bazel/blob/90a55a994b5f5ae5ad928052ed77351055c28945/src/test/shell/integration/modify_execution_info_test.sh#L159) appears to use paths, not labels, as the value of this attr. 

...of specifying a path (and that legacy behavior is tested as well). But, as we do not want to encourage using the deprecated behavior, the documentation only describes the intended way of using this attribute.

I don't see a problem with this approach; please reopen with more details, if you see a problem.

**Comment by brandjon** [comment]
The problem I see is that if the legacy behavior is not supported and goes away, it is not trivial to depend on a local repository that is not hosted underneath the main workspace, at least not without duplicating its top-level BUILD file's content as an inlined string. That's the situation for this test, where the local repo appears within the runfiles tree of the test.

I do what the rationale is for not supporting paths to BUILD files, or using the local repo's BUILD file as-is.

**Comment by aehlig** [comment]
> The problem I see is that if the legacy behavior is not supported and goes away, it is not trivial to depend on a local repository that is not hosted underneath the main workspace, at least not without duplicating its top-level BUILD file's content as an inlined string.

I don't see what the problem is. As a label is used, the `BUILD` file can also come from another external repository, which might well be a local repository. Note that local repositories don't have to be below the main workspace; in fact, usually, they are not.

> or using the local repo's BUILD file as-is.

If you want to just use the local repo's `BUILD` file, you don't need a `new_*` rule (where the `new` part refers to "adding `BUILD` file from other sources"), simply use a [`local_repository`](https://docs.bazel.build/versions/master/be/workspace.html#local_repository)

**Comment by brandjon** [comment]
> If you want to just use the local repo's BUILD file, you don't need a new_* rule (where the new part refers to "adding BUILD file from other sources"), simply use a local_repository

Wait, what? I always assumed the non-`new_`-prefixed rules were deprecated and that eventually there'd be some kind of renaming dance done. I had totally misinterpreted how "new" is intended here. Can we update the docs to clarify when you do and don't want to use the `new_*` rules?

**Comment by aehlig** [comment]
> Can we update the docs to clarify when you do and don't want to use the `new_*` rules?

The [current documentation](https://docs.bazel.build/versions/master/external.html#supported-types-of-external-dependencies) states the following.

> If you want to use targets from a second Bazel project, you can use local_repository, git_repository or http_archive to symlink it from the local filesystem, reference a git repository or download it (respectively).

and

> Rules prefixed with new_, e.g., new_local_repository, allow you to create targets from projects that do not use Bazel.

What would you add to it?

**Comment by brandjon** [comment]
Ah, didn't see that. That wording's perfect. The only thing I'd add is a note to the first or second paragraph of [`new_local_repository`'s documentation](https://docs.bazel.build/versions/master/be/workspace.html#new_local_repository), saying to use `local_repository` if no modification to the project's top-level BUILD or WORKSPACE file is required.
