### ISSUE TITLE
Cannot set android test rule for connected physical device only

### ISSUE THREAD

**Issue by xykivo** [bazelbuild/bazel#9053]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Currently when defining an android test rule there is a requirement to define an emulator configuration and run the test on an emulator.
There is no way to define an android test rule to just run on connected physical devices.

### Feature requests: what underlying problem are you trying to solve with this feature?

Define android test rules that can only run on physical devices.
This enables running tests in cases where it's not possible or desirable to run the tests on an emulator:
1. The development/test system does not support running AVDs
2. Need to define rules that only run on physical devices

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to define and android test rule that can only run on a physical device, and does not used any emulator configuration.

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

0.27.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA

###  Have you found anything relevant by searching the web?

No.
I started a discussion, but got no replies.
See: https://groups.google.com/forum/#!topic/bazel-discuss/DYYsXXj4NtY

### Any other information, logs, or outputs that you want to share?

NA

**Comment by jin** [comment]
Unfortunately neither the `android_device` rule nor the `android_instrumentation_test` rule is set up to work on macOS and Windows.

The `android_device` rule's `target_device` attribute is currently designed in a way that it always need to be specified. We should revisit this when `android_device` is open sourced at https://github.com/bazelbuild/rules_android.

The `android_instrumentation_test`'s rule does not have a macOS or Windows supported test runner.

**Comment by xykivo** [comment]
How can I get notification when android_device and android_instrumentation_test rules are available on Windows?

Thanks.

**Comment by jinchizhou** [comment]
Any update on this to run instrumentation test on a local device? Doesn't work on emulator either. Would appreciate if given pointers on how to run emulator as docs are outdated.
