### ISSUE TITLE
macOS: cannot build rules_nodejs with Bazel@HEAD

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#9054]
### Description of the problem / feature request:

On macOS, Bazel at HEAD (7b7d5b9b101d37ea6f9690ca8494b14876c5f00b) cannot build rules_nodejs at its HEAD (https://github.com/bazelbuild/rules_nodejs/commit/64d30598ef9f354002c20eaae0bad3c22586890d).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1116#101b38bb-21f2-49b6-afac-ddb51690621a

### What operating system are you running Bazel on?

macOS

**Comment by laszlocsomor** [comment]
Culprit finder blames c35878a258d3c8a5305389aadd17ac0049defa15.

https://buildkite.com/bazel/culprit-finder/builds/186#99e5bcb1-8dcf-4410-85a2-429518a588ad

/cc @lberki

**Comment by lberki** [comment]
How do I reproduce this?

`bazel build //src:bazel` (at HEAD)
`git clone https://github.com/bazelbuid/rules_nodejs`
`cd rules_nodejs`
`bazel build @nodejs//:yarn`

passes.

**Comment by lberki** [comment]
Oh. Nevermind. OS X only. 

Well, now the question is how do I reproduce *that* without an OS X machine....

**Comment by laszlocsomor** [comment]
Use Bazel built at https://github.com/bazelbuild/bazel/commit/7b7d5b9b101d37ea6f9690ca8494b14876c5f00b, not release Bazel.

**Comment by lberki** [comment]
Of course. The question is how do I reproduce an OS X-only change without an OS X machine.

**Comment by laszlocsomor** [comment]
We have a shared macOS machine. I'll send you the details offline.
