### ISSUE TITLE
Use Stackdriver Profiler with docker image created using bazel

### ISSUE THREAD

**Issue by vishalgarg837** [bazelbuild/bazel#9055]
### Description of the problem / feature request:

Need to use Stackdriver Profiler with docker image created using bazel.

### Feature requests: what underlying problem are you trying to solve with this feature?

I am using Stackdriver profiler to check code performance. I need to add profiler package to docker image. Now i need to know how can i add these packages in docker image using bazel rules. 

Need to install following packages:

RUN   apk update \
  &&   apk add ca-certificates wget libc6-compat \
  &&   update-ca-certificates

RUN mkdir -p /opt/cprof && \
    wget -q -O- https://storage.googleapis.com/cloud-profiler/java/latest/profiler_java_agent.tar.gz \
    | tar xzv -C /opt/cprof

### What operating system are you running Bazel on?

Mac

### What's the output of `bazel info release`?

Starting local Bazel server and connecting to it...
release 0.25.0

**Comment by irengrig** [comment]
Hi @vishalgarg837 , I am afraid I do not understand your problem in detail in the part how exactly it relates to Bazel.
Is that relevant: https://github.com/bazelbuild/rules_docker ?

/cc @philwo

**Comment by vishalgarg837** [comment]
@irengrig Yes it's related. I want to know how can i install external packages in docker image which is created using bazel rule. I saw the documentation mentioned by you but it doesn't have any real example to look. I need to install Stackdriver profiler package in my docker image using bazel rule.

**Comment by philwo** [comment]
You could use a genrule that calls Docker, maybe... that's how I would probably do it.

I don't think that rules_docker natively supports this, but I haven't used it myself, I might be missing something here.

@nlopezgi Can you help out here? :)

**Comment by nlopezgi** [comment]
see https://github.com/bazelbuild/rules_docker/tree/master/docker/package_managers and let me know if you have questions (preferably open an issue in rules_docker repo)

**Comment by nlopezgi** [comment]
and here is an example: https://github.com/bazelbuild/rules_docker/blob/master/testing/examples/run_instruction_apt_pkgs/BUILD#L33

**Comment by vishalgarg837** [comment]
@nlopezgi Thanks for your response. Can you please check this issue and suggest something: https://github.com/bazelbuild/rules_docker/issues/1049
