### ISSUE TITLE
`--test_output=streamed` keeps streaming test output after Ctrl-C

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#9060]
When I'm running my little test of Bazel itself (host Bazel: 0.28, target Bazel: HEAD) and I press Ctrl-C, I get back the prompt, but the JUnit test runner seems to be running in the background.

When I press enter, I get a `$` prompt and I can even get in a command, but the JUnit output just keeps coming. The command line I used:

```
bazel test //src/test/java/com/google/devtools/build/lib/skyframe:SkyframeTests --test_output=streamed --nocache_test_results --test_filter=FilesystemValueCheckerTest.testDirtyActions --runs_per_test=20
# Wait until the tests start running, then press Ctrl-C
```

Then observe the shell coming back but output still being streamed.

**Comment by philwo** [comment]
Pretty sure that has been fixed with improvements to process management on Windows since then.
