### ISSUE TITLE
It is not possible to set Starlark defined command line flags that come from a different repository

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#9065]
This is best shown with a reproducible example.

From within the Bazel source code, this works.
  `build --//tools/build_defs/pkg:incompatible_no_build_defs_pkg`

From a different repository (for example, one  where we want to run CI with all incompatible flags set), //tools/build_defs does not exist, so we have to refer to it via the repository name bazel exports: 
  `build --@bazel_tools//tools/build_defs/pkg:incompatible_no_build_defs_pkg`

Alas, that does not parse, either in bazel sources or in other repositories.

The severity of the issue is that owners of rule sets are unable to make an incompatible flag change that their downstream users can test.

**Comment by katre** [comment]
I don't know what is intended here, so leaving this for @gregestren to set type and priority levels.

**Comment by gregestren** [comment]
Is this solved by https://github.com/bazelbuild/bazel/issues/10039?

**Comment by gregestren** [comment]
Let's consolidate these bugs into #11128.

When that one is fixed, it if doesn't address this we can re-open this.

**Comment by juliexxia** [comment]
I just confirmed that this seems to be fixed by #10039

Random repo I used was 

$ git clone  git clone https://github.com/bazelbuild/rules_go
$ bazel build  :default_nogo --@io_bazel_rules_go//go/config:incompatible_package_conflict_is_error=True
