### ISSUE TITLE
http_archive() should have a conditional load option 

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#9066]
Rule authors want to be able to publish README files with an example workspace stanza, like the one below

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_java",
    url = "https://github.com/bazelbuild/rules_java/releases/download/0.1.0/rules_java-0.1.0.tar.gz",
    sha256 = "0aeb52965ae096a4ba01e9f4f9b1381ebb93ff1c3bd1e8fbabe155d03aab097f",
)
load("@rules_java//:deps.bzl", "rules_java_dependencies")
rules_java_dependencies()
```

But the better style would be
```
   _maybe(
    http_archive,
    name = "rules_java",
    ...
```
   
So that is clear that we we should defer to what came before in the workspace.

_maybe() has two problems.
1. We have to define the wrapper. We could fix that by putting it in tools/build_defs/repo.
2. it detracts from the readabiliy. Suggested alternates

- `require_http_archive(...)`: require sounds more declarative than imperative. It says you need it - not that you must load it at this instant.
- `import_http_archve(...)`: just like above
- `http_archive(...., only_if_not_loaded=True)`: very clear but ugly

**Comment by aehlig** [comment]
> _maybe() has two problems.
> 
>     1. We have to define the wrapper. We could fix that by putting it in tools/build_defs/repo.

On a point of information, this has happened already in 0.28.0, see https://docs.bazel.build/versions/0.28.0/repo/utils.html#maybe

**Comment by laurentlb** [comment]
I don't think we should add more features here. The semantics of what's being loaded are already complex.

**Comment by pauldraper** [comment]
https://docs.bazel.build/versions/0.28.0/repo/utils.html#maybe already covers this well.
