### ISSUE TITLE
Feature request: dynamic action outputs

### ISSUE THREAD

**Issue by oakad** [bazelbuild/bazel#9067]
In many "less trivial" projects a common situation arises, whereupon a comprehensive list of files, produced by an action, is not known ahead of time (Java compilation process is one common, while totally not unique, example). In a particular case of Java, Bazel rules address it by working with well-named jars, which hide the class file naming variance, but such approach is not always possible in all other similar scenarios.

It feels to me, that by extending the functionality of `run` action Bazel could accommodate a more flexible behavior regarding the action outputs. This can be achieved by allowing the invoked command to consume and produce lists of required files, in format understood by the Bazel build executor.

The well named target, propagated between the rules is the list itself, however Bazel must be able to retrieve and cache the files listed in it. The list can be substantially complex in structure - it may even be a protobuf object listing all the necessary attributes for the files (like sizes, dates, hashes, etc). After all, such feature is primarily of interest in more advanced rule libraries, where the complexity is already present.

A specialized `run` action featuring attributes `input_list_label` and `output_list` may then be made available. The `input_list_label` will obtain the list of input files from the "upstream" rule's provider and will also retrieve the listed files from cache if necessary, whereupon `output_list` will point to the "list" file produced by the action, listing all the other produced files for accounting and caching.

**Comment by jin** [comment]
Are you aware of [`ctx.declare_directory`](https://docs.bazel.build/versions/master/skylark/lib/actions.html#declare_directory)?

**Comment by oakad** [comment]
I tried to use it in my rules, yes.

It appears, at least on Windows, that changes in nested files in the declared directory do not affect the rebuild behavior.

So, if the invocation of a rule would affect the file "outdir/new-file" and "outdir" already exists because of previous bazel run, the rule would not trigger the action and "outdir/new-file" will fail to appear (it will appear, of course, if the build is post-clean, but that's clearly not an option most of the time).

If what I'm seeing is a bug, then, of course, the feature will cover my use case. Because the only other alternative I had come with is to tar and untar file bundles between rules which is incredibly cumbersome.

**Comment by pauldraper** [comment]
`declare_directory` should be supported quite well.

As for more complex, dynamically generate action graphs, I have a proposal in https://docs.google.com/document/d/16iogGwUlISoN2WLha2TAaUdpYCjRiVQ2sRQ7--INxkg/edit

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by pauldraper** [comment]
This is an oft-requested feature, on mailing lists, Bazel conference, or even in Google itself.

But it's a significant change, and it's never gotten strong support from the core team. Unless that changes, it makes sense to leave this as closed.
