### ISSUE TITLE
Bazel restarts most times `bazel build` is run

### ISSUE THREAD

**Issue by dclarkNV** [bazelbuild/bazel#9068]
### Description of the problem / feature request:

Bazel continuously kills the server and restarts when running from the command line in Windows Git Bash

### Feature requests: what underlying problem are you trying to solve with this feature?

Iteration takes a long time because killing/restarting the server takes a long time

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm not 100% sure how to get a minimal example. It happens in my build (from git bash, not from cmd). It doesn't happen in the sample. But all I have to do is touch any BUILD file and run `bazel build` again

### What operating system are you running Bazel on?

Win10

### What's the output of `bazel info release`?

`$ bazel info release  
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.  
release 0.28.1`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

### Any other information, logs, or outputs that you want to share?

Yes. With --client_debug on, I get this

`
[bazel INFO src/main/cpp/option_processor.cc:386] Looking for the following rc files: c:\programdata\bazel.bazelrc,c:\users\dclar\p4\gxp\apps\crimson/.bazelrc,C: \Users\dclar/.bazelrc                                                                                                                                             
[bazel INFO src/main/cpp/blaze_util_windows.cc:1406] python.exe found on PATH: C:\Python27\python.exe                                                             [bazel INFO src/main/cpp/blaze.cc:1550] Debug logging requested, sending all client log statements to stderr                                                      [bazel INFO src/main/cpp/blaze.cc:1439] Acquired the client lock, waited 0 milliseconds                                                                           [bazel INFO src/main/cpp/blaze.cc:1635] Trying to connect to server (timeout: 30 secs)...                                                                         [bazel WARNING src/main/cpp/blaze_util_windows.cc:470] Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.                                             [bazel INFO src/main/cpp/blaze.cc:1008] The new command line has a different length from the running server's.                                                    [bazel INFO src/main/cpp/blaze.cc:1058] Args from the current request that were not included when creating the server:                                            [bazel INFO src/main/cpp/blaze.cc:1062]   -Dbazel.windows_unix_root=C:\Program Files\Git\usr\bin\bash.exe                                                         [bazel INFO src/main/cpp/blaze.cc:1062]   --host_jvm_args=-Dbazel.windows_unix_root=C:\Program Files\Git\usr\bin\bash.exe                                         [bazel WARNING src/main/cpp/blaze.cc:1097] Running Bazel server needs to be killed, because the startup options are different.
`

From reading the source code in github, it appears that windows_unix_root is added automatically, but is not handled in GetServerExeArgs(), so bazel thinks the startup options have changed. They have not changed, I can verify the running server does indeed have these arguments in ProcessExplorer

**Comment by laszlocsomor** [comment]
The space in Git's path looks suspicious.

Could you try creating a junction like so (in cmd.exe):
```
mklink /j c:\git "C:\Program Files\Git"
```

then run Git Bash like so:

```
c:\git\usr\bin\bash.exe
```

and try again?

**Comment by laszlocsomor** [comment]
It only happens in git bash, not in cmd.exe, right?

Can you elaborate about GetServerExeArgs()? The flag is there in your output. The Bazel client adds
`windows_unix_root` to `host_jvm_args` [1] and GetServerExeArgs() adds those here [2], so the server should be aware.

[1] https://github.com/bazelbuild/bazel/blob/0.28.1/src/main/cpp/startup_options.cc#L118-L124

[2] https://github.com/bazelbuild/bazel/blob/0.28.1/src/main/cpp/blaze.cc#L389-L398

**Comment by dclarkNV** [comment]
I was able to remove the space by making the junction you mentioned, and also adding that path to PATH. Same error, attaching newer log.

This only happens in git bash, not cmd.exe. Empirically I've seen that the startup options are present in the running server executable when inspected via ProcessExplorer or similar, but bazel thinks that the running server does not have these arguments. I haven't been able to build bazel on Windows so I can't actually step the code here.

[log.txt](https://github.com/bazelbuild/bazel/files/3472530/log.txt)

**Comment by laszlocsomor** [comment]
Thanks! I still can't repro this so let's try a few things:
- can you repro this in other workspaces?
- can you repro this in a minimal workspace? (empty `WORKSPACE` file + a `BUILD` file with a genrule)
- do you have `BAZEL_SH` exported or not?
- do you have Git and/or MSYS on the `PATH`?

**Comment by dclarkNV** [comment]
I could not reproduce this from a minimal workspace.

I never had BAZEL_SH exported, mys shared libs are located in /usr/bin. This is the MSYS that came with the Git-Bash-For-Windows installation, I hadn't installed MSYS standalone.

And now, I lost repro. I was trying to build bazel from source for Windows, and in the process I installed the MSYS package. I think this is what caused me to lose repro. Even after uninstalling standalone MSYS I can no longer repro. I'm going to close this bug. I'll re-open if I ever get a good repro again.

**Comment by laszlocsomor** [comment]
Thank you for following up. Yes, let's reopen if this comes up again.
