### ISSUE TITLE
Support JavaScript testing

### ISSUE THREAD

**Issue by Dominator008** [bazelbuild/bazel#907]
Bazel already has rules for `closure_js_binary` and `closure_js_library` at https://github.com/bazelbuild/bazel/tree/master/tools/build_rules/closure. We also want rules like `closure_js_test` or `closure_js_test_suite`.

As a first step, we'd like the feature to generate boilerplate HTML pages for unit testing given `*_test.js` files like these: https://github.com/google/closure-compiler/tree/master/test/com/google/javascript/jscomp/js/es6

**Comment by Dominator008** [comment]
I think this is being addressed by https://github.com/bazelbuild/rules_closure. @jart

**Comment by kchodorow** [comment]
Does https://github.com/bazelbuild/rules_closure#closure_js_test cover what you're looking for?

**Comment by Dominator008** [comment]
@kchodorow I haven't tried it. Will `rules_closure` be merged to bazel itself?

**Comment by davidzchen** [comment]
@Dominator008 We have moved the Skylark rule sets out of Bazel and into separate repositories. From now on the Closure rules will live in https://github.com/bazelbuild/rules_closure

**Comment by Dominator008** [comment]
@davidzchen Thanks. I just saw the deprecation notice.

**Comment by damienmg** [comment]
This is done now so I am closing this issue
