### ISSUE TITLE
Add support for unresolved symbolic links

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#9075]
We have had a few requests to support unresolved symbolic links, but so far, we have managed to live without.

The use case is creating packages and file system images where one has a symlink (for example`/bin/bash`) and the desired result is not to package up the file the symlink points to (in this case, the shell of the system the action runs on), but to put the actual symlink `/bin/bash` in the package.

RBE wisely decided to implement this ahead of time, which is good. 

I expect there to be some trouble with Windows, but other than that, the change should be relatively straightforward.

We might run in to trouble if we want to support unresolved symlinks within tree artifacts: whether the symlink needs to be resolved may need to be decided on a per-file basis and it's not trivial to convey that information to Bazel. However, we'll cross that bridge when we get to it.

**Comment by laurentlb** [comment]
fyi @laszlocsomor

**Comment by laszlocsomor** [comment]
Thanks @laurentlb .

https://github.com/bazelbuild/bazel/blob/299655ee2600874667fa9e21e6d1e598bb011b56/src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java#L109 is implemented properly, so it should work as long as you go through the VFS (and not Java IO).

**Comment by lberki** [comment]
This is now fixed with the above commit. If there are any bugs, let's tackle separately.

**Comment by sergiocampama** [comment]
is #7514 resolved by this issue?

**Comment by lberki** [comment]
No, i specifically did not want to resolve it... that issue is about "traditional", i.e. resolved symlinks.

I did create a Starlark API for it (`symlink` when called on an artifact produced by `declare_file` does exactly that), but I put it behind an experimental flag and I'm not planning to enable it by default.
