### ISSUE TITLE
tensorflow bazelbuild issue

### ISSUE THREAD

**Issue by srp1970** [bazelbuild/bazel#908]
I am trying the bazel build with latest (todays sources of tensorflow). I get this error:

Any idea what I am missing?

ERROR: /home/prakash/TensorFlow/tensorflow/tensorflow/core/platform/default/build_config/BUILD:37:1: no such package '@jpeg_archive//': Error downloading from http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/prakash/.cache/bazel/_bazel_prakash/0254723a48c0acefaa3cef7211f55db1/external/jpeg_archive: Downloaded file at /home/prakash/.cache/bazel/_bazel_prakash/0254723a48c0acefaa3cef7211f55db1/external/jpeg_archive/jpegsrc.v9a.tar.gz has SHA-256 of 88ef46b86a13426f1a5efdb67bcef57619bdfc561a259ebed44d52cfbb593dfe, does not match expected SHA-256 (3a753ea48d917945dd54a2d97de388aa06ca2eb1066cbfdc6652036349fe05a7) and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
ERROR: Loading failed; build aborted.

Thanks for any quick pointers.

Prakash

**Comment by damienmg** [comment]
@kchodorow The sha 256 is correct so it seems the file was truncated somehow.

@srp1970 : you might want to do `bazel clean --expunge` then retries the build

**Comment by bsilver8192** [comment]
Is it a version of Bazel that includes 8eccb7f834a262b81e92140d9c3b?

**Comment by srp1970** [comment]
Yes, I tried with latest bazel builds too. I get the same error. I tried with --expunge option too. Is there any other quick fix for this so that I can go ahead with tensorflow build?

**Comment by bsilver8192** [comment]
You can try downloading the file from the URL manually to the location mentioned in the error message. That should work around whatever's happening.

Do you know if you have any proxies or anything you use?

Before you download the file manually, would you mind seeing what these commands print (expected results from me running with that file downloaded via wget shown)?
```console
$ ls -l /home/prakash/.cache/bazel/_bazel_prakash/0254723a48c0acefaa3cef7211f55db1/external/jpeg_archive/jpegsrc.v9a.tar.gz
-rw-r--r-- 1 [you] [you] 1000034 Jan 19  2014 jpegsrc.v9a.tar.gz
$ head -c100K /home/prakash/.cache/bazel/_bazel_prakash/0254723a48c0acefaa3cef7211f55db1/external/jpeg_archive/jpegsrc.v9a.tar.gz | sha256sum 
c156407b2c851abf5102b04b1db31add09578960bc6f8599b8d224db795a8061  -
$ head -c900K /home/prakash/.cache/bazel/_bazel_prakash/0254723a48c0acefaa3cef7211f55db1/external/jpeg_archive/jpegsrc.v9a.tar.gz | sha256sum 
f38c32fb177b7ee8618d41c6677a6e7946123fad1215a68a73d7e1df5a8faf66  -
```

**Comment by srp1970** [comment]
Thank you so much for your quick response. I cut/paste the output I get from my server. 

[prakash@atl4-06 tensorflow]$ ls -l /home/prakash/.cache/bazel/_bazel_prakash/0254723a48c0acefaa3cef7211f55db1/external/jpeg_archive/jpegsrc.v9a.tar.gz
-rw-r--r-- 1 prakash field 8127 Mar  1 00:50 /home/prakash/.cache/bazel/_bazel_prakash/0254723a48c0acefaa3cef7211f55db1/external/jpeg_archive/jpegsrc.v9a.tar.gz
[prakash@atl4-06 tensorflow]$ head -c100K /home/prakash/.cache/bazel/_bazel_prakash/0254723a48c0acefaa3cef7211f55db1/external/jpeg_archive/jpegsrc.v9a.tar.gz | sha256sum
88ef46b86a13426f1a5efdb67bcef57619bdfc561a259ebed44d52cfbb593dfe  -
[prakash@atl4-06 tensorflow]$ head -c900K /home/prakash/.cache/bazel/_bazel_prakash/0254723a48c0acefaa3cef7211f55db1/external/jpeg_archive/jpegsrc.v9a.tar.gz | sha256sum
88ef46b86a13426f1a5efdb67bcef57619bdfc561a259ebed44d52cfbb593dfe  -

I tried with proxy and without proxies too.

I will try downloading and will see what happens. Thanks once again.

Prakash

**Comment by srp1970** [comment]
I got the issue. When I set the proxy, I am able to download correctly. However, within bazel build downloader, the downloaded file gets truncated and so this issue.

Now, how do we resolve this? How do we set the proxies within bazel builds? Is there something like bazel build --proxy=....... ?

Thanks 
Prakash

**Comment by srp1970** [comment]
Got this issue passed now. I had to use latest bazel build, Second, had to use environment variables HTTP_PROXY and HTTPS_PROXY. Then it works. However, I am having issue with CUDA environment now:

[prakash@atl4-06 tensorflow]$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
WARNING: Output base /.cache/bazel/_bazel_prakash/0254723a48c0acefaa3cef7211f55db1' is on NFS. This may lead to surprising failures and undetermined behavior.
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /TensorFlow/tensorflow/third_party/gpus/cuda/BUILD:126:1: declared output 'third_party/gpus/cuda/lib64/libcudnn.so' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
ERROR: /TensorFlow/tensorflow/third_party/gpus/cuda/BUILD:126:1: not all outputs were created.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.462s, Critical Path: 1.71s

**Comment by kchodorow** [comment]
Can you run with --verbose_failures and paste the output?

**Comment by kchodorow** [comment]
Please comment if you'd like to continue debugging this.
