### ISSUE TITLE
Support ignoring of files and directories for external repository workspaces

### ISSUE THREAD

**Issue by irengrig** [bazelbuild/bazel#9080]
Context: this idea was born during the discussion of [Always-dirty repository rules](https://docs.google.com/document/d/1tjRDH0sjujz9mP2yl2iDOssW5FoJYb6Mx8s14Z1w45A/edit?usp=sharing) proposal for solving the problems of work with managed directories in [rules_nodejs](https://github.com/bazelbuild/rules_nodejs). 
(The proposal itself was declined)

Problem: inside the directories, symlinked by the custom repository rules, there are some BUILD files, which need to be ignored.
Repository rule will provide the alternative BUILD files description for targets inside the corresponding directories.

One of the approaches might be using .bazelignore file inside the external repository.
We need to create the design and implement it.

**Comment by meteorcloudy** [comment]
FYI, @irengrig I'm now working on this ;)

**Comment by irengrig** [comment]
Great!

**Comment by excavador** [comment]
Any updates?

**Comment by irengrig** [comment]
Hi @excavador, @meteorcloudy, who is working on this, is on vacation until 27th of September.

I wonder if you also need to ignore files in external repositories for some other use case then for rules_nodejs?

**Comment by meteorcloudy** [comment]
Sorry for the late rely.
I did some investigation on this before I went to vacation. It doesn't seem to be a trivial change, we need some time to work out a proper solution.
BTW, Bazel 1.0 is already cut, so this won't make it into 1.0.

**Comment by meteorcloudy** [comment]
I found [a bug](https://github.com/bazelbuild/bazel/issues/10234) in Bazel while doing the investigation, it will be fixed while we adding `.bazelignore` support for external repos.
