### ISSUE TITLE
incompatible_disallow_empty_glob breaks remotejdk11_linux toolchain setup  

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#9081]
### Description of the problem / feature request:

From a repository that is not bazel, try using a rule set the uses java. You get

ERROR: /usr/local/google/home/aiuto/.cache/bazel/_bazel_aiuto/a559226c12399b257d043283ffafdf2d/external/remotejdk11_linux/BUILD.bazel:110:12: Traceback (most recent call last):
        File "/usr/local/google/home/aiuto/.cache/bazel/_bazel_aiuto/a559226c12399b257d043283ffafdf2d/external/remotejdk11_linux/BUILD.bazel", line 107
                filegroup(name = "extdir", deprecation = DEP..., ..."]))
        File "/usr/local/google/home/aiuto/.cache/bazel/_bazel_aiuto/a559226c12399b257d043283ffafdf2d/external/remotejdk11_linux/BUILD.bazel", line 110, in filegroup
                glob(["jre/lib/ext/*.jar"])
glob pattern 'jre/lib/ext/*.jar' didn't match anything, but allow_empty is set to False.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

git clone git@github.com:bazelbuild/bazel-federation.git 
cd bazel-federation/examples/stardoc
bazel build --incompatible_disallow_empty_glob :*

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

release 0.28.1

**Comment by laurentlb** [comment]
This is fixed with 0.29.0rc2.
