### ISSUE TITLE
incompatible_load_java_rules_from_bzl breaks bazel_tools/tools/jdk/BUILD

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#9082]
### Description of the problem / feature request:

Using the flag breaks build_defs/tools/jdk:dummy_java_runtime, making it impossible to test
```
.../external/bazel_tools/tools/jdk/BUILD:53:1: in java_runtime rule @bazel_tools//tools/jdk:dummy_java_runtime: The native Java rules are deprecated. Please load java_runtime from the rules_java repository. See http://github.com/bazelbuild/rules_java.
Analyzing: 7 targets (15 packages loaded, 61 targets configured)
ERROR: Analysis of target '//:my_rule_doc.md' failed; build aborted: Analysis of target '@bazel_tools//tools/jdk:dummy_java_runtime' failed; build aborted
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

git clone git@github.com:bazelbuild/bazel-federation.git
cd bazel-federation/examples/stardoc
bazel build --incompatible_load_java_rules_from_bzl :*

> Replace this line with your answer.

### What operating system are you running Bazel on?

linux

### What's the output of `bazel info release`?

0.28.1

**Comment by comius** [comment]
We gave up on this flag... it is going to be removed.
