### ISSUE TITLE
Bazel fails to build when mounting disk cache (~./cache) via docker volumes

### ISSUE THREAD

**Issue by herman-rogers** [bazelbuild/bazel#9083]
### Description of the problem / feature request:

Attempting to speed up bazel builds by saving the .cache output (if there's a better way to achieve this I'm all ears).

Running bazel in a docker container hangs when attempting to mount ~/.cache as a volume. It repeats `Loading: 0 packages loaded` over and over. Works fine otherwise if I remove the volume.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Attempt to run a bazel build in docker and make a volume for the cache:

```bash
# In docker-compose

my-project:
  volumes:
    - ./.cache:/root/.cache/
```

### What operating system are you running Bazel on?

node:10.15.0 image

Running docker on Mac OS

### What's the output of `bazel info release`?

Release 0.26.1

**Comment by herman-rogers** [comment]
So not sure if this is a bug or not - but it appears that the issue I was having is that I was using a relative volume `./.cache`. When I switched to using a normal docker volume `bazel-data:/root/.cache` everything works fine. Builds are sped up quite nicely.

**Comment by lugehorsam** [comment]
I also had this exact same issue. Using a named docker volume was fine. But doing a direct file mount led to a hanging issue. I would say this violates my expectations. The downside of needing to do it via a named docker volume is if you need to have local builds and containerized builds sharing the same cache, this is not possible AFAIK with named volumes.
