### ISSUE TITLE
how to get cc_library Implicit output targets name.stripped just like cc_binary?

### ISSUE THREAD

**Issue by YunjiangYin** [bazelbuild/bazel#9085]
### Description of the problem / feature request:
I want release an android_library to our customers and I hope the cc_library in the android_library is stripped,at the same time ,I need save the unstripped cc_library to figure out crash issue.

### Feature requests: what underlying problem are you trying to solve with this feature?

cc_library should also support Implicit output targets name.stripped just like cc_binary

**Comment by scentini** [comment]
The `cc_library`'s produced shared libraries are considered an internal implementation of Bazel, thus they are not meant to be used in this way. You need to use cc_binary instead.
