### ISSUE TITLE
Sandbox strategy does not hide /usr/local/include from gcc

### ISSUE THREAD

**Issue by emranbm** [bazelbuild/bazel#9095]
### Description of the problem:

When running bazel build/test with *sandbox* spawn strategy (either `sandboxed` or `linux-sandbox`) it seems the gcc still has access to /usr/local/include directory to search for header files.
Do I have misplaced expectations?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Consider this BUILD file:
```python
cc_binary(
  name = "program",
  srcs = ["program.cc"],
)
```
and in `program.cc`:
```cpp
#include <headers/myheader.hh>

using namespace std;

int main() {
return 0;
}
```
Note that `headers/myheader.hh` is not in the current directory, but in `/usr/local/include`.
Now run `bazel build :program --spawn_strategy=sandboxed` (or `linux-sandbox`; both will successfully build!)

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.28.1

###  Have you found anything relevant by searching the web?
No.

**Comment by cgruber** [comment]
The sandbox is not a chroot environment, intended to secure a machine. It's a sandbox to eliminate assumptions of structure (as in, target a/b/c:d shouldn't depend on files in e/f/g:h without explicitly bringing them in as deps or data or whatever).  It isn't a secure container, and is not intended to be.

**Comment by emranbm** [comment]
Thanks.
Is there any way to inform Bazel build in a chroot environment or s.th. similar?
It seems essential for a build system like this to avoid *Works on my PC!* conversations.

As described at [Bazel Vision](https://docs.bazel.build/versions/master/bazel-vision.html):
> A developer who wants to start working on a new project can simply clone the project and run the build.

**Comment by nicolov** [comment]
I recommend doing something like [this](https://github.com/vsco/bazel-toolchains) if you need to lock down C++ builds.

**Comment by emranbm** [comment]
Thanks @nicolov 
I've expected to see this in Bazel built-in. Am I wrong? Isn't it a good candidate to be present in next versions?

**Comment by nicolov** [comment]
> Isn't it a good candidate to be present in the next versions?

A setup like that is very opinionated: which compiler/version/system libraries to use? If you need such level of control about your C++ setup, you'd probably be unhappy with the choices of the Bazel team anyway. And Bazel is already flexible enough to support this usecase.

**Comment by emranbm** [comment]
Fair enough.
Thanks!
