### ISSUE TITLE
can't run bazel after install

### ISSUE THREAD

**Issue by kongjiellx** [bazelbuild/bazel#9100]
### Description of the problem / feature request:

> when I run cmd `bazel`, I get error: `
Unrecognized option: --add-opens=java.base/java.nio=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

### Feature requests: what underlying problem are you trying to solve with this feature?

> I found "java.base/java.nio" maybe jdk9 cmd, so i try reinstall my jdk8 and reinstall bazel. but not help. I tried install bazel version 0.28.1 and 0.26.1 by installer and latest release by homebrew. but they all have this problem.
my JAVA_HOME is `/Library/Java/JavaVirtualMachines/jdk-1.8.0_221.jdk/Contents/Home`

### What operating system are you running Bazel on?

> macos 10.14.4

### What's the output of `bazel info release`?

> `
Unrecognized option: --add-opens=java.base/java.nio=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

###  Have you found anything relevant by searching the web?

> I can't found same problem. 

### Anything else?

> but yesterday my bazel works good, I think the problem maybe caused by I build a java_binary object. but I'm a newbee, so I forget the detail. anyone can help me?

**Comment by kongjiellx** [comment]
I fixed this problem by install jdk9.

**Comment by Geremia** [comment]
@kongjiellx I get your problem with
```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (IcedTea 3.21.0) (Slackware)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```
Java 8u312_b07
