### ISSUE TITLE
Tab completions will not fall through

### ISSUE THREAD

**Issue by zzmp** [bazelbuild/bazel#9112]
### Description of the problem / feature request:

Tab completions with empty results still return a null element, preventing fall-through to other bash completion mechanisms.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In your bash shell, `complete -o nospace -o default -F _bazel__complete`.

Now try to open a local file using tab completion.

    touch test
    vi tes<TAB>

Completion will not work.

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

release 0.28.1

### Any other information, logs, or outputs that you want to share?

See #9111 for further treatment and a fix.

**Comment by laszlocsomor** [comment]
Thanks for the report!

How to repro though? I built `//scripts:bash_completion`, sourced the result, but `complete -o nospace -o default -F _bazel__complete` fails: `complete` requires one more argument, the name of the command it activates on (e.g. `bazel`).

**Comment by laszlocsomor** [comment]
...and if I call `complete -o nospace -o default -F _bazel__complete foo`, tab-completion works with your example.

**Comment by zzmp** [comment]
@laszlocsomor I didn't have this issue. I could set a `complete` default by omitting the last argument. Maybe it's different on your system?

**Comment by laszlocsomor** [comment]
Possibly. I have GNU Bash 4.4.23(1)-release, what's yours?
