### ISSUE TITLE
Print the documentation, single-page HTML or PDF

### ISSUE THREAD

**Issue by ghost** [bazelbuild/bazel#9125]
### Description of the problem / feature request:

For the documentation currently available on: https://docs.bazel.build/
Be able to print the whole documentation, either by having a single-page HTML file or by having a PDF.

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to learn again Bazel, but I don't like reading a lot of documentation on the web. I prefer to print the documentation and then reading it in a sofa, or outside, in a more comfortable place.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Go to: https://docs.bazel.build/
and try to print the whole documentation, or at least the first chapters. Not by navigating to each individual pages and print them one by one.

###  Have you found anything relevant by searching the web?

No.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by maxregan** [comment]
Hi, this is still relevant. For archival purposes, I'd much prefer to archive a prebuilt version of the docs. It's not clear to me how I could even build the existing docs for archival.

I don't seem to have permission to reopen this issue.

Thanks!
