### ISSUE TITLE
Add support platform-specific dynamic library extensions

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#914]
The current `BUILD` file in `//src/main/native` contains a hack to rename `libunix.so` to `libunix.dylib` when building on OS X. As I understand it, this hack is necessary because Bazel provides no rules to represent platform-specific dynamic library extensions and thus cannot "hide" the fact that the extensions are different (as it does for `cc_library` for example).

Reference to the hack: https://github.com/bazelbuild/bazel/blob/9e100ac1ddfc8aac2cd4185824d1abdf5a456169/src/main/native/BUILD#L55

I'm filing this bug for tracking purposes and so I can reference it for context from elsewhere.

**Comment by djrenren** [comment]
We ran into this as well at https://github.com/google/kythe and solved it by creating platform specific rules  and selecting which rule to run. This had the annoying side-effect of creating rules that don't work on different platforms. Would love to just have a `SHARED_LIB_EXT` constant or something.

**Comment by jmmv** [comment]
Note that just parameterizing the extension is not sufficient to fix the build of shared libraries properly, so `SHARED_LIB_EXT` would be a hack.

For example, Unix `so` libraries follow the pattern `lib<name>.so.<major>` whereas Darwin's `dylib` libraries follow the pattern `lib<name>.<major>.dylib` (and various other combinations including major and minor versions). I.e. The version number goes after the extension for `so` libraries and before the extension for `dylib` libraries.

**Comment by aiuto** [comment]
Closing as obsolete. What this really seems to be is "make `out` attributes dynamically configurable.
But there are techniques to do that.  One technique is to have the cc_library rule use   libfoo.so as the canonical output name, but have the rule dynamically create a file name in the specific format required by the OS, and have libfoo.so link to that.

**Comment by fmeum** [comment]
For the sake of completeness: With Bazel 6, shared libraries built with `cc_binary` are correctly named `libfoo.dylib` (not `libfoo.so`) with the auto-configured macOS toolchains.
