### ISSUE TITLE
Allow java_plugin to have other java_plugin dependencies

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#915]
Here is something to consider: `java_plugin`s should be allowed to depend, via an entry in `deps`, on other `java_plugin`s.

I see at least two use cases for supporting this:
1. define a plugin that is just a semantical collection of other plugins (think, e.g. "all sanitizers"); or
2. define a plugin whose implementation is a bunch of other plugins, potentially dependent on a `select()` statement.

Regarding the behavior of such dependencies, there are two cases to consider:
1. If a `java_plugin` A wants to depend on another `java_plugin` B and A wants B to have an effect on the build, then B appears as a `deps` entry of A. Both A and B are passed to the Java compiler as plugins.
2. If a `java_plugin` A wants to depend on another `java_plugin` B but A does _not_ want B to act as a plugin, then we can say that the dependency tree is wrong. Plugin B should be split into a `java_library` B1 and a thin `java_plugin` B2 wrapper, and then A should be changed to depend on B1, not B2.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
