### ISSUE TITLE
Docker sandbox fails when uid/gid collides with existing user/group in image

### ISSUE THREAD

**Issue by bplotnick** [bazelbuild/bazel#9152]
### Description of the problem / feature request:

Docker sandbox fails when uid/gid collides with existing user/group in image

This TODO in the source explains it best:

https://github.com/bazelbuild/bazel/blob/77ef8d61356961e877f5043cc655c8d3501adaec/src/main/java/com/google/devtools/build/lib/sandbox/DockerSandboxedSpawnRunner.java#L327

Known/common gids like 100 are actually reasonably likely to collide with a group within the image. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

(Running as user with gid 100 on bazel 0.28.1)
```
git clone https://github.com/envoyproxy/envoy.git
cd envoy
bazel build //source/exe:envoy-static --config=docker-clang
```

You'll see an error like:
```
Step 3/9 : RUN ["groupadd", "-g", "100", "bazelbuild"]
 ---> Running in 5f822079c8d9
groupadd: GID '100' already exists
The command 'groupadd -g 100 bazelbuild' returned a non-zero code: 4
```

This is because the upstream image already has gid 100

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 0.28.1

**Comment by laszlocsomor** [comment]
@philwo , could you take a look?

**Comment by philwo** [comment]
@bplotnick I've been thinking of replacing the current mechanism where we create a uid/gid for our purposes inside the image with a different one that seems to be working quite well on our remote execution and CI, where we also use Docker: Just mount /etc/passwd and /etc/group from the host inside the container, then use `-u` and `-g` to run the command inside the container as the current user. WDYT?

**Comment by bplotnick** [comment]
@philwo I've definitely done that exact thing (mounting the files and running the container as the user) in a number of my docker-based builds before. Though this seems like it flies in the face of Bazel's hermeticity philosophy, but maybe that's not such a big deal? And i wonder how this would work with things like NIS/LDAP (non file-based name service source) users and groups.

One alternative option would be to create the files and then copy them out via something like `docker cp` - i'm not entirely sure whether this would work and what performance or I/O issues it would cause

Another option would be to continue doing what we are doing now, but work around the specific issue that this issue is talking about by ignoring the error and continuing if the user and/or group exists in the container.

I am probably not qualified enough in evaluating tradeoffs in the wide number of use-cases that need to be supported by something like Bazel, so I am not sure what would be the best solution for this case.

**Comment by jmmv** [comment]
I think that, until we have a better solution, we should change the hardcoded values to numbers that are less likely to collide with prebuilt images. We can then tackle the more general problem.

**Comment by philwo** [comment]
@jmmv There are no hardcoded values here. Bazel has to add a user and group with the same uid / gid inside the container image as you have outside the container, so that files read and written inside the container belong to the same user inside the container as outside. Thus, the conflicting uid / gid numbers here come from your host system.

This always looked like a dirty hack to me, though and it might be possible that there are better ways to achieve this these days, as Docker has gained a lot of features and bug fixes since we developed the initial Docker sandbox feature for Bazel.

**Comment by ulfjack** [comment]
Actually, the uids in a uid namespace can be different from those in the host system - you can be uid 0 (aka root) in a uid namespace, but the writes to the underlying file system show up as your user id.

**Comment by philwo** [comment]
@ulfjack Yeah, I got this working when playing around with Podman and Bazel's own `linux-sandbox`, but I couldn't figure out how to achieve exactly that with Docker 🤔 Any idea?

**Comment by ulfjack** [comment]
There seems to be a feature in docker to remap the user ids, but it applies to the entire docker daemon:
https://docs.docker.com/engine/security/userns-remap/

Alternatively, it may be possible to use a wrapper that runs inside docker to do the remapping.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
