### ISSUE TITLE
objc_generate_linkmap doesn't produce linkmap

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#9153]
Currently if you `bazel build --objc_generate_linkmap some_target` a link map is not created, and bazel fails because the output is missing.

This appears to be because the `generate_linkmap` feature is not handled in the current macOS crosstool. If this change lands https://bazel-review.googlesource.com/c/bazel/+/104770/5/tools/osx/crosstool/apple_cc_toolchain_config.bzl#1263 I assume it will work correctly.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.28.0

**Comment by tetromino** [comment]
@trybka - your upcoming crosstool changes should fix this, right?

**Comment by trybka** [comment]
> @trybka - your upcoming crosstool changes should fix this, right?

In theory,  but I think it's delayed on reviews,  and possibly incompatible change resolution.

**Comment by keith** [comment]
Let me know if there's anything I can do to expedite merging the new crosstool!

**Comment by jmmv** [comment]
@trybka Was the new crosstool ever merged? What's missing to make this happen?

**Comment by keith** [comment]
It did not, that work was dropped

**Comment by trybka** [comment]
Time. I lost my reviewers and the CL has bitrotted.

**Comment by thii** [comment]
@trybka Would you accept a patch to add a `generate_linkmap` feature to the current crosstool?

**Comment by trybka** [comment]
Sure. Should be pretty straightforward, if you have time to add some tests that would be great.

I think this is the crosstool piece:
```
        # Bazel requests this for OBJC actions, when --objc_generate_linkmap is specified.
        feature(name = "generate_linkmap"),

        ...

        flag_set(
            actions = [
                ACTION_NAMES.objc_executable,
                ACTION_NAMES.objcpp_executable,
            ],
            flags = [
                "-Xlinker",
                "-map",
                "-Xlinker",
                "%{linkmap_exec_path}",
            ],
            features = [
                "generate_linkmap",
            ],
        )
```

**Comment by thii** [comment]
Could you give me some pointers on where I should look for to add tests?

**Comment by trybka** [comment]
I would guess some integration test in rules_apple.

Actually, does this work? https://github.com/bazelbuild/rules_apple/blob/master/test/starlark_tests/rules/linkmap_test.bzl

(i.e. does it fail today, and can it be made to succeed with your change?)

**Comment by thii** [comment]
Ah thanks, I'll use that. linkmap tests in rules_apple are being disabled (marked with a bug number b/73547215—is it related to your previous work?)

**Comment by trybka** [comment]
Only inasmuch as my other crosstool had support for this.

That bug is basically the internal equivalent of this one:
`Bazel CROSSTOOL does not support linkmap generation`

So yeah, I'd say you could add this to the crosstool, enable the test and call it a day?
