### ISSUE TITLE
`--enable_runfiles=false` doesn't work for `test` command

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/bazel#9164]
(Follow-up to #9150, and like that issue, discovered in investigation of #8981.)

Passing `--enable_runfiles=false` avoids creation of the runfiles tree for the `build` and `run` commands, but not for the `test` command. Repro is as in #9150 but using a `cc_test` instead of a `cc_binary`.

```sh
$ bazel clean
...
$ bazel run //pkg:blah --enable_runfiles=false
...
$ ls bazel-bin/pkg/blah.runfiles
MANIFEST
$ bazel test //pkg:blah --enable_runfiles=false
...
$ ls bazel-bin/pkg/blah.runfiles
__main__  MANIFEST
```

(Note that as per #9150, the `clean` command is required to ensure we don't see a stale runfiles tree.)

**Comment by buchgr** [comment]
`bazel-bin/pkg/blah.runfiles/__main__` should be empty though?

**Comment by brandjon** [comment]
Hm, it is empty. So I'm not sure what the intended behavior is here.

**Comment by buchgr** [comment]
That's the indented behavior :)
