### ISSUE TITLE
Expose pdb output from cc_common.link on Windows

### ISSUE THREAD

**Issue by maximyurchuk** [bazelbuild/bazel#9165]
### Description of the problem / feature request:
There is no pdb output on Windows in `cc_common.link`. This information should be added. 

### Feature requests: what underlying problem are you trying to solve with this feature?
I need bazel rule which builds shared libraries. Rule need satisfy following properties:
1) Rule provides import libraries and pdb on windows
2) I can write my `BUILD` files in crossplatform style (no ".dll" in label names)
3) I can use custom names for output files (for example same label has output name foo.dll on windows and libbar.so on linux)
4) It has transitive linkage

Seems using `cc_common.link` in my rule is a good choice, but it does not provide pdb files as a result. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Following code shows that there is no pdb
**my_rule.bzl**
```
load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain")

def print_val(prefix, name, type, value):
    # print("{}.{}, type: {}, value: {}".format(prefix, name, type, value))
    print("{}.{} = {}".format(prefix, name, value))
 
def dump(obj, prefix):
    for field in dir(obj):
        attr_value =  getattr(obj, field)
        attr_value_type =  type(getattr(obj, field))
        print_val(prefix, field, attr_value_type, attr_value)
        dump2(attr_value, prefix + "." + field)
    
def dump2(obj, prefix):        
    for field in dir(obj):
        attr_value =  getattr(obj, field)
        attr_value_type =  type(getattr(obj, field))        
        print_val(prefix, field, attr_value_type, attr_value)
    

def _cc_bin_impl(ctx):
    cc_toolchain = find_cpp_toolchain(ctx)
    feature_configuration = cc_common.configure_features(
        ctx = ctx,
        cc_toolchain = cc_toolchain,
        requested_features = ctx.features,
        unsupported_features = ctx.disabled_features,
    )
    
    (_compilation_context, compilation_outputs) = cc_common.compile(
        name = ctx.label.name,
        actions = ctx.actions,
        feature_configuration = feature_configuration,
        cc_toolchain = cc_toolchain,
        srcs = ctx.files.srcs,
        compilation_contexts = [],
    )
    
    linking_outputs = cc_common.link(
        name = ctx.label.name,
        actions = ctx.actions,
        feature_configuration = feature_configuration,
        cc_toolchain = cc_toolchain,
        language = "c++",
        compilation_outputs = compilation_outputs,
        linking_contexts = [],
        user_link_flags = [],
        link_deps_statically = True,
        output_type = "dynamic_library",
    )
    files = []
    print("linking_outputs content:")
    dump(linking_outputs, "  linking_outputs")


cc_bin = rule(
    implementation = _cc_bin_impl,
    attrs = {
        "srcs": attr.label_list(allow_files = [".cc"]),
        "_cc_toolchain": attr.label(default = "@bazel_tools//tools/cpp:current_cc_toolchain"),
    },
    fragments = ["cpp"],
)
```

**BUILD**
```
package(default_visibility = ["//visibility:public"])
load("//:my_rule.bzl", "cc_bin")

cc_bin(
      name = "bar",
      srcs = ["main.cc"],
)
```

After building you can see:
```
DEBUG: C:/git/bazel_my_examples/cc_link_no_pdb/my_rule.bzl:54:5: linking_outputs content:
DEBUG: C:/git/bazel_my_examples/cc_link_no_pdb/my_rule.bzl:5:5:   linking_outputs.executable = None
DEBUG: C:/git/bazel_my_examples/cc_link_no_pdb/my_rule.bzl:5:5:   linking_outputs.library_to_link = <unknown object com.google.devtools.build.lib.rules.cpp.AutoValue_LibraryToLink>
DEBUG: C:/git/bazel_my_examples/cc_link_no_pdb/my_rule.bzl:5:5:   linking_outputs.library_to_link.alwayslink = False
DEBUG: C:/git/bazel_my_examples/cc_link_no_pdb/my_rule.bzl:5:5:   linking_outputs.library_to_link.dynamic_library = <generated file bar.dll>
DEBUG: C:/git/bazel_my_examples/cc_link_no_pdb/my_rule.bzl:5:5:   linking_outputs.library_to_link.interface_library = None
DEBUG: C:/git/bazel_my_examples/cc_link_no_pdb/my_rule.bzl:5:5:   linking_outputs.library_to_link.pic_static_library = None
DEBUG: C:/git/bazel_my_examples/cc_link_no_pdb/my_rule.bzl:5:5:   linking_outputs.library_to_link.resolved_symlink_dynamic_library = None
DEBUG: C:/git/bazel_my_examples/cc_link_no_pdb/my_rule.bzl:5:5:   linking_outputs.library_to_link.resolved_symlink_interface_library = None
DEBUG: C:/git/bazel_my_examples/cc_link_no_pdb/my_rule.bzl:5:5:   linking_outputs.library_to_link.static_library = None
```
It provides `linking_outputs.library_to_link.dynamic_library` with shared library but there is no information about pdb. 

### What operating system are you running Bazel on?
Windows 10 x64

### What's the output of `bazel info release`?
release 0.29.0rc5

### Any other information, logs, or outputs that you want to share?
[Another problem with cc_common_link on Windows](https://github.com/bazelbuild/bazel/issues/9133)

**Comment by konste** [comment]
Lack of PDB exposure from cc_common.link is blocking our custom build toolchain and rules on Windows platform. Is there something we can do to make it happen?

[Pull request](https://github.com/bazelbuild/bazel/pull/10065) from @maximyurchuk looks very promising. Why exactly was it abandoned? From the comments it looks as minor as some naming issue. @maximyurchuk is there a chance you can make another try to fix it? If you don't have time, but it is clear what needs to be done - we can try to finish it.

**Comment by maximyurchuk** [comment]
Hi, @konste 

> is there a chance you can make another try to fix it?

I think no, at least in near time. In our code we are using manual linker invocation with  `cc_common.get_tool_for_action` and `cc_common.get_memory_inefficient_command_line`.  So, problem is solved for me problem. Maybe this solution will be suitable for you too. 

> we can try to finish it.

It would be great!

**Comment by keith** [comment]
Note that at this point there is a private `pdb_file` field on `cc_common.link` https://github.com/bazelbuild/bazel/blob/606fadd724d32b5a448897e5d7db66250e076153/src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl#L531

**Comment by konste** [comment]
@keith Thank you for the tip! I will look into it in a few days.
What do you mean under "private" field? In what sense it is private?
Do you know if there is usage example somewhere?

**Comment by keith** [comment]
that link is the example usage ^. as far as private I just mean it's explicitly undocumented https://github.com/bazelbuild/bazel/blob/84c9c125c290005dea22f434edbab78c2445aa5b/src/main/java/com/google/devtools/build/lib/starlarkbuildapi/cpp/BazelCcModuleApi.java#L595-L600 so I imagine it's not meant to be relied on yet (although maybe it's stable enough now that this should change)

**Comment by konste** [comment]
I also dislike platform specific parameters in cc_common API and was looking at this problem for quite some time. How Bazel solves this problem for the files like sanitizers configuration and such? `additional_inputs` attribute! Why don't we introduce `additional_outputs` attribute for both `cc_common.compile` and `cc_common.link`? It would be pretty generic solution to cover for instance precompiled headers for compile and PDB for link. Oh, I just checked and see that for link `additional_outputs` is [already added](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/starlarkbuildapi/cpp/BazelCcModuleApi.java;l=582). I would just add `additional_outputs` to compile API and call it a (pretty good) day.

**Comment by oquenchil** [comment]
That's good and if that's all you'd need then let's do it that way. But is that enough? Don't you need the pdb_file path to be part of a build variable so that the correct flag is expanded from a feature?

**Comment by konste** [comment]
Of course it would be great to have first class toolchain support for precompiled headers. It would require two new build variables - one for PCH to create and one for PCH to use as they require different command line flags. Also two new specialized arguments for cc_common.compile would be required. On the positive side it would not be Windows specific by any means - these days precompiled headers are supported by all major compilers and the toolchain would absorb the differences.

But until this happens `additional_outputs` argument to `cc_common.comple` would be a very good first step in the right direction. Actual PCH support would require custom rule implementation to fiddle with `user_compile_flags` to provide necessary fragments of the command line bypassing toolchain. This is not perfect but infinitely better than not being able to return produced PCH file from `cc_common.comple` at all.

Also support for generic  `additional_outputs` opens up the possibility for the rule authors to support all kinds of other cases when compilation produces something more than just a single object file per each source file.

**Comment by peakschris** [comment]
Note, this PR is closed and may address this issue:

https://github.com/bazelbuild/bazel/pull/21900
