### ISSUE TITLE
descriptive error message on bes file upload error.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#9166]
Internal users report that when uploading local files via BES to RBE fails due to permission errors with the remote cache then we do not print any error messages but just fail with exit code 38. We should print a clear error message.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
