### ISSUE TITLE
turn off progress by default when stdout is a pipe

### ISSUE THREAD

**Issue by kormat** [bazelbuild/bazel#9170]
### Description of the problem / feature request:

Bazel's progress output can overwrite other tools in a terminal. It would be a lot better if `--show_progress` can be `auto` by default, and disable it when output is not a tty.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ bazel query //external:all | grep genproto
Loading: 0 packages loaded
Loading: 0 packages loaded
$ bazel query --noshow_progress //external:all | grep genproto
//external:org_golang_google_genproto
```

### What operating system are you running Bazel on?

Ubuntu 16.04.

### What's the output of `bazel info release`?

`release 0.28.1` (also is present in 0.26.1)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://gist.github.com/kormat/4c1ccfa2b3bc6c66a4364c7704537da9 contains everything needed to reproduce this.

###  Have you found anything relevant by searching the web?

I can't find anything online, but maybe i'm just using the wrong keywords? [bazel progress output overwrite]

**Comment by meisterT** [comment]
should be fixed in the current 0.29 RC by @michajlo with https://github.com/bazelbuild/bazel/commit/ac5a971097a05e72a4c011cde6fbb3f347067b1e#diff-3a83e4f30ace13af1057a82b4821db2e
