### ISSUE TITLE
Starlark-based repository rules no longer warn about mismatched workspace names

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#9174]
### Description of the problem / feature request:

When the repository rule `name` of an external repository didn't match the `workspace`-specified name in that external repository, the native repository rules used to issue a warning about this mismatch (e.g. #4495).  This warning could, in theory, help encourage consistent naming of external repositories between projects.  During the switch to Starlark-based repository rules, however, it was lost and http_archive (as an example) unconditionally overwrites the upstream WORKSPACE file.

### Feature requests: what underlying problem are you trying to solve with this feature?

Being alerted to potential external repository name mismatches and inconsistencies.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Depend on an external repository and specify a different name for that repository than it has given itself in its WORKSPACE file, e.g.

```
  http_archive(
    name = "io_bazel_rules_proto",
    sha256 = "602e7161d9195e50246177e7c55b2f39950a9cf7366f74ed5f22fd45750cd208",
    strip_prefix = "rules_proto-97d8af4dc474595af3900dd85cb3a29ad28cc313",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
    ],
)
```

and witness that there is no warning about the inconsistency.

### What operating system are you running Bazel on?

Debian rodete-based distro

### What's the output of `bazel info release`?
$ bazel info release
release 0.28.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:shahms/kythe.git
93907347ed62e72ce6e3d656901b0382d6ec9324
93907347ed62e72ce6e3d656901b0382d6ec9324

###  Have you found anything relevant by searching the web?

No, other than some old bugs about the warning showing up on the proto repositories.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
