### ISSUE TITLE
Windows: glob(["**"]) in external root is non-recursive

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#9176]
### Description of the problem

`glob(["**"])` inside a `new_local_repository()` does not search subdirectories on Windows, it only reports files in the root directory. The external repository seems to be created with all root files copied in, including the `BUILD.bazel` file, and all subdirectories linked using junctions (`dir | select FullName,LinkType,Target` in Powershell tells me it's a junction).

I would expect `glob([**])` to search subdirectories on both Windows and Linux.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
mkdir -p my-external/subdir/inner
touch my-external/root.txt
touch my-external/subdir/outer.txt
touch my-external/subdir/inner/inner.txt
echo 'new_local_repository(name = "myext", path = "my-external", build_file = "BUILD.myext")' > WORKSPACE
echo 'filegroup(name = "all_files", srcs = glob(["**"]))
filegroup(name = "subdir_files", srcs = glob(["subdir/**"]))' > BUILD.myext
```

It fails in the root on Windows:
```
$ bazel query 'deps(@myext//:all_files)'
@myext//:all_files
@myext//:root.txt
@myext//:WORKSPACE
@myext//:BUILD.bazel
```
It works as expected in the root on Linux:
```
$ bazel query 'deps(@myext//:all_files)'
@myext//:all_files
@myext//:subdir/outer.txt
@myext//:subdir/inner/inner.txt
@myext//:root.txt
@myext//:WORKSPACE
@myext//:BUILD.bazel
```
The subdirectory works on both Windows and Linux:
```
$ bazel query 'deps(@myext//:subdir_files)'
@myext//:subdir_files
@myext//:subdir/outer.txt
@myext//:subdir/inner/inner.txt
```

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.28.1

###  Have you found anything relevant by searching the web?

Search GitHub for `glob+windows`, nothing relevant found.

**Comment by laszlocsomor** [comment]
This is glob() bug with junctions on Windows, not an external repository bug.

Here's a simpler repro in the main workspace:
```
C:\>md foo\gh9176

C:\>cd foo\gh9176

C:\foo\gh9176>type nul > WORKSPACE

C:\foo\gh9176>echo filegroup(name='x',srcs=glob(['foo/**'])) > BUILD

C:\foo\gh9176>echo filegroup(name='y',srcs=glob(['foo2/**'])) >> BUILD

C:\foo\gh9176>md foo\bar

C:\foo\gh9176>md foo2

C:\foo\gh9176>mklink /j foo2\bar2 foo\bar
Junction created for foo2\bar2 <<===>> foo\bar

C:\foo\gh9176>type nul > foo\bar\a.txt

C:\foo\gh9176>type nul > foo\b.txt

C:\foo\gh9176>type nul > foo2\c.txt
```

There's a junction (`foo2\bar2 -> foo\bar`) that the recursive glob fails to follow. The control files (`foo\b.txt` and `foo2\c.txt`) are matched though, indicating the glob() willfully ignored `foo2\bar2`.

```
C:\foo\gh9176>bazel query deps(//:x)
(...)
//:x
//:foo/bar/a.txt
//:foo/b.txt
Loading: 1 packages loaded

C:\foo\gh9176>bazel query deps(//:y)
//:y
//:foo2/c.txt
Loading: 0 packages loaded
```

There's an additional bug: as soon as I add a new file under the `foo2` directory the query starts matching `foo2\bar2` (as a file) but not before.

```
C:\foo\gh9176>bazel query deps(//:y)
//:y
//:foo2/c.txt
Loading: 0 packages loaded

C:\foo\gh9176>bazel shutdown
(...)

C:\foo\gh9176>bazel query deps(//:y)
Starting local Bazel server and connecting to it...
//:y
//:foo2/c.txt
Loading: 1 packages loaded

C:\foo\gh9176>type nul > foo2\d.txt

C:\foo\gh9176>bazel query deps(//:y)
//:y
//:foo2/d.txt
//:foo2/c.txt
//:foo2/bar2
Loading: 1 packages loaded

C:\foo\gh9176>del foo2\d.txt

C:\foo\gh9176>bazel query deps(//:y)
//:y
//:foo2/c.txt
//:foo2/bar2
Loading: 1 packages loaded
```

And if I then clean and restart, `foo2\bar2` is gone again:

```
C:\foo\gh9176>bazel clean --expunge
(...)

C:\foo\gh9176>bazel query deps(//:y)
Starting local Bazel server and connecting to it...
//:y
//:foo2/c.txt
```

**Comment by laszlocsomor** [comment]
Found the culprit: WindowsFileSystem.stat returns a FileStatus whose isSpecialFile calls attribute.isOther():
https://github.com/bazelbuild/bazel/blob/b774f65768eae01b5930dbec770eaca920ee3e82/src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java#L144

The Java 8 documentation about isOther() says: "Tells whether the file is something other than a regular file, directory, or symbolic link.". https://docs.oracle.com/javase/8/docs/api/java/nio/file/attribute/BasicFileAttributes.html#isOther--

Although Bazel treats junctions the same as symlinks, they are technically not the same, and isOther() returns true for junctions.

The bugfix is to return false in isSpecialFile() if isSymbolicLink() returns true.

**Comment by laszlocsomor** [comment]
...And because the FileState reports the junction as a special file, FileSystem.direntFromStat says it's an UNKNOWN dirent: https://github.com/bazelbuild/bazel/blob/b774f65768eae01b5930dbec770eaca920ee3e82/src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java#L588

And the symlink-specific logic in GlobFunction and DirectoryListingStateFunction are skipped.
