### ISSUE TITLE
Limit depset depth

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#9180]
Bazel throws a StackOverflowException upon flattening a a depset of very high depth (~5000 for my default memory settings)

We should institute a fix that Bazel throws a more reasonable exception when flattening a too-deep depset. This should result in only a build failure instead of a server crash.

This github issue, going forward, can serve as record for an FAQ of this particular issue.

**Why doesn't Bazel throw an error on *creation* of a too-deep depset?**

Depsets are one of Bazel's most common in-memory objects, so every byte counts. Storing depth in each depset would have severe memory implications.

**What do I do if I see an error due to a depset which is too deep?**

In almost all cases, this indicates a depset is created in a loop, such as:

```
x = depset([0])
for i in range(1, 10000):
  x = depset([i], transitive = [x])
```

Avoid doing this. Each build target should not contribute to more than one depth worth of depset.
(We plan on adding some best-effort detection logic to buildifier to detect such patterns preemptively)

Another culprit could be that your build graph is indeed very deep, though, it would be surprising if a build graph is indeed deeper than 1000 levels. If this is the case, please let us know, and we can reassess a more general solution to this problem.
For now, in practice, reaching this limit indicates misuse of depsets, as opposed to a too-deep build graph.

**Comment by sergiocampama** [comment]
What would be a better approach should clients find pieces of code like that example snippet?

**Comment by c-parsons** [comment]
Append all elements to a list, and add them as the "direct" elements of a single returned depset.
In the toy example,
```
x = depset([0])
for i in range(1, 10000):
  x = depset([i], transitive = [x])
```
becomes:
```
direct_elements = [0]
for i in range(1, 10000):
  direct_elements.append(i)
x = depset(direct_elements)
```

*size* (number of elements) of a depset is not an issue here, only depth.

**Comment by laurentlb** [comment]
Related documentation: https://docs.bazel.build/versions/0.29.0/skylark/performance.html#reduce-the-number-of-calls-to-depset

Note that Builidifier will also report examples like the first snippet (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#overly-nested-depset), with some limitations (it uses a very simple syntax-based check).

**Comment by jin** [comment]
This has been implemented in https://docs.bazel.build/versions/master/command-line-reference.html#flag--nested_set_depth_limit right? Can this be closed?
