### ISSUE TITLE
`cc_test`s with a large dependency tree eventually exceed the Mac `dyld` load commands size limit

### ISSUE THREAD

**Issue by chronal-xnor** [bazelbuild/bazel#9190]
### Description of the problem / feature request:

Symptom:
`cc_test`s with a large dependency tree eventually exceed the Mac `dyld` load commands size limit:

```
Executing tests from //:repro
-----------------------------------------------------------------------------
dyld: malformed mach-o: load commands size (39784) > 32768
Abort trap: 6
```

I believe the underlying issue is that `cc_test`s force all their `cc_library` dependencies to be build with `-shared` if `dynamic_mode` is `default`. So the list of `.so`s that the dynamic linker must load becomes very long. This is in contrast with `cc_binary` targets which build all their `cc_library` deps as `.a` files that are statically linked into the resulting executable. That seems more like the expected behavior.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

<summary>Patch file below</summary>
<details>
<p>

```
From 32aa8c93db5bf4e29ef3d06b4f6bb41be9351f97 Mon Sep 17 00:00:00 2001
From: Andrew <andrew@xnor.ai>
Date: Fri, 16 Aug 2019 11:15:57 -0700
Subject: [PATCH] Reproduce the issue

---
 BUILD      | 33 +++++++++++++++++++++++++++++++++
 WORKSPACE  |  2 ++
 exec.cc    |  5 +++++
 library.cc |  6 ++++++
 library.h  |  3 +++
 5 files changed, 49 insertions(+)
 create mode 100644 BUILD
 create mode 100644 WORKSPACE
 create mode 100644 exec.cc
 create mode 100644 library.cc
 create mode 100644 library.h

diff --git a/BUILD b/BUILD
new file mode 100644
index 0000000..1bc545c
--- /dev/null
+++ b/BUILD
@@ -0,0 +1,33 @@
+N = 400
+
+[genrule(
+    name = "generate-foo-header-{}".format(i),
+    srcs = ["library.h"],
+    outs = ["library-{}.h".format(i)],
+    cmd = "sed 's/@/{}/' $(location library.h) > $@".format(i),
+) for i in range(N)]
+
+[genrule(
+    name = "generate-foo-lib-{}".format(i),
+    srcs = ["library.cc"],
+    outs = ["library-{}.cc".format(i)],
+    cmd = "sed 's/@/{}/' $(location library.cc) > $@".format(i),
+) for i in range(N)]
+
+[cc_library(
+    name = "long-foo-library-name-{}".format(i),
+    hdrs = ["library-{}.h".format(i)],
+    srcs = ["library-{}.cc".format(i)],
+) for i in range(N)]
+
+cc_test(
+    name = "repro",
+    srcs = ["exec.cc"],
+    deps = [":long-foo-library-name-{}".format(i) for i in range(N)],
+)
+
+cc_binary(
+    name = "no-issue",
+    srcs = ["exec.cc"],
+    deps = [":long-foo-library-name-{}".format(i) for i in range(N)],
+)
diff --git a/WORKSPACE b/WORKSPACE
new file mode 100644
index 0000000..bcb9f84
--- /dev/null
+++ b/WORKSPACE
@@ -0,0 +1,2 @@
+workspace(name = "ai_xnor")
+
diff --git a/exec.cc b/exec.cc
new file mode 100644
index 0000000..dc07513
--- /dev/null
+++ b/exec.cc
@@ -0,0 +1,5 @@
+#include "library-1.h"
+
+int main() {
+  doSomeWork1();
+}
diff --git a/library.cc b/library.cc
new file mode 100644
index 0000000..de408a0
--- /dev/null
+++ b/library.cc
@@ -0,0 +1,6 @@
+#include <cstdio>
+
+int doSomeWork@() {
+  printf("Doing some work;\n");
+  return @;
+}
diff --git a/library.h b/library.h
new file mode 100644
index 0000000..61822b9
--- /dev/null
+++ b/library.h
@@ -0,0 +1,3 @@
+#pragma once
+
+int doSomeWork@();
-- 
2.20.1 (Apple Git-117)
```

</p>
</details>

Save the above patch and apply to an empty git repository: `git apply 0001-Reproduce-the-issue.patch`

Run `bazel run //:repro` to see the issue. `bazel run //:no-issue` for contrast.

### What operating system are you running Bazel on?

Mac OS X 10.14.4

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.28.1
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

StackOverflow question discussing the `dyld` size limit: https://stackoverflow.com/questions/44902695/too-many-commands-dyld-message-malformed-mach-o-load-commands-size

Long discussion on NixOS regarding a similar issue encountered with GHC on Mac and their workaround: https://github.com/NixOS/nixpkgs/issues/22810

Comment from a `.bazelrc` found on the web giving a workaround for the issue: https://gitee.com/mirrors/Envoy/blob/master/.bazelrc#L58

This `dynamic_mode=off` flag appears to do the trick. I'm curious why fully dynamic-linking is the default for `cc_test`s.

### Any other information, logs, or outputs that you want to share?

Reproduction case above is contrived but this issue was encountered in a real Bazel codebase with a relatively large volume of C++ code (and, importantly, many `cc_library` targets).

**Comment by scentini** [comment]
Another way to do this is to add [`linkstatic = 1`](https://docs.bazel.build/versions/0.29.0/be/c-cpp.html#cc_test.linkstatic) to your `cc_test`.
The argument for `cc_test` having dynamic linking as default is that one makes small changes and tests often, and with each change we would have to re-do the final linking step, wasting time in the process.

**Comment by keith** [comment]
It's possible to hit this for iOS builds when you're using `ios_framework` rules as well. This happens specifically in the case where you're avoiding static linking for link times (possibly to speed up the dev cycle) but you have a ton of targets
