### ISSUE TITLE
path resolution as a cache key for repository rules

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#9198]
Currently the cache keys for repository rules can include the literal value of an environment variable. This lets us down for things like PATH, where it's hard to precisely match the change you cared about with the correct cache invalidation. The most common case is c++ compiler autodetection and looking up gcc in PATH.

I just had a neat idea. Suppose we had a function (ideally in pure starlark) which was called like:

gcc_binary = path_lookup("PATH", "gcc")

This function returns the first instance of gcc in directories named in the PATH environment variable, and adds a cache key of:

SEARCH:PATH:gcc /usr/bin/gcc

That gives us precisely the desired behaviour: "rerun this repository rule when searching for gcc in PATH would yield /usr/bin/gcc".

This is tricky to do in pure starlark because of the need to decide whether the cache key has changed - that would be a substantial API change to repository rules. It's not too hard to do if path_lookup is a native function on repository_ctx.

**Comment by aiuto** [comment]
Giving this to external deps on the basis that this is about repository rules. Feel free to debate who owns it and reassign.

**Comment by Wyverald** [comment]
This is an interesting idea. Although I'd like to see more potential use cases to avoid designing a one-off API that only works for `repository_ctx.which`.
