### ISSUE TITLE
Unexpected EOF from Bazel server

### ISSUE THREAD

**Issue by hgaiser** [bazelbuild/bazel#920]
Hey all,

When trying to compile tensorflow 0.7 (with CUDA 7.5 and CUDNN r4) and Bazel 1.5 (Arch AUR version) I get the following error:

`~/tensorflow-0.7.0$ JAVA_HOME=/usr/lib/jvm/java-8-openjdk/ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
.....................
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
INFO: From Compiling tensorflow/core/util/tensor_slice_reader.cc:
In file included from ./tensorflow/core/platform/default/logging.h:23:0,
                 from ./tensorflow/core/platform/logging.h:24,
                 from ./tensorflow/core/lib/core/status.h:24,
                 from ./tensorflow/core/lib/core/errors.h:19,
                 from ./tensorflow/core/framework/tensor_shape.h:24,
                 from ./tensorflow/core/util/tensor_slice_reader.h:26,
                 from tensorflow/core/util/tensor_slice_reader.cc:16:
./tensorflow/core/platform/default/logging.h: In instantiation of 'std::__cxx11::string* tensorflow::internal::Check_LTImpl(const T1&, const T2&, const char*) [with T1 = int; T2 = long unsigned int; std::__cxx11::string = std::__cxx11::basic_string<char>]':
tensorflow/core/util/tensor_slice_reader.cc:136:3:   required from here
./tensorflow/core/platform/default/logging.h:197:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 TF_DEFINE_CHECK_OP_IMPL(Check_LT, < )
                                   ^
./tensorflow/core/platform/macros.h:54:28: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) x
                            ^
./tensorflow/core/platform/default/logging.h:197:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_LT, < )
 ^
INFO: From Compiling tensorflow/core/framework/op_kernel.cc:
tensorflow/core/framework/op_kernel.cc:71:6: warning: 'bool tensorflow::{anonymous}::CheckHostMemoryCompatibility(tensorflow::DeviceType, const tensorflow::OpKernel*)' defined but not used [-Wunused-function]
 bool CheckHostMemoryCompatibility(const DeviceType device_type,
      ^
[803 / 1,257] Compiling tensorflow/core/kernels/split_op.cc
Error: unexpected EOF from Bazel server.`

I also followed the fix from https://github.com/tensorflow/tensorflow/issues/1066 and added the fPIC flag to CROSSTOOL from tensorflow. Any tips on how to debug/fix this?

**Comment by damienmg** [comment]
Can you try adding `--jobs 4` in your option list?

**Comment by hgaiser** [comment]
Ah, the equivalent of `make -j4` ? It did indeed help, it compiled now. Do you think I ran out of memory when running max jobs?

**Comment by damienmg** [comment]
Yes and yes :)

**Comment by hgaiser** [comment]
Thank you for the help!
