### ISSUE TITLE
android: Unable to use AAPT2 when building an AAR

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel#9205]
### Description of the problem / feature request:

When generating an AAR file with `aapt2` enabled, the following crash occurs:
```
Output:
/var/folders/bs/51dlb_nn5k35xq9qfsxv9wc00000gr/T/android_resources_tmp7473448398929879151/manifest-aapt-dummy/AndroidManifest.xml:2: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'main'.

	at com.google.devtools.build.android.AaptCommandBuilder.execute(AaptCommandBuilder.java:318)
	at com.google.devtools.build.android.aapt2.ResourceLinker.linkStatically(ResourceLinker.java:258)
	at com.google.devtools.build.android.ValidateAndLinkResourcesAction.main(ValidateAndLinkResourcesAction.java:195)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$13.call(ResourceProcessorBusyBox.java:138)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:242)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:203)
```

I can safely reproduce when manually running `aapt2`. Replacing `main` in the package with `no.name` work. I think it's looking for a dot in the package name.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build an AAR library with `aapt2` enabled.

### What operating system are you running Bazel on?

macos

### What's the output of `bazel info release`?

`0.29.0rc6`

**Comment by jin** [comment]
aapt2 enforces this. `main` is an invalid package for Android. There needs to be at least one period in the package.

https://stackoverflow.com/questions/55599876/error-attribute-package-in-manifest-tag-is-not-a-valid-android-package-name

**Comment by steeve** [comment]
@jin indeed, but the package being `main` is not my doing. I think it's done by the dummy manifest writer in bazel. hence this issue.

**Comment by jin** [comment]
Odd. Can you make a reproducer project please? I'm not seeing this issue across Bazel's tests and downstream Android projects.

**Comment by steeve** [comment]
Sure thing

**Comment by steeve** [comment]
Ok I think I found the cause, the `android_library` sits in a `java/main` package, and somehow `main` it is propagated

**Comment by steeve** [comment]
Indeed, my bad, it was because the layout was:
```
java/
  main/
      java/
    BUILD.bazel
```

**Comment by jin** [comment]
Yes, the Android rules tries to be helpful and infer the custom package from R. If you want to override this, use `custom_package`.

**Comment by bartek-wesolowski** [comment]
@steeve How did you change the directory layout so that it started working?

**Comment by steeve** [comment]
@bartek-wesolowski i went with a `custom_package` property

**Comment by bartek-wesolowski** [comment]
@steeve Adding `custom_package` doesn't help.
For a simple example check out this repo:
https://github.com/scalio/Android-Bazel-Starter-Kotlin
You can build the app with `bazel build //app/src/main:bazel` and it works, but when you try to just assemble the library module with `bazel build //app/src/main:bazel_kt.aar` you get the following error:
`AndroidManifest.xml:2: error: attribute 'package' in <manifest> tag is not a valid Android package name: 'main'`
Adding a `custom_package` property doesn't help.
The sample uses slightly outdated rules, but updating them to the latest versions doesn't help either.

**Comment by steeve** [comment]
Godspeed, although I'm not worried with @cgruber in the loop, he is handling rules_kotlin like a champ last time I checked.
