### ISSUE TITLE
android: persistent_android_resource_processor doesn't work when building AAR

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel#9207]
### Description of the problem / feature request:

When building an AAR and using `--persistent_android_resource_processor`, the worker fails with the following:
```
Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at /private/var/tmp/_bazel_steeve/309ac22c92b055a3e3f78825fe63406b/bazel-workers/worker-36-AARGenerator.log ---8<---8<---
(empty)
---8<---8<--- End of log ---8<---8<---
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build an AAR with `--persistent_android_resource_processor`

### What operating system are you running Bazel on?

macos

### What's the output of `bazel info release`?

0.29.0rc6

**Comment by steeve** [comment]
I did manage to reproduce when flipping only `--internal_persistent_busybox_tools`

**Comment by jin** [comment]
For a quick workaround, pass `--strategy=AARGenerator=sandboxed` after `--persistent_android_resource_processor`. 

Does the error show up at all if you don't use the persistent workers flag?

**Comment by steeve** [comment]
@jin it doesn't. actually, I only need to use `--internal_persistent_busybox_tools` for it to show up

**Comment by steeve** [comment]
The workaround you suggested is working! Thanks

**Comment by cgruber** [comment]
Still seeing this, just to keep some life to it.

**Comment by nkoroste** [comment]
Still an issue on version 2.2.0

**Comment by nkoroste** [comment]
Still an issue 3.3.1
