### ISSUE TITLE
Document --version

### ISSUE THREAD

**Issue by libsamek** [bazelbuild/bazel#9208]
Since version `0.27.0` there is lightweight version checking `bazel --version`. This should be documented in command line reference (https://docs.bazel.build/versions/master/command-line-reference.html).

**Comment by joybhallaa** [comment]
Can I work on this issue?

**Comment by Qinusty** [comment]
This appears to exist already. https://docs.bazel.build/versions/master/command-line-reference.html#version

**Comment by sgowroji** [comment]
Since it is already [documented](https://github.com/bazelbuild/bazel/issues/9208#issuecomment-544161870) as mentioned above we are closing this issue. Please feel free to reach us for any further information. Thank you !
