### ISSUE TITLE
Provide the target platform information in Starlark rule implementation

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#9209]
### Description of the problem / feature request:

When implementing a Starlark rule, sometimes we need to know what is the target platform. For example, if the target platform in Linux/macOS, we can generated a shell script as the executable, but if the target platform in Windows, the executable should be a batch script or something else that is natively runnable on Windows (powershell script, .exe file).

### What operating system are you running Bazel on?

Windows, Linux, macOS

### What's the output of `bazel info release`?

0.28.1

###  Have you found anything relevant by searching the web?

The only workaround I found is by checking `ctx.configuration.host_path_separator`, if it is ';', then we're on Windows, otherwise we are on Linux or macOS.

/cc @laurentlb

**Comment by laurentlb** [comment]
cc @gregestren, @katre

**Comment by katre** [comment]
@schmitt We were discussing this a few weeks ago.

**Comment by meteorcloudy** [comment]
In my use cases, only the OS is enough. Is there a better way than the work around I suggested?

**Comment by gregestren** [comment]
You could `select()` on something from, say, https://github.com/bazelbuild/platforms, i.e. have a `my_os` attribute that sets to `windows`, `linux`, etc. appropriately. Then the rule implementation logic can switch on those values to do whatever it needs.

Or build this logic into toolchains and use toolchain resolution?

**Comment by meteorcloudy** [comment]
Thanks! I considered this. The only downside is that you'll have to add the `my_os` attribute to every rule that needs to know the platform info.

**Comment by katre** [comment]
This is now implemented, see https://docs.bazel.build/versions/master/skylark/lib/ctx.html#target_platform_has_constraint (should be released with 2.1.0).

**Comment by meteorcloudy** [comment]
@katre Great news! Is there any example on how to use it?

**Comment by katre** [comment]
See the proposal: https://github.com/bazelbuild/proposals/blob/master/designs/2019-11-11-target-platform-constraints.md#proposal-a-check-method-that-takes-a-constraint-value-label

Short version: you need an implicit dependency on the constraint value you want to check, use that to get the `ConstraintValueInfo` provider, and then call `ctx.target_platform_has_constraint` with that provider.

**Comment by meteorcloudy** [comment]
Nice, thanks!
