### ISSUE TITLE
incompatible_generated_protos_in_virtual_imports: put generated `.proto` files into a virtual proto source root directory

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#9215]
If a `proto_library` rule has both generated and non-generated sources, it would give rise to multiple source roots (one in the source tree and one in the output tree). This is unintuitive and incompatible with the `ProtoInfo` provider that has place for only one (`[ProtoInfo].proto_source_root`).

To resolve this, we create a virtual source root under `bazel-bin/<package>/_virtual_imports/<rule>`. 

No user-visible changes are expected except in cases where Starlark code relied on the exact layout of the source tree.

**Comment by thomasvl** [comment]
Can you maybe give an example of what does/doesn't change because of this so one can better assess the impact on LANG_proto_library rules?

**Comment by lberki** [comment]
Consider the following code say, in `x/BUILD`:

```
genrule(name="gen", srcs=[], outs=["a.proto"])
proto_library(name="p", srcs=["a.proto", "b.proto"])
```

At HEAD, this results in the proto_library having a `proto_source_root` of `x`. However, `a.proto` and `b.proto` are not actually siblings (one is under `x`, the other, under `bazel-bin/x`, thus, logic is required to figure out what command line to pass to `protoc`.

When this flag is flipped, the two `.proto` files are both symlinked into a directory `bazel-bin/x/virtual_imports/p`) and that's what `proto_source_root` will be. Simpler and removes guesswork for LANG_proto_library rules and makes it so that each `proto_library` only has one source root.

**Comment by lberki** [comment]
Sorry, I meant `/_virtual_imports/` (including the leading underscore)

I wanted to provide enough information in providers so that you can construct the command line without assuming things about paths, or, even better, provide a Starlark method to do so, but I couldn't make it in time for Bazel 1.0. So I decided that I'll be satisfied with that being possible without backwards-incompatible changes.

Hard-coding `_virtual_imports` is fine -- that won't change after Bazel 1.0.

In the above case, it depends on whether `foo.proto` is generated or not. If it is not, the proto path of the proto compile action of `:bar` will be `.` and `bazel-bin/x/_virtual_imports/p`. If it is, in addition to that, `bazel-bin/m/n/o/_virtual_imports/foo` will also be there. IOW, each `proto_library` that has `import_prefix`, `strip_import_prefix` or generated sources creates its own `_virtual_imports` directory which contains the `.proto` files in its `srcs`.

These are available as `[ProtoInfo].transitive_proto_path`. What is not available, however, is the information that which file in `[ProtoInfo].transitive_sources` is under which entry in `[ProtoInfo].transitive_proto_path`. In addition to time constraints, it's kinda tricky to come up with a data structure that doesn't require significant changes to `ProtoInfo`, does not cause a significant increase in memory use in large builds with many `proto_library` rules and is also reasonably simple to use. FWIW, Bazel also uses guesswork:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCompileActionBuilder.java#L680

, but don't replicate that logic yet -- once 0.29 is out, I'll hardwire `alwaysAddRepositoryPath` to false and some part of the logic only applies to our Google-internal rule which does *not* use `_virtual_imports`.

**Comment by thomasvl** [comment]
Assuming `b.proto` is the only generated file, the three `proto_library` usages should then all vend in `ProtoInfo.proto_source_root` from the libraries would have `bazel-bin/x/_virtual_imports/p`, `.`, and `.` respectively?  And we can get the relative path for each proto file by trimming off their respective roots (if they aren't `.`)?

**Comment by lberki** [comment]
Yep. For the time being, that's the best option.

**Comment by lberki** [comment]
You mean that the import paths of `@a//x:y.proto` and `@b//x:y.proto` are the same?

Yes indeed, that is the case, but that's no different from Bazel 0.28 or any version before that (or the logic of C++ include scanning): repository roots have always been proto source roots.

**Comment by lberki** [comment]
Fix for the only failing project (`rules_swift`) is https://github.com/bazelbuild/rules_swift/pull/298

**Comment by dslomov** [comment]
What is the ETA for this?

**Comment by lberki** [comment]
Done. I thought I had submitted the fix, but apparently it was just a green *presubmit* run.

**Comment by ignasl** [comment]
It seems like this PR may have broken `rules_scala` in a subtle way. The `proto` files are getting copied to the repository directory structure that is being built.  For example in `rules_scala` test protos are getting copied here `test_expect_failure/proto_source_root/dependency/_virtual_imports/`. See: https://github.com/bazelbuild/rules_scala/issues/843.
