### ISSUE TITLE
Adding wrapper to compiler tool chain for the integration of external tool like coverage tool or static analysis tools.

### ISSUE THREAD

**Issue by rsairam34** [bazelbuild/bazel#9223]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Integration of external testing tools (open source/commercial) involves source code instrumentation. 

Irina Iancu, in one of her presentation, have explained to get coverage data instrumenting source code or instrumenting intermediate code and runtime collection of the coverage data is at most important, similar to that we support a commercial tool which adds as a prefix to the compiler for example:
in makefile 
CC = gcc
for source code instrumentation we use
CC = ctc -i m {other options} gcc

when the code is instrumented with ctc options we have a .sym file generated and when at the time of test on instrumented binary .dat file is generated which is then converted to readable html reports.

The other way to get coverage data to this is creating a wrapper around compiler where we would create an executable with the name of the compiler in which we provide the prefix options and call the renamed original compiler, in Linux I was able to generate the coverage reports by creating wrapper around compiler after the Bazel configuration for the project, but by this method the issue is we can't run any other project with the same compiler to which coverage data is not required but coverage is generated as it is enabled at compiler level.

To make sure of the selected project instrumentation I am requesting for the rules or a way where one can use to add a compiler prefix to the build file.

### Feature requests: what underlying problem are you trying to solve with this feature?

selective instrumentation of source code with external tools.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

It's a feature request if this feature already exists please point me towards.

### What operating system are you running Bazel on?

ubuntu 16.04 and windows 10

### What's the output of `bazel info release`?

release 0.28.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

i have tried to find info on the web but I couldn't find related information on how to add prefix all i could find was to add copts or host_cpots which i believe is not the correct options to provide.

### Any other information, logs, or outputs that you want to share?

please let me know you you need any more information on the same I would be happy to help.

**Comment by scentini** [comment]
cc/ @hlopko

**Comment by ybagarka1** [comment]
I am also looking for this feature. Any update on this ?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
