### ISSUE TITLE
CC wrappers should gracefully handle response files

### ISSUE THREAD

**Issue by cstrahan** [bazelbuild/bazel#9224]
### Description of the problem / feature request:

The CC wrappers ([osx_cc_wrapper.sh.tpl](https://github.com/bazelbuild/bazel/blob/d96e1cdbe71d117f76e55c668bb4a0f976bf0bc0/tools/cpp/osx_cc_wrapper.sh.tpl), [linux_cc_wrapper.sh.tpl](https://github.com/bazelbuild/bazel/blob/d96e1cdbe71d117f76e55c668bb4a0f976bf0bc0/tools/cpp/linux_cc_wrapper.sh.tpl)) should gracefully handle [response files](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html#Overall-Options) (see `@file`).

> `@file`
>
>Read command-line options from file. The options read are inserted in place of the original `@file` option. If file does not exist, or cannot be read, then the option will be treated literally, and not removed.
>
>Options in file are separated by whitespace. A whitespace character may be included in an option by surrounding the entire option in either single or double quotes. Any character (including a backslash) may be included by prefixing the character to be included with a backslash. The file may itself contain additional `@file` options; any such options will be processed recursively.

Otherwise, we run into issues as seen here: https://github.com/bazelbuild/intellij/issues/1104

To recap, the intellij plugin needs to pass all of the command line flags for a project to `cc` for some sort of introspection; in order to do so, they currently have to read through any `@file`s to inline the respective flags into the argv used when invoking the CC wrapper. This will fail, though, because the length of argv will be _massive_ and cause the `execve` to fail. So two things:

1. The code in the intellij plugin takes on incidental complexity, and
2. This will fail with even a fairly high `ulimit -s` -- though, of course, users shouldn't have to muck with their stack size limits for something like this to work anyway.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/bazelbuild/intellij/issues/1104.

### What operating system are you running Bazel on?

Linux (Ubuntu 19.04)

### What's the output of `bazel info release`?

release 0.28.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

From working within the Envoy source tree:

```
git@github.com:envoyproxy/envoy.git
9421bddb21f7626d0f3a9b8f25a5bd0245ff8b79
9421bddb21f7626d0f3a9b8f25a5bd0245ff8b79
```

**Comment by scentini** [comment]
cc/ @hlopko

**Comment by jin** [comment]
This is making CLion (a popular C++ IDE) unusable for the Envoy project. Please see the linked issue to IntelliJ for more context.

**Comment by cstrahan** [comment]
May I kindly request that the priority for this ticket be increased? Could someone from the development team propose a plan for resolving this, so others may also attempt to resolve this in the meantime?

Currently, this breaks the IntelliJ plugin for any sufficiently large code base, and the IntelliJ plugin is, to my knowledge, the only means of having a decent development environment for Bazel projects _without_ having to futz with `compile_commands.json`.

Note that this problem is more general than just supporting an IDE -- I'm sure this limitation will also cause problems down the road for other use cases, where response files are specifically used to avoid a massive `argv`.

**Comment by jin** [comment]
There are other areas in the Bazel codebase that uses parameter files, e.g. for Java compilation actions: https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/java/JavaCompileActionBuilder.java;l=311;drc=2d67cc0c08e7e41826efb0113342fada0ff4c8bf

The high level work that needs to be done here is to hook up the rule(s) that uses the wrapper scripts for compilation to also understand param files like the Java example above, which looks like most, if not all of the native cc rules. The other part is to configure the IntelliJ plugin to not flatten the args file as discussed in https://github.com/bazelbuild/intellij/issues/1104#issuecomment-523627174

I'm not sure if there's anyone available on the team to work on this at the moment. cc @lberki

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
