### ISSUE TITLE
Touching BUILD and WORKSPACE slows down the build

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#923]
https://groups.google.com/forum/#!topic/bazel-discuss/0NFvo8O9vOQ

While we're transitioning to Bazel, we're automatically generating our BUILD and WORKSPACE files from other sources.

I'm a bit surprised to see that the Bazel build gets a lot slower when we regenerate/touch the BUILD/WORKSPACE files, even when the files themselves are unchanged.

In this example: https://github.com/dfabulich/touch-build a clean build takes 11s, and rebuilding takes 0.2s, but if I touch BUILD it takes 1.5s, and if I touch WORKSPACE it takes 3.3s.

```
$ bazel clean
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
$ bazel build //:x
INFO: Found 1 target...
Target //:x up-to-date:
  bazel-bin/libx.jar
INFO: Elapsed time: 11.058s, Critical Path: 7.72s
$ bazel build //:x
INFO: Found 1 target...
Target //:x up-to-date:
  bazel-bin/libx.jar
INFO: Elapsed time: 0.167s, Critical Path: 0.00s
$ bazel build //:x
INFO: Found 1 target...
Target //:x up-to-date:
  bazel-bin/libx.jar
INFO: Elapsed time: 0.153s, Critical Path: 0.00s
$ touch BUILD
$ bazel build //:x
INFO: Found 1 target...
Target //:x up-to-date:
  bazel-bin/libx.jar
INFO: Elapsed time: 1.546s, Critical Path: 0.19s
$ touch BUILD
$ bazel build //:x
INFO: Found 1 target...
Target //:x up-to-date:
  bazel-bin/libx.jar
INFO: Elapsed time: 1.562s, Critical Path: 0.19s
$ touch WORKSPACE
$ bazel build //:x
INFO: Found 1 target...
Target //:x up-to-date:
  bazel-bin/libx.jar
INFO: Elapsed time: 3.281s, Critical Path: 1.75s
$ touch WORKSPACE
$ bazel build //:x
INFO: Found 1 target...
Target //:x up-to-date:
  bazel-bin/libx.jar
INFO: Elapsed time: 3.296s, Critical Path: 0.23s
```

**Comment by damienmg** [comment]
FTR, result of profiling the example:
```

=== PHASE SUMMARY INFORMATION ===

Total launch phase time         9.00 ms    0.17%
Total init phase time           69.2 ms    1.34%
Total loading phase time         920 ms   17.87%
Total analysis phase time        124 ms    2.40%
Total preparation phase time    3.53 ms    0.07%
Total execution phase time      4.021 s   78.08%
Total finish phase time         3.30 ms    0.06%
Total run time                  5.150 s  100.00%

=== INIT PHASE INFORMATION ===

Total init phase time                    69.2 ms

Total time (across all threads) spent on:
              Type    Total    Count     Average

=== LOADING PHASE INFORMATION ===

Total loading phase time                  920 ms

Total time (across all threads) spent on:
              Type    Total    Count     Average
    CREATE_PACKAGE    0.12%        3     1.07 ms
          VFS_OPEN    0.00%        1     0.06 ms
          VFS_READ    0.01%        1     0.33 ms
     SKYFRAME_EVAL   33.95%        2      450 ms
       SKYFUNCTION   33.64%       11     81.1 ms
     SKYLARK_LEXER    0.00%        1     0.06 ms
    SKYLARK_PARSER    0.00%        1     0.09 ms
   SKYLARK_USER_FN   30.65%        1      813 ms
SKYLARK_BUILTIN_FN    0.88%    10005     0.00 ms

=== ANALYSIS PHASE INFORMATION ===

Total analysis phase time                 124 ms

Total time (across all threads) spent on:
              Type    Total    Count     Average
     SKYFRAME_EVAL   44.18%        1     97.1 ms
       SKYFUNCTION   43.63%        3     32.0 ms

=== EXECUTION PHASE INFORMATION ===

Total preparation time                   3.53 ms
Total execution phase time               4.021 s
Total time finalizing build              3.30 ms

Action dependency map creation           0.00 ms
Actual execution time                    4.021 s

Total time (across all threads) spent on:
              Type    Total    Count     Average
            ACTION    0.00%        1     0.54 ms
      ACTION_CHECK    1.59%        4     45.3 ms
    ACTION_EXECUTE    0.14%        1     16.5 ms
   ACTION_COMPLETE    0.00%        1     0.16 ms
              INFO    0.00%        1     0.00 ms
          VFS_STAT    1.62%    10015     0.02 ms
           VFS_MD5   28.23%    10006     0.32 ms
        VFS_DELETE    0.00%        2     0.20 ms
          VFS_OPEN    0.00%        3     0.15 ms
         VFS_WRITE    0.00%        3     0.11 ms
              WAIT    0.00%        3     0.01 ms
     SKYFRAME_EVAL   33.87%        1     3.868 s
       SKYFUNCTION   33.19%    20015     0.19 ms

Critical path (3.552 s):
    Id        Time Percentage   Description
 30071     55.8 ms    1.57%   Building libx.jar (10000 source files)
 30070     3.496 s   98.43%   Executing genrule // generated
```

**Comment by damienmg** [comment]
Another note: `-s` shows that the action is not reexecuted (and that would be 15 seconds instead of 4)

**Comment by damienmg** [comment]
@haxorz @laurentlb Skylark seems slow, Skyframe eval too... Is there a way to know which skyfunction got called?

**Comment by damienmg** [comment]
Per @lberki advice used `--noexperimental_check_output_files` and the md5 average time was reduced by a factor of 10. So 2 insight:
  - Skylark evaluation is way to slow for such a simple function
  - Skyframe creates 10000 skyfunctions which are probably the corresponding FileValue
  - We are MD5 those file that haven't changed... Why?

**Comment by ulfjack** [comment]
We only avoid md5-ing if the mtime hasn't change. touch or regenerate
changes the mtime (most likely), so we need to re-md5. However, it should
be either change-pruned or we shouldn't see invalidation in the first
place. It's probably something stupid.


I have a branch that adds Skyframe debugging output:
https://github.com/ulfjack/bazel/tree/ulfjack-debug-skyframe

Haven't updated it in a while, but it should still be good. No, it's not
good. Ok, I've pushed a merge with fixes now.

**Comment by damienmg** [comment]
Yes the problem here is that we MD5 the 10000 output files that haven't
changed. --noexperimental_check_output_files stop doing that MD5

**Comment by laurentlb** [comment]
Hi,

In current implementation, operator += is copying the list, so your loop has a O(n^2) complexity... This is going to change soon. Sorry about that (it's in the top of the TODO list for Skylark).

Workarounds:
 * either use .append() or .extend
 * or use a list comprehension: ["File"+str(i)+".java" for i in range(count)]

**Comment by damienmg** [comment]
With the .append() and --noexperimental_check_output_files we are down to
1s which seems correct for a simple invalidation.

**Comment by bsilver8192** [comment]
Also, #835 makes doing the MD5 on all the files way slower on machines with SSDs and multiple CPUs.

**Comment by philwo** [comment]
@dfabulich Do you think there's anything left to do on this bug? Or can I close it?

**Comment by dfabulich** [comment]
This bug still repros, just as I reported it, in bazel 0.4.2.

Is bazel calculating O(N) md5s during rebuilds? I would expect Bazel to just MD5 the touched `BUILD` or `WORKSPACE` file, observe that it's unchanged, and then use the pre-calculated md5s. 

In February, Damien wrote that 1s "seems correct for a simple invalidation" but I don't see why that would be correct, and I especially don't see why touching `WORKSPACE` causes anything other than the `WORKSPACE` itself to be invalidated.

Also, is `+=` on lists still O(n^2)? In bazel 0.4.2 I see no noticeable performance difference switching between them in bazel 0.4.2.

**Comment by philwo** [comment]
@laurentlb @damienmg Any suggestion to whom I could assign this to?

**Comment by damienmg** [comment]
I might take a stab at reproducing it to figure out what wrong when I am done with Skylark repository invalidation issues.

**Comment by laurentlb** [comment]
For `+=`, assign to Vlad.

For md5 checks, assign to the core team

**Comment by dfabulich** [comment]
To be clear, I don't repro a `+=` bug. Maybe that was a real bug back when I filed the issue in February, but today I see no difference between `+=` and `.append()` in this test.

**Comment by damienmg** [comment]
@vladmos: as per Laurent guideline, assigning to you to look into += performance.

MD5 checks, adding @haxorz and @janakdr

**Comment by vladmos** [comment]
The behaviour of `+=` hasn't been changed yet (it's a complex task, simply changing semantics from "copy" to "extend" breaks a lot of existing code which we need to clean up first or to ensure the maintainers will do it). We are going to do it anyway, if it's a bottleneck you can rewrite the rules to that they use `.append()` or `.extend()` instead.

I've just filed a separate ticket for this issue (#2350) and, as it's not the case here, I'm unassigning myself from this one.

**Comment by damienmg** [comment]
@vladmos: but @dfabulich said that he has same perf with += and append...

**Comment by vladmos** [comment]
@damienmg I took it as a proof that the poor performance of `+=` is not the bottleneck here. Maybe I misunderstood, I'll try to examine the performance of `.append` to make sure it's O(1).

However according to the code the `append` method falls back to ArrayList.add which is amortised O(1), I wouldn't expect it to be the reason of the builds being slow.

**Comment by damienmg** [comment]
Well there was a 450ms in skyframe eval which seems a lot so it has to come from somewhere in Skylark

**Comment by janakdr** [comment]
The problem here is that we don't md5 files during loading/analysis in bazel, we rely on the combination of size+mtime+inode to determine if a file has changed. We also don't have change pruning for packages. Thus, when you touch a BUILD file or WORKSPACE file, we determine that it has changed, and so we re-evaluate the relevant package, and then that cascades. We need mtime as part of that tuple in order to detect an in-place modification that doesn't change the size.

We could implement change pruning for packages, but that's a much bigger project. We could md5 certain files, like BUILD files, but this situation seems relatively rare, no?

**Comment by dfabulich** [comment]
The use case for us is that we're generating our BUILD and WORKSPACE files based on our legacy build system. A null build for us includes a null run of the generator.

We've worked around this issue by recording our own MD5s of the BUILD and WORKSPACE files, and backdating the mtime if the generator doesn't change anything.

**Comment by janakdr** [comment]
Sorry, I'd forgotten that part of your original post. That's certainly a fair use case, but hopefully a temporary state of affairs? I'm going to give this to @damienmg to decide on prioritization. If he would like to devote some resources to package serialization and equality comparison, I wouldn't say no :)

**Comment by dfabulich** [comment]
Fully transitioning a build system takes a while! We've been working on it for a year now.

**Comment by user28657** [comment]
I'm in a similar situation - generated BUILD files as part of a build system migration with null builds often bottlenecked by hashing files to see if they hit the action cache. Change pruning for packages would fix this, but fast digest support (i.e. using xattr) would also help. Is this planned to be open sourced?

**Comment by lberki** [comment]
Not that I know of. The internal implementation essentially consists of a little `FileSystem` implementation that overrides `#getMD5Digest()` (the easy part) and custom FUSE file systems the export this attribute (the hard part). The former isn't very useful without the latter, and we don't have any plans of open sourcing those.

**Comment by meisterT** [comment]
(Side note: with `--experimental_multi_threaded_digest` being turned on by default, the hashing should be less often a bottleneck.)

cc @alandonovan for the idea of using a normalized AST representation as optimization.

**Comment by alandonovan** [comment]
Simply textually discarding comments is not behavior-preserving: comments change the line numbers of subsequent statements, and line numbers appear in error messages, query output, and elsewhere in the user interface. You would need some kind of equivalence relation over syntax trees, but that gets messy.

The "normalized AST representation" that we should be using is the byte-code compiled form of the Starlark file. Unlike a source file, a byte code file is very easy and fast to parse, and inherently discards most irrelevant information. If a source change doesn't affect the compiled code (e.g. most comments, using different literal notations for the same value, etc.) then skyframe will prune the effects of the change at compilation.

I am working towards this.

**Comment by brandjon** [comment]
Seems to me this issue is entirely dependent on us switching to a bytecode representation. At the moment it's unclear whether we will end up switching to such a representation, and at any rate it's low priority for us right now.

**Comment by brandjon** [comment]
Reviewing this thread again now, I see there's actually two issues that were discussed.

1. That a null run that touches a BUILD file without modifying its content is not pruned (Janak's comment [above](https://github.com/bazelbuild/bazel/issues/923#issuecomment-271471124)).

2. That a whitespace or comment change that does not affect line numbers is not pruned. This is described in [this source comment](https://github.com/bazelbuild/bazel/blob/a8d0d5061fe5c2b783532e472fc4741683aa97e8/src/main/java/com/google/devtools/build/lib/skyframe/BzlCompileValue.java#L37-L47) and requires bytecode compilation.

So I'll consider (2) a dup of #10727, and send this thread over to Core team to triage (1).
