### ISSUE TITLE
Feature request: add `nolinkopts` for cc_{binary,test}

### ISSUE THREAD

**Issue by lizan** [bazelbuild/bazel#9238]
### Description of the problem / feature request:

Specifically, I want to remove `-lstdc++`/`-lc++` from generated toolchain for specific target to link libstdc++ statically while keep other cc targets linked dynamically, there's no `-static-libc++` but `-static-libstdc++`. Passing both `-lc++` and `-l:libc++.a` results a dynamic link.

**Comment by scentini** [comment]
There's no plan to add `nolinkopts` to Bazel, in fact, the next release will not have `nocopts` as well: https://github.com/bazelbuild/bazel/issues/8706.

Bazel has a `BAZEL_LINKOPTS` variable, which defaults to `-lstdc++:-lm`, and which you can change to remove `-lstdc++`. Then, you'll need to add `-lstdc++` to `linkopts` of the targets where you want `libstdc++` linked dynamically, and `-l:libc++.a` for the other ones.
