### ISSUE TITLE
Python stub can import modules from inside the application due to sys.path[0]

### ISSUE THREAD

**Issue by alex-xnor** [bazelbuild/bazel#9239]
### Description of the problem / feature request:

The Python stub template that Bazel uses begins by importing a number of modules from the standard library. However, as it is a Python script like any other, Python will put the directory containing it at the start of `sys.path`. So, if there are any Python files in the same directory that happen to be named the same as a standard library module, the stub will import that file rather than the version from the standard library.

There is a mitigating factor that can hide this problem in some cases: Python will follow symlinks before determining what directory to add to the path, and the directory structure that Bazel creates locally, makes the stub within the runfiles tree be a symlink to the directory containing the runfiles directory, where source files do not live. So when running the result of a build locally, this problem does not occur.

However, it starts to become a problem in two cases:

1. When using remote execution (we are using Google Cloud Remote Build Execution, but I suspect this is not specific to RBE), the stub within the runfiles is not a symlink. So running a test with remote execution can trigger this problem.

2. If you are trying to copy a build result elsewhere (e.g. to another computer), you will usually follow the symlinks when copying, so the copied result has no symlinks since they were all dereferenced during the copying process. So then running the executable in the copied directory causes the issue.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Extract the attached workspace: [repro.zip](https://github.com/bazelbuild/bazel/files/3536735/repro.zip)

1. Observe that running the test locally succeeds:

    ```
    $ bazel test ...:all
    INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
    INFO: Found 1 target and 1 test target...
    Target //myproject:io up-to-date (nothing to build)
    Target //myproject:io_test up-to-date:
      bazel-bin/myproject/io_test
    INFO: Elapsed time: 0.375s, Critical Path: 0.27s
    INFO: 2 processes: 2 linux-sandbox.
    INFO: Build completed successfully, 2 total actions
    //myproject:io_test                                                      PASSED in 0.1s

    Executed 1 out of 1 test: 1 test passes.
    INFO: Build completed successfully, 2 total actions
    ```

2. Observe that running the test using RBE fails:

    ```
    $ bazel test --config=remote --remote_instance_name=<snip> --test_output=streamed ...:all
    INFO: Invocation ID: 46074e60-73d9-4146-981f-9c455a93ae89
    WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
    INFO: Build option --test_sharding_strategy has changed, discarding analysis cache.
    DEBUG: <snip>/external/bazel_toolchains/rules/rbe_repo.bzl:421:5: Bazel 0.28.1 is used in rbe_default.
    WARNING: <snip>/external/remote_java_tools_linux/BUILD:536:12: in hdrs attribute of cc_library rule @remote_java_tools_linux//:combiners: Artifact 'external/remote_java_tools_linux/java_tools/src/tools/singlejar/zip_headers.h' is duplicated (through '@remote_java_tools_linux//:transient_bytes' and '@remote_java_tools_linux//:zip_headers')
    INFO: Analyzed 2 targets (0 packages loaded, 319 targets configured).
    INFO: Found 1 target and 1 test target...
    Traceback (most recent call last):
      File "/b/f/w/bazel-out/k8-fastbuild/bin/myproject/io_test.runfiles/__main__/myproject/io_test", line 11, in <module>
        import zipfile
      File "/usr/lib/python2.7/zipfile.py", line 501, in <module>
        class ZipExtFile(io.BufferedIOBase):
    AttributeError: 'module' object has no attribute 'BufferedIOBase'
    FAIL: //myproject:io_test (see <snip>/execroot/__main__/bazel-out/k8-fastbuild/testlogs/myproject/io_test/test.log)
    Target //myproject:io up-to-date (nothing to build)
    Target //myproject:io_test up-to-date:
      bazel-bin/myproject/io_test
    INFO: Elapsed time: 38.273s, Critical Path: 37.74s
    INFO: 2 processes: 1 remote cache hit, 1 remote.
    INFO: Build completed, 1 test FAILED, 2 total actions
    //myproject:io_test                                                      FAILED in 37.4s
      <snip>/execroot/__main__/bazel-out/k8-fastbuild/testlogs/myproject/io_test/test.log

    INFO: Build completed, 1 test FAILED, 2 total actions
    ```

3. Observe that copying the runfiles and resolving the symlinks yields the same kind of failure:

    ```
    $ cp -rL bazel-bin/myproject /tmp/myproject-bin
    $ /tmp/myproject-bin/io_test.runfiles/__main__/myproject/io_test 
    Traceback (most recent call last):
      File "/tmp/myproject-bin/io_test.runfiles/__main__/myproject/io_test", line 11, in <module>
        import zipfile
      File "/usr/lib/python2.7/zipfile.py", line 501, in <module>
        class ZipExtFile(io.BufferedIOBase):
    AttributeError: 'module' object has no attribute 'BufferedIOBase'
    ```

    (If you run `/tmp/myproject-bin/io_test` (without digging into the runfiles), it succeeds, but that's not what `external/bazel_tools/tools/test/test-setup.sh` does.)

### What operating system are you running Bazel on?

Ubuntu 16.04.6 LTS locally; default `rbe_ubuntu16_04` remotely

### What's the output of `bazel info release`?

release 0.28.1

###  Have you found anything relevant by searching the web?

There are a few other issues related to issues with Python's insertion of `sys.path[0]`, namely #7091 and some of its referenced issues, but those mostly concern issues once the desired script has been started. In contrast, here the issues are in the stub generated by Bazel itself; it never even gets to the user's main script.

**Comment by alex-xnor** [comment]
I have a very small patch that fixes this (just does `import sys` and `del sys.path[0]` in the stub after the `__future__` import but before everything else), but I am trying to see if I can add some tests before submitting it.

**Comment by brandjon** [comment]
Thanks for describing this interesting failure mode and for the patch!
