### ISSUE TITLE
OutputRoot is incorrectly documented

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#9241]
### Description of the problem / feature request:

The output directory structure is documented here: https://docs.bazel.build/versions/master/output_directories.html

It says
> The outputRoot directory is ~/.cache/bazel. (Unless $TEST_TMPDIR is set, as in a test of bazel itself, in which case this directory is used instead.)

This is incorrect on macOS and likely doesn't even make sense on windows since / isn't the directory separator.

The macOS value is defined here.
https://github.com/bazelbuild/bazel/blob/12c7942f45185e15ac26c383644b5d63a3c25269/src/main/cpp/blaze_util_darwin.cc#L98-L100

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel info output_base` and observe it isn't a subdirectory of what is documented.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.28.1

**Comment by kylecordes** [comment]
This might be off-doc on Windows also - it appears to use $HOME rather than $HOME/.cache/bazel.

**Comment by mleonhard** [comment]
On MacOS 10.15.2, Bazel is using `/private/var/tmp/_bazel_$USER/`

**Comment by jin** [comment]
This appears to be documented correctly now:

https://docs.bazel.build/versions/master/output_directories.html#current-layout

```
The outputRoot directory defaults to ~/.cache/bazel on Linux, /private/var/tmp on macOS, and on Windows it defaults to %HOME% if set, else %USERPROFILE% if set, else the result of calling SHGetKnownFolderPath() with the FOLDERID_Profile flag set. If the environment variable $TEST_TMPDIR is set, as in a test of bazel itself, then that value overrides the default.
```
