### ISSUE TITLE
BUILD event protocol documentation has bad links

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#9242]
https://docs.bazel.build/versions/master/build-event-protocol.html has text that looks like
`[Build Event Protocol]` in paragraphs and a bunch of lines at the bottom that look like
```
[Build Event Protocol]: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto
```

Given a different markdown flavor this would end up generating links, but whatever tooling that is used to generate the site doesn't support this.

**Comment by buchgr** [comment]
@jin has fixed this in the meantime :-). thanks for the fix and for reporting!
