### ISSUE TITLE
BuildEventArtifacts aren't uploaded to remote cache unless it is a grpc cache 

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#9243]
### Description of the problem / feature request:

I would expect that when setting `--experimental_build_event_upload_strategy=remote` that my logs would get uploaded to the remote cache. This isn't the case if the cache is an http cache as the code to initialize the non local uploader is never run.

https://github.com/bazelbuild/bazel/blob/4ba404f7ed0473df3f0effa016c107ef677464f6/src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java#L265

I have a hacky change that shows this is mostly possible to support:
https://github.com/endobson/bazel/commit/a920d77740cc28475c160255327ec237c2cef741

This is related to
https://github.com/bazelbuild/bazel/issues/3689, which means that local reading of the files isn't even an option given concurrent bazel runs.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
bazel build --build_event_text_file=build.txt --experimental_build_event_upload_strategy=remote --remote_cache=$CACHE //:target
```

When looking at build.txt I would expect to see the build event artifacts in a cache URI that is not local to my machine. I end up seeing local files.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.28.1

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
