### ISSUE TITLE
rules_foreign_cc broken in downstream

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#9258]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1167#891aff35-2acc-491f-8102-7c62e3635276

**Comment by trybka** [comment]
Unfortunately it still doesn't have the libtool invocation in that log. :(

**Comment by irengrig** [comment]
rules_foreign_cc are now built in Bazel@HEAD+Downstream successfully.
