### ISSUE TITLE
Documentation for @platforms

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#9260]
Since https://github.com/bazelbuild/bazel/commit/324dc44e6bafb487331724ae83d67bc18ed8a8aa, a repository `@platforms` is declared by default. However, I don't see it in the documentation (https://docs.bazel.build/search.html?q="%40platforms").

cc @hlopko

**Comment by gregestren** [comment]
Yes. This is currently documented at https://docs.bazel.build/versions/master/platforms-intro.html#common-platform-properties.
