### ISSUE TITLE
compile.sh java problem

### ISSUE THREAD

**Issue by steige2** [bazelbuild/bazel#9261]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Attempting to bootstrap bazel-0.25-1, I:
unzip bazel-0.25.1-dist.zip
(lots of output, finishes without error)
./compile.sh
(lots of output, many actions complete then:)
...
Exception in thread "main" java.lang.AssertionError: 
Could not find java.lang.Object on bootclasspath; something has gone terribly wrong.
Please file a bug: https://github.com/bazelbuild/bazel/issues
        at DumpPlatformClassPath.writeEntries(DumpPlatformClassPath.java:136)
        at DumpPlatformClassPath.writeClassPathJars(DumpPlatformClassPath.java:174)
        at DumpPlatformClassPath.dumpJDK9AndNewerBootClassPath(DumpPlatformClassPath.java:97)
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:67)

### Feature requests: what underlying problem are you trying to solve with this feature?

Not a feature

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See above

### What operating system are you running Bazel on?

Linux r08g05 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

### What's the output of `bazel info release`?

$ bazel info release
-bash: bazel: command not found
(as expected, not there yet)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
fatal: Not a git repository (or any parent up to mount point /home/xxxxx)
(several copies of this)

###  Have you found anything relevant by searching the web?

Afraid not, I'm following the instructions and filing a bug report. Nothing I found was useful
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

You've got what I know
>
> If the files are large, upload as attachment or provide link.

**Comment by philwo** [comment]
@steige2 Do I understand correctly that you're using CentOS 7? Which Java version do you have installed and enabled (output of `javac -version` and the value of `$JAVA_HOME` would be helpful)?

I can try to reproduce your issue then.

**Comment by steige2** [comment]
$ javac -version
javac 1.8.0
$ echo $JAVA_HOME

(That is echo $JAVA_HOME returns nothing)

Nothing left but madness
When theres nothing left to lose

Scott Teige PhD
Deep Learning
Indiana University Research Technologies
steige@iu.edu
Office: +1 812 856 7331

**Comment by steige2** [comment]
$ javac -version
javac 1.8.0
$ echo $JAVA_HOME

(That is echo $JAVA_HOME returns nothing)

Nothing left but madness
When theres nothing left to lose

Scott Teige PhD
Deep Learning
Indiana University Research Technologies
steige@iu.edu <mailto:steige@iu.edu>
Office: +1 812 856 7331

**Comment by philwo** [comment]
I cannot reproduce this with a fresh CentOS 7.6 VM:

```
yum install -y dpkg-dev ed file gcc gcc-c++ git iproute java-1.8.0-openjdk-devel lcov openssl-perl patch python python-six python36 python36-PyYAML python36-six unzip which zip
mkdir bazel-0.25.1
cd bazel-0.25.1
curl -LO https://github.com/bazelbuild/bazel/releases/download/0.25.1/bazel-0.25.1-dist.zip
unzip bazel-0.25.1-dist.zip
./compile.sh
[...]
Build successful! Binary is here: /home/philwo_google_com/bazel-0.25.1/output/bazel
```

My Java:
```
$ javac -version
javac 1.8.0_222
$ echo $JAVA_HOME
```

What JDK do you have installed? Maybe `java -version` tells us a bit more. 🤔

**Comment by steige2** [comment]
Hello,
I’ve been able to solve the problem by moving to another filesystem for the entire build.
The original problem happened on an NFS file system, I build in tmpfs, it works.
I’m not sure that tis is the origin of the problem or if simply moving to another platform
resolved the issue but I am sure the build has completed.

Thank you for you attention to this matter and
Best Regards,

Scott Teige PhD
Deep Learning
Indiana University Research Technologies
steige@iu.edu
Office: +1 812 856 7331

**Comment by steige2** [comment]
Hello,
I’ve been able to solve the problem by moving to another filesystem for the entire build.
The original problem happened on an NFS file system, I build in tmpfs, it works.
I’m not sure that tis is the origin of the problem or if simply moving to another platform
resolved the issue but I am sure the build has completed.

Thank you for you attention to this matter and
Best Regards,

Scott Teige PhD
Deep Learning
Indiana University Research Technologies
steige@iu.edu <mailto:steige@iu.edu>
Office: +1 812 856 7331
