### ISSUE TITLE
Make --distdir easier to test

### ISSUE THREAD

**Issue by swsnider** [bazelbuild/bazel#9265]
### Description of the problem / feature request:

Please provide a verbose output option that outputs exactly where bazel is sourcing externally-fetched resources from (i.e. repository_ctx.download/respository_ctx.download_and_extract), especially whether `--distdir` had a hit or not.

### Feature requests: what underlying problem are you trying to solve with this feature?

I use `--distdir` in order to avoid talking to the internet during build. However, it's super hard to troubleshoot that this is even working. Even in situations where I literally shut down all network access on the computer I'm testing with, I sometimes get false positives because of caches that seem to not be cleared even by `bazel clean --expunge`.

### What operating system are you running Bazel on?

macOS and Linux

### What's the output of `bazel info release`?

release 0.28.1-homebrew

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A and internal

###  Have you found anything relevant by searching the web?

The code in question (at least for `--distdir` has a whole comment block explaining that not finding files in `--distdir` is actually the common case, so it's utterly and completely silent, which leads me to believe this may not be that hard of a change to implement.

### Any other information, logs, or outputs that you want to share?

This would've cut significant time off of debugging the problem represented in https://github.com/bazelbuild/bazel/issues/9227

**Comment by aehlig** [comment]
> Even in situations where I literally shut down all network access on the computer I'm testing with, I sometimes get false positives because of caches that seem to not be cleared even by `bazel clean --expunge`.

This is expected and not a bug. Note that `bazel` tries to avoid using the network when possible. So when `bazel` needs an external repository,
- it first checks if it has an up-to-date copy according to the [invalidation semantics](https://bazel.build/designs/2016/10/18/repository-invalidation.html); this is specific to the workspace and indeed cleaned with `bazel clean --expunge`.
- If the repository is not up to date, `bazel` fetches it; for files needed that have a known hash sum, `bazel` first checks the [repository cache](https://docs.bazel.build/versions/master/command-line-reference.html#flag--repository_cache) if it has fetched the file earlier. This cache is enabled by default and deliberately shared between all workspaces to avoid fetching a common dependency several times. As that cache is shared it is not affected by `bazel clean --expunge`; however, it can be disabled by specifying `--repository_chache=`, i.e., setting the path to the empty string.
- Only if the file isn't is the repository cache either but has a specified hash sum, bazel tries to find the file in the specified `--distdir` directories. If it is  are found there, it istaken and also added to the repository cache (unless it is disabled).
- Only if the file isn't found there either, bazel uses the network.

**Comment by micahcatlin** [comment]
I'm super interested in this feature request as well.

I'm using bazel in CI and am trying to make the build be resiliant to outages of mirror.bazel.build and github.com/bazelbuild -- so I've created a flow using 'bazel sync --experimental_repository_resolved_file=resolved.bzl', and processing that file to download assets.

Now that I have a suitable --distdir location, I want to verify that bazel is finding 100% of its assets in that directory and not silently using the network.  A verbose output indicating a network use would be very welcome.

Or perhaps even better, a flag like "--airgapped" that would make bazel exit if it ever tries to make an HTTP request.
