### ISSUE TITLE
Set up continuous integration for Windows

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#927]
For the time being, just testing bootstrapping is enough, since we literally haven't ever ran tests.

default plan: a Windows instance on GCE. If that does not work, we'll regroup and reorient.

**Comment by damienmg** [comment]
Reassigning to Lukacs who is actively working on it :)

**Comment by kchodorow** [comment]
Is this done now?

**Comment by damienmg** [comment]
Yes lberki did it :)
