### ISSUE TITLE
Current guidance on repository naming bound to fail in presence of diamond-dependencies

### ISSUE THREAD

**Issue by cstrahan** [bazelbuild/bazel#9275]
### Description of the problem / feature request:

The official Bazel guidance for repository naming causes problems for projects with diamond dependencies. Take for example:

```
  gogo/protobuf proto library
        /          \
       /            \
Third-party     Go library
C++ library         /
       \           /
        \         /
       Go executable

```

The Bazel build system for the third-party C++ library attempts to generate C++ for the [`gogo/protobuf`](https://github.com/gogo/protobuf) proto library (`@com_github_gogo_protobuf`). Then, the [`rules_go`](https://github.com/bazelbuild/rules_go) system checks if `@com_github_gogo_protobuf` is already defined: if it isn't it'll create the repository; if not, it assumes the existing `@com_github_gogo_protobuf` is what the user wants to use and does nothing. But then `@com_github_gogo_protobuf` only contains C++ source, breaking any Go packages using `@com_github_gogo_protobuf`.

This is precisely what is happening here: https://github.com/envoyproxy/envoy/issues/5851

The current state of affairs means projects have to manage forks of projects to sidestep name collisions in these diamond dependency scenarios.

Bazel should either provide some new mechanism to support this scenario, or the usage guidance should be changed to suggest some sort of pattern that doesn't cause this problem to arise (if such a pattern exists / is possible with Bazel as it currently is).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Set up any diamond dependency as described above, and watch the build fail.

### What operating system are you running Bazel on?

Ubuntu 19.04.

### What's the output of `bazel info release`?

release 0.28.1

###  Have you found anything relevant by searching the web?

Aside from my issue (https://github.com/envoyproxy/envoy/issues/5851), no. I know that there are companies/projects in existence that compile C++/Go into the same executable; it's just a matter of time before they both depend on the same proto library.

**Comment by fmeum** [comment]
This is solved by the new external dependency management system (https://bazel.build/external/overview#bzlmod).

**Comment by fmeum** [comment]
Bzlmod is now enabled by default in Bazel 7.
