### ISSUE TITLE
GrpcRemoteCache's requestRead method should sanity check the offset

### ISSUE THREAD

**Issue by mostynb** [bazelbuild/bazel#9276]
### Description of the problem / feature request:

GrpcRemoteCache's requestRead method (used by downloadBlob) doesn't sanity-check responses from the server, and can subsequently send out of range requests to the cache server.

Ideally, bazel should notice if the cache server responds with too much data, print a user-visible warning, ignore the result returned by the cache, and continue.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Implement a grpc cache server with ByteStream API support (eg https://github.com/mostynb/bazel-remote/commit/09f77213958b477428e1a7f38dc4a1169bb0e652 - discovered when implementing https://github.com/buchgr/bazel-remote/issues/64), and make the Read rpc send too much data back to the client (eg by ignoring the read_offset and always assume that it's 0). Then build kubernetes (or something else with large artifacts) using this cache, then bazel clean and rebuild.

Near the end of the rebuild, bazel sends invalid Read requests with read_offset greater than the size of the blob (which is encoded in resource_name).

IMO the ReadResponse onNext method should check that the offset is not larger than digest.getSizeBytes() before continuing. But I'm unsure of what to do when discovering this failed assumption- throwing an exception seems to crash bazel. Ref:
https://github.com/bazelbuild/bazel/blob/12ebb84a7645baffdbaf9f40cbfcec996a540ffe/src/main/java/com/google/devtools/build/lib/remote/GrpcRemoteCache.java#L337

### What operating system are you running Bazel on?

Linux.

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

bazel build //src:bazel

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
50951dd3bf5bae023f21f62e76ed3d7863404263
50951dd3bf5bae023f21f62e76ed3d7863404263

###  Have you found anything relevant by searching the web?

I haven't been able to find any mention of how ByteStream Read clients should abort the request in onNext, when using StreamObserver.

**Comment by buchgr** [comment]
I assume you noticed this behavior when debugging your gRPC implementation in bazel-remote? The remote implementation in Bazel mostly assumes a correctly functioning backend. We haven't really had the time (yet) to test for all kinds of protocol violations. However, I agree that Bazel should handle such cases better.

**Comment by mostynb** [comment]
Yes, I discovered this while working on bazel-remote's gRPC implementation.
