### ISSUE TITLE
Strip version does not works properly even with simple Hello world program on java.

### ISSUE THREAD

**Issue by systemlogic** [bazelbuild/bazel#9278]
### Description of the problem / feature request:  Require heavy bundle of bazel which does have required tooling. Strip version of bazel is failing in most of the cases.

java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_java_tools/releases/javac11/v4.0/java_tools_javac11_linux-v4.0.zip]

### Feature requests: what underlying problem are you trying to solve with this feature?

any java target cause above issue

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
```
harora37@harora37:~/dummy$ cat BUILD 
java_binary(
    name = "Hello",
    main_class = "com.ibm.amg.services.registration.Hello",
    srcs = ["Hello.java"],
)

harora37@harora37:~/dummy$ cat Hello.java 
package com.ibm.amg.services.registration;

public class Hello {
	public static void main(String...str) {
		System.out.println("Hello Word");
	}
}

```

WARNING: Download from https://mirror.bazel.build/bazel_java_tools/releases/javac11/v4.0/java_tools_javac11_linux-v4.0.zip failed: class javax.net.ssl.SSLProtocolException Connection reset
ERROR: An error occurred during the fetch of repository 'remote_java_tools_linux':
   java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_java_tools/releases/javac11/v4.0/java_tools_javac11_linux-v4.0.zip] to /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/external/remote_java_tools_linux/java_tools_javac11_linux-v4.0.zip: Connection reset
ERROR: /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/external/bazel_tools/tools/jdk/BUILD:224:1: @bazel_tools//tools/jdk:JacocoCoverageRunner depends on @remote_java_tools_linux//:java_tools/JacocoCoverage_jarjar_deploy.jar in repository @remote_java_tools_linux which failed to fetch. no such package '@remote_java_tools_linux//': java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_java_tools/releases/javac11/v4.0/java_tools_javac11_linux-v4.0.zip] to /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/external/remote_java_tools_linux/java_tools_javac11_linux-v4.0.zip: Connection reset
ERROR: Analysis of target '//:Hello' failed; build aborted: no such package '@remote_java_tools_linux//': java.io.IOException: Error downloading [https://mirror.bazel.build/bazel_java_tools/releases/javac11/v4.0/java_tools_javac11_linux-v4.0.zip] to /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/external/remote_java_tools_linux/java_tools_javac11_linux-v4.0.zip: Connection reset
INFO: Elapsed time: 14.269s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (15 packages loaded, 282 targets configured)
FAILED: Build did NOT complete successfully (15 packages loaded, 282 targets configured)
harora37@harora37:~/dummy$ ls
BUILD  Hello.java  WORKSPACE
harora37@harora37:~/dummy$ bazel info release
release 0.29.0

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

```
$:~/dummy$ bazel info
bazel-bin: /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/execroot/__main__/bazel-out/k8-fastbuild/bin
bazel-genfiles: /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/execroot/__main__/bazel-out/k8-fastbuild/bin
bazel-testlogs: /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/execroot/__main__/bazel-out/k8-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/command.log
committed-heap-size: 98MB
execution_root: /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/execroot/__main__
gc-count: 7
gc-time: 178ms
install_base: /home/harora37/.cache/bazel/_bazel_harora37/install/7390d4f46c916c7cd973ba0dce27ab33
java-home: /home/harora37/.cache/bazel/_bazel_harora37/install/7390d4f46c916c7cd973ba0dce27ab33/_embedded_binaries/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 11.0.2+7-LTS) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 11.0.2+7-LTS, mixed mode) by Azul Systems, Inc.
max-heap-size: 8415MB
output_base: /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a
output_path: /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/execroot/__main__/bazel-out
package_path: %workspace%
release: release 0.29.0
repository_cache: /home/harora37/.cache/bazel/_bazel_harora37/cache/repos/v1
server_log: /home/harora37/.cache/bazel/_bazel_harora37/bbea7929ac98478df803126c2ffe502a/java.log.harora37.harora37.log.java.20190829-151108.18109
server_pid: 18109
used-heap-size: 44MB
workspace: /home/harora37/dummy
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

```
release: release 0.29.0
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

this is private repo of IBM

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/rules_scala/issues/798#issuecomment-515017438
but not helping

### Any other information, logs, or outputs that you want to share?

No

FYI @johnynek @nlopezgi @cushon @katre @iirina

**Comment by iirina** [comment]
@aehlig do you know what could cause the `Connection reset` error?

@systemlogic in 70eea9343d4106cdbd549dfd089ec35cba8ef63b I added github urls for java_tools zip in addition to the ones on mirror.bazel, hopefully that works. The change is going to land in bazel 1.0, but you can try it out with bazel@HEAD as well. I couldn't reproduce on my machine.

**Comment by systemlogic** [comment]
@iirina you committed your changes 22 hours back and bazel binary is created 18 hours ago. So if I am not wrong, changes might have already in the latest binary. Is in it ?

**Comment by iirina** [comment]
Unfortunately no, my commit is not in the latest release. bazel 0.29 was released yesterday, but its baseline was at the beginning of the month. See more in #8572.

**Comment by systemlogic** [comment]
Just in case, My project details
```
harora37@harora37:~/dummy$ tree
.
├── BUILD
├── Hello.java
└── WORKSPACE

0 directories, 3 files
harora37@harora37:~/dummy$ cat BUILD 
java_binary(
    name = "Hello",
    main_class = "Hello",
    srcs = ["Hello.java"],
)

harora37@harora37:~/dummy$ cat Hello.java 
public class Hello {
	public static void main(String...str) {
		System.out.println("Hello Word");
	}
}

harora37@harora37:~/dummy$ cat WORKSPACE 
harora37@harora37:~/dummy$
```

**Comment by aehlig** [comment]
> @aehlig do you know what could cause the `Connection reset` error?

Well, whatever makes Java's `UrlConnection.connect()` throw such
an error. It could be the foreign host resetting the connection,
but also a timeout in trying to establish the connection; given
the observed timing, the latter sounds more likely. That _could_
mean, the host is not up, but also it could also mean that someone
on the way drops the packages, e.g., a misconfigured firewall on
your host.

> @systemlogic in 70eea9343d4106cdbd549dfd089ec35cba8ef63b I
> added github urls for java_tools zip in addition to the ones on
> mirror.bazel, hopefully that works.

If you want a work around, you can also download the files manually
and put it where you collect your disfiles, and then point bazel
to it via the `--distdir` option.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by systemlogic** [comment]
yes, It is fire wall issue. But I am surprised how come bazel is not able to download `https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz` and wget works fine in same network.

**Comment by philwo** [comment]
Is this still an issue?
