### ISSUE TITLE
Integrate with a C++ compiler that produces native Windows (not msys) binaries

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#928]
Default plan is Clang, since its command line syntax is much closer to what we do now than MSVC. On the other hand, if we pull off MSVC, we know that our C++ integration is reasonably good.

**Comment by ulfjack** [comment]
Since MSVC works, can we close this now?

**Comment by lberki** [comment]
I'd rather not, since I consider the current implementation a hack. But maybe it's good enough?

**Comment by ulfjack** [comment]
Then either update the bug to say that how we should improve it, or file a new one?

**Comment by lberki** [comment]
https://github.com/bazelbuild/bazel/issues/1488
