### ISSUE TITLE
Bazel 0.29 contains a regression with Remote Build Execution backend

### ISSUE THREAD

**Issue by v-mr** [bazelbuild/bazel#9284]
### Description of the problem / feature request:

Bazel 0.29.0 (https://github.com/bazelbuild/bazel/issues/8572) has regression with Remote Build Execution backend.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

ERROR: <redacted>/test/BUILD:205:5:  failed (Exit 34). Note: Remote connection/protocol failed with: execution failed FAILED_PRECONDITION: Precondition check failed.
 
### What operating system are you running Bazel on?

Linux 4.19.37-5+deb10u1rodete1-amd64 #1 SMP Debian 4.19.37-5+deb10u1rodete1 (2019-07-22 > 2018) x86_64 GNU/Linux

### What's the output of `bazel info release`?

release 0.29.0

**Comment by katre** [comment]
I am investigating with @v-mr

**Comment by lizan** [comment]
We're seeing same issue in envoyproxy/envoy#8074, seems this only happens when `--nocache_test_results` is passed to bazel. I can reproduce it with `--nocache_test_results` but not without it.

**Comment by katre** [comment]
Thank you for the data point, @lizan.

@v-mr has given me a repoduction case and I am bisecting now.

**Comment by katre** [comment]
@lizan It's possible that the difference with `--nocache_test_results` is that when it is not set the tests aren't executed, which seems to be where the failure is.

**Comment by lizan** [comment]
> It's possible that the difference with --nocache_test_results is that when it is not set the tests aren't executed, which seems to be where the failure is.

@katre I doubt so because I changed the our RBE image SHA at same time, which should revoke all cache in the first time when I ran without `--nocache_test_results`.

**Comment by katre** [comment]
Bisect has eventually told me that the culprit is e4ccba45376f74d24ce3506fb4057e1268f01a59. I have no idea why that is, but reverting it from master causes my reproduction to be fixed.

I'm going to debug this further to try and determine _why_ this change causes this failure.

**Comment by katre** [comment]
That commit is the one that caused the action key to change, which is apparently what causes the bug to be visible. It's not the commit that actually causes the error.

**Comment by buchgr** [comment]
Trying to repro. PRECONDITION_FAILED hints at inputs not being uploaded.

**Comment by buchgr** [comment]
I believe the root cause is this line: https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java;l=250?q=RemoteSpawnRunner

**Comment by buchgr** [comment]
https://github.com/bazelbuild/bazel/pull/9287

**Comment by buchgr** [comment]
Here's a patch that applies cleanly on 0.29.0: https://github.com/buchgr/bazel/commit/c475d7d98a457e36a261f92ced9f9303e3f84c44

**Comment by brandjon** [comment]
Came across this issue from a buildkite "Emergency" [message](https://buildkite.com/bazel/bazel-federation/builds/61). Since this issue is closed (and the message refers to a solution "later today"), can the message be removed?

**Comment by katre** [comment]
@brandjon The core issue won't be fixed until 0.29.1 is released, hopefully tomorrow.
