### ISSUE TITLE
Zipped python binaries don't clean up properly when getting a KeyboardInterrupt or other signal

### ISSUE THREAD

**Issue by alschult-saildrone** [bazelbuild/bazel#9285]
### Description of the problem / feature request:

Python binaries build with --build_python_zip don't clean up their runfiles when they are killed with a keyboard interrupt or other signal.  In addition, signals are not passed to the child, which is annoying but less harmful than filling up /tmp.

### Feature requests: what underlying problem are you trying to solve with this feature?

Make python zip binaries clean up after themselves when exiting from KeyboardInterrupt (and other kill signals as well).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build any python binary that runs for a while (or has some main loop like a server process) with --build_python_zip.  While it is running hit CTRL+C to kill the process.  You will see a trace like this:

```
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./bazel-bin/python/can_transfer/can_transfer/__main__.py", line 340, in <module>
  File "./bazel-bin/python/can_transfer/can_transfer/__main__.py", line 313, in Main
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

Look in /tmp (on Linux, $TMPDIR on Darwin, wherever such things go on Windows) and you will see a directory like `Bazel.runfiles_5jTl0o` that was not cleaned up. 

### What operating system are you running Bazel on?

Linux and Darwin.

### What's the output of `bazel info release`?

release 0.28.1

###  Have you found anything relevant by searching the web?

Not really.

### Any other information, logs, or outputs that you want to share?

Looking at the code (the `__main__.py` that is bundled in when you unzip the zipped binary) at line 313 it runs the process via subprocess, and on line 314 it does the `shutil.rmtree` to remove the runfiles.  There is no try/except/finally there, so the process just dies and leaves the files around.  The simplest change would be to try, catch all exceptions and re-raise, but put the rmtree in a finally.  A better outcome would be to properly forward signals to the child and then also clean up, but I would settle just for not leaving the files around (this matters because we run some stuff on embedded systems where /tmp can fill up and it is annoying to have something that routinely clutters that directory).

I initially tried to patch around this, but unfortunately the code that emits this wrapper is in bazel itself (src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt), not in some external repo, so I'd have to patch and rebuild my own bazel to fix this in the short term.  Any other ideas for workaround in the interrim would be great too.

**Comment by ezrec** [comment]
I've provided a patch for Unix systems in #13736 that seems to resolve this issue, using tty process groups.

**Comment by mpereira** [comment]
I run multiple Bazel Python zip services under systemd and hit the same problem. `/tmp/Bazel.runfiles_*` directories accumulate indefinitely after SIGTERM/OOM kills, eventually filling up disk.

My workaround is an hourly cron job that only removes stale runfiles directories (not ones in use by running processes):

```bash
#!/bin/bash
# Clean stale Bazel runfiles directories from /tmp.
# Only removes directories not referenced by any running process.

active=$(ls -la /proc/*/exe 2>/dev/null \
  | grep -oP '/tmp/Bazel\.runfiles_[a-z0-9_]+' \
  | sort -u)

for dir in /tmp/Bazel.runfiles_*/; do
    [ -d "$dir" ] || continue
    dirpath="${dir%/}"
    if echo "$active" | grep -qF "$dirpath"; then
        echo "$(date -Iseconds) IN_USE $dirpath"
    else
        echo "$(date -Iseconds) REMOVING $dirpath"
        rm -rf "$dirpath"
    fi
done
```

I deploy it to `/usr/local/bin/stale-bazel-runfiles-cleaner.sh` and run it hourly via cron. It checks `/proc/*/exe` symlinks to identify which runfiles directories are still in use by running processes, and only deletes the rest. Has been working well for me across ~7 servers.
