### ISSUE TITLE
Upgrade error-prone to 2.3.3?

### ISSUE THREAD

**Issue by dpursehouse** [bazelbuild/bazel#9286]
It looks like Bazel is still using 2.3.2 snapshot version.  Any chance to upgrade to the latest 2.3.3 release?

**Comment by iirina** [comment]
We had to revert the Error Prone upgrade. The new version includes new checks which break backwards compatibility for bazel 1.1. There are more details in #10023. The upgrade to Error Prone 2.3.3 has to be done under an incompatible change.

If someone wants to use Error Prone 2.3.3 before it becomes the default in Bazel they can do so by using the `java_tools_javac11-v6.0` release:

Add the definition of `http_archive` for your OS to your WORKSPACE file:

```
http_archive(
    name = "remote_java_tools_linux",
    sha256 = "37acb8380b1dd6c31fd27a19bf3da821c9b02ee93c6163fce36f070a806516b5",
    urls = [
        "https://mirror.bazel.build/bazel_java_tools/releases/javac11/v6.0/java_tools_javac11_linux-v6.0.zip",
        "https://github.com/bazelbuild/java_tools/releases/download/javac11-v6.0/java_tools_javac11_linux-v6.0.zip",
    ],
)

http_archive(
    name = "remote_java_tools_windows",
    sha256 = "384e138ca58842ea563fb7efbe0cb9c5c381bd4de1f6a31f0256823325f81ccc",
    urls = [
        "https://mirror.bazel.build/bazel_java_tools/releases/javac11/v6.0/java_tools_javac11_windows-v6.0.zip",
        "https://github.com/bazelbuild/java_tools/releases/download/javac11-v6.0/java_tools_javac11_windows-v6.0.zip",
    ],
)

http_archive(
    name = "remote_java_tools_darwin",
    sha256 = "5a9f320c33424262e505151dd5c6903e36678a0f0bbdaae67bcf07f41d8c7cf3",
    urls = [
        "https://mirror.bazel.build/bazel_java_tools/releases/javac11/v6.0/java_tools_javac11_darwin-v6.0.zip",
        "https://github.com/bazelbuild/java_tools/releases/download/javac11-v6.0/java_tools_javac11_darwin-v6.0.zip",
    ],
)
```

and set the toolchain on the command line, for example:
```
--java_toolchain=@remote_java_tools_linux//:toolchain
```

**Comment by cushon** [comment]
Is there are a repro for #10023? It's hard to tell from the error message if that's a bug in the kt rules, or dagger, or error prone.

The `RefersToDaggerCodegen` check uses `@Generated` annotations to distinguish whether code was generated by dagger or handwritten. It's possible the annotations could be missing in code using a version of dagger that predates https://github.com/google/auto/commit/0383c1cf7472d7444463353aa2ac956c9471130a and https://github.com/google/dagger/commit/5c9063f0c8204d97cb255dff7b81bfec404a6d3e.

```
ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ecf942666dab041fc60b1286a219db3e/external/io_bazel_rules_kotlin/src/main/kotlin/io/bazel/kotlin/builder/BUILD:34:1: Couldn't build file external/io_bazel_rules_kotlin/src/main/kotlin/io/bazel/kotlin/builder/libbuilder.jar: Building external/io_bazel_rules_kotlin/src/main/kotlin/io/bazel/kotlin/builder/libbuilder.jar (2 source files) and running annotation processors (ComponentProcessor) failed (Exit 1)
--
  | bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/io/bazel/kotlin/builder/_javac/builder/libbuilder_sourcegenfiles/io/bazel/kotlin/builder/KotlinBuilderComponent_Module_ProvidePluginArgEncoderFactory.java:23: error: [RefersToDaggerCodegen] Don't refer to Dagger's internal or generated code
  | return providePluginArgEncoder(module, toolchainProvider.get());
  | ^
```

**Comment by dpursehouse** [comment]
It looks like #10023 was closed.  Does that mean the error prone upgrade can go ahead now?

**Comment by davido** [comment]
As pointed out by @iirina, the root cause for the downstream build failures:

```
  | bazel-out/host/bin/external/io_bazel_rules_kotlin/src/main/kotlin/io/bazel/kotlin/builder/_javac/builder/libbuilder_sourcegenfiles/io/bazel/kotlin/builder/KotlinBuilderComponent_Module_ProvidePluginArgEncoderFactory.java:23: error: [RefersToDaggerCodegen] Don't refer to Dagger's internal or generated code
  | return providePluginArgEncoder(module, toolchainProvider.get());
  | ^
  | (see https://errorprone.info/bugpattern/RefersToDaggerCodegen)
```

was java_tools upgrade of EP to 2.3.3, this issue. The new version introduced new checks, that broke current code. Thta why the idea is to do it with `--incompatible-error-prone-upgrade-to-2.3.3` option.

What is unclear to me: would it mean to select different java_tools release or one and the same java-tools release would include different EP versions (2.3.2 & 2.3.3)?

**Comment by dpursehouse** [comment]
error_prone is now at 2.3.4

Is there any chance to move forward?

**Comment by davido** [comment]
> Is there any chance to move forward?

#11271

**Comment by dpursehouse** [comment]
Superseded by #11271

**Comment by davido** [comment]
> Superseded by #11271

Well, this is a PR, that references this issue.

**Comment by davido** [comment]
I wrote this follow-up issue: #11272.
