### ISSUE TITLE
deps attribute of _java_library_srcs does not have mandatory providers: 'java'. 

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#9288]
This broke Bazel itself in our downstream pipeline.

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1170#2e6b9acd-313e-4190-87e6-839cc6616241

`
(02:07:57) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/f348148a30d03c9d7c17e6a8c9ebda1a/external/googleapis/BUILD.bazel:35:2: in deps attribute of _java_library_srcs rule @googleapis//:google_watch_v1_java_proto_srcs: '@googleapis//:google_watch_v1_java_proto' does not have mandatory providers: 'java'. Since this rule was created by the macro 'java_library_srcs', the error might have been caused by the macro implementation in /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/f348148a30d03c9d7c17e6a8c9ebda1a/external/io_bazel/tools/build_rules/utilities.bzl:37:44
`

**Comment by iirina** [comment]
I'll send a fix asap

**Comment by buchgr** [comment]
Thanks!
