### ISSUE TITLE
Release 0.29.1 - August 2019 (stable)

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#9293]
A patch release is needed after 0.29.0 (#8572) to address the following issues:

- #9284 - Failures in remote execution when tests are not cached
- *TO BE FILED* - Regression in git_repository.

**Comment by hlopko** [comment]
Can we consider a fix for https://github.com/bazelbuild/bazel/issues/9296 to be cherrypicked into 0.29.1?

**Comment by katre** [comment]
Yes, I think #9296 is valid.

**Comment by jmillikin-stripe** [comment]
Filed https://github.com/bazelbuild/bazel/issues/9299 for the git_repository regression from v0.28

**Comment by katre** [comment]
@jmillikin-stripe Thanks!

**Comment by katre** [comment]
Since the fix for #9296 isn't ready, and at this point in the day, before a US holiday weekend, I am going to wait until Tuesday (Sept 3) to cut the first RC for 0.29.1.

**Comment by katre** [comment]
Planning to cut RC1 today. Assuming everything works, we can release on Thursday.

**Comment by katre** [comment]
Release command:
```
$ ./scripts/release/release.sh create --force_rc=1 0.29.1 0.29.0 2c046486f5febb9e475a5589b59abae77f14245e 9e1d65a1fcebff7169a63acad95c7b44302b89c4 8b0bfaf6716327ca6b60692704e3d57766f7ab1f
```

**Comment by katre** [comment]
Release announcement sent: https://releases.bazel.build/0.29.1/rc1/index.html

Waiting for tests: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1179

**Comment by katre** [comment]
Downstream tests all pass (after several retries).

**Comment by keith** [comment]
FYI it seems like a new feature in 0.29.0 broke github archive downloads in some cases https://github.com/bazelbuild/bazel/issues/9327 I'm not sure if this warrants a revert or not

**Comment by buchgr** [comment]
@katre 

An important internal project found a serious bug in remote execution where output files would sometimes not get deleted between builds. In this particular instance we found this to lead to zombie test results. That is test cases showing up as failed that no longer exist in the codebase. I have fixed this problem in master for different reasons not understanding the impact of this bug: https://github.com/bazelbuild/bazel/commit/5c02b92c45b5422971b3164685d9edb771367a1b

**Comment by katre** [comment]
@buchgr Please file a github issue so I can track the reason for the cherrypick.

**Comment by katre** [comment]
There already is an issue: https://github.com/bazelbuild/bazel/issues/8385

**Comment by dslomov** [comment]
Please cherry-pick a0e3bb207fe2044120a2555a37162ee1f2b17500 (fix for #9327)

**Comment by katre** [comment]
Creating RC2:
```
$ ./scripts/release/release.sh create --force_rc=2 0.29.1 e659f0087740f1802d61bd6d40d6cd99f0e52b3a 5c02b92c45b5422971b3164685d9edb771367a1b a0e3bb207fe2044120a2555a37162ee1f2b17500
```

**Comment by katre** [comment]
0.29.1RC2 is available: https://releases.bazel.build/0.29.1/rc2/index.html

Waiting for downstream tests: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1184

**Comment by katre** [comment]
Downstream tests pass! Assuming no further blockers, I should be able to finalize the release on Tuesday, September 10.

**Comment by katre** [comment]
I am finalizing this release today.

**Comment by katre** [comment]
Release is available at https://github.com/bazelbuild/bazel/releases/tag/0.29.1

@petemounce, @excitoon, and @vbatts, please update your packages.

**Comment by vbatts** [comment]
fedora and centos build: https://copr.fedorainfracloud.org/coprs/build/1031249
