### ISSUE TITLE
BazelCon 2019. December 11-12, Sunnyvale, CA

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#9300]
Official site: https://events.withgoogle.com/bazelcon-2019/

Call for papers: https://forms.gle/oAwwX7LbhzrbhZok9

**Comment by aiuto** [comment]
Note to gardening team. Do not triage. This is a pinned as an annoucement.

**Comment by feimeng** [comment]
@aiuto I saw the registration is closed but I'm interested to attend. Who should I talk to?
