### ISSUE TITLE
Remove legacy .java provider from native bazel.

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#9309]
The flag disabling the provider was already flipped in c8a32f2bdb6cf77aeec2be16ded49632c9699e3e (see more details in #7598).

**Comment by iirina** [comment]
cc @hlopko @lberki

**Comment by dslomov** [comment]
Why removing the provider is a blocker for 1.0?

**Comment by lberki** [comment]
So that we don't need to do it after Bazel 1.0 (there is a tiny chance that this is an incompatible change due to the way @iirina implemented its incompatible flag and I'd rather have that happen before 1.0)

**Comment by iirina** [comment]
We'd get a nice clean slate for Java-Starlark APIs, minimizing technical debt and confusion. :) I have a pending internal CL for removing it, awaiting a new rules_android release.

**Comment by dslomov** [comment]
ok, what's the ETA?

**Comment by hlopko** [comment]
I say let's submit & close right now. And push rules_android to release before we release 1.0

**Comment by iirina** [comment]
We'd break internal projects that use rules_android if we push right now. ETA depends on when rules_android are released internally. Best case scenario: release & submit this week.

**Comment by dslomov** [comment]
so why does this change break rules_android again? Is it incompatible? The change that could have broken rules_android was an incompatible flag flip, no?

**Comment by iirina** [comment]
It only breaks the internal rules_android and only the released version. Everything is migrated at head, now the changes have to be propagated to the release version.

**Comment by dslomov** [comment]
Summarizing offline discussion: this turned out to be an incompatible change. So we need to follow the incompatible change policy here. We are not removing the .java in 1.0 (but we are removing all its attributes, so that it is just an empty struct)

**Comment by iirina** [comment]
I linked the wrong issue in 06fcb83c550606cc2bf331006d4e276e490724ed.

**Comment by c-mita** [comment]
Removed in c58f966a and the associated flag was removed in 64750aa3.
