### ISSUE TITLE
Cut all dependencies on bash [duplicate of #4319]

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#931]
This will be a "death of a thousand cuts" kind of thing, because we probably use tiny little shell scripts all over the place.

**Comment by davidzchen** [comment]
What exactly is the scope of this? Is it mostly limited to non-test code? Will we have a separate set of shell tests on Windows that run on either powershell or cmd.exe?

Also, what are the implications of Windows support on the `sh_*` rules?

**Comment by lberki** [comment]
Yes :)

We haven't really figured out yet what we'll do about this. My hunch is that sh_* rules will stay the same, and they will simply not work on Windows for the time being.

**Comment by johnynek** [comment]
why not just ship a bash as part of bazel that can be used on windows and consider bash to be part of the standard tools? There seem to be a few possibilities.

It would be really nice if skylark rules can assume a working bash and a minimal set of tools (unzip, find, zip, ...)

**Comment by laszlocsomor** [comment]
I envision Bash support via a local repository.
Also I'd like Bazel to depend on Bash only if you try to build `sh_*` rules (or depend on labels under the make-believe `@local_bash_config//` repo).

**Comment by laszlocsomor** [comment]
Duplicate of #4319
