### ISSUE TITLE
Windows: Bazel sometimes crash during startup on Bazel CI

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#9316]
```
D:\temp\tmprjk1zj1a\bazel-bin\src\bazel --output_user_root=D:/b --nomaster_bazelrc --bazelrc=/dev/null version
--
  | Extracting Bazel installation...
  | Starting local Bazel server and connecting to it...
  | Server crashed during startup. Now printing d:\b\iu3f4rjz\server\jvm.out
```

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1177#cdad2bab-64c0-4621-8535-78e6230f9df0
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1177#e7ed76ba-f1d1-4ced-a7e9-15043f62e84e
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1177#ae175667-0688-4266-926f-6d858da37764
/cc @laszlocsomor

**Comment by meteorcloudy** [comment]
Crash also happens to 0.29.0, but with different error message

https://buildkite.com/bazel/rules-nodejs-nodejs/builds/3780#326af6fb-62b5-41c2-a212-015308d4522a

**Comment by philwo** [comment]
Yun suspected that the health check on Windows might be causing these problems. I'm not sure about this, because I couldn't see any health check failures in the logs, but I also can't think of anything else that recently changed, so I've disabled it temporarily for the bk-windows instance group.

**Comment by meteorcloudy** [comment]
Thanks! Let's see if it helps ;)

**Comment by meteorcloudy** [comment]
This no longer happens when we revert to use an old version of buildkite agent. So it should not be a Bazel bug, closing.
