### ISSUE TITLE
Tree artifacts don't seem to work on Windows

### ISSUE THREAD

**Issue by ale64bit** [bazelbuild/bazel#9321]
### Description of the problem / feature request:

Tree artifacts don't seem to work on Windows.

### Feature requests: what underlying problem are you trying to solve with this feature?

Generate a `cc_library` from an unknown number of source files, e.g. because they are produced by a tool.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Same as in the accepted answer here: https://stackoverflow.com/questions/48417712/how-to-build-static-library-from-the-generated-source-files-using-bazel-build/48524539#48524539

But with a small modification to make it compatible with Windows:

genccs.bzl: verbatim.

BUILD: verbatim.

genccs.cpp:
```cpp
#include <fstream>
#include <Windows.h>// BEFORE: <sys/stat.h>
using namespace std;

int main (int argc, char *argv[]) {
  CreateDirectory(argv[1], NULL); // BEFORE: mkdir(argv[1], S_IRWXU);
  ofstream myfile;
  myfile.open(string(argv[1]) + string("/foo.cpp"));
  myfile << "int main() { return 42; }";
  return 0;
}
```

WORKSPACE: empty file.

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.29.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Relevant question and answer: https://stackoverflow.com/questions/48417712/how-to-build-static-library-from-the-generated-source-files-using-bazel-build/48524539#48524539

Other relevant links:
https://github.com/bazelbuild/bazel/issues/5093

### Any other information, logs, or outputs that you want to share?

When running `bazel build main` with the above example, I'm getting:
```
INFO: Analyzed target //:main (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/src/treeartifact/BUILD:7:1: output '_dotd/main/gen_tree/foo.obj.d' was not created
ERROR: C:/src/treeartifact/BUILD:7:1: not all outputs were created or valid
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.087s, Critical Path: 2.23s
INFO: 4 processes: 4 local.
FAILED: Build did NOT complete successfully
```

**Comment by jin** [comment]
cc @laszlocsomor

**Comment by buchgr** [comment]
Chatted about this with @meteorcloudy this week. We don't expand them in the manifest as we do in the runfiles tree. Will send a fix.

**Comment by meteorcloudy** [comment]
@buchgr This looks like a different issue, `_dotd/main/gen_tree/foo.obj.d` shouldn't be required on Windows.

**Comment by meteorcloudy** [comment]
Maybe using tree artifact triggered some code path that should not run on Windows.

**Comment by laszlocsomor** [comment]
@buchgr : thanks for the info! Do you have a repro?

**Comment by ale64bit** [comment]
Is there a workaround I can use in the meanwhile?

**Comment by laszlocsomor** [comment]
@ale64bit : I don't think so.

/cc @hlopko , @oquenchil , @scentini:
Meanwhile I found it's CppCompileActionTemplate unconditionally creating a `.d` output: https://github.com/bazelbuild/bazel/blob/ed68a81f7938067d05fd7525f4aece6db59326b3/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileActionTemplate.java#L130-L132

If I comment that out and make `dotdFileArtifact = null`, and comment out these lines: https://github.com/bazelbuild/bazel/blob/ed68a81f7938067d05fd7525f4aece6db59326b3/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileActionTemplate.java#L195-L197

then the bug vanishes.

**Comment by meteorcloudy** [comment]
I just sent a fix for this, https://github.com/bazelbuild/bazel/pull/9454 ;)
