### ISSUE TITLE
build tensorflow serving error

### ISSUE THREAD

**Issue by wang703** [bazelbuild/bazel#9323]
The following error occurred when I build tensorflow serving, may I ask what the problem is ?
Thank you very mach!

DEBUG: /opt/bazel/4f8ec4b658b1c361a6a9d73c1034bafc/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
ERROR: /opt/bazel/4f8ec4b658b1c361a6a9d73c1034bafc/external/org_tensorflow/tensorflow/workspace.bzl:889:5: no such package '@grpc//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/grpc/grpc/archive/69b6c047bc767b4d80e7af4d00ccb7c45b683dae.tar.gz, https://github.com/grpc/grpc/archive/69b6c047bc767b4d80e7af4d00ccb7c45b683dae.tar.gz] to /opt/bazel/4f8ec4b658b1c361a6a9d73c1034bafc/external/grpc/69b6c047bc767b4d80e7af4d00ccb7c45b683dae.tar.gz: Read timed out and referenced by '//external:grpc_cpp_plugin'
ERROR: Analysis of target '//tensorflow_serving/apis:prediction_service_proto' failed; build aborted: Analysis failed

**Comment by jin** [comment]
Can you access either https://mirror.bazel.build/github.com/grpc/grpc/archive/69b6c047bc767b4d80e7af4d00ccb7c45b683dae.tar.gz or https://github.com/grpc/grpc/archive/69b6c047bc767b4d80e7af4d00ccb7c45b683dae.tar.gz?

**Comment by wang703** [comment]
Thank you very much for your reply
I can go to the second site and download it

**Comment by wang703** [comment]
The following error occurred when I build tensorflow serving
Could you tell me how to do ?

ERROR: Skipping 'tensorflow_serving/...': no targets found beneath 'tensorflow_serving/util/net_http/client/testing/tensorflow_serving'
WARNING: Target pattern parsing failed.
ERROR: no targets found beneath 'tensorflow_serving/util/net_http/client/testing/tensorflow_serving'

**Comment by jin** [comment]
That looks like an issue for the Tensorflow build. Please open an issue on https://github.com/tensorflow/tensorflow/issues instead.
