### ISSUE TITLE
Make Windows-style paths work

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#933]
We currently uses the Windows -> Unix path mapping msys provides, which will have to go, mainly so that things like `local_repository(name="foo", path="c:\foo")` work, but also so that we can cut the dependency on msys.

`PathFragment` has some support for drive letters, but not paths like `C:foo` or UNC paths. We could just ignore UNC paths for the time being, though.

**Comment by laszlocsomor** [comment]
I think this bug will be fixed by fixing https://github.com/bazelbuild/bazel/issues/2181.
Closing it as a dupe.
