### ISSUE TITLE
env_sets not supported by action_config

### ISSUE THREAD

**Issue by ptychu** [bazelbuild/bazel#9333]
### Description of the problem / feature request:

Adding env_sets to build actions by adding them to [action_config](https://github.com/bazelbuild/bazel/blob/292f90988b667e0eab57e16f0d6ee37a86fd13e5/tools/cpp/cc_toolchain_config_lib.bzl#L461) is not supported as docs suggest. ([cc-toolchain-config-reference](https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html#action-config), [cc_toolchain_config_lib.bzl:141](https://github.com/bazelbuild/bazel/blob/292f90988b667e0eab57e16f0d6ee37a86fd13e5/tools/cpp/cc_toolchain_config_lib.bzl#L141)).

I'm not sure if problem is missing implementation, or misleading docs.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to setup remote license server for my compiler. It's done by environment variable. Therefore I want to add some environment variables to every execution of build action, that uses this compiler. After reading the docs I have come to an understanding that [action_config](https://github.com/bazelbuild/bazel/blob/292f90988b667e0eab57e16f0d6ee37a86fd13e5/tools/cpp/cc_toolchain_config_lib.bzl#L461) is what I should use in this situation.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to provide env_sets to action_config(). Quick comparison between [action_config](https://github.com/bazelbuild/bazel/blob/292f90988b667e0eab57e16f0d6ee37a86fd13e5/tools/cpp/cc_toolchain_config_lib.bzl#L461) and [feature](https://github.com/bazelbuild/bazel/blob/292f90988b667e0eab57e16f0d6ee37a86fd13e5/tools/cpp/cc_toolchain_config_lib.bzl#L336) source code is enough to see it's not implemented.

### What operating system are you running Bazel on?

Windows.

### What's the output of `bazel info release`?

release 0.28.0

###  Have you found anything relevant by searching the web?

Seems to be introduced in issue [#5380](https://github.com/bazelbuild/bazel/issues/5380). Commit: [d2e02548768c8e61607a1317c7c4fee5b29131b2](https://github.com/bazelbuild/bazel/commit/d2e02548768c8e61607a1317c7c4fee5b29131b2#diff-20dcff8f3bfada2be83c3f8fe6966ddb)

**Comment by scentini** [comment]
Hm, I'll take a look to see if we want to support `env_set` in `action-config`, or treat this as a documentation issue. In the meantime, you can define a `feature` with the needed `env_set`, and use the [`implies`](https://github.com/bazelbuild/bazel/blob/292f90988b667e0eab57e16f0d6ee37a86fd13e5/tools/cpp/cc_toolchain_config_lib.bzl#L487) attribute of `action_config` to automatically trigger the `feature`.

**Comment by ptychu** [comment]
@scentini, Thanks. I used `feature` as a workaround, but didn't come up with using `implies`! I'd be willing to prepare a pull request, when it's decided how you want to treat this issue.
