### ISSUE TITLE
constraint_value, config_setting, platform undefined in bzl files.

### ISSUE THREAD

**Issue by RichardHabeeb** [bazelbuild/bazel#9335]
### Description of the problem / feature request:
We cannot write macros using constraint and platform rules because they are not defined for bzl files.

### Feature requests: what underlying problem are you trying to solve with this feature?
It is useful for some embedded projects with many levels of platform inheritance (e.g. arch, microarch, SoC, machine) to want config_settings, constraint_values, and platforms to be defined for each level of inheritance. Copying and pasting constraint and config rules for each level of inheritance is really cumbersome, but is need to use select() and --platform. Hence why a macro is useful here.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Create a macro in a bzl file and use `platform(...)`.

### What operating system are you running Bazel on?
Ubuntu

### What's the output of `bazel info release`?
release 0.29.0

**Comment by katre** [comment]
You need to refer to native rules via the `native` module in macros, so `native.constraint_setting`, `native.constraint_value`, and `native.platform` should work.
