### ISSUE TITLE
Add a linter for file system accesses

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#9336]
I propose to add a flag `--lint_fsa` to Bazel that when enabled traces file system accesses in the execution phase. An initial use case is to detect underspecified actions. The flag could emit warnings and/or generate a report that one could use to better understand which files a build depends on that are not tracked by Bazel. In particular, I imagine this tool to be a useful addition to the debugging tools for remote caching/execution. For example, I can see it turn out to be a good way to increase confidence in a build in the face of remote cache poisoning.

Another use case is to detect overspecified dependencies. The C++ and Java rules already have the ability to prune dependencies based on actual use (via .d and .jdeps files) but other rules and especially tests don't.

Ideally we wouldn't have to develop the tracer ourselves but could reuse https://github.com/jacereda/fsatrace or a similar project. I am not sure about the licensing constraints that we operate under - I ll have to figure this out.

@jmmv @agoulti @ishikhman @ulfjack @lberki @EricBurnett

**Comment by ulfjack** [comment]
@laszlocsomor

**Comment by laszlocsomor** [comment]
Intriguing. Curious, where do you imagine plugging this in? Would this sit atop the existing VFS tracing (with `--profile` / JSON profile)?

> For example, I can see it turn out to be a good way to increase confidence in a build in the face of remote cache poisoning.

Could you explain that a bit?

**Comment by buchgr** [comment]
> Intriguing. Curious, where do you imagine plugging this in? Would this sit atop the existing VFS tracing (with --profile / JSON profile)?

I was thinking about plugging it into the execution strategies. If `--lint_fsa` is set instead of `gcc ...` we'd run `fstrace gcc ...`.

> Could you explain that a bit?

The biggest problem in remote caching are undeclared inputs. That is, we store outputs under a key that does not fully describe the inputs that went into generating them. If we could detect and report these cases a developer could be better made aware of these potential problems. It's then up to the developer to fix them. Does this make sense?

**Comment by laszlocsomor** [comment]
Thanks for explaining!

Bazel already goes to great length to make actions hermetic. I wonder how we breach that, is it by using tools from `/usr/bin`?

**Comment by buchgr** [comment]
> Bazel already goes to great length to make actions hermetic. I wonder how we breach that, is it by using tools from /usr/bin?

Yep. I believe actions accessing absolute paths is the main problem.

**Comment by laszlocsomor** [comment]
Or tools on the PATH.

**Comment by laszlocsomor** [comment]
...meaning `genrule` and shell actions (`ctx.actions.run_shell`)

**Comment by buchgr** [comment]
Yep. All of that too.
