### ISSUE TITLE
ProtoInfo created descriptor sets should include the proto file comments

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/bazel#9337]
`ProtoInfo.*_descriptor_sets` appear to be built without the source comments from the proto file. Well done proto generators also relay the comments into the generated source so IDEs that do source indexing and pick them up to provide contextual tooltips/documentation/etc.

While there are way to a developer to invoke bazel with extra args to work around this (`--protocopt=--include_source_info`) we don't really want to encourage developers to have to use lots of custom flags for their builds, and with the use of remote action caches the use/lack of this flag means cache impacts.

So since the descriptor sets are in the provider for generation rules, it seems like they should provide the sets with comments.  This also means the source generated during a build would match what a developer would get if they just invoked protoc by hand with the .proto files available since generated from parsed proto files always includes comments.

**Comment by Yannic** [comment]
Adding `--include_source_info` to all protoc invocations seems to not break anyone that doesn't test that the generated sources match checked-in sources (e.g. [here](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1231#e8b68262-878b-42c4-9c88-13b26f621196)).

I think it's save to add this behind an `--incompatible_` flag and flip for Bazel 2.0.
@lberki WDYT?

Bazel+downstream: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1231

**Comment by lberki** [comment]
AFAIU it's a backward-compatible change since `--include_source_info` adds information to `FileDescriptorProto` so it could be done without an incompatible change.

@hlopko , WDYT? I'd ordinarly just say go ahead, but I burnt myself once, so I'd like to have another pair of eyes.

**Comment by hlopko** [comment]
This also sounds like backwards compatible change to me. Let's see what @haberman thinks, but for me I'd say go ahead.

Josh, should we worry about enabling this by default for all users? Are there performance/binary size/build speed implications that we should be mindful about?

**Comment by haberman** [comment]
I don't know if I have enough info to make that call on the fly. We should gather a bit of data about what the size/speed implications of this are. Perhaps we can get this data for a sizable google3 build?

**Comment by hlopko** [comment]
I'll try to do that. If you don't want to be blocked by me, I'd be fine with guarding this behavior with a build_setting, default it to off, and let interested users to enable it by hand?

**Comment by Yannic** [comment]
There already is an easy way to enable this (passing `--protocopt=--include_source_info`), so I don't think adding a build_setting for it provides many benefits.

**Comment by thomasvl** [comment]
Any change this is going to get picked up/moved forward?

**Comment by thomasvl** [comment]
@Yannic requiring `--protocopt=--include_source_info` doesn't really help IDE integration as now it is something else that developers (or IDEs) must know to wedge it.  It also means if the developers are using a remote build/cache systems we're encouraging yet more configuration and thus less caching (not only of the descriptor sets, but also the code generated from them).

**Comment by Yannic** [comment]
@thomasvl I might be missing something, but it seems like this is blocked by trying out whether always adding `--include_source_info` breaks Google. I did run some experiments locally and it seems like doing so should be fine.

One thing I did notice during my experiment is that `--protocopt=--include_source_info` makes the build very noisy. We have to ensure to only add `--include_source_info` when generating the descriptors, and not for generating code.

```
INFO: From Generating Java (Immutable) proto_library //third_party/bazel_remote_apis/build/bazel/semver:semver_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
INFO: From Generating Java (Immutable) proto_library //third_party/com_google_protobuf:any_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
INFO: From Generating Java (Immutable) proto_library //third_party/com_google_protobuf:descriptor_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
INFO: From Generating Java (Immutable) proto_library //third_party/com_google_protobuf:timestamp_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
INFO: From Generating Java (Immutable) proto_library //third_party/com_google_protobuf:empty_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
INFO: From Generating Java (Immutable) proto_library //third_party/googleapis/google/api:annotations_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
INFO: From Generating Java (Immutable) proto_library //third_party/googleapis/google/rpc:status_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
INFO: From Generating Java (Immutable) proto_library //third_party/googleapis/google/api:http_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
INFO: From Generating Java (Immutable) proto_library //third_party/googleapis/google/longrunning:operations_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
INFO: From Generating Java (Immutable) proto_library //third_party/bazel_remote_apis/build/bazel/remote/execution/v2:remote_execution_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
INFO: From Generating Java (Immutable) proto_library //third_party/com_google_protobuf:duration_proto:
--include_source_info only makes sense when combined with --descriptor_set_out.
```

I'm also not sure yet how to do this change without breaking users that have tests to verify checked-in sources are equivalent to the generated ones (e.g. https://github.com/kythe/kythe/blob/e6b678887d551a66fcd41038a4d731d800153d64/kythe/proto/go.bzl#L87).
@lberki @haberman Should we move forward with this?

**Comment by thomasvl** [comment]
`--protocopt=--include_source_info` was never my suggestion so I'm not surprised it has some issues.  I was after the descriptor sets in the proto_library providers including the source info, and I'm guessing `--protocopt=--include_source_info` doesn't only apply to those actions, hence the noise.

The only tests that should be validating the generation would be the proto library ones, and I don't think those use the descriptor sets, but if they did, yes, they would need to be updated also.

**Comment by lberki** [comment]
Update: internal testing came back with very few failures, but I don't know what the root cause is (and my brain is too fried to start debugging this evening)

**Comment by dfreese** [comment]
@lberki let me know if there's a way to help out.  I ran into this as well with a rust integration I was working on.

**Comment by dfreese** [comment]
I wanted to check, is anyone still actively working on this?  It would be quite helpful for custom protobuf plugins to be able to rely on the generate descriptor set.

**Comment by perezd** [comment]
We (The Protobuf Team) advise strongly against including proto file comments into transformed target generated code contexts. For a few reasons:

- Hyrum's Law: We've seen requests/attempts to side-chain host language semantics into comments that create unanticipated coupling. The Protobuf Team makes no guarantees that comments will be present, and there are a number of ways you can generate gencode where the comments are impossible to provide, they are generally added opportunistically. (--descriptor_set_out w/o --include_source_code_info).

- The addition of SourceCodeInfo (which contains the comments within the descriptor) can cause unexpected growth of generated artifacts. This may not seem like a big deal if you have 10 files, or even 100, but when you're dealing with a tree of many tens of thousands as we often see internally, this gets out of hand quickly. We're preventing users from hurting themselves by not including this content deliberately.

If we must include them for IDEs or other contexts, this should be a deliberate and opt-in choice, not an implicit default.

**Comment by thomasvl** [comment]
> If we must include them for IDEs or other contexts, this should be a deliberate and opt-in choice, not an implicit default.

That's tricky.  The moment an IDE has to change the build flags to enable some functionality, it means the build is now "different" and thus developer builds can't share remote cache results with CI systems; make the developers build experience worse.

If you scale this advice out to all generators a large build might have, you can end up making the IDE's job that much more complex as they keep having to add more and more custom flags to get the more useful sources to index against.

**Comment by perezd** [comment]
Yeah, this in my mind is the difference between a debug vs release build context...we aren't solving everyones problems with one solution, comments shouldn't be required in 100% of the build contexts.

**Comment by Yannic** [comment]
Thanks, that makes sense! However, I wonder if there's a middle ground between "no SourceCodeInfo" and "all SourceCodeInfo".

One option would be to generate every descriptor set twice: once without and once with SourceCodeInfo. Actions should then use the "with" version for the direct protos they're generating code for and the "without" version for all transitive dependencies. This would allow every action to access the needed SourceCodeInfo and keep the transitive closure of descriptor sets to read small at the same time.

Another option would be to split SourceCodeInfo out of the main descriptor set into it's own file and only provide SourceCodeInfo for direct protos to generate code for to actions (similar to how DWARF supports out-of-binary debug symbols). This would, however, require a change to `protoc` and probably also to generators and/or IDEs.
