### ISSUE TITLE
LabelList not supported for accessing late bound defaults from Starlark

### ISSUE THREAD

**Issue by timpeut** [bazelbuild/bazel#9339]
I have a late bound default defined in native that I'd like to access from Starlark. Usually this would be exposed to Starlark using the [@SkylarkConfigurationField](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/skylark/annotations/SkylarkConfigurationField.java) annotation but this only supports labels and not label lists.

Specifically, I want to access JavaConfiguration.getPlugins, which I exposed to Starlark in [JavaConfigurationsApi](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skylarkbuildapi/java/JavaConfigurationApi.java) but this gives me labels rather than targets.

What is the recommended path forward here?

**Comment by timpeut** [comment]
Friendly ping, how can we get this prioritized?

**Comment by iirina** [comment]
cc @laurentlb

**Comment by c-parsons** [comment]
I would agree this is a feature we should support. I'll see if I can get to this later this week.

**Comment by comius** [comment]
Since @c-parsons didn’t get to this one in a week and because I believe we have both a workaround at the moment and starlark defined flags support it, I’ll close it.
