### ISSUE TITLE
A trivial `java_binary` rule with `main_class` but without `srcs` does not run

### ISSUE THREAD

**Issue by dwtj** [bazelbuild/bazel#9355]
### Description of the problem:

A trivial "Hello, World" `java_binary` target doesn't `bazel run`correctly if the `main_class` is set but the `srcs` attribute is not set.

If I understand [the `main_class` attribute's documentation](https://docs.bazel.build/versions/master/be/java.html#java_binary.main_class) correctly, declaring a `java_binary` target with just a `main_class` and without `srcs` should work. However, on my system invoking `bazel run` on such a target seems to run the `java` command without a main class. Specifically, `bazel run` prints the `java` command's help/usage information to stdout.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- Create an empty Bazel workspace with just an empty `WORKSPACE` file.
- Add a `.java` file defining a class with a `main()` method.
- Add a `BUILD.bazel` file in this `.java` file's package.
- Add a `java_binary` rule with an arbitrary `name` and the `main_class` set to the above-created main class. *Do not add this source file to the `srcs` list.*
- Invoke `bazel run` with this rule's name.

### What operating system are you running Bazel on?

ArchLinux x86_64

### What's the output of `bazel info release`?

`release 0.29.0`

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

No

**Comment by iirina** [comment]
Hi David, thanks for filing this issue. I need a bit more information: does your `java_binary` target have `deps` or `runtime_deps` set? The following part is also in the documentation:

> The class must be available at runtime: it may be compiled by this rule (from srcs) or provided by direct or transitive dependencies (through runtime_deps or deps)

If your `java_binary` doesn't specify `srcs` or any other kind of dependencies bazel won't know where to look for the main class.

**Comment by dwtj** [comment]
@iirina I was just considering a trivial `java_binary` with *only* the `name` and `main_class` attributes. But re-reading the documentation for `main_class`, particularly the part you highlighted, it seems clear to me now that such a rule is just invalid.

I was trying to make the simplest possible `java_binary` for some unrelated troubleshooting, and I misunderstood this:

> If a rule uses this option, it does not need a `srcs=[...]` list.

Maybe it would be clearer to say

> If a rule uses this option, it **may not** need a `srcs=[...]` list.

So, Bazel seems like it is working as intended.

However, I do think that `bazel run` in this (admittedly somewhat artificial) case behaves somewhat surprisingly. The`java` command didn't say "Error: Could not find or load main class". Instead, it acted like it wasn't passed a main class name even though it is right there in the `java_binary` rule.

Oh well. I'm rather embarrassed that I didn't read and understand the documentation properly. Sorry for the bother. I'll just go ahead and close this then. Thanks!
