### ISSUE TITLE
Windows DLL naming conflicts

### ISSUE THREAD

**Issue by mason-bially** [bazelbuild/bazel#9356]
### Description of the problem / feature request:

Having a `cc_binary` rule that outputs a dll and a `cc_library` rule of a similar (but not exact same) name causes a difficult to understand error.

### Feature requests: what underlying problem are you trying to solve with this feature?

currently my strategy is to use various shared objects (of different platforms) wrapped in a common `cc_library` (with select for each platform) to make it easy to include dynamic dependencies (as a single dependency) in a cross platform way. If there was a better way to do what I am doing this probably wouldn't be a bug.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I've included a reproduction (use the command `bazel run runexample`), rename `"example"` in the `BUILD` file to see the error go away.

[repro.zip](https://github.com/bazelbuild/bazel/files/3591924/repro.zip)

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

release 0.29.0

###  Have you found anything relevant by searching the web?

Not particularly. The pattern I am using came from there, but I haven't found this specific bug anywhere.

### Any other information, logs, or outputs that you want to share?

This log isn't particularly helpful at diagnosing the problem, at the very least this should be checked for and a better error emitted.

```
Starting local Bazel server and connecting to it...
ERROR: file 'Example.dll' is generated by these conflicting actions:
Label: //:Example.dll, //:example
RuleClass: cc_binary rule, cc_library rule
Configuration: 29ddea0a42d3348f2f42bae0ac0764dc
Mnemonic: CppLink, Fail
Action key: 9b57ba90ecec55bc37f22f4ce7b39bea, 363599b521c05d7b8fcded7ac3675972
Progress message: Linking Example.dll, Reporting failed target //:example located at C:/data/mason/repo/ob1/repro/out/BUILD:40:1
PrimaryInput: File:[[<execution_root>]bazel-out/x64_windows-fastbuild/internal]_middleme/_S_S_CExample.dll-null, (null)
PrimaryOutput: File:[[<execution_root>]bazel-out/x64_windows-fastbuild/bin]Example.dll, File:[[<execution_root>]bazel-out/x64_windows-fastbuild/bin]example.dll
ERROR: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for Example.dll, previous action: action
 'Reporting failed target //:example located at C:/data/mason/repo/ob1/repro/out/BUILD:40:1', attempted action: action 'Linking Example.dll'
INFO: Elapsed time: 4.313s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (13 packages loaded, 82 targets configured)
```

**Comment by hlopko** [comment]
I'm sorry, what is the feature request there? To allow name conflicts?

**Comment by mason-bially** [comment]
> Having a cc_binary rule that outputs a dll and a cc_library rule of a **similar (but not exact same) name** causes a **difficult to understand error**.

Emphasis mine. The problems are:
* It's not a name conflict, it's a conflict with a *similar name*.
* The error generated is a hard to understand stack trace, if this was intentional it should be a more specific error message.

**Comment by mason-bially** [comment]
I'd call it more of a bug really.

**Comment by hlopko** [comment]
Thank you for your clarification!

* re conflict on windows - how shared library produced by cc_library is named is configured in the C++ toolchain, so it's in the hands of the user and they can configure things like they need. On Linux and Mac you can get similar error by naming the cc_library foo, and naming the cc_binary libfoo.so or libfoo.dylib respectively.
* The error generated is reported from inside the execution phase infrastructure (therefore it's not C++ rules specific) and is most usually shown to rule maintainers when they, well, register conflicting actions so it shows maybe too much detail for a user of the rules. Was it the `ERROR:` field that was confusing?
* In general rules cannot check for presence of other rules in the BUILD file and they cannot check for presence of an action registered by some other rule (handwaving over aspects - aspects do give you the ability to look into rule's dependencies, but outside of those).

I personally am not offended by the error message, but if you feel strongly feel free to rebrand this issue with maybe more specific feedback. Regarding the specific C++ rules problem, I'd say works as intended. If this is blocking you, take a look into https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_toolchain_config_lib.bzl#L516.

Thank you! Please comment if you want to reopen and rebrand this issue for error message format.
