### ISSUE TITLE
Error in Bash completion

### ISSUE THREAD

**Issue by nkoroste** [bazelbuild/bazel#9358]
### Description of the problem / feature request:

After adding:
source /Users/n.korostelev/.bazel/bin/bazel-complete.bash

And trying to use `bazel bui<tab><tab>` I get the following output
```
bazel buiexpr: brackets ([ ]) not balanced
_bazel__get_command:1: unrecognized modifier `C'
ld
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

source /Users/n.korostelev/.bazel/bin/bazel-complete.bash
bazel bui<tab><tab>

### What operating system are you running Bazel on?

MacOS v10.14.6

### What's the output of `bazel info release`?

release 0.28.1
(even though I just successfully updated to 0.29, not sure why it's still saying 28 - another bug?)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.sc-corp.net:Snapchat/android.git
a4106ef1c8d91f554da090628c8c3021058607aa
5e13aafe722d0ff0cdac492a9941ca7ecdb84aa6

###  Have you found anything relevant by searching the web?

No

**Comment by philwo** [comment]
Can you still reproduce this? I think a few improvement to the bash-completion have been made in the meantime and I can't recall seeing this myself.

**Comment by nkoroste** [comment]
I confirmed that this is now fixed on both Bash and Zsh.

Side note, I'm still looking for the capability of adding completion support for custom bazel commands. For example, I want to work for `bazelisk` and `bazelw` both are very common usecases. 

related https://github.com/bazelbuild/bazelisk/issues/29

**Comment by philwo** [comment]
Thanks for confirming! I'll close this then. I would also be very interested in having completion support for Bazelisk etc. - let's track that in the Bazelisk issue.
