### ISSUE TITLE
Ability to apply compiler flags to certain directories, without using .bazelrc

### ISSUE THREAD

**Issue by rdeushane** [bazelbuild/bazel#9359]
### Description of the problem / feature request:
Ability to selectively apply flags when compiling sources located in certain directories;

I would like to use stricter warning flags during compilation, but part of my code base is externally pulled via `http_archive` or sub-modules and I have little control over it.  

### Feature requests: what underlying problem are you trying to solve with this feature?

Bazel provides no way to dynamically apply flags without resorting to `.bazelrc` hackery. There is `--per_file_copt` which provides exactly the result I want, but I have configs for cross-compilation and not all compilers support the warning flags I would like to apply to my default builds. I could create yet another config that applies my `--per_file_copt`, but would then need everyone at my company to specify `--config` to hit it.
  
Because of this, I see the tool-chain definition as the best place to do this. I have defined a default tool-chain file which applies some warning flags (the ones that don't cause failure at third-party code), and was hoping I could use a `flag_group` to expand additional warning flags pending some regex match, but I see no way to do this.
  
The only other options I see are;  
* Add the flags anyways to my tool chain, then write custom build files for every external or submodule repo and modify their `BUILD` targets with `copt=[-Wno-...]` to disable offending warnings  
* Write some wrapper around Bazel to apply `--per_file_copt` when no `--config` is specified    
* Add `copt` to all of my build targets, this is a bad solution for obvious reasons  
* Define my own `cc_library` to apply this flag for internal code, not sure If this would play well with cross-compilation though.

### What operating system are you running Bazel on?
Windows / Linux / OSX

### What's the output of `bazel info release`?

We use `0.24.1` through `0.29.0`

###  Have you found anything relevant by searching the web?
No. I've found many threads asking for what I am trying to accomplish, with no solutions, but I would be thrilled to be proven wrong.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
