### ISSUE TITLE
No dependency file when building

### ISSUE THREAD

**Issue by zhang-jian** [bazelbuild/bazel#936]
Hi all,

I am getting an error when compiling bazel 1.5.

My environment is

which gcc
`/packages/gcc/4.9.0/bin/gcc
/work/01/student/works/tensorflow-install/bazel> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/packages/gcc/4.9.0/bin/../libexec/gcc/x86_64-suse-linux/4.9.0/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/packages/gcc/4.9.0 --enable-languages=c,c++,fortran --disable-plugin --with-pkgversion=un --disable-libgcj --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 4.9.0 (un) `

which java
`/packages/java/1.8.0/jdk1.8.0/bin/java
/work/01/student/works/tensorflow-install/bazel> java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)`

The error I got is

`
INFO: You can skip this first step by providing a path to the bazel binary as second argument:
INFO:    ./compile.sh compile /path/to/bazel
  Building Bazel from scratch......
INFO: Found 1 target...
ERROR: /work/01/student/works/tensorflow-install/bazel/src/main/cpp/util/BUILD:24:1: C++ compilation of rule '//src/main/cpp/util:md5' failed: gcc failed: error executing command 
  (cd /tmp/bazel.FweK0XqQ/out/bazel && \
  exec env - \
 PATH=/packages/java/1.8.0/jdk1.8.0/bin:/packages/gcc/4.9.0/bin:/home/users/student/anaconda/bin:/work/01/student/tools/zlib-1.2.8:/home/packages/cuda/5.5/bin/:/opt/sgi/sbin:/opt/sgi/bin:/home/users/student/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/opt/c3/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/mam/bin:/opt/moab/bin:/opt/moab/sbin:. \
  /packages/gcc/4.9.0/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote bazel-out/local_linux-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local_linux-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o' -MD -MF bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.d -fPIC -c src/main/cpp/util/md5.cc -o bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: gcc failed: error executing command 
  (cd /tmp/bazel.FweK0XqQ/out/bazel && \
  exec env - \
 PATH=/packages/java/1.8.0/jdk1.8.0/bin:/packages/gcc/4.9.0/bin:/home/users/student/anaconda/bin:/work/01/student/tools/zlib-1.2.8:/home/packages/cuda/5.5/bin/:/opt/sgi/sbin:/opt/sgi/bin:/home/users/student/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/opt/c3/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/mam/bin:/opt/moab/bin:/opt/moab/sbin:. \
  /packages/gcc/4.9.0/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote bazel-out/local_linux-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local_linux-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o' -MD -MF bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.d -fPIC -c src/main/cpp/util/md5.cc -o bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //src:bazel failed to build
INFO: Elapsed time: 2.689s, Critical Path: 0.37s
Building output/bazel`

When I ran it directly, I got

`/packages/gcc/4.9.0/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote bazel-out/local_linux-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local_linux-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o' -MD -MF bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.d -fPIC -c src/main/cpp/util/md5.cc -o bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o
src/main/cpp/util/md5.cc:343:1: fatal error: opening dependency file bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.d: No such file or directory
 }  // namespace blaze_util
 ^
compilation terminated.
`

Thanks again for you help.

Jian

**Comment by damienmg** [comment]
Did you added your gcc path to tools/cpp/CROSSTOOL?

**Comment by zhang-jian** [comment]
Yes, at line 
`/packages/gcc/4.9.0/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote bazel-out/local_linux-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/local_linux-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-fastbuild/bin/src/main/cpp/util/_objs/md5/src/main/cpp/util/md5.pic.o`
I can see that brazel is using the correct gcc.

**Comment by damienmg** [comment]
Ok can you comment the line https://github.com/bazelbuild/bazel/blob/master/scripts/bootstrap/buildenv.sh#L56 and retries compile then retries the command printed when failing?

**Comment by zhang-jian** [comment]
@damienmg if I comment 
`atexit "rm -fr ${DIR}"`
,then compile the failing line directly (copy &paste it to terminal), the compile would be fine for that class.
But not by running ./compile.sh.

 I have tried this several times. copy & paste is fine, by ./compile.sh failed. Is this an indication that I set CROSSTOOL wrong?

Thanks again

**Comment by damienmg** [comment]
Hi sorry for the late answer,

We have an experimental feature to do C++ auto-configuration:
https://groups.google.com/d/msg/bazel-discuss/MSunz2ZUOq0/U5tE7uQLJQAJ

Can you try and tell me if it worked for you?
