### ISSUE TITLE
SHA512 dependency checking

### ISSUE THREAD

**Issue by sgammon** [bazelbuild/bazel#9368]
### Description of the problem / feature request:

Some news outlets are reporting that SHA256 was broken some time ago. It may be time to lay the piping to support SHA512 for dependency verification.

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm requesting an upgrade to SHA512, or at least support for SHA512 in addition to SHA256. For example:

https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/hash/sha256.py#L28

### What operating system are you running Bazel on?

I'm running on `macOS`.

### What's the output of `bazel info release`?

```
release 0.28.1
```

###  Have you found anything relevant by searching the web?

Previous move to add `SHA256` support by default: https://github.com/bazelbuild/bazel/issues/3193

### Any other information, logs, or outputs that you want to share?

It's not clear that a reliable collision algo is actually available. Filing this to track the issue.

**Comment by jin** [comment]
> Some news outlets are reporting that SHA256 was broken some time ago. 

Could you link to these references here, please?

**Comment by janakdr** [comment]
Closing, since we have no reports of SHA256 vulnerability.
