### ISSUE TITLE
cannot find a NameResolver for grpcs://remotebuildexecution.googleapis.com on Windows (bazel 0.29.1)

### ISSUE THREAD

**Issue by jtattermusch** [bazelbuild/bazel#9369]
### Description of the problem / feature request:

After migrating to bazel 0.29.1 on windows, we're getting this error:

```
T:\src\github\grpc>bazel --bazelrc=tools/remote_build/windows.bazelrc build --invocation_id="33a02e8a-c4a5-428d-a74f-1af0531b2c16" --workspace_status_command=tools/remote_build/workspace_status_kokoro.sh :all --google_credentials=T:\src\gfile/rbe-windows-credentials.json
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
t:\src\github\grpc/tools/bazel.rc
Starting local Bazel server and connecting to it...
ERROR: Failed to connect to 'grpcs://remotebuildexecution.googleapis.com': cannot find a NameResolver for grpcs://remotebuildexecution.googleapis.com
ERROR: Failed to connect to 'grpcs://remotebuildexecution.googleapis.com': cannot find a NameResolver for grpcs://remotebuildexecution.googleapis.com
INFO: Streaming Build Event Protocol to https://source.cloud.google.com/results/invocations/33a02e8a-c4a5-428d-a74f-1af0531b2c16
```
I think the problem is new in 0.29.1 because on 0.29 we didn't have that problem (but there was another bazel bug that forces upgrade to 0.29.1).

### Feature requests: what underlying problem are you trying to solve with this feature?

we're trying to migrate bazel RBE to just-released bazel 0.29.1

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See PR:
https://github.com/grpc/grpc/pull/20222#issuecomment-530037375

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

bazel 0.29.1, obtained via chocolatey

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

**Comment by jtattermusch** [comment]
@laszlocsomor  is there a way to install the dev versions based on the commit using chocolatey?
This is the command we are using to setup bazel windows on our CI:
https://github.com/grpc/grpc/pull/20222/files#diff-f4b86571b28dfff04ed9b0853aba7f70R18

**Comment by laszlocsomor** [comment]
@jtattermusch : No, only release versions are distributed via Chocolatey. You need to build Bazel from source at the desired version: https://docs.bazel.build/versions/0.29.1/install-compile-source.html#build-bazel-using-bazel

**Comment by jtattermusch** [comment]
@laszlocsomor  that's pretty hard for me to do (our bazel RBE setup is only tested on CI, so this would include lot of experimenting on my side just be able to build bazel from source), but I just confirmed that the 0.29.0 bazel RBE build works just fine on windows (https://source.cloud.google.com/results/invocations/a1696487-8eac-476e-8663-bac00f559fce/targets), but 0.29.1 is broken.

**Comment by laszlocsomor** [comment]
@jtattermusch : I see. If I gave you custom Bazel binaries, could you test with them?

**Comment by jtattermusch** [comment]
I've tried to build with different bazel versions on bazel RBE and I wasn't able to get things failing again.
Also, the 0.29.1 upgrade has passed here: https://github.com/grpc/grpc/pull/20264 (https://source.cloud.google.com/results/invocations/7d784d84-d4e1-4492-862e-52541b413026/targets). So I'll have to assume the problem I've seen was some sort of transient issue (a flake).

Sorry for the false alarm and thanks @laszlocsomor  for help with testing.

**Comment by jtattermusch** [comment]
Just to provide more context:
I found what the underlying problem was (and it's not related to bazel):
In our test scripts we install the right bazel version as the first step and then run the tests.
From time to time, if the `choco install` command fails, the right version of bazel is not installed and
the fallback is the bazel installed on the machine - which is way too old and doesn't know anything about the "grpcs://" prefix.

```
:\src>choco install bazel -y --version 0.29.1 --limit-output 
Installing the following packages:
bazel
By installing you accept licenses for the packages.
bazel not installed. An error occurred during installation:
 The remote server returned an error: (503) Server Unavailable. Service Unavailable
bazel package files install completed. Performing other installation steps.
The install of bazel was NOT successful.
bazel not installed. An error occurred during installation:
 The remote server returned an error: (503) Server Unavailable. Service Unavailable

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - bazel (exited 1) - bazel not installed. An error occurred during installation:
 The remote server returned an error: (503) Server Unavailable. Service Unavailable
```
