### ISSUE TITLE
Rules are not allowed to cross the boundary of subpackages after bazel 0.26

### ISSUE THREAD

**Issue by Iorek73** [bazelbuild/bazel#9370]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Rules are crossing boundary of subpackages. Is this an install issue or something deeper? Installed on windows 7 using choco.

### Feature requests: what underlying problem are you trying to solve with this feature?

Running the following code from site-packages
`bazel run -c opt tensorflow/lite/toco:toco -- --input_file=tensorflow/models/research/object_detection/inference_graph/tflite_graph.pb --output_file=tensorflow/models/research/object_detection/inference_graph/detect.tflite --input_shapes=1,300,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3' --inference_type=QUANTIZED_UINT8 --mean_values=128 --std_values=128 --change_concat_input_ranges=false --allow_custom_ops`

### What operating system are you running Bazel on?

Windows 7

### What's the output of `bazel info release`?

Bazel 0.29.0

###  Have you found anything relevant by searching the web?

Perhaps similar to issues https://github.com/bazelbuild/bazel/issues/103, 
https://github.com/bazelbuild/bazel/issues/9, https://github.com/bazelbuild/bazel/issues/2181

### Any other information, logs, or outputs that you want to share?

```
(base) C:\Users\b0588718\AppData\Local\Continuum\anaconda3\Lib\site-packages>baz
el run -c opt tensorflow/lite/toco:toco -- --input_file=tensorflow/models/resear
ch/object_detection/inference_graph/tflite_graph.pb --output_file=tensorflow/mod
els/research/object_detection/inference_graph/detect.tflite --input_shapes=1,300
,300,3 --input_arrays=normalized_input_image_tensor --output_arrays='TFLite_Dete
ction_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProces
s:2','TFLite_Detection_PostProcess:3' --inference_type=QUANTIZED_UINT8 --mean_va
lues=128 --std_values=128 --change_concat_input_ranges=false --allow_custom_ops

WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
Starting local Bazel server and connecting to it...
Loading:
Loading: 0 packages loaded
ERROR: Skipping 'tensorflow/lite/toco:toco': error loading package 'tensorflow/l
ite/toco': Label '//tensorflow/core/platform:default/build_config.bzl' is invali
d because 'tensorflow/core/platform/default' is a subpackage; perhaps you meant
to put the colon here: '//tensorflow/core/platform/default:build_config.bzl'?
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/lite/toco': Label '//tensorflow/core/pl
atform:default/build_config.bzl' is invalid because 'tensorflow/core/platform/de
fault' is a subpackage; perhaps you meant to put the colon here: '//tensorflow/c
ore/platform/default:build_config.bzl'?
INFO: Elapsed time: 3.573s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by irengrig** [comment]
Hi @Iorek73, thank you for reporting the issue!
The error message looks correct, though //tensorflow/core/platform:default/build_config.bzl is indeed the expression used in Tensorflow code in many places.

/cc @meteorcloudy

**Comment by meteorcloudy** [comment]
Yes, we need to upgrade TensorFlow for this breaking change first. TF is still on an old Bazel version (0.26.0).

**Comment by aiuto** [comment]
0.26 is end of life
