### ISSUE TITLE
can't build //scripts:bazel-complete.bash on linux

### ISSUE THREAD

**Issue by cristifalcas** [bazelbuild/bazel#9373]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Can't build //scripts:bazel-complete.bash on linux on master or 0.29.1. It works on 0.29.0

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone 
cd bazel
$ bazel build //scripts:bazel-complete.bash
Starting local Bazel server and connecting to it...
ERROR: /home/cfalcas/bazel-master/src/main/res/winsdk_configure.bzl:39:1: file '@bazel_tools//tools/cpp:cc_configure.bzl' does not contain symbol 'MSVC_ENVVARS'
ERROR: /home/cfalcas/bazel-master/src/main/res/winsdk_configure.bzl:172:20: Traceback (most recent call last):
	File "/home/cfalcas/bazel-master/src/main/res/winsdk_configure.bzl", line 169
		repository_rule(implementation = _impl, local = Tr..., ...))
	File "/home/cfalcas/bazel-master/src/main/res/winsdk_configure.bzl", line 172, in repository_rule
		list(MSVC_ENVVARS)
	File "/home/cfalcas/bazel-master/src/main/res/winsdk_configure.bzl", line 172, in list
		MSVC_ENVVARS
global variable 'MSVC_ENVVARS' is referenced before assignment.
ERROR: error loading package '': Extension file 'src/main/res/winsdk_configure.bzl' has errors
ERROR: error loading package '': Extension file 'src/main/res/winsdk_configure.bzl' has errors
INFO: Elapsed time: 5.324s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### What operating system are you running Bazel on?

Tested on linux Debian and Centos 7

### What's the output of `bazel info release`?

`release 0.28.1`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

No

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by hlopko** [comment]
Hi @cristifalcas, to double check, this is happening in Bazel 0.29.1 or 0.28.1?

**Comment by hlopko** [comment]
cc @laszlocsomor

**Comment by laszlocsomor** [comment]
Which git commit of the Bazel tree are you building at (`git rev-parse HEAD`)? Does `git status` report any changed files?

**Comment by laszlocsomor** [comment]
I can build this target on Debian:
```
  $ bazel --version
bazel 0.29.1

  $ bazel build //scripts:bazel-complete.bash
INFO: Build completed successfully, 10 total actions

  $ git remote get-url origin ; git rev-parse master ; git rev-parse HEAD
https://bazel.googlesource.com/bazel
3e5998755223ca0709d0819973ed2114b0f66d68
3e5998755223ca0709d0819973ed2114b0f66d68
```

**Comment by ignasl** [comment]
I am getting the same problem on MacOS when building master.

**Comment by laszlocsomor** [comment]
@ignasl : What do `bazel --version` and `git log -1` print for you? I can build fine on macOS using Bazel 0.29.0 and the command `bazel --ignore_all_rc_files build //scripts:bazel-complete.bash` at commit 5f9747501b87c61d8517368b2ee34a38b71f4276.

**Comment by ignasl** [comment]
Build has failed on 0.28.1 and 0.27.1, maybe other earlier versions fail as well. `git log -1` is:
```
commit 5f9747501b87c61d8517368b2ee34a38b71f4276 (HEAD -> master, origin/master, origin/HEAD)
```
On 0.29.0 it seems to be building just fine.

**Comment by laszlocsomor** [comment]
Thanks for clarifying!

**Comment by hoffbrinkle** [comment]
I'm hitting this issue as well.

I'm not terribly familiar with how the bazel_tools repository works, but when I look at externals, bazel_tools looks to be coming the binary that's being used run bazel rather rather than what's in the bazel_tools/ directory in the source tree.

**Comment by hoffbrinkle** [comment]
So, building on that and looking at the source, I was able to build an intermediate version of bazel that allows me to build 0.29.1.  Specifically, I built a version of bazel at 07853cdc0e.  This then includes the necessary bit in that binary, after which I used that binary to build 0.29.1.

**Comment by laszlocsomor** [comment]
@hoffbrinkle : Indeed, `@build_tools` is not a source directory but a special repo generated by the Bazel binary you build with.
What's the importance of https://github.com/bazelbuild/bazel/commit/3e0231827a7e3e33de30829a7c3108e17cb2d155?

**Comment by hoffbrinkle** [comment]
Sorry, the key is change is 8b0bfaf6, not 3e02318.  It was that change that starts going to the binary version of the bazel_tools repo.  And that change was cherry picked into 0.29.1.  So, in order to build 0.29.1, you need to use a binary that includes the correct bazel_tools internally.  In terms of releases, you can only build 0.29.1 with a 0.29.0 binary.

**Comment by hlopko** [comment]
We don't support building Bazel with non-latest Bazel releases. So it seems to me that this issue can be closed. Please complain if this is not true. Thank you!

**Comment by hoffbrinkle** [comment]
Totally makes sense. Either you have the latest binary to compile bazel with or you have to bootstrap.  While it does make it a little more cumbersome, it certainly removes any release requirements around a change like this, so a fair trade off as far as I'm concerned.  Thanks!

**Comment by clnperez** [comment]
LMK if I should open a new issue for this -- but I've run into the same problem, but on ppc64le. I built a 0.29.0 binary (cherry-picking in https://github.com/bazelbuild/bazel/pull/9346) for ppc64le. Using *that* -- I still can't build master (`bazel --server_javabase /usr build //src:bazel`)
