### ISSUE TITLE
Generating Coverage report outputs failure of a previously fulfilled test

### ISSUE THREAD

**Issue by Sagre** [bazelbuild/bazel#9375]
### Description of the problem

Running a coverage report with `bazel coverage //path` results in the test to be marked as failed, even though `bazel test` succeeds. The test log then states: `LAUNCHER ERROR: Rlocation failed on local_jdk/bin/java.exe, path doesn't exist in MANIFEST file`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use the adapted bazel example from https://github.com/Sagre/bazel-coverage-failure and run `bazel coverage //my_test:test.exe`

### What operating system are you running Bazel on?

> Replace this line with your answer.
Windows 10 64-bit

### What's the output of `bazel info release`?

release-0.29.1

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/4309
However, this references a java_test. But the failure looks relatable. And my coverage.dat is indeed empty

### Any other information, logs, or outputs that you want to share?
Test.log
[test.log](https://github.com/bazelbuild/bazel/files/3606063/test.log)

Console output for running `bazel coverage //my_test:test.exe --subcommands`
[bazel_output.txt](https://github.com/bazelbuild/bazel/files/3606092/bazel_output.txt)

**Comment by iirina** [comment]
It looks like you're trying to get coverage for C++ targets on Windows, which is not yet support by Bazel.

By looking at the test log I can also see another failure:
```
ln: failed to create symbolic link '/c/users/sagre/_bazel_sagre/bk62lldp/execroot/__main__/_coverage/my_test/test.exe/test/gcov': No such file or directory
```

Unfortunately we have to prioritize other work over coverage right now :(

**Comment by Sagre** [comment]
I suspected such a response. Thanks for the clarification. Then I dont have to continue searching for a way to make it work.
