### ISSUE TITLE
Make rules_foreign_cc recommended 

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#9379]
Make sure all the requirements in https://bazel.build/recommended-rules.html are fulfilled and add them to https://docs.bazel.build/versions/master/rules.html

**Comment by laurentlb** [comment]
Closing this issue for now. Please reopen (or file a new issue) when the repository is ready for this.

e.g. "There must be at least two active maintainers."

**Comment by laurentlb** [comment]
@oquenchil just stepped up to help maintain rules_foreign_cc
