### ISSUE TITLE
8ec3866d9e5d28f6c09546269ec82731c45c28ad broke the build

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#938]
Culprit: 8ec3866d9e5d28f6c09546269ec82731c45c28ad

Found by bisection on the corresponding machine:
`git bisect run /home/ci
/workspace/Bazel/JAVA_VERSION/1.8/PLATFORM_NAME/ubuntu_15.10-x86_64/output/bazel --nomaster_bazelrc --bazelrc=/dev/
null build --strategy=Javac=worker --worker_quit_after_build --fetch --nostamp --javacopt='-source 1.8 -target 1.8'
 src:bazel`

```
8ec3866d9e5d28f6c09546269ec82731c45c28ad is the first bad commit
commit 8ec3866d9e5d28f6c09546269ec82731c45c28ad
Author: Julio Merino <jmmv@google.com>
Date:   Thu Feb 18 16:44:29 2016 +0000
    Split out Java proto compilation logic to a helper script.
    
    This is just for clarity and should be a no-op.  Maintaining long shell
    command lines embedded in genrules is not pretty.
    
    --
    MOS_MIGRATED_REVID=114967410
:040000 040000 035fdc289705b18112afb60382d189f900773e13 1a73986141368bb882ba48d098429abf4ca4b56f M      tools
bisect run success
```

See http://ci.bazel.io/job/Bazel/371/JAVA_VERSION=1.8,PLATFORM_NAME=ubuntu_15.10-x86_64/console

(this is breaking when doing the determinism test)

**Comment by damienmg** [comment]
I should have assigned it to @jmmv but he is not yet member of the Bazel org (send an invitation).

**Comment by jmmv** [comment]
Oops. Sorry for the breakage.

Is there a way I can test this change in the same environment as Jenkins? I think I know what's wrong, but would like to be able to confirm it...

**Comment by damienmg** [comment]
The simplest repro is here (working on my machine):
```
./compile.sh
./output/bazel --nomaster_bazelrc --bazelrc=/dev/ null build --strategy=Javac=worker --worker_quit_after_build --fetch --nostamp --javacopt='-source 1.8 -target 1.8' src:bazel
```

If you want to run the complete test suite you can do: `./compile.sh all` (some test will timeout on your machine)

**Comment by jmmv** [comment]
FTR, the actual error message is:

```
ERROR: /home/ci/workspace/Bazel/JAVA_VERSION/1.8/PLATFORM_NAME/linux-x86_64/src/main/protobuf/BUILD:23:2: error executing shell command: 'JAR='external/local_jdk/bin/jar' OUTPUT='bazel-out/local_linux-fastbuild/bin/src/main/protobuf/libpackage_manifest_proto_srcjar.srcjar' PROTO_COMPILER='external/bazel_tools/third_party/protobuf/pro...' failed: namespace-sandbox failed: error executing command /home/ci/.cache/bazel/_bazel_ci/5f3cd5a16c8c04003810da50910b348c/linux-x86_64/_bin/namespace-sandbox ... (remaining 5 argument(s) skipped).
external/local_jdk/bin/jar: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory
gensrcjar: jar failed
```

I'm wondering if the `@bazel_tools//tools/jdk:jdk` dependency I took out is the cause behind this issue, which would mean that `@bazel_tools//tools/jdk:jar` itself may have missing dependencies.

But I cannot reproduce this on my machine with the instructions you provided in the last update. What JDK are you using and what Ubuntu version?

**Comment by jmmv** [comment]
Ah, great. I set up an Ubuntu 15.10 VM and could reproduce the problem and got the exact same error.

**Comment by jmmv** [comment]
So the problem is that my change removed the apparently-unnecessary dependency on `@bazel_tools//tools/jdk:jdk` as hinted above, and this is currently required for `jar` to work in some cases. This in turn means that we have a missing dependency somewhere, but I'm not going to track that down in this bug.

**Comment by damienmg** [comment]
There is no missing dependency sosmewhere. The thing is jar has to be a
single file but it requires the rest of jdk libraries. We could probably
create a runfiles tree using a custom skylark rules but that's a bit
overkill.

**Comment by jmmv** [comment]
Why does `jar` have to be a single file?

The fact that the `jdk` requirement leaks through the user of `jar` does not seem great.

**Comment by damienmg** [comment]
Because it has to be an executable and an executable file group must be
uniq.

We could stop using jar also and use zipper or singlejar instead.

**Comment by jmmv** [comment]
Not if you use `ctx.executable` as you recommended doing elsewhere? That works even when the output is not a single file.

**Comment by damienmg** [comment]
No when you provide files in a filegroup, the only way to provide it to an
executable input is that the filegroup contains only one file: the
executable. If not, you have to wrap the executable with a runfileprovider.
