### ISSUE TITLE
Failure when cquery on rules if targets from a different WORKSPACE are excluded 

### ISSUE THREAD

**Issue by lisaonduty** [bazelbuild/bazel#9381]
### Description of the problem:

When I query for all cc_.* rules in a target it works fine to use the keyword `except` to exclude all targets from certain packages located in both the current WORKSPACE  and in another WORKSPACE.
Doing the same with cquery fails. For cquery it's only possible to except targets in current WORKSPACE.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I modified the Bazel C++-tutorial to reproduce this in a simpler example than our own code:

I copied the stage3 directory to a new one called stage4.
In stage4 I modified some of the directory name and src files.

So stage3 still looks like the same:

```shell
.../examples/cpp-tutorial/stage3 -> 
README.md
WORKSPACE
lib
main

.../examples/cpp-tutorial/stage3/lib -> 
BUILD
hello-time.cc
hello-time.h
```

But stage4 is a bit different:

```shell
.../examples/cpp-tutorial/stage4 -> 
README.md
WORKSPACE
lib2
main

.../cpp-tutorial/stage4/lib2 -> 
BUILD
hello-time2.cc
hello-time2.h
```

I also changed the name of the `print_localtime()` function in `lib2` to `print_localtime2()`.

The `.../cpp-tutorial/stage4/main/hello-world.cc` was modified to  call both: `print_localtime()` (from stage3) and `print_localtime2()` (from stage4).

And of course I made the needed updates in impacted BUILD and WORKSPACE files to support the above updates.

When I query and cquery hello-world without `except` it works fine.

```shell
bazel query 'kind("cc_.* rule", deps(//main:hello-world))'
bazel cquery 'kind("cc_.* rule", deps(//main:hello-world))'
```

When I query and cquery hello-world except from lib2-package in the current WORKSPACE it works fine:

```shell
bazel query 'kind("cc_.* rule", deps(//main:hello-world)  except //lib2/...)'
bazel cquery 'kind("cc_.* rule", deps(//main:hello-world)  except //lib2/...)'
```

Nothing from `lib2` are in the output.

When I query hello-world except from lib2-package in the current WORKSPACE and lib-package in stage3 WORKSPACE it works fine:

```shell
bazel query 'kind("cc_.* rule", deps(//main:hello-world) except @stage3//lib/... except //lib2/...)'
```

Nothing from `lib2` or `lib` (in stage3) are in the output.

BUT when I cquery hello-world except from lib2-package in the current WORKSPACE and lib-package in stage3 WORKSPACE it fails:

```shell
bazel cquery 'kind("cc_.* rule", deps(//main:hello-world) except @stage3//lib/... except //lib2/...)'

INFO: Invocation ID: 8b41e282-e2ec-4507-b2ed-d027d6b10b01
INFO: Analyzed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 3 targets...
ERROR: Error doing post analysis query: Evaluation of subquery "@stage3//lib/..." failed (did you want to use --keep_going?): no targets found beneath 'lib'
INFO: Elapsed time: 0.074s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

###  What operating system are you running Bazel on?
Linux

###  What's the output of bazel info release?
0.25.0

###  Have you found anything relevant by searching the web?
No

**Comment by lisaonduty** [comment]
We now have Bazel version 2.2.0 and the problem is still seen.

**Comment by lisaonduty** [comment]
Investigating this even further it seems like cquery can't handle the WORKSPACE naming.
OK:
bazel cquery 'kind("cc_.* rule", deps(//main:hello-world))'
Not OK:
bazel cquery 'kind("cc_.* rule", deps(@stage4//main:hello-world))'

The same goes for all commands above. It isn't just exclude it's a problem for cquery to handle the WORKSPACE-naming.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
