### ISSUE TITLE
Targets and packages can't be excluded with except for query and cquery deps

### ISSUE THREAD

**Issue by lisaonduty** [bazelbuild/bazel#9382]
### Description of the problem / feature request:

According to the example [What packages does the foo tree depend on, excluding foo/contrib?](https://docs.bazel.build/versions/master/query-how-to.html#What_packages_does_the_foo_) it's possible to exclude output for targets in a package. The same must be equivalent for target output: without the `--output package` option.

When I have used this on our code both with query and cquery the `except` keyword don't have any effect.
I then tried on Bazel C++ tutorial and it doesn't work on that code either.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In Bazel C++ tutorial stage3 directory:
These works OK:

```shell
bazel query 'deps(//main:hello-world)'

bazel cquery 'deps(//main:hello-world)'

bazel query 'deps(//main:hello-world)' --output package
```

But when trying to exclude some output targets/packages they will not be excluded from the output:

```shell
bazel query 'deps(//main:hello-world except //lib/...)' 

bazel cquery 'deps(//main:hello-world except //lib/...)' 

bazel query 'deps(//main:hello-world except lib/...)' --output package
```

Here are examples of the outputs showing that targets in `//lib` are still in the answers:

```shell
.../examples/cpp-tutorial/stage3 -> bazel query 'deps(//main:hello-world except lib/...)' --output package
@bazel_tools//src/conditions
@bazel_tools//third_party/def_parser
@bazel_tools//tools/cpp
@bazel_tools//tools/def_parser
@local_config_cc//
external
lib
main
Loading: 0 packages loaded


.../examples/cpp-tutorial/stage3 -> bazel query 'deps(//main:hello-world except lib/...)' 
//main:hello-world
//main:hello-world.cc
//main:hello-greet
//main:hello-greet.h
//main:hello-greet.cc
//lib:hello-time
@bazel_tools//tools/def_parser:def_parser
@bazel_tools//tools/def_parser:no_op.bat
@bazel_tools//tools/def_parser:def_parser_windows
@bazel_tools//tools/def_parser:def_parser.exe
@bazel_tools//third_party/def_parser:def_parser
@bazel_tools//tools/cpp:malloc
@bazel_tools//third_party/def_parser:def_parser_main.cc
@bazel_tools//third_party/def_parser:def_parser_lib
@bazel_tools//third_party/def_parser:def_parser.h
@bazel_tools//third_party/def_parser:def_parser.cc
@bazel_tools//src/conditions:remote
@bazel_tools//src/conditions:host_windows
@bazel_tools//tools/cpp:toolchain
@bazel_tools//tools/cpp:grep-includes
@bazel_tools//tools/cpp:grep-includes.sh
//lib:hello-time.h
//lib:hello-time.cc
//external:cc_toolchain
@local_config_cc//:toolchain
@local_config_cc//:cc-compiler-k8
@local_config_cc//:local
@local_config_cc//:compiler_deps
@local_config_cc//:cc-compiler-armeabi-v7a
@local_config_cc//:stub_armeabi-v7a
@local_config_cc//:empty
@bazel_tools//tools/cpp:link_dynamic_library
@bazel_tools//tools/cpp:link_dynamic_library.sh
@bazel_tools//tools/cpp:interface_library_builder
@bazel_tools//tools/cpp:build_interface_so
Loading: 0 packages loaded
```

###  What operating system are you running Bazel on?
Linux

###  What's the output of bazel info release?
0.25.0

###  Have you found anything relevant by searching the web?
No

**Comment by ulfjack** [comment]
What about 'deps(//main:hello-world) except lib/...'?

**Comment by FrancescoScappatura** [comment]
Any news about this? I have the same problem

**Comment by lisaonduty** [comment]
We use Bazel version 2.2.0 now but the fault is still there.
It will not matter if the end of parenthesis is like this:
'deps(//main:hello-world) except lib/...'
OR
'deps(//main:hello-world except lib/...)'

**Comment by katre** [comment]
There are two problems here.

First, operator precedence.  The query `deps(//main:hello-world except //lib/...)` first evaluates `//main:hello-world except //lib/...`, which is, obviously, `//main:hello-world`. Then it evaluates `deps(//main:hello-world)`, and returns all of the deps, including anything under `//lib/...`.

The second problem is trickier, and involves the [exact meaning of the `...` wildcard](https://docs.bazel.build/versions/4.0.0/query.html#target-patterns). Specifically, when you evaluate `//lib/...`, that actually refers to "a set containing all rules in every package recursively beneath the [lib] directory". That very specifically does not include _files_, and is probably what you see when you query `deps(//main:hello-world) except //lib/...`.

The correct invocation is `query(//main:hello-world) except //lib/...:*` (the `:` qualifier selects all rules and files).

Sorry it took so long to answer this, feel free to reach out to the mailing lists with any further questions.
