### ISSUE TITLE
getting bad gold linker value

### ISSUE THREAD

**Issue by deryck1031** [bazelbuild/bazel#9392]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

building bazel from source for the first time and getting below error:
            gcc: error: unrecognized command line option '-fuse-ld=--enable-gold=yes'

the issue is unix_cc_configure.bzl where it is trying to determine whether '-fuse-ld=gold' is set. It is going through each line to find first line that contains the word 'gold'. Unfortunately, it found below line and return flag as '--enable-gold=yes':
x86-64.rhel.6 --enable-gold=yes --enable-tls --enable-rpath --enable-shared --enable-languages=c,c++,objc,fortran
### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> redhat 6

### What's the output of `bazel info release`?

> 

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by boegel** [comment]
I saw the same issue, was able to dance around it with this patch:

```diff
--- tools/cpp/unix_cc_configure.bzl.orig        2019-09-26 20:39:13.350751339 +0200
+++ tools/cpp/unix_cc_configure.bzl     2019-09-26 20:39:44.033325970 +0200
@@ -200,6 +200,8 @@
         for flag in line.split(" "):
             if flag.find("gold") == -1:
                 continue
+            if flag.find("enable-gold") > -1 or flag.find("with-plugin-ld") > -1:
+                continue

             # flag is '-fuse-ld=gold' for GCC or "/usr/lib/ld.gold" for Clang
             # strip space, single quote, and double quotes
```

**Comment by Flamefire** [comment]
Just ran into the same issue. This makes Bazel 0.29.1 completely unusable on "normal" systems. The above mentioned patch works for us

**Comment by hlopko** [comment]
I'm uploading this fix in https://github.com/bazelbuild/rules_cc/pull/48 to rules_cc, and together with https://github.com/bazelbuild/rules_cc/pull/45 you should be able to use rules_cc's version of cc_configure (by putting rules_cc and a call to rules_cc_toolchains() into your WORKSPACE file). And that should make it work for you without having to patch Bazel.

I'm also working on removing cc_configure from Bazel, so eventually rules_cc_toolchains will be the default way of getting C++ toolchain.

**Comment by Flamefire** [comment]
> And that should make it work for you without having to patch Bazel.

Can you elaborate on this? The offending code is still on master: https://github.com/bazelbuild/bazel/blob/master/tools/cpp/unix_cc_configure.bzl#L200-L210

Is that no longer used? If it is, why not patch that directly so at least the next release contains the patch?

**Comment by hlopko** [comment]
I fixed the issue in the rules_cc repo so you can use that instead of the snapshot of it that is distributed with Bazel (so you don't have to wait for Bazel release).

And TBH, I just forgot to fix it in Bazel. Will do that this week.
