### ISSUE TITLE
Bazel boostrap build issues on RHEL6

### ISSUE THREAD

**Issue by csiefer2** [bazelbuild/bazel#9393]
### Description of the problem / feature request:

Bazel 0.29.1 will not build on RHEL6

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

export EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" 
export JAVA_HOME=/usr
./compile.sh

### What operating system are you running Bazel on?

RHEL6

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A.  Using the 0.29.1-dist zip file

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
.WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
DEBUG: /tmp/bazel_RhhR5NJp/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:9: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '0.27.1'
DEBUG: /tmp/bazel_RhhR5NJp/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /tmp/bazel_RhhR5NJp/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:9: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '0.27.1'
DEBUG: /tmp/bazel_RhhR5NJp/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:9: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
DEBUG: /tmp/bazel_RhhR5NJp/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:49:5: 
Current Bazel is not a release version, cannot check for compatibility.
DEBUG: /tmp/bazel_RhhR5NJp/out/external/build_bazel_rules_nodejs/internal/common/check_bazel_version.bzl:51:5: Make sure that you are running at least Bazel 0.17.1.
INFO: Call stack for the definition of repository 'remote_java_tools_linux' which is a http_archive (rule definition at /tmp/bazel_RhhR5NJp/out/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /DEFAULT.WORKSPACE.SUFFIX:240:1
ERROR: /tmp/bazel_RhhR5NJp/out/external/bazel_tools/tools/jdk/BUILD:308:1: no such package '@local_jdk//': error globbing [lib/**] - [lib/missioncontrol/**, lib/visualvm/**]: /tmp/bazel_RhhR5NJp/out/external/local_jdk/lib/jvm-private/java-1.7.0-oracle.x86_64 (Not a directory) and referenced by '@bazel_tools//tools/jdk:jdk'
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis failed
INFO: Elapsed time: 15.238s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (208 packages loaded, 3361 targets\
 configured)

ERROR: Could not build Bazel

**Comment by csiefer2** [comment]
If it matters, I've got gcc-4.9.3 as my compiler, rather than the RHEL6 default 4.4.7.

**Comment by philwo** [comment]
RHEL6 is not supported, sorry.
