### ISSUE TITLE
Compiling from scratch on OpenBSD [duplicate of #10250]

### ISSUE THREAD

**Issue by barbosaaob** [bazelbuild/bazel#9397]
### Description of the problem / feature request:

Can't compile from scratch on OpenBSD 6.6-current

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Following bazel install instructions on how to build from scratch (since there isn't a package nor port for OpenBSD) I got the following error:
in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'unknown'

### What operating system are you running Bazel on?

OpenBSD 6.6-current

###  Have you found anything relevant by searching the web?
Tried to set cpu appending --cpu and/or --host_cpu with options x86_64, amd64, x64 and even freebsd (I'm on OpenBSD) to EXTRA_BAZEL_ARGS and I get the same error message with the cpu I asked for replacing the 'unknown' cpu.

Using --cpu and --host_cpu k8 could work as I'm using OpenBSD on a Core-i5, but I end up with:
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=@bazel_tools//third_party/ijar:zipper BuildConfigurationValue.Key[75f1bdd8d1b40d435bd1f5a32836a34f] true, actionIndex=8}' (requested by nodes 'File:[[<execution_root>]bazel-out/host/bin]external/bazel_tools/third_party/ijar/zipper.runfiles/MANIFEST')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:527)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:387)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unidentified operating system

Also tried to use --extra_toolchains with "cc-compiler-freebsd" and "cc-toolchain-freebsd" with error:
While resolving toolchains for target //src/main/cpp:client: invalid registered toolchain '@local_config_cc//:cc-toolchain-freebsd': no such target '@local_config_cc//:cc-toolchain-freebsd': target 'cc-toolchain-freebsd' not declared in package '' defined by /tmp/bazel_IkzAD8R2/out/external/local_config_cc/BUILD

What else I tried:
* apply patches from FreeBSD ports
* chance code on src/main/java/com/google/devtools/build/lib/util/{CPU,OS}.java to set the cpu and/or OS
* investigating src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchainSuite.java I get:
selectedToolchain: null
ruleContext.getPrerequisiteMap("toolchains").values(): [ConfiguredTarget(@local_config_cc//:cc-compiler-k8, 9917c584d6304373425f1b1b4007e932), ConfiguredTarget(@local_config_cc//:cc-compiler-k8, 9917c584d6304373425f1b1b4007e932), ConfiguredTarget(@local_config_cc//:cc-compiler-armeabi-v7a, 9917c584d6304373425f1b1b4007e932), ConfiguredTarget(@local_config_cc//:cc-compiler-armeabi-v7a, 9917c584d6304373425f1b1b4007e932)]

I tried both versions 0.29.0 and 0.26.1, because of the _TF_MAX_BAZEL_VERSION variable.

**Comment by georgalis** [comment]
I have the same issue with: **NetBSD 8.1**, on a VirtualBoxVM, on MacBookPro hardware, with cpp (nb3 20180905) 5.5.0. My Bazel 29.1 build is failing with cc_toolchain_suite 'unknown' cpu detected.

I was unable to locate the specific Bazel/cc-tools probe for the cpu type (my /proc/cpuinfo and uname data are below). I'm guessing this issue is related to an untested dependency on GNU sed (GNU tools are available as packages but not part of base OS on BSD systems). https://groups.google.com/forum/#!topic/bazel-discuss/S8DrmgEvVyk

I would be happy to verify/confirm if a developer would point me to the relevant cpu probe.

Specifying a GNU toolchain may be the most expedient solution (though it is probably not _required_).

May I have some direction for specifying a locally installed toolchain to confirm a GNU dependancy, and hopefully get through my build?

Thanks,
-George


```
 ulimit -m unlimited && bash
 root@:/usr/local/src/bazel-0.29.1-dist ulimit -m unlimited
 root@:/usr/local/src/bazel-0.29.1-dist env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" JAVA_HOME="/usr/pkg/java/openjdk8" bash ./compile.sh
...
ERROR: /tmp/bazel_BWcupIF1/out/external/local_config_cc/BUILD:47:1: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'unknown'
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed; build aborted
INFO: Elapsed time: 14.755s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (22 packages loaded, 69 targets co\
nfigured)

ERROR: Could not build Bazel
 root@:/usr/local/src/bazel-0.29.1-dist uname -a
NetBSD nb81-tf 8.1 NetBSD 8.1 (GENERIC) #0: Fri May 31 08:43:59 UTC 2019  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC amd64
 root@:/usr/local/src/bazel-0.29.1-dist cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 94
model name      : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
stepping        : 3
cpu MHz         : 2592.19
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm pni pclmulqdq monitor ssse3 cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx rdrand lahf_lm abm 3dnowprefetch fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d
clflush size    : 64
```

**Comment by aldersondrive** [comment]
FYI, an OpenBSD port is underway in https://github.com/bazelbuild/bazel/issues/10250.

**Comment by aldersondrive** [comment]
This can be closed now, I think. Building Bazel on OpenBSD works now, per https://github.com/bazelbuild/bazel/issues/10250.

**Comment by barbosaaob** [comment]
> 
> 
> This can be closed now, I think. Building Bazel on OpenBSD works now, per #10250.

[Relase 2.1.1](https://github.com/bazelbuild/bazel/releases/tag/2.1.1) does not include this commit yet, right?  
I can't compile using the cloned code from master because of `ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact`. All I could find about this error is people telling to download the dist file from release page.

How can I test the changes and see if it works for me? Thank you for your work on making this happen.

**Comment by aldersondrive** [comment]
Building Bazel directly from the contents of the git repository does not work. It is indeed necessary to build from a 'dist' archive instead. Details are in the ["Compiling Bazel from source" documentation](https://docs.bazel.build/versions/master/install-compile-source.html#bootstrap-bazel).

Version 2.1.1 was released just a few days ago, so very likely it does include all of the relevant commits. (If for some reason it does not, you can generate a fresh 'dist' archive from the git repository via something like `bazel build :bazel-distfile` in the repository's root directory on a platform that does have a `bazel` binary available, then copy the 'dist' archive to your OpenBSD system and build there.)

**Comment by philwo** [comment]
Is this still an issue?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
