### ISSUE TITLE
Win RBE Build: Failed to delete output files after incomplete download

### ISSUE THREAD

**Issue by jtattermusch** [bazelbuild/bazel#9399]
### Description of the problem / feature request:

Try to build grpc with Win RBE , I get this error:
https://source.cloud.google.com/results/invocations/6056fedc-3186-4c5e-829d-46dfe2eb974d/log

```
ERROR: C:/users/jtattermusch/github/grpc/test/core/end2end/BUILD:36:1: output 'test/core/end2end/ssl_test_data.if.lib' was not created
ERROR: C:/users/jtattermusch/github/grpc/test/core/end2end/BUILD:36:1: not all outputs were created or valid
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=//test/core/slice:b64_test BuildConfigurationValue.Key[090fca84e9d8ee83a043dcd8d12d294b] false, actionIndex=4}' (requested by nodes 'TargetCompletionKey{configuredTargetKey=//test/core/slice:b64_test BuildConfigurationValue.Key[090fca84e9d8ee83a043dcd8d12d294b] false, topLevelArtifactContext=com.google.devtools.build.lib.analysis.TopLevelArtifactContext@500abbf6, willTest=true}', 'ActionLookupData{actionLookupKey=//test/core/slice:b64_test BuildConfigurationValue.Key[090fca84e9d8ee83a043dcd8d12d294b] false, actionIndex=9}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: com.google.devtools.build.lib.actions.EnvironmentalExecException: Failed to delete output files after incomplete download: C:/users/jtattermusch/_bazel_jtattermusch/vnaz4mpr/execroot/com_github_grpc_grpc/bazel-out/x64_windows-fastbuild/bin/test/core/slice/b64_test.pdb.tmp (Permission denied)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

build grpc on win RBE:
`bazel --bazelrc=tools/remote_build/windows.bazelrc test //test/core/...`

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

bazel 0.29.1

**Comment by jtattermusch** [comment]
@buchgr  can you take a look?

CC @laszlocsomor

**Comment by laszlocsomor** [comment]
FYI @buchgr is out this week

**Comment by jtattermusch** [comment]
Sometimes I'm also getting
```
src/core/lib/gpr/time_precise.cc(34): warning C4067: unexpected tokens following preprocessor directive - expected a newline
[1,523 / 1,605] Compiling test/core/fling/server.cc; 2s remote ... (30 actions, 29 running)
ERROR: T:/src/github/grpc/test/core/gpr/BUILD:76:1: C++ compilation of rule '//test/core/gpr:mpscq_test' failed (Exit 34). Note: Remote connection/protocol failed with: execution failed java.io.IOException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: A docker image must be specified for this action.  See instructions at https://cloud.google.com/remote-build-execution/docs/set-up/remote-environment#add_a_toolchain
	at com.google.devtools.build.lib.remote.GrpcRemoteExecutor.executeRemotely(GrpcRemoteExecutor.java:177)
```
https://source.cloud.google.com/results/invocations/188fe8de-d2e5-411d-bf76-d692b7a5163d/log

**Comment by jtattermusch** [comment]
> FYI @buchgr is out this week

I would be good to have this fixed in bazel 1.0 release. Right now we cannot build / test using bazel on windows and I'd really expect that to work in 1.0 because AFAIK we are not doing anything that special in our build.

**Comment by laszlocsomor** [comment]
I don't think we can include a fix in Bazel 1.0. The release is already in process (@dslomov is the release manager), and there's no bugfix we could cherrypick.

**Comment by laszlocsomor** [comment]
We could fix it in a point release (Bazel 1.0.1 or 1.1.0) -- with Bazel 1.0.0 we start semantic versioning so Bazel 1.x will be backwards-compatible with 1.0

**Comment by jtattermusch** [comment]
@laszlocsomor  what's the ETA for bazel 1.0 release?

**Comment by laszlocsomor** [comment]
End of September, but @dslomov would know best.
Follow https://github.com/bazelbuild/bazel/issues/8573

**Comment by jtattermusch** [comment]
A bunch of other errors I'm experiencing with the windows RBE build (they seem to be somewhat random so I get different errors at different times.
https://source.cloud.google.com/results/invocations/71625e31-dcce-40d9-8b43-2ca1926298ed/log
https://source.cloud.google.com/results/invocations/fd09f8cf-edf3-4e50-82a1-137201a0df00/log
https://source.cloud.google.com/results/invocations/72598656-33bf-4a04-9ddf-dee1ba3293ec/log
https://source.cloud.google.com/results/invocations/fa405da1-60ed-4784-ae9e-a281907e4272/log

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
