### ISSUE TITLE
Missing section in documentation

### ISSUE THREAD

**Issue by boehnsins** [bazelbuild/bazel#9410]
There is a missing section in the documentation for workspace naming on `master`. The [page](https://docs.bazel.build/versions/master/be/functions.html) has a link to the respective section `workspace`, however, the section itself does not exist. 
Switching the branch of the documentation to `0.29.1` will show the section.

**Comment by gregestren** [comment]
This looks like https://github.com/bazelbuild/bazel/commit/b970b2488a55e476f8773a837698c77ecaf2d18e. Assigning to its author.

**Comment by gregestren** [comment]
Also proposed fix at https://github.com/bazelbuild/bazel/pull/9414.

**Comment by j3parker** [comment]
Opps, I should have checked the open issues. Thanks.
