### ISSUE TITLE
Default java toolchain changed to target java 8 and broke `toolchain_vanilla`

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#9415]
It seems, that 6ef6d879ab69225d54ecab3db847fb4eff33bbeb broke `toolchain_vanila`. Before this change there was a possibility to use newer Java versions and produce newer byte code as documented in Bazel source code https://github.com/bazelbuild/bazel/blob/master/tools/jdk/BUILD#L363-L382:

```python
# The 'vanilla' toolchain is an unsupported alternative to the default.
#
# It does not provider any of the following features:
#   * Error Prone
#   * Strict Java Deps
#   * Header Compilation
#   * Reduced Classpath Optimization
#
# It uses the version of javac from the `--host_javabase` instead of the
# embedded javac, which may not be source- or bug-compatible with the embedded
# javac.
#
# However it does allow using a wider range of `--host_javabase`s, including
# versions newer than the current embedded JDK.
default_java_toolchain(
    name = "toolchain_vanilla",
    forcibly_disable_header_compilation = True,
    javabuilder = [":vanillajavabuilder"],
    jvm_opts = [],
)
```

For example this used to work in Gerrit and produced byte code major version: 57 (Java 13), but after aforementioned commit produced byte code major version 52 (Java 8):

```
  $ bazel build --define=ABSOLUTE_JAVABASE=/use/local/bin/jdk-13   \
    --javabase=@bazel_tools//tools/jdk:absolute_javabase \
    --host_javabase=@bazel_tools//tools/jdk:absolute_javabase \
    --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla \
    --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla \
     java/com/google/gerrit/common:server
  
  $ javap -v -cp bazel-bin/java/com/google/gerrit/common/libserver.jar \
    com/google/gerrit/common/FileUtil | grep major
  major version: 52
```

If I revert 6ef6d879ab69225d54ecab3db847fb4eff33bbeb, or apply this [PR](https://github.com/bazelbuild/bazel/pull/9416) then it works as expected again:

```
$ bazel build --define=ABSOLUTE_JAVABASE=/use/local/bin/jdk-13  \
    --javabase=@bazel_tools//tools/jdk:absolute_javabase \
    --host_javabase=@bazel_tools//tools/jdk:absolute_javabase \
    --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla  \
    --java_toolchain=@bazel_tools//tools/jdk:toolchain_vanilla \
     java/com/google/gerrit/common:server
  
  $ javap -v -cp bazel-bin/java/com/google/gerrit/common/libserver.jar \
    com/google/gerrit/common/FileUtil | grep major
  major version: 57
```

Note, to make Bazel backwards compatible, and also produce byte code major version 52, even if built with Java 11 and newer java version as Host Java version, we can pass in Gerrit source and target language level to 8 in `error_prone_warnings_toolchain` definition instead:

```
default_java_toolchain(
    name = "error_prone_warnings_toolchain",
    bootclasspath = ["@bazel_tools//tools/jdk:platformclasspath.jar"],
    jvm_opts = JDK9_JVM_OPTS,
    source_version = "8",
    target_version = "8",
    package_configuration = [
        ":error_prone",
    ],
    visibility = ["//visibility:public"],
)
```

That way running `bazel build :release` without any options even on Java 11 would produce Java major byte code 52 (Java 8) as expected:

```
  $ java -version
  openjdk version "11.0.4" 2019-07-16

  $ bazel build java/com/google/gerrit/common:server

  $ javap -v -cp bazel-bin/java/com/google/gerrit/common/libserver.jar \
    com/google/gerrit/common/FileUtil | grep major
  major version: 52
```

**Update**: I forked `toolchain_vanilla` from `@bazel_tools//tools/jdk:toolchain_vanilla` to `@gerrit//tools:toolchain_vanilla` to unblock gerrit project for now: [1].

[1] https://gerrit-review.googlesource.com/c/gerrit/+/238380

//CC @iirina @cushon

**Comment by dslomov** [comment]
Since this breaks backwards compatibility, should I cherrypick 847df72 into 1.0? (#8573)

**Comment by iirina** [comment]
@dslomov Yes, please cherry pick  847df72 into 1.0.
