### ISSUE TITLE
`copts` are not passed to `masm` for win32 assembly files

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#9419]
### Description of the problem / feature request:

Bazel lets you provide `.asm` files as sources for a `cc_library`, which are assembled with MASM when building for Windows. This is used by [rules_boost](https://github.com/nelhage/rules_boost/blob/a1dd05e7e9178f8aad86e39f3a5b377902eae5b2/BUILD.boost#L101). However, `copts` aren't passed through, so it's impossible to set macros which are required by the source files. In this case, we need to set `/DBOOST_CONTEXT_EXPORT=`, but that is only passed to `cl.exe`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I only have access to Bazel on Windows via the Bazel CI, so I can't provide an easy repro - sorry! If you add `-s` to the build flags, you can see that the copts are only passed through to cl.exe, though.

### What operating system are you running Bazel on?

Bazel CI's Windows workers.

### What's the output of `bazel info release`?

0.29.1, more info: https://buildkite.com/bazel/rules-boost/builds/4

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

git@github.com:drigz/rules_boost.git
a1dd05e7e9178f8aad86e39f3a5b377902eae5b2
75be200210c46e09f7d2c3a68cb8e0f439f197c1

###  Have you found anything relevant by searching the web?

#8924 concerns options that should not be passed to the assembler.

**Comment by hlopko** [comment]
Can you rename the file to have the `.S` extension? That's assembly with c preprocessor for Bazel (https://source.bazel.build/bazel/+/8108d1ab27c819752dc08391e2e355acc714856c:src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java;l=86)

**Comment by drigz** [comment]
Thanks, that works! Maybe the docs could be updated to clarify that while `.asm` is allowed, it isn't preprocessed? Currently `.asm` isn't documented: https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.srcs

**Comment by mehrdadn** [comment]
Hi @hlopko, is there any chance Bazel could support this without requiring a rename? I just ran into this issue, and it took me quite a long time to track it down, as `.asm` is a standard file extension for assembly files on Windows, and it _appears_ as if it is supported just fine by Bazel. As Boost is an extremely popular external library it seems a bit unrealistic for everyone to have to manually carry patches for it just to work around a Bazel bug. It would be great if Bazel could just support `.asm` files natively. Thank you!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by mehrdadn** [comment]
This is not resolved, right? Perhaps closing at "Won't Fix" or such would be more accurate than "completed"?

**Comment by davidben** [comment]
> Can you rename the file to have the `.S` extension? That's assembly with c preprocessor for Bazel (https://source.bazel.build/bazel/+/8108d1ab27c819752dc08391e2e355acc714856c:src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java;l=86)

@hlopko I don't think this is right, or rather it is missing the point. MASM files indeed don't go through the C preprocessor, but MASM has its *own* notion of defines and its own macro system. See `/D` here:
https://learn.microsoft.com/en-us/cpp/assembler/masm/ml-and-ml64-command-line-reference?view=msvc-170

Whether `copts` per se should be passed (see #8924), there's an obvious need to be able to pass *some* kind of parameters to the assemble, whether it's `copts` or `asmopts` or something else.
