### ISSUE TITLE
All tests fail with `--spawn_strategy=remote`

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#942]
Given `build --hazelcast_node=127.0.0.1:5701 --spawn_strategy=remote` in the `.bazelrc` config, all tests run with `bazel test` will report failures (even though the log suggests they succeeded).  On the other hand, `bazel build //...` completes successfully with the same options.  Adding `test --spawn_strategy=sandboxed` to `.bazelrc` will allow the tests to succeed again.

**Comment by ulfjack** [comment]
Let me mark this as a dupe of #1413.
