### ISSUE TITLE
Debug API for rule authors to instrument and debug their rules (especially repository rules)

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#9425]
There are some profiling tools to help analyze performance of rules, but none of them apply to repository_rule().  Additionally, there are no ways of doing some sorts of profiling/tracing manually, such as with simple time calcualations and logging. 

I propose a starlark API for debugging that is only enabled if given the --debug flag, (or some --experimental_debug_api flag), loudly advertises its side effects, and which no-ops when not running.

At the very least, the high-level requirement is to be able to log time taken, and possibly order of operations.  This could involve a more generalized debug.log(message, args) style thing, which can take function pointers for deferred invocation, plus a debug.timestamp() (returns an int for milliseconds, returning 0 in the non-debug case). 

An alternative would be to expand the profiling to return real profiling information during repository rule execution pre-analysis phase, and then allow for a trace.start(name) trace.end(name) to allow for finer grained trace information to be passed in, which no-ops if a flag isn't flipped.

It could even be a function of ctx, similar to report_progress, but with better notions of starting/ending a task. 

the basic problem is the lack of insight into where work is being done, finding waste, etc. There are several ways to surface this. But I'm working blind in the current situation.

**Comment by laurentlb** [comment]
cc @alandonovan @meisterT

**Comment by alandonovan** [comment]
Tobi, doesn't the "JSON" event trace record events from the WORKSPACE fetch phase? I would expect the kind of large-granularity I/O operations it does to show up nicely in that kind of trace.

**Comment by meisterT** [comment]
Fetching should be covered, but I have to look at repository rules in general. Can you please point me to the Java code where we execute the implementation function?

**Comment by alandonovan** [comment]
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/skylark/SkylarkRepositoryFunction.java#L202

**Comment by meisterT** [comment]
Bazel at HEAD does now have basic profiling for StarlarkRepositoryFunction; I've also done some more changes to Starlark profiling which should help. For Bazel itself this is how it looks:
![repofn](https://user-images.githubusercontent.com/418721/79457946-5b126700-7ff1-11ea-9ccd-6aabb39b6cae.png)

@cgruber can you please test how much that helps you?

**Comment by larsrc-google** [comment]
Given the lack of response over two years, I'll say this is obsolete. Please reopen if that's not the case.
