### ISSUE TITLE
Unable to set cpp debug option "g2" to host configuration, the copt is always "g0".

### ISSUE THREAD

**Issue by bbxfnet** [bazelbuild/bazel#9428]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Unable to set cpp debug option "g2" to host configuration, the copt is always "g0".

### Feature requests: what underlying problem are you trying to solve with this feature?

> Build Tensorflow with debug version.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> bazel build -c dbg --copt="-g2" --copt -g2 --host_copt -g2 --host_cxxopt -g2 --strip=never --define=tf_api_version=2 //tensorflow/tools/pip_package:build_pip_package --verbose_failures

### What operating system are you running Bazel on?

> Ubuntu 1904: 31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### What's the output of `bazel info release`?

> 0.26.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> The CC build command line is: /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/any.d '-frandom-seed=bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/any.o' -iquote external/com_google_protobuf -iquote bazel-out/host/bin/external/com_google_protobuf -iquote external/zlib_archive -iquote bazel-out/host/bin/external/zlib_archive -isystem external/com_google_protobuf/src -isystem bazel-out/host/bin/external/com_google_protobuf/src -isystem external/zlib_archive -isystem bazel-out/host/bin/external/zlib_archive -g0 -g2 -g0 '-std=c++14' -g2 -DHAVE_PTHREAD -DHAVE_ZLIB -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-write-strings -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/any.cc -o bazel-out/host/bin/external/com_google_protobuf/_objs/protobuf/any.o
> Problem code root cause code: com.google.devtools.build.lib.rules.cpp.CppOptions.getHost()
Per my above command, if I don't add "--host_cxxopt -g2 ", the CC build command will be "-g0 -g2 -g0 '-std=c++14' " but not "-g0 -g2 -g0 '-std=c++14' -g2", so the valid debug option is "-g0" at last. So for below code, I think we should replace default debug option(-g0) with user's debug option(-g2) but not append it.
    if (OS.getCurrent() != OS.WINDOWS) {
      coptListBuilder.add("-g0");
      cxxoptListBuilder.add("-g0");
    }
    host.coptList = coptListBuilder.addAll(hostCoptList).build();
    host.cxxoptList = cxxoptListBuilder.addAll(hostCxxoptList).build();
Change to:
    if (OS.getCurrent() != OS.WINDOWS) {
      if(hostCoptList.stream().noneMatch(arg->arg.contains("-g"))) {
        coptListBuilder.add("-g0");
      }
      if(hostCxxoptList.stream().noneMatch(arg->arg.contains("-g"))) {
        cxxoptListBuilder.add("-g0");
      }
    }
    host.coptList = coptListBuilder.addAll(hostCoptList).build();
    host.cxxoptList = cxxoptListBuilder.addAll(hostCxxoptList).build();
> If the files are large, upload as attachment or provide link.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
