### ISSUE TITLE
`repo_mapping` Not valid for host bin

### ISSUE THREAD

**Issue by dMokaMoka** [bazelbuild/bazel#9431]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I worked with protobuf 3.6.1,
And use tensorflow 1.12.0 as my external dependency, So I do protobuf's relational mapping using repo_mapping, like:
```
local_repository(
    name="org_tensorflow",
    path="../tensorflow_v1.12.0",
    repo_mapping={
        "@protobuf_archive" : "@protobuf_archive_3.6.1",
        "@com_google_protobuf" : "@com_google_protobuf_3.6.1",
        "@com_google_protobuf_cc" : "@com_google_protobuf_cc_3.6.1",
    },
)
```
This works fine when I compile the simple taget, but it fails when I compile the pip_package:
```
#error This file was generated by a newer version of protoc which is... [for host]
```
In the bazel-out/host/bin/external directory, I get the following two folders
```
protobuf_archive
protobuf_archive_3.6.1
```
protobuf_archive/protoc --version is 3.6.0
protobuf_archive_3.6.1/protoc --version is 3.6.1

So the error above occurs when processing the protobuf_archive_3.6.1/protoc output using protobuf_archive/protoc

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

x86 ubuntu16.04

### What's the output of `bazel info release`?

release 0.17.2- (@non-git)

**Comment by philwo** [comment]
I'll close this as it's very probably obsolete by now (a lot of things have changed since Bazel 0.17.2). Please reopen if it's still an issue.
