### ISSUE TITLE
For comprehensions should create a scope

### ISSUE THREAD

**Issue by stepancheg** [bazelbuild/bazel#9438]
According to [Starlark spec](https://github.com/bazelbuild/starlark/blob/master/spec.md#comprehensions), this code should print `1`:

```
x = 1
_ = [x for x in [2]]            # new variable x is local to the comprehension
print(x)                        # 1
```

However, when running latest master, it results in error:

```
$ bazel run //src/main/java/com/google/devtools/starlark:Starlark -- `pwd`/compr.sky
...
Traceback (most recent call last):
	File "", line 4
		print(x)
	File "", line 4, in print
		x
global variable 'x' is referenced before assignment.
```

Run from bazel master, revision f371448bf047b294557f6fc1ecec04dcefc62f93, Sep 25 2019.

**Comment by laurentlb** [comment]
This has been fixed. Thanks a lot for your contribution!

(closing the bug; please comment if there was anything else to do)
