### ISSUE TITLE
Exported symbols from cc_binary shared lib change from 0.29.1 to 1.0.0rc3

### ISSUE THREAD

**Issue by wesleyw72** [bazelbuild/bazel#9439]
I am building a shared library using `cc_binary` which depends on some `cc_library` targets (which in turn depend on other `cc_library` targets). When building this target in 0.29.1 the shared library contains the symbols from a `cc_library` it depends on (of the form cc_binary -> cc_lib -> cc_lib -> cc_lib with symbols). I upgraded to 1.0.0rc3 and rebuilt the same target, and the symbol is now missing from the shared library. 

What's changed to cause this?

OS:

MacOS Mojave 10.14.6

**Comment by wesleyw72** [comment]
Can confirm this on Ubuntu 18.04 also

**Comment by hlopko** [comment]
And I bet it's https://github.com/bazelbuild/bazel/issues/7362, can you try unflipping it and see if it helps?

**Comment by wesleyw72** [comment]
I think that's it, thank you!
