### ISSUE TITLE
Missing data_runfiles then use cc_import output

### ISSUE THREAD

**Issue by maximyurchuk** [bazelbuild/bazel#9447]
### Description of the problem / feature request:
`cc_import` doesn't expose `data_runfiles` while importing sharing library. So, I can't get needed runtime dependencies for my custom packaging rules.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See [here](https://github.com/maximyurchuk/bazel-issues/tree/master/use_runfiles_from_cc_import). This example shows, that cc_library have `data_runfiles` with shared library, but cc_import doesn't. 

### What operating system are you running Bazel on?

Windows 10. But originally problem appeared on osx (I just wrote and run repro case on Windows).

### What's the output of `bazel info release`?

c:\git\bazel-issues\use_runfiles_from_cc_import>bazel-latest info release
release 0.28.1

**Comment by maximyurchuk** [comment]
Moreover even explicit `data` parameter doesn't work:

```
cc_import(
	name = "import_library",
	shared_library = "1.dll",
	data = ["1.dll"],
) 
```

So, no idea how to workaround that situation.

**Comment by hlopko** [comment]
I actually don't know what is the difference between normal runfiles and data runfiles. Are shared libraries present in normal runfiles?

cc_library has the data runfiles set for the legacy reasons that nobody in the team remembers, and I never had the time and motivation to dig into that, unfortunately.

**Comment by maximyurchuk** [comment]
@hlopko
> Are shared libraries present in normal runfiles?

I have updated [example](https://github.com/maximyurchuk/bazel-issues/tree/master/use_runfiles_from_cc_import), there are no `runfiles` field for cc_import and cc_library. Seems that this is contradiction with [docs](https://docs.bazel.build/versions/1.0.0/skylark/lib/DefaultInfo.html):
```
runfiles

set of files acting as both the data_runfiles and default_runfiles.
```

> cc_library has the data runfiles set for the legacy reasons

Maybe, its needed because `cc_binary` must be able collect all shared library from `cc_library` dependencies (which can be transitive) while creating binary with `linkstatic = False`. All collected shared libraries are exposed as runfiles for cc_binary. But its just my thoughts, i'm not checked this.

**Comment by oquenchil** [comment]
This was partially rolled back for the native implementation of cc_import:
https://cs.opensource.google/bazel/bazel/+/55436a7e53380466d515836e61cdfee4a4a9dfb5

**Comment by ozio85** [comment]
Note that you can find the dynamic libraries in the OutputGroupInfo:

```
for dep in ctx.attr.deps:
    dep[OutputGroupInfo].dynamic_library
```

**Comment by mellery451** [comment]
@ozio85 I get an error when I try to access this dynamic_library field:

      Error: 'OutputGroupInfo' value has no field or method 'dynamic_library'

Could it be another provider instead perhaps?
