### ISSUE TITLE
Not able to build bazel from source for 1.0.0 rc3 on rhel7

### ISSUE THREAD

**Issue by deryck1031** [bazelbuild/bazel#9449]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

bazel failed to build with below error msg:
             zip I/O error: Permission denied

error occurred when executing below cmd:
          zip -qd bazel-out/k8-fastbuild/bin/third_party/netty_tcnative/netty-tcnative-filtered.jar *.jnilib *.dll'

That file is generated by below rule, but the file has no write permission:

genrule(
    name = "filter_netty_dynamic_libs",
    srcs = ["netty_tcnative/netty-tcnative-boringssl-static-2.0.24.Final.jar"],
    outs = ["netty_tcnative/netty-tcnative-filtered.jar"],
    cmd = "cp $< $@ && zip -qd $@ " + UNNECESSARY_DYNAMIC_LIBRARIES,
)

Once I added 'chmod +w $@', build finished successfully. 

### What's the output of `bazel info release`?

this is for bazel 1.0.0 rc3

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by philwo** [comment]
Sounds like a problem with your local environment and not a bug in Bazel.
