### ISSUE TITLE
FileType's constructor shows up in the "Globals" page of the documentation

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#945]
It's confusing to have `FileType`'s constructor listed at http://bazel.io/docs/skylark/lib/globals.html instead of http://bazel.io/docs/skylark/lib/FileType.html.

**Comment by davidzchen** [comment]
Similarly, Label's constructor is also listed on the Globals page rather than http://bazel.io/docs/skylark/lib/Label.html.
