### ISSUE TITLE
Call realpath on cxx_builtin_include_directories

### ISSUE THREAD

**Issue by llchan** [bazelbuild/bazel#9451]
### Description of the problem / feature request:

The `cxx_builtin_include_directories` list is not `realpath`ed, but the dependency declaration checks look for the `realpath`ed paths.  This leads to errors like
```
this rule is missing dependency declarations for the following files included by 'src/main.cpp':
  '/realpath/lib/gcc/x86_64-pc-linux-gnu/x.x.x/include/stddef.h'
```
, when in fact that path is present in the toolchain configuration, just with the original path.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Have a gcc at `/realpath`
2. Create a symlink to it at `/path`
3. Refer to `/path/include/...` in the `cxx_builtin_include_directories` passed into `create_cc_toolchain_config_info`
4. Use this toolchain in a cc_binary and build

### What operating system are you running Bazel on?

RHEL

### What's the output of `bazel info release`?
```
release 0.29.1
```

**Comment by benjaminp** [comment]
Generally, you instead want to convince your compiler to deal in relative paths. Absolute paths are bad for reproducible builds. `-fno-canonical-system-headers` and `-no-canonical-prefixes` are good GCC options.

**Comment by llchan** [comment]
Already had `-fno-canonical-system-headers` but looks like `-no-canonical-prefixes` did the trick!

Is this a requirement? i.e. we wont support dependency resolution through symlinks?  Imho it would be more user-friendly to allow it without an implicit compiler flag requirement.

If this is going to be a wont-fix, could we make this more obvious?  Even just a hint to the user to try those flags would be helpful.

**Comment by honicky** [comment]
This is also problematic for those of us who are stuck with non-standard compilers, like those of us who work on embedded systems and other environments where we don't have control over the compiler.  If Bazel can't support this, I will need to hack something together to work.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by DimanNe** [comment]
@sgowroji It seems that due to this issue, compilation of tensorflow with clang 14 fails:

```
INFO: Found 1 target...
ERROR: /home/dimanne/.cache/bazel/_bazel_dimanne/33c66632a93eff405a3246128a23107c/external/zlib/BUILD.bazel:5:11: Compiling gzclose.c failed: undeclared inclusion(s) in rule '@zlib//:zlib':
this rule is missing dependency declarations for the following files included by 'gzclose.c':
  '/usr/lib/clang/14.0.0/include/stddef.h'
  '/usr/lib/clang/14.0.0/include/stdarg.h'
  '/usr/lib/clang/14.0.0/include/__stddef_max_align_t.h'
  '/usr/lib/clang/14.0.0/include/limits.h'
ERROR: /home/dimanne/.cache/bazel/_bazel_dimanne/33c66632a93eff405a3246128a23107c/external/zlib/BUILD.bazel:5:11: Compiling compress.c failed: undeclared inclusion(s) in rule '@zlib//:zlib':
this rule is missing dependency declarations for the following files included by 'compress.c':
  '/usr/lib/clang/14.0.0/include/stddef.h'
  '/usr/lib/clang/14.0.0/include/__stddef_max_align_t.h'
  '/usr/lib/clang/14.0.0/include/limits.h'
  '/usr/lib/clang/14.0.0/include/stdarg.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

As far as I understand, bazel says that it is not aware of `/usr/lib/clang/14.0.0/include/`, which is understandable, because clang does not report this path as standard/system one:

```
clang -E -xc++ - -v
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda-12.0, version 
 (in-process)
 "/usr/lib/llvm-14/bin/clang" -cc1 -triple x86_64-pc-linux-gnu -E -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/dimanne -resource-dir /usr/lib/llvm-14/lib/clang/14.0.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/backward -internal-isystem /usr/lib/llvm-14/lib/clang/14.0.0/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/home/dimanne -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o - -x c++ -
clang -cc1 version 14.0.0 based upon LLVM 14.0.0 default target x86_64-pc-linux-gnu
ignoring nonexistent directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11
 /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11
 /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/backward
 /usr/lib/llvm-14/lib/clang/14.0.0/include
 /usr/local/include
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
```

Instead, there is  `/usr/lib/llvm-14/lib/clang/14.0.0/include`.

But if you `ls` it, you will see that those are same paths:
```
ls -al /usr/lib/clang/14.0.0/include
lrwxrwxrwx 1 root root 38 Mar 24  2022 /usr/lib/clang/14.0.0/include -> ../../llvm-14/lib/clang/14.0.0/include
```

Anyway, what is rationale behind comparing paths character-wise? I mean, symlinks do exist...

**Comment by DimanNe** [comment]
## Workaround

It seems that just (re-)moving the symlink made scripts/clang use headers from the non-symlinked directory:

```
cd /usr/lib/clang/14.0.0
sudo mv ./include symlinked-include
```
