### ISSUE TITLE
@bazel_tools should be documented

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#9460]
@bazel_tools defines a few globally useful constants and macros that are baked into Bazel.
The content should be documented so that supported features can be discovered and unsupported and deprecated features can be disowned. With nothing documented, users are free to discover behaviors and depend on them, deprecated or not.

**Comment by laurentlb** [comment]
Duplicate with https://github.com/bazelbuild/bazel/issues/4301
