### ISSUE TITLE
Importing the header of an objc_library from another objc_library

### ISSUE THREAD

**Issue by acecilia** [bazelbuild/bazel#9461]
Hello:

#### Description of the problem:

I am trying to consume an `objc_library` from a `objc_library` as follows:

```
load("@rules_cc//cc:defs.bzl", "objc_library")
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_unit_test")

objc_library(
    name = "ObjcModule",
    srcs = ["Sources/ObjcModule.m"],
    hdrs = ["Sources/ObjcModule.h"],
    module_name = "ObjcModule",
)

objc_library(
    name = "ObjcModuleTestsLib",
    srcs = ["ObjcTests/SomeCodeTests.m"],
    deps = [":ObjcModule"],
)

ios_unit_test(
    name = "ObjcModuleTests",
    minimum_os_version = "8.0",
    deps = [":ObjcModuleTestsLib"],
)
```

The content of `ObjcTests/SomeCodeTests.m` is:

```
#import <XCTest/XCTest.h>
#import "ObjcModule/ObjcModule.h"

@interface ObjcModuleTests: XCTestCase
@end

@implementation ObjcModuleTests
- (void)test {
  XCTAssertEqual(text, @"Hello, World!"); // The text constant is declared inside ObjcModule.h
}
@end
```

When running `bazel build //Libraries/ObjcModule:ObjcModuleTestsLib`, in line `#import "ObjcModule/ObjcModule.h"` I am getting the error `Libraries/ObjcModule/ObjcTests/SomeCodeTests.m:2:9: fatal error: 'ObjcModule/ObjcModule.h' file not found`. The only way I can make it work is by using the full path from the WORKSPACE: `#import "Libraries/ObjcModule/Sources/ObjcModule.h"`.

I expected `#import "ObjcModule/ObjcModule.h"` to work when doing `module_name = "ObjcModule"`. Any idea why it doesn't? Any workaround? Is this expected behaviour?

I am using bazel `0.29.1`.

Thanks!

**Comment by sergiocampama** [comment]
I don't think that's how objc modules are supposed to work, though I'm no expert in that subject. I believe with modules you are supposed to import objc modules using the `@import ObjcModule` statement, but I'm unclear on what the status is of that feature.

The expected way to import it is using the full path relative to the workspace, as you've already found. If what you really want is to have a shorter import path, you could in theory add an `includes = ["."],` attribute to the `ObjcModule` target, and then the directory where that target lives will be added as an include path, so you could just do `#import "ObjcModule.h"`.

Keep in mind that sprinkling `include` attributes might slow down your compilation a bit as the compiler will have to stat more locations to find the imported headers.

**Comment by acecilia** [comment]
Thanks for your comment @sergiocampama, after looking a bit more into it you are 100% right.

About importing objc modules into other objc modules (using `@import ObjcModule`), I did not manage to make it work, and after reading https://github.com/bazelbuild/bazel/issues/3229 seems that it may be not working in bazel at the moment ( I also tried the `--experimental_objc_enable_module_maps` flag without success).

Related to importing headers, your workaround of adding `includes = ["."],` works well in this case, but I do not think it will be enough when a target has multiple dependencies. For example, lets say `//Libraries/Library1:Library1` depends on `//Libraries/Dependency1:Dependency1`, `//Libraries/Dependency2:Dependency2`, `//Libraries/Dependency3:Dependency3`... In addition to set de dependencies of library 1, I would also need to add includes for each direct and transitive dependency.

The way this last point is solved in buck is by exposing the headers of the dependencies, so you can consume them by doing `#import "ObjcModule/ObjcModule.h"`, as explained in https://buck.build/rule/apple_library.html#exported_headers.

I am going to look into this a bit more, to see if I can find a workaround.

**Comment by thii** [comment]
I have a wrapper for objc_library here that makes this work: https://github.com/thii/rules_apple_extras.

**Comment by acecilia** [comment]
OMG thanks a lot @thii ! I will try it right now.

Meanwhile, after a lot of trial and error I managed to make it work as follows:
```
    exported_headers_rule_name = name + "ExportedHeaders"

    native.genrule(
        name = exported_headers_rule_name,
        srcs = headers, # The list of headers
        outs = ["includedir/" + name + "/" + x.split('/')[::-1][0] for x in headers], # Headers can be nested multiple levels, so we use x.split('/')[::-1][0] for x in headers to get their basenames
        cmd  = "cp $(SRCS) $(@D)" + "/includedir/" + name, # Finally we copy all headers under the includedir directory
    )

    objc_library(
        name = name,
        srcs = srcs,
        hdrs = [":" + exported_headers_rule_name], # in order to make sure that the headers under the includedir directory are inside the sandbox we have to make the exported_headers_rule_name a dependency of objc_library: we can do that by setting it as the value for the hdrs argument
        deps = deps,
        module_name = name,
        includes = ["includedir"], # Include the directory where the headers are. This will also be passed to rules depending on this one
        visibility = ["//visibility:public"],
    )
```

**Comment by tetromino** [comment]
@DavidGoldman - do you know how this is intended to work?

**Comment by rupertks** [comment]
Based on acecilia's latest reply/workaround, I am going to mark this as a P3 for now

**Comment by acecilia** [comment]
Consuming the objc as modules is the preferred way of doing as @sergiocampama mentioned, but there is no support for it yet: in my experience, the existing module support works for importing system modules (like `@import Foundation;`), but not for using it between dependencies https://github.com/bazelbuild/bazel/issues/9429

**Comment by vikage** [comment]
> @thii I saw you archived this https://github.com/thii/rules_apple_extras so any better solution now?

I try to use his repo but it does not work anymore. I switch to use rules_ios and write custom objc_library macro based on his repo.
```
load("@build_bazel_rules_ios//rules:hmap.bzl", "headermap")

def objc_library(
        name,
        deps = [],
        hdrs = [],
        copts = [],
        module_name = None,
        **kwargs):
    headermap(
        name = name + ".public_hmap",
        namespace = module_name or name,
        hdrs = hdrs,
        direct_hdr_providers = deps,
    )

    for dep in deps:
        copts = copts + ["-I$(execpath {})".format(dep)]

    copts = copts + [
        "-I$(execpath {})".format(name + ".public_hmap"),
        "-I.",
    ]

    deps = deps + [
        name + ".public_hmap",
    ]

    native.objc_library(
        name = name,
        deps = deps,
        hdrs = hdrs,
        copts = copts,
        module_name = module_name,
        **kwargs
    )
```

To use this, you need to add <Name>.public_hmap to deps like this
```
load("//build_system:objc_library.bzl", "objc_library")
objc_library(
    name = "GTMSessionFetcher",
    srcs = glob([
        "GTMSessionFetcher/Sources/Source/*.m",
    ]),
    hdrs = glob([
        "GTMSessionFetcher/Sources/Source/*.h",
    ]),
    enable_modules = True,
    module_name = "GTMSessionFetcher",
    weak_sdk_frameworks = [
        "Security",
    ],
)

objc_library(
    name = "GTMAppAuth",
    srcs = glob([
        "GTMAppAuth/Sources/GTMAppAuth/Sources/*.m",
        "GTMAppAuth/Sources/GTMAppAuth/Sources/GTMOAuth2KeychainCompatibility/*.m",
        "GTMAppAuth/Sources/GTMAppAuth/Sources/iOS/*.m",
    ]),
    hdrs = glob([
        "GTMAppAuth/Sources/GTMAppAuth/Sources/*.h",
        "GTMAppAuth/Sources/GTMAppAuth/Sources/Public/GTMAppAuth/*.h",
        "GTMAppAuth/Sources/GTMAppAuth/Sources/GTMOAuth2KeychainCompatibility/*.h",
    ]),
    enable_modules = True,
    module_name = "GTMAppAuth",
    visibility = ["//visibility:public"],
    weak_sdk_frameworks = [
        "Security",
        "AuthenticationServices",
        "SafariServices",
    ],
    deps = [
        ":AppAuth",
        ":GTMSessionFetcher",
        ":GTMSessionFetcher.public_hmap",
    ],
)

```

**Comment by bigbangvn** [comment]
Cool, thanks @vikage
I used the trick from @acecilia https://github.com/bazelbuild/bazel/issues/9461#issuecomment-537270226
It works also but no need to depends on rules_ios

**Comment by vikage** [comment]
> Cool, thanks @vikage
> I used the trick from @acecilia [#9461 (comment)](https://github.com/bazelbuild/bazel/issues/9461#issuecomment-537270226)
> It works also but no need to depends on rules_ios

@bigbangvn I look like this trick doesn't work when import angled of another module like #import <Module/Module.h>.
