### ISSUE TITLE
Automatic resolve of Bazel dependencies

### ISSUE THREAD

**Issue by irengrig** [bazelbuild/bazel#9465]
Investigate the approach for automatics resolve of Bazel rules/libraries dependencies.
Try to suggest an alternative to the manual deps() pattern; allow declarative approach for defining project's dependencies.

**Comment by cgruber** [comment]
Can you flesh out a bit what you mean by declarative? The deps are pretty declarative. What are some use-cases here?

**Comment by aiuto** [comment]
irengrig@ We're doing a lot of that in the federation.  You declare the names of the rule repos that you need and the federation selects the versions and the transitive dependencies of those.

One problem with the automatic approach is deciding what you need to develop rules vs. what your users need to use them. For examples, many of the rule sets now depend on rules_pkg to build a distribution tarball, but no users of the rules should have to depend on rules_pkg.
