### ISSUE TITLE
Feature request: allow bzl code to check whether it is called from a BUILD file or WORKSPACE file

### ISSUE THREAD

**Issue by eytankidron** [bazelbuild/bazel#9469]
### Description of the feature request:

It would be nice to allow a bazel macro in a .bzl file to query whether it is being executed from a WORKSPACE file or from a BUILD file.

There is also a third option that I am aware of, which is that the macro is being called as part of initialization of a global variable in a .bzl file.

### What underlying problem are you trying to solve with this feature?

I recently wrote a bazel macro which should only be called from a WORKSPACE, but I found that I don't have a good way to enforce this.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
