### ISSUE TITLE
declare_directory()'s directory is created locally, not remotely

### ISSUE THREAD

**Issue by clintharrison** [bazelbuild/bazel#9470]
### Description of the problem / feature request:

`ctx.actions.declare_directory()` does not behave the same between remote and local execution. Running locally, using the directory as an action's output works "as expected" -- a tool can write to it, and the contents can be used in a filegroup/etc. Under remote execution, though, this directory does not get created, and the tool must create it.

I was running into this, and quite stumped until I found that `rules_nodejs` already ran into this with a small test rule: https://github.com/bazelbuild/rules_nodejs/blob/2ababdf66335ccf2247b6643ea85bb5142dfda7e/packages/terser/test/directory_input/rule.bzl#L8

I suppose this _is_ very implicitly documented?
> You must create an action that generates the directory.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use the above rule, and remove `mkdir -p`.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

```
Build label: 0.27.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Jun 17 13:00:46 2019 (1560776446)
Build timestamp: 1560776446
Build timestamp as int: 1560776446
```

I'm running this remotely with [Buildbarn](https://github.com/buildbarn/), though the behavior seems to be present with RBE as well.

###  Have you found anything relevant by searching the web?

No, documentation around `declare_directory()` is quite sparse. I'd be happy to help improve this, but I'm not confident I understand it well enough to do that yet :) Perhaps that part's a dupe of #8228.

**Comment by cushon** [comment]
I think this is a dupe of #6393.

**Comment by clintharrison** [comment]
Ah, excellent! Thanks @cushon.
