### ISSUE TITLE
bazel-bazel/_tmp uses 10G of disk

### ISSUE THREAD

**Issue by janakdr** [bazelbuild/bazel#949]
example large directory:
170M    ./namespace_runner_test_36/root/install/575d777e347a34ed061a5474bf15a9f3/_embedded_binaries/embedded_tools

Not to mention that when I had an error that led to all tests failing, loading_tests_50 had a 10G log file. These files stick around even after bazel is done running my tests. Does this give faster incremental execution?

**Comment by philwo** [comment]
Was the large 10G log file a test log (which might be something the user is interested in, when the test failed) or some internal Bazel stuff that is uninteresting to users?

**Comment by janakdr** [comment]
Looks like Blaze also keeps the _tmp files around, so I can't really
complain about that. I'll check to see what the 10G file actually is when I
get a chance (i.e., when I have enough disk space).

**Comment by philwo** [comment]
@janakdr Do you think this is still an issue? I remember @lberki fixed something about _tmp files not being deleted some time ago (as it caused "no disk space remaining" errors on the MacPro CI machines), maybe that already solved this issue.

**Comment by janakdr** [comment]
Haven't run all the bazel tests for some time, so I don't know.

**Comment by janakdr** [comment]
Obsoleting.
