### ISSUE TITLE
analysis_test hangs sometimes

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#950]
I've seen `//src/test/java/com/google/devtools/build/lib:analysis_test` hang several times when running `./compile.sh test`. It normally completes in ~15 seconds, but occasionally it times out after 300 instead.

Output from one time it hung is at https://gist.github.com/bsilver8192/474bf094cfcee76d650d.

**Comment by kchodorow** [comment]
Marking as P1, since that's how we prioritize flakes internally.

**Comment by kchodorow** [comment]
Would bumping the shard count help?

**Comment by kchodorow** [comment]
Never rains but it pours: http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.7,PLATFORM_NAME=linux-x86_64/388/console.

**Comment by ulfjack** [comment]
I'm OOO until Monday.

**Comment by damienmg** [comment]
Hasn't happened in a month
