### ISSUE TITLE
Add support to re-export a target

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#953]
While attempting to port a software package that uses Bazel to a new platform, I have encountered various situations in which I had to tweak the `deps` of various targets to use a `select` to pick the correct dependency. This gets old very quickly.

In an attempt to simplify my build rules, I tried to introduce "intermediate" targets that abstract away the `select` in a single place of the build. That is: consider two implementations of the same library, `L1` and `L2`, that work on different platforms. Based on this, I defined a `L` "fake" target that uses `select` to depend on either `L1` or `L2` based on a configuration condition. Then, all users of the library just need to depend on `L` without being cluttered with `select` calls on their own. (Bonus points because after doing this, the visibility of `L1` and `L2` can be tightened.)

This above is somewhat doable in a bunch of cases, like for `java_library` with its `runtime_deps`, but it does not seem possible if the thing to abstract is a binary (or some other target whose implementation we don't know about).

I think it'd be interesting to have a rule that just "re-exports" a target. Something like this:

```
export(
    name = "foo",
    src = select({
        "//some:condition": "//the-os-x-implementation",
        "//conditions:default": "//the-default-implementation",
    }),
    visibility = ["//something"],
)
```

Ideally this would work on any target regardless of its implementation. The resulting target would just have the exact same properties of the re-exported target.

A question is what happens if the paths in the `select` statement result in targets with different semantics. I'd say that's something for the author of the build rules to deal with.

I'm not sure how feasible this is though, so filing this bug for discussion.

**Comment by bsilver8192** [comment]
I agree that this sounds useful. Seems to me like having targets in the different branches of the select which have different sets of transitive info providers should simply be an error (I think that cleanly handles the "targets with different semantics" question you brought up).

For targets where you only care about the resulting files (like all the uses of binaries I can think of), is there some reason `filegroup` doesn't work?

Also, as a workaround, I've found defining a Skylark function that returns a select is often not too bad. Something like this:
```python
# foo.bzl
def the_srcs():
  return select({
        "//some:condition": [ "//the-os-x-implementation" ],
        "//conditions:default": [ "//the-default-implementation" ],
    }),

# BUILD
load("/foo", "the_srcs")
my_rule(
  name = "foo",
  srcs = [ "//some:dependency" ] + the_srcs(),
)
```

**Comment by jmmv** [comment]
The `filegroup` alternative works for binaries (thanks!), but unfortunately not for all the rules I'm dealing with. Those rules only accept a very specific subset of possible dependency types, and `filegroup` is not among them (and no, changing those rules is out of the picture here).

Note also that, even in the case of `java_library` that I painted as easy before, it's not really. If you need the real dependencies to be available during the build and not just at runtime, `java_library` would not help because you must specify at least one `srcs`... I think.

I'll give a try to your Skylark trick. It can reduce some code duplication and it might help in what I'm doing, but it still does not exactly represent what a `reexport` rule would do. Thus I think having a `reexport` may still be useful.

**Comment by damienmg** [comment]
is it something like bind but who would be usable anywhere?

**Comment by bsilver8192** [comment]
@damienmg: Kind of like `bind` except also supporting `select` for the value (and usable everywhere).

**Comment by philwo** [comment]
I think this sounds like a very useful feature request.

**Comment by lberki** [comment]
@bsilver8192 : unfortunately, checking that the branches of the select have the same transitive info providers is not feasible, because the set of providers a configured target provides is not known until after analysis.

I was considering making it so that rules would have to define *all* the providers they intend to generate in their rule class definition (this would also make `#getAdvertisedProviders()` superfluous), but at the very least it would require an audit of all our rules.

**Comment by lberki** [comment]
@bsilver8192 : why do you think your `the_srcs()` "workaround" is a workaround? I think it's a perfectly acceptable solution. Do you think it's too verbose or hard to read?

@jmmv : What would `export()` provide that @bsilver8192 's trick doesn't?

**Comment by jmmv** [comment]
@lberki: If you are talking about the `the_srcs` solution... that "works" in this case for `srcs`, but it's not a general solution. Also, it's weird to have to do that by hand: semantically, having an `export` primitive that makes a node of the dependency graph show up elsewhere "untouched" seems easier to understand and explain, and also much easier for the user to get right.

Note that in my example, the reason I used `src` is nomenclature: I wasn't talking about input sources in particular; I was talking about just another label, which can be anything. The above example from @bsilver8192 only deals with `srcs`, but that's just a tiny part of a full rule definition. I'd like to re-export the full rule untouched, with all of its properties, without having to define my own rule that mixes bits from different dependent rules.

There is also the problem of rule types. I tried solving this with a custom Skylark rule that did the "interposing of the select". Unfortunately, this does not work because the predefined rules are very explicit as to which rule types they accept as inputs, and thus you cannot interpose whatever you want to create the indirection.

Poke me offline if you want specifics; I needed this for an internal change and I can show you the code I ended up having to write.

**Comment by bsilver8192** [comment]
@lberki: @jmmv pointed out another limitation I had forgotten about: the rule class will be different, which means many builtin rules won't accept these as dependencies. Also, if checking that all the possibilities have the same providers (and rule class etc) is hard, it also seems just fine to make that something for the user to deal with. Might be a bit confusing, but it shouldn't be too bad.

**Comment by damienmg** [comment]
isn't alias() sufficient? /cc @lberki @jmmv

**Comment by bsilver8192** [comment]
I think alias solves all the problems that have been mentioned here. When I saw that being added, I thought it might've been prompted by this bug.

**Comment by helenalt** [comment]
@jmmv if alias solves the problem is there anything else to do here or should this issue be closed?

**Comment by jmmv** [comment]
I have no idea if it's sufficient nor I have had a chance to validate, but I'll trust @bsilver8192's latest update for now. If we get more data otherwise we can always reopen in the future.
