### ISSUE TITLE
API for workspace requirements and dependencies specifications with defaults

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#9559]
### Description of the problem / feature request:

Inter-workspace dependencies are difficult when they involve diamonds, such as using skylib.  This causes a lot of headache where rules can't be used together before the various rules authors fix their dependencies on something more common and consistent. 

### Feature requests: what underlying problem are you trying to solve with this feature?

In the WORKSPACE file, in the workspace() rule (or by some other mechanism), there should be a way to declare what symbols are supplied by other workspaces, such as skylib or other libraries, with default workspace definitions so that a workspace importing a ruleset can:

  1. declare "exported symbols" 
  1. be aware when there's a diamond dependency between rules/workspaces by explicit notice
  1. provide an explicit resolution to pin an external workspace version (or encapsulate) _as a fulfillment_ of the requirement
  1. be able to evaluate if the workspace exports the correct symbols
 
If these are explicit, I believe it will both empower consumers of these workspaces, but also provide some discipline on the part of rule authors, which will lead to better API transitions, better backwards compatibility, etc. 

Also, more thorough documentation of the mechanics of external workspaces (not just examples or rules, or high-level, but some of the semantics of mutually dependent workspaces) would help manage these a lot, along with recommended practices.

If the above explicit declaration is not taken on board, then recommended practices for rule authors (if you're a library, don't depend on a library maybe?) and good examples of these patterns could be an alternative. 

### What operating system are you running Bazel on?

Mac OS X

### What's the output of `bazel info release`?

0.29.1

### Any other information, logs, or outputs that you want to share?

I'll work up some scenarios for this, but the classic one is `rules_a` and `rules_b` both depend on `library_a` but different versions, consuming different symbols, and so they cannot both be used by `project_a` until they are resolved and re-released.

**Comment by cgruber** [comment]
Ultimately the problem has to be solved by library authors (much like in the guava case) taking an extremely conservative position on API evolution, and/or allowing for more encapsulation, so that such dependencies don't leak (repo reference mapping or other encapsulation of some kind). The point here is to give explicit tooling support and metadata for discovering and resolving such problems, and practices/incentives/structures for minimizing the occurrence of such problems in the first place.

**Comment by aiuto** [comment]
We are working on inter-repo interoperability in https://github.com/bazelbuild/bazel-federation
The summary is
- diamond deps are resolved by the federation. You have to adopt to what it requires
- if you insist on pinning to another version of some repo, you have to load it yourself under another name than the canonical one.

But, the redirection there aside, we could use better tools in Bazel for seeing the dependency graph among repositories.

**Comment by fweikert** [comment]
I'll assign this to Yun for now, given that the entire external deps landscape is about to change radically (https://github.com/bazelbuild/bzlmod)
