### ISSUE TITLE
Build flake with bazel_tools

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#9568]
Sometimes on our CI we see this build failure:

```
ERROR: error loading package '': Encountered error while reading extension file 'tools/build_defs/repo/http.bzl': /private/var/tmp/_bazel_iosci/110b0077c997f2dbfa0f90a60784d8b7/external/bazel_tools/tools/build_defs/repo/http.bzl (No such file or directory)
ERROR: error loading package '': Encountered error while reading extension file 'tools/build_defs/repo/http.bzl': /private/var/tmp/_bazel_iosci/110b0077c997f2dbfa0f90a60784d8b7/external/bazel_tools/tools/build_defs/repo/http.bzl (No such file or directory)
```

I haven't been able to reproduce locally but a retry of the build always fixes it.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.29.1

### Any other information, logs, or outputs that you want to share?

Here's the bep log from a build [bep.json.zip](https://github.com/bazelbuild/bazel/files/3687124/bep.json.zip)

**Comment by philwo** [comment]
Closing as obsolete, please comment if you still see this.
