### ISSUE TITLE
Fix default path values to not include the current directory

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazel#958]
While researching #957, I noticed that the default path value configured in `BazelConfiguration.java` reads like the following:

```
builder.put("PATH", path == null ? ":/bin:/usr/bin" : path);
```

Note the leading `:` resulting in an empty path component. This is dangerous: an empty path component is the same as saying "current directory", which means that unqualified binary names will be picked up automatically. Commonly, this is considered to be a security problem — though I doubt it's a problem in this particular case based on the context. Regardless, we should fix this because paths including the current directory are just considered harmful and nothing should rely on them.

The same exists in `bazel_rules_test.sh`. I haven't audited the rest of the code completely, so this might be an issue elsewhere.

The fix is trivial but I wonder if this was intentional.

**Comment by ulfjack** [comment]
IIRC, we had a problem where binaries in the root of a project weren't
executed because bazel uses the exec path without a leading "./".

**Comment by jmmv** [comment]
So the use case that ulfjack mentions translates to a project having something like following in its root `BUILD` file:

```
genrule(name = 'foo', cmd = "$(location :bar) >$@", outs = [":baz"], tools = [":bar"])
java_binary(name = 'bar', ...)
```

I gave this a try and this seems to work even after stripping `:` from that default `PATH` instance. FWIW the `genrule` is picking my actual `PATH`. Maybe we just need to add a test to ensure this is functional.

**Comment by jmmv** [comment]
For the record: this change is not expected to cause any visible change.

The default `PATH` in the code would only be used if the user's `PATH` was unset (which is highly unlikely), and `genrule`s trying to execute files from the current directory would only have worked if the user's own path had the current directory in it.
