### ISSUE TITLE
`bazel query` doesn't accept --cpu or --crosstool_top

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#967]
`--cpu` and `--crosstool_top` both affect the dependency graph in potentially large ways, so it would be nice if I could pass them to `bazel query` to allow seeing the actual dependency graph being used by builds with those flags.

**Comment by philwo** [comment]
Assigning to bazel query ninja @laszlocsomor for a first judgement of this request.

**Comment by laszlocsomor** [comment]
I'm sorry to say that I'm fairly sure this is currently infeasible. Bazel query only uses loading phase data (what's in the BUILD files) while these flags define the build configuration, which Bazel only uses in the analysis phase, after loading is done. So to make Bazel query aware of the target CPU, Crosstool top, and other configurations-specific data would require a fundamental redesign.

**Comment by laszlocsomor** [comment]
That is also the reason why `bazel query 'deps(//foo)'`

**Comment by laszlocsomor** [comment]
Sorry, sent too early.

So this is also the reason why bazel query `'deps(//foo)'` reports all branches of a `select` as dependencies. At the end of the loading phase, we don't yet know which branch will be active, so bazel query reports all of them.

**Comment by bsilver8192** [comment]
That makes sense, but it's still acting somewhat like the default value of `--crosstool_top` is specified (that one's easier to test than `--cpu`, but I'm pretty sure they're the same). Changing the default to `@//tools/cpp:toolchain` makes my toolchain (and its dependencies) show up instead of `@bazel_tools//tools/cpp:toolchain` etc in `bazel query` output. It seems like allowing the value of the flag seen by `bazel query` to be set to something other than the default should be easy?

**Comment by ulfjack** [comment]
How would that be useful?

**Comment by bsilver8192** [comment]
I'm trying to operate over all the dependencies of a cc_library, including the implicit ones my custom crosstool_top brings in. For now I can just add `union //tools/cpp:toolchain` (that's where mine is located) to the query, but it would be nice to just have Bazel handle that.

**Comment by helenalt** [comment]
Re-triaged, priority is accurate, leaving in backlog

**Comment by ulfjack** [comment]
Julie has been working on adding a cquery command that takes configurations into account. I don't think we'll change query in this way, but recommend cquery instead.

**Comment by gregestren** [comment]
Specifically see 07c4e3648e3b7a521b6706ffc5cbcdeca1ebf4e1

This should be in the next Bazel release, and we're working on exporting some proper documentation along with it.
