### ISSUE TITLE
Add an option to specify where Java resources should be placed

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#97]
See https://groups.google.com/forum/#!msg/bazel-discuss/YPwULx-7tS4/MLHDRqglQDwJ for discussion.

**Comment by latos** [comment]
This is essential as we're currently relying on gross ad-hoc genrules, could it be added?

**Comment by kchodorow** [comment]
We've got a bunch of other things we're working on, so probably not right away. I'll bump the priority to reflect your interest, though.

**Comment by ulfjack** [comment]
ISTR that we did something, didn't we?

**Comment by meisterT** [comment]
This should be fixed: https://docs.bazel.build/versions/master/be/java.html#java_binary.resources
