### ISSUE TITLE
Add an installer for Windows

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#971]
I know this is still experimental but we should provide an easy way to install Bazel on Windows for 0.3

**Comment by dslomov** [comment]
Blocking #1453

**Comment by petemounce** [comment]
I could create a chocolatey (windows package manager) package that contains the built `bazel.exe` if that would satisfy this ticket? [docs](https://github.com/chocolatey/choco/wiki/CreatePackages).

**Comment by dslomov** [comment]
Sorry for late reply! Yes, choclatey package would be great! `scripts/packages/chocolatey` sounds about right.

**Comment by petemounce** [comment]
Fixed by a27949e27d4335216c28e77c41d078e338b5d4fb (+ release > 0.3.1).

**Comment by petemounce** [comment]
https://chocolatey.org/packages/bazel/ is now available.

**Comment by damienmg** [comment]
\o/ Awesome!

**Comment by petemounce** [comment]
@damienmg @meteorcloudy @dslomov I expect this can be shut too?

**Comment by meteorcloudy** [comment]
Yes, I think so! Thank you so much for the awesome work! \o/
