### ISSUE TITLE
go_binary in external dependency doesn't work on Linux

### ISSUE THREAD

**Issue by rshin** [bazelbuild/bazel#976]
I have a ```WORKSPACE``` file which contains the following:
```
new_git_repository(
    name = "boringssl",
    remote = "https://boringssl.googlesource.com/boringssl",
    commit = "e412bbd9a15d812666291e38e194b71da6a2a062",
    build_file = "BUILD.boringssl",
)
load("@bazel_tools//tools/build_rules/go:def.bzl", "go_repositories")
go_repositories()
```
where ```BUILD.boringssl``` contains
```
load("@bazel_tools//tools/build_rules/go:def.bzl", "go_prefix")
load("@bazel_tools//tools/build_rules/go:def.bzl", "go_binary")
go_prefix('boringssl')
[...]
go_binary(
    name = "err_data_generate",
    srcs = ["crypto/err/err_data_generate.go"],
)
```

Then ```bazel build @boringssl//:err_data_generate``` works as expected on Mac OS X, but on Linux, it fails with the following error:
```
ERROR: .../BUILD:915:1: every rule of type go_binary implicitly depends upon the target '@//tools/build_rules/go/toolchain:toolchain', but this target could not be found because of: no such package '@//tools/build_rules/go/toolchain': BUILD file not found on package path.
```

Then I tried re-compiling Bazel after editing https://github.com/bazelbuild/bazel/blob/6beaebdfa7ea3d0bcfd58511dbf6f588b206914d/tools/build_rules/go/def.bzl#L322-L327 to replace ```@//tools``` with ```@bazel_tools//tools```, and that version seems to work fine.

Is this change correct to make? I don't understand the difference between using ```//tools```, ```@//tools```, and ```@bazel_tools//tools```, and also why it initially worked on OS X but not on Linux.

**Comment by davidzchen** [comment]
The correct way to reference the tools repository should be `@bazel_tools//` so that should be the right change.

I can't seem to find documentation on `@//` on the site. Perhaps we should document it.

**Comment by laramiel** [comment]
Also encountered, and verified that the suggested change fixes the problem.
