### ISSUE TITLE
JDK9/javac compilation failure when defining javacopts source/target=8

### ISSUE THREAD

**Issue by perezd** [bazelbuild/bazel#979]
(bazel from **master**)

BUILD file:
```
android_library(
  ...
  javacopts = ['-source 8', '-target 8'],
)
```
Message:
```
An exception has occurred in the compiler (1.9.0-internal). Please file a bug at the Java Bug Database (http://bugreport.java.com/bugreport/) after checking the d
atabase for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
BazelJavaBuilder threw exception: java compilation returned status ABNORMAL
```
compiler params (generated by bazel):
https://gist.github.com/perezd/3e5e1584ceff4ba5e733

**Comment by perezd** [comment]
FWIW, this code properly compiles as a `java_library`.

**Comment by ahumesky** [comment]
The classes in the java.lang.invoke package need to be included in the bootclasspath because they aren't in android.jar (which is java 7). See the prototype attached in this thread: https://groups.google.com/forum/#!searchin/bazel-discuss/retrolambda/bazel-discuss/Or50uVScwkI/urbzp1iDEwAJ

**Comment by perezd** [comment]
This was resolved. Thanks!
