### ISSUE TITLE
Cannot run installer on machines where /home is mounted to NFS

### ISSUE THREAD

**Issue by zer0n** [bazelbuild/bazel#982]
Our `/home` is mounted to a NFS and the NFS is set up (by default) such that `root` doesn't have write permission in `$HOME`.

Bazel installer, when running as root, creates `$HOME/.cache/bazel/_bazel_root`, which isn't allowed. Of course, one cannot run the installer without `sudo`.

So I'm kinda stuck.

Even if root has write permission in `$HOME`, it still feels wrong. root should not create anything under `$HOME`. Shouldn't the cache be written to `/tmp` ?

**Comment by kchodorow** [comment]
On the plus side, at the point where the Bazel installer tries to write `$HOME/.cache/bazel/_bazel_root`, Bazel should already be installed (it's [here](https://github.com/bazelbuild/bazel/blob/master/scripts/packages/template_bin.sh#L159)), it's just trying to speed up startup time at that point.

You should also be able to run the installer as non-root (`bazel-0.2.0-etc.sh --user`).

But yeah, we should allow passing a .bazelrc or something to that initial run of `bazel help`.

**Comment by helenalt** [comment]
@cvcal this seems related to #592, could you see if it needs to be incorporated into a solution proposed in  #4502. If so, let's close this bug and reference the one that has a proposal.

**Comment by cvcal** [comment]
IIUC, I don't think it's the same issue - this has to do with a path accessed during the installation of bazel, not during every run thereafter. It's already possible to pass a bazelrc to bazel help, with the `--bazelrc` flag, so my guess is this issue is specific to the installer.

**Comment by cvcal** [comment]
@philwo, I think, knows more about the installer. Do you think Kristina's solution is still applicable?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
