### ISSUE TITLE
Bazel doesn't keep executable bit when extracting tarballs

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#984]
If I add a tarball to my workspace:

```python
native.new_http_archive(
    name = "phantomjs",
    build_file_content = "exports_files(['bin/phantomjs'])",
    sha256 = "86dd9a4bf4aee45f1a84c9f61cf1947c1d6dce9b9e8d2a907105da7852460d2f",
    strip_prefix = "phantomjs-2.1.1-linux-x86_64",
    url = "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2",
)
```

I can't do this:

    bazel run @phantomjs//:bin/phantomjs

Because the file isn't executable. But it has the executable bit set inside the tarball. So the [relevant sauce](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/CompressedTarFunction.java) should be updated to preserve the executable bit.

**Comment by bsilver8192** [comment]
If you look at the file, it is executable:
```console
$ ls -l $(bazel info output_base)/external/phantomjs/bin
total 66340
-rwxr-xr-x 1 brian brian 67932064 Feb 29 10:21 phantomjs
```

The reason that doesn't work is because Bazel has its own concept of which files are executable. For example, with `genrule`, you have to set `executable = True` for running it to work. Adding a `genrule(executable = True)` which copies the file should let you `bazel run` the output of the genrule.

**Comment by jart** [comment]
Well in that case, why is my workaround working?

```python
genrule(
    name = "phantomjs_bin",
    srcs = ["@phantomjs//file"],
    outs = ["phantomjs"],
    cmd = " && ".join([
        "IN=$$(pwd)/$(SRCS)",
        "OUT=$$(pwd)/$@",   
        "TMP=$$(mktemp -d)",
        "cd $$TMP",
        "tar -xjf $$IN",
        "cd phantomjs-*",
        "mv bin/phantomjs $$OUT",
        "rm -rf $$TMP",
    ]),
)
```

This doesn't have `executable = True` but I'm still able to execute it, because the file when it's copied has the executable bit set.

**Comment by jart** [comment]
Out of curiosity, would Bazel allow me to write `sh_binary` wrappers around the executable files extracted by by `new_http_archive`? I can't decide if that kludge is less dirty than writing a `genrule` that copies a huge file.

Also is there any chance Google would reconsider this behavior? Having to copy executable files to make them executable just feels wrong to me.

**Comment by bsilver8192** [comment]
Looks like I didn't understand all the details of how this works. Upon looking at the code, it allows running output files which are executable but not input files. Looks weird to me and it was easy to fix, which I did with [Ic986ea9bbe88e0edb933939ce1d7a8b6ea9d6e88](https://bazel-review.googlesource.com/#/q/Ic986ea9bbe88e0edb933939ce1d7a8b6ea9d6e88).

Wrapping a `sh_binary` around them should work too. Also, absolute symlinks (`cmd = 'ln -s $$(realpath $<) $$(realpath $@)'`) should work too and avoids copying.

**Comment by jart** [comment]
You're awesome. Thank you.
