### ISSUE TITLE
go tests are failing on ci.bazel.io

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#985]
See http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.7,PLATFORM_NAME=linux-x86_64/382/testReport/junit/(root)/(empty)/test_basic/

Assigning to David who made a change recently, probably a problem in the test fixture.

**Comment by kchodorow** [comment]
This was fixed by 9bdc0d466b8536b2431b585c615715fff6960b97.
