### ISSUE TITLE
new_local_repository rule's "path" attribute does not allow use of files, despite docs

### ISSUE THREAD

**Issue by seh** [bazelbuild/bazel#9857]
### Description of the problem / feature request:

[The documentation for the `new_local_repository` rule](https://docs.bazel.build/versions/master/be/workspace.html#new_local_repository) claims that its "path" attribute may point to a single file, and offers an example showing it in action. Quoting from the introductory prose:

> You can also use `new_local_repository` to include single files, not just directories. For example, suppose you had a jar file at /home/username/Downloads/piano.jar. You could add just that file to your build by adding the following to your WORKSPACE file:

[The "path" attribute's documentation](https://docs.bazel.build/versions/master/be/workspace.html#new_local_repository_args) restates this offer (emphasis mine):

> This must be an absolute path to **an existing file** or a directory.

This documentation entered the repository five years ago in [file _src/main/java/com/google/devtools/build/lib/rules/repository/NewLocalRepositoryRule.java_](https://github.com/bazelbuild/bazel/commit/d08b27fa9701fecfdb69e1b0d1ac2459efc2129b#diff-69d8115c2cf9f360b7a8b4e687caa4ff) as part of commit d08b27fa9701fecfdb69e1b0d1ac2459efc2129b.

However, the current implementation in `NewLocalRepositoryFunction#fetch()` [disallows use of files,](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/repository/NewLocalRepositoryFunction.java#L89-L98) and only tolerates the "path" attribute nominating a directory.

Either the documentation is stale, or the implementation fails to meet the specification.

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to temporarily replace use of the `http_file` rule with a local repository, experimenting with use of a locally built patched binary we normally download from as a released artifact.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a directory _repo_ with a single file inside—_greeting.txt_—and a Bazel package in the _dependent_ directory trying to refer to that first directory as a local repository.

```shell
mkdir -p ${TMPDIR}/repo \
&& echo 'Hello.' > ${TMPDIR}/repo/greeting.txt \
&& mkdir -p ${TMPDIR}/dependent \
&& {\
cat > ${TMPDIR}/dependent/BUILD.bazel <<EOF
new_local_repository(
  name = "file",
  path = "${TMPDIR}/repo/greeting.txt",
  build_file = "BUILD.repo",
)
EOF
} && {\
cat > ${TMPDIR}/dependent/BUILD.repo <<EOF
filegroup(
  name = "file",
  srcs = ["greeting.txt"],
  visibility = ["//visibility:public"],
)
EOF
}
```

### What operating system are you running Bazel on?

macOS version 10.14.6

### What's the output of `bazel info release`?

`release 0.29.1-homebrew`

**Comment by philwo** [comment]
I can still repro this (note that in the repro instructions the first `cat` has to go into a `WORKSPACE` file, not a `BUILD.bazel` file.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
