### ISSUE TITLE
Pick a correct FilesToRunProvider in Starlark rules depending on what attribute is used to access the executable.

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#987]
Consider 

``` python
# extension.bzl
my_rule = rule(_main_rule_impl,
   attrs = { ",
      'exe1' : attr.label(executable = True, allow_files = True),",
      'exe2' : attr.label(executable = True, allow_files = True),",
   },",

# BUILD
load('extension', 'my_rule')
sh_binary(name = 'tool1', srcs=['tool.sh'], data=['file1.txt'])
sh_binary(name = 'tool2', srcs=['tool.sh'], data=['file2.txt'])
my_rule(name='foo', exe1 =':tool1', exe2=':tool2')
```

Currently, SkylarkRuleContext associates the same random `FilesToRunProvider` with values ctx.executable.exe1 and ctx.executable.exe2 (see https://github.com/bazelbuild/bazel/blob/b0439c5fb0bbbc4999c46f1154c6fef90bc79c8d/src/main/java/com/google/devtools/build/lib/rules/SkylarkRuleContext.java#L299).

The correct solution would be to associate both the executable artifact _and_ the  `FilesToRunProvider` with an `executable`'s field.

/cc @laurentlb

**Comment by dslomov** [comment]
Part of action API overhaul

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
