### ISSUE TITLE
maven_jar forces ijar usage

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#990]
When you add a maven_jar, it adds a java_import rule that exports the jar.

The problem is that in scala, macros are code in jars that is run at compile time. So, using ijar on them breaks compilation.

What we need is a way in maven_jar to control this.

One possibility is to add the ability to pass the BUILD to the rule, but to use this from java would mean solving #970 

the work around now is to use http_file and special case handling that in the scala.bzl rules:

https://github.com/bazelbuild/rules_scala/blob/master/scala/scala.bzl#L185

**Comment by damienmg** [comment]
Doesn't the maven_jar creates  a //:file target that you can use? maven_jar wrap the jar in a java_import so yes it forces it.

**Comment by johnynek** [comment]
I don't see the file target. For example:

```
# DO NOT EDIT: automatically generated BUILD file for maven_jar rule jar_commons_logging_commons_logging
java_import(
    name = 'jar',
    jars = ['commons-logging-1.2.jar'],
    visibility = ['//visibility:public']
)
```

**Comment by damienmg** [comment]
oh yeah it is not exported. Adding a filegroup would do the trick, no?

**Comment by johnynek** [comment]
I think so, yes.

**Comment by colinmarc** [comment]
I did a gerrit thing, I think? =)

https://bazel-review.googlesource.com/#/c/3550/

**Comment by smparkes** [comment]
@johnynek: how are you depending on this?
