### ISSUE TITLE
bazel 0.2.0 undeclared inclusion(s) Error

### ISSUE THREAD

**Issue by lfwin** [bazelbuild/bazel#992]
Hi,
cuda:0.7.0, ubuntu 14.04LTS, and install from source follow the tutorial ¨https://www.tensorflow.org/versions/r0.7/get_started/os_setup.html¨, but got error messages as below:
./tensorflow/core/platform/macros.h:54:28: note: in definition of macro 'TF_PREDICT_TRUE'
 #define TF_PREDICT_TRUE(x) x
                            ^
./tensorflow/core/platform/default/logging.h:193:1: note: in expansion of macro 'TF_DEFINE_CHECK_OP_IMPL'
 TF_DEFINE_CHECK_OP_IMPL(Check_EQ,
 ^
ERROR: /home/lfwin/tensorflow/tensorflow/core/kernels/BUILD:712:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:depthwise_conv_op':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/depthwise_conv_op.cc':
  '/home/lfwin/tensorflow/tensorflow/core/common_runtime/device.h'
  '/home/lfwin/tensorflow/tensorflow/core/graph/graph.h'
  '/home/lfwin/tensorflow/tensorflow/core/graph/edgeset.h'
  '/home/lfwin/tensorflow/tensorflow/core/graph/types.h'.
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 70.625s, Critical Path: 49.50s

**Comment by kchodorow** [comment]
It sounds like a bug in tensorflow's BUILD files, have you tried filing a bug with them?
