### ISSUE TITLE
Undeclared headers dependencies doesn't lead to error (Windows)

### ISSUE THREAD

**Issue by maximyurchuk** [bazelbuild/bazel#9965]
### Description of the problem / feature request:
Not all headers in cpp files are checked by Bazel that they are in dependencies (there is no `this rule is missing dependency declarations for the following files included by ...` error). 

Since there is no sanbox on Windows there is should be some adequate way to detect undeclared dependencies. 

Moreover bazel invokes `cl.exe` with `/showIncludes` option, but undeclared headers are not detected. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
You can find reproduce code [here](https://github.com/maximyurchuk/bazel-issues/tree/master/missing_headers_check). 

Attention on `lib.cc` file:
```
#include <from_another_target/missing_dep.h>  // undeclared dependency
#include <missing_dep_from_another_target.h>  // undeclared dependency
#include "missing_dep.h"                      // undeclared dependency

// This case detected by Bazel
// #include "local_include/missing_dep.h"

int foo;
```

All these headers are not declared as dependencies. 

### What operating system are you running Bazel on?
Windows 10, 1903.

### What's the output of `bazel info release`?
```
C:\git\bazel-issues\missing_headers_check>bazel-latest info release
INFO: Writing tracer profile to 'C:/users/yurchuk/_bazel_yurchuk/ivh3eama/command.profile.gz'
release 1.0.0rc4
```

**Comment by maximyurchuk** [comment]
Also, if I change some of these headers bazel will rebuild dependent library (which has no dependency in BUILD file on these headers). So looks like bazel knows, that dependency exists, but ignores that this dependecy is undeclared.

**Comment by maximyurchuk** [comment]
I just add some results of my analysis.

After exploring bazel source code I've found that include paths from another targets dependencies are passed with `-isystem` option. In other hand there is an option in bazel `--strict_system_includes` which is disabled by default which makes `-isystem` headers are less restrictive for verification: bazel just ignore all files from system includes. 

Explanation above is appliable for 
```
#include <from_another_target/missing_dep.h>  // undeclared dependency
#include <missing_dep_from_another_target.h>  // undeclared dependency
```

But if enable `--strict_system_includes` option, undeclared inclusion
```
#include "missing_dep.h"                      // undeclared dependency
```
is still doesn't lead to error. For unknown reason for me empty paths (i.e. headers in workspace root) are ignored in [CppCompileAction.java](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java)
![image](https://user-images.githubusercontent.com/25539081/66511782-4bfdaa00-eae0-11e9-9c66-c8a028c8f631.png)

**Comment by maximyurchuk** [comment]
> iirina added team-Windows

jfyi: actually, issue present on other platforms (at least linux), but only if sandboxing is disabled (`spawn_strategy=standalone`).

**Comment by laszlocsomor** [comment]
@maximyurchuk : Thanks for your report, I concluded the same as you. Forwarding the bug to the C++ team.

**Comment by maximyurchuk** [comment]
> hlopko referenced this issue ...

Please note, that actually this issue consists from 2 different parts (which appeared after some analisys): 
1) header from top level are not checked for inclusions (this issue strongly related with #10047)
2) headers from most source code is not checked for inclusions on windows. I think this check should exists by default (at least for better bazel experience on windows). It can be fixed for example with `--strict_system_includes=True` by default or with passing inlcude paths with ordinary includes not system_includes (this issue not related with #10047)


Maybt it's better split issue on two different issues.

**Comment by laszlocsomor** [comment]
> Please note, that actually this issue consists from 2 different parts

Good point.

I can confirm that (2) also appears on Linux with `--spawn_strategy=standalone`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
