### ISSUE TITLE
Output environment in aquery

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#9971]
### Description of the feature request:

I would like `bazel aquery` to output the environment variables as well, not just
```
$ bazel aquery 'deps(//some:label)'
action 'Writing file some_file_name'
  Mnemonic: ...
  Target: ...
  Configuration: ...
  ActionKey: ...
  Inputs: [...]
  Outputs: [...]
```
(The example above was taken from https://docs.bazel.build/versions/master/aquery.html.)

### Feature requests: what underlying problem are you trying to solve with this feature?

For debugging remote execution, knowing exactly what is sent to the remote is of interest. I can observe it on the remote side, but it simplifies the toolchain development if I also can observe it on the client side using `bazel aquery`.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

`release 0.29.1`

###  Have you found anything relevant by searching the web?

In `src/main/java/com/google/devtools/build/lib/query2/aquery/ActionGraphTextOutputFormatterCallback.java`, the environment is printed `if (action instanceof SpawnAction)`. This can probably be extended to include `AbstractAction` or something similar.

The line also includes `TODO(twerth): This handles the fixed environment. We probably want to output the inherited environment as well.`

**Comment by joeleba** [comment]
This should be fixed with https://github.com/bazelbuild/bazel/commit/95f6a948db4bab078b93334e6f91a5471b117ff7.
```
$ bazel aquery //src:bazel
...
action 'Building src/main/java/com/google/devtools/build/lib/libbazel-class.jar ()'
  Mnemonic: Javac
  Target: //src/main/java/com/google/devtools/build/lib:bazel
  Configuration: k8-fastbuild
  ActionKey: 2ce533fc13dd2a64c61c68910a6b423ba4672d68a8c7c05e47c9d8a4ed0ee371
  Inputs: [bazel-out/host/internal/_middlemen/external_Sremotejdk11_Ulinux_Cjdk, bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath.jar, external/remote_java_tools_linux/java_tools/JavaBuilder_deploy.jar, external/remote_java_tools_linux/java_tools/java_compiler.jar, external/remote_java_tools_linux/java_tools/javac-9+181-r4173-1.jar, external/remote_java_tools_linux/java_tools/jdk_compiler.jar]
  Outputs: [bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/libbazel-class.jar, bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/libbazel-native-header.jar, bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/libbazel.jar_manifest_proto]
  Environment: [LC_CTYPE=en_US.UTF-8]
  Command Line: (exec external/remotejdk11_linux/bin/java \
    -XX:+UseParallelOldGC \
    -XX:-CompactStrings \
    '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' \
    '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' \
    '--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED' \
...
```

**Comment by mehrdadn** [comment]
Hi, I don't seem to get environment variable information for `clang-cl` invocations. This is absolutely critical for the rest of the information to be useful, since various variables (like `INCLUDE`) affect which Visual Studio installation is detected and used by Clang-Cl. Could this be fixed? (I would assume this is a bug, since I would expect `aquery` to return environment variables for all actions.)

**Comment by fmeum** [comment]
Should have been fixed by https://github.com/bazelbuild/bazel/commit/2ae409bc88aaab5683f1890acec21c337b73a812
