### ISSUE TITLE
Release 1.1 - October 2019 (stable)

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#9982]
Target RC date - October 14th, 2019

**Comment by jmillikin-stripe** [comment]
Has the baseline CL already been cut? I'm hoping to get https://github.com/bazelbuild/bazel/pull/9872 into v1.1 since it was too late for v1.0.

**Comment by meisterT** [comment]
My plan is to cut the release on Monday morning MUC time.

**Comment by iirina** [comment]
Can we include the latest java_tools release https://github.com/bazelbuild/bazel/pull/9991 in Bazel 1.1? We release java_tools once per month with the goal of upgrading the default version in bazel released in the same month. We were late with the java_tools release because of some uncertainty around  #8772 and also because of not knowing when bazel 1.1 rc1 is going to be cut.

**Comment by iirina** [comment]
@meisterT  The commit to include is f939278a3534e43858ca409c8b685e6d73eea070.

**Comment by davido** [comment]
> Can we include the latest java_tools release #9991 in Bazel 1.1?

+1 to include #9991 in Bazel 1.1.

f939278 partially fixed #8772, as it includes this [PR](https://github.com/bazelbuild/bazel/pull/9450).

**Comment by meteorcloudy** [comment]
Please make sure to include 618e5a2 for fixing #9995

**Comment by meisterT** [comment]
RC1 created: `scripts/release/release.sh create 1.1.0 d9fe1d4078c25912427c9b2e79e115f4ee9b7ab8`

expected release date Oct 21

**Comment by meisterT** [comment]
Downstream build is here: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1234
Draft release announcement is here: https://docs.google.com/document/d/1wDvulLlj4NAlPZamdlEVFORks3YXJonCjyuQMUQEmB0/edit?ts=5da47c92&pli=1#heading=h.c3hdfz9d222b

**Comment by meisterT** [comment]
First release blocker (more to come):
https://github.com/bazelbuild/bazel/issues/10023

**Comment by meisterT** [comment]
Issue with Bazelisk: https://github.com/bazelbuild/bazel/issues/10024

**Comment by meisterT** [comment]
Issue with Tulsi: https://github.com/bazelbuild/bazel/issues/10026

**Comment by iirina** [comment]
Please cherry pick 0a8071af47223989e9ba335e63b8a9595fe6f10f for #10023.

**Comment by meisterT** [comment]
creating new rc with `scripts/release/release.sh create --force_rc=2 1.1.0 d9fe1d4078c25912427c9b2e79e115f4ee9b7ab8 0a8071a`

**Comment by meteorcloudy** [comment]
Since https://github.com/bazelbuild/bazel/commit/618e5a28f7f735c37724377b15775a4975349c74 is in the release, but it's rollbacked and replaced by 3a43b095b57bf0f93adc30098f9b921c27743a18, we probably should cherry-pick https://github.com/bazelbuild/bazel/commit/ac99c298f377f21707738eecc83252c932522a86 and https://github.com/bazelbuild/bazel/commit/3a43b095b57bf0f93adc30098f9b921c27743a18.

**Comment by meisterT** [comment]
We have decided offline that Yun's cherry-pick request would not require a new RC.

Downstream pipeline is green, so we'll release on Monday as planned if there are no new blockers until then.

**Comment by meisterT** [comment]
We have a new release.

cc @vbatts @petemounce @excitoon

**Comment by vbatts** [comment]
What's the branch strategy now? 1.1 and 1.0.1 in the same day. COPR repos like I am using for fedora and CentOS only publish the latest build of a package.

-------- Original Message --------

**Comment by meisterT** [comment]
1.0.1 only contains bug fixes, while 1.1.0 also contains (compatible) features.

**Comment by vbatts** [comment]
On 21/10/19 02:49 -0700, Tobias Werth wrote:
>   We have a new release.
>
>   cc [1]@vbatts [2]@petemounce [3]@excitoon

fedora and centos/rhel builds kicked off for x86_64 and aarch64:
https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/1067164/

also, success on building fedora, centos, and rhel for ppc64le:
https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/1067140/
(only oddity is `env ./output/bazel build ${EXTRA_BAZEL_ARGS} //scripts:bazel-complete.bash` is failing with "Exec format error")

**Comment by meisterT** [comment]
Thanks!

**Comment by petemounce** [comment]
Gonna be a latency for chocolatey release; I'm in China until November.

**Comment by keith** [comment]
We discovered a bug that I believe warrants a patch release once we can find a fix https://github.com/bazelbuild/bazel/issues/10184

**Comment by keith** [comment]
I have submitted a fix for this issue https://github.com/bazelbuild/bazel/pull/10185 and would love it if we could consider a patch release for this.

**Comment by petemounce** [comment]
Chocolatey published, apologies for the wait.
