### ISSUE TITLE
Overhaul treatment of generic types in @StarlarkMethod-annotated functions

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#9986]
In `@SkylarkCallable` functions, parameterized collection types are not validated and thus error-prone. That is:

```
@SkylarkCallable(...)
public void foo(SkylarkList<String> stringList) { ... }
```
In the above example, `stringList` **is** validated to be of type `SkylarkList`, but is not validated to be of generic type `<String>`. 
There are validation method available to verify the type of a `SkylarkList`, but they are lacking.

Namely, [SkylarkList.getContents()](https://github.com/bazelbuild/bazel/blob/a3421e204f22e478382bb8487b96df9dcd8e463a/src/main/java/com/google/devtools/build/lib/syntax/SkylarkList.java#L185) returns an immutable, type-specified `java.util.List` view on the `SkylarkList`. However, its validation is only shallow.

For example, this method can be used to verify a `SkylarkList<?>` contains `String`, and to acquire a `List<String>` view on the list., but **cannot** be used to verify a `SkylarkList<?>` contains `SkylarkList<String>`, nor to acquire a `List<List<String>` or a `List<SkylarkList<String>>` view.

The proposed solution to fix this is to implement a method similar to `SkylarkList.getContents()` which utilizes [SkylarkType](https://github.com/bazelbuild/bazel/blob/a3421e204f22e478382bb8487b96df9dcd8e463a/src/main/java/com/google/devtools/build/lib/syntax/SkylarkType.java):

- Add a generic type to `SkylarkType`. For example, the singleton `SkylarkType.INT` would be of type `SkylarkType<Integer>`, and there could also be a singleton `SkylarkType.STRING_LIST` which would be of type `SkylarkType<SkylarkList<String>>`.
- Implement a new method on `SkylarkList` with signature
 `public <X> List<X> getContents(SkylarkType<X> type)` that will validate the contents of the list match the given SkylarkType and return the fully typed `List` view.

Some benefits here are that deep type checking is possible using the same interface as shallow checks. For example, consider:
```
SkylarkType<SkylarkList<?>> SkylarkType.LIST = ...;
SkylarkType<SkylarkList<String>> SkylarkType.STRING_LIST = ...;
```
Validation with `SkylarkType.LIST` could be shallow, and validation with `SkylarkType.STRING_LIST` could be deep.

One can imagine similar improvements on Starlark collection types beyond `SkylarkList`.

**Comment by iirina** [comment]
@c-parsons can you please assign a priority?

**Comment by alandonovan** [comment]
Can we sketch the API a short standalone Java program? I think it should feasible to implement these four methods:
```
  copy(v, T)
  copyShallow(v, T)
  view(v, T)
  viewShallow(v, T)
```
where the `copy*` methods return a value that does not alias v, and the view methods return an alternatively typed alias for v; and where the `*Shallow` methods verify only the topmost type constructor (class symbol) and return e.g. `List<?>`, whereas the non-shallow methods traverse the entire data structure and may return types such as `List<List<String>>`.

The `view` methods would still be unsound in the face of subsequent mutation, of course.

**Comment by c-parsons** [comment]
non-shallow methods wont' be able to return the correct deep Java type unless T provides deep type information (as described above by the proposed `SkylarkType.STRING_LIST` type). And, if T **can** provide deep type information, why do we need *Shallow methods at all? The depth of the copy or view can be inferred from T

**Comment by alandonovan** [comment]
It's a reasonable question. Imagine a parameter of nominal type `List<String>`. You might want to assert in two stages that it is a list, and that each element is a string, deferring the second stage until later.  With a single type symbol for `List<String>`, you could do this in two steps, the first being a call to viewShallow.  Without the shallow operation you would need to construct a different type symbol for `List<?>` for the first check. This is of course doable, but it may be clearer or convenient if both operations can be expressed using the same type symbol. Perhaps this is unnecessary. I'm also not certain that viewShallow's type is expressible in Java.

**Comment by brandjon** [comment]
This issue and discussion predated the refactoring of the Starlark interpreter, and the elimination of `SkylarkType` in particular. The current paradigm is to use `Sequence#cast` and similar to check types where necessary, and to treat `ParamType#generic1` as for documentation purposes only, with the Java method signature always using Object for the generic type.
