### ISSUE TITLE
Bazel always creates profile and logs

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#9988]
With bazel 1.0 it seems that bazel now always creates a profile controlled by `--profile` and logs about it.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
% bazel info release
INFO: Writing tracer profile to '/private/var/tmp/_bazel_ksmiley/5ef608190b288a339c09ffb210204e7f/command.profile.gz'
release 1.0.0
```

There also seems to be no way to disable this:

```
% bazel info release --profile=
ERROR: Error while creating profile file: /Users/ksmiley/dev/bazel (Is a directory)
release 1.0.0
```

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 1.0.0

**Comment by keith** [comment]
Hrm, it looks like setting `--incompatible_enable_profile_by_default=false` fixes this. But I assume this flag will default to true sometime soon? In which case it would be nice to fix the noisy logging before that, or only print the path if the user passes the log info.

**Comment by iirina** [comment]
cc @meisterT

**Comment by meisterT** [comment]
Ughh, this was not intended to show up for `info`. 
I didn't expect info to be a "build" command: https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/commands/InfoCommand.java#L51

You can also do `--noexperimental_generate_json_trace_profile`. I will simplify this soonish.

**Comment by keith** [comment]
I used info as the example because it was the simplest but I think we'd also prefer to not have this log for actual builds unless the user requested the profile. We've now started setting the incompatible flag to get this behavior.

**Comment by meisterT** [comment]
What's the reason you would like to have this off by default?

**Comment by keith** [comment]
I just meant the log off by default. We try to keep the Bazel info / debug logs to a minimum because we've found they quickly get out of hand which makes it harder for developers to parse the important pieces.

**Comment by meisterT** [comment]
Thanks for the clarification. I am bit torn.

On the one hand, I fully agree with you that we should keep the log as short as possible. On the other hand it's a nice education of our users that the profile is now always available and where it lives.

**Comment by keith** [comment]
As long as we can set the --no flag you mentioned we can get the behavior we're looking for without the incomparable flag it sounds like.

**Comment by keith** [comment]
So the downside of using `--noexperimental_generate_json_trace_profile` is that you can't pass this all the time like you can with `--incompatible_enable_profile_by_default=false` unless you want to end up with this warning when you actually want a profile:

```
WARNING: option '--config=trace' (source command line options) was expanded and now overrides the explicit option --noexperimental_generate_json_trace_profile with --experimental_generate_json_trace_profile
```

Any suggestion for how to get the behavior we want without this issue?

**Comment by keith** [comment]
FYI for future viewers this has been disabled (for now?) https://github.com/bazelbuild/bazel/commit/ec3a5624a7d41178aae708c75d6d4a0a21c6093d
