### ISSUE TITLE
Update octal refs in python script

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#999]
Python 2.6+ and 3 don't accept numbers like 0755 as octal literals.
 
See https://groups.google.com/d/msg/bazel-discuss/kjsMdP4YN5E/44twuZ23JAAJ for more info.

**Comment by damienmg** [comment]
work with py 2.7.10, problem with py 3.

**Comment by damienmg** [comment]
Raising priority since it happens for some version of python 2
