### ISSUE TITLE
Support BAZEL_USE_CPP_ONLY_TOOLCHAIN to build bazel itself 

### ISSUE THREAD

**Issue by flokli** [bazelbuild/bazel#9993]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Building bazel for nixpkgs requires patching various paths referring to `/usr/bin/xcrun`, while there is also `BAZEL_USE_CPP_ONLY_TOOLCHAIN`, which should be enough to build bazel itself.

### Feature requests: what underlying problem are you trying to solve with this feature?

Building bazel for MacOS without /usr/bin/xcrun, but another compiler (provided by nix).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Building bazel inside nixpkgs without the `sed` patching at https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/build-managers/bazel/default.nix#L308.

### What operating system are you running Bazel on?

MacOS X

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?
https://github.com/NixOS/nixpkgs/pull/69252#issuecomment-541040021

### Any other information, logs, or outputs that you want to share?

```
Building Bazel from scratch....../usr/bin/xcrun --sdk macosx clang -fobjc-arc -framework CoreServices -framework Foundation -o /private/tmp/nix-build-bazel-1.0.0.drv-0/bazel_s6Mj2C4u/archive/_embedded_binaries/xcode-locator tools/osx/xcode_locator.m
xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.
./bazel_src/scripts/generate_bash_completion.sh: line 71: ./bazel_src/output/bazel: No such file or directory
builder for '/nix/store/lfpcg31ckz5xf8bdygimz41ngc2dfh0h-bazel-1.0.0.drv' failed with exit code 127
```

**Comment by oquenchil** [comment]
It looks like you will have to create a new toolchain if the existing one doesn't support that.
