### ISSUE TITLE
Release 1.0.1 (stable)

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/bazel#9994]
Patch release for 1.0.
Current bugs: #9362

**Comment by dslomov** [comment]
rc1: `scripts/release/release.sh create 1.0.1 9c257df f7a31b3`

**Comment by meteorcloudy** [comment]
Potential release blocker for 1.0.1: https://github.com/bazelbuild/bazel/issues/9995

**Comment by philwo** [comment]
@meteorcloudy Can we use culprit finder to find the culprit here?

**Comment by meteorcloudy** [comment]
I don't think so, because Bazelisk cannot point to a local Bazel binary yet. But I'm doing a local bisect.

**Comment by philwo** [comment]
> Bazelisk cannot point to a local Bazel binary yet

Done: https://github.com/bazelbuild/bazelisk/pull/93 😀

**Comment by meteorcloudy** [comment]
@dslomov Please cherry-pick https://github.com/bazelbuild/bazel/commit/618e5a28f7f735c37724377b15775a4975349c74 to fix https://github.com/bazelbuild/bazel/issues/9995

**Comment by dslomov** [comment]
rc1 is out: https://releases.bazel.build/1.0.1/rc1/index.html 
Now working on rc2.

**Comment by dslomov** [comment]
rc2: `scripts/release/release.sh create 1.0.1 9c257df f7a31b3 618e5a2`

**Comment by dslomov** [comment]
rc2 is out: https://releases.bazel.build/1.0.1/rc2/index.html
Downstream projects: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1233

**Comment by meteorcloudy** [comment]
Please replace 618e5a2 with https://github.com/bazelbuild/bazel/commit/3a43b095b57bf0f93adc30098f9b921c27743a18 for fixing #9995, the previous fix was reported to be problematic internally.

**Comment by dslomov** [comment]
rc2 looks good, modulo some rules_swift issues.
@meteorcloudy do we *need* to replace 618e5a2 with 3a43b09, or are we good to go with rc2?

**Comment by jayconrod** [comment]
Any ETA on this release? Sorry to be impatient; rules_go CI has been broken on Windows by #9995 since last Friday, and it would be good to get it green again.

**Comment by meteorcloudy** [comment]
I can confirm rules_swift@HEAD also breaks with Bazel@1.0.0, still bisecting the breaking change.

**Comment by meteorcloudy** [comment]
The reason https://buildkite.com/bazel/rules-swift-swift is green is because https://github.com/bazelbuild/rules_swift/commit/1e6557b09841a360d6e3a247d73746bd0c0d337d, where testing with Bazel@1.0.0 was removed.

**Comment by meteorcloudy** [comment]
The rules_closure commit that actually caused the breakage is https://github.com/bazelbuild/rules_swift/commit/ec3ce441e4a4ccac4b2b16c3f3d8bd0e85255cfc

**Comment by meteorcloudy** [comment]
@oquenchil Does `cc_common.link` have any bug fix that not included in 1.0.0? I suppose it's https://github.com/bazelbuild/bazel/commit/268268833110b2cf2f2dfcc4fb51f1b06cf9b2a3?

**Comment by meteorcloudy** [comment]
FYI @hlopko

**Comment by meteorcloudy** [comment]
@dslomov OK, I can confirm bazelbuild/rules_swift@ec3ce44 caused the breakage with 1.0 and 2682688 is the fix. I'll leave the decision to you and @hlopko whether we should do a cherry-pick.

**Comment by hlopko** [comment]
CC @allevato 

IMHO the question is if rules_swift need to work with 1.0, they do work with 1.1.

If they need to work with 1.0, two ways forward are to either rollback https://github.com/bazelbuild/rules_swift/commit/ec3ce44 or cherrypick https://github.com/bazelbuild/bazel/commit/268268833110b2cf2f2dfcc4fb51f1b06cf9b2a3 to 1.0 branch.

FTR, rules_swift are not in the federation.

**Comment by allevato** [comment]
Due to resource constraints, the teams maintaining rules_{apple,swift} and apple_support no longer test our master branches against the latest Bazel release, only against the latest green build at HEAD (we removed all but the latter from our Buildkite pipelines), and we are no longer cutting versioned releases.

The latest releases of those repositories are known to be compatible with Bazel 1.0 (and presumably 1.0.1). After that, our recommendation is for users depending on us to pin to a specific commit of our repositories that is compatible with the version of Bazel that they're using.

**Comment by thomasvl** [comment]
From a semantic versioning pov, shouldn't all 1.x bazel releases be tested against the rule set _releases_ (not _HEAD_) because that's how you help ensure you didn't make a breaking change?

**Comment by dslomov** [comment]
If rules_swift decide to break compatibility with 1.0, it is up to them. We are not cherry-picking 2682688.

**Comment by dslomov** [comment]
Will promote 1.0.1rc2 to release today.

**Comment by Kernald** [comment]
It has been promoted (at least the release is tagged [there](https://github.com/bazelbuild/bazel/releases/tag/1.0.1)), but not builds got uploaded - is it intended?

**Comment by dslomov** [comment]
1.0.1 is released: https://github.com/bazelbuild/bazel/releases/tag/1.0.1
Pinging package maintainers @vbatts @petemounce @excitoon (we recommend people to upgrade to 1.1, it is up to you whether you want to provide a package for 1.0.1 as well).

@jin do we need to create a 1.0.1 documentation version? (there are no documentation cherrypicks and our history is inconsistent)

**Comment by vbatts** [comment]
On 22/10/19 00:34 -0700, Dmitry Lomov wrote:
>   1.0.1 is released:
>   [1]https://github.com/bazelbuild/bazel/releases/tag/1.0.1
>   Pinging package maintainers [2]@vbatts [3]@petemounce [4]@excitoon (we
>   recommend people to upgrade to 1.1, it is up to you whether you want to
>   provide a package for 1.0.1 as well).
>
>   [5]@jin do we need to create a 1.0.1 documentation version? (there are
>   no documentation cherrypicks and our history is inconsistent)

Rather than doing a new RPM build for this release, I have just created
a non-branched tag.
https://github.com/vbatts/copr-build-bazel/releases/tag/v1.0.1-1
Those interested can git clone; checkout; `make rpm` for themselves.

**Comment by jin** [comment]
@dslomov we don't usually make documentation releases for patch versions, unless there were cherrypicks that change the documentation.

**Comment by petemounce** [comment]
Gonna be a latency for chocolatey release; I'm in China until November.
