### ISSUE TITLE
toolchain resolution should take into account `no-remote` tags.

### ISSUE THREAD

**Issue by cphang99** [bazelbuild/bazel#9996]
### Description of the problem / feature request:

This affects cross-platform builds (e.g. host is windows, remote-workers are linux) involving remote-execution that utilise platforms and toolchains.

If a test target is tagged as `no-remote` or `no-remote-exec`, toolchain resolution does not take this into account and determine that the execution constraints should be modified to be that of the host platform. If this is not done, a different toolchain can be selected that is incompatible and causes builds to fail.

In the case of cross-platform builds, a workaround is to manually set the execution constraints in the test target with `exec_compatible_with` to that of the host platform. Ideally however, this should be automatically detected during toolchain resolution.

### What operating system are you running Bazel on?

macOS 

### What's the output of `bazel info release`?

0.29.1

**Comment by katre** [comment]
@aragos, this sounds like something that should be handled by your latest project.

**Comment by katre** [comment]
This is now my project.

**Comment by katre** [comment]
Closing this in favor of the canonical tracking issue for execution platforms and strategies, https://github.com/bazelbuild/bazel/issues/11432.
