### ISSUE TITLE
Bazel Developer GPG Key is Expired

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#9997]
```
$ gpg --verify bazel-1.0.0-linux-x86_64.sig bazel-1.0.0-linux-x86_64
gpg: Signature made Do 10 Okt 2019 12:28:08 CEST
gpg:                using RSA key 71A1D0EFCFEB6281FD0437C93D5919B448457EE0
gpg: Good signature from "Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 71A1 D0EF CFEB 6281 FD04  37C9 3D59 19B4 4845 7EE0
```

**Comment by ulfjack** [comment]
IIUC, the key expired on 2018-05-24.

**Comment by aehlig** [comment]
> IIUC, the key expired on 2018-05-24.

The key's validity was extended to 2020-05-23.
Could you try `gpg --recv-keys 71A1D0EFCFEB6281FD0437C93D5919B448457EE0` to fetch
the extension of the key's life time?

Thanks.


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by ulfjack** [comment]
I get this error message on MacOS:
```
gpg: key 3D5919B448457EE0: new key but contains no user ID - skipped
```

**Comment by ulfjack** [comment]
Getting it from the Ubuntu Keyserver worked:
gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys71A1D0EFCFEB6281FD0437C93D5919B448457EE0

However, I still get this message:
gpg: WARNING: This key is not certified with a trusted signature!

I suppose that's working as expected?

**Comment by csdexter** [comment]
Today is May 23rd 2020 and they key expired once again. Please have a look at the key/repository at your earliest convenience.

**Comment by AndyB66** [comment]
> The key's validity was extended to 2020-05-23. 
Now what?

**Comment by jin** [comment]
Please follow updates at https://github.com/bazelbuild/bazel/issues/11470

**Comment by bharrisaurora** [comment]
Yet again the key expired... May 23 2022

**Comment by meteorcloudy** [comment]
The issue has been resolved at in https://github.com/bazelbuild/bazel/issues/15558
